In [1]:
import pandas as pd
import numpy as np
import json
from rdkit import Chem
from rdkit.Chem import Draw
from rdkit.Chem import rdChemReactions
from rdkit.Chem.Draw import rdMolDraw2D
from rdkit.Chem.Draw import IPythonConsole
from IPython.display import SVG, display
from rdkit.Chem.Fingerprints import FingerprintMols
from rdkit import DataStructs
from rdkit.Chem import MACCSkeys
from rdkit.Chem import AllChem
import pandas as pd
import rdchiral
import itertools
import pickle
import sys
from tqdm import tqdm 
from rdchiral.main import rdchiralRun, rdchiralRunText, rdchiralReaction, rdchiralReactants
import cobra
from itertools import chain, combinations
import sys
import multiprocessing
from functools import partial
import matplotlib.pyplot as plt
import multiprocessing
from tqdm import tqdm
sys.path.append('../')

from common import *

### input and output

In [2]:
# step1
#input
mnxreac_smile_atom_mapping_rules_file_path = '../../Data/retrosynthesis/MNXreaction_smiles_atommap_rules_filter_0.2.csv'
mnxreac_smile_atom_mapping_rules_file_path = '/home/wuke/project/microbiome–drug/Results/MNXreaction_smiles_atommap_rules_filter_0.2.csv'
target_drug_path = '../../Data/Drug/drug_Zimmermann_2019.xlsx'

###output

In [3]:
def process_rule(rule_smiles, mets_total_smiles):
    score = []
    smiles = []
    if 'C' in rule_smiles or 'c' in rule_smiles:
        for j in mets_total_smiles:
            current_score = calculate_similarity(rule_smiles, j)
            if current_score > 0.3:               ########################################################################
                score.append(current_score)
                smiles.append(j)
    else:
        smiles.append(rule_smiles)
        score.append(1)

    if len(score) == 0:
        return rule_smiles, [], []
    elif len(score) > 50:
        top40_data = sorted(zip(score, smiles), reverse=True)[:50]
    else:
        top40_data = sorted(zip(score, smiles), reverse=True)
    
    top40_scores, top40_smiles = zip(*top40_data)
    
    return rule_smiles, list(top40_smiles), list(top40_scores)

####################################################################################

def count_carbons(smiles):
    """计算一个 SMILES 字符串中碳 (C) 的个数"""
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return 0
    return sum(1 for atom in mol.GetAtoms() if atom.GetSymbol() == 'C')


# def process_rule(rule_smiles, mets_total_smiles):
#     score = []
#     smiles = []
    
#     # 计算 rule_smiles 的碳原子数
#     rule_c_count = count_carbons(rule_smiles)

#     if 'C' in rule_smiles or 'c' in rule_smiles:
#         for j in mets_total_smiles:
#             # 计算当前代谢物的碳原子数
#             j_c_count = count_carbons(j)
            
#             # 计算相似度
#             current_score = calculate_similarity(rule_smiles, j)
            
#             # 计算罚分
#             if rule_c_count!=0:
#                 if rule_c_count > j_c_count:
#                     penalty = (rule_c_count - j_c_count) / (rule_c_count) /10.216
#                 elif rule_c_count < j_c_count:
#                     penalty = (j_c_count - rule_c_count) / (rule_c_count) /8.828
#                 else:
#                     penalty = 0
#             else:
#                 penalty = 0
            
#             # 应用罚分
#             adjusted_score = max(0, current_score - penalty)

#             # 仅保留相似度大于0.3的结果
#             if adjusted_score > -5:
#                 score.append(adjusted_score)
#                 smiles.append(j)
    
#     else:
#         smiles.append(rule_smiles)
#         score.append(1)

#     if len(score) == 0:
#         return rule_smiles, [], []
#     # elif len(score) > 100:
#     #     top20_data = sorted(zip(score, smiles), reverse=True)[:100]
#     else:
#         top20_data = sorted(zip(score, smiles), reverse=True)
    
#     top20_scores, top20_smiles = zip(*top20_data)
    
#     return rule_smiles, list(top20_smiles), list(top20_scores)

# def process_rule(rule_smiles, mets_total_smiles):
#     score = []
#     smiles = []
    
#     # 计算 rule_smiles 的碳原子数
#     rule_c_count = count_carbons(rule_smiles)

#     if 'C' in rule_smiles or 'c' in rule_smiles:
#         for j in mets_total_smiles:
#             # 计算当前代谢物的碳原子数
#             j_c_count = count_carbons(j)
            
#             # 计算相似度
#             current_score = calculate_similarity(rule_smiles, j)
# # 最小满足条件的 N: 21.8108108108, M: 2.4864864865
#             # 计算罚分
#             if rule_c_count!=0:
#                 if rule_c_count > j_c_count:
#                     penalty = (rule_c_count - j_c_count) / (rule_c_count) /2.4864864865
#                 elif rule_c_count < j_c_count:
#                     penalty = (j_c_count - rule_c_count) / (rule_c_count) /21.8108108108
#                 else:
#                     penalty = 0
#             else:
#                 penalty = 0
            
#             # 应用罚分
#             adjusted_score = max(0, current_score - penalty)

#             # 仅保留相似度大于0.3的结果
#             if adjusted_score > 0.1:
#                 score.append(adjusted_score)
#                 smiles.append(j)
    
#     else:
#         smiles.append(rule_smiles)
#         score.append(1)

#     if len(score) == 0:
#         return rule_smiles, [], []
#     # elif len(score) > 20:
#         # top20_data = sorted(zip(score, smiles), reverse=True)[:20]
#     else:
#         top20_data = sorted(zip(score, smiles), reverse=True)
    
#     top20_scores, top20_smiles = zip(*top20_data)
    
#     return rule_smiles, list(top20_smiles), list(top20_scores)

In [4]:
# for index,row in retrosys_smiles_calculate_similarity_pd.iterrows():
#     if row['rules_smiles'] not in row['smiles_in_mets_total_smiles']:
#         retrosys_smiles_calculate_similarity_pd.loc[index,'smiles_in_mets_total_smiles'] = row['smiles_in_mets_total_smiles'].append(row['rules_smiles'])

In [5]:
def process_retrorule(index_row, mets_total_smiles,retrosys_smiles_calculate_similarity_pd,heterologous_met_smiles):
    rxndb_list_tmp = []
    # newdbSmiles_tmp = []
    failedrxn_tmp = []
    index, row = index_row
    rxn_id, ECnumber, reactants, products = row['MNX_ID'], row['classifs'], row['substrate_smiles'], row['product_smiles']
    deprecated_equ_smiles, reactantSMARTs, productSMARTs, rule = row['deprecated_equ_smiles'], row['ReactantsSMARTs'], row['ProductSMARTs'], row['RetroRules']
    deprecated_equ_smiles = deprecated_equ_smiles.split('>>')
    if rxn_id not in ['MNXR101882', 'MNXR101884', 'MNXR101879', 'MNXR101885', 'MNXR101886', 'MNXR101887',
                        'MNXR103528', 'MNXR103575']:  # ATP NADH conversion stuff
        productSMARTs = productSMARTs.split('.')
        products = products.split('.')
        new_products_smiles = []
        scores = []
        
        if len(productSMARTs) == len(products):
            for x in range(len(productSMARTs)):  # prepare mets with substructure and sort the reactants combination
                new_products_smile_one,score_one = get_calculate_similarity(products[x],retrosys_smiles_calculate_similarity_pd)
                new_products_smiles.append(new_products_smile_one)
                scores.append(score_one)

            product_prepared = []
            scores_prepared = []
            for lst, score_lst in zip(new_products_smiles, scores):
                if heterologous_met_smiles in lst:
                    if len(new_products_smiles) == 1:  # if only one sub list
                        product_prepared.append([heterologous_met_smiles])
                        scores_prepared.append(score_lst)
                    else:
                        other_lists = [sub_lst for sub_lst in new_products_smiles if sub_lst != lst]
                        tmp_product = list(itertools.product([heterologous_met_smiles], *other_lists))
                        product_prepared += tmp_product

                        tmp_scores = list(itertools.product([score_lst[new_products_smiles.index(lst)]], *scores))
                        scores_prepared += tmp_scores
            # print('product_prepared',product_prepared,len(product_prepared))
            for m in range(0, len(product_prepared)):  # apply the rule and output the rxn
                smile = product_prepared[m]
                score = scores_prepared[m]
                
                if len(smile) > 1:
                    product_smile = '.'.join(smile)
                else:
                    product_smile = smile[0]

                retrorule_tmp = rule.split('>>')
                retrorule_tmp = '(' + retrorule_tmp[0] + ')>>' + '(' + retrorule_tmp[1] + ')'            
                product_smile_tmp = product_smile
                # print('retrorule_tmp',retrorule_tmp)
                # print('product_smile',product_smile)
                try:
                    # print('product_smile_tmp',product_smile_tmp)
                    product_mol = Chem.MolFromSmiles(product_smile_tmp)
                    reaction = AllChem.ReactionFromSmarts(retrorule_tmp)
                    reactant_smiles = reaction.RunReactants((product_mol,))
                    smiles = [Chem.MolToSmiles(x[0]) for x in reactant_smiles]
                    reactant_smiles = list(set(smiles))

                    for reactant_smile in reactant_smiles:
                        if len(deprecated_equ_smiles) > 0:
                            if deprecated_equ_smiles[0] == '':
                                reactant_smile_final = reactant_smile
                            else:
                                reactant_smile_final = reactant_smile + '.' + deprecated_equ_smiles[0]
                            if deprecated_equ_smiles[1] == '':
                                product_smile_final = product_smile_tmp
                            else:
                                product_smile_final = product_smile_tmp + '.' + deprecated_equ_smiles[1]
                        rxn_smiles = reactant_smile + '>>' + product_smile_tmp
                        rxn_smiles_final = reactant_smile_final + '>>' + product_smile_final
                        
                        tmp = {
                            'EC number': ECnumber,
                            'rule': rule,
                            'templateID': rxn_id,
                            'templateSubstrate': products,
                            'rxn_smiles_basic': rxn_smiles,
                            'rxn_smiles_final': rxn_smiles_final,
                            'reactant_smile': reactant_smile,
                            'productsmile': product_smile_tmp,
                            'similarity': score
                        }
                        if check_rule(tmp['rxn_smiles_basic'])=='blance':
                            rxndb_list_tmp.append(tmp)  
                            # mets_tmp = reactant_smile.split('.')      
                            # for reactant in mets_tmp:             
                            #     if reactant not in mets_total_smiles and reactant not in newdbSmiles_tmp:         
                            #         newdbSmiles_tmp.append(reactant)        
                except:
                    failedrxn_tmp.append(rxn_id)
                
    return(rxndb_list_tmp,failedrxn_tmp)

In [6]:
def process_ec_list(ec_list,topn):
    processed_set = set()
    
    for ec in ec_list:
        for sub_ec in ec.split(';'):
            parts = sub_ec.strip().split('.')
            if len(parts) >= 3:  # Only process EC numbers with at least 3 parts
                processed_set.add('.'.join(parts[:topn]))
    
    return list(processed_set)

# Example usage
input_ec_numbers = ['4.1.3.-', '3.1.3.1', '1.1.3.100;2.1.4.2']
output_ec_numbers = process_ec_list(input_ec_numbers,3)
print(output_ec_numbers)

['3.1.3', '2.1.4', '4.1.3', '1.1.3']

In [7]:
def check_productsmile(smiles):#only keep smiles with carbon
    smiles_lst = smiles.split('.')
    smiles_lst = [x for x in smiles_lst if smiles_has_carbon(x)]
    return len(smiles_lst)

In [8]:
rules_product_smiles_lst = []
retrorules = pd.read_csv(mnxreac_smile_atom_mapping_rules_file_path)
# retrorules = retrorules[retrorules['MNX_ID'].str.contains('MNXR97814')]
for index,row in retrorules.iterrows():
    tmp  = row['product_smiles'].split('.')
    for i in tmp:
        if i not in rules_product_smiles_lst:
            rules_product_smiles_lst.append(i)
print('rules_product_smiles_lst',len(rules_product_smiles_lst))

rules_product_smiles_lst 11047

In [9]:
target_drug = pd.read_excel(target_drug_path)
target_drug.rename(columns={'MOLENAME':'drug_name','SMILES':'drug_smiles'},inplace=True)
target_drug['drug_smiles'] = target_drug['drug_smiles'].apply(lambda x:x.replace('.Cl','').replace('.[Na+]',''))
target_drug = target_drug[['drug_name','drug_smiles']]
target_drug = target_drug[target_drug['drug_smiles'].apply(lambda x:normalize_smiles(x)!=None)]
target_drug

                drug_name                                        drug_smiles
0        ABACAVIR SULFATE               Nc1nc(NC2CC2)c2ncn(C3C=CC(CO)C3)c2n1
1              ACEBUTOLOL      CCCC(=O)Nc1ccc(OCC(O)C[NH2+]C(C)C)c(C(C)=O)c1
2              ACECAINIDE               CC[NH+](CC)CCNC(=O)c1ccc(NC(C)=O)cc1
3               ALFUZOSIN        COc1cc2nc(N(C)CCCNC(=O)C3CCCO3)nc(N)c2cc1OC
4             ALMOTRIPTAN     C[NH+](C)CCc1c[nH]c2ccc(CS(=O)(=O)N3CCCC3)cc12
..                    ...                                                ...
266              WARFARIN           CC(=O)CC(c1ccccc1)c1c([O-])c2ccccc2oc1=O
267              ZALEPLON           CCN(C(C)=O)c1cccc(-c2ccnc3c(C#N)cnn23)c1
268      ZIDOVUDINE [AZT]       Cc1cn(C2CC(N=[N+]=[N-])C(CO)O2)c(=O)[nH]c1=O
269  ZIPRASIDONE MESYLATE  O=C1Cc2cc(CC[NH+]3CCN(c4nsc5ccccc45)CC3)c(Cl)c...
270              ZOLPIDEM            Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1

[271 rows x 2 columns]

In [10]:
# 读取gut clean ec预测结果
with open('../../Results/AGORA2_strain_eclist_top3_common.pkl', 'rb') as f:
    loaded_top3 = pickle.load(f)

with open('../../Results/AGORA2_strain_eclist_top4_common.pkl', 'rb') as f:
    loaded_top4 = pickle.load(f)

print("读取完成！")
print(f"Top3 列表长度：{len(loaded_top3)}")
print(f"Top4 列表长度：{len(loaded_top4)}")

读取完成！
Top3 列表长度：70
Top4 列表长度：35

## byproduct prediction

In [11]:
result_num = {'drug_name':[],
              'reaction_num':[],
              'ec4_num':[],
              'ec4_list':[],
              'ec3_num':[],
              'ec3_list':[],
            #   'success_predict':[],
            #   'success_ecnumber':[],
              }
# filter_info = {'drug_carbon':[],
#                'success_carbon':[],
#                'error_carbon':[],
#                'success_sim_score':[],
#                'error_sim_score':[],
#                }

for index,row in tqdm(target_drug.iterrows(),total=len(target_drug)):
    print(row['drug_name'])
    heterologous_met_smiles = row['drug_smiles']
    # heterologous_met_smiles = 'FC1=CNC(=O)NC1=O'
    # heterologous_met_smiles = 'N[C@@H](CC1=CC(O)=C(O)C=C1)C(O)=O'
    # heterologous_met_smiles = '[NH3+][C@@H](Cc1ccc(O)c(O)c1)C(=O)[O-]' ######## L-dopa
    heterologous_met_smiles = normalize_smiles(heterologous_met_smiles)
    # model_met = target_drug['smiles'].to_list()
    model_met = [heterologous_met_smiles,heterologous_met_smiles,heterologous_met_smiles,'O=C([O-])CCC(=O)C(=O)[O-]']
    new_met = []

    # add heterologous_met_smiles to model_met list
    new_model_and_heterologous_met = model_met + new_met
    new_model_and_heterologous_met.append(heterologous_met_smiles)
    new_model_and_heterologous_met = [smile for smile in new_model_and_heterologous_met if '.' not in smile]
    new_model_and_heterologous_met = [smile for smile in new_model_and_heterologous_met if 'C' in smile or 'c' in smile] ###只筛第一轮
    print(len(new_model_and_heterologous_met))
    #calculate similarity
    num_processes = 100
    pool = multiprocessing.Pool(num_processes)
    retrosys_smiles_calculate_similarity = {'rules_smiles': [],
                                            'smiles_in_mets_total_smiles': [],
                                            'scores': []}


    process_rule_partial = partial(process_rule, mets_total_smiles=new_model_and_heterologous_met)
    for result in tqdm(pool.imap(process_rule_partial, rules_product_smiles_lst, chunksize=100), total=len(rules_product_smiles_lst)):
        if result[0] not in retrosys_smiles_calculate_similarity['rules_smiles']:
            retrosys_smiles_calculate_similarity['rules_smiles'].append(result[0]) 
            retrosys_smiles_calculate_similarity['smiles_in_mets_total_smiles'].append(result[1]) 
            retrosys_smiles_calculate_similarity['scores'].append(result[2]) 
    pool.close()
    pool.join()

    retrosys_smiles_calculate_similarity_pd = pd.DataFrame(retrosys_smiles_calculate_similarity)
    
##############################################
    # for index4, row4 in retrosys_smiles_calculate_similarity_pd.iterrows():
    #     if row4['rules_smiles'] not in row4['smiles_in_mets_total_smiles']:
    #         # 修改 DataFrame 中嵌套的列表
    #         retrosys_smiles_calculate_similarity_pd.at[index4, 'smiles_in_mets_total_smiles'].append(row4['rules_smiles'])
##############################################
    rxndb_list = [] 
    # newdbSmiles = []
    failedrxn = []
    num_processes =100  #  adjust the number of processes according to your needs
    pool = multiprocessing.Pool(num_processes)
    # Execute in parallel using process pool

    # Create a partial function that passes mets_total_smiles and mets_total_mol as default parameters to the process_retrorule function
    process_retrorule_partial = partial(process_retrorule, mets_total_smiles=new_model_and_heterologous_met,retrosys_smiles_calculate_similarity_pd = retrosys_smiles_calculate_similarity_pd,heterologous_met_smiles = heterologous_met_smiles)

    # Using the process pool to execute in parallel, the chunksize parameter is placed inside the imap function.
    for result in tqdm(pool.imap(process_retrorule_partial, retrorules.iterrows(), chunksize=100), total=len(retrorules)):
        # if result == ([], [], []):
        #     pass
        # else:
        #     print(result)
        if result[0] :  #  check if the result is not empty
            rxndb_list.extend(result[0]) 
        # if result[1] is not None:
        #     newdbSmiles.extend(result[1])
        if result[1]:
            failedrxn.extend(result[1])  

    pool.close()
    pool.join()

    rxndb = {}
    for i, rxn_dict in enumerate(rxndb_list):
        # generate a unique key for each reaction, for example "rxn0"，"rxn1"，"rxn2"，...
        key = f'rxn{i+1}'
        # merge to the dictionary
        rxndb[key] = rxn_dict
    # with open(rxndb_path, 'w') as json_file:
    #     json.dump(rxndb, json_file)

    # with open(rxndb_path, 'r') as f:
    #     rxndb = json.load(f)
    print('rxndb num',len(rxndb))
    print('failedrxn num',len(failedrxn))

    ecnumber_list = []
    for _,x in rxndb.items():
        ec_list = x['EC number'].split(';')
        ec_list = process_ec_list(ec_list,3)
        ecnumber_list += ec_list

    ecnumber_list = list(set(ecnumber_list))   
    result_df = {'ID':[],
            'reactant_smile':[],
            'productsmile':[],
            'rxn_smiles_basic':[],
            'templateID':[],
            'EC number':[],}

    for k,v in rxndb.items():
        result_df['ID'].append(k)
        result_df['reactant_smile'].append(v['reactant_smile'])
        result_df['productsmile'].append(v['productsmile'])
        result_df['rxn_smiles_basic'].append(v['rxn_smiles_basic'])
        result_df['templateID'].append(v['templateID'])
        result_df['EC number'].append(v['EC number'])

    result_df = pd.DataFrame({'ID': result_df['ID'],
                        'reactant_smile': result_df['reactant_smile'],
                        'productsmile': result_df['productsmile'],
                        'rxn_smiles_basic': result_df['rxn_smiles_basic'],
                        'templateID': result_df['templateID'],
                        'EC number': result_df['EC number'],
                        })

    result_df.drop_duplicates(subset=['reactant_smile', 'productsmile'], inplace=True)
    result_df.reset_index(drop=True, inplace=True)

    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.OO']
    result_df = result_df[result_df['productsmile']!='OO.'+ heterologous_met_smiles]
    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.O=C=O']
    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.O=S([O-])[O-]']
    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.[SH-]']
    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.O=P([O-])([O-])OP(=O)([O-])O']
    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.II']
    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.[NH4+]']
    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.[Br-]']

    result_df['productsmile_num'] = result_df['productsmile'].apply(lambda x: check_productsmile(x))
    result_df = result_df[result_df['productsmile_num']==1]


    # error_ec = ['1.2.1', '1.14.13', '1.14.14', '1.1.1', '3.1.3' ,'1.21.1','1.22.1','1.1.1','3.1.6'] #1.10.3#3.1.6
    error_ec = []
    # 过滤 DataFrame，使得 "EC number" 列中的每个 EC 号都属于 error_ec
    result_df['EC number'] = result_df['EC number'].apply(lambda x:x.split(';'))
    result_df = result_df[~result_df['EC number'].apply(lambda ec_list: all('.'.join(x.split('.')[0:3]) in error_ec for x in ec_list))]
    result_df['EC number'] = result_df['EC number'].apply(lambda x:';'.join(x))
    
    # gut_common_ec_list_top3 = loaded_top3
    # result_df['EC number'] = result_df['EC number'].apply(lambda x:x.split(';'))
    # result_df = result_df[~result_df['EC number'].apply(lambda ec_list: any('.'.join(x.split('.')[0:3]) in gut_common_ec_list_top3 for x in ec_list))]
    # result_df['EC number'] = result_df['EC number'].apply(lambda x:';'.join(x))    

    try:
        res = result_df['reactant_smile'].to_list()
        ec_lst = []
        for k,v in rxndb.items():
            if v['reactant_smile'] in res:
                ec_lst.append(v['EC number'])
    except:
        ec_lst = []
        pass
    # print(row['name'],len(result_df))
    # print(row['name'],ec_lst)
    print('result_df',len(result_df))
    print(ec_lst)
    ec_lst_4 = process_ec_list(ec_lst,4)
    ec_lst_3 = process_ec_list(ec_lst,3)
    print(len(ec_lst_3))
    print(len(ec_lst_4))
    
    result_num['drug_name'].append(row['drug_name'])
    result_num['reaction_num'].append(len(result_df))
    result_num['ec4_num'].append(len(ec_lst_4))
    result_num['ec4_list'].append(str(ec_lst_4))
    result_num['ec3_num'].append(len(ec_lst_3))
    result_num['ec3_list'].append(str(ec_lst_3))
    
    # success_predict = 0
    # success_ecnumber = []
    # success_ID = []
    # if row['product_smiles'] != 'unknown' and row['drug_name'] != 'Lactulose':
    #     target_smiles = row['product_smiles'].split('.')[0]
    #     for index2,row2 in result_df.iterrows():
    #         smiles_list = row2['reactant_smile'].split('.')
    #         if any(compare_smiles_inchikey(smiles,target_smiles) for smiles in smiles_list):
    #             success_predict =1
    #             success_ID.append(row2['ID'])
    #             tmp_ec_lst = row2['EC number'].split(';')
    #             success_ecnumber+=process_ec_list(tmp_ec_lst,3)
    
    # result_num['success_predict'].append(success_predict)
    # result_num['success_ecnumber'].append(str(list(set(success_ecnumber))))
    
    
    # drug_carbon = calculate_carbon_count(heterologous_met_smiles)
    # success_sim_score = []
    # success_carbon = []
    # error_carbon = []
    # error_sim_score = []
    # # for tmpid,tmp_result in rxndb.items():
    # #     if tmpid in result_df['ID']:
    # for index3,row3 in result_df.iterrows():
    #     if row3['ID'] in success_ID:
    #         success_sim_score.append(min(rxndb[row3['ID']]['similarity']))
    #         success_carbon.append(max(calculate_carbon_count(tmp_smiles) for tmp_smiles in rxndb[row3['ID']]['templateSubstrate']))
    #     else:
    #         error_sim_score.append(min(rxndb[row3['ID']]['similarity']))
    #         error_carbon.append(max(calculate_carbon_count(tmp_smiles) for tmp_smiles in rxndb[row3['ID']]['templateSubstrate']))

    # filter_info['drug_carbon'].append(drug_carbon)
    # filter_info['success_carbon'].append(success_carbon)
    # filter_info['error_carbon'].append(error_carbon)
    # filter_info['success_sim_score'].append(success_sim_score)
    # filter_info['error_sim_score'].append(error_sim_score)
    
    # # 保存结果
    # # 保存 drug_degration_ec 到 JSON 文件
    # drug_degration_ec_path = os.path.join(output_dir, 'drug_degration_ec.json')
    # with open(drug_degration_ec_path, 'w') as json_file:
    #     json.dump(drug_degration_ec, json_file, indent=4)

    # # 保存 result_df 到 CSV 文件
    # result_df_path = os.path.join(output_dir, 'result_df.csv')
    # # 保存结果时，使用追加模式（mode='a'）
    # result_df.to_csv(result_df_path, index=False, mode='a', header=not os.path.exists(result_df_path))

  0%|          | 0/271 [00:00<?, ?it/s]

ABACAVIR SULFATE
5

100%|██████████| 11047/11047 [00:04<00:00, 2583.97it/s]
100%|██████████| 27873/27873 [00:05<00:00, 5046.21it/s]
  0%|          | 1/271 [00:12<54:59, 12.22s/it]

rxndb num 152
failedrxn num 0
result_df 30
['1.1.1.23', '3.1.3.15', '1.1.1.3', '1.1.1.3', '3.1.3.74', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '3.1.3.74', '1.1.1.1', '3.1.3.73', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.1.3.23', '3.1.3.39', '1.1.1.191;1.1.1.2;1.1.1.21', '3.5.4.11', '3.8.1.8', '3.5.4.-', '1.14.13.-', '1.1.1.1', '1.1.1.1', '3.1.3.-;3.1.3.88', '3.5.4.-;3.5.4.26', '3.5.4.-;3.5.4.26', '3.5.4.32', '1.14.13.-', '3.1.3.92', '1.14.13;1.14.13.-', '1.14.13.-', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.3.3', '3.1.3', '3.1.3;3.1.3.-', '1.7.1;1.7.1.-', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '3.5.4.3', '3.5.4.3', '1.14.13', '1.14.13', '1.1.1', '1.1.1.1', '1.17.1.4', '3.1.3.33;3.1.3.5', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3', '3.8.1.7', '3.8.1.8', '3.8.1.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.5.4.-;3.5.99.-', '3.5.4.42;3.5.99.4', '3.5.4.45;3.5.99.-', '3.5.4.-', '3.1.3.91', '3.6.1;3.6.1.-', '1.14.14.1', '3.1.3.2;3.1.3.31;3.1.3.34', '3.5.4.3', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.1.1.204;1.17.1.4', '1.17.3.2', '1.1.1.23', '2.-.-.-', '1.1.1.273', '1.1.1.273', '1.1.1.273', '1.1.1.317', '1.1.1.317', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.5.4.11;3.5.4.24', '3.1.3.M8', '1.1.1.273', '3.5.4.11', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.2;3.1.3.5', '1.6.6.8;1.7.1.7', '6.3.4.1;6.3.5.2', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.5.4.15', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '1.1.1.1;1.1.1.190', '3.1.3.-;3.1.3.104']
22
74
ACEBUTOLOL
5

100%|██████████| 11047/11047 [00:03<00:00, 3385.95it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3313.59it/s]
  1%|          | 2/271 [00:27<1:01:36, 13.74s/it]

rxndb num 1365
failedrxn num 0
result_df 74

100%|██████████| 11047/11047 [00:02<00:00, 4513.23it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4331.89it/s]
  1%|          | 3/271 [00:38<56:34, 12.67s/it]

rxndb num 97
failedrxn num 0
result_df 21
['1.14.13.9', '1.14.13.9', '3.1.1.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.5.1.40', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.7.1.12', '1.7.1.12', '3.4.22.40;3.5.1.72', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.11.2.5', '1.11.2.5', '6.3.1.18', '1.14.13.209', '1.14.13.209', '3.5.1.123', '1.14.13', '1.14.13', '1.14.13', '3.5.1', '3.4.11.3;3.4.11.6;3.4.22.40', '2.3.2.2;3.4.11.10;3.4.19.3', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '3.4.21.4;3.4.22;3.4.22.1', '3.1.1.3', '3.3.2.6;3.4.11.10;3.4.11.15', '3.1.1;3.1.1.3', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '3.4.11.5', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '1.14.14.1', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.18.2', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.4.15.6', '3.4.15.6', '3.4.19.7', '3.4.19.7', '3.2.1.-', '3.2.1.-', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.5.1', '1.14.18.2', '1.1.1;1.1.1.206']
23
53
ALFUZOSIN
5

100%|██████████| 11047/11047 [00:02<00:00, 3825.85it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4082.28it/s]
  1%|▏         | 4/271 [00:50<56:10, 12.62s/it]

rxndb num 717
failedrxn num 0
result_df 64
['3.5.1.94', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.5.4.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '6.3.2.1', '3.5.1.92', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '3.5.1.22', '6.3.2.23', '6.3.1.2;6.3.1.6', '3.5.1.65', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '6.3.2.20', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '3.5.4.23', '3.5.1.24;3.5.1.74', '3.5.1.24', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.5.4.5', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '6.3.2.36', '1.14.19.n5', '1.11.2.5', '1.11.2.5', '3.5.1.-', '6.3.2.44', '6.3.4.24', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '3.3.2.14', '3.3.2.14', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '6.3.2.18', '3.5.4.20', '6.3.2;6.3.2.-', '6.3.2', '6.3.2', '6.3.2', '3.4.11.25', '6.3.2.59', '6.3.2.59', '1.14.13', '1.14.13', '1.3.1', '1.3.1', '3.5.4.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.4.13', '6.3.2', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '1.3.1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2', '3.4', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.3.1', '3.5.1.115', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '1.14.18.1', '1.14.18.1', '3.5.4.5', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '3.5.1.23', '3.5.1.23', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '3.2.1.78', '6.3.2.18', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '3.8.1.8', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.3.1;1.3.1.-', '2.4.1.-', '2.4.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.3.1.11', '3.5.1.-;3.5.1.78', '6.3.1.8;6.3.1.9', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.5.1.4;3.5.1.99', '1.14.14.1', '1.14.14.1', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.5.1.24;3.5.1.74', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '6.3.1.9', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '3.5.1.-', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '6.3.1.13', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.19.41;1.3.1.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '6.3.1.10', '6.3.1.10', '3.5.1.90', '3.5.1.90', '3.5.4.1', '3.5.4.12', '3.5.4.13', '6.3.2.56;6.3.2.ad', '3.5.1.60;3.5.1.99', '3.5.1.60', '3.5.1.60;3.5.1.99', '3.5.1.99', '3.5.1.99', '3.5.1.60', '1.14.13.9', '1.14.13.9', '3.4', '3.2.1.14', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.4.15.6', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '6.3.2;6.3.2.-', '6.3.2', '3.2.1.143', '3.2.1.143', '3.2.1.143', '6.3.2', '6.3.2', '6.3.2', '6.3.2', '6.3.2.37', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '6.3.4.2', '3.5.4.13', '6.3.1.10', '3.5.4.12', '3.5.4.5', '1.3.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.182', '1.14.13.182', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '6.3.2.58', '6.3.2.58', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '3.5.1.115', '1.1.1;1.1.1.206', '3.5.1.46', '3.5.4.14;3.5.4.5']
34
134
ALMOTRIPTAN
5

100%|██████████| 11047/11047 [00:03<00:00, 3681.43it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3810.27it/s]
  2%|▏         | 5/271 [01:04<56:49, 12.82s/it]

rxndb num 107
failedrxn num 0
result_df 30
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.235', '1.14.13', '1.14.13', '1.14.13.8', '1.14.13', '1.14.13', '1.14.13', '1.13.11.52', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.4.11.5', '3.2.1.35', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '1.13.11.52', '1.13.11.11;1.13.11.52', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.13.11.11;1.13.11.52', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.13.99.3', '1.13.11.52', '1.14.-.-', '1.14.-.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.176', '1.3.99.-', '1.14.13.182', '1.14.13.182', '1.13.99.3', '1.13.11.52', '1.13.11.52']
11
31
ALPRENOLOL
5

100%|██████████| 11047/11047 [00:02<00:00, 4520.58it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3454.51it/s]
  2%|▏         | 6/271 [01:16<56:39, 12.83s/it]

rxndb num 1114
failedrxn num 0
result_df 47
['3.1.3.69', '1.1.1.14;1.1.1.6', '1.1.1.1;1.1.1.10;1.1.1.156;1.1.1.2;1.1.1.21;1.1.1.72;1.3.1.20', '3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.27', '3.1.3.3', '3.1.3;3.1.3.2', '3.1.3.74', '1.5.3.13;1.5.3.17', '1.5.3.13', '1.5.3.13;1.5.3.17', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.6.2', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.1.1;1.1.1.10', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3.2;3.1.3.29;3.1.3.38', '1.1.1.137', '1.1.1.137;1.1.1.405', '1.1.1.69', '3.1.3.22;3.1.3.23', '1.1.1;1.1.1.207', '3.1.3.39', '1.1.1.148', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.3.16', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.1.1;1.1.1.208', '1.14.13.6', '1.14.13.6', '1.14.13.6', '1.14.13.6', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.147', '1.1.1.147', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '3.1.3.40', '1.1.1.143', '1.1.1.142', '3.1.6.9', '3.1.6.10', '1.1.1;1.1.1.-', '1.1.1.230', '1.14.-.-', '1.-.-.-;1.1.1.342', '3.1.3.14', '1.1.1.62', '1.1.1.62', '1.1.1.53', '1.1.1.50', '1.1.1.53', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.1.1.166', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.2;1.1.1.21;1.1.1.261', '1.1.1.263', '1.1.1.270', '3.1.3.69', '1.1.1.274', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.297', '1.1.1;1.1.1.-', '1.1.1.364', '1.17.1.3', '1.17.1.3', '1.14.13.-', '1.17.1.3', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.1.1.270', '3.1.3.76', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.1.1.-', '1.1.1;1.1.1.-;1.1.1.50', '1.-.-.-', '1.1.1.292', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.162', '1.1.1.-', '1.1.1.-', '1.1.1.-;1.1.1.341;4.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.274;1.1.1.346', '1.1.1.-;1.1.1.329', '3.1.3.-;3.1.3.88', '1.1.1.297', '1.1.1.-', '1.1.1.239;1.1.1.62', '1.1.1.213', '1.1.1.209;1.1.1.213;1.1.1.357', '1.1.1.62', '3.1.3.79', '1.5.3.15;1.5.3.17', '1.5.1.-;1.5.1.43', '1.14.14.-', '1.1.3.-;1.1.3.45', '1.1.1.297', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.1.1.301', '3.1.3.85', '1.14.-.-', '3.1.3.83', '1.1.1.323', '1.1.1.323', '1.1.1.-;1.1.1.329', '1.1.1.335', '1.1.1.340;1.14.13.-', '1.1.1.339;1.1.1.344', '1.1.1.355', '1.1.1.356', '1.1.1.356', '1.1.1.361', '3.1.3.92', '1.1.1.364', '1.1.1.367', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.1.1.374', '1.1.1.385', '1.1.1.389', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.1.1.393', '3.1.3.101', '3.1.3.-', '1.1.1.-', '1.1.1.-', '1.1.1.-', '3.1.3;3.1.3.-', '1.1.1.-', '1.1.1.402', '1.1.1.14;1.1.1.162;1.1.1.403', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '3.1.3.103', '1.1.1.251', '1.1.1.289', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.1.1.395', '1.1.1.-;1.1.1.395', '1.1.1.14;1.1.1.15', '1.1.1', '1.1.1.14', '1.1.3.11', '3.1.3.3', '3.1.3', '1.5.3.14', '3.1.3.-', '1.1.1;1.1.1.-', '3.1.3;3.1.3.-', '1.1.1.201', '1.1.1.-;1.1.1.50;1.1.1.52', '1.1.1.391', '1.1.1.15', '1.1.1.-;1.1.1.270', '1.1.1;1.1.1.-;1.1.1.270', '1.1.1.-;1.1.1.270', '3.1.3;3.1.3.-', '1.1.1;1.1.1.-;1.1.1.12', '1.1.1', '1.1.1', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.1.1.102', '1.1.1.-;1.1.1.393', '1.1.1.145', '1.1.1;1.1.1.-', '1.1.1;1.1.1.-', '1.14.14.133', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.1.1', '3.1.3.50', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.1.1', '1.1.1', '3.1.3', '3.1.3.4', '1.1.1.201', '3.1.3.4', '1.1.1', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1', '1.14.13', '1.1.1.M2', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.M11', '1.1.1.M11', '1.1.1.392', '1.1.1.393', '1.1.1.52', '1.1.1.391', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.52', '1.1.1.391', '1.1.1.392;1.1.1.50;1.1.1.52', '1.1.1.392', '1.1.1.393', '1.1.1.393', '3.1.3', '1.1.1.M28', '1.1.1.14;1.1.1.M29', '1.1.1', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '3.1.3;3.1.3.-;3.1.3.104;3.1.3.2;3.1.3.29', '3.1.3', '3.1.3;3.1.3.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1.270', '1.1.1.270', '1.1.1.140', '1.1.1.123', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.2;1.1.1.213;1.1.1.239;1.1.1.62;1.3.1.20', '1.1.1.159', '1.1.1.218', '3.1.6.14', '1.1.1.218', '1.1.1.1', '1.1.1.188;1.1.1.213;1.1.1.50', '1.1.1.1', '3.1.3.29', '3.1.3.29', '1.14.15.15', '1.1.1.149', '1.1.1.145', '1.1.1.1', '1.1.1.1', '1.1.1.1', '1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50;1.3.1.20', '1.1.1.140;1.1.1.17', '3.1.3.33;3.1.3.5', '1.1.1.133', '1.1.1.239;1.1.1.51', '1.1.1.239;1.1.1.51', '1.1.1.184', '1.1.1;1.1.1.184;1.1.1.62', '1.1.1.184;1.1.1.2;1.1.1.62', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.213;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.50', '1.1.1.51', '1.14.13.126;1.14.15.16', '1.1.1;1.1.1.209', '1.1.1.292', '1.1.1', '1.1.1.209', '1.1.1.209', '1.1.1.209', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.1.1', '1.1.1.357;1.1.1.50', '1.1.1.210;1.1.1.357', '3.1.3', '3.1.3', '1.14.14.55', '3.2.1.78', '3.2.1.78', '1.1.1.184;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.50', '1.1.1.184;1.1.1.50', '1.1.1.12;1.1.1.14', '1.1.1.12;1.1.1.14', '1.1.1.12', '1.1.1;1.1.1.10;1.1.1.405', '1.1.1.10', '1.1.3.38', '3.1.3', '3.1.3', '1.1.1.146;1.1.1.159;1.1.1.50', '3.1.6.3', '1.1.99.13', '3.1.3.68', '1.1.1.162', '1.1.1.-', '1.14.15.4', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.133', '1.14.15.4', '1.14.15.6', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.297', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '3.2.1.154;3.2.1.26;3.2.1.80', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.55', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '1.1.1.-', '3.2.1.65', '3.2.1.145;3.2.1.23', '3.2.1.110', '1.1.1.125;1.1.1.127', '3.1.3.91', '3.6.1;3.6.1.-', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '3.2.1.137;3.2.1.78', '1.1.1.104', '1.1.1.104', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '1.1.1.239;1.1.1.51', '1.1.1;1.1.1.239;1.1.1.62;1.1.1.64', '2.4.1.-', '1.1.1.104', '1.14.-.-', '1.14.-.-', '1.1.1.-;1.1.1.146', '1.1.1;1.1.1.-;1.1.1.146;1.1.1.51', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62;1.1.1.63', '1.1.1.184;1.1.1.2;1.1.1.213;1.1.1.51;1.1.1.64', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.2;1.1.1.209;1.1.1.21;1.1.1.213;1.1.1.50;1.3.1.20', '3.1.3.23;3.1.3.29;3.1.3.9', '1.1.1.124;1.1.1.138;1.1.1.14;1.1.1.67;1.1.99.11;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '3.1.3.27', '1.5.3.11;1.5.3.13;1.5.3.16;1.5.3.17', '1.1.1.166;1.1.1.24;1.1.1.282', '1.1.1.14;1.1.1.56', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '1.1.1.12;1.1.1.124;1.1.1.138;1.1.1.14;1.1.1.67;1.1.1.9;1.1.99.11;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.1.3.24', '1.1.1.58', '1.1.1.133', '3.1.3.12', '1.1.1.14;1.1.1.9', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '1.1.1.271', '1.1.1.124;1.1.1.138;1.1.1.21;1.1.1.287;1.1.1.67;1.1.99.11;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '1.1.1.124;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.1.3.29', '1.1.1;1.1.1.148;1.1.1.209', '3.1.3.-', '1.1.1.134;1.1.1.344', '1.1.1.159;1.1.1.50', '1.1.1.176', '1.1.1.206', '1.1.1.236', '1.1.1.16', '1.1.1.198', '1.1.1.227', '1.1.1.241', '1.1.1.174', '1.1.1.135;1.1.1.187', '1.1.1.187;1.1.1.281', '1.1.1.135;1.1.1.187', '1.1.1.187;1.1.1.281', '1.1.1.51', '1.1.1.51;1.1.1.62;1.1.1.64', '1.1.1.238', '1.14.13.74', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.1.1.146', '1.1.1.213;1.1.1.52', '3.1.3.63', '3.1.3.63', '1.1.1.152;1.1.1.184;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1.184;1.1.1.209;1.1.1.213;1.1.1.50', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.1.1.213;1.1.1.50', '1.1.1.50', '1.1.1.209;1.1.1.50', '1.1.1.213;1.1.1.50;1.1.1.51', '1.1.1.149;1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '2.-.-.-', '1.1.1.266', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.1.1.213;1.1.1.277;1.1.1.50', '1.14.13.79', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.1.1.282', '1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.278', '1.14.13.94', '1.14.13.96', '1.14.13.97', '3.1.3.21;3.1.3.25;3.1.3.29', '3.1.3.21;3.1.3.25', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.-.-', '1.14.-.-', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.147', '1.1.1.210;1.1.1.357;1.1.1.50;1.1.1.51', '1.14.13.-', '1.1.1.380', '1.1.1.1;1.1.1.391', '1.1.1.-;1.1.1.146;1.1.1.209;1.1.1.213;1.1.1.392;1.1.1.50', '3.1.3.73', '1.1.1;1.1.1.-', '3.1.3', '3.1.3', '1.1.1.159', '1.14.14.149', '1.1.1.-', '1.1.1.270', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.1.1;1.1.1.10', '1.1.1.153', '1.1.1.10;1.1.1.14;1.1.1.15', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.213;1.1.1.50;1.1.1.51;1.1.1.53', '3.1.3.45', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.1.1.-;1.1.1.M53', '1.14.13;1.14.13.-', '3.1.3', '3.1.3.68', '1.5.1.43', '1.1.1.414', '1.1.1.270', '1.1.1.270', '1.1.1.201', '1.1.1', '1.1.1.425', '3.1.3.M8', '1.1.1', '1.1.1.104', '1.1.1.323', '1.1.1.323', '1.1.1.266', '3.1.3.106;3.1.3.76', '1.1.1.367', '1.1.1.M48', '1.1.1.57', '1.1.1.406', '1.1.1.407', '1.1.1.64', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.5.1.43', '1.1.1;1.1.1.206', '1.1.1', '1.1.1', '1.1.1', '1.14.14.70', '1.14.14.70', '1.1.1.14', '1.1.1', '1.1.1.10', '1.1.3.10', '1.1.3.10', '3.1.3.58;3.1.3.9', '3.1.6.3', '3.2.1.37', '3.2.1.37', '3.2.1.55', '3.2.1.55', '3.2.1.3;3.2.1.58;3.2.1.59', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.1.1.227', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.1.1.274', '1.1.1.297', '1.1.1.297', '1.14.13.126', '1.14.-.-', '1.14.-.-', '1.1.1.323', '1.1.1.323', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.2.1.1', '1.1.1.-', '1.7.3.-', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.-', '1.14.13.-', '1.14.13.-', '3.2.1.2', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.15.5', '1.1.1.-;1.1.1.270', '1.1.1.-;1.1.1.270', '1.14.13.79', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '3.2.1.137', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.96', '1.1.1.-', '3.1.3.27', '1.1.1.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.183', '1.14.13.184', '1.14.13.194', '1.14.13', '3.1.3', '3.1.3.73', '3.2.1.143', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.14.13.M64', '1.1.1.M51', '3.1.3.73', '1.1.1.M51', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.106', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '1.1.1.-;1.1.1.1;1.1.1.327', '1.1.1.270', '1.14.13.98', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.1.1.184;1.1.1.189', '3.1.3.82', '3.1.3.29;3.1.3.50', '3.1.3.50', '1.1.1.296', '1.1.1.296', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1;1.1.1.51;1.1.1.62', '1.14.13.-;1.14.15.6', '1.1.1.271', '1.1.1.271', '1.1;1.1.1;1.1.1.209;1.1.1.213', '1.1.1.1', '1.1.99.13', '3.1.3.58;3.1.3.9', '1.17.99.5', '1.1.1;1.1.1.184;1.1.1.210;1.1.1.50', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.2;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.3.1.20', '1.1.1.184;1.1.1.357', '1.14.13.97', '1.17.99.5', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '1.1.5.3;1.1.99.5', '1.1.1.367', '1.1.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.395', '1.1.1', '1.1.1.146', '1.1.1.64', '1.1.1.146', '1.1.1.239', '1.1.1.239', '1.1.1.62', '1.1.1.270', '1.1.1.238', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1.206', '3.1.3.76', '3.1.3.76', '1.1.1.102', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '4.2.3;4.2.3.1', '1.1.1;1.1.1.69', '1.1.1.213;1.1.1.50', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '3.1.3.1;3.1.3.75', '1.1.1.261', '3.1.3.1;3.1.3.19;3.1.3.2;3.1.3.25;3.1.3.29', '1.1.1.8;1.1.1.94;1.1.5.3', '1.1.1.49;1.1.1.8;1.1.1.94;1.3.1.20', '3.1.3.2;3.1.3.21']
40
353
AMANTADINE
5

100%|██████████| 11047/11047 [00:02<00:00, 3743.66it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4608.32it/s]
  3%|▎         | 7/271 [01:29<56:11, 12.77s/it]

rxndb num 2
failedrxn num 0
result_df 2
['3.10.1.2', '1.14.13.-']
2
2
AMINOGLUTETHIMIDE
5

100%|██████████| 11047/11047 [00:02<00:00, 4200.11it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3830.53it/s]
  3%|▎         | 8/271 [01:42<56:09, 12.81s/it]

rxndb num 765
failedrxn num 0
result_df 50
['3.5.1.94', '3.5.1.94', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '6.3.2.1', '6.3.2.1', '3.5.1.92', '3.5.1.92', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '3.5.1.22', '3.5.1.22', '6.3.2.23', '6.3.2.23', '6.3.1.2;6.3.1.6', '6.3.1.2;6.3.1.6', '3.5.1.65', '3.5.1.65', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '6.3.2.20', '6.3.2.20', '1.17.1.1', '1.17.1.1', '1.14.14.-;1.14.14.1', '1.3.1.5', '1.3.1.5', '3.5.1.24;3.5.1.74', '3.5.1.24;3.5.1.74', '3.5.1.24', '3.5.1.24', '1.3.1.48', '1.3.1.48', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.8.99.3;1.8.99.5', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.1', '1.1.1.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '6.3.2.36', '6.3.2.36', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.-.-', '1.14.13.-;1.14.13.161', '1.14.13.-;1.14.13.161', '1.14.13.-;1.14.13.161', '1.11.2.5', '1.11.2.5', '3.5.1.-', '3.5.1.-', '6.3.2.44', '6.3.2.44', '6.3.4.24', '6.3.4.24', '1.14.13.209', '1.14.13.209', '1.14.13.-', '1.14.-.-', '1.14.-.-', '6.3.2.18', '6.3.2.18', '6.3.2;6.3.2.-', '6.3.2;6.3.2.-', '1.3.3.6', '6.3.2', '6.3.2', '6.3.2', '6.3.2', '6.3.2', '6.3.2', '3.4.11.25', '3.4.11.25', '1.14.13;1.14.13.-', '1.3.1.93', '1.3.1.93', '6.3.2.59', '6.3.2.59', '6.3.2.59', '6.3.2.59', '1.3.1', '1.3.1', '1.3.1.93', '1.3.1.93', '1.14.14', '1.14.14', '3.4.13', '3.4.13', '6.3.2', '6.3.2', '1.3.1.93', '1.3.1.93', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '1.3.1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2', '6.3.2', '3.4', '3.4', '3.5.1.115', '3.5.1.115', '1.3.3.6', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '1.3.1.48', '1.3.1.48', '1.3.1.48', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '1.14.15.15', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '3.5.2.16', '3.5.2.16', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '1.14.13', '1.14.13', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '6.3.2.18', '6.3.2.18', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '3.4.11.5', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '6.3.2.17', '6.3.2.17', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-', '1.3.1;1.3.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.3.1.11', '6.3.1.11', '3.5.1.-;3.5.1.78', '3.5.1.-;3.5.1.78', '6.3.1.8;6.3.1.9', '6.3.1.8;6.3.1.9', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.5.1.4;3.5.1.99', '3.5.1.4;3.5.1.99', '1.14.13.30', '1.14.14.1', '1.14.14.1', '3.5.1.24;3.5.1.74', '3.5.1.24;3.5.1.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '6.3.1.9', '6.3.1.9', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.3.1.104;1.3.1.38;1.3.1.8', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.3.1.104;1.3.1.38;1.3.1.44;1.3.1.8', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.-.-', '1.14.-.-', '3.5.1.-', '3.5.1.-', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '6.3.1.13', '6.3.1.13', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1;1.3.1.44', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.19.41;1.3.1.-', '1.3.99.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.3.99.3', '1.1.1;1.3.99.3', '1.3.1.9', '6.3.1.10', '6.3.1.10', '6.3.1.10', '6.3.1.10', '3.5.1.90', '3.5.1.90', '3.5.1.90', '3.5.1.90', '1.3.1.-', '6.3.2.56;6.3.2.ad', '6.3.2.56;6.3.2.ad', '1.3.1.42', '3.5.1.60;3.5.1.99', '3.5.1.60;3.5.1.99', '3.5.1.60', '3.5.1.60', '3.5.1.60;3.5.1.99', '3.5.1.60;3.5.1.99', '3.5.1.99', '3.5.1.99', '3.5.1.99', '3.5.1.99', '3.5.1.60', '3.5.1.60', '1.14.13.9', '1.14.13.9', '3.4', '3.4', '3.2.1.14', '3.2.1.14', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-;1.14.13.-', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '3.4.15.6', '3.4.15.6', '3.4.19.9', '3.4.19.9', '3.4.19.7', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.-', '3.2.1.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.13.174', '1.-.-.-', '1.14.13.72', '1.14.15.5', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.194', '6.3.2;6.3.2.-', '6.3.2;6.3.2.-', '6.3.2', '6.3.2', '6.3.2', '6.3.2', '6.3.2', '6.3.2', '1.3.3.6', '6.3.2', '6.3.2', '6.3.2', '6.3.2', '6.3.2.37', '6.3.2.37', '1.3.1.93', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.3.3.6', '1.3.1.104;1.3.1.38;1.3.1.8', '6.3.1.10', '6.3.1.10', '1.3.99.-', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.3.3.6;1.3.8.1;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.3.3.6', '1.3.3.6', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.3.1.10;1.3.1.38;1.3.1.8', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.14.14', '1.14.14', '6.3.2.58', '6.3.2.58', '6.3.2.58', '6.3.2.58', '3.5.1.115', '3.5.1.115', '1.11.2.6', '1.11.2.6', '1.3.1.74', '1.1.1;1.1.1.206', '1.1.1;1.1.1.206', '3.5.1.46', '3.5.1.46']
36
135
AMISULPRIDE
5

100%|██████████| 11047/11047 [00:03<00:00, 2802.78it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4231.89it/s]
  3%|▎         | 9/271 [01:55<55:49, 12.78s/it]

rxndb num 303
failedrxn num 0
result_df 42
['1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '3.5.1.40', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.12.14', '1.14.12.-', '1.14.13.180', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '3.3.2.14', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.13.-', '1.14.13.-', '3.4.11.5', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '3.2.1.35', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '1.14.-.-', '1.14.-.-', '2.4.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.1', '1.14.14.1', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.87', '3.4.15.6', '3.4.15.6', '3.4.19.7', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.-', '3.2.1.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.15.5', '1.14.15.5', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '3.2.1.143', '1.3.99.-', '1.14.13.-', '1.14.13.-', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '3.6.1.18;3.6.1.9']
26
61
ANAGRELIDE
5

100%|██████████| 11047/11047 [00:03<00:00, 3391.23it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3530.95it/s]
  4%|▎         | 10/271 [02:08<56:43, 13.04s/it]

rxndb num 96
failedrxn num 0
result_df 21
['1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '6.3.2.23', '6.3.2.20', '3.5.1.24;3.5.1.74', '3.8.1.7', '3.8.1.7', '3.5.1.24', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.5.1.-', '6.3.4.24', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '6.3.2.18', '3.4.13', '6.3.2', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '3.5.1.115', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '6.3.2.18', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.5.1.-;3.5.1.78', '6.3.1.8;6.3.1.9', '3.5.1.24;3.5.1.74', '6.3.1.9', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '3.5.1.-', '1.14.13.11', '1.14.13.11', '6.3.1.13', '6.3.1.10', '6.3.1.10', '3.5.1.90', '3.5.1.90', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.4.15.6', '1.3.98.-', '1.3.98.-', '3.2.1.-', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.3.2.37', '6.3.1.10', '1.14.19.58', '1.14.19.58', '3.5.1.115', '1.1.1;1.1.1.206']
19
53
ANASTROZOLE
5

100%|██████████| 11047/11047 [00:02<00:00, 4515.49it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3344.42it/s]
  4%|▍         | 11/271 [02:21<56:26, 13.02s/it]

rxndb num 47
failedrxn num 0
result_df 17
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.5.5.1', '1.14.13.58', '1.14.13.58', '4.2.1.84', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.209', '1.14.13.209', '1.17.1.4', '1.17.1.4', '4.99.1.M4', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '4.3.1;4.99.1.6', '4.99.1.6']
9
20
ANTAZOLINE PHOSPHATE
5

100%|██████████| 11047/11047 [00:03<00:00, 3023.45it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4432.04it/s]
  4%|▍         | 12/271 [02:34<56:13, 13.02s/it]

rxndb num 118
failedrxn num 0
result_df 19
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-']
5
17
APOMORPHINE
5

100%|██████████| 11047/11047 [00:04<00:00, 2684.16it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3369.93it/s]
  5%|▍         | 13/271 [02:50<58:57, 13.71s/it]

rxndb num 989
failedrxn num 0
result_df 87
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.6.1;3.1.6.2', '3.1.6.1;3.1.6.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.7', '1.14.13.7', '1.14.13.31', '1.14.13.31', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.6', '1.14.13.6', '1.14.13.29', '1.14.13.29', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.44', '1.14.13.44', '1.14.13.20', '1.14.13.20', '1.3.1.29', '1.3.1.49', '1.14.-.-', '1.5.1.27', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.219;1.14.13.7', '1.14.13.219;1.14.13.7', '1.14.13.-;1.14.13.20;1.14.13.7', '1.14.13.-;1.14.13.20;1.14.13.7', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.14.13.-', '1.17.1.3', '1.17.1.3', '1.14.13.-;1.6.5.2', '1.14.13.-;1.6.5.2', '1.3.1.29', '1.1.-.-', '1.3.1.29', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.13.11.-', '1.3.1.29', '1.14.12.23', '1.14.12.23', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.3.1.29', '1.3.1.29', '1.3.1.29', '1.3.-.-', '1.3.-.-', '1.3.-.-', '1.3.-.-', '1.3.-.-', '1.6.5.-', '1.14.12.-;1.14.12.24', '1.14.12.-;1.14.12.24', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.13.244;1.14.13.M20', '1.14.13.244;1.14.13.M20', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.189', '1.14.13.189', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.220', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.20', '1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.8', '1.14.13.8', '1.1.1;1.1.1.2', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.3.1.20', '3.1.6.1', '3.1.6.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.91', '1.14.14.91', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.18.1', '1.14.18.1', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3.48', '3.1.3.48', '3.1.3.2;3.1.3.48;3.1.3.76', '3.1.3.2;3.1.3.48;3.1.3.76', '3.1.3.36;3.1.3.48', '3.1.3.36;3.1.3.48', '3.1.3.2', '3.1.3.2', '1.14.13.31', '1.14.13.31', '1.14.18.1', '1.14.18.1', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.97.1.2', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.55', '3.2.1.55', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '3.2.1.21;3.2.1.3', '3.2.1.65', '3.2.1.65', '3.2.1.145;3.2.1.23', '3.2.1.145;3.2.1.23', '1.14.-.-', '1.14.-.-', '1.14.14.1', '1.14.13', '3.2.1.137;3.2.1.78', '3.2.1.137;3.2.1.78', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3;3.1.3.2;3.1.3.48', '3.1.3;3.1.3.2;3.1.3.48', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.7', '1.14.13.7', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.88', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '3.2.1.22;3.2.1.23', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.127', '1.14.13.127', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.37', '3.2.1.37', '3.2.1.37', '3.2.1.37', '3.2.1.3;3.2.1.58;3.2.1.59', '3.2.1.3;3.2.1.58;3.2.1.59', '3.2.1.4', '3.2.1.4', '3.2.1.4', '3.2.1.4', '1.3.1.20', '3.2.1.116', '3.2.1.116', '3.2.1.60', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.1', '3.2.1.1', '1.14.12.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.2', '3.2.1.2', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.137', '3.2.1.137', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.88', '1.14.13', '1.14.13', '1.14.13.236', '1.14.13.236', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.190', '1.14.13.190', '1.14.14.20', '1.14.14.20', '1.14.14.8', '1.14.14.8', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.27', '1.14.14.27', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '3.1.3.76', '3.1.3.76', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '1.1.1.50;1.3.1.20']
31
125
ARTEMISININ
5

100%|██████████| 11047/11047 [00:03<00:00, 3084.56it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3362.04it/s]
  5%|▌         | 14/271 [03:04<59:48, 13.96s/it]

rxndb num 997
failedrxn num 0
result_df 99
['1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.15.6', '1.14.15.6', '3.1.1.23', '3.1.1.22;3.1.1.75', '1.1.1.118;1.1.1.47', '1.1.1.119;1.1.1.47', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.1.70', '1.1.1.173;1.1.1.378', '3.1.1.51', '1.14.13.154', '1.14.13.154', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.3.1.-', '1.3.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.4.1.247', '2.4.1.247', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.-;3.2.1.21', '3.2.1.-;3.2.1.21', '3.2.1.21', '3.2.1.21', '3.2.1.21', '3.2.1.21', '1.3.1.-;1.3.1.92', '2.4.1.-;2.4.1.282', '2.4.1.-;2.4.1.282', '3.1.1.93', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.4.1.320', '2.4.1.320', '1.1.1.203', '1.1.1.203', '1.1.1.363;1.1.1.388', '2.4.1.329', '1.1.1.390', '2.4.1.332', '2.4.1.332', '2.4.1.216', '3.2.1.150', '3.2.1.150', '1.1.1.116', '1.1.1.359;1.1.1.376;1.1.1.46', '1.1.1.203', '6.3.2', '3.1.1;3.1.1.1;3.1.1.3', '3.2.1.159', '3.2.1.159', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.2.1.52', '3.2.1.52', '1.3.1', '1.3.1', '1.3.1', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.14.133', '3.2.1', '3.2.1', '3.2.1.149', '3.2.1.149', '3.2.1.149', '3.2.1.149', '1.1.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '3.2.1.194', '3.2.1.194', '3.2.1.195', '3.2.1.195', '3.1.1.26', '3.1.1.4', '3.1.1.23', '3.1.1.23', '3.1.1.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '2.4.1.230', '2.4.1.230', '1.1.1.-;1.1.1.377;1.1.1.378', '3.2.1.40', '3.2.1.40', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '3.1.1', '1.1.1.-', '1.1.1', '2.4.1.7', '3.2.1.28', '3.1.1.1;3.1.1.13;3.1.1.3', '3.1.1.1;3.1.1.3', '3.1.1.3', '3.1.1.3', '3.1.1.1', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '1.14.15.15', '1.14.15.15', '1.14.15.15', '3.1.1.1;3.1.1.2', '3.1.1.1;3.1.1.2', '3.1.1.1;3.1.1.2', '3.2.1.70', '3.2.1.70', '1.1.1.179;1.3.1.20', '1.1.1.179;1.3.1.20', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '3.2.1.81', '3.2.1.81', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '3.2.1.78', '3.2.1.78', '3.2.1.78', '3.2.1.78', '1.1.1.121', '1.1.1.121', '1.1.1.47', '1.1.1.122', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.154', '1.14.13.154', '1.2.1.74', '1.14.13.-', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.82', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.76', '3.2.1.31', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '2.3.1.-', '3.2.1.28', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.3.1;1.3.1.-', '1.3.1;1.3.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.1.5', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.15.3', '1.14.15.3', '1.14.15.3', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.2.1.26', '1.14.13.30', '1.14.13.30', '1.14.13.30', '2.4.1.10;3.2.1.20;3.2.1.26;3.2.1.48', '2.4.1.7', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '3.1.1.10', '1.1.1.113', '3.2.1.26', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '2.4.1.231', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.107;1.1.1.122', '1.14.-.-;1.14.13.-', '1.14.-.-;1.14.13.-', '1.14.-.-;1.14.13.-', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '2.3.1.-', '1.3.1.-;1.3.1.72;1.3.1.M20', '1.3.1.-;1.3.1.72;1.3.1.M20', '1.3.1.-;1.3.1.71', '1.3.1.-;1.3.1.71', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.-.-', '1.1.1.363;1.1.1.388;1.1.1.47;1.1.1.49', '3.1.1', '3.2.1.21', '3.2.1.21', '3.2.1', '3.2.1', '3.2.1', '3.2.1', '3.2.1.128', '3.2.1.128', '3.1.1.116', '1.1.1.376', '2.4.1.359;2.4.1.dr', '2.4.1.359;2.4.1.dr', '1.1.1.420', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '3.2.1.10;3.2.1.20', '3.2.1.10;3.2.1.20;3.2.1.26', '1.1.1.120', '3.2.1.14', '1.1.1.121;1.1.1.175', '1.1.1.121', '1.1.1.179', '1.1.1.179', '3.2.1.104', '3.2.1.104', '3.2.1.104', '3.2.1.104', '1.1.1.46', '1.1.1.46', '2.4.1.64', '2.4.1.64', '3.2.1.117', '3.2.1.117', '3.2.1.105', '3.2.1.105', '3.2.1.74', '3.2.1.74', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.1.1.121', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-;1.14.13.-', '1.14.-.-;1.14.13.-', '1.14.-.-;1.14.13.-', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '2.4.1.247', '2.4.1.247', '2.4.1.247', '2.4.1.247', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '2.4.1.280', '2.4.1.280', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.2.1.87', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '2.3.1.-', '2.3.1.-', '2.3.1.-', '2.3.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.-', '3.2.1.177', '3.2.1.177', '3.2.1.159', '3.2.1.159', '1.14.13.-;1.14.13.188', '1.14.13.-;1.14.13.188', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '3.1.-.-', '3.1.-.-', '3.1.-.-', '1.3.1.-', '1.3.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.15.5', '1.14.15.5', '1.14.15.5', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '3.2.1.15', '4.2.2.2', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '6.2.1.3', '6.2.1.3', '1.1.1.117', '1.1.1.117', '1.1.1.117', '1.1.1.117', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '3.1.1.5', '1.1.1.46', '1.1.1.46', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.1.1.-', '1.14.13.156', '1.14.13.156', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.194', '1.14.13.194', '1.14.13.194', '3.2.1', '3.2.1', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.1.1.363;1.1.1.49', '3.2.1.119', '3.2.1.119', '2.4.1.211', '2.4.1.211', '3.1.1.88', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.1.1.118', '1.1.1.120;1.1.1.179;1.1.1.359;1.1.1.360;1.1.1.47;1.1.1.48;1.3.1.20', '1.1.1.120', '3.2.1.118', '3.2.1.118', '3.2.1.117', '3.2.1.117', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '2.4.1.216', '1.1.1.119', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.1.1.121;1.1.1.359;1.1.1.47;1.1.1.48', '1.1.1.121', '3.2.1.20;3.2.1.28', '1.1.1.363;1.1.1.47;1.1.1.49', '1.1.1.49', '3.2.1.118', '3.2.1.118', '3.2.1.214', '3.2.1.214', '1.1.1.424', '3.2.1.37', '3.2.1.37', '3.2.1.37', '3.2.1.37', '3.2.1.20', '3.2.1.20', '3.1.1.3', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-;1.14.13.-;1.14.13.cs', '1.14.-.-;1.14.13.-;1.14.13.cs', '1.14.-.-;1.14.13.-;1.14.13.cs']
24
160
ATENOLOL
5

100%|██████████| 11047/11047 [00:02<00:00, 4425.20it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3705.98it/s]
  6%|▌         | 15/271 [03:17<57:52, 13.56s/it]

rxndb num 836
failedrxn num 0
result_df 50
['6.3.1.2', '1.4.1.13;1.4.1.14;1.4.7.1;2.4.2;2.4.2.14;3.5.1.2;3.5.1.38;4.3.1;4.3.3.6;6.3.4.2;6.3.5.2;6.3.5.4;6.3.5.5;6.3.5.7', '3.1.3.69', '1.1.1.14;1.1.1.6', '1.1.1.1;1.1.1.10;1.1.1.156;1.1.1.2;1.1.1.21;1.1.1.72;1.3.1.20', '3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.14.1', '3.1.3.-', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.27', '3.1.3.3', '3.1.3;3.1.3.2', '3.1.3.74', '1.5.3.13;1.5.3.17', '1.5.3.13', '1.5.3.13;1.5.3.17', '3.1.3', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.1.1;1.1.1.10', '3.5.1.-;3.5.1.111;3.5.1.3', '6.3.1.4', '1.14.18.1', '1.14.18.1', '3.5.1.12', '3.5.5.4;4.2.1.65', '3.1.3.2;3.1.3.29;3.1.3.38', '1.1.1.137', '1.1.1.137;1.1.1.405', '3.5.1.2;3.5.1.35;3.5.1.38', '1.1.1.69', '3.5.1.73', '3.10.1.1', '3.1.3.22;3.1.3.23', '3.1.3.39', '1.1.3.16', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '3.5.1.50', '1.14.14.1', '1.14.13.4', '1.14.13.4', '3.1.3.40', '1.1.1.143', '1.1.1.142', '3.1.6.9', '3.1.6.10', '1.1.1;1.1.1.-', '4.2.1.84', '1.-.-.-;1.1.1.342', '1.1.1.226', '3.1.3.14', '1.1.1.62', '1.1.1.62', '1.1.1.53', '1.1.1.50', '1.1.1.53', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.166', '1.14.13.-', '1.14.13.-', '1.1.1.2;1.1.1.21;1.1.1.261', '1.1.1.263', '3.5.1.86', '3.1.3.69', '1.1.1.274', '1.1.1.297', '1.1.1;1.1.1.-', '1.1.1.364', '1.17.1.3', '1.17.1.3', '1.14.13.-', '1.17.1.3', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '3.1.3.76', '1.14.13.-', '1.14.13.-', '1.14.13.-', '4.2.1.84', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.1.1.-', '1.1.1;1.1.1.-;1.1.1.50', '1.-.-.-', '1.1.1.292', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.162', '1.1.1.-', '1.1.1.-', '1.1.1.-;1.1.1.341;4.2.1.-', '1.14.13.-', '1.14.13.-', '1.1.1.274;1.1.1.346', '1.1.1.-;1.1.1.329', '3.1.3.-;3.1.3.88', '1.1.1.297', '1.1.1.-', '1.1.1.213', '3.1.3.79', '1.5.3.15;1.5.3.17', '1.5.1.-;1.5.1.43', '1.1.3.-;1.1.3.45', '1.1.1.297', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '3.5.1.99', '1.1.1.301', '3.5.1.100', '3.1.3.85', '1.14.-.-', '3.1.3.83', '1.1.1.-;1.1.1.329', '1.1.1.335', '1.1.1.339;1.1.1.344', '1.1.1.355', '1.1.1.356', '1.1.1.356', '1.1.1.361', '3.1.3.92', '1.1.1.364', '1.1.1.367', '1.11.2.5', '1.11.2.5', '1.1.1.374', '1.1.1.385', '1.1.1.389', '1.14.13.209', '1.14.13.209', '1.1.1.393', '3.1.3.101', '3.1.3.-', '1.1.1.-', '1.1.1.-', '1.1.1.-', '3.1.3;3.1.3.-', '1.1.1.-', '1.1.1.402', '1.1.1.14;1.1.1.162;1.1.1.403', '1.14.-.-', '1.14.-.-', '2.1.1.-', '3.1.3.103', '1.1.1.251', '1.1.1.289', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.1.1.395', '1.1.1.-;1.1.1.395', '1.1.1.14;1.1.1.15', '1.1.1', '1.1.1.14', '1.1.3.11', '3.1.3.3', '3.1.3', '1.5.3.14', '3.1.3.-', '1.1.1;1.1.1.-', '3.1.3;3.1.3.-', '1.1.1.201', '1.1.1.-;1.1.1.50;1.1.1.52', '1.1.1.391', '1.1.1.15', '3.1.3;3.1.3.-', '1.1.1;1.1.1.-;1.1.1.12', '1.1.1', '1.1.1', '3.1.6;3.1.6.-', '1.1.1.102', '1.1.1.145', '1.1.1;1.1.1.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1', '1.1.1', '1.14.13', '1.14.13', '3.5.1.100', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '4.2.1.84', '4.2.1.84', '1.1.1', '3.1.3.50', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.1.1', '1.1.1', '3.1.3', '3.1.3.4', '1.1.1.201', '3.1.3.4', '1.1.1', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.1.1', '1.14.13', '1.1.1.M2', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.M11', '1.1.1.M11', '1.1.1.392', '1.1.1.393', '1.1.1.52', '1.1.1.391', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.52', '1.1.1.391', '1.1.1.392;1.1.1.50;1.1.1.52', '1.1.1.392', '1.1.1.393', '1.1.1.393', '3.5.1.4', '4.2.1.84', '3.1.3', '1.1.1.M28', '1.1.1.14;1.1.1.M29', '1.1.1', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '3.1.3;3.1.3.-;3.1.3.104;3.1.3.2;3.1.3.29', '3.1.3', '3.1.3;3.1.3.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1.140', '1.1.1.123', '1.1.1.159', '1.1.1.218', '3.1.6.14', '1.1.1.218', '3.5.1.4', '3.5.1.4', '3.1.3.29', '3.1.3.29', '1.1.1.149', '1.1.1.140;1.1.1.17', '3.1.3.33;3.1.3.5', '1.1.1.133', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '2.3.2.2;6.3.1.2', '3.5.1.1', '3.5.1.1', '1.1.1.213;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.50', '1.14.13.126;1.14.15.16', '1.1.1.292', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.1.1', '1.14.13', '1.14.13', '1.14.18.1', '1.14.18.1', '3.1.3', '3.1.3', '3.2.1.78', '3.2.1.78', '1.1.1.12;1.1.1.14', '1.1.1.12;1.1.1.14', '1.1.1.12', '1.1.1;1.1.1.10;1.1.1.405', '1.1.1.10', '3.1.3', '3.1.3', '1.1.1.146;1.1.1.159;1.1.1.50', '3.1.6.3', '1.1.99.13', '3.1.3.68', '1.1.1.162', '1.14.18.1', '1.14.18.1', '1.1.1.-', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.1.1.133', '1.14.15.4', '1.14.15.6', '1.1.1.297', '1.14.13.36', '1.14.13.36', '3.4.11.5', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.55', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '1.1.1.-', '6.3.2.17', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.145;3.2.1.23', '3.2.1.110', '3.2.1.35', '1.1.1.125;1.1.1.127', '3.1.3.91', '3.6.1;3.6.1.-', '1.14.14.91', '1.14.14.91', '3.2.1.137;3.2.1.78', '1.1.1.104', '1.1.1.104', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '2.4.1.-', '1.1.1.104', '1.14.-.-', '1.14.-.-', '1.1.1.-;1.1.1.146', '1.1.1;1.1.1.-;1.1.1.146;1.1.1.51', '3.1.3.23;3.1.3.29;3.1.3.9', '1.1.1.124;1.1.1.138;1.1.1.14;1.1.1.67;1.1.99.11;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.13.-;1.14.13.95;1.14.18.8', '3.1.3.27', '1.5.3.11;1.5.3.13;1.5.3.16;1.5.3.17', '1.1.1.166;1.1.1.24;1.1.1.282', '1.1.1.14;1.1.1.56', '3.1.3', '1.1.1.12;1.1.1.124;1.1.1.138;1.1.1.14;1.1.1.67;1.1.1.9;1.1.99.11;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.1.3.24', '1.1.1.58', '1.1.1.133', '3.1.3.12', '1.1.1.14;1.1.1.9', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '1.1.1.271', '3.5.1.57', '1.1.1.124;1.1.1.138;1.1.1.21;1.1.1.287;1.1.1.67;1.1.99.11;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '1.1.1.124;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '2.3.2.7', '3.1.3.29', '3.1.3.-', '1.1.1.134;1.1.1.344', '1.1.1.159;1.1.1.50', '1.1.1.176', '1.1.1.206', '1.1.1.236', '1.1.1.16', '1.1.1.174', '1.1.1.135;1.1.1.187', '1.1.1.187;1.1.1.281', '1.1.1.135;1.1.1.187', '1.1.1.187;1.1.1.281', '1.1.1.238', '1.14.13.74', '1.1.1.146', '1.1.1.213;1.1.1.52', '3.1.3.63', '3.1.3.63', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.57', '1.14.13.57', '1.1.1.213;1.1.1.50', '1.1.1.50', '1.1.1.209;1.1.1.50', '2.-.-.-', '1.1.1.266', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.1.1.282', '1.14.13.94', '1.14.13.96', '1.14.13.97', '3.1.3.21;3.1.3.25;3.1.3.29', '3.1.3.21;3.1.3.25', '1.14.13.138', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.-.-', '1.14.-.-', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.147', '1.14.13.-', '1.1.1.380', '1.1.1.1;1.1.1.391', '1.1.1.-;1.1.1.146;1.1.1.209;1.1.1.213;1.1.1.392;1.1.1.50', '3.1.3.73', '1.1.1;1.1.1.-', '3.1.3', '3.1.3', '1.1.1.159', '1.1.1.-', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.1.1;1.1.1.10', '1.1.1.153', '1.1.1.10;1.1.1.14;1.1.1.15', '3.1.3.45', '1.1.1.-;1.1.1.M53', '3.1.3', '3.1.3.68', '1.14.13.127', '1.14.13.127', '3.5.1.11;3.5.1.4', '3.5.1.4', '3.5.1.30', '1.5.1.43', '1.1.1.414', '3.5.1.-;3.5.1.4', '3.5.1.4', '1.1.1.201', '1.1.1', '3.1.3.M8', '1.1.1', '1.1.1.104', '1.1.1.266', '3.1.3.106;3.1.3.76', '1.1.1.367', '1.1.1.57', '1.1.1.406', '1.1.1.407', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '1.14.19.55', '1.14.19.55', '1.14.13.9', '1.14.13.9', '1.5.1.43', '1.1.1.14', '1.1.1', '1.1.1.10', '1.1.3.10', '1.1.3.10', '3.1.3.58;3.1.3.9', '3.1.6.3', '3.2.1.14', '3.2.1.37', '3.2.1.37', '3.2.1.55', '3.2.1.55', '3.2.1.3;3.2.1.58;3.2.1.59', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.1.1.274', '1.1.1.297', '1.1.1.297', '1.14.-.-;1.14.13.-', '1.14.13.126', '1.14.-.-', '1.14.-.-', '3.2.1.116', '3.2.1.137', '3.2.1.154', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.4.15.6', '3.4.19.9', '3.4.19.5', '3.4.19.7', '3.2.1.1', '1.1.1.-', '1.7.3.-', '1.7.3.-', '1.7.3.-', '1.14.13.112', '1.14.13.112', '1.14.13.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.1.1.-', '3.2.1.2', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.-', '1.14.13.-', '1.14.15.5', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '3.2.1.137', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.96', '1.1.1.-', '3.1.3.27', '1.1.1.-', '1.14.13.138', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.183', '1.14.13.184', '3.1.1.101', '3.1.3', '3.1.3.73', '3.2.1.143', '3.1.3.73', '3.1.3', '3.1.3.73', '4.2.1.140;4.2.1.39', '3.1.3.73', '3.1.3.73', '3.1.3.73', '4.2.1.6', '1.14.13.M64', '1.1.1.M51', '3.1.3.73', '1.1.1.M51', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.106', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '1.1.1.-;1.1.1.1;1.1.1.327', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.1.1.184;1.1.1.189', '3.1.3.82', '3.1.3.29;3.1.3.50', '3.1.3.50', '1.14.13.-', '1.14.13.-', '1.1.1.271', '1.1.1.271', '1.1.99.13', '3.1.3.58;3.1.3.9', '1.17.99.5', '1.14.13.97', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.4.19.5;3.5.1.1;3.5.1.26;3.5.1.38;3.5.5.4', '3.5.1.1', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '1.1.5.3;1.1.99.5', '1.1.1.367', '1.1.1.-', '1.14.13.-', '1.14.13.-', '1.1.1.395', '1.1.1', '1.14.13', '1.1.1.146', '1.1.1.239', '1.1.1.238', '1.11.2.6', '1.11.2.6', '1.1.1.206', '1.1.1;1.1.1.206', '3.1.3.76', '3.1.3.76', '1.1.1.102', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '4.2.3;4.2.3.1', '1.1.1;1.1.1.69', '1.1.1.213;1.1.1.50', '6.3.1.1;6.3.5.4', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '3.1.3.1;3.1.3.75', '1.1.1.261', '3.1.3.1;3.1.3.19;3.1.3.2;3.1.3.25;3.1.3.29', '1.1.1.8;1.1.1.94;1.1.5.3', '1.1.1.49;1.1.1.8;1.1.1.94;1.3.1.20', '3.1.3.2;3.1.3.21']
58
365
ATORVASTATIN CALCIUM
5

100%|██████████| 11047/11047 [00:03<00:00, 3407.44it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3719.26it/s]
  6%|▌         | 16/271 [03:31<57:45, 13.59s/it]

rxndb num 2469
failedrxn num 0
result_df 188

100%|██████████| 11047/11047 [00:03<00:00, 3203.68it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3676.07it/s]
  6%|▋         | 17/271 [03:45<58:09, 13.74s/it]

rxndb num 140
failedrxn num 0
result_df 26
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.224', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.234', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.79', '1.14.13.79', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.13.99.3', '1.14.13.79', '1.14.13.79', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.182', '1.14.13.182', '1.13.99.3']
5
24
BAMBUTEROL
5

100%|██████████| 11047/11047 [00:02<00:00, 3959.73it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3408.67it/s]
  7%|▋         | 18/271 [03:59<58:39, 13.91s/it]

rxndb num 436
failedrxn num 0
result_df 33
['3.1.3.69', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '3.1.3.-', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.27', '3.1.3.3', '3.1.3;3.1.3.2', '3.1.3.74', '1.5.3.13;1.5.3.17', '1.5.3.13', '1.5.3.13;1.5.3.17', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.14.18.1', '1.14.18.1', '3.1.3.2;3.1.3.29;3.1.3.38', '3.1.3.39', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.4', '1.14.13.4', '3.1.3.40', '3.1.6.9', '3.1.6.10', '3.1.3.14', '1.14.13.-', '1.14.13.-', '3.1.3.69', '1.1.1.362', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.-.-.-', '3.1.1.1', '3.1.1.1', '1.14.13.8', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '3.1.3.-;3.1.3.88', '3.1.3.79', '1.5.3.15;1.5.3.17', '1.5.1.-;1.5.1.43', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '3.1.3.80', '3.1.3.85', '1.14.-.-', '3.1.3.83', '1.1.1.349', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '3.1.3.103', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '3.1.3.3', '3.1.3', '1.5.3.14', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.1.1.362', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3', '3.1.3.4', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '3.1.3;3.1.3.-;3.1.3.104;3.1.3.2;3.1.3.29', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.1;3.1.1.1;3.1.1.14;3.1.1.2;3.1.1.7;3.1.1.74;3.1.1.88;3.1.2.12;3.1.2.2', '3.1.6.14', '3.1.1;3.1.1.1;3.1.1.2', '3.1.3.29', '3.1.3.33;3.1.3.5', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.8', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.18.1', '1.14.18.1', '3.1.3', '3.1.3', '3.1.1;3.1.1.1;3.1.1.2;3.1.1.74;3.1.1.88;3.1.2.12', '3.1.3', '3.1.3', '3.1.6.3', '3.1.3.68', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.13.36', '1.14.13.36', '1.1.1.-', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.55', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.82', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '6.3.2.17', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.145;3.2.1.23', '3.2.1.110', '3.2.1.31', '3.2.1.35', '3.1.3.91', '3.6.1;3.6.1.-', '1.1.1.246;1.1.1.348', '1.14.14.91', '1.14.14.91', '3.2.1.137;3.2.1.78', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '2.4.1.-', '3.1.3.23;3.1.3.29;3.1.3.9', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.27', '1.5.3.11;1.5.3.13;1.5.3.16;1.5.3.17', '1.14.13.30', '3.1.3', '3.1.3.24', '3.1.3.12', '3.1.3.29', '3.1.3.-', '3.1.3.63', '3.1.3.63', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.-.-', '1.14.-.-', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '3.1.3.73', '3.1.3', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '3.1.3.45', '3.1.3.68', '1.5.1.43', '3.1.3.M8', '3.1.3.106;3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '1.14.13.9', '1.14.13.9', '1.1.1.50', '1.5.1.43', '3.1.3.58;3.1.3.9', '3.1.6.3', '3.2.1.14', '3.2.1.37', '3.2.1.37', '3.2.1.3;3.2.1.58;3.2.1.59', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.14.-.-', '1.14.-.-', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.4.15.6', '3.4.19.9', '3.4.19.5', '3.4.19.7', '3.2.1.1', '1.7.3.-', '1.7.3.-', '1.7.3.-', '3.2.1.-', '3.2.1.2', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.-', '1.14.13.-', '1.14.15.5', '6.2.1.3', '3.2.1.137', '1.14.13.103', '1.14.13.103', '3.1.3.27', '3.1.1.101', '1.14.13', '3.1.3', '3.1.3.73', '3.2.1.143', '3.1.3.73', '3.1.3', '3.1.3.73', '4.2.1.140;4.2.1.39', '3.1.3.73', '3.1.3.73', '3.1.3.73', '4.2.1.6', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.106', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '3.1.3.82', '1.14.13.-', '1.14.13.-', '1.1.1', '1.1.1', '3.1.3.58;3.1.3.9', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.1.1.422', '1.1.1.423', '1.11.2.6', '1.11.2.6', '1.1.1.422', '1.1.1.423', '3.1.3.76', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '4.2.3;4.2.3.1', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75']
36
204
BENAZEPRIL
5

100%|██████████| 11047/11047 [00:03<00:00, 3143.86it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3430.45it/s]
  7%|▋         | 19/271 [04:14<59:24, 14.14s/it]

rxndb num 802
failedrxn num 0
result_df 89
['1.2.1.3;1.2.1.54', '1.2.1.-;1.2.1.99', '1.1.1.23', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.1.5', '1.2.1.3', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.15', '1.2.1.24;1.2.1.5;1.2.1.88;1.5.1.12', '1.5.1.12', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.2.1.5', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.2.1.40', '3.1.1.70', '3.1.1.51', '1.14.13.72', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.14.13.22', '1.2.1.-;1.2.1.99', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.5.1;1.5.1.-', '1.5.1;1.5.1.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.-.-', '1.2.1.-;1.2.1.M5', '1.2.1.-;1.2.1.83', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.1.1.363;1.1.1.388', '1.1.1.363;1.1.1.388', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.3.2', '6.3.2', '3.1.1;3.1.1.1;3.1.1.3', '1.2.1;1.2.1.-', '3.1.1', '3.1.1', '3.1.1.26', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.1.4', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '1.2.1', '3.1.1', '1.1.1.-', '1.1.1.-', '3.1.1.3', '3.1.1.3', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '1.1.1.179;1.3.1.20', '1.1.1.179;1.3.1.20', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.2.1.19;1.2.1.3', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '3.4.21;3.4.21.62', '3.4.16.5;3.4.21;3.4.21.62', '6.3.1.2', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '6.3.4.2', '3.2.1.78', '3.2.1.78', '1.1.1.47', '1.1.1.47', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.2.3.1', '1.14.13.72', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '3.4.11.5', '3.4.11.5', '3.4.11.5', '1.1.1.23;1.1.1.24', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '6.3.2.17', '6.3.2.17', '6.3.2.17', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '3.2.1.35', '2.3.1.-', '3.1.1', '1.14.-.-', '3.1.1.5', '3.1.1.5', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.23', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.2.1.31', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '3.1.1.10', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.2.1.3', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.72', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.-.-', '1.14.-.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.3.1.-', '1.2.1.31', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.2.1.95;1.2.1.z', '1.2.1.31', '1.2.1.3', '1.1.1.363;1.1.1.388;1.1.1.47;1.1.1.49', '1.1.1.363;1.1.1.388;1.1.1.47;1.1.1.49', '1.14.14.22;1.14.99.46', '3.1.1.116', '1.2.1.101;1.2.1.ah', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.2.1.14', '1.14.-.-', '1.14.-.-', '3.2.1.87', '3.4.15.6', '3.4.15.6', '3.4.15.6', '3.4.19.9', '3.4.19.9', '3.4.19.9', '3.4.19.7', '3.4.19.7', '3.4.19.7', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.2.1.-', '3.1.-.-', '3.1.-.-', '1.14.11.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.72', '1.14.13.72', '1.14.15.5', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '6.2.1.3', '1.2.1.70;6.1.1.17', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '3.1.1.5', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.1.101', '3.1.1.101', '3.1.1.101', '1.14.13', '1.14.13', '3.2.1.143', '3.5.1', '1.1.1.363;1.1.1.49', '1.1.1.363;1.1.1.49', '1.14.13.15', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.2.1.3;1.2.1.40', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.1.1.363;1.1.1.47;1.1.1.49', '1.1.1.363;1.1.1.47;1.1.1.49', '1.1.1.49', '1.1.1.49', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '1.2.1', '1.2.1', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1;1.1.1.206', '1.2.1.5', '1.2.1;1.2.1.19;1.2.1.3', '1.2.1;1.2.1.-;1.2.1.19;1.2.1.3', '1.2.1.3;1.2.1.5', '1.2.1.5']
41
131
BENZBROMARONE
5

100%|██████████| 11047/11047 [00:02<00:00, 4293.00it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4030.44it/s]
  7%|▋         | 20/271 [04:25<56:19, 13.46s/it]

rxndb num 730
failedrxn num 0
result_df 75
['1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.6', '1.14.13.6', '1.14.13.6', '1.14.13.6', '1.14.13.6', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.219;1.14.13.7', '1.14.13.219;1.14.13.7', '1.14.13.219;1.14.13.7', '1.14.13.219;1.14.13.7', '1.14.13.219;1.14.13.7', '1.1.1.256', '1.1.1.256', '1.14.13.-;1.14.13.20;1.14.13.7', '1.14.13.-;1.14.13.20;1.14.13.7', '1.14.13.-;1.14.13.20;1.14.13.7', '1.14.13.-;1.14.13.20;1.14.13.7', '1.14.13.-;1.14.13.20;1.14.13.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.17.1.3', '1.17.1.3', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.17.1.3', '1.14.13.180', '1.97.1.-', '1.97.1.-', '1.97.1.-', '1.97.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.-.-', '1.13.12.20', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.220', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13;1.14.13.-', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.99', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.1.1;1.1.1.-', '1.1.1;1.1.1.-', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.15.15', '1.14.13;1.14.14', '1.14.13;1.14.14', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '3.8.1.6', '3.8.1.6', '3.8.1.6', '3.8.1.6', '3.8.1.6', '3.8.1.6', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.12.9', '1.14.12.9', '1.14.12.9', '1.14.12.9', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.21', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.-', '1.14.13.-', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.82', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.76', '3.2.1.31', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.-.-', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.-.-', '1.14.-.-', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.-.-;1.14.13.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '3.2.1.14', '1.14.-.-', '1.14.-.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.15.5', '3.2.1.15', '4.2.2.2', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.1.1.256', '1.1.1.256', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.194', '1.14.13', '1.14.13.236', '1.14.13.236', '1.14.13.236', '1.14.13.236', '1.14.13.236', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.27', '1.14.14.27', '1.14.14.27', '1.14.14.27', '1.14.14.27', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127']
26
80
BENZTHIAZIDE
5

100%|██████████| 11047/11047 [00:03<00:00, 3521.60it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4111.28it/s]
  8%|▊         | 21/271 [04:38<55:17, 13.27s/it]

rxndb num 55
failedrxn num 0
result_df 20
['1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.8.1.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.2.1.35', '3.2.1.35', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.-.-.-']
7
12
BETAMETHASONE ACETATE
5

100%|██████████| 11047/11047 [00:04<00:00, 2560.21it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3465.49it/s]
  8%|▊         | 22/271 [04:54<57:47, 13.93s/it]

rxndb num 3478
failedrxn num 0
result_df 170

100%|██████████| 11047/11047 [00:03<00:00, 2880.95it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3836.61it/s]
  8%|▊         | 23/271 [05:07<57:17, 13.86s/it]

rxndb num 4141
failedrxn num 0
result_df 232

100%|██████████| 11047/11047 [00:03<00:00, 3261.17it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3815.74it/s]
  9%|▉         | 24/271 [05:21<56:42, 13.78s/it]

rxndb num 1070
failedrxn num 0
result_df 54
['3.1.3.69', '1.1.1.14;1.1.1.6', '1.1.1.1;1.1.1.10;1.1.1.156;1.1.1.2;1.1.1.21;1.1.1.72;1.3.1.20', '3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.27', '3.1.3.3', '3.1.3;3.1.3.2', '3.1.3.74', '1.5.3.13;1.5.3.17', '1.5.3.13', '1.5.3.13;1.5.3.17', '1.14.14.1', '1.14.14.1', '2.5.1.46', '3.1.3', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '1.5.3.14;1.5.99.6', '3.1.6.2', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.1.1;1.1.1.10', '1.14.18.1', '1.14.18.1', '3.1.3.2;3.1.3.29;3.1.3.38', '1.1.1.137', '1.1.1.137;1.1.1.405', '1.1.1.69', '3.1.3.22;3.1.3.23', '1.1.1;1.1.1.207', '3.1.3.39', '1.1.1.1;1.1.1.163;1.1.1.184;1.1.1.245;1.1.1.90', '1.1.1.148', '1.14.14.1', '1.14.14.1', '1.1.3.16', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.1.1;1.1.1.208', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.147', '1.1.1.147', '1.1.1.101', '1.14.13.4', '1.14.13.4', '3.1.3.40', '1.1.1.143', '1.1.1.142', '3.1.6.9', '3.1.6.10', '1.1.1;1.1.1.-', '1.1.1.230', '1.-.-.-;1.1.1.342', '1.1.1.226', '3.1.3.14', '1.1.1.62', '1.1.1.62', '1.1.1.146', '1.1.1.53', '1.1.1.50', '1.1.1.53', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.1.1.166', '1.14.13.-', '1.14.13.-', '1.1.1.2;1.1.1.21;1.1.1.261', '1.1.1.263', '1.1.1.270', '3.1.3.69', '1.1.1.274', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.297', '1.1.1;1.1.1.-', '1.1.1.364', '1.17.1.3', '1.17.1.3', '1.14.13.-', '1.17.1.3', '1.14.13.-', '1.14.13.-;1.14.15.-;1.14.15.3', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.270', '3.1.3.76', '1.14.13.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.-', '1.1.1;1.1.1.-;1.1.1.50', '1.-.-.-', '1.1.1.292', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.162', '1.1.1.-', '1.1.1.-', '1.1.1.-;1.1.1.341;4.2.1.-', '1.14.13.-', '1.14.13.-', '1.1.1.274;1.1.1.346', '1.1.1.-;1.1.1.329', '3.1.3.-;3.1.3.88', '1.1.1.297', '1.1.1.-', '1.1.1.239;1.1.1.62', '1.1.1.213', '1.1.1.209;1.1.1.213;1.1.1.357', '1.1.1.62', '3.1.3.79', '1.5.3.15;1.5.3.17', '1.5.1.-;1.5.1.43', '1.1.3.-;1.1.3.45', '1.1.1.297', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.1.1.301', '3.1.3.85', '1.14.-.-', '3.1.3.83', '1.1.1.323', '1.1.1.323', '1.1.1.-;1.1.1.329', '1.1.1.335', '1.1.1.340;1.14.13.-', '1.1.1.339;1.1.1.344', '1.14.13.-', '1.1.1.355', '1.1.1.356', '1.1.1.356', '1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.361', '3.1.3.92', '1.1.1.364', '1.1.1.367', '1.11.2.5', '1.11.2.5', '1.5.1.48', '1.1.1.374', '1.1.1.385', '1.1.1.389', '1.14.13.209', '1.14.13.209', '1.1.1.393', '3.1.3.101', '3.1.3.-', '1.1.1.-', '1.1.1.-', '1.1.1.-', '3.1.3;3.1.3.-', '1.1.1.-', '1.1.1.402', '1.1.1.14;1.1.1.162;1.1.1.403', '1.14.-.-', '1.14.-.-', '2.1.1.-', '3.1.3.103', '1.1.1.251', '1.1.1.289', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.1.1.395', '1.1.1.-;1.1.1.395', '1.1.1.14;1.1.1.15', '1.1.1', '1.1.1.14', '1.1.3.11', '3.1.3.3', '3.1.3', '1.5.3.16', '1.5.3.14', '3.1.3.-', '1.1.1;1.1.1.-', '3.1.3;3.1.3.-', '1.1.1.201', '1.1.1.-;1.1.1.50;1.1.1.52', '1.1.1.391', '1.1.1.15', '1.1.1.-;1.1.1.270', '1.1.1;1.1.1.-;1.1.1.270', '1.1.1.-;1.1.1.270', '3.1.3;3.1.3.-', '1.1.1;1.1.1.-;1.1.1.12', '1.1.1', '1.1.1', '3.1.6;3.1.6.-', '1.1.1.102', '1.1.1.-;1.1.1.393', '1.1.1.145', '1.1.1;1.1.1.-', '1.1.1;1.1.1.-', '1.14.14.133', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1', '1.1.1', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.1.1', '3.1.3.50', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.1.1.101', '1.1.1', '1.1.1', '3.1.3', '3.1.6.c', '3.1.3.4', '1.1.1.201', '3.1.3.4', '1.1.1', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1', '1.14.13', '1.1.1.M2', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.M11', '1.1.1.M11', '1.1.1.M11', '1.1.1.392', '1.1.1.393', '1.1.1.52', '1.1.1.391', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.52', '1.1.1.391', '1.1.1.392;1.1.1.50;1.1.1.52', '1.1.1.392', '1.1.1.393', '1.1.1.393', '3.1.3', '1.1.1.M28', '1.1.1.14;1.1.1.M29', '1.1.1', '1.5.3.14', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '3.1.3;3.1.3.-;3.1.3.104;3.1.3.2;3.1.3.29', '3.1.3', '3.1.3;3.1.3.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1.270', '1.1.1.270', '1.1.1.140', '1.1.1.123', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.2;1.1.1.213;1.1.1.239;1.1.1.62;1.3.1.20', '1.1.1.159', '1.1.1.218', '3.1.6.14', '1.1.1.218', '1.1.1.1', '1.1.1.188;1.1.1.213;1.1.1.50', '1.1.1.1', '3.1.3.29', '3.1.3.29', '1.14.15.15', '1.5.3.16', '1.1.1.149', '1.1.1.145', '1.1.1.1', '1.1.1.1', '1.1.1.1', '1.1.1.1', '1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50;1.3.1.20', '1.1.1.140;1.1.1.17', '3.1.3.33;3.1.3.5', '1.1.1.133', '1.1.1.239;1.1.1.51', '1.1.1.239;1.1.1.51', '1.1.1.239', '1.1.1.184', '1.1.1;1.1.1.184;1.1.1.62', '1.1.1.184;1.1.1.2;1.1.1.62', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.213;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.50', '1.1.1.51', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.1.1;1.1.1.209', '1.1.1.292', '1.1.1', '1.1.1.209', '1.1.1.209', '1.1.1.209', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.1.1', '1.1.1.357;1.1.1.50', '1.1.1.210;1.1.1.357', '1.14.18.1', '1.14.18.1', '3.1.3', '3.1.3', '1.14.14.55', '1.14.14.55', '1.14.14.55', '3.2.1.78', '3.2.1.78', '3.2.1.78', '1.1.1.184;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.50', '1.1.1.184;1.1.1.50', '1.1.1.184;1.1.1.188;1.1.1.2', '1.1.1.12;1.1.1.14', '1.1.1.12;1.1.1.14', '1.1.1.12', '1.1.1;1.1.1.10;1.1.1.405', '1.1.1.10', '1.1.1;1.1.1.1', '3.1.3', '3.1.3', '1.1.1.146;1.1.1.159;1.1.1.50', '3.1.6.3', '1.1.99.13', '3.1.3.68', '1.1.1.162', '1.1.1.-', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.1.1.146', '1.1.1.133', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.297', '1.14.13.36', '1.14.13.36', '3.2.1.154;3.2.1.26;3.2.1.80', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.55', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '1.1.1.-', '3.2.1.65', '3.2.1.145;3.2.1.23', '3.2.1.110', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.1.1.125;1.1.1.127', '3.1.3.91', '3.6.1;3.6.1.-', '3.2.1.137;3.2.1.78', '1.1.1.104', '1.1.1.104', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '1.1.1.239;1.1.1.51', '1.1.1;1.1.1.239;1.1.1.62;1.1.1.64', '2.4.1.-', '1.1.1.104', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.-;1.1.1.146', '1.1.1;1.1.1.-;1.1.1.146;1.1.1.51', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62;1.1.1.63', '1.1.1.184;1.1.1.2;1.1.1.213;1.1.1.51;1.1.1.64', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.2;1.1.1.209;1.1.1.21;1.1.1.213;1.1.1.50;1.3.1.20', '3.1.3.23;3.1.3.29;3.1.3.9', '1.1.1.124;1.1.1.138;1.1.1.14;1.1.1.67;1.1.99.11;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.1.3.27', '1.5.3.11;1.5.3.13;1.5.3.16;1.5.3.17', '1.5.3;1.5.3.13;1.5.3.16;1.5.3.17', '1.1.1.166;1.1.1.24;1.1.1.282', '1.1.1.14;1.1.1.56', '1.14.13.30', '1.14.14.1', '1.14.14.1', '3.1.3', '1.1.1.12;1.1.1.124;1.1.1.138;1.1.1.14;1.1.1.67;1.1.1.9;1.1.99.11;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.1.3.24', '1.1.1.58', '1.1.1.133', '3.1.3.12', '1.1.1.14;1.1.1.9', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '1.1.1.271', '1.1.1.124;1.1.1.138;1.1.1.21;1.1.1.287;1.1.1.67;1.1.99.11;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '1.1.1.124;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.1.3.29', '1.1.1;1.1.1.148;1.1.1.209', '3.1.3.-', '1.1.1.134;1.1.1.344', '1.1.1.159;1.1.1.50', '1.1.1.176', '1.1.1.206', '1.1.1.236', '1.1.1.16', '1.1.1.198', '1.1.1.227', '1.1.1.241', '1.1.1.174', '1.1.1.135;1.1.1.187', '1.1.1.187;1.1.1.281', '1.1.1.135;1.1.1.187', '1.1.1.187;1.1.1.281', '1.1.1.51', '1.1.1.51;1.1.1.62;1.1.1.64', '1.1.1.238', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.1.1.201', '1.1.1.146', '1.1.1.213;1.1.1.52', '3.1.3.63', '3.1.3.63', '1.1.1.152;1.1.1.184;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1.184;1.1.1.209;1.1.1.213;1.1.1.50', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.1.1.213;1.1.1.50', '1.1.1.50', '1.1.1.209;1.1.1.50', '1.1.1.213;1.1.1.50;1.1.1.51', '1.1.1.149;1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '2.-.-.-', '2.-.-.-', '1.1.1.266', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.1.1.213;1.1.1.277;1.1.1.50', '1.14.13.79', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.1.1.282', '1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.278', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '3.1.3.21;3.1.3.25;3.1.3.29', '3.1.3.21;3.1.3.25', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.-.-', '1.14.-.-', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.-.-;1.14.13.-', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.1.1.210;1.1.1.357;1.1.1.50;1.1.1.51', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.380', '1.1.1.1;1.1.1.391', '1.1.1.-;1.1.1.146;1.1.1.209;1.1.1.213;1.1.1.392;1.1.1.50', '3.1.3.73', '1.1.1;1.1.1.-', '3.1.3', '3.1.3', '1.1.1.159', '1.14.14.149', '1.14.14.149', '1.1.1.-', '1.1.1.270', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.1.1;1.1.1.10', '1.1.1.153', '1.1.1.10;1.1.1.14;1.1.1.15', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.213;1.1.1.50;1.1.1.51;1.1.1.53', '3.1.3.45', '1.1.1.-;1.1.1.M53', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.3', '3.1.3.68', '1.5.1.43', '1.1.1.414', '1.1.1.270', '3.1.6.d', '1.1.1.270', '1.1.1.270', '1.1.1.201', '1.1.1', '3.1.3.M8', '1.1.1', '1.1.1.104', '1.1.1.322', '1.1.1.322', '1.1.1.323', '1.1.1.323', '1.1.1.266', '3.1.3.106;3.1.3.76', '1.1.1.367', '1.1.1.57', '1.1.1.406', '1.1.1.407', '1.1.1.64', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '1.14.13.9', '1.14.13.9', '1.5.1.43', '1.1.1;1.1.1.206', '1.1.1;1.1.1.206', '1.1.1', '1.1.1', '1.1.1', '1.14.14.70', '1.14.14.70', '1.1.1.14', '1.1.1', '1.1.1.10', '1.1.3.10', '1.1.3.10', '3.1.3.58;3.1.3.9', '3.1.6.3', '3.2.1.37', '3.2.1.37', '3.2.1.55', '3.2.1.55', '3.2.1.3;3.2.1.58;3.2.1.59', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.1.1.227', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.1.1.274', '1.1.1.297', '1.1.1.297', '1.14.-.-;1.14.13.-', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.143', '1.1.1.323', '1.1.1.323', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.2.1.87', '3.2.1.1', '1.1.1.-', '1.7.3.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.-', '1.14.13.-', '1.14.13.-', '3.2.1.2', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.15.5', '1.1.1.-;1.1.1.270', '1.1.1.-;1.1.1.270', '1.14.13.79', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '3.2.1.137', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.1.1.-', '3.1.3.27', '1.1.1.-', '1.1.1.-', '1.1.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.194', '1.14.13', '3.1.3', '3.1.3.73', '3.2.1.143', '3.2.1.143', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.14.13.M64', '1.14.13.M64', '1.1.1.M51', '3.1.3.73', '1.1.1.M51', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.106', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '1.1.1.-;1.1.1.1;1.1.1.327', '1.1.1.270', '1.14.13.98', '1.14.13.98', '1.14.13.98', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.1.1.184;1.1.1.189', '3.1.3.82', '3.1.3.29;3.1.3.50', '3.1.3.50', '1.1.1.296', '1.1.1.296', '1.14.13.-', '1.14.13.-', '1.1.1;1.1.1.51;1.1.1.62', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.1.1.271', '1.1.1.271', '1.1;1.1.1;1.1.1.209;1.1.1.213', '1.1.1.1', '1.1.99.13', '3.1.3.58;3.1.3.9', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.1.1;1.1.1.184;1.1.1.210;1.1.1.50', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.2;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.3.1.20', '1.1.1.184;1.1.1.357', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.1.5.3;1.1.99.5', '1.1.1.367', '1.1.1.-', '1.14.13.-', '1.14.13.-', '1.1.1.395', '1.1.1', '1.1.1.146', '1.1.1.64', '1.1.1.146', '1.1.1.146', '1.1.1.239', '1.1.1.239', '1.1.1.62', '1.1.1.270', '1.1.1.238', '1.11.2.6', '1.11.2.6', '1.1.1.206', '3.1.3.76', '3.1.3.76', '1.1.1.102', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '4.2.3;4.2.3.1', '1.1.1;1.1.1.69', '1.1.1.213;1.1.1.50', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '3.1.3.1;3.1.3.75', '1.1.1.261', '3.1.3.1;3.1.3.19;3.1.3.2;3.1.3.25;3.1.3.29', '1.1.1.8;1.1.1.94;1.1.5.3', '1.1.1.49;1.1.1.8;1.1.1.94;1.3.1.20', '3.1.3.2;3.1.3.21']
41
357
BEZAFIBRATE
5

100%|██████████| 11047/11047 [00:02<00:00, 3683.72it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3356.57it/s]
  9%|▉         | 25/271 [05:35<57:14, 13.96s/it]

rxndb num 554
failedrxn num 0
result_df 67
['1.2.1.3;1.2.1.54', '1.2.1.-;1.2.1.99', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.2.1.3', '1.14.13.15', '1.2.1.24;1.2.1.5;1.2.1.88;1.5.1.12', '1.5.1.12', '1.2.1.3;1.2.1.47', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.2.1.5', '1.2.1.26;1.2.1.3', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.5.1.40', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.2.1.33', '1.14.12.9', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.2.1.40', '3.8.1.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.180', '1.14.13.-', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.2.1.-;1.2.1.99', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.-.-', '1.2.1.-;1.2.1.M5', '1.2.1.-;1.2.1.83', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.2.1.98', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13;1.14.13.-', '1.2.1;1.2.1.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.1', '1.14.19', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '1.2.1', '1.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.2.1.-;1.2.1.26;1.2.1.3', '1.2.1.47', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.2.1.19;1.2.1.3', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '6.3.1.2', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '6.3.4.2', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.12.9', '1.14.12.9', '1.14.12.9', '1.14.12.9', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.2.3.1', '1.14.13.-', '1.14.13.154', '1.14.13.154', '1.14.13.72', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.-', '3.4.11.5', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.82', '3.2.1.15;3.2.1.82', '6.3.2.17', '6.3.2.17', '1.5.1.12;1.5.99.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.-.-', '2.4.1.-', '1.14.13.30', '1.1.1.-', '1.1.1.136', '1.1.1.132', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.2.1.31', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.2.1.3', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.72', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.79', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.-.-', '1.14.-.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.2.1.31', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.1.1.-;1.1.1.336', '1.1.1.22', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.2.1.95;1.2.1.z', '1.2.1.31', '1.2.1;1.2.1.-;1.2.1.19;1.2.1.3;1.2.1.5', '1.14.14.22;1.14.99.46', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.1.1.420', '1.2.1.101;1.2.1.ah', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '1.14.-.-', '1.14.-.-', '3.2.1.87', '3.4.15.6', '3.4.15.6', '3.4.19.9', '3.4.19.9', '3.4.19.7', '3.4.19.7', '1.3.98.-', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.2.1.-', '1.2.1.3', '1.14.11.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.15.5', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '6.2.1.3', '1.2.1.70;6.1.1.17', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.1.101', '3.1.1.101', '1.14.13', '3.5.1', '1.14.13.15', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.19.58', '1.2.1.3;1.2.1.40', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.2.1', '1.2.1', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.2.1.29;1.2.1.3;1.2.1.5', '1.2.1.5', '1.2.1.3;1.2.1.5', '1.2.1.5', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.2.1.5', '1.2.1.3;1.2.1.5', '1.2.1.5', '1.2.1;1.2.1.19;1.2.1.3', '1.2.1.29;1.2.1.5;1.2.1.53', '1.2.1;1.2.1.88;1.5.1.12;1.5.99.8', '1.2.1.5', '1.2.1;1.2.1.-;1.2.1.19;1.2.1.3']
40
121
BICALUTAMIDE
5

100%|██████████| 11047/11047 [00:02<00:00, 4158.18it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3864.65it/s]
 10%|▉         | 26/271 [05:48<55:01, 13.48s/it]

rxndb num 223
failedrxn num 0
result_df 32
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.1.1.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '3.1.3.-', '3.1.3.27', '3.1.3.73', '3.1.3.39', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.1.3.40', '3.1.6.9', '3.1.6.10', '3.4.22.40;3.5.1.72', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.1.3.-;3.1.3.88', '3.1.3.83', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '6.3.1.18', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.5.1.123', '3.1.3', '3.1.3.-', '3.1.6;3.1.6.-', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '3.5.1', '3.1.6.14', '3.4.11.3;3.4.11.6;3.4.22.40', '3.1.3.29', '2.3.2.2;3.4.11.10;3.4.19.3', '3.1.3.33;3.1.3.5', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.4.21.4;3.4.22;3.4.22.1', '3.3.2.6;3.4.11.10;3.4.11.15', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3.68', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.-.-', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '3.1.3.91', '3.6.1;3.6.1.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.27', '3.1.3.11;3.1.3.37', '3.1.3.29', '3.1.3.-', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.140', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '3.1.3.73', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.1.3.M8', '3.1.3.107', '3.1.3.105', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.1.3.29', '3.2.1.-', '3.2.1.-', '1.14.13.-;1.14.13.188', '3.1.3.27', '1.14.13.140', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '3.1.3.82', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '3.1.3.76', '4.2.3;4.2.3.1', '3.1.3.-;3.1.3.104']
25
91
BIPERIDEN
5

100%|██████████| 11047/11047 [00:02<00:00, 4174.68it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3801.11it/s]
 10%|▉         | 27/271 [06:01<54:08, 13.31s/it]

rxndb num 944
failedrxn num 0
result_df 75
['3.1.3.69', '3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.74', '3.1.3.27', '3.1.3.74', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '1.3.1.70', '1.3.1.70', '1.3.1.70', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.6.2', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '3.1.3.39', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.6.9', '3.1.6.10', '3.1.3.69', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.1.3.-;3.1.3.88', '3.1.3.79', '3.1.3.85', '3.1.3.83', '1.14.13.-', '3.1.3.92', '1.14.13.209', '1.14.13.209', '1.14.13.209', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.3.103', '3.1.3', '3.1.3.-', '3.1.3;3.1.3.-', '1.3.1.70', '1.3.1.70', '1.3.1.70', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.14.14.133', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.14', '1.14.14', '1.14.14', '3.1.3', '3.1.3.4', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '1.3.1', '3.1.6.14', '3.1.3.29', '3.1.3.33;3.1.3.5', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '3.1.3', '3.1.3', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '3.2.1.78', '3.2.1.78', '3.2.1.78', '3.1.3', '3.1.3', '3.1.3.68', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.65', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '3.1.3.91', '3.6.1;3.6.1.-', '3.1.3.2;3.1.3.31;3.1.3.34', '1.3.1;1.3.1.-', '1.3.1;1.3.1.-', '3.1.3.29', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.3.1.70', '1.3.1.70', '1.3.1.70', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.1.3.27', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.24', '3.1.3.12', '3.1.3.29', '3.1.3.-', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '3.1.3.63', '3.1.3.63', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.3.1.70', '1.3.1.70', '1.3.1.70', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '3.1.3.45', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.3.68', '1.3.1.70', '1.3.1.70', '1.3.1.70', '1.3.1.70', '1.3.1.70', '1.3.1.70', '3.1.3.M8', '1.14.13.-', '3.1.3.105', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.1', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.3.1.-', '1.3.1.-', '1.3.1.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '3.2.1.2', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.3.1.70', '1.3.1.70', '1.3.1.70', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '3.1.3.27', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.156', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '3.1.3.82', '1.3.99.-', '1.3.99.-', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '3.1.3.76', '3.1.3.76', '4.2.3;4.2.3.1', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '3.1.3.1;3.1.3.75']
26
137
BISACODYL
5

100%|██████████| 11047/11047 [00:02<00:00, 3809.58it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4057.91it/s]
 10%|█         | 28/271 [06:13<53:09, 13.13s/it]

rxndb num 765
failedrxn num 0
result_df 75
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.1.1.118;1.1.1.47', '1.1.1.119;1.1.1.47', '1.17.1.5', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.6', '1.14.13.6', '1.14.13.6', '1.14.13.6', '1.14.13.6', '3.1.1.55', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.19', '1.14.13.19', '1.1.1.173;1.1.1.378', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '3.1.1.1;3.1.1.56', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.61', '1.14.13.61', '1.14.13.219;1.14.13.7', '1.14.13.219;1.14.13.7', '1.14.13.219;1.14.13.7', '1.14.13.219;1.14.13.7', '1.14.13.219;1.14.13.7', '1.14.12.-', '1.14.12.-', '1.14.12.-', '1.14.12.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.181', '1.14.13.-;1.6.5.2', '1.14.13.-;1.6.5.2', '1.14.13.-;1.6.5.2', '1.14.13.-;1.6.5.2', '1.14.13.-;1.6.5.2', '1.14.13.-', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.13.130', '1.14.13.244;1.14.13.M20', '1.14.13.244;1.14.13.M20', '1.14.13.244;1.14.13.M20', '1.14.13.244;1.14.13.M20', '1.14.13.244;1.14.13.M20', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.1.1.203', '1.1.1.203', '1.1.1.363;1.1.1.388', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.220', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13.224', '1.14.13.224', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.1.1.203', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.235', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.1.1.-;1.1.1.377;1.1.1.378', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '1.14.13.M33', '1.14.13.M33', '1.14.13.M33', '1.14.13.M33', '1.14.13.M33', '1.1.1.-', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '3.1.1;3.1.1.1;3.1.1.14;3.1.1.2;3.1.1.7;3.1.1.74;3.1.1.88;3.1.2.12;3.1.2.2', '3.1.1;3.1.1.1;3.1.1.2', '3.1.1.1;3.1.1.13', '1.1.1.179;1.3.1.20', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.1.13;3.1.1.2;3.1.1.3', '1.14.13.84', '1.14.13.84', '1.14.13.84', '3.1.1.1', '1.14.13.84', '3.1.1.1', '3.1.1.1', '3.1.1.1', '1.14.14;1.14.14.1;1.14.14.25', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.1;3.1.1.1;3.1.1.2;3.1.1.74;3.1.1.88;3.1.2.12', '3.1.1;3.1.1.1', '1.1.1.121', '1.1.1.1;1.2.1.3;1.2.1.88;3.1.1;3.1.1.1;3.1.1.101;3.1.1.2;3.1.1.3;3.1.1.6;3.1.1.7;3.1.1.74;3.1.1.88;3.1.2.12', '1.1.1.47', '1.1.1.122', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.-', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.82', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.76', '3.2.1.31', '1.14.13.10', '1.14.13.10', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.-.-', '2.4.1.-', '1.14.13.30', '3.1.1.2', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.84', '3.1.1;3.1.1.2', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.1.1.107;1.1.1.122', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.2.1.5', '1.2.1.39;1.2.1.5', '1.1.1.363;1.1.1.388;1.1.1.47;1.1.1.49', '1.3.3.8', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.2.3.1', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.1.1.120', '3.2.1.14', '1.1.1.121;1.1.1.175', '1.1.1.121', '1.1.1.179', '1.1.1.179', '1.1.1.121', '1.14.-.-', '3.2.1.87', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.15', '4.2.2.2', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.176', '1.14.13.194', '3.1.1.101', '1.1.1.363;1.1.1.49', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.14.20', '1.14.14.20', '1.14.14.20', '1.14.14.20', '1.14.14.20', '1.1.1.118', '1.1.1.120;1.1.1.179;1.1.1.359;1.1.1.360;1.1.1.47;1.1.1.48;1.3.1.20', '1.1.1.120', '1.1.1.119', '1.1.1.121;1.1.1.359;1.1.1.47;1.1.1.48', '1.1.1.121', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.27', '1.14.14.27', '1.14.14.27', '1.14.14.27', '1.14.14.27', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.1.1.363;1.1.1.47;1.1.1.49', '1.1.1.49', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127']
29
134
BISOPROLOL FUMARATE
5

100%|██████████| 11047/11047 [00:03<00:00, 3140.04it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3928.98it/s]
 11%|█         | 29/271 [06:27<53:09, 13.18s/it]

rxndb num 963
failedrxn num 0
result_df 44
['3.1.3.69', '1.1.1.14;1.1.1.6', '1.1.1.1;1.1.1.10;1.1.1.156;1.1.1.2;1.1.1.21;1.1.1.72;1.3.1.20', '3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.27', '3.1.3.3', '3.1.3;3.1.3.2', '3.1.3.74', '1.5.3.13;1.5.3.17', '1.5.3.13', '1.5.3.13;1.5.3.17', '1.14.14.1', '1.14.14.1', '2.5.1.46', '3.1.3', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '1.5.3.14;1.5.99.6', '3.1.6.2', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.1.1;1.1.1.10', '1.14.18.1', '1.14.18.1', '3.1.3.2;3.1.3.29;3.1.3.38', '1.1.1.137', '1.1.1.137;1.1.1.405', '1.1.1.69', '3.1.3.22;3.1.3.23', '1.1.1;1.1.1.207', '3.1.3.39', '1.1.1.1;1.1.1.163;1.1.1.184;1.1.1.245;1.1.1.90', '1.1.1.148', '1.14.14.1', '1.14.14.1', '1.1.3.16', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.1.1;1.1.1.208', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.147', '1.1.1.147', '1.1.1.101', '1.14.13.4', '1.14.13.4', '3.1.3.40', '1.1.1.143', '1.1.1.142', '3.1.6.9', '3.1.6.10', '1.1.1;1.1.1.-', '1.1.1.230', '1.14.-.-', '1.-.-.-;1.1.1.342', '1.1.1.226', '3.1.3.14', '1.1.1.62', '1.1.1.62', '1.1.1.146', '1.1.1.53', '1.1.1.50', '1.1.1.53', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.1.1.166', '1.14.13.-', '1.14.13.-', '1.1.1.2;1.1.1.21;1.1.1.261', '1.1.1.263', '1.1.1.270', '3.1.3.69', '1.1.1.274', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.297', '1.1.1;1.1.1.-', '1.1.1.364', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.15.-;1.14.15.3', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.1.1.270', '3.1.3.76', '1.14.13.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.-', '1.1.1;1.1.1.-;1.1.1.50', '1.-.-.-', '1.-.-.-', '1.1.1.292', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.162', '1.1.1.-', '1.1.1.-', '1.1.1.-;1.1.1.341;4.2.1.-', '1.14.13.-', '1.14.13.-', '1.1.1.274;1.1.1.346', '1.1.1.-;1.1.1.329', '3.1.3.-;3.1.3.88', '1.1.1.297', '1.1.1.-', '1.1.1.239;1.1.1.62', '1.1.1.213', '1.1.1.209;1.1.1.213;1.1.1.357', '1.1.1.62', '3.1.3.79', '1.5.3.15;1.5.3.17', '1.5.1.-;1.5.1.43', '1.1.3.-;1.1.3.45', '1.1.1.297', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.1.1.301', '3.1.3.85', '1.14.-.-', '1.14.-.-', '3.1.3.83', '1.1.1.323', '1.1.1.323', '1.1.1.-;1.1.1.329', '1.1.1.335', '1.1.1.340;1.14.13.-', '1.1.1.339;1.1.1.344', '1.1.1.355', '1.1.1.356', '1.1.1.356', '1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.361', '3.1.3.92', '1.1.1.364', '1.1.1.367', '1.11.2.5', '1.11.2.5', '1.5.1.48', '1.1.1.374', '1.1.1.385', '1.1.1.389', '1.14.13.209', '1.14.13.209', '1.1.1.393', '3.1.3.101', '3.1.3.-', '1.1.1.-', '1.1.1.-', '1.1.1.-', '3.1.3;3.1.3.-', '1.1.1.-', '1.1.1.402', '1.1.1.14;1.1.1.162;1.1.1.403', '1.14.-.-', '1.14.-.-', '2.1.1.-', '3.1.3.103', '1.1.1.251', '1.1.1.289', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.1.1.395', '1.1.1.-;1.1.1.395', '1.1.1.14;1.1.1.15', '1.1.1', '1.1.1.14', '1.1.3.11', '3.1.3.3', '3.1.3', '1.5.3.16', '1.5.3.14', '3.1.3.-', '1.1.1;1.1.1.-', '3.1.3;3.1.3.-', '1.1.1.201', '1.1.1.-;1.1.1.50;1.1.1.52', '1.1.1.391', '1.1.1', '1.1.1', '1.1.1.15', '1.1.1.-;1.1.1.270', '1.1.1;1.1.1.-;1.1.1.270', '1.1.1.-;1.1.1.270', '3.1.3;3.1.3.-', '1.1.1;1.1.1.-;1.1.1.12', '1.1.1', '1.1.1', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.1.1.102', '1.1.1.-;1.1.1.393', '1.1.1.145', '1.1.1;1.1.1.-', '1.1.1;1.1.1.-', '1.14.14.133', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1', '1.1.1', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.1.1', '3.1.3.50', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.1.1.101', '1.14.13', '1.1.1', '1.1.1', '3.1.3', '3.1.6.c', '3.1.3.4', '1.1.1.201', '3.1.3.4', '1.1.1', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.1.1', '1.1.1.M2', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '1.1.1.M11', '1.1.1.M11', '1.1.1.M11', '1.1.1.392', '1.1.1.393', '1.1.1.52', '1.1.1.391', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.52', '1.1.1.391', '1.1.1.392;1.1.1.50;1.1.1.52', '1.1.1.392', '1.1.1.393', '1.1.1.393', '3.1.3', '1.1.1.M28', '1.1.1.14;1.1.1.M29', '1.1.1', '1.5.3.14', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '3.1.3;3.1.3.-;3.1.3.104;3.1.3.2;3.1.3.29', '3.1.3', '3.1.3;3.1.3.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1.270', '1.1.1.270', '1.1.1.140', '1.1.1.123', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.2;1.1.1.213;1.1.1.239;1.1.1.62;1.3.1.20', '1.1.1.159', '1.1.1.218', '3.1.6.14', '1.1.1.218', '1.1.1.1', '1.1.1.188;1.1.1.213;1.1.1.50', '1.1.1.1', '3.1.3.29', '3.1.3.29', '1.14.15.15', '1.14.15.15', '1.5.3.16', '1.1.1.149', '1.1.1.145', '1.1.1.1', '1.1.1.1', '1.1.1.1', '1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50;1.3.1.20', '1.1.1.140;1.1.1.17', '3.1.3.33;3.1.3.5', '1.1.1.133', '1.1.1.239;1.1.1.51', '1.1.1.239;1.1.1.51', '1.1.1.239', '1.1.1.184', '1.1.1;1.1.1.184;1.1.1.62', '1.1.1.184;1.1.1.2;1.1.1.62', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.213;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.50', '1.1.1.51', '1.14.13.126;1.14.15.16', '1.1.1;1.1.1.209', '1.1.1.292', '1.1.1', '1.1.1.209', '1.1.1.209', '1.1.1.209', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.1.1', '1.1.1.357;1.1.1.50', '1.1.1.210;1.1.1.357', '3.1.3', '3.1.3', '1.14.14.55', '3.2.1.78', '3.2.1.78', '3.2.1.78', '1.1.1.184;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.50', '1.1.1.184;1.1.1.50', '1.1.1.184;1.1.1.188;1.1.1.2', '1.1.1.12;1.1.1.14', '1.1.1.12;1.1.1.14', '1.1.1.12', '1.1.1;1.1.1.10;1.1.1.405', '1.1.1.10', '1.1.1;1.1.1.1', '3.1.3', '3.1.3', '1.1.1.146;1.1.1.159;1.1.1.50', '3.1.6.3', '1.1.99.13', '3.1.3.68', '1.1.1.162', '1.1.1.-', '1.14.15.4', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.1.1.146', '1.1.1.133', '1.14.15.4', '1.14.15.6', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.297', '1.14.13.36', '1.14.13.36', '3.2.1.154;3.2.1.26;3.2.1.80', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.55', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '1.1.1.-', '3.2.1.65', '3.2.1.145;3.2.1.23', '3.2.1.110', '1.1.1.125;1.1.1.127', '3.1.3.91', '3.6.1;3.6.1.-', '3.2.1.137;3.2.1.78', '1.1.1.104', '1.1.1.104', '1.14.-.-', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '1.1.1.239;1.1.1.51', '1.1.1;1.1.1.239;1.1.1.62;1.1.1.64', '2.4.1.-', '1.1.1.104', '1.14.-.-', '1.14.-.-', '1.1.1.-;1.1.1.146', '1.1.1;1.1.1.-;1.1.1.146;1.1.1.51', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62;1.1.1.63', '1.1.1.184;1.1.1.2;1.1.1.213;1.1.1.51;1.1.1.64', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.2;1.1.1.209;1.1.1.21;1.1.1.213;1.1.1.50;1.3.1.20', '3.1.3.23;3.1.3.29;3.1.3.9', '1.1.1.124;1.1.1.138;1.1.1.14;1.1.1.67;1.1.99.11;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '3.1.3.27', '1.5.3.11;1.5.3.13;1.5.3.16;1.5.3.17', '1.5.3;1.5.3.13;1.5.3.16;1.5.3.17', '1.1.1.166;1.1.1.24;1.1.1.282', '1.1.1.14;1.1.1.56', '1.14.13.30', '1.14.13.30', '1.14.14.1', '1.14.14.1', '3.1.3', '1.1.1.12;1.1.1.124;1.1.1.138;1.1.1.14;1.1.1.67;1.1.1.9;1.1.99.11;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.1.3.24', '1.1.1.58', '1.1.1.133', '3.1.3.12', '1.1.1.14;1.1.1.9', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '1.1.1.271', '1.1.1.124;1.1.1.138;1.1.1.21;1.1.1.287;1.1.1.67;1.1.99.11;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '1.1.1.124;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.1.3.29', '1.1.1;1.1.1.148;1.1.1.209', '3.1.3.-', '1.1.1.134;1.1.1.344', '1.1.1.159;1.1.1.50', '1.1.1.176', '1.1.1.206', '1.1.1.236', '1.1.1.16', '1.1.1.198', '1.1.1.227', '1.1.1.241', '1.1.1.174', '1.1.1.135;1.1.1.187', '1.1.1.187;1.1.1.281', '1.1.1.135;1.1.1.187', '1.1.1.187;1.1.1.281', '1.1.1.51', '1.1.1.51;1.1.1.62;1.1.1.64', '1.1.1.238', '1.14.13.74', '1.1.1.201', '1.1.1.146', '1.1.1.213;1.1.1.52', '3.1.3.63', '3.1.3.63', '1.1.1.152;1.1.1.184;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1.184;1.1.1.209;1.1.1.213;1.1.1.50', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.1.1.213;1.1.1.50', '1.1.1.50', '1.1.1.209;1.1.1.50', '1.1.1.213;1.1.1.50;1.1.1.51', '1.1.1.149;1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '2.-.-.-', '1.1.1.266', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.1.1.213;1.1.1.277;1.1.1.50', '1.14.13.79', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.1.1.282', '1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.278', '1.14.13.94', '1.14.13.96', '1.14.13.97', '3.1.3.21;3.1.3.25;3.1.3.29', '3.1.3.21;3.1.3.25', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.147', '1.1.1.210;1.1.1.357;1.1.1.50;1.1.1.51', '1.14.13.-', '1.1.1.380', '1.1.1.1;1.1.1.391', '1.1.1.-;1.1.1.146;1.1.1.209;1.1.1.213;1.1.1.392;1.1.1.50', '3.1.3.73', '1.1.1;1.1.1.-', '3.1.3', '3.1.3', '1.1.1.159', '1.1.1.-', '1.1.1.270', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.1.1;1.1.1.10', '1.1.1.153', '1.1.1.10;1.1.1.14;1.1.1.15', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.213;1.1.1.50;1.1.1.51;1.1.1.53', '3.1.3.45', '1.1.1.-;1.1.1.M53', '1.14.13;1.14.13.-', '3.1.3', '3.1.3.68', '1.5.1.43', '1.1.1.414', '1.1.1.270', '3.1.6.d', '1.1.1.270', '1.1.1.270', '1.1.1.201', '1.1.1', '1.1.1.425', '3.1.3.M8', '1.1.1', '1.1.1.104', '1.1.1.322', '1.1.1.322', '1.1.1.323', '1.1.1.323', '1.1.1.266', '3.1.3.106;3.1.3.76', '1.1.1.367', '1.1.1.M48', '1.1.1.57', '1.1.1.406', '1.1.1.407', '1.1.1.64', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '1.14.13.9', '1.14.13.9', '1.5.1.43', '1.1.1;1.1.1.206', '1.1.1;1.1.1.206', '1.1.1', '1.1.1', '1.1.1', '1.14.14.70', '1.14.14.70', '1.1.1.14', '1.1.1', '1.1.1.10', '1.1.3.10', '1.1.3.10', '3.1.3.58;3.1.3.9', '3.1.6.3', '3.2.1.37', '3.2.1.37', '3.2.1.55', '3.2.1.55', '3.2.1.3;3.2.1.58;3.2.1.59', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.1.1.227', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.1.1.274', '1.1.1.297', '1.1.1.297', '1.14.-.-;1.14.13.-', '1.14.-.-;1.14.13.-', '1.14.13.126', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.143', '1.1.1.323', '1.1.1.323', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.2.1.1', '1.1.1.-', '1.7.3.-', '1.7.3.-', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.-', '1.14.13.-', '1.14.13.-', '3.2.1.2', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.15.5', '1.14.15.5', '1.1.1.-;1.1.1.270', '1.1.1.-;1.1.1.270', '1.14.13.79', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '6.2.1.3', '3.2.1.137', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.96', '1.1.1.-', '3.1.3.27', '1.1.1.-', '1.1.1.-', '1.1.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.183', '1.14.13.184', '1.14.13.194', '1.14.13.194', '3.1.3', '3.1.3.73', '3.2.1.143', '3.2.1.143', '3.2.1.143', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.14.13.M64', '1.1.1.M51', '3.1.3.73', '1.1.1.M51', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.106', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '1.1.1.-;1.1.1.1;1.1.1.327', '1.1.1.270', '1.14.13.98', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.1.1.184;1.1.1.189', '3.1.3.82', '3.1.3.29;3.1.3.50', '3.1.3.50', '1.1.1.296', '1.1.1.296', '1.14.13.-', '1.14.13.-', '1.1.1;1.1.1.51;1.1.1.62', '1.14.13.-;1.14.15.6', '1.1.1.271', '1.1.1.271', '1.1;1.1.1;1.1.1.209;1.1.1.213', '1.1.1.1', '1.1.99.13', '3.1.3.58;3.1.3.9', '1.17.99.5', '1.1.1;1.1.1.184;1.1.1.210;1.1.1.50', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.2;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.3.1.20', '1.1.1.184;1.1.1.357', '1.14.13.97', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.1.5.3;1.1.99.5', '1.1.1.367', '1.1.1.-', '1.14.13.-', '1.14.13.-', '1.1.1.395', '1.1.1', '1.1.1.146', '1.1.1.64', '1.1.1.146', '1.1.1.146', '1.1.1.239', '1.1.1.239', '1.1.1.62', '1.1.1.270', '1.1.1.238', '1.11.2.6', '1.11.2.6', '1.1.1.206', '3.1.3.76', '3.1.3.76', '1.1.1.102', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '4.2.3;4.2.3.1', '1.1.1;1.1.1.69', '1.1.1.213;1.1.1.50', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '3.1.3.1;3.1.3.75', '1.1.1.261', '3.1.3.1;3.1.3.19;3.1.3.2;3.1.3.25;3.1.3.29', '1.1.1.8;1.1.1.94;1.1.5.3', '1.1.1.49;1.1.1.8;1.1.1.94;1.3.1.20', '3.1.3.2;3.1.3.21']
40
358
BROMOCRIPTINE MESYLATE
5

100%|██████████| 11047/11047 [00:05<00:00, 2143.08it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3693.59it/s]
 11%|█         | 30/271 [06:42<55:47, 13.89s/it]

rxndb num 1096
failedrxn num 0
result_df 119
['3.5.1.94', '3.4.19.14', '2.3.2.2;3.4.19;3.4.19.13', '3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.15.6', '1.14.15.6', '3.1.3.-', '6.3.2.1', '3.1.3.74', '3.1.3.27', '3.5.1.92', '3.1.3.74', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.6.2', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.3.1.72', '3.1.3.39', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.5.1.22', '6.3.2.23', '6.3.1.2;6.3.1.6', '3.5.1.65', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '6.3.2.20', '3.5.1.26', '3.1.6.9', '3.1.6.10', '1.3.1.72', '3.5.1.24;3.5.1.74', '3.5.1.24', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.154', '1.14.13.154', '1.17.1.3', '1.17.1.3', '1.17.1.3', '3.5.1.93', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.3.1.72', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.-;3.1.3.88', '3.1.3.79', '6.3.2.36', '3.1.3.85', '1.14.-.-', '1.14.-.-', '3.1.3.83', '1.14.13.-', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.11.2.5', '3.5.1.-', '6.3.2.44', '6.3.4.24', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.103', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '3.4.19.11', '3.5.1.70', '6.3.2.18', '3.1.3', '6.3.2;6.3.2.-', '6.3.2', '6.3.2', '3.1.3.-', '3.4.19.16', '3.4.19.16', '3.4.19.16', '3.4.19.16', '3.4.19.16', '3.4.19.16', '3.4.19.16', '6.3.2', '3.4.19.16', '3.1.3;3.1.3.-', '3.4.11.25', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.3.1', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '6.3.2.59', '6.3.2.59', '3.4.19.13;3.4.19.9', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.13', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '6.3.2', '3.1.3', '3.4.13;3.4.13.-', '6.3.2', '3.4.13', '6.3.2', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '1.3.1.72', '6.3.2', '3.4', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '3.5.1.115', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.8', '1.14.13.8', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.1.6.14', '3.5.1.11', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.1.3.29', '1.14.15.15', '1.14.15.15', '3.1.3.33;3.1.3.5', '3.4.15.1;3.4.21.39', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '3.5.1.23', '3.5.1.23', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '3.2.1.78', '3.2.1.78', '3.2.1.78', '3.2.1.78', '3.2.1.78', '3.2.1.78', '3.1.3', '3.1.3', '3.1.3.68', '6.3.2.18', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.154', '1.14.13.154', '1.2.1.74', '1.2.1.74', '1.2.1.74', '3.4.11.5', '3.4.11.5', '3.4.11.5', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.3.1.72', '1.3.1.72', '3.2.1.35', '3.2.1.35', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '3.1.3.91', '3.6.1;3.6.1.-', '1.14.-.-', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.34', '1.3.1;1.3.1.-', '3.1.3.29', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.3.1.11', '3.5.1.-;3.5.1.78', '6.3.1.8;6.3.1.9', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.13.15;1.14.15.15', '1.14.13.15;1.14.15.15', '1.14.13.15;1.14.15.15', '1.14.13.15;1.14.15.15', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.5.1.11', '3.1.3.27', '3.5.1.4;3.5.1.99', '1.14.13.30', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.24', '3.1.3.12', '6.3.2.10', '3.1.3.29', '3.1.3.-', '3.5.1.24;3.5.1.74', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '6.3.1.9', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '6.3.2.10', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '2.-.-.-', '2.-.-.-', '1.3.1.69', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.5.1.-', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '6.3.1.13', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.3.1.-;1.3.1.72;1.3.1.M20', '1.3.1.-;1.3.1.72;1.3.1.M20', '1.3.1.-;1.3.1.71', '1.3.1.-;1.3.1.71', '1.14.19.41;1.3.1.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.45', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.3.68', '3.1.3.10', '3.1.3.10', '6.3.1.10', '6.3.1.10', '3.5.1.90', '3.5.1.90', '3.4.19.16', '6.3.2.56;6.3.2.ad', '3.4.19.13', '1.3.1.72', '3.1.3.M8', '6.3.2.45', '3.5.1.60;3.5.1.99', '3.5.1.60', '3.5.1.60;3.5.1.99', '3.5.1.99', '3.5.1.99', '3.1.3.105', '3.5.1.128', '3.5.1.60', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.4', '3.2.1.14', '3.2.1.14', '3.2.1.14', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.141', '1.14.13.141', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.4.15.6', '3.4.15.6', '3.4.15.6', '3.4.19.7', '3.4.19.7', '3.4.19.7', '3.2.1.1', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.-', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.188', '1.14.13.-;1.14.13.188', '1.14.99.-', '3.2.1.2', '1.13.99.3', '1.3.1.-', '1.3.1.-', '1.3.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '3.5.1.28', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.15.5', '1.14.15.5', '3.2.1.15', '3.2.1.15', '3.2.1.15', '4.2.2.2', '4.2.2.2', '4.2.2.2', '1.3.1.72', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '3.1.3.27', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.159', '1.14.13.159', '1.14.13.176', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.194', '1.14.13.194', '6.3.2;6.3.2.-', '1.14.13', '3.1.3', '6.3.2', '3.1.3.73', '3.2.1.143', '3.1.3.73', '6.3.2', '6.3.2', '3.4.19.16', '3.1.3', '3.1.3.73', '3.4.19.13', '3.1.3.73', '3.4.19.13', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.4.19.13', '3.1.3.73', '3.4.19.13', '6.3.2', '3.4.19.13', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.4.19.13', '6.3.2', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '6.3.4.13', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '6.3.2.37', '1.14.13.15', '1.14.13.15', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '6.3.1.10', '3.1.3.7;3.1.3.97', '3.1.3.7', '3.1.3.82', '1.3.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.182', '1.14.13.182', '1.13.99.3', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '6.3.2.58', '6.3.2.58', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.5.1.115', '1.1.1;1.1.1.206', '1.1.1;1.1.1.206', '1.1.1;1.1.1.206', '3.1.3.76', '3.5.1.46', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '1.3.1.72', '1.14.13.159', '1.14.13.159', '1.3.1.72', '1.3.1.72']
43
236
BUDESONIDE
5

100%|██████████| 11047/11047 [00:04<00:00, 2293.44it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3487.39it/s]
 11%|█▏        | 31/271 [06:58<57:32, 14.39s/it]

rxndb num 3993
failedrxn num 0
result_df 197

100%|██████████| 11047/11047 [00:02<00:00, 4041.12it/s]
100%|██████████| 27873/27873 [00:05<00:00, 4681.16it/s]
 12%|█▏        | 32/271 [07:09<53:27, 13.42s/it]

rxndb num 130
failedrxn num 0
result_df 37
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.6', '1.14.12.9', '1.14.12.9', '1.14.13.-;1.14.13.20;1.14.13.7', '1.14.13.-;1.14.13.20;1.14.13.7', '1.14.13.-;1.14.13.20;1.14.13.7', '1.14.13.-;1.14.13.20;1.14.13.7', '1.14.13.-', '1.14.13.-', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.97.1.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.229', '1.14.13.229', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.19', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.84', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.6', '3.8.1.6', '1.14.12.9', '1.14.12.9', '1.14.12.9', '1.14.12.9', '1.14.13.-', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.1.1.50', '1.3.98.-', '1.14.12.-', '1.14.12.-', '2.6.1.-', '1.14.19.58', '1.1.1', '1.1.1', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.1.1.422', '1.1.1.423', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1.422', '1.1.1.423']
14
30
BURAMATE
5

100%|██████████| 11047/11047 [00:02<00:00, 4462.08it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3367.92it/s]
 12%|█▏        | 33/271 [07:22<53:17, 13.43s/it]

rxndb num 616
failedrxn num 0
result_df 33
['3.1.3.69', '1.1.1.23', '3.1.3.15', '1.1.1.3', '1.1.1.3', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.1.5', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '3.1.3.-', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.27', '1.1.1;1.1.1.21;1.1.1.71', '3.1.3.3', '3.1.3.74', '1.1.1.1', '3.1.3', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.1.3.23', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3.2;3.1.3.29;3.1.3.38', '1.1.1.1;1.1.1.14;1.1.1.6;1.1.1.77', '3.1.3.22;3.1.3.23', '3.1.3.39', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.1.1.164;1.1.1.192', '1.1.1.106', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.1.1.191;1.1.1.2;1.1.1.21', '1.1.1.1;1.1.1.284;1.1.1.73', '1.1.1.150', '1.1.1.151', '1.14.13.4', '1.14.13.4', '1.14.13.4', '3.1.6.9', '3.1.6.10', '1.1.1.66', '4.99.1.-', '1.1.1.1;1.1.1.90', '3.1.3.14', '1.1.1.2', '1.1.1.258', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.3.39', '1.14.13.72', '3.1.3.69', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.76', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.1', '1.14.14.-;1.14.14.1', '1.14.13.15;1.14.15.15', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.3.-;1.1.3.43', '3.1.3.-;3.1.3.88', '1.1.3.-;1.1.3.44', '3.1.3.79', '1.1.-.-', '1.14.-.-', '1.1.-.-', '1.1.1.309', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '3.1.3.80', '3.1.3.85', '3.1.3.83', '1.1.3;1.1.3.-', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.1.1.-', '1.14.13.209', '1.14.13.209', '1.14.13.209', '3.1.3.101', '3.1.3.-', '1.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.103', '1.14.13.230', '1.1.3.40', '1.1.1.19', '1.1.1;1.1.1.-;1.1.1.1;1.1.1.2;1.1.1.21', '1.1.1.21;1.1.1.55', '3.1.3.3', '3.1.3', '1.1.1.1', '3.1.3.-', '1.1.1.365', '3.1.3;3.1.3.-', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '3.1.1', '1.1.1.1;1.1.1.2;1.1.1.21', '1.1.1.14;1.1.1.21', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.50', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.1.1', '1.2.1', '3.1.3', '1.1.1', '3.1.6.c', '3.1.3.4', '3.1.3.4', '1.14.13', '1.14.13', '1.14.13', '1.2.1', '1.1.3.48', '1.14.13', '1.14.13', '1.14.13.M9', '1.14.13.229', '1.14.13.M41', '1.14.13.M41', '1.1.1', '1.1.1', '3.1.3', '1.1.1', '1.1.1.1', '1.1.1.1', '1.1.1;1.1.1.-', '3.1.3;3.1.3.-;3.1.3.104;3.1.3.2;3.1.3.29', '1.1.1;1.1.1.-', '1.1.1.2', '3.1.3', '3.1.3;3.1.3.-', '1.14.14.145', '1.1.1.2;1.1.1.71', '3.1.6.14', '1.1.1.2;1.1.1.21;1.1.1.71', '1.1.1.2;1.1.1.71', '1.1.1.21', '3.1.3.29', '3.1.3.29', '1.14.15.15', '1.1.1.21', '1.1.1.184;1.1.1.21', '1.1.1.184;1.1.1.2;1.1.1.21;1.1.1.71', '3.1.3.33;3.1.3.5', '1.1.1.21', '1.1.1.1;1.1.1.71', '1.1.1.2', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.405', '1.1.1.1', '1.1.1.1', '1.1.1.1;1.1.1.71', '1.1.3.9', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.1.1;1.1.1.21', '1.1.1;1.1.1.10;1.1.1.21', '1.1.1;1.1.1.1;1.1.1.10;1.1.1.184;1.1.1.188;1.1.1.19;1.1.1.2;1.1.1.21;1.1.1.365', '1.1.1.2', '1.1.1;1.1.1.2;1.1.1.202;1.1.1.21', '3.1.3', '1.1.1.2;1.1.1.21', '1.1.1.1;1.1.1.284', '1.1.1;1.1.1.1;1.1.1.2;1.1.1.21;1.1.1.284;1.1.1.71', '1.1.1.21', '1.1.1;1.1.1.2;1.1.1.21;1.1.1.71', '1.1.1.2;1.1.1.21;1.1.1.71', '1.1.1.21', '1.1.1.21', '1.1.1.10', '1.1.1.10', '1.1.1.1', '1.1.1.1', '3.1.3', '3.1.3', '3.1.6.3', '3.1.3.68', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.36', '1.14.13.36', '1.14.13.36', '3.4.11.5', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.55', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '6.3.2.17', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.145;3.2.1.23', '3.2.1.110', '3.2.1.35', '1.1.1.126', '3.1.3.91', '3.6.1;3.6.1.-', '3.2.1.137;3.2.1.78', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '1.1.1.405', '1.1.1.21', '1.1.1.21', '1.1.1.2;1.1.1.61;1.2.1.16', '1;1.1.1;1.1.1.-;1.1.1.2;1.1.1.co;1.1.1.n11;1.2.1.16', '3.1.1.5', '3.1.3.23;3.1.3.29;3.1.3.9', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.15.3', '3.1.3.27', '1.14.12.19', '1.14.12.19', '1.14.13.30', '3.1.3', '3.1.3.24', '3.1.3.12', '1.1.1.-', '1.1.1;1.1.1.188;1.1.1.19;1.1.1.2;1.1.1.21;1.1.1.307;1.1.1.72', '1.1.1.136', '1.1.1.177;1.1.1.21', '1.1.1.132', '1.1.3.9', '3.1.3.29', '1.1.1.32;1.1.1.88', '1.1.1.2;1.1.1.32;1.1.1.33', '1.1.1.1;1.1.1.21;1.1.1.55', '3.1.3.-', '1.1.1.23', '1.1.1.114', '1.1.1.186', '3.1.3.63', '3.1.3.63', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.72', '3.1.3.70', '1.1.1.273', '1.1.1.273', '1.1.1.273', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.1.1.186', '3.1.3.21;3.1.3.25;3.1.3.29', '3.1.3.21;3.1.3.25', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.-.-;1.14.13.-', '1.1.1.317', '1.1.1.317', '3.1.3.73', '3.1.3', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.1.1.1;1.1.1.161', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '3.1.3.45', '1.1.1.-;1.1.1.336', '1.1.1.22', '3.1.3', '3.1.3.68', '1.1.1;1.1.1.2;1.1.1.21', '1.14.13.246', '3.1.3.M8', '1.1.1.131', '1.1.1.131', '1.1.1.273', '1.1.1.200', '3.1.3.106;3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '1.1.1', '1.1.1.71', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.1.1', '3.1.3.58;3.1.3.9', '3.1.6.3', '1.1.3.9', '1.1.3.9', '3.2.1.14', '3.2.1.37', '3.2.1.37', '3.2.1.55', '3.2.1.55', '3.2.1.3;3.2.1.58;3.2.1.59', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.14.-.-', '1.14.-.-;1.14.13.-', '3.2.1.116', '3.2.1.137', '3.2.1.154', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.4.15.6', '3.4.19.9', '3.4.19.5', '3.4.19.7', '1.1.3.20', '3.2.1.1', '1.7.3.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.-', '3.2.1.-', '1.1.1.-', '3.2.1.2', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.15.5', '1.14.15.5', '1.1.3.20', '6.2.1.3', '3.2.1.137', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '3.1.3.27', '1.1.1.-', '1.1.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.194', '3.1.1.101', '3.1.3', '3.1.3.73', '3.2.1.143', '3.1.3.73', '3.1.3', '3.1.3.73', '4.2.1.140;4.2.1.39', '3.1.3.73', '3.1.3.73', '3.1.3.73', '4.2.1.6', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.106', '3.1.3.73', '3.1.3', '1.1.1.2;1.1.1.20;1.1.1.21', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '1.1.1.1;1.1.1.161', '1.14.13.15;1.14.15.15', '1.14.13.72', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.82', '3.1.3.29;3.1.3.50', '3.1.3.50', '3.1.3.58;3.1.3.9', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '1.1.1.1', '1.1.1.M66', '1.11.2.6', '1.11.2.6', '1.11.2.6', '3.1.3.76', '3.1.3.76', '1.1.1.202', '1.1.1.1', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '1.14.13.127', '4.2.3;4.2.3.1', '1.1.1.77', '1.1.1.77', '1.1.1.1;1.1.1.90', '1.1.1;1.1.1.-;1.1.1.21', '1.1.1.1;1.1.1.190', '1.1.1;1.1.1.-;1.1.1.1;1.1.1.2;1.1.1.21', '1.1.1;1.1.1.-;1.1.1.1;1.1.1.188;1.1.1.2;1.1.1.21', '3.1.3.-;3.1.3.104', '3.1.3.1;3.1.3.75', '1.14.13.-', '1.14.-.-;1.14.13.-;1.14.13.cs', '3.1.3.1;3.1.3.19;3.1.3.2;3.1.3.25;3.1.3.29', '3.1.3.2;3.1.3.21']
38
252
BUSPIRONE
5

100%|██████████| 11047/11047 [00:02<00:00, 4051.84it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3896.80it/s]
 13%|█▎        | 34/271 [07:35<52:06, 13.19s/it]

rxndb num 418
failedrxn num 0
result_df 45
['1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.17.1.1', '1.17.1.1', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.-.-', '1.14.13.224', '1.14.13.224', '1.14.13.235', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '1.3.1', '1.14.13', '1.14.14.55', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.8', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '1.14.14.1', '1.14.13.56', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.9', '3.2.1.14', '3.4.15.6', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.182', '1.14.13.182', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.1.1;1.1.1.206']
17
48
CAMYLOFINE DIHYDROCHLORIDE
5

100%|██████████| 11047/11047 [00:03<00:00, 3476.16it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4032.77it/s]
 13%|█▎        | 35/271 [07:48<51:52, 13.19s/it]

rxndb num 378
failedrxn num 0
result_df 43
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.1.5', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '3.1.1.23', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.1.1.70', '3.1.1.51', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.3.1.-', '1.3.1.-', '1.3.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.-.-', '1.14.-.-', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '6.3.2', '6.3.2', '3.1.1;3.1.1.1;3.1.1.3', '3.1.1', '1.3.1', '3.1.1', '3.1.1.26', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.1.4', '3.1.1.23', '3.1.1.23', '3.1.1.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1.72', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.1.1;3.1.1.13;3.1.1.3', '3.1.1.1;3.1.1.3', '3.1.1.3', '3.1.1.3', '3.1.1.1', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '1.14.15.15', '1.14.15.15', '3.1.1.1;3.1.1.2', '3.1.1.1;3.1.1.2', '3.1.1.1;3.1.1.2', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '3.4.21;3.4.21.62', '3.4.16.5;3.4.21;3.4.21.62', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.2.1.74', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '6.3.2.17', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '2.3.1.-', '3.1.1', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.1.5', '3.1.1.5', '1.14.13.15;1.14.15.15', '1.14.13.15;1.14.15.15', '1.14.15.3', '1.14.15.3', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.30', '1.14.13.30', '1.14.13.46', '1.14.13.46', '1.14.13.74', '1.14.13.74', '3.1.1.10', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.3.1.69', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.-.-;1.14.13.-', '1.14.-.-;1.14.13.-', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '2.3.1.-', '1.1.1', '1.14.13.M76', '1.14.13.M76', '3.1.1.116', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-', '1.14.-.-', '1.14.-.-;1.14.13.-', '1.14.-.-;1.14.13.-', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.87', '3.4.15.6', '3.4.19.9', '3.4.19.5', '3.4.19.7', '1.14.13.-', '1.14.13.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.-', '1.2.-.-', '1.14.13.-', '1.3.1.-', '1.3.1.-', '1.3.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.15.5', '1.14.15.5', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '3.1.1.5', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '3.1.1.101', '1.14.13.M64', '1.14.13.149', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.11.2.6', '1.11.2.6', '1.11.2.6', '3.1.1.3', '1.14.13.-', '1.14.13.-', '1.14.-.-;1.14.13.-;1.14.13.cs', '1.14.-.-;1.14.13.-;1.14.13.cs']
32
97
CAPECITABINE
5

100%|██████████| 11047/11047 [00:02<00:00, 3978.19it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3478.09it/s]
 13%|█▎        | 36/271 [08:02<52:20, 13.36s/it]

rxndb num 948
failedrxn num 0
result_df 78
['3.1.3.69', '3.1.3.69', '3.1.3.15', '3.1.3.15', '3.1.3.74', '3.1.3.74', '3.1.1.5', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.-', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.74', '3.1.3.27', '3.1.3.27', '5.3.1.24', '3.1.3.74', '3.1.3.74', '3.1.3', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '3.1.3.39', '3.1.3.39', '1.1.3.16', '1.1.3.16', '1.14.14.1', '1.14.14.1', '1.1.1.101', '1.1.1.101', '3.1.3.40', '3.1.3.40', '3.1.6.9', '3.1.6.9', '3.1.6.10', '3.1.6.10', '1.1.1;1.1.1.-', '1.1.1;1.1.1.-', '1.-.-.-;1.1.1.342', '1.-.-.-;1.1.1.342', '1.1.1.62', '1.1.1.62', '1.1.1.62', '1.1.1.62', '1.1.1.53', '1.1.1.53', '1.1.1.50', '1.1.1.50', '1.1.1.53', '1.1.1.53', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.263', '1.1.1.263', '3.1.3.69', '3.1.3.69', '1.1.1;1.1.1.-', '1.1.1;1.1.1.-', '1.1.1.364', '1.1.1.364', '1.14.13.181', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.76', '3.1.3.76', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.-', '1.1.1.-', '1.1.1;1.1.1.-;1.1.1.50', '1.1.1;1.1.1.-;1.1.1.50', '1.-.-.-', '1.-.-.-', '1.1.1.292', '1.1.1.292', '2.4.2.4', '2.4.2.3;2.4.2.4', '1.1.1.-', '1.1.1.-', '1.1.1.-', '1.1.1.-', '1.1.1.-;1.1.1.341;4.2.1.-', '1.1.1.-;1.1.1.341;4.2.1.-', '1.1.1.-;1.1.1.329', '1.1.1.-;1.1.1.329', '3.1.3.-;3.1.3.88', '3.1.3.-;3.1.3.88', '1.1.1.-', '1.1.1.-', '1.1.1.213', '1.1.1.213', '3.1.3.79', '3.1.3.79', '1.1.3.-;1.1.3.45', '1.1.3.-;1.1.3.45', '3.3.2.-;3.3.2.10', '3.1.3.85', '3.1.3.85', '1.14.-.-', '1.14.-.-', '3.1.3.83', '3.1.3.83', '1.1.1.-;1.1.1.329', '1.1.1.-;1.1.1.329', '1.1.1.335', '1.1.1.335', '1.1.1.339;1.1.1.344', '1.1.1.339;1.1.1.344', '1.1.1.355', '1.1.1.355', '1.1.1.356', '1.1.1.356', '1.1.1.356', '1.1.1.356', '1.14.19.n5', '1.1.1.361', '1.1.1.361', '5.4.99.59', '3.1.3.92', '3.1.3.92', '1.1.1.364', '1.1.1.364', '1.1.1.367', '1.1.1.367', '1.1.1.374', '1.1.1.374', '2.4.2.57', '1.1.1.385', '1.1.1.385', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.1.1.393', '1.1.1.393', '3.1.3.101', '3.1.3.101', '3.1.3.-', '3.1.3.-', '1.1.1.-', '1.1.1.-', '1.1.1.-', '1.1.1.-', '1.1.1.-', '1.1.1.-', '3.1.3;3.1.3.-', '3.1.3;3.1.3.-', '1.1.1.-', '1.1.1.-', '1.14.13.224', '1.14.13.224', '3.1.3.103', '3.1.3.103', '1.1.1.395', '1.1.1.395', '1.1.1.-;1.1.1.395', '1.1.1.-;1.1.1.395', '1.1.1', '1.1.1', '3.1.3', '3.1.3', '3.1.3.-', '3.1.3.-', '1.1.1.201', '1.1.1.201', '1.1.1.-;1.1.1.50;1.1.1.52', '1.1.1.-;1.1.1.50;1.1.1.52', '1.1.1.391', '1.1.1.391', '3.1.3;3.1.3.-', '3.1.3;3.1.3.-', '1.14.13', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.1.1.102', '1.1.1.102', '1.1.1.145', '1.1.1.145', '3.1.1', '1.1.1', '1.1.1', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '5.4.99.59', '1.1.1', '1.1.1', '1.1.1.101', '1.1.1.101', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1', '1.1.1', '1.1.1', '1.1.1', '3.1.3.4', '3.1.3.4', '1.1.1.201', '1.1.1.201', '1.1.1', '1.1.1', '1.1.1', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1', '1.1.1', '1.1.1.M2', '1.1.1.M2', '1.14.13', '1.14.13', '1.14.13.M9', '1.1.1.M11', '1.1.1.M11', '1.1.1.M11', '1.1.1.M11', '1.1.1.392', '1.1.1.392', '1.1.1.393', '1.1.1.393', '1.1.1.52', '1.1.1.52', '1.1.1.391', '1.1.1.391', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.52', '1.1.1.52', '1.1.1.391', '1.1.1.391', '1.1.1.392;1.1.1.50;1.1.1.52', '1.1.1.392;1.1.1.50;1.1.1.52', '1.1.1.392', '1.1.1.392', '1.1.1.393', '1.1.1.393', '1.1.1.393', '1.1.1.393', '1.1.1', '1.1.1', '1.3.1', '1.1.1.159', '1.1.1.159', '1.1.1.218', '1.1.1.218', '3.1.6.14', '3.1.6.14', '1.1.1.218', '1.1.1.218', '3.1.3.29', '3.1.3.29', '1.1.1.149', '1.1.1.149', '3.1.3.33;3.1.3.5', '3.1.3.33;3.1.3.5', '1.1.1.133', '1.1.1.133', '1.1.1.239', '1.1.1.239', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.50', '1.1.1.292', '1.1.1.292', '3.1.3', '3.1.3', '3.2.1.78', '3.2.1.78', '3.2.1.78', '2.4.2.2;2.4.2.3;2.4.2.4', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '1.1.1.146;1.1.1.159;1.1.1.50', '1.1.1.146;1.1.1.159;1.1.1.50', '3.1.6.3', '3.1.6.3', '1.1.99.13', '1.1.99.13', '3.1.3.68', '3.1.3.68', '1.1.1.-', '1.1.1.-', '1.14.15.4', '1.14.15.4', '3.8.1.7', '1.1.1.133', '1.1.1.133', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.8', '3.2.1.154;3.2.1.26;3.2.1.80', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.55', '3.2.1.55', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.82', '3.2.1.15;3.2.1.82', '3.2.1.4;3.2.1.91', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '3.2.1.21;3.2.1.3', '1.1.1.-', '1.1.1.-', '3.2.1.65', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.145;3.2.1.23', '3.2.1.145;3.2.1.23', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.31', '3.2.1.31', '3.2.1.35', '3.2.1.35', '3.1.3.91', '3.1.3.91', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.2.1.137;3.2.1.78', '3.2.1.137;3.2.1.78', '1.14.-.-', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '3.1.3.29', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.-;1.1.1.146', '1.1.1.-;1.1.1.146', '1.1.1;1.1.1.-;1.1.1.146;1.1.1.51', '1.1.1;1.1.1.-;1.1.1.146;1.1.1.51', '3.1.1.5', '3.1.3.23;3.1.3.29;3.1.3.9', '3.1.3.23;3.1.3.29;3.1.3.9', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.27', '3.1.3.27', '1.14.13.30', '1.14.13.30', '3.1.3', '3.1.3', '3.1.3.24', '3.1.3.24', '1.1.1.133', '1.1.1.133', '2.4.2.2;2.4.2.3;2.4.2.4', '3.1.3.12', '3.1.3.12', '1.1.1.271', '1.1.1.271', '3.1.3.29', '3.1.3.29', '3.1.3.-', '3.1.3.-', '1.1.1.134;1.1.1.344', '1.1.1.134;1.1.1.344', '1.1.1.159;1.1.1.50', '1.1.1.159;1.1.1.50', '1.1.1.176', '1.1.1.176', '1.1.1.206', '1.1.1.206', '1.1.1.236', '1.1.1.236', '1.1.1.135;1.1.1.187', '1.1.1.135;1.1.1.187', '1.1.1.187;1.1.1.281', '1.1.1.187;1.1.1.281', '1.1.1.135;1.1.1.187', '1.1.1.135;1.1.1.187', '1.1.1.187;1.1.1.281', '1.1.1.187;1.1.1.281', '1.1.1.238', '1.1.1.238', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.1.1.146', '1.1.1.146', '1.1.1.213;1.1.1.52', '1.1.1.213;1.1.1.52', '1.1.1.50', '1.1.1.50', '1.1.1.209;1.1.1.50', '1.1.1.209;1.1.1.50', '2.-.-.-', '2.-.-.-', '2.-.-.-', '1.1.1.266', '1.1.1.266', '3.1.3.70', '3.1.3.70', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.4.2.3;2.4.2.4', '3.1.3.68', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.1;1.1.1.391', '1.1.1.1;1.1.1.391', '1.1.1.-;1.1.1.146;1.1.1.209;1.1.1.213;1.1.1.392;1.1.1.50', '1.1.1.-;1.1.1.146;1.1.1.209;1.1.1.213;1.1.1.392;1.1.1.50', '3.1.3.73', '3.1.3.73', '1.1.1;1.1.1.-', '1.1.1;1.1.1.-', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '1.1.1.159', '1.1.1.159', '1.1.1.-', '1.1.1.-', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '3.2.1.22;3.2.1.23', '1.1.1.153', '3.1.3.45', '3.1.3.45', '1.1.1.-;1.1.1.M53', '1.1.1.-;1.1.1.M53', '3.1.3.68', '3.1.3.68', '2.4.2.1;2.4.2.2;2.4.2.23;2.4.2.3;2.4.2.4', '1.1.1.201', '1.1.1.201', '1.1.1.425', '1.1.1.425', '3.1.3.M8', '3.1.3.M8', '1.1.1', '1.1.1', '1.1.1.266', '1.1.1.266', '3.1.3.106;3.1.3.76', '3.1.3.106;3.1.3.76', '1.1.1.367', '1.1.1.367', '3.1.3.106;3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.106', '3.1.3.76', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '3.1.3.105', '1.1.1', '1.1.1', '3.2.2.3;3.2.2.8', '1.1.3.10', '1.1.3.10', '1.1.3.10', '1.1.3.10', '3.1.3.58;3.1.3.9', '3.1.3.58;3.1.3.9', '3.1.6.3', '3.1.6.3', '3.2.2.3', '3.2.1.14', '3.2.1.14', '3.2.1.37', '3.2.1.37', '3.2.1.37', '3.2.1.37', '3.2.1.55', '3.2.1.55', '3.2.1.55', '3.2.1.55', '3.2.1.3;3.2.1.58;3.2.1.59', '3.2.1.3;3.2.1.58;3.2.1.59', '3.1.3.29', '3.1.3.29', '3.2.2.-;3.2.2.8', '3.2.1.4', '3.2.1.4', '3.2.1.4', '3.2.1.4', '3.3.2.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.116', '3.2.1.116', '3.2.1.60', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.2.1.87', '3.4.15.6', '3.4.15.6', '3.2.1.1', '3.2.1.1', '1.1.1.-', '1.1.1.-', '1.14.13.112', '1.14.13.112', '3.2.1.-', '3.2.1.-', '1.1.1.-', '1.1.1.-', '1.14.99.-', '1.14.99.-', '3.2.1.2', '3.2.1.2', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.13.174', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '3.2.1.153;3.2.1.26;3.2.1.80', '3.2.2.-', '1.14.15.5', '1.14.15.5', '3.2.2.3', '3.2.1.15', '3.2.1.15', '4.2.2.2', '4.2.2.2', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '3.2.1.137', '3.2.1.137', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.1.1.-', '1.1.1.-', '3.1.3.27', '3.1.3.27', '3.1.3', '3.1.3', '3.1.3.73', '3.1.3.73', '3.2.1.143', '3.2.1.143', '3.1.3.73', '3.1.3.73', '3.1.3', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.1.1.M51', '1.1.1.M51', '3.1.3.73', '3.1.3.73', '1.1.1.M51', '1.1.1.M51', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.106', '3.1.3.106', '3.1.3.73', '3.1.3.73', '3.1.3', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.5.1', '2.4.2.2', '3.1.3;3.1.3.-;3.1.3.4', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '3.2.1.23', '3.5.4.16', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7;3.1.3.97', '3.1.3.7', '3.1.3.7', '1.1.1.184;1.1.1.189', '1.1.1.184;1.1.1.189', '3.2.2.3;3.2.2.8', '3.1.3.82', '3.1.3.82', '3.3.2.10', '1.3.99.-', '1.3.99.-', '1.1.1.271', '1.1.1.271', '1.1.1.271', '1.1.1.271', '1.1.99.13', '1.1.99.13', '3.1.3.58;3.1.3.9', '3.1.3.58;3.1.3.9', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '3.1.3.-', '3.1.3.-', '3.1.3', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.1.1.367', '1.1.1.367', '1.1.1.-', '1.1.1.-', '1.1.1.395', '1.1.1.395', '1.1.1', '1.1.1', '1.1.1.238', '1.1.1.238', '3.1.3.76', '3.1.3.76', '1.1.1.102', '1.1.1.102', '4.2.3;4.2.3.1', '4.2.3;4.2.3.1', '3.1.3.-;3.1.3.104', '3.1.3.-;3.1.3.104']
38
222
CARBETAPENTANE CITRATE
5

100%|██████████| 11047/11047 [00:02<00:00, 4271.35it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3909.05it/s]
 14%|█▎        | 37/271 [08:14<50:45, 13.02s/it]

rxndb num 562
failedrxn num 0
result_df 58
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.1.5', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.1.23', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '3.1.1.22;3.1.1.75', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.1.70', '3.1.1.51', '1.14.13.22', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.-.-', '1.14.13.-;1.14.13.161', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '6.3.2', '6.3.2', '3.1.1;3.1.1.1;3.1.1.3', '1.14.13;1.14.13.-', '3.1.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '3.1.1', '3.1.1.26', '1.14.14', '1.14.14', '1.14.14', '3.1.1.4', '3.1.1.23', '3.1.1.23', '3.1.1.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.-', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '3.1.1.1;3.1.1.13;3.1.1.3', '3.1.1.1;3.1.1.3', '3.1.1.3', '3.1.1.3', '3.1.1.1', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '1.14.15.15', '3.1.1.1;3.1.1.2', '3.1.1.1;3.1.1.2', '3.1.1.1;3.1.1.2', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '3.4.21;3.4.21.62', '3.4.16.5;3.4.21;3.4.21.62', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.2.1.74', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '6.3.2.17', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '2.3.1.-', '3.1.1', '1.14.-.-', '1.3.1;1.3.1.-', '1.3.1;1.3.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.1.5', '3.1.1.5', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.15.3', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.12.19', '1.14.12.19', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '3.1.1.10', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.11.-', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.-.-', '1.14.-.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.-.-;1.14.13.-', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.3.1.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.M76', '1.14.13.M76', '3.1.1.116', '1.1.1.420', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-', '1.14.-.-;1.14.13.-', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '3.2.1.87', '3.2.1.87', '3.4.15.6', '3.4.19.9', '3.4.19.7', '1.14.13.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.-', '1.2.-.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '3.1.-.-', '3.1.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.15.5', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '3.1.1.5', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '3.1.1.101', '3.2.1.143', '3.2.1.143', '1.14.13.M64', '1.14.13.M64', '1.14.13.149', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.3.99.-', '1.3.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.11.2.6', '1.11.2.6', '1.11.2.6', '3.1.1.3', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.-', '1.14.-.-;1.14.13.-;1.14.13.cs']
38
113
CARBINOXAMINE MALEATE
5

100%|██████████| 11047/11047 [00:03<00:00, 3439.13it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4308.53it/s]
 14%|█▍        | 38/271 [08:27<50:14, 12.94s/it]

rxndb num 120
failedrxn num 0
result_df 23
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.8.1.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.8', '1.2.3.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.3.3.8', '1.3.98.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.19.58', '3.6.1.18;3.6.1.9']
11
29
CARISOPRODOL
5

100%|██████████| 11047/11047 [00:02<00:00, 4416.27it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3790.75it/s]
 14%|█▍        | 39/271 [08:40<49:43, 12.86s/it]

rxndb num 368
failedrxn num 0
result_df 39
['3.1.1.5', '3.1.1.5', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.5.1.75', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.181', '2.1.3.12', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.3.-', '6.1.2.2', '1.14.13', '3.1.1', '3.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '2.3.2.2;6.3.1.2', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.13.154', '1.14.13.154', '1.14.13.108', '1.14.13.108', '1.14.13.108', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '6.3.2.17', '6.3.2.17', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.1.5', '3.1.1.5', '1.14.15.3', '1.14.15.3', '1.14.15.3', '2.3.2.7', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-;1.14.13.-', '1.14.-.-;1.14.13.-', '1.14.-.-;1.14.13.-', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.3', '2.1.3', '3.2.1.14', '3.2.1.14', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-;1.14.13.-', '1.14.-.-;1.14.13.-', '1.14.-.-;1.14.13.-', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.4.15.6', '3.4.15.6', '3.4.19.9', '3.4.19.9', '3.4.19.5', '3.4.19.5', '3.4.19.7', '3.4.19.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.-', '3.2.1.-', '2.1.3.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.13.174', '1.14.15.5', '1.14.15.5', '1.14.15.5', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '3.1.1.101', '3.1.1.101', '3.2.1.143', '3.2.1.143', '1.3.99.-', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-;1.14.13.-;1.14.13.cs', '1.14.-.-;1.14.13.-;1.14.13.cs', '1.14.-.-;1.14.13.-;1.14.13.cs']
23
56
CARVEDILOL
5

100%|██████████| 11047/11047 [00:03<00:00, 3345.11it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3896.81it/s]
 15%|█▍        | 40/271 [08:52<49:23, 12.83s/it]

rxndb num 1881
failedrxn num 0
result_df 138

100%|██████████| 11047/11047 [00:02<00:00, 4031.99it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4471.26it/s]
 15%|█▌        | 41/271 [09:04<48:05, 12.55s/it]

rxndb num 48
failedrxn num 0
result_df 18
['1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.2.1.35', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '2.6.1.114']
5
11
CETIRIZINE
5

100%|██████████| 11047/11047 [00:02<00:00, 3888.68it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3643.24it/s]
 15%|█▌        | 42/271 [09:17<48:34, 12.73s/it]

rxndb num 296
failedrxn num 0
result_df 50
['1.2.1.3;1.2.1.54', '1.2.1.-;1.2.1.99', '1.1.1.23', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.2.1.3', '1.2.1.24;1.2.1.5;1.2.1.88;1.5.1.12', '1.5.1.12', '1.2.1.3;1.2.1.47', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.12.9', '3.8.1.7', '1.2.1.-;1.2.1.99', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.2.1.-;1.2.1.M5', '1.2.1.-;1.2.1.83', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.13.11.78', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.1', '1.2.1', '1.1.1.-', '1.2.1.47', '1.1.1.179;1.3.1.20', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.2.1.19;1.2.1.3', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '6.3.1.2', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '6.3.4.2', '1.1.1.47', '1.1.99.1', '1.14.12.9', '1.14.12.9', '1.14.12.9', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.2.3.1', '3.4.11.5', '1.1.1.23;1.1.1.24', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '6.3.2.17', '1.5.1.12;1.5.99.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.14.1', '1.1.1.-', '1.1.1.136', '1.1.1.132', '1.1.1.23', '1.2.1.31', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.2.1.3', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.2.1.31', '1.1.1.-;1.1.1.336', '1.1.1.22', '1.2.1.95;1.2.1.z', '1.2.1.31', '1.2.1.3', '1.2.1;1.2.1.-;1.2.1.19;1.2.1.3;1.2.1.5', '1.14.14.22;1.14.99.46', '1.2.1.101;1.2.1.ah', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.87', '3.4.15.6', '3.4.19.9', '3.4.19.7', '1.3.98.-', '3.2.1.-', '1.2.1.3', '6.2.1.3', '1.2.1.70;6.1.1.17', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.1.101', '3.2.1.143', '3.5.1', '1.14.19.58', '3.6.1.18;3.6.1.9', '1.13.11.90', '1.13.11.90', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.2.1;1.2.1.19;1.2.1.3', '1.2.1;1.2.1.88;1.5.1.12;1.5.99.8', '1.2.1;1.2.1.-;1.2.1.19;1.2.1.3', '1.2.1.3;1.2.1.5', '1.2.1.5', '1.2.1.19;1.2.1.3;1.2.1.8', '1.2.1.19;1.2.1.8']
37
90
CHLORMEZANONE
5

100%|██████████| 11047/11047 [00:02<00:00, 4685.62it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4433.53it/s]
 16%|█▌        | 43/271 [09:28<46:28, 12.23s/it]

rxndb num 38
failedrxn num 0
result_df 15
['1.14.13.58', '1.14.13.58', '1.17.1.1', '1.17.1.1', '3.8.1.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.-.-', '1.14.-.-', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '3.2.1.-', '3.2.1.-', '1.3.8.-', '1.1.1;1.1.1.206']
9
20
CIMETIDINE
5

100%|██████████| 11047/11047 [00:02<00:00, 4764.06it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4120.61it/s]
 16%|█▌        | 44/271 [09:40<45:50, 12.12s/it]

rxndb num 41
failedrxn num 0
result_df 12
['1.14.14.1', '2.1.1.49', '2.1.1.49', '2.1.1.49', '2.1.1.49', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '2.1.1.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '2.1.1;2.1.1.-', '2.1.1;2.1.1.-', '2.1.1;2.1.1.-', '2.1.1;2.1.1.-', '1.14.13', '1.14.13', '2.1.1;2.1.1.-', '2.1.1;2.1.1.-', '2.1.1;2.1.1.-', '2.1.1;2.1.1.-', '2.1.1.49', '2.1.1.49', '2.1.1.49', '2.1.1.49', '2.1.1.106', '2.1.1.106', '2.1.1.106', '2.1.1.106', '2.5.1.-', '2.6.1.114', '1.-.-.-', '2.5.1;2.5.1.-;2.5.1.48']
6
12
CITALOPRAM HYDROBROMIDE
5

100%|██████████| 11047/11047 [00:02<00:00, 3959.48it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4444.27it/s]
 17%|█▋        | 45/271 [09:52<45:22, 12.05s/it]

rxndb num 517
failedrxn num 0
result_df 41
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.14.133', '1.3.1', '1.3.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.8', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '1.3.1;1.3.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.19.41;1.3.1.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.3.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-']
15
54
CLEMASTINE FUMARATE
5

100%|██████████| 11047/11047 [00:04<00:00, 2752.29it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3624.71it/s]
 17%|█▋        | 46/271 [10:07<47:59, 12.80s/it]

rxndb num 639
failedrxn num 0
result_df 49
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.8.1.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.-.-', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13;1.14.13.-', '1.14.14.133', '1.3.1', '1.3.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.8', '1.14.13.8', '1.14.15.15', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '1.14.-.-', '1.3.1;1.3.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.-.-', '1.14.-.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.19.41;1.3.1.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.3.98.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.72', '1.14.15.5', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '3.2.1.143', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.3.99.-', '1.14.19.58', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-']
18
59
CLEMIZOLE
5

100%|██████████| 11047/11047 [00:03<00:00, 3669.36it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3450.52it/s]
 17%|█▋        | 47/271 [10:21<49:17, 13.21s/it]

rxndb num 148
failedrxn num 0
result_df 26
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.8.1.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.8', '1.14.14.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.3.98.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.176', '1.14.13.176', '1.14.13.176', '1.14.13.M64', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.19.58']
6
26
CLENBUTEROL
5

100%|██████████| 11047/11047 [00:02<00:00, 4421.35it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4259.96it/s]
 18%|█▊        | 48/271 [10:32<47:09, 12.69s/it]

rxndb num 208
failedrxn num 0
result_df 35
['3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3.-', '3.1.3.74', '3.1.3.3', '3.1.3;3.1.3.2', '3.1.3.74', '1.5.3.13', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.14.18.1', '3.1.3.39', '1.14.13.-;1.14.18.1', '1.14.13.58', '3.1.3.40', '3.1.6.9', '3.1.6.10', '1.14.13.20', '3.8.1.7', '1.14.13.50', '1.14.13.-', '1.14.13.-', '1.97.1.-', '1.7.1.-', '1.8.99.3;1.8.99.5', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.1', '3.1.3.-;3.1.3.88', '1.5.1.-;1.5.1.43', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.21.1.1;1.22.1.1', '1.14.-.-', '3.1.3.92', '1.11.2.5', '1.14.13.209', '1.14.13.-', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.3.103', '3.1.3.3', '3.1.3', '3.1.3.-', '3.1.3;3.1.3.-', '3.5.4;3.5.4.-', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '1.1.1', '1.1.1.362', '1.14.14', '3.1.3', '1.14.19', '1.14.13', '1.14.13', '1.14.13.M41', '1.14.13.M41', '1.14.13', '1.14.13.20', '1.14.13;1.14.13.20', '3.1.6.14', '3.1.3.29', '1.14.15.15', '3.1.3.33;3.1.3.5', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.1.1.2', '1.1.1.2', '1.14.12.17', '1.14.14;1.14.14.1;1.14.14.25', '3.1.3', '3.1.3', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.110', '3.1.3.91', '3.6.1;3.6.1.-', '1.14.-.-', '3.1.3.29', '1.14.13.30', '3.1.3', '3.1.3.29', '3.1.3.-', '1.14.13.50', '1.14.13.50', '1.14.13.71;1.14.14.102', '1.14.13.73;1.14.14.103', '1.14.-.-', '1.14.-.-', '1.14.13.11', '3.1.3.73', '3.1.3', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.5.1.43', '3.1.3.M8', '3.1.3.105', '1.14.13.9', '1.1.1.50', '1.5.1.43', '3.1.3.29', '1.14.-.-', '1.14.-.-', '1.14.14.-', '1.3.98.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.-;3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.3;3.1.3.-;3.1.3.4', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '1.14.19.58', '1.1.1', '1.1.1', '1.14.14.8', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '1.1.1.422', '1.1.1.423', '1.11.2.6', '1.1.1.422', '1.1.1.423', '3.1.3.76', '4.2.3;4.2.3.1', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '3.1.3.1;3.1.3.75']
30
98
CLIDINIUM BROMIDE
5

100%|██████████| 11047/11047 [00:04<00:00, 2555.72it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3864.69it/s]
 18%|█▊        | 49/271 [10:47<49:04, 13.26s/it]

rxndb num 736
failedrxn num 0
result_df 71
['3.1.3.69', '3.1.3.74', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.27', '3.1.3.74', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.1.23', '3.1.3.73', '3.1.6.2', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3.39', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.14.13.4', '1.14.13.4', '3.1.6.9', '3.1.6.10', '3.1.1.70', '3.1.1.51', '3.1.3.69', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.76', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.-;3.1.3.88', '1.14.13.105', '3.1.3.79', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '3.1.3.85', '3.1.3.83', '1.14.13.-', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.1.1.363;1.1.1.388', '1.14.13.209', '1.14.13.209', '1.14.13.209', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.103', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.14.108', '1.14.14.108', '3.1.3', '3.1.3.-', '6.3.2', '6.3.2', '3.1.3;3.1.3.-', '3.1.1;3.1.1.1;3.1.1.3', '3.1.6;3.1.6.-', '1.3.1', '1.14.13', '1.14.13', '1.14.13', '3.1.1', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.1.26', '1.14.14', '1.14.14', '1.14.14', '3.1.1.4', '3.1.1.23', '3.1.1.23', '3.1.1.13', '1.14.13', '1.14.13', '3.1.3.4', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.1', '1.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.105', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.1.1;3.1.1.13;3.1.1.3', '3.1.1.1;3.1.1.3', '3.1.1.3', '3.1.1.3', '3.1.1.1', '3.1.6.14', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.3.29', '1.1.1.179;1.3.1.20', '3.1.3.33;3.1.3.5', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14.25', '1.14.14.25', '3.4.21;3.4.21.62', '3.4.16.5;3.4.21;3.4.21.62', '1.14.13', '1.14.13', '1.14.13', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3', '3.1.3', '1.14.14.55', '1.14.14.55', '3.2.1.78', '3.2.1.78', '1.1.1.47', '3.1.3', '3.1.3', '1.14.15.4', '1.14.15.4', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.2.1.74', '1.14.13.36', '1.14.13.36', '1.14.13.36', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.82', '3.2.1.4;3.2.1.91', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.31', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '2.3.1.-', '3.1.3.91', '3.6.1;3.6.1.-', '3.1.1', '1.14.14.91', '1.14.14.91', '1.14.14.91', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '1.14.-.-', '1.14.-.-', '3.1.1.5', '3.1.1.5', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.1.3.27', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.24', '3.1.3.12', '3.1.3.29', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.3.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '3.1.1.10', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.79', '1.14.13.79', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.1.1.107;1.1.1.122', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3', '1.14.14.149', '1.14.14.149', '2.3.1.-', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.45', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.1.1.363;1.1.1.388;1.1.1.47;1.1.1.49', '3.1.3.M8', '3.1.1.116', '3.1.3.106;3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '3.2.1.14', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.54', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.4.19.7', '3.2.1.1', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.2.-.-', '3.2.1.2', '3.1.-.-', '3.1.-.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '3.1.1.5', '3.1.3.27', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.156', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '3.1.1.101', '3.1.3', '3.1.3.73', '3.2.1.143', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.106', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '1.14.13.149', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '1.14.13.98', '1.14.13.98', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.1.1.363;1.1.1.49', '3.1.3.82', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.1.88', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.1.1.363;1.1.1.47;1.1.1.49', '1.1.1.49', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.11.2.6', '1.11.2.6', '1.11.2.6', '3.1.3.76', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '1.14.13.127', '3.1.3.2;3.1.3.75']
40
192
CLONIDINE
5

100%|██████████| 11047/11047 [00:02<00:00, 4070.21it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3571.04it/s]
 18%|█▊        | 50/271 [11:00<49:01, 13.31s/it]

rxndb num 39
failedrxn num 0
result_df 11
['1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '3.8.1.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.97.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '3.8.1.7', '3.8.1.7', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.9', '1.14.13.9', '1.3.98.-', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.19.58']
8
18
CLOPIDOGREL SULFATE
5

100%|██████████| 11047/11047 [00:02<00:00, 4141.15it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3745.72it/s]
 19%|█▉        | 51/271 [11:13<48:09, 13.13s/it]

rxndb num 188
failedrxn num 0
result_df 26
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.1.1.70', '3.8.1.7', '3.1.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.1.1.95', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.19', '3.1.1', '1.1.1.-', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.4.11.5', '2.3.1.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '3.1.1.10', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.3.98.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.-.-', '3.1.-.-', '1.14.-.-', '1.-.-.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '3.1.1.5', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13', '3.2.1.143', '1.14.19.58', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9']
16
43
CLOZAPINE
5

100%|██████████| 11047/11047 [00:04<00:00, 2302.40it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4485.40it/s]
 19%|█▉        | 52/271 [11:27<48:51, 13.39s/it]

rxndb num 134
failedrxn num 0
result_df 27
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.8.1.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.8', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.3.98.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.19.58']
6
19
COLCHICINE
5

100%|██████████| 11047/11047 [00:03<00:00, 2998.64it/s]
100%|██████████| 27873/27873 [00:09<00:00, 2963.41it/s]
 20%|█▉        | 53/271 [11:43<51:48, 14.26s/it]

rxndb num 807
failedrxn num 0
result_df 81
['3.5.1.94', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13;1.14.14.1;1.14.99.10', '1.14.13;1.14.99.10', '6.3.2.1', '3.5.1.92', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '3.5.1.17', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.5.1.21', '3.5.1.62', '3.5.1.33', '2.3.1.32', '3.5.1;3.5.1.-;3.5.1.63', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.5.1.22', '6.3.2.23', '6.3.1.2;6.3.1.6', '3.5.1.65', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '6.3.2.20', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '3.5.1.24;3.5.1.74', '3.5.1.17', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.5.1.24', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '3.5.1.25', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.17.1.3', '1.17.1.3', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.17.1.3', '1.14.13.181', '3.5.1.76;3.5.1.85', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.5.1.-;3.5.1.112', '3.5.1.-;3.5.1.113', '6.3.2.36', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.-.-', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '3.5.1.-', '6.3.2.44', '6.3.4.24', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '3.3.2.14', '3.3.2.14', '3.3.2.14', '3.3.2.14', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '6.3.2.18', '6.3.2;6.3.2.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '6.3.2', '6.3.2', '6.3.2', '3.4.11.25', '3.5.1.-;3.5.1.136', '6.3.2.59', '6.3.2.59', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.5.1', '1.14.13', '1.14.13', '3.4.13', '6.3.2', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2', '3.4', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '3.5.1.105', '3.5.1.115', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '1.14.15.15', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '3.5.1.23', '3.5.1.23', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.55', '1.14.14.55', '6.3.2.18', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.82', '3.2.1.15;3.2.1.82', '6.3.2.17', '6.3.2.17', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.-.-', '2.4.1.-', '2.4.1.-', '2.4.1.-', '2.4.1.-', '1.14.-.-', '1.14.-.-', '6.3.1.11', '3.5.1.-;3.5.1.78', '6.3.1.8;6.3.1.9', '3.5.1.103', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.5.1.4;3.5.1.99', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.5.1.24;3.5.1.74', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '6.3.1.9', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.99.10', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.-.-', '1.14.-.-', '3.5.1.-', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '6.3.1.13', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.14.149', '1.14.14.149', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '6.3.1.10', '6.3.1.10', '3.5.1.90', '3.5.1.90', '1.14.18.2', '6.3.2.56;6.3.2.ad', '3.5.1.108', '3.5.1.60;3.5.1.99', '3.5.1.60', '3.5.1.60;3.5.1.99', '3.5.1.99', '3.5.1.99', '3.5.1.62', '3.5.1.85', '3.5.1.60', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.4', '3.5.1.33', '3.2.1.14', '3.2.1.14', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.4.15.6', '3.4.15.6', '3.4.19.9', '3.4.19.9', '3.4.19.7', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.15.5', '3.2.1.15', '3.2.1.15', '4.2.2.2', '4.2.2.2', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.194', '6.3.2;6.3.2.-', '1.14.13', '6.3.2', '3.2.1.143', '3.2.1.143', '3.2.1.143', '3.2.1.143', '6.3.2', '6.3.2', '6.3.2', '6.3.2', '1.14.18.2', '6.3.2.37', '1.14.13.98', '1.14.13.98', '6.3.1.10', '3.5.1.25', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '3.5.1.108', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '6.3.2.58', '6.3.2.58', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.5.1.115', '3.5.1', '3.5.1.108', '3.5.1.108', '3.5.1.108', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '3.5.1.108', '3.5.1.63', '3.5.1.46']
36
152
CYCLOBENZAPRINE
5

100%|██████████| 11047/11047 [00:02<00:00, 3836.54it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4298.99it/s]
 20%|█▉        | 54/271 [11:55<49:04, 13.57s/it]

rxndb num 205
failedrxn num 0
result_df 16
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.13.100', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.8', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1;1.14.14.55', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.48', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.8', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.6', '1.14.15.6', '1.14.13.234', '1.14.13.48', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.14.23', '1.14.13.17', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.79', '1.14.13.79', '1.14.13.77', '1.14.13.76', '1.14.13.-', '1.14.13.-', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.-;1.14.14.149', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.13.99;1.14.99', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.121', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13.145', '1.14.13.99', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.48', '1.14.13.79', '1.14.13.79', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.100;1.14.13.17;1.14.13.60', '1.14.13.99', '1.14.13.98', '1.14.13.98', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.106', '1.14.13.106', '1.14.13', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.80;1.14.14.53', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-']
8
52
CYCLOPHOSPHAMIDE
5

100%|██████████| 11047/11047 [00:03<00:00, 3333.52it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4479.54it/s]
 20%|██        | 55/271 [12:07<47:04, 13.08s/it]

rxndb num 27
failedrxn num 0
result_df 10
['1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13', '1.14.13', '1.3.1', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.35', '1.14.13.97', '1.14.13.97', '3.2.1.14', '3.4.15.6', '3.2.1.-', '6.2.1.3', '3.2.1.143', '1.14.13.M64', '3.6.1.18;3.6.1.9']
12
22
CYPROTERONE ACETATE
5

100%|██████████| 11047/11047 [00:04<00:00, 2339.15it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4026.81it/s]
 21%|██        | 56/271 [12:22<48:44, 13.60s/it]

rxndb num 2129
failedrxn num 0
result_df 145

100%|██████████| 11047/11047 [00:03<00:00, 3606.18it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4074.34it/s]
 21%|██        | 57/271 [12:34<47:05, 13.20s/it]

rxndb num 842
failedrxn num 0
result_df 89
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.1.5', '3.1.1.5', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '3.1.1.23', '3.10.1.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.17.1.1', '1.17.1.1', '3.1.1.70', '3.1.1.51', '1.14.13.180', '1.14.13.180', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.-.-', '1.14.-.-', '1.14.19.n5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.224', '1.14.13.224', '6.3.2', '3.1.1;3.1.1.1;3.1.1.3', '3.1.1', '3.1.1', '3.1.1', '1.14.13.235', '3.1.1.26', '3.1.1.4', '3.1.1.23', '3.1.1.23', '3.1.1.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '1.3.1', '3.1.1', '1.1.1.-', '1.3.1', '3.1.1.1;3.1.1.13;3.1.1.3', '3.1.1.1;3.1.1.3', '3.1.1.3', '3.1.1.1', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '1.2.3.1', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.4.21;3.4.21.62', '3.4.16.5;3.4.21;3.4.21.62', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.8', '1.14.13.-', '1.14.13.-', '3.4.11.5', '3.4.11.5', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '3.2.1.35', '3.2.1.35', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '2.3.1.-', '3.1.1', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.1.5', '3.1.1.5', '3.1.1.5', '1.14.13.30', '1.14.13.30', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '3.1.1.10', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.3.1.-', '3.1.1.116', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.2.1.14', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.87', '3.2.1.87', '3.4.15.6', '3.4.15.6', '3.4.15.6', '3.4.19.7', '3.4.19.7', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.-', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '3.1.-.-', '3.1.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.13.174', '1.14.15.5', '1.14.15.5', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '3.1.1.5', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.176', '1.14.13.176', '1.14.13.176', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '3.2.1.143', '3.2.1.143', '1.3.99.-', '1.3.99.-', '1.3.99.-', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9']
32
87
DANAZOL
5

100%|██████████| 11047/11047 [00:04<00:00, 2283.11it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4132.15it/s]
 21%|██▏       | 58/271 [12:48<47:45, 13.45s/it]

rxndb num 1161
failedrxn num 0
result_df 92
['3.1.3.74', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1;1.14.14.25;1.14.14.55;1.14.14.57', '1.14.13.100', '3.1.3.74', '3.1.3.74', '3.1.3.73', '3.1.6.2', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '3.1.3.39', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.6.9', '3.1.6.10', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '3.1.3.-;3.1.3.88', '1.14.13.100;1.14.14.29', '3.1.3.79', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13.-;1.14.13.224', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.13.224', '1.14.13.228', '1.3.1.114', '3.1.3', '3.1.6;3.1.6.-', '1.3.1', '1.3.1', '1.3.1', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.14.133', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.14.13', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.13.235', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1.114', '4.1.99.16', '1.14.14.1', '1.14.15.15', '1.14.15.15', '3.1.3.33;3.1.3.5', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '3.1.3', '3.1.3', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '3.1.3', '3.1.3', '1.14.14.1', '3.1.3.68', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.13.70;1.3.1.70', '3.8.1.7', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.13.154', '1.14.13.154', '1.14.13.108', '1.14.13.108', '3.2.1.154;3.2.1.26;3.2.1.80', '3.2.1.65', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-;1.14.13.129', '1.14.13.-;1.14.13.129', '1.14.13.-;1.14.13.129', '1.14.13.-;1.14.13.129', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.234', '1.14.13.-;1.14.13.129', '1.14.13.-;1.14.13.129', '1.14.99.45', '1.14.-.-', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.34', '1.3.1;1.3.1.-', '1.3.1;1.3.1.-', '1.3.1;1.3.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-;1.14.13.129', '1.14.13.-;1.14.13.129', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.30', '1.14.13.30', '3.1.3.24', '1.14.14.23', '1.14.13.17', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.77', '1.14.13.76', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.17', '1.14.-.-;1.14.13.-', '1.14.-.-;1.14.13.-', '1.14.13.-;1.14.13.146', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3', '1.14.13.-;1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.13.129;1.14.99;1.14.99.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.13.99;1.14.99', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.13.129', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.129', '1.14.13.-', '1.14.13.-', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.121', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13.145', '1.14.13.99', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.13.99.3', '1.14.99.45', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.70', '1.14.13.70', '1.14.13.72', '1.14.13.72', '1.14.15.5', '1.14.15.5', '1.14.13.129', '1.14.13.129', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.186', '1.14.13.194', '1.14.13.194', '1.14.13', '3.1.3', '1.3.1.114', '3.1.3.73', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3', '3.1.3.-;3.1.3.5', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '1.14.14.1', '1.14.13.100;1.14.13.17;1.14.13.60', '1.14.13.99', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '1.14.13.106', '1.14.13.106', '1.13.99.3', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13;1.14.14.1', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2']
18
105
DARIFENACIN HYDROBROMIDE
5

100%|██████████| 11047/11047 [00:02<00:00, 3718.67it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4094.38it/s]
 22%|██▏       | 59/271 [13:01<46:21, 13.12s/it]

rxndb num 564
failedrxn num 0
result_df 77
['6.3.1.2', '1.4.1.13;1.4.1.14;1.4.7.1;2.4.2;2.4.2.14;3.5.1.2;3.5.1.38;4.3.1;4.3.3.6;6.3.4.2;6.3.5.2;6.3.5.4;6.3.5.5;6.3.5.7', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '3.5.1.-;3.5.1.111;3.5.1.3', '6.3.1.4', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.5.1.12', '3.5.5.4;4.2.1.65', '3.5.1.2;3.5.1.35;3.5.1.38', '3.5.1.73', '3.10.1.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.5.1.50', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '4.2.1.84', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '4.2.1.84', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '3.5.1.99', '3.5.1.100', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.3.1', '3.5.1.100', '4.2.1.84', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '3.5.1.4', '3.5.1.4', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '2.3.2.2;6.3.1.2', '3.5.1.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '1.14.14.55', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '2.4.1.-', '1.14.-.-', '1.14.-.-', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.5.1.57', '2.3.2.7', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.5.1.11;3.5.1.4', '3.5.1.30', '3.5.1.-;3.5.1.4', '3.5.1.4', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '3.2.1.87', '3.4.15.6', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13', '1.14.13', '3.2.1.143', '1.14.13.M64', '1.14.13.149', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.4.19.5;3.5.1.1;3.5.1.26;3.5.1.38;3.5.5.4', '3.5.1.1', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '1.14.13', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1;1.1.1.206', '6.3.1.1;6.3.5.4']
39
110
DASATINIB
5

100%|██████████| 11047/11047 [00:03<00:00, 3487.50it/s]
100%|██████████| 27873/27873 [00:06<00:00, 3997.40it/s]
 22%|██▏       | 60/271 [13:14<46:13, 13.15s/it]

rxndb num 260
failedrxn num 0
result_df 41
['1.1.1.23', '3.1.3.15', '1.1.1.3', '1.1.1.3', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.74', '3.1.3.74', '1.1.1.1', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.1.3.23', '1.1.3.17', '3.1.3.39', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.1.1.191;1.1.1.2;1.1.1.21', '3.1.6.9', '3.1.6.10', '3.8.1.7', '4.99.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1;1.1.1.-;1.1.1.1', '3.1.3.-;3.1.3.88', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.224', '1.14.13.224', '3.1.3', '3.1.3.-', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.1.1', '1.14.13', '1.14.13', '1.1.1', '1.1.1.1', '3.1.6.14', '3.1.3.29', '3.1.3.33;3.1.3.5', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '3.1.3', '3.1.3', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.8', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.35', '1.14.14.1', '3.1.3.91', '3.6.1;3.6.1.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3', '3.1.3.29', '3.1.3.-', '1.1.1.23', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.1.1.273', '1.1.1.273', '1.1.1.273', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.140', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.1.1.317', '1.1.1.317', '3.1.3.73', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.1.99.1', '3.1.3.M8', '1.1.1.273', '3.1.3.105', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.1.3.29', '3.4.15.6', '1.3.98.-', '3.2.1.-', '1.1.1.1', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.140', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.14.19.58', '2.6.1.114', '2.6.1.114', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '3.1.3.76', '1.1.1.1;1.1.1.190', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '1.1.1;1.1.1.1', '3.1.3.1;3.1.3.75']
23
92
DEFLAZACORT
5

100%|██████████| 11047/11047 [00:04<00:00, 2307.41it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3858.36it/s]
 23%|██▎       | 61/271 [13:29<48:04, 13.73s/it]

rxndb num 2951
failedrxn num 0
result_df 154

100%|██████████| 11047/11047 [00:02<00:00, 3726.91it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4184.44it/s]
 23%|██▎       | 62/271 [13:41<46:09, 13.25s/it]

rxndb num 880
failedrxn num 0
result_df 61
['3.1.3.69', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.27', '3.1.3.74', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.6.2', '3.1.6.1;3.1.6.2', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3.39', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.6', '1.14.13.6', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.14.13.4', '1.14.13.4', '3.1.6.9', '3.1.6.10', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.219;1.14.13.7', '1.14.13.219;1.14.13.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.69', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.76', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.-;3.1.3.88', '3.1.3.79', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '3.1.3.85', '3.1.3.83', '1.21.1.1;1.22.1.1', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.220', '3.1.3.103', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.10.3.1;1.14.18.1', '3.1.3', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.3;3.1.3.-', '1.14.14.133', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3', '3.1.6.c', '3.1.3.4', '3.1.3.4', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '4.1.99.16', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.8', '3.1.6.14', '3.1.3.29', '1.1.1.1', '3.1.3.33;3.1.3.5', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '3.2.1.78', '3.1.3.48', '3.1.3.2', '3.1.3', '3.1.3', '3.1.6.3', '3.1.3.68', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.13.36', '1.14.13.36', '3.2.1.154;3.2.1.26;3.2.1.80', '3.2.1.154;3.2.1.26;3.2.1.80', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.55', '3.2.1.55', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '3.2.1.21;3.2.1.3', '3.2.1.65', '3.2.1.65', '3.2.1.145;3.2.1.23', '3.2.1.145;3.2.1.23', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '1.14.18.-', '1.14.13.18', '1.14.13.18', '3.1.3.91', '3.6.1;3.6.1.-', '3.2.1.137;3.2.1.78', '3.2.1.137;3.2.1.78', '3.1.3.2;3.1.3.31;3.1.3.34', '1.3.1;1.3.1.-', '1.3.1;1.3.1.-', '3.1.3.29', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.23;3.1.3.29;3.1.3.9', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.1.3.27', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.24', '3.1.3.12', '3.1.3;3.1.3.2;3.1.3.48', '3.1.3.29', '3.1.3.-', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '3.1.3.63', '3.1.3.63', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.21.3', '1.14.21.3', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '3.2.1.22;3.2.1.23', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '3.1.3.45', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.3.68', '3.1.6.d', '3.1.3.M8', '3.1.3.106;3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '1.14.14.1', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.1.3.58;3.1.3.9', '3.1.6.3', '3.2.1.37', '3.2.1.37', '3.2.1.37', '3.2.1.37', '3.2.1.3;3.2.1.58;3.2.1.59', '3.2.1.3;3.2.1.58;3.2.1.59', '3.1.3.29', '3.2.1.4', '3.2.1.4', '3.2.1.4', '3.2.1.4', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '3.2.1.116', '3.2.1.116', '3.2.1.60', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.1', '3.2.1.1', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '3.2.1.2', '3.2.1.2', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.137', '3.2.1.137', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '3.1.3.27', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.106', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.82', '1.3.99.-', '1.3.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.190', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '3.1.3.58;3.1.3.9', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.8', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.27', '1.14.14.27', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.11.2.6', '1.11.2.6', '1.11.2.6', '3.1.3.76', '3.1.3.76', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '1.14.13.127', '4.2.3;4.2.3.1', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '3.1.3.1;3.1.3.75']
34
183
DEXAMETHASONE
5

100%|██████████| 11047/11047 [00:04<00:00, 2715.75it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3477.46it/s]
 23%|██▎       | 63/271 [13:56<47:57, 13.84s/it]

rxndb num 3716
failedrxn num 0
result_df 160

100%|██████████| 11047/11047 [00:03<00:00, 3173.09it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4309.77it/s]
 24%|██▎       | 64/271 [14:09<46:06, 13.36s/it]

rxndb num 1014
failedrxn num 0
result_df 78
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '2.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.3.1', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.8', '1.14.13.8', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '1.3.1;1.3.1.-', '1.3.1;1.3.1.-', '1.3.1;1.3.1.-', '2.4.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.3.99.-', '1.3.99.-', '1.3.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-']
19
66
DIACETAMATE
5

100%|██████████| 11047/11047 [00:03<00:00, 3280.16it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4400.76it/s]
 24%|██▍       | 65/271 [14:21<44:29, 12.96s/it]

rxndb num 301
failedrxn num 0
result_df 35
['1.14.13.9', '1.14.13.9', '3.1.1.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.7', '1.14.13.7', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.6', '1.14.13.6', '3.1.1.55', '1.14.13.29', '1.14.13.29', '1.14.13.4', '1.14.13.4', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.7.1.12', '1.7.1.12', '3.1.1.1;3.1.1.56', '1.14.-.-', '1.14.-.-', '1.14.13.219;1.14.13.7', '1.14.13.219;1.14.13.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.181', '1.14.13.181', '1.14.13.-;1.6.5.2', '1.14.13.-;1.6.5.2', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.13.244;1.14.13.M20', '1.14.13.244;1.14.13.M20', '1.11.2.5', '1.11.2.5', '6.3.1.18', '1.1.1.203', '1.1.1.203', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.220', '1.14.-.-', '1.14.-.-', '2.1.1.-', '3.5.1.123', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.1.1.203', '1.14.13.44', '1.14.13.44', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '3.5.1', '1.14.13.M33', '1.14.13.M33', '1.1.1.-', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.20', '1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '3.1.1;3.1.1.1;3.1.1.14;3.1.1.2;3.1.1.7;3.1.1.74;3.1.1.88;3.1.2.12;3.1.2.2', '3.1.1;3.1.1.1;3.1.1.2', '2.3.2.2;3.4.11.10;3.4.19.3', '3.1.1.1;3.1.1.13', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.1.13;3.1.1.2;3.1.1.3', '3.4.21.4;3.4.22;3.4.22.1', '1.14.13.84', '1.14.13.84', '1.14.13.84', '3.1.1.1', '1.14.13.84', '3.1.1.3', '3.3.2.6;3.4.11.10;3.4.11.15', '3.1.1.1', '3.1.1.1', '3.1.1.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '3.1.1;3.1.1.3', '1.14.14.91', '1.14.14.91', '1.14.13', '1.14.13', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.1;3.1.1.1;3.1.1.2;3.1.1.74;3.1.1.88;3.1.2.12', '3.1.1;3.1.1.1', '1.1.1.1;1.2.1.3;1.2.1.88;3.1.1;3.1.1.1;3.1.1.101;3.1.1.2;3.1.1.3;3.1.1.6;3.1.1.7;3.1.1.74;3.1.1.88;3.1.2.12', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.36', '1.14.13.36', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.82', '3.2.1.15;3.2.1.82', '6.3.2.17', '6.3.2.17', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '1.14.14.91', '1.14.14.91', '3.1.1.2', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.7', '1.14.13.7', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.57', '1.14.13.57', '1.14.13.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.84', '3.1.1;3.1.1.2', '1.14.13.88', '1.14.13.88', '1.14.13.140', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.1.1.107;1.1.1.122', '1.14.13.88', '1.14.13.88', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '1.2.1.5', '1.2.1.39;1.2.1.5', '1.14.18.2', '1.14.19.55', '1.14.19.55', '1.14.14.1', '1.14.14.1', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.4.19.9', '3.4.19.9', '3.4.19.7', '3.4.19.7', '1.14.12.-', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '3.2.1.15', '3.2.1.15', '4.2.2.2', '4.2.2.2', '1.14.13.-', '1.14.13.-', '1.14.13.140', '3.2.1.143', '3.5.1', '1.14.18.2', '1.14.13.-', '1.14.13.-', '1.14.14.20', '1.14.14.20', '1.14.14.8', '1.14.14.8', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.27', '1.14.14.27', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.11.2.6', '1.11.2.6', '3.1.1.74', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127']
35
115
DICYCLOMINE
5

100%|██████████| 11047/11047 [00:03<00:00, 3635.21it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4000.04it/s]
 24%|██▍       | 66/271 [14:34<44:09, 12.92s/it]

rxndb num 902
failedrxn num 0
result_df 83
['3.1.1.5', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.1.1.23', '3.1.1.22;3.1.1.75', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.1.70', '3.1.1.51', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.-.-', '1.14.-.-', '1.14.13.-;1.14.13.161', '6.3.2', '6.3.2', '3.1.1;3.1.1.1;3.1.1.3', '1.3.1', '1.14.13;1.14.13.-', '3.1.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '3.1.1', '3.1.1.26', '3.1.1.4', '3.1.1.23', '3.1.1.23', '3.1.1.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.1.1;3.1.1.13;3.1.1.3', '3.1.1.1;3.1.1.3', '3.1.1.3', '3.1.1.3', '3.1.1.1', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '1.14.15.15', '3.1.1.1;3.1.1.2', '3.1.1.1;3.1.1.2', '3.1.1.1;3.1.1.2', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '3.4.21;3.4.21.62', '3.4.16.5;3.4.21;3.4.21.62', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.2.1.74', '3.4.11.5', '6.3.2.17', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '2.3.1.-', '3.1.1', '1.14.-.-', '1.3.1;1.3.1.-', '1.3.1;1.3.1.-', '1.3.1;1.3.1.-', '1.3.1;1.3.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.1.5', '3.1.1.5', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.15.3', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.30', '1.14.13.16', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '3.1.1.10', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.11.-', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-;1.14.13.-', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '2.3.1.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.M76', '1.14.13.M76', '3.1.1.116', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-', '1.14.-.-;1.14.13.-', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '3.2.1.87', '3.4.15.6', '3.4.19.9', '3.4.19.7', '1.14.13.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.-', '1.2.-.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.13.72', '1.14.15.5', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '3.1.1.5', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '3.1.1.101', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.3.99.-', '1.3.99.-', '1.3.99.-', '1.3.99.-', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '3.1.1.3', '1.14.13.-', '1.14.-.-;1.14.13.-;1.14.13.cs']
24
75
DIFLORASONE DIACETATE
5

100%|██████████| 11047/11047 [00:04<00:00, 2293.74it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3924.32it/s]
 25%|██▍       | 67/271 [14:48<45:40, 13.43s/it]

rxndb num 3060
failedrxn num 0
result_df 159

100%|██████████| 11047/11047 [00:04<00:00, 2307.78it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3827.81it/s]
 25%|██▌       | 68/271 [15:04<47:26, 14.02s/it]

rxndb num 6049
failedrxn num 0
result_df 351

100%|██████████| 11047/11047 [00:05<00:00, 2122.85it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3392.29it/s]

rxndb num 6582
failedrxn num 0
result_df 360

 25%|██▌       | 69/271 [15:20<49:48, 14.79s/it]

43
437
DILTIAZEM
5

100%|██████████| 11047/11047 [00:02<00:00, 4018.40it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3753.31it/s]
 26%|██▌       | 70/271 [15:32<47:04, 14.05s/it]

rxndb num 601
failedrxn num 0
result_df 87
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13;1.14.99.10', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.1.1.70', '1.14.13.19', '1.14.13.19', '3.1.1.51', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.1.1.53', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.-.-', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.3.2.14', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13', '6.3.2', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.1', '3.1.1.26', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.1.4', '3.1.1.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '3.1.1', '3.1.1', '3.1.1', '3.1.1;3.1.1.-', '3.1.1', '3.1.1', '1.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.8', '3.1.1.1;3.1.1.13;3.1.1.3', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '1.14.14;1.14.14.1;1.14.14.25', '2.5.1.18', '3.4.21;3.4.21.62', '3.4.16.5;3.4.21;3.4.21.62', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '2.5.1.18', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '1.14.14.1', '2.3.1.-', '3.1.1', '1.14.-.-', '2.4.1.-', '3.1.1.5', '3.1.1.5', '1.14.13.30', '1.14.13.54', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.1.10', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '3.1.1.80', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.1.80', '3.1.1.80', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.-.-', '1.14.-.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '3.1.1.94', '2.3.1.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.1.105', '3.1.1.105', '3.5.1.M13', '3.1.1.80', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13', '3.2.1.14', '3.2.1.14', '3.1.1.53', '3.1.1.53', '3.1.1.53', '3.1.1.53', '1.14.-.-', '1.14.-.-', '3.2.1.87', '3.2.1.87', '3.4.15.6', '3.4.15.6', '3.4.19.7', '3.4.19.7', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.-.-', '3.1.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.15.5', '3.1.1.53', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '3.1.1.5', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.194', '3.1.1.101', '3.1.1.101', '3.2.1.143', '3.2.1.143', '1.14.13.32', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.1', '3.1.1', '3.1.1', '3.1.1.53', '3.1.1.53', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1;1.1.1.206', '3.1.1.7;3.1.1.8']
35
100
DIPERODON
5

100%|██████████| 11047/11047 [00:04<00:00, 2626.54it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4176.28it/s]
 26%|██▌       | 71/271 [15:46<46:21, 13.91s/it]

rxndb num 374
failedrxn num 0
result_df 55
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.1.5', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.1', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.12', '1.14.12', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.2.1.78', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '3.4.11.5', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '6.3.2.17', '6.3.2.17', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '1.14.14.1', '3.1.1.5', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.140', '1.14.13.140', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.2.1.154', '3.2.1.154', '3.2.1.87', '3.2.1.87', '3.4.15.6', '3.4.15.6', '3.4.19.9', '3.4.19.9', '3.4.19.5', '3.4.19.5', '3.4.19.7', '3.4.19.7', '3.2.1.-', '3.2.1.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '6.2.1.3', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.140', '1.14.13.140', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.1.101', '3.1.1.101', '3.2.1.143', '3.2.1.143', '4.2.1.140;4.2.1.39', '4.2.1.140;4.2.1.39', '4.2.1.6', '4.2.1.6', '1.14.13.M64', '1.14.13.M64', '1.3.99.-', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6']
29
67
DIPHENYLPYRALINE
5

100%|██████████| 11047/11047 [00:02<00:00, 3875.53it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3510.30it/s]
 27%|██▋       | 72/271 [16:00<46:08, 13.91s/it]

rxndb num 239
failedrxn num 0
result_df 20
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.14.133', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.8', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14.25', '1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '1.14.14.55', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '1.14.-.-', '1.14.-.-', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.14.149', '1.14.14.149', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '3.2.1.87', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.M64', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-']
13
52
DIPYRIDAMOLE
5

100%|██████████| 11047/11047 [00:03<00:00, 3675.41it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4087.73it/s]
 27%|██▋       | 73/271 [16:12<44:04, 13.36s/it]

rxndb num 478
failedrxn num 0
result_df 55
['1.1.1.23', '1.1.1.23', '3.1.3.15', '3.1.3.15', '1.1.1.3', '1.1.1.3', '1.1.1.3', '1.1.1.3', '3.1.3.74', '3.1.3.74', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.1.3.-', '3.1.3.-', '3.1.3.74', '3.1.3.74', '3.1.3.3', '3.1.3.3', '3.1.3.74', '3.1.3.74', '1.1.1.1', '1.1.1.1', '3.1.3.73', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.1.3.23', '1.1.3.23', '1.1.3.17', '1.1.3.17', '3.1.3.39', '3.1.3.39', '1.1.1.191;1.1.1.2;1.1.1.21', '1.1.1.191;1.1.1.2;1.1.1.21', '3.1.6.9', '3.1.6.9', '3.1.6.10', '3.1.6.10', '1.1.1.66', '1.1.1.66', '4.99.1.-', '4.99.1.-', '1.1.1.2', '1.1.1.2', '1.1.1.258', '1.1.1.258', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.1', '1.1.1.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.1', '1.1.1.1', '1.1.1;1.1.1.-;1.1.1.1', '1.1.1;1.1.1.-;1.1.1.1', '1.14.13.15;1.14.15.15', '1.14.13.15;1.14.15.15', '3.1.3.-;3.1.3.88', '3.1.3.-;3.1.3.88', '3.1.3.79', '3.1.3.79', '1.1.-.-', '1.1.-.-', '1.14.-.-', '1.14.-.-', '1.1.-.-', '1.1.-.-', '1.1.1.309', '1.1.1.309', '3.1.3.92', '3.1.3.92', '3.1.3.101', '3.1.3.101', '3.1.3.-', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.3;3.1.3.-', '3.1.3', '3.1.3', '3.1.3.-', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.3;3.1.3.-', '3.1.3;3.1.3.-', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.1.1', '1.1.1', '3.1.3', '3.1.3', '1.1.1', '1.1.1', '3.1.3.4', '3.1.3.4', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '1.3.1', '1.1.1', '1.1.1', '1.1.1.1', '1.1.1.1', '1.1.1;1.1.1.-', '1.1.1;1.1.1.-', '3.1.6.14', '3.1.6.14', '3.1.3.29', '3.1.3.29', '1.14.15.15', '1.14.15.15', '3.1.3.33;3.1.3.5', '3.1.3.33;3.1.3.5', '1.1.1.1;1.1.1.284', '1.1.1.1;1.1.1.284', '1.1.1.1', '1.1.1.1', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.8.1.7', '3.8.1.7', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.8', '3.8.1.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.4;3.2.1.91', '3.2.1.65', '3.2.1.65', '3.2.1.110', '3.2.1.110', '1.14.14.1', '3.1.3.91', '3.1.3.91', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '3.1.3.29', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.15.3', '1.14.15.3', '1.14.13.30', '1.14.13.30', '3.1.3', '3.1.3', '3.1.3.24', '3.1.3.24', '3.1.3.12', '3.1.3.12', '3.1.3.29', '3.1.3.29', '3.1.3.-', '3.1.3.-', '1.1.1.23', '1.1.1.23', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.1.1.273', '1.1.1.273', '1.1.1.273', '1.1.1.273', '1.1.1.273', '1.1.1.273', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.-.-;1.14.13.-', '1.14.-.-;1.14.13.-', '1.1.1.317', '1.1.1.317', '1.1.1.317', '1.1.1.317', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3.73', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.1.1.1;1.1.1.161', '1.1.1.1;1.1.1.161', '3.1.3.68', '3.1.3.68', '1.1.99.1', '1.1.99.1', '1.14.13.246', '1.14.13.246', '3.1.3.M8', '3.1.3.M8', '1.1.1.273', '1.1.1.273', '3.1.3.105', '3.1.3.105', '3.1.3.29', '3.1.3.29', '3.2.1.4', '3.2.1.4', '3.2.1.4', '3.2.1.4', '1.14.-.-', '1.14.-.-', '1.14.-.-;1.14.13.-', '1.14.-.-;1.14.13.-', '3.2.1.116', '3.2.1.116', '3.2.1.60', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.1', '3.2.1.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.-', '1.1.1.-', '1.14.99.-', '1.14.99.-', '3.2.1.2', '3.2.1.2', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.15.5', '1.14.15.5', '1.14.15.5', '1.14.15.5', '1.1.1.1', '1.1.1.1', '1.1.1.-', '1.1.1.-', '1.1.1.-', '1.1.1.-', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.73', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '3.2.1.23', '1.1.1.1;1.1.1.161', '1.1.1.1;1.1.1.161', '1.14.13.15;1.14.15.15', '1.14.13.15;1.14.15.15', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7;3.1.3.97', '3.1.3.7', '3.1.3.7', '1.3.99.-', '1.3.99.-', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '3.1.3.-', '3.1.3.-', '3.1.3', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '3.1.3.-;3.1.3.102;3.1.3.2', '3.1.3.76', '3.1.3.76', '3.1.3.76', '3.1.3.76', '4.2.3;4.2.3.1', '4.2.3;4.2.3.1', '1.1.1.1;1.1.1.190', '1.1.1.1;1.1.1.190', '3.1.3.-;3.1.3.104', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '3.1.3.2;3.1.3.75', '1.1.1;1.1.1.1', '1.1.1;1.1.1.1', '3.1.3.1;3.1.3.75', '3.1.3.1;3.1.3.75', '1.14.13.-', '1.14.13.-', '1.14.-.-;1.14.13.-;1.14.13.cs', '1.14.-.-;1.14.13.-;1.14.13.cs']
27
115
DISOPYRAMIDE PHOSPHATE
5

100%|██████████| 11047/11047 [00:03<00:00, 2856.15it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4472.47it/s]
 27%|██▋       | 74/271 [16:25<43:06, 13.13s/it]

rxndb num 292
failedrxn num 0
result_df 37
['6.3.1.2', '1.4.1.13;1.4.1.14;1.4.7.1;2.4.2;2.4.2.14;3.5.1.2;3.5.1.38;4.3.1;4.3.3.6;6.3.4.2;6.3.5.2;6.3.5.4;6.3.5.5;6.3.5.7', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.5.1.-;3.5.1.111;3.5.1.3', '6.3.1.4', '3.5.1.12', '3.5.5.4;4.2.1.65', '3.5.1.2;3.5.1.35;3.5.1.38', '3.5.1.73', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.5.1.50', '4.2.1.84', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '4.2.1.84', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.5.1.99', '3.5.1.100', '1.14.-.-', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '3.5.1.100', '1.14.13.235', '4.2.1.84', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '3.5.1.4', '4.2.1.84', '3.5.1.4', '3.5.1.4', '1.2.3.1', '1.14.15.15', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '2.3.2.2;6.3.1.2', '3.5.1.1', '3.5.1.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.6', '1.14.15.6', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '1.14.-.-', '1.14.13.30', '3.5.1.57', '2.3.2.7', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '3.5.1.11;3.5.1.4', '3.5.1.30', '3.5.1.-;3.5.1.4', '3.5.1.4', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '3.4.15.6', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.M64', '1.14.13.149', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '3.4.19.5;3.5.1.1;3.5.1.26;3.5.1.38;3.5.5.4', '3.5.1.1', '1.14.13', '1.1.1;1.1.1.206', '6.3.1.1;6.3.5.4']
30
88
DOMPERIDONE
5

100%|██████████| 11047/11047 [00:03<00:00, 3229.24it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3725.60it/s]
 28%|██▊       | 75/271 [16:38<43:06, 13.20s/it]

rxndb num 296
failedrxn num 0
result_df 45
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.8.1.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.5.99.9', '3.5.99.9', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13', '1.14.13', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.3.1', '1.3.1', '1.3.1', '1.14.12.16', '1.14.12.16', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.8', '3.8.1.8', '3.4.11.5', '3.4.11.5', '3.2.1.18', '3.2.1.18', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.4.15.6', '3.4.15.6', '1.3.98.-', '3.2.1.-', '3.2.1.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.176', '1.14.13.176', '1.14.13.176', '1.14.13.176', '1.14.13.176', '1.14.13.176', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.19.58', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.19.59', '1.14.19.59', '1.14.19.60', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14']
14
37
DOXAZOSIN MESYLATE
5

100%|██████████| 11047/11047 [00:03<00:00, 3680.60it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3931.24it/s]
 28%|██▊       | 76/271 [16:51<42:28, 13.07s/it]

rxndb num 506
failedrxn num 0
result_df 60
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.5.4.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '3.5.4.23', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '3.5.4.5', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.3.2.14', '3.3.2.14', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '3.5.4.20', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.5.4.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.5.4.5', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.2.1.78', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.82', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.35', '2.4.1.-', '2.4.1.-', '2.4.1.-', '2.4.1.-', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.88', '1.14.13.88', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.5.4.1', '3.5.4.12', '3.5.4.13', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.4.15.6', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '6.2.1.3', '6.2.1.3', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.88', '1.14.13.88', '1.14.13.176', '3.2.1.143', '3.2.1.143', '3.2.1.143', '3.2.1.143', '6.3.4.2', '3.5.4.13', '3.5.4.12', '3.5.4.5', '1.14.13.182', '1.14.13.182', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.1.1;1.1.1.206', '3.5.4.14;3.5.4.5']
22
70
DOXEPIN
5

100%|██████████| 11047/11047 [00:03<00:00, 2959.83it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4289.18it/s]
 28%|██▊       | 77/271 [17:03<41:54, 12.96s/it]

rxndb num 528
failedrxn num 0
result_df 32
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1;1.14.14.25;1.14.14.55;1.14.14.57', '1.14.13.100', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.8', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.100;1.14.14.29', '1.14.13.-', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.14.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.8', '1.14.14.25', '1.14.14.25', '1.14.14.55', '1.14.14.55', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.13.234', '1.14.99.45', '2.4.1.-', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.14.23', '1.14.13.17', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.79', '1.14.13.79', '1.14.13.77', '1.14.13.76', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.17', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.14.1', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13.145', '1.14.13.99', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.45', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.79', '1.14.13.79', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.100;1.14.13.17;1.14.13.60', '1.14.13.99', '1.14.13.98', '1.14.13.98', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.106', '1.14.13.106', '1.14.13', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-']
11
65
DOXYLAMINE SUCCINATE
5

100%|██████████| 11047/11047 [00:02<00:00, 4257.37it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3929.50it/s]
 29%|██▉       | 78/271 [17:16<40:58, 12.74s/it]

rxndb num 192
failedrxn num 0
result_df 22
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.-.-', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13;1.14.13.-', '1.14.13', '1.14.13.M9', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.8', '1.2.3.1', '1.14.15.15', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.-.-', '1.14.13.30', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.3.3.8', '1.14.-.-', '1.14.-.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.13.72', '1.14.15.5', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.176', '3.2.1.143', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-']
14
35
DROSPIRENONE
5

100%|██████████| 11047/11047 [00:06<00:00, 1679.16it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3597.85it/s]
 29%|██▉       | 79/271 [17:33<44:47, 13.99s/it]

rxndb num 2191
failedrxn num 0
result_df 178

100%|██████████| 11047/11047 [00:02<00:00, 4359.85it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4227.53it/s]
 30%|██▉       | 80/271 [17:44<42:12, 13.26s/it]

rxndb num 732
failedrxn num 0
result_df 75
['1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.5.3.13;1.5.3.17', '1.5.3.13;1.5.3.17', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.5.3.4', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.4.3.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.5.3.15;1.5.3.17', '1.5.1.-;1.5.1.43', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.5.3.21', '1.5.3.-;1.5.3.19', '1.4.3.-;1.4.3.24', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '2.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.5.3.14', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.55', '1.14.14.55', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '2.4.1.-', '1.14.-.-', '1.14.-.-', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.5.3.11;1.5.3.13;1.5.3.16;1.5.3.17', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.14.149', '1.14.14.149', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.5.1.43', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.5.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.98', '1.14.13.98', '1.4.3.M1', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127']
21
73
ELETRIPTAN HYDROBROMIDE
5

100%|██████████| 11047/11047 [00:04<00:00, 2712.13it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4485.54it/s]
 30%|██▉       | 81/271 [17:57<41:27, 13.09s/it]

rxndb num 373
failedrxn num 0
result_df 45
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.224', '1.14.13.235', '1.14.13', '1.14.13;1.14.13.-', '1.14.13', '1.14.13.8', '1.14.13.8', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.13.11.52', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '3.4.11.5', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.13.11.52', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.13.11.11;1.13.11.52', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.13.11.11;1.13.11.52', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.13.99.3', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.13.11.52', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.3.99.-', '1.14.13.182', '1.14.13.182', '1.13.99.3', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.13.11.52', '1.13.11.52']
12
42
ENALAPRIL MALEATE
5

100%|██████████| 11047/11047 [00:02<00:00, 3938.37it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3751.36it/s]
 30%|███       | 82/271 [18:10<41:05, 13.04s/it]

rxndb num 520
failedrxn num 0
result_df 73
['1.2.1.3;1.2.1.54', '1.2.1.-;1.2.1.99', '3.4.13.18;3.4.13.9', '1.1.1.23', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.1.5', '1.2.1.3', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.13.15', '4.1.1.30', '4.1.1.36', '1.2.1.24;1.2.1.5;1.2.1.88;1.5.1.12', '1.5.1.12', '3.1.1.23', '1.2.1.3;1.2.1.47', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.2.1.40', '3.1.1.70', '3.1.1.51', '1.14.13.72', '1.14.13.22', '1.2.1.-;1.2.1.99', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.5.1;1.5.1.-', '1.5.1;1.5.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.2.-.-', '1.2.-.-', '1.2.-.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.-.-', '1.14.-.-', '1.2.1.-;1.2.1.M5', '1.2.1.-;1.2.1.83', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.3;6.3.-.-', '6.3.2', '6.3.2', '3.1.1;3.1.1.1;3.1.1.3', '1.14.13;1.14.13.-', '1.2.1;1.2.1.-', '3.1.1', '3.1.1', '3.1.1.26', '1.14.14', '1.14.14', '1.14.14', '3.1.1.4', '3.1.1.23', '3.1.1.23', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '1.3.1', '1.2.1', '3.1.1', '1.1.1.-', '1.1.1.-', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '3.1.1.1;3.1.1.3', '3.1.1.3', '3.1.1.3', '3.1.1.1', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '1.2.1.47', '3.1.1.1;3.1.1.2', '3.1.1.1;3.1.1.2', '3.1.1.1;3.1.1.2', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.2.1.19;1.2.1.3', '3.4.21;3.4.21.62', '3.4.16.5;3.4.21;3.4.21.62', '6.3.1.2', '1.14.13', '1.14.13', '1.14.13', '6.3.4.2', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.2.3.1', '1.14.13.72', '3.4.11.5', '3.4.11.5', '3.4.11.5', '1.1.1.23;1.1.1.24', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '6.3.2.17', '6.3.2.17', '6.3.2.17', '1.5.1.12;1.5.99.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '3.2.1.35', '2.3.1.-', '3.1.1', '1.14.-.-', '1.14.-.-', '3.1.1.5', '3.1.1.5', '1.1.1.23', '1.2.1.31', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '3.1.1.10', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.2.1.3', '2.-.-.-', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.72', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.79', '1.14.11.-', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.-.-;1.14.13.-', '1.14.-.-;1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.3.1.-', '1.2.1.31', '1.2.1.95;1.2.1.z', '1.2.1.31', '1.2.1.3', '1.2.1;1.2.1.-;1.2.1.19;1.2.1.3;1.2.1.5', '1.14.14.22;1.14.99.46', '1.2.1.3', '1.14.13.M76', '1.14.13.M76', '1.14.13.M76', '3.1.1.116', '1.1.1.420', '1.1.1.420', '1.2.1.101;1.2.1.ah', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.2.1.14', '1.14.-.-;1.14.13.-', '1.14.-.-;1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.87', '3.4.15.6', '3.4.15.6', '3.4.15.6', '3.4.19.9', '3.4.19.9', '3.4.19.9', '3.4.19.5', '3.4.19.5', '3.4.19.5', '3.4.19.7', '3.4.19.7', '3.4.19.7', '3.2.1.-', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.2.1.-', '1.14.99.-', '1.14.99.-', '3.1.-.-', '3.1.-.-', '1.2.1.3', '1.14.11.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.15.5', '1.14.15.5', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '6.2.1.3', '1.2.1.70;6.1.1.17', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '3.1.1.5', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.1.101', '3.1.1.101', '3.1.1.101', '3.2.1.143', '3.5.1', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '1.14.13.15', '1.3.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.2.1.3;1.2.1.40', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '3.6.1.18;3.6.1.9', '1.2.1', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1;1.1.1.206', '3.1.1.3', '1.2.1;1.2.1.19;1.2.1.3', '1.2.1;1.2.1.88;1.5.1.12;1.5.99.8', '1.2.1;1.2.1.-;1.2.1.19;1.2.1.3', '1.2.1.3;1.2.1.5', '1.2.1.5']
46
129
ENTACAPONE
5

100%|██████████| 11047/11047 [00:02<00:00, 4468.46it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3967.28it/s]
 31%|███       | 83/271 [18:22<39:40, 12.66s/it]

rxndb num 250
failedrxn num 0
result_df 44
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '3.1.3;3.1.3.1;3.1.3.16;3.1.3.2;3.1.3.23;3.1.3.25;3.1.3.29;3.1.3.31;3.1.3.36;3.1.3.41;3.1.3.43;3.1.3.48;3.1.3.5;3.1.3.74;3.1.3.76;3.1.4.4;3.6.1.7;5.4.2.6', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.31', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.7.1.9', '1.7.1.9', '1.7.1.-;1.7.1.16', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.12.23', '1.14.13.-', '1.14.13.-', '1.-.-.-;1.7.1', '1.7.1.-', '1.-.-.-', '1.12.99.6;1.2.7.1;1.2.7.4;1.2.99.2', '1.-.-.-', '1.7.1.-', '1.7.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.14.12.-;1.14.12.24', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.24', '1.14.12.24', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.12.23', '1.7.1.16', '1.14.12.23', '1.14.12.23', '1.7.1', '1.7.1.16', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.3.1', '1.14.18.1', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.13', '1.14.13', '1.14.13', '1.14.13.25', '1.14.13.25', '1.14.13.25', '3.1.3.48', '3.1.6.1;3.1.6.12;3.1.6.8', '3.1.3.48', '1.14.13.31', '1.14.18.1', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.36', '1.14.13.36', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '1.14.-.-', '3.2.1.35', '3.2.1.35', '1.14.14.91', '3.1.3;3.1.3.2;3.1.3.48', '1.14.21.3', '1.14.21.3', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.14.22;1.14.99.46', '1.14.14.22;1.14.99.46', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.1.6.1', '3.2.1.14', '3.2.1.14', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.7.1.-', '1.7.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.8', '1.14.14', '1.14.14', '1.14.14', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.7.1.M3', '1.7.1.M3', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.14.13.3;1.14.14.9']
27
85
ERGONOVINE MALEATE
5

100%|██████████| 11047/11047 [00:03<00:00, 2766.01it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4185.14it/s]
 31%|███       | 84/271 [18:35<40:08, 12.88s/it]

rxndb num 430
failedrxn num 0
result_df 50
['3.5.1.94', '1.1.1.23', '3.1.3.15', '1.1.1.3', '1.1.1.3', '3.1.3.74', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '3.1.3.-', '6.3.2.1', '3.1.3.74', '3.5.1.92', '3.1.3.3', '3.1.3.74', '1.1.1.1', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.1.3.23', '1.1.3.17', '3.1.3.39', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.5.1.22', '1.1.1.191;1.1.1.2;1.1.1.21', '6.3.2.23', '6.3.1.2;6.3.1.6', '3.5.1.65', '6.3.2.20', '3.1.6.9', '3.1.6.10', '3.5.1.24;3.5.1.74', '3.5.1.24', '1.14.13.61', '1.14.13.72', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.1', '1.14.14.-;1.14.14.1', '1.1.1.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.5.1;1.5.1.-', '1.1.1;1.1.1.-;1.1.1.1', '1.14.13.15;1.14.15.15', '3.1.3.-;3.1.3.88', '1.14.13.-', '1.14.13.-', '6.3.2.36', '3.1.3.92', '3.5.1.-', '6.3.2.44', '6.3.4.24', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.224', '1.14.13.224', '6.3.2.18', '3.1.3.3', '3.1.3', '6.3.2;6.3.2.-', '6.3.2', '6.3.2', '3.1.3.-', '3.1.3;3.1.3.-', '6.3.2', '3.1.3;3.1.3.-', '3.4.11.25', '3.1.6;3.1.6.-', '1.1.1;1.1.1.-', '1.14.13;1.14.13.-', '6.3.2.59', '6.3.2.59', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.13.235', '1.14.13', '1.14.13;1.14.13.-', '1.1.1', '3.1.3', '1.1.1', '3.4.13', '6.3.2', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.13.11', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '1.1.1', '1.1.1.1', '6.3.2', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.4', '3.5.1.115', '1.14.13.8', '1.14.13.8', '1.14.14.145', '1.14.14.145', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.1.6.14', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.1.3.29', '1.14.15.15', '3.1.3.33;3.1.3.5', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.5.1.23', '3.5.1.23', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '1.13.11.52', '6.3.2.18', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.109', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.110', '3.2.1.35', '1.14.14.1', '3.1.3.91', '3.6.1;3.6.1.-', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '6.3.1.11', '3.5.1.-;3.5.1.78', '6.3.1.8;6.3.1.9', '1.13.11.52', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.5.1.4;3.5.1.99', '1.14.13.30', '3.1.3', '1.13.11.11;1.13.11.52', '3.1.3.29', '3.1.3.-', '3.5.1.24;3.5.1.74', '1.1.1.23', '6.3.1.9', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.72', '1.1.1.273', '1.1.1.273', '1.1.1.273', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.78', '1.14.14.145', '1.13.11.11;1.13.11.52', '1.14.-.-', '1.14.-.-', '3.5.1.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '6.3.1.13', '1.1.1.317', '1.1.1.317', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.1.1.1;1.1.1.161', '6.3.1.10', '6.3.1.10', '3.5.1.90', '3.5.1.90', '1.1.99.1', '6.3.2.56;6.3.2.ad', '1.14.13.246', '1.1.1', '3.1.3.M8', '1.1.1.273', '3.5.1.60;3.5.1.99', '3.5.1.60', '3.5.1.60;3.5.1.99', '3.5.1.99', '3.5.1.99', '3.1.3.105', '3.5.1.60', '3.4', '3.2.1.14', '3.1.3.29', '1.14.13.-', '1.14.-.-', '1.14.13.144', '3.4.15.6', '3.4.19.7', '3.2.1.-', '1.1.1.-', '1.13.99.3', '1.14.13.-', '1.14.13.-', '1.13.11.52', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.15.5', '1.14.15.5', '1.14.15.5', '1.1.1.1', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.176', '1.14.13.194', '6.3.2;6.3.2.-', '6.3.2', '3.1.3.73', '3.1.3.73', '6.3.2', '6.3.2', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '6.3.2', '3.1.3.73', '6.3.2', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '1.1.1.1;1.1.1.161', '1.14.13.15;1.14.15.15', '6.3.2.37', '1.14.13.72', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '6.3.1.10', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.14.13.182', '1.14.13.182', '1.13.99.3', '3.1.3.-', '3.1.3', '6.3.2.58', '6.3.2.58', '3.1.3.-;3.1.3.102;3.1.3.2', '3.5.1.115', '1.1.1;1.1.1.206', '1.13.11.52', '3.1.3.76', '4.2.3;4.2.3.1', '1.13.11.52', '3.5.1.46', '1.1.1.1;1.1.1.190', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '1.1.1;1.1.1.1']
32
160
ERGOTAMINE TARTRATE
5

100%|██████████| 11047/11047 [00:05<00:00, 2044.76it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3447.70it/s]
 31%|███▏      | 85/271 [18:51<42:56, 13.85s/it]

rxndb num 1197
failedrxn num 0
result_df 128
['3.5.1.94', '3.1.3.69', '3.4.19.14', '2.3.2.2;3.4.19;3.4.19.13', '3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '6.3.2.1', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.27', '3.5.1.92', '3.1.3.74', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.6.2', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '3.1.3.10', '3.1.3.39', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.5.1.22', '6.3.2.23', '6.3.1.2;6.3.1.6', '3.5.1.65', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '6.3.2.20', '3.5.1.26', '3.1.3.40', '3.1.6.9', '3.1.6.10', '3.5.1.24;3.5.1.74', '3.5.1.24', '3.1.3.69', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.17.1.3', '3.5.1.93', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.-;3.1.3.88', '3.1.3.79', '6.3.2.36', '1.14.14.-;1.14.14.1', '3.1.3.85', '1.14.-.-', '3.1.3.83', '1.3.3.13', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '3.5.1.-', '6.3.2.44', '6.3.4.24', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.224', '1.14.13.224', '3.1.3.103', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '3.4.19.11', '3.5.1.70', '6.3.2.18', '3.1.3', '6.3.2;6.3.2.-', '6.3.2', '6.3.2', '3.1.3.-', '3.4.19.16', '3.4.19.16', '3.4.19.16', '3.4.19.16', '3.4.19.16', '3.4.19.16', '3.4.19.16', '6.3.2', '3.4.19.16', '3.1.3;3.1.3.-', '3.4.11.25', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.14.13;1.14.13.-', '6.3.2.59', '6.3.2.59', '3.4.19.13;3.4.19.9', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '1.3.1', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.13', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '6.3.2', '3.1.3', '3.4.13;3.4.13.-', '6.3.2', '3.4.13', '6.3.2', '3.1.3.4', '3.1.3.4', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '1.13.11', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2', '3.4', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '3.5.1.115', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.8', '1.14.13.8', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.1.6.14', '3.5.1.11', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.1.3.29', '1.14.15.15', '3.1.3.33;3.1.3.5', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.4.15.1;3.4.21.39', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '3.5.1.23', '3.5.1.23', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '3.2.1.78', '3.2.1.78', '3.2.1.78', '3.2.1.78', '3.1.3', '3.1.3', '1.13.11.52', '3.1.6.3', '3.1.3.68', '6.3.2.18', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '3.4.11.5', '3.4.11.5', '3.4.11.5', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.55', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.82', '3.2.1.15;3.2.1.82', '3.2.1.15;3.2.1.82', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.18', '3.2.1.145;3.2.1.23', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '3.2.1.35', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '3.1.3.91', '3.6.1;3.6.1.-', '3.2.1.137;3.2.1.78', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.34', '1.3.1;1.3.1.-', '3.1.3.29', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.3.1.11', '3.5.1.-;3.5.1.78', '6.3.1.8;6.3.1.9', '1.13.11.52', '3.1.3.23;3.1.3.29;3.1.3.9', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.5.1.11', '3.1.3.27', '3.5.1.4;3.5.1.99', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.24', '3.1.3.12', '1.13.11.11;1.13.11.52', '6.3.2.10', '3.1.3.29', '3.1.3.-', '3.5.1.24;3.5.1.74', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '6.3.1.9', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '6.3.2.10', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.13.11.11;1.13.11.52', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.-.-', '1.14.-.-', '3.5.1.-', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '6.3.1.13', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.19.41;1.3.1.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.45', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.3.68', '3.1.3.10', '3.1.3.10', '6.3.1.10', '6.3.1.10', '3.5.1.90', '3.5.1.90', '3.4.19.16', '6.3.2.56;6.3.2.ad', '3.4.19.13', '3.1.3.M8', '6.3.2.45', '3.5.1.60;3.5.1.99', '3.1.3.106;3.1.3.76', '3.5.1.60', '3.5.1.60;3.5.1.99', '3.5.1.99', '3.5.1.99', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '3.5.1.128', '3.5.1.60', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.4', '3.1.3.58;3.1.3.9', '3.1.3.10', '3.1.6.3', '3.2.1.14', '3.2.1.14', '3.2.1.14', '3.2.1.37', '3.2.1.37', '3.2.1.55', '3.2.1.55', '3.2.1.3;3.2.1.58;3.2.1.59', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '2.7.1.62', '2.7.1.62', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.4.15.6', '3.4.15.6', '3.4.15.6', '3.4.19.7', '3.4.19.7', '3.4.19.7', '3.2.1.1', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.-', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '3.2.1.2', '1.13.99.3', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.13.11.52', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '3.5.1.28', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.15.5', '3.1.3.-', '3.2.1.15', '3.2.1.15', '3.2.1.15', '4.2.2.2', '4.2.2.2', '4.2.2.2', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '3.2.1.137', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '3.1.3.27', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.176', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.194', '6.3.2;6.3.2.-', '1.14.13', '1.14.13', '3.1.3', '6.3.2', '3.1.3.73', '3.2.1.143', '3.1.3.73', '6.3.2', '6.3.2', '3.4.19.16', '3.1.3', '3.1.3.73', '3.4.19.13', '3.1.3.73', '3.4.19.13', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.4.19.13', '3.1.3.73', '3.4.19.13', '6.3.2', '3.4.19.13', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.106', '3.4.19.13', '6.3.2', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '6.3.4.13', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '6.3.2.37', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '3.1.3.23;3.1.3.94', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '6.3.1.10', '3.1.3.7;3.1.3.97', '3.1.3.7', '3.1.3.82', '1.3.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.182', '1.14.13.182', '1.13.99.3', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '3.1.3.58;3.1.3.9', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '6.3.2.58', '6.3.2.58', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.5.1.115', '1.1.1;1.1.1.206', '1.1.1;1.1.1.206', '1.1.1;1.1.1.206', '1.13.11.52', '3.1.3.76', '4.2.3;4.2.3.1', '1.13.11.52', '3.5.1.46', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75']
45
258
ESZOPICLONE
5

100%|██████████| 11047/11047 [00:02<00:00, 4093.17it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4032.55it/s]
 32%|███▏      | 86/271 [19:03<41:14, 13.37s/it]

rxndb num 125
failedrxn num 0
result_df 27
['1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '3.8.1.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.13.224', '1.14.13.224', '1.14.13.224', '1.14.13.224', '1.14.13.224', '1.14.13.224', '1.14.13.8', '1.2.3.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.14.55', '3.8.1.7', '1.14.18.1', '1.14.18.1', '3.4.11.5', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '1.14.14.1', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.11', '1.14.13.11', '1.17.3.1', '1.17.3.1', '1.17.3.1', '1.17.3.1', '1.17.3.1', '1.17.3.1', '1.14.13.5', '1.14.13.5', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.4.15.6', '3.4.15.6', '3.4.19.7', '3.4.19.7', '1.3.98.-', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '3.2.1.143', '1.14.13.182', '1.14.13.182', '1.14.19.58', '1.14.14.7;1.14.19.9', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9']
19
56
ETHOPROPAZINE
5

100%|██████████| 11047/11047 [00:04<00:00, 2366.39it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4217.00it/s]
 32%|███▏      | 87/271 [19:17<41:08, 13.41s/it]

rxndb num 80
failedrxn num 0
result_df 12
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190']
4
17
ETHOXZOLAMIDE
5

100%|██████████| 11047/11047 [00:02<00:00, 4005.63it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4062.47it/s]
 32%|███▏      | 88/271 [19:29<39:41, 13.01s/it]

rxndb num 40
failedrxn num 0
result_df 16
['1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.2.1.35', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.2.1.3', '1.14.13.176', '1.14.13.176', '3.2.1.143', '3.6.1.18;3.6.1.9']
6
16
ETHYNODIOL DIACETATE
5

100%|██████████| 11047/11047 [00:03<00:00, 3288.13it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4186.19it/s]
 33%|███▎      | 89/271 [19:41<38:59, 12.86s/it]

rxndb num 1579
failedrxn num 0
result_df 160

100%|██████████| 11047/11047 [00:03<00:00, 2973.90it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4207.74it/s]
 33%|███▎      | 90/271 [19:55<38:59, 12.93s/it]

rxndb num 845
failedrxn num 0
result_df 70
['1.2.1.-;1.2.1.99', '1.1.1.23', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.2.1.3', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.15', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.2.1.24;1.2.1.5;1.2.1.88;1.5.1.12', '1.5.1.12', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.1.1.118;1.1.1.47', '1.1.1.119;1.1.1.47', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.17.1.1', '1.17.1.1', '1.14.14.-;1.14.14.1', '1.2.1.40', '1.14.13.72', '1.2.1.74', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.14.13.181', '1.2.1.-;1.2.1.99', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.2.1.-;1.2.1.83', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.1.1.363;1.1.1.388', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.116', '1.1.1.359;1.1.1.376;1.1.1.46', '1.14.13', '1.14.13;1.14.13.-', '1.2.1;1.2.1.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.14.133', '1.14.14.133', '1.14.14.133', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.1', '1.14.13;1.14.13.-', '1.1.1.-', '1.1.1', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.15.15', '1.14.15.15', '1.2.1.19', '1.1.1.179;1.3.1.20', '1.1.1.179;1.3.1.20', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.2.1.19;1.2.1.3', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.2.1.3;1.2.1.5', '6.3.1.2', '1.14.13', '1.14.13', '1.14.13', '1.2.1.48;1.2.1.5', '1.2.1.48;1.2.1.5', '1.2.1.48', '1.2.1.48', '1.2.1.48;1.2.1.5', '6.3.4.2', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.1.1.121', '1.2.1.5', '1.2.1.5', '1.2.1.5', '1.2.1.3;1.2.1.5', '1.2.1.3;1.2.1.5', '1.1.1.47', '1.13.11;1.13.11.12;1.13.11.33', '1.1.1.122', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.2.3.1', '1.14.13.72', '1.2.1.74', '3.4.11.5', '1.1.1.23;1.1.1.24', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '6.3.2.17', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.15.3', '1.14.15.3', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.30', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.23', '4.1.1.42', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.2.1.31', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.1.1.113', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.2.1.3', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.72', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.78', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.185', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.-.-;1.14.13.-', '1.14.-.-;1.14.13.-', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.2.1.31', '1.14.13.88', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.88', '1.2.1.95;1.2.1.z', '1.2.1.31', '1.2.1.3', '1.1.1.363;1.1.1.388;1.1.1.47;1.1.1.49', '1.14.14.22;1.14.99.46', '1.2.1.3', '1.1.1.376', '1.11.2.4', '1.11.2.4', '1.1.1.420', '1.2.1.-', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.1.1.120', '3.2.1.14', '1.1.1.121;1.1.1.175', '1.1.1.121', '1.1.1.179', '1.1.1.179', '1.1.1.46', '1.1.1.46', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.1.1.121', '1.14.-.-', '1.14.-.-', '1.14.-.-;1.14.13.-', '1.14.-.-;1.14.13.-', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13.144', '3.2.1.87', '3.4.19.9', '3.4.19.7', '1.2.1.5', '1.14.13.-', '1.14.13.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.-', '1.14.13.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.13.99.3', '1.13.99.3', '1.14.11.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.174', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.15.5', '1.14.15.5', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.2.1.70;6.1.1.17', '1.1.1.117', '1.1.1.117', '1.1.1.117', '1.1.1.117', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.2.1.5', '1.2.1.5', '1.2.1.5', '1.2.1.5', '1.2.1.5', '1.2.1.5', '1.2.1.5', '1.2.1.5', '1.2.1.5', '1.2.1.5', '1.2.1.5', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.46', '1.1.1.46', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.88', '1.14.13.176', '1.14.13.176', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.194', '1.14.13.194', '1.14.13', '1.14.13', '3.2.1.143', '3.5.1', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.1.1.363;1.1.1.49', '1.14.13.15', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.13.99.3', '1.13.99.3', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.1.1.118', '1.1.1.120;1.1.1.179;1.1.1.359;1.1.1.360;1.1.1.47;1.1.1.48;1.3.1.20', '1.1.1.120', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.2.1.3;1.2.1.40', '1.1.1.119', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.1.1.121;1.1.1.359;1.1.1.47;1.1.1.48', '1.1.1.121', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.1.1.363;1.1.1.47;1.1.1.49', '1.1.1.49', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '5.2.1.M1', '1.2.1', '1.2.1', '1.1.1.424', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.2.1.3;1.2.1.48;1.2.1.5', '1.2.1.19', '1.2.1.3;1.2.1.48;1.2.1.5', '1.2.1.48;1.2.1.5', '1.2.1.48', '1.2.1.3;1.2.1.48;1.2.1.5', '1.2.1.48', '1.2.1.3;1.2.1.5', '1.2.1.5', '1.2.1.3;1.2.1.36;1.2.1.48;1.2.1.5', '1.2.1.3;1.2.1.5', '1.2.1.3;1.2.1.48;1.2.1.5', '1.2.1.3;1.2.1.5', '1.14.13.-', '1.14.13.-', '1.14.-.-;1.14.13.-;1.14.13.cs', '1.14.-.-;1.14.13.-;1.14.13.cs']
35
152
EZETIMIBE
5

100%|██████████| 11047/11047 [00:02<00:00, 3835.99it/s]
100%|██████████| 27873/27873 [00:09<00:00, 3086.09it/s]
 34%|███▎      | 91/271 [20:09<39:52, 13.29s/it]

rxndb num 914
failedrxn num 0
result_df 107
['3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '3.1.3.74', '3.1.3.74', '1.14.14.1', '3.1.3.73', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.219', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '3.1.6.9', '3.1.6.10', '1.1.1.219', '1.14.13.19', '1.14.13.19', '1.1.1.234', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.20', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.234', '1.14.13.-;1.14.13.20;1.14.13.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.17.1.3', '1.17.1.3', '1.14.13.-', '1.1.1.234', '1.17.1.3', '1.1.1.362', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.219', '1.1.1.219', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.-;3.1.3.88', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.1.1.349', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.217', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.103', '1.10.3.1;1.14.18.1', '3.1.3', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '3.1.3.-', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.1.1.362', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.348', '1.1.1.348', '1.14.13.20', '1.14.13;1.14.13.20', '3.1.6.14', '3.1.3.29', '3.1.3.33;3.1.3.5', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.6.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.3;1.3.1.120', '1.14.14.91', '1.14.14.91', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3', '3.1.3.48', '3.1.3.2;3.1.3.48;3.1.3.76', '3.1.3.48', '3.1.3.48', '3.1.3.2', '3.1.3', '3.1.3', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.1.1.-', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.35', '1.14.18.-', '1.14.13.18', '1.14.13.18', '3.1.3.91', '3.6.1;3.6.1.-', '1.14.13', '1.1.1.246;1.1.1.348', '1.1.1.219', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3;3.1.3.2;3.1.3.48', '3.1.3.29', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.3.-', '4.2.1.94', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '3.1.3.73', '1.1.1.219', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.45', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.M8', '3.1.3.105', '1.3.1.120', '1.14.14.1', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.1.1.50', '3.2.1.14', '3.1.3.29', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.-.-.-', '1.14.13.-', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.-', '1.14.13.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13', '3.1.3.73', '3.1.3.73', '1.14.13.236', '1.14.13.236', '1.14.13.236', '1.14.13.236', '1.14.13.236', '1.14.13.236', '1.14.13.236', '3.1.3.73', '3.1.3.73', '1.14.13.236', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.3.1', '1.3.1.-', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.8', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1;1.1.1.206', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '3.1.3.-;3.1.3.104']
25
122
FAMCICLOVIR
5

100%|██████████| 11047/11047 [00:02<00:00, 4444.81it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3689.68it/s]
 34%|███▍      | 92/271 [20:21<39:14, 13.15s/it]

rxndb num 149
failedrxn num 0
result_df 34
['3.1.1.5', '3.5.4.11', '3.1.1.70', '3.1.1.54', '3.8.1.8', '1.14.13.181', '3.5.4.-', '1.14.13.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.1.1.53', '3.5.4.-;3.5.4.26', '3.5.4.-;3.5.4.26', '3.5.4.32', '1.14.13.-', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.14.13.224', '1.14.13.224', '6.3.2', '6.3.2', '3.1.1;3.1.1.1;3.1.1.3', '1.7.1;1.7.1.-', '3.1.1', '3.1.1', '1.14.13.235', '3.1.1.26', '3.1.1.4', '1.14.13', '1.14.13', '3.5.4.3', '3.5.4.3', '1.14.13', '1.14.13.M9', '3.1.1', '3.1.1', '3.1.1', '3.1.1;3.1.1.-', '3.1.1', '1.3.1', '1.14.13', '3.1.1', '1.1.1.-', '1.17.1.4', '3.1.1.1;3.1.1.3', '3.1.1.1', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '1.1.1.2', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.14.14.1', '1.14.14.1', '3.4.21;3.4.21.62', '3.4.16.5;3.4.21;3.4.21.62', '1.14.14.55', '3.8.1.7', '3.8.1.8', '3.8.1.8', '3.4.11.5', '2.3.1.-', '3.5.4.-;3.5.99.-', '3.5.4.42;3.5.99.4', '3.5.4.45;3.5.99.-', '3.5.4.-', '3.1.1', '1.14.14.1', '3.5.4.3', '3.1.1.5', '3.1.1.5', '1.1.1.204;1.17.1.4', '1.17.3.2', '1.14.13.74', '1.14.13.74', '3.1.1.10', '2.-.-.-', '1.14.13.74', '1.14.13.74', '3.1.1.80', '1.14.13.97', '1.14.13.97', '3.1.1.80', '3.1.1.80', '1.14.13.-', '1.14.13.-', '3.1.1.94', '2.3.1.-', '1.17.3.1', '1.17.3.1', '3.1.1.105', '3.1.1.105', '3.5.1.M13', '1.14.13.5', '3.1.1.80', '3.1.1.116', '1.2.3.1', '3.5.4.11', '3.1.1.53', '3.1.1.53', '3.1.1.53', '3.1.1.53', '3.4.15.6', '3.2.1.-', '3.1.-.-', '3.1.-.-', '3.1.1.53', '6.2.1.3', '3.1.1.5', '3.1.1.101', '3.2.1.143', '1.6.6.8;1.7.1.7', '6.3.4.1;6.3.5.2', '3.5.4.15', '3.1.1', '3.1.1', '3.1.1', '3.1.1.53', '3.1.1.53', '3.6.1.18;3.6.1.9', '3.1.1.7;3.1.1.8']
27
72
FAMPROFAZONE
5

100%|██████████| 11047/11047 [00:03<00:00, 2838.18it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4399.21it/s]
 34%|███▍      | 93/271 [20:35<38:59, 13.14s/it]

rxndb num 142
failedrxn num 0
result_df 21
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91']
7
20
FEBUXOSTAT
5

100%|██████████| 11047/11047 [00:02<00:00, 3898.17it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3294.15it/s]
 35%|███▍      | 94/271 [20:49<39:52, 13.52s/it]

rxndb num 369
failedrxn num 0
result_df 42
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.2.3.1;1.2.3.8', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.2.1.67', '1.2.1.28;1.2.1.64;1.2.1.96', '1.2.1.29;1.2.3.1', '1.2.1.29;1.2.3.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.2.1.7;1.2.1.96', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.2.1.-;1.2.1.3;1.2.1.65', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.19', '1.14.13.19', '3.5.5.6', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.2.3.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.154', '1.14.13.154', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.2.1.7', '1.2.1.28;1.2.1.3;1.2.1.64', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.13.-', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1.415;1.1.1.ee', '1.14.13', '1.14.13', '1.14.13', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.2.1', '1.2.1.29', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M67', '1.2.1.7', '1.2.1.7', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.2.3.1;1.2.3.8', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.2.1.3', '1.2.1.3', '1.2.1.3', '1.2.1.3;1.2.1.5', '1.1.3.38', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.-.-', '1.14.-.-', '1.14.13.154', '1.14.13.154', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.82', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.-.-', '2.4.1.-', '1.14.13.30', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.88', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.1.1.415', '1.14.14.22;1.14.99.46', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.2.1.102;1.2.1.M12', '1.2.3.1', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '1.14.-.-', '3.2.1.87', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.188', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.194', '3.2.1.143', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '2.6.1.114', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '1.14.13.127']
28
96
FENOFIBRATE
5

100%|██████████| 11047/11047 [00:02<00:00, 4421.75it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4381.03it/s]
 35%|███▌      | 95/271 [21:00<37:40, 12.85s/it]

rxndb num 671
failedrxn num 0
result_df 95
['1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '3.1.1.22;3.1.1.75', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.6', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.6', '1.14.13.6', '1.14.13.6', '1.14.13.6', '1.14.12.9', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '3.1.1.70', '1.14.13.19', '1.14.13.19', '1.1.1.173;1.1.1.378', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '3.1.1.51', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.219;1.14.13.7', '1.14.13.219;1.14.13.7', '1.14.13.219;1.14.13.7', '1.14.13.219;1.14.13.7', '1.1.1.256', '1.1.1.256', '1.14.13.-;1.14.13.20;1.14.13.7', '1.14.13.-;1.14.13.20;1.14.13.7', '1.14.13.-;1.14.13.20;1.14.13.7', '1.14.13.-;1.14.13.20;1.14.13.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.180', '1.14.13.180', '1.14.13.-;1.6.5.2', '1.14.13.-;1.6.5.2', '1.14.13.-;1.6.5.2', '1.14.13.-;1.6.5.2', '1.14.13.-', '1.14.13.-', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.105', '1.1.-.-', '1.14.-.-', '1.14.-.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.-.-', '1.14.-.-', '1.14.13.-;1.14.13.171', '1.13.12.20', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.1.1.203', '1.1.1.203', '1.1.1.363;1.1.1.388', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.220', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.14.14.108', '1.14.14.108', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.1.1.203', '3.1.1;3.1.1.1;3.1.1.3', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.1', '3.1.1.26', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.1.13', '1.1.1.-;1.1.1.377;1.1.1.378', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.19', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '1.14.13.M9', '3.1.1', '1.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.105', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.1.1;3.1.1.13;3.1.1.3', '3.1.1.1;3.1.1.3', '3.1.1.1', '1.14.15.15', '1.14.15.15', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '3.4.21;3.4.21.62', '3.4.16.5;3.4.21;3.4.21.62', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.6', '3.8.1.6', '3.8.1.6', '3.8.1.6', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.12.9', '1.14.12.9', '1.14.12.9', '1.14.12.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.154', '1.14.13.154', '1.2.1.74', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.-', '1.14.13.-', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.82', '3.2.1.15;3.2.1.82', '3.2.1.76', '3.2.1.76', '3.2.1.31', '3.2.1.31', '3.1.1', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.-.-', '1.14.-.-', '2.4.1.-', '1.14.13.30', '1.14.13.30', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.1.1.107;1.1.1.122', '2.3.1.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.1.1.363;1.1.1.388;1.1.1.47;1.1.1.49', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.87', '3.2.1.87', '1.14.13.-', '1.14.13.-', '1.14.14.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.-.-', '3.1.-.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.15.5', '1.14.15.5', '3.2.1.15', '3.2.1.15', '4.2.2.2', '4.2.2.2', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.1.1.256', '1.1.1.256', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.194', '1.14.13.194', '3.1.1.101', '3.1.1.101', '1.14.13.236', '1.14.13.236', '1.14.13.236', '1.14.13.236', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.1.1.363;1.1.1.49', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.1.88', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.27', '1.14.14.27', '1.14.14.27', '1.14.14.27', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.1.1.363;1.1.1.47;1.1.1.49', '1.1.1.49', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127']
29
104
FENSPIRIDE
5

100%|██████████| 11047/11047 [00:02<00:00, 4256.85it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3904.12it/s]
 35%|███▌      | 96/271 [21:13<37:01, 12.69s/it]

rxndb num 300
failedrxn num 0
result_df 29
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14.25', '1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '1.14.14.55', '1.14.15.4', '1.14.15.4', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '6.3.2.17', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '1.14.-.-', '1.14.-.-', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.74', '1.14.13.74', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '3.2.1.87', '3.4.15.6', '3.4.19.9', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13', '3.2.1.143', '1.14.13.M64', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '1.11.2.6', '1.11.2.6', '1.11.2.6']
24
67
FEXOFENADINE
5

100%|██████████| 11047/11047 [00:03<00:00, 3461.90it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3670.22it/s]
 36%|███▌      | 97/271 [21:26<37:41, 13.00s/it]

rxndb num 1642
failedrxn num 0
result_df 111

100%|██████████| 11047/11047 [00:04<00:00, 2747.60it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3926.58it/s]
 36%|███▌      | 98/271 [21:41<38:43, 13.43s/it]

rxndb num 1313
failedrxn num 0
result_df 122
['3.5.1.94', '3.5.1.94', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '6.3.2.1', '6.3.2.1', '3.5.1.92', '3.5.1.92', '1.3.1.104;1.3.1.38;1.3.1.8', '4.2.1.17;4.2.1.74', '3.5.1.22', '3.5.1.22', '6.3.2.23', '6.3.2.23', '6.3.1.2;6.3.1.6', '6.3.1.2;6.3.1.6', '3.5.1.65', '3.5.1.65', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '6.3.2.20', '6.3.2.20', '1.3.1.5', '1.3.1.5', '3.5.1.24;3.5.1.74', '3.5.1.24;3.5.1.74', '3.5.1.24', '3.5.1.24', '1.3.1.48', '1.3.1.48', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.5.1;1.5.1.-', '1.14.13.-', '1.14.13.-', '6.3.2.36', '6.3.2.36', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-;1.14.13.161', '3.5.1.-', '3.5.1.-', '6.3.2.44', '6.3.2.44', '1.14.13;1.14.13.-', '6.3.4.24', '6.3.4.24', '1.14.13.228', '6.3.2.18', '6.3.2.18', '6.3.2;6.3.2.-', '6.3.2;6.3.2.-', '6.3.2', '6.3.2', '6.3.2', '6.3.2', '4.2.1;4.2.1.-', '3.4.11.25', '3.4.11.25', '1.14.13;1.14.13.-', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '4.2.1;4.2.1.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.3.1.93', '1.3.1.93', '6.3.2.59', '6.3.2.59', '6.3.2.59', '6.3.2.59', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1.93', '4.2.1.119', '4.2.1.119', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.4.13', '3.4.13', '6.3.2', '6.3.2', '4.2.1.134', '1.3.1.93', '1.3.1.93', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '4.2.1.17', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '4.2.1.17', '4.2.1.17', '4.2.1.17', '1.3.1', '1.3.1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2', '6.3.2', '3.4', '3.4', '3.5.1.115', '3.5.1.115', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '4.2.1.119', '3.5.1.23', '3.5.1.23', '4.2.1.119', '1.3.1.48', '1.3.1.48', '1.3.1.48', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '1.14.15.15', '1.14.15.15', '1.14.15.15', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.3;1.3.1.120', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.1', '6.3.2.18', '6.3.2.18', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.13.70;1.3.1.70', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.13.108', '1.2.1.74', '1.2.1.74', '3.4.11.5', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-;1.14.13.129', '1.14.13.-;1.14.13.129', '1.14.13.-;1.14.13.129', '1.14.13.-;1.14.13.129', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '4.2.1;4.2.1.-', '1.14.13.-;1.14.13.129', '1.14.13.-;1.14.13.129', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.3.1;1.3.1.-', '1.3.1;1.3.1.-', '1.3.1;1.3.1.-', '1.3.1;1.3.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-;1.14.13.129', '1.14.13.-;1.14.13.129', '6.3.1.11', '6.3.1.11', '3.5.1.-;3.5.1.78', '3.5.1.-;3.5.1.78', '6.3.1.8;6.3.1.9', '6.3.1.8;6.3.1.9', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.5.1.4;3.5.1.99', '3.5.1.4;3.5.1.99', '1.14.13.30', '1.14.13.30', '1.14.13.30', '3.5.1.24;3.5.1.74', '3.5.1.24;3.5.1.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '6.3.1.9', '6.3.1.9', '1.3.1.104;1.3.1.38;1.3.1.8', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.3.1.104;1.3.1.38;1.3.1.44;1.3.1.8', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.5.1.-', '3.5.1.-', '6.3.1.13', '6.3.1.13', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1;1.3.1.44', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '4.2.1.17', '1.3.99.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.-.-', '1.3.99.3', '1.1.1;1.3.99.3', '1.3.1.9', '1.3.99.3', '6.3.1.10', '6.3.1.10', '6.3.1.10', '6.3.1.10', '3.5.1.90', '3.5.1.90', '3.5.1.90', '3.5.1.90', '4.2.1.-;4.2.1.150;4.2.1.17;4.2.1.74', '4.2.1.17;4.2.1.74', '6.3.2.56;6.3.2.ad', '6.3.2.56;6.3.2.ad', '1.3.1.42', '3.5.1.60;3.5.1.99', '3.5.1.60;3.5.1.99', '3.5.1.60', '3.5.1.60', '3.5.1.60;3.5.1.99', '3.5.1.60;3.5.1.99', '3.5.1.99', '3.5.1.99', '3.5.1.99', '3.5.1.99', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.3.1.120', '3.5.1.60', '3.5.1.60', '3.4', '3.4', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '3.2.1.14', '3.2.1.14', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '3.4.15.6', '3.4.15.6', '3.4.19.7', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.-', '3.2.1.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.13.70', '1.14.13.70', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.15.5', '1.14.15.5', '1.14.15.5', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.186', '1.14.13.194', '1.14.13.194', '1.14.13.194', '6.3.2;6.3.2.-', '6.3.2;6.3.2.-', '6.3.2', '6.3.2', '6.3.2', '6.3.2', '6.3.2', '6.3.2', '1.3.3.6', '6.3.2', '6.3.2', '6.3.2', '6.3.2', '1.14.14.1', '6.3.2.37', '6.3.2.37', '4.2.1.119', '4.2.1.119', '4.2.1.17', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.3.1.104;1.3.1.38;1.3.1.8', '6.3.1.10', '6.3.1.10', '1.3.99.-', '1.3.99.-', '1.3.99.-', '1.3.99.-', '4.2.1.17;4.2.1.74', '4.2.1.17;4.2.1.74', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.3.3.6;1.3.8.1;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.3.3.6', '1.3.3.6', '1.3.1.10;1.3.1.38;1.3.1.8', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '6.3.2.58', '6.3.2.58', '6.3.2.58', '6.3.2.58', '1.17.99.11', '3.5.1.115', '3.5.1.115', '4.2.1.17', '1.1.1;1.1.1.206', '1.1.1;1.1.1.206', '3.5.1.46', '3.5.1.46']
29
124
FLUCONAZOLE
5

100%|██████████| 11047/11047 [00:03<00:00, 3575.72it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4608.77it/s]
 37%|███▋      | 99/271 [21:53<37:17, 13.01s/it]

rxndb num 152
failedrxn num 0
result_df 19
['3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '3.1.3.74', '3.1.3.74', '3.1.3.73', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '3.1.3.39', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.1.3.-;3.1.3.88', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3;3.1.3.-', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.17.1.4', '1.17.1.4', '3.1.3.33;3.1.3.5', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3.91', '3.6.1;3.6.1.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '3.1.3.73', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.1.3.M8', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '3.1.3.-;3.1.3.104']
9
50
FLUOXETINE
5

100%|██████████| 11047/11047 [00:02<00:00, 3918.14it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3507.62it/s]
 37%|███▋      | 100/271 [22:07<37:56, 13.31s/it]

rxndb num 391
failedrxn num 0
result_df 41
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.5.3.13;1.5.3.17', '1.5.3.13', '1.5.3.13;1.5.3.17', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '2.5.1.46', '1.5.3.14;1.5.99.6', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.5.3.4', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.4.3.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.5.3.15;1.5.3.17', '1.5.1.-;1.5.1.43', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.5.3.21', '1.5.3.-;1.5.3.19', '1.4.3.-;1.4.3.24', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.5.3.16', '1.5.3.14', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '1.5.3.14', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.5.3.16', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.5.3.11;1.5.3.13;1.5.3.16;1.5.3.17', '1.5.3;1.5.3.13;1.5.3.16;1.5.3.17', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.5.1.43', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.5.1.43', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '3.5.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.183', '1.14.13.183', '1.14.13.236', '1.14.13.236', '1.14.13.236', '1.14.13.236', '1.14.13.236', '1.14.13.98', '1.14.13.98', '1.4.3.M1', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127']
22
65
FLUPHENAZINE
5

100%|██████████| 11047/11047 [00:03<00:00, 3525.72it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4415.89it/s]
 37%|███▋      | 101/271 [22:19<36:35, 12.91s/it]

rxndb num 326
failedrxn num 0
result_df 43
['1.1.1.23', '3.1.3.15', '1.1.1.3', '1.1.1.3', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '3.1.3.-', '3.1.3.74', '1.1.1.1', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.1.3.23', '1.1.3.17', '3.1.3.39', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.1.1.191;1.1.1.2;1.1.1.21', '1.1.1.150', '1.1.1.151', '4.99.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1;1.1.1.-;1.1.1.1', '3.1.3.-;3.1.3.88', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.3', '3.1.3;3.1.3.-', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.1.1', '3.1.3', '1.1.1', '1.14.13', '1.14.13', '1.3.1', '1.3.1', '1.1.1', '1.1.1.1', '1.14.14.145', '1.14.15.15', '3.1.3.33;3.1.3.5', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '3.1.3', '3.1.3', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '3.1.3.91', '3.6.1;3.6.1.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.13.30', '3.1.3', '1.1.1.23', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.1.1.273', '1.1.1.273', '1.1.1.273', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.1.1.317', '1.1.1.317', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.1.99.1', '3.1.3.M8', '1.1.1.273', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-', '1.1.1.1', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.1.1.71', '1.1.1.71', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.14.13.M64', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '1.1.1.1;1.1.1.190', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '1.1.1;1.1.1.1', '3.1.3.1;3.1.3.75']
14
77
FLUVOXAMINE MALEATE
5

100%|██████████| 11047/11047 [00:03<00:00, 3308.67it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4346.26it/s]
 38%|███▊      | 102/271 [22:31<35:53, 12.74s/it]

rxndb num 202
failedrxn num 0
result_df 25
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.4.3.22;1.4.3.4', '1.4.3.21;1.4.3.22;1.4.3.4;1.4.3.6', '1.4.3.10;1.4.3.21;1.4.3.22;1.4.3.6', '1.4.3.21;1.4.3.22;1.4.3.4;1.4.3.6;1.4.9.2;1.4.99.4', '1.14.13.59', '1.4.3.8', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.4.3.13;1.4.3.21;1.4.3.22', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.187', '1.14.13.187', '1.14.13.195;1.14.13.196', '1.14.13.196', '1.14.13.209', '1.14.13.209', '1.4.3.4', '1.4.3', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M65', '1.4.3.M4', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.4.3.22', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.4.3.-;1.4.3.M3', '1.4.1.18', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.4.3.20', '1.14.13.11', '1.14.13.11', '6.2.1.3', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '1.3.99.-', '1.3.99.-', '1.4.3.21;1.4.3.22;1.4.3.6', '1.4.3.21', '1.4.3.21;1.4.3.4;1.4.3.6;1.4.9.2;1.4.99.4', '1.4.3.21;1.4.3.22;1.4.3.4', '1.4.3.4']
11
39
GALANTAMINE
5

100%|██████████| 11047/11047 [00:04<00:00, 2752.40it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4125.23it/s]
 38%|███▊      | 103/271 [22:44<35:57, 12.84s/it]

rxndb num 1093
failedrxn num 0
result_df 61
['3.1.3.69', '3.1.3.74', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1;1.14.14.25;1.14.14.55;1.14.14.57', '1.14.13.100', '3.1.3.-', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.27', '3.1.3.74', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.6.2', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.14.18.1', '1.14.18.1', '3.1.3.39', '1.1.1.148', '1.14.14.1', '1.14.14.1', '1.1.3.16', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.1.1.141', '1.1.1.196', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.147', '1.1.1.147', '1.1.1.101', '3.1.6.9', '3.1.6.10', '1.14.13.19', '1.14.13.19', '1.1.1;1.1.1.-', '1.1.1.230', '1.1.1.62', '1.1.1.62', '1.1.1.146', '1.1.1.53', '1.1.1.50', '1.1.1.53', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.1.1.166', '1.1.1.270', '3.1.3.69', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.297', '1.1.1.357', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.270', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.-', '1.1.1;1.1.1.-;1.1.1.50', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.-', '1.14.13.-', '1.14.13.-', '1.1.1.-;1.1.1.329', '3.1.3.-;3.1.3.88', '1.1.1.297', '1.14.13.100;1.14.14.29', '1.1.1.239;1.1.1.62', '1.1.1.213', '1.1.1.209;1.1.1.213;1.1.1.357', '1.1.1.62', '3.1.3.79', '1.1.1.297', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '3.1.3.85', '3.1.3.83', '1.1.1.323', '1.1.1.323', '1.1.1.-;1.1.1.329', '1.1.1.335', '1.1.1.340;1.14.13.-', '1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.213;1.1.1.357;1.1.1.50', '1.11.2.5', '1.11.2.5', '1.1.1.374', '1.14.13.209', '1.14.13.209', '1.1.1.393', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.1.1.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '3.1.3.103', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.1.1.395', '1.1.1.-;1.1.1.395', '3.1.3', '1.14.13', '3.1.3.-', '1.1.1.201', '1.1.1.-;1.1.1.50;1.1.1.52', '1.1.1.391', '1.1.1.-;1.1.1.270', '1.1.1;1.1.1.-;1.1.1.270', '1.1.1.-;1.1.1.270', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.1.1.102', '1.1.1.-;1.1.1.393', '1.1.1.145', '1.1.1;1.1.1.-', '1.1.1;1.1.1.-', '1.14.14.133', '1.14.14.133', '1.14.13', '1.14.13', '1.3.1', '1.3.1', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.1.1', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.1.1.101', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1', '1.1.1', '3.1.3.4', '1.1.1.201', '3.1.3.4', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1', '1.14.13', '1.14.13', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.M11', '1.1.1.M11', '1.1.1.392', '1.1.1.393', '1.1.1.52', '1.1.1.391', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.52', '1.1.1.391', '1.1.1.392;1.1.1.50;1.1.1.52', '1.1.1.392', '1.1.1.393', '1.1.1.393', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1.270', '1.1.1.270', '1.14.13.8', '1.14.13.8', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.2;1.1.1.213;1.1.1.239;1.1.1.62;1.3.1.20', '1.14.14.1', '1.1.1.159', '3.1.6.14', '1.1.1.1', '1.1.1.188;1.1.1.213;1.1.1.50', '1.1.1.1', '3.1.3.29', '1.1.1.149', '1.1.1.145', '1.1.1.1', '1.1.1.1', '1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50;1.3.1.20', '3.1.3.33;3.1.3.5', '1.1.1.239;1.1.1.51', '1.1.1.239;1.1.1.51', '1.1.1.239', '1.1.1.184', '1.1.1;1.1.1.184;1.1.1.62', '1.1.1.184;1.1.1.2;1.1.1.62', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.213;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.50', '1.1.1.51', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.1.1;1.1.1.209', '1.1.1', '1.1.1.209', '1.1.1.209', '1.1.1.209', '1.1.1.209', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.1.1.357;1.1.1.50', '1.1.1.210;1.1.1.357', '1.14.14.1', '1.14.13', '1.14.13', '1.1.1.184', '3.1.3', '3.1.3', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '3.2.1.78', '3.2.1.78', '1.1.1.184;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.50', '1.1.1.184;1.1.1.50', '1.1.1.146', '1.1.1.146', '1.1.1.141', '3.1.3', '3.1.3', '1.1.1.146;1.1.1.159;1.1.1.50', '1.1.99.13', '3.1.3.68', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.1.1.146', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.297', '1.14.13.36', '1.14.13.36', '3.2.1.154;3.2.1.26;3.2.1.80', '3.2.1.4;3.2.1.91', '3.2.1.65', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-;1.14.13.129', '1.14.13.-;1.14.13.129', '1.14.13.-;1.14.13.129', '1.14.13.-;1.14.13.129', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '1.14.13.234', '3.1.3.91', '3.6.1;3.6.1.-', '1.14.13.-;1.14.13.129', '3.1.3.2;3.1.3.31;3.1.3.34', '1.3.1;1.3.1.-', '3.1.3.29', '1.1.1.239;1.1.1.51', '1.1.1;1.1.1.239;1.1.1.62;1.1.1.64', '2.4.1.-', '2.4.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-;1.14.13.129', '1.1.1.-;1.1.1.146', '1.1.1;1.1.1.-;1.1.1.146;1.1.1.51', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62;1.1.1.63', '1.1.1.184;1.1.1.2;1.1.1.213;1.1.1.51;1.1.1.64', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.2;1.1.1.209;1.1.1.21;1.1.1.213;1.1.1.50;1.3.1.20', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.1.3.27', '1.1.1.166;1.1.1.24;1.1.1.282', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.24', '3.1.3.12', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '1.14.14.23', '1.14.13.17', '3.1.3.29', '1.1.1;1.1.1.148;1.1.1.209', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.3.-', '1.1.1.159;1.1.1.50', '1.1.1.176', '1.1.1.206', '1.1.1.236', '1.1.1.198', '1.1.1.227', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.1.1.51', '1.1.1.51;1.1.1.62;1.1.1.64', '1.1.1.238', '1.1.1.231', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.1.1.201', '1.1.1.146', '1.1.1.213;1.1.1.52', '1.1.1.152;1.1.1.184;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1.184;1.1.1.209;1.1.1.213;1.1.1.50', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.1.1.213;1.1.1.50', '1.1.1.50', '1.1.1.209;1.1.1.50', '1.1.1.213;1.1.1.50;1.1.1.51', '1.1.1.149;1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.1.1.213;1.1.1.277;1.1.1.50', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.77', '1.14.13.76', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.1.1.282', '1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.278', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.17', '1.14.13.-;1.14.13.146', '1.14.13.-;1.14.13.146', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.1.1.210;1.1.1.357;1.1.1.50;1.1.1.51', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.1;1.1.1.391', '1.1.1.-;1.1.1.146;1.1.1.209;1.1.1.213;1.1.1.392;1.1.1.50', '3.1.3.73', '3.1.3', '3.1.3', '1.1.1.159', '1.14.13.-;1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.1.1.270', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.213;1.1.1.50;1.1.1.51;1.1.1.53', '1.14.13.89', '1.14.13.89', '1.14.19.41;1.3.1.-', '1.14.13.88', '1.14.13.88', '3.1.3.45', '1.14.13.88', '1.14.13.88', '1.1.1.-;1.1.1.M53', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.3.68', '1.1.1.270', '1.1.1.270', '1.1.1.270', '1.1.1.201', '1.1.1.425', '3.1.3.M8', '1.1.1', '1.1.1.141', '1.1.1.322', '1.1.1.322', '1.1.1.323', '1.1.1.323', '3.1.3.106;3.1.3.76', '1.1.1.141', '1.1.1.64', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '1.1.1;1.1.1.206', '1.1.1', '1.1.1', '1.1.1', '1.14.14.70', '1.14.14.70', '1.1.1', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.1.1.227', '1.14.13.129', '1.14.13.129', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.129', '1.14.13.129', '1.1.1.297', '1.1.1.297', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.121', '1.14.13.121', '1.14.13.134', '1.14.13;1.14.13.143', '1.14.13.145', '1.1.1.323', '1.1.1.323', '1.14.13.99', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.2.1.87', '3.2.1.1', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.-', '1.14.13.-', '1.1.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '3.2.1.2', '1.14.99.45', '1.1.1.145', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.-', '1.14.13.-', '1.1.1.-;1.1.1.270', '1.1.1.-;1.1.1.270', '1.14.13.129', '1.14.13.129', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.1.1.-', '3.1.3.27', '1.1.1.-', '1.1.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '3.1.3', '3.1.3.73', '3.2.1.143', '3.2.1.143', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.14.13.M64', '1.1.1.M51', '3.1.3.73', '1.1.1.M51', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.106', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '1.14.13.100;1.14.13.17;1.14.13.60', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '1.1.1.141;1.1.1.196', '1.1.1.-;1.1.1.1;1.1.1.327', '1.1.1.270', '1.14.13.99', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.1.1.197', '1.1.1.184;1.1.1.189', '3.1.3.82', '1.3.99.-', '1.1.1.296', '1.1.1.296', '1.14.13.-', '1.14.13.-', '1.14.13.106', '1.14.13.106', '1.14.13.106', '1.14.13.106', '1.1.1;1.1.1.51;1.1.1.62', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13;1.14.14.1', '1.1;1.1.1;1.1.1.209;1.1.1.213', '1.1.1.1', '1.1.99.13', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.1.1;1.1.1.184;1.1.1.210;1.1.1.50', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.2;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.3.1.20', '1.1.1.184;1.1.1.357', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.1.1.141', '1.1.1.395', '1.1.1.146', '1.1.1.64', '1.1.1.146', '1.1.1.146', '1.1.1.239', '1.1.1.239', '1.1.1.62', '1.1.1.270', '1.1.1.141', '1.1.1.238', '1.11.2.6', '1.11.2.6', '1.1.1.206', '1.1.1.206', '3.1.3.76', '3.1.3.76', '1.1.1.102', '1.1.1.213;1.1.1.50', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75']
31
238
GLICLAZIDE
5

100%|██████████| 11047/11047 [00:03<00:00, 2836.10it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4483.62it/s]
 38%|███▊      | 104/271 [22:57<35:57, 12.92s/it]

rxndb num 51
failedrxn num 0
result_df 15
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '3.4.11.5', '3.4.11.5', '3.2.1.35', '3.2.1.35', '1.14.13.56', '1.14.13.56', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '3.4.15.6', '3.4.15.6', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.6.1.114']
8
20
GLIPIZIDE
5

100%|██████████| 11047/11047 [00:03<00:00, 3434.41it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3299.34it/s]
 39%|███▊      | 105/271 [23:12<37:10, 13.44s/it]

rxndb num 83
failedrxn num 0
result_df 29
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '3.5.1.40', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.5.1;1.5.1.-', '1.14.13.209', '1.14.13.209', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '3.4.11.5', '3.4.11.5', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '3.2.1.35', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '1.17.3.1', '1.17.3.1', '1.17.3.1', '1.17.3.1', '1.17.3.1', '1.17.3.1', '1.17.3.1', '1.17.3.1', '3.2.1.14', '3.2.1.14', '3.2.1.14', '3.4.15.6', '3.4.15.6', '3.4.15.6', '3.4.19.7', '3.4.19.7', '3.4.19.7', '3.2.1.-', '3.2.1.-', '3.2.1.-', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.6.1.114']
16
33
GRISEOFULVIN
5

100%|██████████| 11047/11047 [00:02<00:00, 3829.84it/s]
100%|██████████| 27873/27873 [00:06<00:00, 3998.14it/s]
 39%|███▉      | 106/271 [23:24<35:56, 13.07s/it]

rxndb num 911
failedrxn num 0
result_df 79
['1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.15.6', '1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.1.1.25;1.1.1.282', '1.3.1.-;1.3.1.22', '1.1.1.148', '1.1.1.148', '1.14.14.1', '1.1.3.16', '1.1.3.16', '1.14.13.58', '1.1.1.141', '1.3.1.3', '1.3.1.22', '1.1.1.196', '1.3.1.22;1.3.1.4', '3.7.1.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.219', '1.1.1.147', '1.1.1.147', '1.1.1.147', '1.1.1.147', '1.14.13.4', '1.17.1.1', '1.17.1.1', '1.14.14.-;1.14.14.1', '1.1.1.143', '1.1.1.143', '1.1.1.142', '1.1.1.142', '1.1.1.219', '1.14.13.19', '1.14.13.19', '1.3.1.3', '1.1.1.225', '1.1.1.234', '1.1.1;1.1.1.-', '1.1.1;1.1.1.-', '1.3.1.3', '1.14.13.20', '1.1.1.230', '1.1.1.230', '3.8.1.7', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.62', '1.1.1.62', '1.1.1.62', '1.1.1.62', '1.1.1.146', '1.1.1.146', '1.1.1.53', '1.1.1.53', '1.1.1.50', '1.1.1.50', '1.1.1.53', '1.1.1.53', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.234', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.1.1.166', '1.1.1.166', '1.14.13.-;1.14.13.20;1.14.13.7', '1.14.13.-', '1.14.13.154', '1.14.13.154', '1.1.1.270', '1.1.1.270', '1.1.1.297', '1.1.1.297', '1.14.13.-', '1.14.13.-', '1.1.1.234', '1.1.1.362', '1.14.13.-', '1.14.13.50', '1.1.1.357', '1.3.1;1.3.1.-;1.3.1.22;1.3.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.3.1;1.3.1.-;1.3.1.22;1.3.99.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.270', '1.1.1.270', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '1.1.1.219', '1.1.1.219', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.-', '1.1.1.-', '1.1.1;1.1.1.-;1.1.1.50', '1.1.1;1.1.1.-;1.1.1.50', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.1.1.-', '1.14.13.-', '1.1.1.297', '1.1.1.239;1.1.1.62', '1.1.1.239;1.1.1.62', '1.3.1.22;1.3.1.30', '1.1.1.213', '1.1.1.213', '1.1.1.209;1.1.1.213;1.1.1.357', '1.1.1.209;1.1.1.213;1.1.1.357', '1.1.1.62', '1.1.1.62', '1.1.1.297', '1.1.1.297', '1.14.-.-', '1.1.1.-;1.1.1.370', '1.1.1.-;1.1.1.370', '1.1.1.-;1.1.1.371', '1.1.1.-;1.1.1.371', '1.1.1.323', '1.1.1.323', '1.1.1.323', '1.1.1.323', '1.1.1.335', '1.1.1.335', '1.1.1.340;1.14.13.-', '1.1.1.340;1.14.13.-', '1.1.1.349', '1.14.13.-', '1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.361', '1.1.1.361', '1.1.1.374', '1.1.1.374', '1.14.13.209', '1.1.1.393', '1.1.1.393', '3.3.2.14', '3.3.2.14', '1.14.-.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '1.14.13.-;1.14.13.M56', '1.1.1.395', '1.1.1.395', '1.3.1.114', '1.3.1.115', '1.1.1.-;1.1.1.395', '1.1.1.-;1.1.1.395', '1.1.1', '1.1.1', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13', '1.14.13', '1.1.1.201', '1.1.1.201', '1.1.1.-;1.1.1.50;1.1.1.52', '1.1.1.-;1.1.1.50;1.1.1.52', '1.1.1.391', '1.1.1.391', '1.1.1.-;1.1.1.270', '1.1.1.-;1.1.1.270', '1.1.1;1.1.1.-;1.1.1.270', '1.1.1;1.1.1.-;1.1.1.270', '1.1.1.-;1.1.1.270', '1.1.1.-;1.1.1.270', '1.1.1', '1.1.1', '1.14.13;1.14.13.-', '1.1.1.-;1.1.1.393', '1.1.1.-;1.1.1.393', '1.3.1', '1.1.1.145', '1.1.1.145', '1.14.13;1.14.13.-', '1.1.1;1.1.1.-', '1.1.1;1.1.1.-', '1.1.1;1.1.1.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.1.1', '1.1.1', '1.1.1.362', '1.14.14', '1.14.13', '1.14.13', '1.1.1', '1.1.1', '1.1.1', '1.1.1.201', '1.1.1.201', '1.14.13', '1.14.13', '1.14.13', '1.1.1', '1.14.13', '1.14.19', '1.3.1', '1.3.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.M11', '1.1.1.M11', '1.1.1.M11', '1.1.1.M11', '1.1.1.392', '1.1.1.392', '1.1.1.393', '1.1.1.393', '1.1.1.52', '1.1.1.52', '1.1.1.391', '1.1.1.391', '1.1.1.395', '1.1.1.395', '1.3.1.115', '1.3.1.114', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.52', '1.1.1.52', '1.1.1.391', '1.1.1.391', '1.1.1.392;1.1.1.50;1.1.1.52', '1.1.1.392;1.1.1.50;1.1.1.52', '1.1.1.392', '1.1.1.392', '1.1.1.393', '1.1.1.393', '1.1.1.393', '1.1.1.393', '1.3.1.116', '1.1.1.348', '1.1.1.348', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.-', '1.1.1.270', '1.1.1.270', '1.1.1.270', '1.1.1.270', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.2;1.1.1.213;1.1.1.239;1.1.1.62;1.3.1.20', '1.1.1;1.1.1.2;1.1.1.213;1.1.1.239;1.1.1.62;1.3.1.20', '1.1.1.159', '1.1.1.159', '1.1.1.1', '1.1.1.1', '1.1.1.188;1.1.1.213;1.1.1.50', '1.1.1.1', '1.1.1.1', '1.14.15.15', '1.1.1.149', '1.1.1.145', '1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50;1.3.1.20', '1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50;1.3.1.20', '1.1.1.50', '1.1.1.239;1.1.1.51', '1.1.1.239;1.1.1.51', '1.1.1.239;1.1.1.51', '1.1.1.239;1.1.1.51', '1.1.1.239', '1.1.1.239', '1.1.1.184', '1.1.1.184', '1.1.1;1.1.1.184;1.1.1.62', '1.1.1;1.1.1.184;1.1.1.62', '1.1.1.184;1.1.1.2;1.1.1.62', '1.1.1.184;1.1.1.2;1.1.1.62', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.50', '1.1.1.51', '1.1.1.51', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.1.1;1.1.1.209', '1.1.1;1.1.1.209', '1.1.1', '1.1.1', '1.1.1.209', '1.1.1.209', '1.1.1.209', '1.1.1.209', '1.1.1.209', '1.1.1.209', '1.14.14.25;1.14.14.55', '1.14.14.25', '1.14.14.25', '1.14.14.91', '1.1.1.357;1.1.1.50', '1.3.1.3', '1.1.1.210;1.1.1.357', '1.1.1.210;1.1.1.357', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.184', '1.14.18.1', '1.14.18.1', '1.1.1;1.1.1.2;1.1.1.213;1.1.1.50;1.3.1.20', '1.14.14.55', '1.14.14.55', '3.2.1.78', '1.1.1.184;1.1.1.209;1.1.1.213;1.1.1.50', '1.1.1.184;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.50', '1.1.1.184;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.50', '1.1.1.184;1.1.1.50', '1.1.1.184;1.1.1.50', '1.1.1.146', '1.1.1.146', '1.1.1.184', '1.1.1.141', '1.1.1.146;1.1.1.159;1.1.1.50', '1.1.1.146;1.1.1.159;1.1.1.50', '1.1.99.13', '1.1.99.13', '1.14.18.1', '1.1.1.-', '1.1.1.-', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.1.1.146', '1.1.1.146', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.154', '1.14.13.154', '1.2.1.74', '1.2.1.74', '1.1.1.297', '1.1.1.297', '1.14.13.36', '1.1.1.-', '1.14.13.-', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.82', '3.2.1.15;3.2.1.82', '1.1.1.-', '1.1.1.-', '3.2.1.18', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-;1.14.13.129', '1.14.13.-;1.14.13.129', '1.14.13.-;1.14.13.129', '1.14.13.-;1.14.13.129', '1.14.13.-;1.14.13.129', '3.2.1.76', '3.2.1.76', '3.2.1.31', '3.2.1.31', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.1.1.246;1.1.1.348', '1.1.1.219', '1.3.1', '1.14.14.91', '1.14.13.-;1.14.13.129', '1.14.-.-', '1.1.1.239;1.1.1.51', '1.1.1.239;1.1.1.51', '1.1.1;1.1.1.239;1.1.1.62;1.1.1.64', '1.1.1;1.1.1.239;1.1.1.62;1.1.1.64', '2.4.1.-', '2.4.1.-', '2.4.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-;1.14.13.129', '1.14.13.-;1.14.13.129', '1.14.13.-;1.14.13.129', '1.1.1.-;1.1.1.146', '1.1.1.-;1.1.1.146', '1.1.1;1.1.1.-;1.1.1.146;1.1.1.51', '1.1.1;1.1.1.-;1.1.1.146;1.1.1.51', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62;1.1.1.63', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62;1.1.1.63', '1.1.1.184;1.1.1.2;1.1.1.213;1.1.1.51;1.1.1.64', '1.1.1.184;1.1.1.2;1.1.1.213;1.1.1.51;1.1.1.64', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.2;1.1.1.209;1.1.1.21;1.1.1.213;1.1.1.50;1.3.1.20', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.2;1.1.1.209;1.1.1.21;1.1.1.213;1.1.1.50;1.3.1.20', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.1.1.166;1.1.1.24;1.1.1.282', '1.1.1.166;1.1.1.24;1.1.1.282', '1.14.13.30', '1.14.14.1', '1.1.1;1.3.1.22;1.3.1.3;1.3.99.5', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '1.3.1;1.3.1.3', '1.3.1.22;1.3.1.30', '1.1.1.213;1.1.1.50;1.3.1.-;1.3.1.3;1.3.1.M16;1.3.99.6', '1.1.1;1.1.1.148;1.1.1.209', '1.1.1;1.1.1.148;1.1.1.209', '1.14.13.21;1.14.13.88', '1.1.1;1.3.1.3', '1.1.1.159;1.1.1.50', '1.1.1.159;1.1.1.50', '1.1.1.176', '1.1.1.176', '1.3.1.3', '1.3.1.3', '1.1.1.198', '1.1.1.198', '1.1.1.227', '1.1.1.227', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.1.1.51', '1.1.1.51', '1.1.1.51;1.1.1.62;1.1.1.64', '1.1.1.51;1.1.1.62;1.1.1.64', '1.1.1.238', '1.1.1.238', '1.1.1.231', '1.14.13.74', '1.14.13.74', '1.1.1.201', '1.1.1.201', '1.1.1.146', '1.1.1.146', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.1.1.213;1.1.1.52', '1.1.1.213;1.1.1.52', '1.1.1.152;1.1.1.184;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1.152;1.1.1.184;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1.184;1.1.1.209;1.1.1.213;1.1.1.50', '1.1.1.184;1.1.1.209;1.1.1.213;1.1.1.50', '1.14', '1.14.13.36', '1.14.13.56', '1.14.13.57', '1.3.1.3;1.3.99.6', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '1.3.1.3;1.3.99.6', '1.1.1.50', '1.1.1.50', '1.1.1.209;1.1.1.50', '1.1.1.209;1.1.1.50', '1.1.1.213;1.1.1.50;1.1.1.51', '1.1.1.213;1.1.1.50;1.1.1.51', '1.1.1.149;1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.149;1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '1.14.13.71;1.14.14.102', '1.14.13.74', '1.14.13.74', '1.1.1.213;1.1.1.277;1.1.1.50', '1.1.1.213;1.1.1.277;1.1.1.50', '1.14.13.79', '1.14.13.79', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14.13.89', '1.1.1.282', '1.1.1.282', '1.1.1.-;1.1.1.166;1.1.1.24;1.1.1.282', '1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.278', '1.1.1.278', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.-.-', '1.14.-.-', '1.14.13.240', '1.14.13.11', '1.14.13.103', '1.14.13.-;1.14.13.146', '1.14.13.147', '1.14.13.147', '1.1.1.18;1.1.1.369', '1.1.1.18;1.1.1.369', '1.1.1.210;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1.210;1.1.1.357;1.1.1.50;1.1.1.51', '1.14.13.-', '1.14.13.-', '1.1.1.1;1.1.1.391', '1.1.1.1;1.1.1.391', '1.1.1.-;1.1.1.146;1.1.1.209;1.1.1.213;1.1.1.392;1.1.1.50', '1.1.1.-;1.1.1.146;1.1.1.209;1.1.1.213;1.1.1.392;1.1.1.50', '1.1.1.219', '1.1.1.159', '1.1.1.159', '1.14.14.149', '1.14.14.149', '1.1.1.270', '1.1.1.270', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.213;1.1.1.50;1.1.1.51;1.1.1.53', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.213;1.1.1.50;1.1.1.51;1.1.1.53', '1.14.13.89', '1.14.13.89', '1.3.1.-;1.3.1.72;1.3.1.M20', '1.3.1.-;1.3.1.71', '1.14.13.88', '1.14.13.88', '1.1.1.-;1.1.1.M53', '1.1.1.-;1.1.1.M53', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.13.127', '1.13.99;1.14.99', '1.1.1.270', '1.1.1.270', '1.1.1.270', '1.1.1.270', '1.1.1.270', '1.1.1.270', '1.1.1.201', '1.1.1.201', '1.1.1', '1.1.1', '1.1.1.425', '1.1.1.425', '1.1.1', '1.1.1', '1.1.1', '1.1.1.141', '1.1.1.322', '1.1.1.322', '1.1.1.322', '1.1.1.322', '1.1.1.323', '1.1.1.323', '1.1.1.323', '1.1.1.323', '1.1.1.141', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.M48', '1.1.1.M48', '1.1.1.64', '1.1.1.64', '1.1.1.50', '1.1.1', '1.1.1', '1.1.1', '1.1.1', '1.1.1', '1.1.1', '1.1.1.227', '1.1.1.227', '1.14.13.129', '1.14.13.129', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.129', '1.1.1.297', '1.1.1.297', '1.1.1.297', '1.1.1.297', '1.14.13.126', '1.14.13.126', '1.14.13.121', '1.14.-.-', '1.14.-.-', '1.14.13.134', '1.1.1.323', '1.1.1.323', '1.1.1.323', '1.1.1.323', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.2.1.87', '1.1.1.-', '1.1.1.-', '1.1.1.18', '1.1.1.18', '1.14.-.-', '1.14.14.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.89', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-;1.14.13.188', '1.1.1.145', '1.14.13.-', '1.14.13.21', '1.3.1.-', '1.3.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.72', '1.14.15.5', '1.1.1.-;1.1.1.270', '1.1.1.-;1.1.1.270', '1.1.1.-;1.1.1.270', '1.1.1.-;1.1.1.270', '1.14.13.129', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '3.2.1.15', '3.2.1.15', '4.2.2.2', '4.2.2.2', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.1.1.-', '1.1.1.-', '1.1.1.-', '1.1.1.-', '1.1.1.-', '1.1.1.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.156', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.194', '1.3.1.114', '1.1.1.M51', '1.1.1.M51', '1.1.1.M51', '1.1.1.M51', '1.14.19.55', '1.1.1.141;1.1.1.196', '1.1.1.-;1.1.1.1;1.1.1.327', '1.1.1.-;1.1.1.1;1.1.1.327', '1.1.1.270', '1.1.1.270', '1.1.1.18', '1.1.1.18', '1.14.13.98', '1.14.13.98', '1.1.1.197', '1.1.1.184;1.1.1.189', '1.1.1.184;1.1.1.189', '1.1.1.112;1.1.1.184', '1.1.1.112;1.1.1.184;1.1.1.51', '1.1.1;1.1.1.112;1.1.1.184;1.1.1.213;1.1.1.50', '1.1.1.112;1.1.1.184;1.1.1.213;1.1.1.50;1.1.1.62;1.3.1.20', '1.14.13.-', '1.14.13.106', '1.14.13.106', '1.1.1;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.51;1.1.1.62', '1.3.1', '1.3.1.-', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.1;1.1.1;1.1.1.209;1.1.1.213', '1.1;1.1.1;1.1.1.209;1.1.1.213', '1.1.1.1', '1.1.1.1', '1.1.99.13', '1.1.99.13', '1.17.99.5', '1.17.99.5', '1.1.1;1.1.1.184;1.1.1.210;1.1.1.50', '1.1.1;1.1.1.184;1.1.1.210;1.1.1.50', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.2;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.3.1.20', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.2;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.3.1.20', '1.1.1.184;1.1.1.357', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.13.-', '1.1.1.141', '1.1.1.395', '1.1.1.395', '1.3.1.22', '1.1.1.146', '1.1.1.146', '1.3.1.22', '1.3.1.22', '1.1.1.64', '1.1.1.64', '1.3.1.22', '1.1.1.146', '1.1.1.146', '1.3.1.22', '1.1.1.146', '1.1.1.146', '1.1.1.239', '1.1.1.239', '1.1.1.239', '1.1.1.239', '1.1.1.62', '1.1.1.62', '1.1.1.270', '1.1.1.270', '1.1.1.141', '1.1.1.238', '1.1.1.238', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50']
26
187
GUANFACINE
5

100%|██████████| 11047/11047 [00:02<00:00, 4423.10it/s]
100%|██████████| 27873/27873 [00:05<00:00, 4885.36it/s]
 39%|███▉      | 107/271 [23:35<34:04, 12.47s/it]

rxndb num 28
failedrxn num 0
result_df 16
['1.14.13.9', '1.14.13.9', '3.8.1.6', '1.14.13.50', '1.14.13.50', '1.97.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13.39;1.14.14.47', '1.14.13.39;1.14.14.47', '3.8.1.6', '3.8.1.6', '1.14.13.-', '1.14.13.-', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.14.13.9', '1.14.13.9', '3.4.15.6', '1.3.98.-', '1.14.19.58', '1.14.14.8', '1.14.14.8']
7
15
HALOPERIDOL
5

100%|██████████| 11047/11047 [00:03<00:00, 3541.53it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3425.07it/s]
 40%|███▉      | 108/271 [23:50<35:27, 13.05s/it]

rxndb num 863
failedrxn num 0
result_df 76
['3.1.3.69', '3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.74', '3.1.3.74', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3.39', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.7.1.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.17.1.1', '1.17.1.1', '1.14.14.-;1.14.14.1', '3.1.6.9', '3.1.6.10', '1.3.1.5', '1.3.1.5', '3.8.1.7', '1.3.1.48', '1.3.1.48', '1.1.1.234', '3.1.3.69', '1.1.1.234', '1.14.13.180', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.1.3.-;3.1.3.88', '3.1.3.79', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '3.1.3.85', '3.1.3.83', '1.1.1.349', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.3.103', '3.1.3', '1.3.3.6', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '1.3.1.93', '1.3.1.93', '1.3.1.93', '1.3.1.93', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.1.1.362', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3', '1.3.1.93', '3.1.3.4', '1.3.1.93', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.19', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.1.1.348', '1.1.1.348', '1.3.3.6', '1.3.1.48', '1.3.1.48', '1.3.1.48', '3.1.6.14', '3.1.3.29', '3.1.3.29', '3.1.3.33;3.1.3.5', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '3.1.3', '3.1.3', '3.1.6.3', '3.1.3.68', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.13.-', '3.4.11.5', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.55', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.145;3.2.1.23', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '3.1.3.91', '3.6.1;3.6.1.-', '1.1.1.246;1.1.1.348', '3.2.1.137;3.2.1.78', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.23;3.1.3.29;3.1.3.9', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.24', '3.1.3.12', '3.1.3.29', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.3.-', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '3.1.3.63', '3.1.3.63', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.3.1.104;1.3.1.38;1.3.1.8', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.3.1.104;1.3.1.38;1.3.1.44;1.3.1.8', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '1.1.1;1.3.1.44', '3.1.3', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.1.3.45', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.3.99.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.68', '1.3.99.3', '1.1.1;1.3.99.3', '1.3.1.9', '3.1.3.M8', '3.1.3.105', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.1.1.50', '3.1.3.58;3.1.3.9', '3.1.6.3', '3.2.1.14', '3.2.1.37', '3.2.1.37', '3.2.1.3;3.2.1.58;3.2.1.59', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.4.15.6', '3.2.1.1', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.3.98.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.-', '1.14.99.-', '3.2.1.2', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.137', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '3.1.3.73', '1.3.3.6', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '1.3.1.93', '1.3.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '1.3.1.104;1.3.1.38;1.3.1.8', '3.1.3.7;3.1.3.97', '3.1.3.7', '3.1.3.82', '1.3.99.-', '1.14.19.58', '3.1.3.58;3.1.3.9', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.3.3.6;1.3.8.1;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.3.3.6', '1.3.3.6', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.3.1.10;1.3.1.38;1.3.1.8', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '3.1.3.76', '3.1.3.76', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '4.2.3;4.2.3.1', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '3.1.3.1;3.1.3.75']
37
189
HYOSCYAMINE
5

100%|██████████| 11047/11047 [00:02<00:00, 4362.01it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3709.83it/s]
 40%|████      | 109/271 [24:02<34:36, 12.82s/it]

rxndb num 1184
failedrxn num 0
result_df 78
['3.1.3.69', '1.1.1.23', '3.1.3.15', '1.1.1.3', '1.1.1.3', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.27', '3.1.3.3', '3.1.3;3.1.3.2', '3.1.3.74', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.1', '3.1.3', '3.1.1.23', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.6.2', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.1.3.23', '3.1.1.22;3.1.1.75', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.3.17', '3.1.3.2;3.1.3.29;3.1.3.38', '1.1.1.118;1.1.1.47', '1.1.1.119;1.1.1.47', '3.1.3.39', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.1.1.164;1.1.1.192', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.1.1.191;1.1.1.2;1.1.1.21', '1.1.1.1;1.1.1.284;1.1.1.73', '1.1.1.150', '1.1.1.151', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.14.13.4', '1.14.13.4', '3.1.6.9', '3.1.6.10', '3.1.1.70', '1.1.1.66', '3.1.1.51', '4.99.1.-', '1.1.1.1;1.1.1.90', '3.1.3.14', '1.1.1.2', '1.1.1.258', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '3.1.3.69', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.76', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.1', '1.14.14.-;1.14.14.1', '1.1.1;1.1.1.-;1.1.1.1', '1.14.13.15;1.14.15.15', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.-;3.1.3.88', '1.14.13.105', '3.1.3.79', '1.14.13.-', '1.14.13.-', '1.1.-.-', '1.14.-.-', '1.1.-.-', '1.2.-.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '3.1.3.85', '3.1.3.83', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.1.1.363;1.1.1.388', '1.1.1.-', '1.1.1.390', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.103', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.1.1.116', '1.1.1.19', '1.1.1;1.1.1.-;1.1.1.1;1.1.1.2;1.1.1.21', '1.1.1.359;1.1.1.376;1.1.1.46', '3.1.3.3', '1.14.14.108', '1.14.14.108', '3.1.3', '1.1.1.1', '3.1.3.-', '1.1.1.365', '3.1.3;3.1.3.-', '6.3.2', '6.3.2', '3.1.3;3.1.3.-', '3.1.1;3.1.1.1;3.1.1.3', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.1.1;1.1.1.-', '1.14.13;1.14.13.-', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '1.3.1', '1.1.1.14;1.1.1.21', '3.1.1', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.1.26', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.1.4', '1.1.1', '3.1.1.23', '3.1.1.23', '3.1.1.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '1.1.1', '3.1.6.c', '3.1.3.4', '3.1.3.4', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.3.48', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M41', '1.1.1', '3.1.3', '1.1.1', '3.1.1', '1.1.1.1', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1.-', '1.1.1', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.105', '1.1.1;1.1.1.-', '3.1.3;3.1.3.-;3.1.3.104;3.1.3.2;3.1.3.29', '1.1.1.2', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.8', '1.14.14.145', '1.14.14.145', '1.14.14.145', '3.1.1.1;3.1.1.13;3.1.1.3', '3.1.1.1;3.1.1.3', '3.1.1.3', '3.1.1.3', '3.1.1.1', '1.1.1.2;1.1.1.71', '3.1.6.14', '1.1.1.2;1.1.1.21;1.1.1.71', '1.1.1.2;1.1.1.71', '1.1.1.21', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.3.29', '3.1.3.29', '1.14.15.15', '3.1.1.1;3.1.1.2', '3.1.1.1;3.1.1.2', '1.1.1.184;1.1.1.21', '1.1.1.184;1.1.1.2;1.1.1.21;1.1.1.71', '1.1.1.179;1.3.1.20', '1.1.1.179;1.3.1.20', '3.1.3.33;3.1.3.5', '1.1.1.21', '1.1.1.1;1.1.1.71', '1.1.1.2', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '1.1.1.405', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.1.1.1', '1.1.1.1', '1.1.1.1;1.1.1.71', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '3.4.21;3.4.21.62', '3.4.16.5;3.4.21;3.4.21.62', '1.14.13', '1.14.13', '1.14.13', '1.1.1;1.1.1.21', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1;1.1.1.10;1.1.1.21', '1.1.1.2', '3.1.3', '3.1.3', '1.1.1.2;1.1.1.21', '1.1.1.1;1.1.1.284', '1.1.1;1.1.1.1;1.1.1.2;1.1.1.21;1.1.1.284;1.1.1.71', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '3.2.1.78', '3.2.1.78', '3.2.1.78', '1.1.1.121', '1.1.1.121', '1.1.1;1.1.1.2;1.1.1.21;1.1.1.71', '1.1.1.2;1.1.1.21;1.1.1.71', '1.1.1.21', '1.1.1.21', '1.1.1.10', '1.1.1.10', '1.1.1.47', '1.1.1.1', '3.1.3', '3.1.3', '3.1.6.3', '1.1.1.122', '3.1.3.68', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.13.109', '1.14.13.36', '1.14.13.36', '1.14.13.36', '3.4.11.5', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.55', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.82', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '6.3.2.17', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.145;3.2.1.23', '3.2.1.110', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '2.3.1.-', '1.1.1.126', '3.1.3.91', '3.6.1;3.6.1.-', '3.1.1', '3.2.1.137;3.2.1.78', '3.1.3.2;3.1.3.31;3.1.3.34', '1.3.1;1.3.1.-', '3.1.3.29', '1.1.1.405', '1.1.1.21', '1.1.1.21', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.2;1.1.1.61;1.2.1.16', '1;1.1.1;1.1.1.-;1.1.1.2;1.1.1.co;1.1.1.n11;1.2.1.16', '3.1.1.5', '3.1.1.5', '3.1.3.23;3.1.3.29;3.1.3.9', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.15.3', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.1.3.27', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.24', '3.1.3.12', '1.1.1;1.1.1.188;1.1.1.19;1.1.1.2;1.1.1.21;1.1.1.307;1.1.1.72', '3.1.3.29', '1.1.1.32;1.1.1.88', '1.1.1.2;1.1.1.32;1.1.1.33', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.3.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.1.1.23', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '3.1.1.10', '3.1.1.10', '1.1.1.113', '3.1.3.63', '3.1.3.63', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.72', '3.1.3.70', '1.1.1.273', '1.1.1.273', '1.1.1.273', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.78', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.14.145', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.-.-;1.14.13.-', '1.1.1.317', '1.1.1.317', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '2.3.1.-', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.1.1.1;1.1.1.161', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.19.41;1.3.1.-', '3.1.3.45', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3', '3.1.3.68', '1.1.1;1.1.1.2;1.1.1.21', '1.1.99.1', '1.1.1.363;1.1.1.388;1.1.1.47;1.1.1.49', '1.14.13.246', '1.1.1', '3.1.3.M8', '1.1.1.131', '1.1.1.131', '1.1.1.273', '1.1.1.200', '3.1.1.116', '3.1.3.106;3.1.3.76', '1.1.1.376', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '1.1.1.420', '1.1.1', '1.1.1.71', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.1.1', '3.1.3.58;3.1.3.9', '3.1.6.3', '1.1.1.120', '3.2.1.14', '1.1.1.121;1.1.1.175', '1.1.1.121', '1.1.1.179', '1.1.1.179', '3.2.1.37', '3.2.1.37', '1.1.1.46', '1.1.1.46', '3.2.1.55', '3.2.1.55', '3.2.1.3;3.2.1.58;3.2.1.59', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.1.1.121', '1.14.13.-', '1.14.-.-', '1.14.-.-;1.14.13.-', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.144', '1.14.13.54', '3.2.1.116', '3.2.1.137', '3.2.1.154', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.4.15.6', '3.4.19.9', '3.4.19.5', '3.4.19.7', '1.1.3.20', '3.2.1.1', '1.7.3.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.-', '1.1.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.-', '1.14.99.-', '3.2.1.2', '3.1.-.-', '3.1.-.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.15.5', '1.14.15.5', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.1.1.1', '1.1.3.20', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '3.2.1.137', '1.1.1.117', '1.1.1.117', '1.1.1.117', '1.1.1.117', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '3.1.1.5', '3.1.3.27', '1.1.1.-', '1.1.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.46', '1.1.1.46', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.194', '3.1.1.101', '3.1.3', '3.1.3.73', '3.2.1.143', '3.1.3.73', '3.1.3', '3.1.3.73', '4.2.1.140;4.2.1.39', '3.1.3.73', '3.1.3.73', '3.1.3.73', '4.2.1.6', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.106', '3.1.3.73', '3.1.3', '1.1.1.2;1.1.1.20;1.1.1.21', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '1.14.13.149', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '1.1.1.1;1.1.1.161', '1.14.13.15;1.14.15.15', '1.1.1.-;1.1.1.36', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.72', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.1.1.363;1.1.1.49', '3.1.3.82', '1.3.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.1.1.118', '1.1.1.120;1.1.1.179;1.1.1.359;1.1.1.360;1.1.1.47;1.1.1.48;1.3.1.20', '1.1.1.120', '3.1.3.58;3.1.3.9', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.1.1.119', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.1.1.121;1.1.1.359;1.1.1.47;1.1.1.48', '1.1.1.121', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.1.1.363;1.1.1.47;1.1.1.49', '1.1.1.49', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.1', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1.424', '3.1.1.3', '3.1.3.76', '3.1.3.76', '1.1.1.1', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '1.14.13.127', '4.2.3;4.2.3.1', '1.1.1.1;1.1.1.190', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '1.1.1;1.1.1.1', '3.1.3.1;3.1.3.75', '1.14.13.-', '1.14.-.-;1.14.13.-;1.14.13.cs']
50
320
IDEBENONE
5

100%|██████████| 11047/11047 [00:03<00:00, 2993.98it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4453.70it/s]
 41%|████      | 110/271 [24:14<33:45, 12.58s/it]

rxndb num 3684
failedrxn num 0
result_df 205

100%|██████████| 11047/11047 [00:03<00:00, 3370.48it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3549.53it/s]
 41%|████      | 111/271 [24:28<34:53, 13.08s/it]

rxndb num 228
failedrxn num 0
result_df 36
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.224', '1.14.13.224', '1.14.13.224', '1.14.13.224', '1.14.13.224', '1.14.13.224', '1.14.13.8', '1.2.3.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.8', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.14.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.4.15.6', '3.4.19.7', '3.2.1.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '2.6.1.114']
14
38
INDAPAMIDE
5

100%|██████████| 11047/11047 [00:02<00:00, 4364.78it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4099.78it/s]
 41%|████▏     | 112/271 [24:40<33:53, 12.79s/it]

rxndb num 87
failedrxn num 0
result_df 27
['1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.8.1.7', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.2.1.35', '3.2.1.35', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.3.98.-', '1.14.19.58']
6
13
INDOMETHACIN
5

100%|██████████| 11047/11047 [00:03<00:00, 2842.97it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4364.42it/s]
 42%|████▏     | 113/271 [24:53<33:51, 12.86s/it]

rxndb num 686
failedrxn num 0
result_df 96
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.2.1.3', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.15', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.2.1.5', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '4.1.1.-', '1.13.12.-', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.12.9', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.2.1.40', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '3.8.1.7', '1.14.13.61', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.14.13.180', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-', '2.1.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.2.1.-;1.2.1.83', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.3.2.14', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13', '1.2.1;1.2.1.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.1', '1.14.19', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.1', '1.13.99.3', '1.1.1.-', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.84', '4.1.1.83', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.3.38', '3.1.1.1;3.1.2.12', '1.14.12.9', '1.14.12.9', '1.14.12.9', '1.14.12.9', '1.14.12.9', '1.14.12.9', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.2.3.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.-', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.82', '3.2.1.15;3.2.1.82', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '1.14.13.10', '4.1.1.83', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '2.4.1.-', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.2.1.3', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.72', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.84', '3.1.1.-;3.1.1.2', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.14.22;1.14.99.46', '1.2.1.101;1.2.1.ah', '4.1.1.115', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.2.1.87', '1.14.14.-', '1.3.98.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.2.1.-', '1.13.99.3', '1.13.99.3', '1.14.11.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.84', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.176', '1.14.13.176', '1.14.13', '3.2.1.143', '1.14.13.15', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.182', '1.14.13.182', '1.14.19.58', '1.13.99.3', '1.2.1.3;1.2.1.40', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '2.6.1.114', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '1.2.1', '1.2.1', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.2.1.29;1.2.1.3;1.2.1.5', '1.2.1.5', '1.2.1.3;1.2.1.5', '1.2.1.5', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.2.1.5', '1.2.1.3;1.2.1.5', '1.2.1.5', '1.2.1.29;1.2.1.5;1.2.1.53', '1.2.1.5', '1.2.1.3;1.2.1.5', '1.2.1.5']
36
107
IRBESARTAN
5

100%|██████████| 11047/11047 [00:03<00:00, 2911.46it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3872.08it/s]
 42%|████▏     | 114/271 [25:07<34:34, 13.21s/it]

rxndb num 195
failedrxn num 0
result_df 30
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.4.15.6', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.1.1;1.1.1.206']
6
23
IRSOGLADINE MALEATE
5

100%|██████████| 11047/11047 [00:02<00:00, 4484.76it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4151.60it/s]
 42%|████▏     | 115/271 [25:19<33:02, 12.71s/it]

rxndb num 73
failedrxn num 0
result_df 25
['3.5.4.11', '3.8.1.7', '3.8.1.7', '3.8.1.8', '3.5.4.-', '1.97.1.-', '1.97.1.-', '1.7.1.-', '1.8.99.3;1.8.99.5', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '3.5.4.-;3.5.4.26', '3.5.4.-;3.5.4.26', '1.14.13.-', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.7.1;1.7.1.-', '3.5.4.3', '3.5.4.3', '1.1.1.2', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.1', '1.14.14.1', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.8', '3.8.1.8', '3.8.1.-', '3.8.1.-', '3.5.4.-;3.5.99.-', '3.5.4.42;3.5.99.4', '3.5.4.45;3.5.99.-', '3.5.4.-', '1.14.14.1', '3.5.99.3', '3.5.99.3', '3.5.4.11;3.5.4.24', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.5.4.11', '1.3.98.-', '1.3.98.-', '1.14.12.-', '1.6.6.8;1.7.1.7', '1.14.19.58', '1.14.19.58', '1.14.14.8', '1.14.14.8', '1.14.14.8']
13
31
ISRADIPINE
5

100%|██████████| 11047/11047 [00:03<00:00, 3240.88it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4326.09it/s]
 43%|████▎     | 116/271 [25:31<32:42, 12.66s/it]

rxndb num 241
failedrxn num 0
result_df 43
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.1.1.51', '3.1.1.51', '3.1.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.1.95', '1.14.13.-;1.14.13.171', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '3.1.1', '3.1.1', '3.1.1', '3.1.1.95', '3.1.1.13', '3.1.1.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '3.1.1', '3.1.1', '1.1.1.-', '1.1.1.-', '3.1.1.1;3.1.1.13;3.1.1.3', '3.1.1.1;3.1.1.13;3.1.1.3', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.13', '1.14.13', '1.14.13', '3.1.1.73', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.36', '1.14.13.36', '1.14.13.36', '3.2.1.15;3.2.1.82', '3.2.1.15;3.2.1.82', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '2.3.1.-', '2.3.1.-', '3.1.1', '3.1.1', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.1.10', '3.1.1.10', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '2.-.-.-', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '2.3.1.-', '2.3.1.-', '1.14.13.88', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.-.-', '3.1.-.-', '3.1.-.-', '3.1.-.-', '3.2.1.15', '3.2.1.15', '4.2.2.2', '4.2.2.2', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.176', '1.14.13.176', '1.14.13.176', '1.14.13.194', '1.14.13.194', '1.14.13.194', '3.2.1.143', '3.2.1.143', '3.1.1.88', '3.1.1.88', '1.14.13.122', '1.14.13.122', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9']
14
56
ITRACONAZOLE
5

100%|██████████| 11047/11047 [00:03<00:00, 2976.04it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3316.14it/s]
 43%|████▎     | 117/271 [25:47<34:31, 13.45s/it]

rxndb num 326
failedrxn num 0
result_df 53
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.8.1.7', '3.8.1.7', '3.2.1.63', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '2.4.1.280', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '3.2.1.159', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.2.1', '3.2.1.40', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.19', '1.14.19', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.2.1', '3.2.1.52', '3.2.1.3', '3.2.1.21;3.2.1.25;3.2.1.58;3.2.1.74', '3.2.1.21', '1.17.3.2', '1.17.3.2', '1.17.3.2', '3.2.1.22', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.2.1.78', '3.2.1.78', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '3.8.1.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.35', '1.14.-.-', '1.14.-.-', '2.4.1.-', '1.14.13.30', '1.14.13.30', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '3.2.1.23', '3.2.1.23', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.97', '1.14.13.97', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.-', '1.14.13.-', '3.2.1', '3.2.1.52', '3.2.1.14', '3.2.1.74', '3.2.1.74', '3.2.1.74', '3.2.1.74', '1.14.-.-', '1.14.-.-', '3.2.1.87', '3.2.1.87', '3.2.1.87', '1.3.98.-', '1.3.98.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.174', '1.14.15.5', '1.14.15.5', '6.2.1.3', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '3.2.1.143', '3.2.1.143', '3.2.1.143', '3.2.1.51', '1.14.19.58', '1.14.19.58', '3.2.1.10;3.2.1.177;3.2.1.20;3.2.1.48', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.2.1.51']
19
74
KETOROLAC TROMETHAMINE
5

100%|██████████| 11047/11047 [00:02<00:00, 4284.70it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3609.37it/s]
 44%|████▎     | 118/271 [25:59<33:38, 13.19s/it]

rxndb num 411
failedrxn num 0
result_df 47
['1.2.1.-;1.2.1.99', '1.1.1.23', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.2.1.3', '1.2.1.24;1.2.1.5;1.2.1.88;1.5.1.12', '1.5.1.12', '1.2.1.3;1.2.1.47', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.61', '1.14.13.61', '4.1.1', '1.2.1.-;1.2.1.99', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.2.1.-;1.2.1.M5', '1.2.1.-;1.2.1.83', '1.13.12.20', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13.235', '1.14.13.235', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.1', '1.3.1', '1.2.1', '1.1.1.-', '1.2.1.47', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.184', '1.2.1.19;1.2.1.3', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '6.3.1.2', '1.1.1.21', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.1.3', '6.3.4.2', '1.14.16.-', '1.14.16.-', '1.1.99.1', '1.14.13.-', '1.14.13.-', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.2.3.1', '3.4.11.5', '3.4.11.5', '1.1.1.23;1.1.1.24', '6.3.2.17', '6.3.2.17', '1.5.1.12;1.5.99.8', '3.2.1.18', '3.2.1.18', '1.14.12.19', '1.14.12.19', '1.1.1.23', '1.14.16.-', '1.14.16.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.2.1.31', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.2.1.3', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.2.1.31', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.2.1.95;1.2.1.z', '1.2.1.31', '1.2.1.3', '1.2.1;1.2.1.-;1.2.1.19;1.2.1.3;1.2.1.5', '1.14.14.22;1.14.99.46', '1.2.1.101;1.2.1.ah', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.4.15.6', '3.4.15.6', '3.4.19.9', '3.4.19.9', '3.4.19.7', '3.4.19.7', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.2.1.3', '1.14.11.-', '1.14.13.-', '1.2.1.70;6.1.1.17', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.176', '3.1.1.101', '3.1.1.101', '3.5.1', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.13.11.90', '1.2.1', '1.13.11.90', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.2.1;1.2.1.19;1.2.1.3', '1.2.1;1.2.1.88;1.5.1.12;1.5.99.8', '1.2.1;1.2.1.-;1.2.1.19;1.2.1.3', '1.2.1.3;1.2.1.5', '1.2.1.5', '1.2.1.19;1.2.1.3;1.2.1.8', '1.2.1.19;1.2.1.8']
34
91
KETOTIFEN FUMARATE
5

100%|██████████| 11047/11047 [00:04<00:00, 2221.43it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4436.23it/s]
 44%|████▍     | 119/271 [26:13<33:51, 13.36s/it]

rxndb num 391
failedrxn num 0
result_df 33
['1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1;1.14.14.25;1.14.14.55;1.14.14.57', '1.14.13.100', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.234', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.100;1.14.14.29', '1.14.13.-', '1.1.1.349', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.348', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.14.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14.25', '1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '1.14.14.55', '1.1.1.184;1.1.1.209;1.1.1.213;1.1.1.50', '1.1.1.184', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.234', '1.1.1.246;1.1.1.348', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.23', '1.14.13.17', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.79', '1.14.13.79', '1.14.13.77', '1.14.13.76', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.94', '1.14.13.94', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.17', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1.50', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13.99', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13', '1.14.13.100;1.14.13.17;1.14.13.60', '1.14.13.99', '1.14.13.98', '1.14.13.98', '1.1.1.112;1.1.1.184', '1.1.1.112;1.1.1.184;1.1.1.51', '1.1.1;1.1.1.112;1.1.1.184;1.1.1.213;1.1.1.50', '1.1.1.112;1.1.1.184;1.1.1.213;1.1.1.50;1.1.1.62;1.3.1.20', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-']
11
74
LABETALOL
5

100%|██████████| 11047/11047 [00:02<00:00, 3890.72it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3289.52it/s]
 44%|████▍     | 120/271 [26:27<34:02, 13.53s/it]

rxndb num 1433
failedrxn num 0
result_df 104

100%|██████████| 11047/11047 [00:02<00:00, 4849.30it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4282.63it/s]
 45%|████▍     | 121/271 [26:38<32:11, 12.88s/it]

rxndb num 78
failedrxn num 0
result_df 28
['1.14.13.58', '1.14.13.58', '1.14.13.58', '3.8.1.7', '3.8.1.7', '3.8.1.8', '3.5.4.-', '1.14.13.-', '1.97.1.-', '1.97.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.8.99.3;1.8.99.5', '1.8.99.3;1.8.99.5', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '3.5.4.-;3.5.4.26', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.5.4.3', '1.1.1.2', '1.1.1.2', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.1', '1.14.14.1', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.8', '3.5.4.-;3.5.99.-', '3.5.4.45;3.5.99.-', '1.14.14.1', '3.5.4.11;3.5.4.24', '1.3.98.-', '1.3.98.-', '1.6.6.8;1.7.1.7', '1.14.19.58', '1.14.19.58']
12
26
LETROZOLE
5

100%|██████████| 11047/11047 [00:03<00:00, 2961.51it/s]
100%|██████████| 27873/27873 [00:05<00:00, 4892.76it/s]
 45%|████▌     | 122/271 [26:51<31:28, 12.67s/it]

rxndb num 26
failedrxn num 0
result_df 6
['1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.17.1.4', '1.17.1.4', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.14.13', '1.14.13', '1.14.13.56', '1.14.13.56', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-']
4
9
LEVAMISOLE
5

100%|██████████| 11047/11047 [00:02<00:00, 4052.63it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4012.32it/s]
 45%|████▌     | 123/271 [27:03<31:15, 12.68s/it]

rxndb num 52
failedrxn num 0
result_df 11
['1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.-.-.-']
5
17
LEVONORGESTREL
5

100%|██████████| 11047/11047 [00:04<00:00, 2656.37it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3901.81it/s]
 46%|████▌     | 124/271 [27:18<32:14, 13.16s/it]

rxndb num 2417
failedrxn num 0
result_df 168

100%|██████████| 11047/11047 [00:03<00:00, 3310.25it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3941.54it/s]
 46%|████▌     | 125/271 [27:31<32:03, 13.17s/it]

rxndb num 354
failedrxn num 0
result_df 42
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.1', '1.13.12.-;1.14.13.178', '1.13.12.-;1.14.13.178', '1.13.12.-;1.14.13.178', '1.13.12.-;1.14.13.178', '1.13.12.-;1.14.13.179', '1.13.12.-;1.14.13.179', '1.13.12.-;1.14.13.178', '1.13.12.-;1.14.13.178', '1.13.12.-;1.14.13.179', '1.13.12.-;1.14.13.179', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.187', '1.14.13.187', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.12.16', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.8', '3.8.1.8', '3.8.1.8', '3.8.1.8', '3.4.11.5', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.M66', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '1.14.-.-', '3.4.15.6', '3.4.15.6', '3.4.19.7', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.176', '1.14.13.194', '1.14.13.182', '1.14.13.182', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '2.6.1.114', '1.14.14', '1.14.14', '1.14.14', '1.14.14']
18
53
LOFEXIDINE
5

100%|██████████| 11047/11047 [00:02<00:00, 4191.85it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4208.03it/s]
 46%|████▋     | 126/271 [27:43<30:59, 12.83s/it]

rxndb num 101
failedrxn num 0
result_df 22
['1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.18.1', '1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.13.20', '1.14.13.20', '3.8.1.7', '1.14.13.50', '1.14.13.50', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '2.1.1.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.14', '1.14.14', '1.14.13.M9', '1.14.13.20', '1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.4.1.-', '1.14.14.1', '1.14.14.1', '1.14.13.50', '1.14.13.50', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.9', '1.14.13.9', '3.2.1.87', '1.14.14.-', '1.3.98.-', '1.-.-.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.143', '1.14.19.58', '3.6.1.18;3.6.1.9', '1.11.2.6', '1.11.2.6']
16
37
LOPERAMIDE
5

100%|██████████| 11047/11047 [00:04<00:00, 2676.47it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3891.70it/s]
 47%|████▋     | 127/271 [27:57<31:38, 13.18s/it]

rxndb num 753
failedrxn num 0
result_df 70
['3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.74', '3.1.3.27', '3.1.3.74', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.6.2', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3.39', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.6.9', '3.1.6.10', '3.8.1.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.8', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.-;3.1.3.88', '3.1.3.79', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '3.1.3.85', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.103', '3.1.3', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.19', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '1.3.1', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '3.1.6.14', '3.1.3.29', '3.1.3.33;3.1.3.5', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.8', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '3.1.3', '3.1.3', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '3.1.3.91', '3.6.1;3.6.1.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.1.3.27', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.24', '3.1.3.29', '3.1.3.-', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '3.1.3.63', '3.1.3.63', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.1.3.45', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.3.68', '3.1.3.M8', '3.1.3.105', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.1.3.29', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '3.4.15.6', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.3.98.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '3.1.3.27', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.14.13.M64', '1.14.13.M64', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '1.14.13.149', '3.1.3;3.1.3.-;3.1.3.4', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.19.58', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1;1.1.1.206', '3.1.3.76', '3.1.3.76', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75']
28
119
LOSARTAN
5

100%|██████████| 11047/11047 [00:02<00:00, 3831.50it/s]
100%|██████████| 27873/27873 [00:09<00:00, 3005.28it/s]
 47%|████▋     | 128/271 [28:12<32:35, 13.68s/it]

rxndb num 221
failedrxn num 0
result_df 32
['3.1.3.15', '3.1.3.74', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.14.1', '1.4.3.5', '3.1.3.74', '1.1.3.12;1.4.3.5', '1.1.1.65', '3.1.3.74', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.1.99.9', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-;3.1.3.88', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3;3.1.3.-', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.33;3.1.3.5', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1;1.1.1;1.1.1.184;1.1.1.2;1.1.1.21;1.1.1.213;1.1.1.50;1.1.1.65;1.1.1.n11', '3.1.3', '3.1.3', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.8', '3.8.1.8', '3.1.3.91', '3.6.1;3.6.1.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3', '1.1.1;1.1.1.-', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.1.3.M8', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.3.99.-', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '1.14.14.1', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75']
12
62
LOVASTATIN
5

100%|██████████| 11047/11047 [00:03<00:00, 3154.06it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3956.32it/s]
 48%|████▊     | 129/271 [28:25<31:59, 13.52s/it]

rxndb num 2199
failedrxn num 0
result_df 190

100%|██████████| 11047/11047 [00:03<00:00, 2796.20it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3559.75it/s]
 48%|████▊     | 130/271 [28:39<32:36, 13.87s/it]

rxndb num 226
failedrxn num 0
result_df 31
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.8.1.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13.8', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '2.4.1.-', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.21.3', '1.14.21.3', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.3.98.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.143', '1.14.19.58', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9']
13
31
MEBENDAZOLE
5

100%|██████████| 11047/11047 [00:02<00:00, 4489.21it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4252.29it/s]
 48%|████▊     | 131/271 [28:51<30:42, 13.16s/it]

rxndb num 275
failedrxn num 0
result_df 25
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.61', '1.14.13.61', '1.14.13.180', '1.14.13.180', '1.14.13.180', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.1.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.1.1.95', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.8', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.140', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.4.15.6', '3.4.15.6', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.140', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.176', '1.14.13.176', '3.2.1.143', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9']
15
52
MEBHYDROLIN NAPHTHALENESULFONATE
5

100%|██████████| 11047/11047 [00:04<00:00, 2528.55it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4403.57it/s]
 49%|████▊     | 132/271 [29:04<30:38, 13.22s/it]

rxndb num 157
failedrxn num 0
result_df 24
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.12.16', '1.14.13.8', '1.14.13.8', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.176', '1.14.13.182', '1.14.13.182']
5
21
MEFLOQUINE
5

100%|██████████| 11047/11047 [00:03<00:00, 3620.39it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3795.45it/s]
 49%|████▉     | 133/271 [29:17<30:16, 13.17s/it]

rxndb num 485
failedrxn num 0
result_df 63
['3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.74', '3.1.3.3', '3.1.3.74', '1.5.3.13;1.5.3.17', '1.5.3.13', '1.5.3.13;1.5.3.17', '2.5.1.46', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '1.5.3.14;1.5.99.6', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3.39', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.6.9', '3.1.6.10', '1.1.1.234', '1.14.13.61', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.1.3.-;3.1.3.88', '1.5.3.15;1.5.3.17', '1.5.1.-;1.5.1.43', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.1.1.349', '3.1.3.92', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.3', '3.1.3', '1.5.3.16', '1.5.3.14', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '1.1.1.348', '1.5.3.14', '3.1.6.14', '3.1.3.29', '1.5.3.16', '3.1.3.33;3.1.3.5', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '3.1.3', '3.1.3', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.110', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '3.1.3.91', '3.6.1;3.6.1.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.5.3.11;1.5.3.13;1.5.3.16;1.5.3.17', '1.5.3;1.5.3.13;1.5.3.16;1.5.3.17', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.29', '3.1.3.-', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.5.1.43', '3.1.3.M8', '3.1.3.105', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.5.1.43', '3.1.3.29', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.176', '1.14.13', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.3.99.-', '1.3.99.-', '1.14.13.182', '1.14.13.182', '1.1.1', '1.1.1', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '1.1.1.422', '1.1.1.423', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1.422', '1.1.1.423', '3.1.3.76', '3.1.3.-;3.1.3.104', '3.1.3.1;3.1.3.75']
29
102
MEGESTROL ACETATE
5

100%|██████████| 11047/11047 [00:03<00:00, 3039.12it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4151.31it/s]
 49%|████▉     | 134/271 [29:30<29:53, 13.09s/it]

rxndb num 2652
failedrxn num 0
result_df 187

100%|██████████| 11047/11047 [00:03<00:00, 2959.04it/s]
100%|██████████| 27873/27873 [00:05<00:00, 4705.85it/s]
 50%|████▉     | 135/271 [29:42<29:00, 12.80s/it]

rxndb num 1306
failedrxn num 0
result_df 45
['1.2.1.3;1.2.1.54', '1.4.1.13;1.4.1.3;1.4.1.4', '1.2.1.-;1.2.1.99', '4.1.1.22;4.1.1.28', '1.1.1.23', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.13.12.2', '1.4.3.2', '1.2.1.3', '4.1.1.17;4.1.1.19;4.1.1.86', '4.1.1.28;4.1.1.53', '1.2.1.24;1.2.1.5;1.2.1.88;1.5.1.12', '1.5.1.12', '4.1.1;4.1.1.-', '1.2.1.3;1.2.1.47', '4.1.1.25;4.1.1.28', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.4.3.2', '1.4.3.11;1.4.3.2', '1.4.3.1;1.4.3.15;1.4.3.3;1.4.3.7', '1.14.13.59', '1.13.12.1', '1.4.1.7', '4.1.1.57', '4.3.1.23;4.3.1.24;4.3.1.25;4.3.1.5', '4.1.99.2', '1.14.18.1', '1.14.18.1', '4.3.1.23;4.3.1.24;4.3.1.25', '5.4.3.6', '1.4.3.12', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '3.10.1.2', '1.4.1.16', '4.1.1.-', '4.1.1.-', '1.4.3.3', '1.2.1.-;1.2.1.99', '1.14.13.-', '1.14.13.-', '1.14.13.-', '4.1.1.86', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '4.3.1.22', '4.1.1.-;4.1.1.96', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.4.3.23', '1.2.1.-;1.2.1.M5', '1.4.1.20', '5.4.3.10', '5.4.3.11', '1.14.13.187', '1.14.13.187', '1.11.2.5', '1.11.2.5', '1.13.11.78', '1.14.13.195;1.14.13.196', '1.14.13.196', '1.4.1.25', '1.4.1.25', '1.14.13.209', '1.14.13.209', '1.4.3.-;1.4.3.2;1.4.3.25', '4.3.1.11;4.3.1.23;4.3.1.25', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.2.1', '1.13.99', '1.14.13.M65', '1.4.3.3', '4.1.1.109', '4.1.1.M23', '1.4.1.20', '1.4.1.20;1.4.1.8', '1.4.1.8', '1.4.3.2', '1.4.3.2', '1.4.3.2', '1.4.3.2', '1.2.1.47', '1.14.13.41;1.14.14.36', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.4.3.3', '4.3.1.24', '1.2.1.19;1.2.1.3', '3.1.3.48', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.91', '1.14.14.91', '6.3.1.2', '1.4.3.3', '1.2.1.3', '6.3.4.2', '1.4.1.2;1.4.1.20', '1.4.1.2;1.4.1.20;1.4.1.8', '1.4.3.3', '1.4.3.3', '1.4.3.3', '1.4.3.3', '1.4.3.2', '1.4.3.2', '1.4.3.2', '1.11.1.7', '4.5.1.2', '1.1.99.1', '1.14.12.9', '1.14.12.9', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '3.4.11.5', '1.1.1.23;1.1.1.24', '6.3.2.17', '1.5.1.12;1.5.99.8', '3.2.1.18', '1.14.14.1', '1.4.3.2', '1.4.3.3', '1.4.1.14;1.4.1.2;1.4.1.3;1.4.1.4', '4.1.1.105;4.1.1.28', '1.4.3.2', '1.4.1.19', '1.4.1.19', '1.13.12.3', '1.11.1.21', '1.11.1.21;1.11.1.7;1.13.12.3;1.13.12.9', '1.1.1.23', '1.2.1.31', '1.14.13.56', '1.14.13.56', '1.4.3.-;1.4.3.23', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.2.1.31', '4.1.1.28', '1.2.1.95;1.2.1.z', '1.2.1.31', '1.2.1;1.2.1.-;1.2.1.19;1.2.1.3;1.2.1.5', '4.1.1.96', '4.1.1.117;4.1.1.y', '1.14.13.M66', '4.1.1.107', '4.1.1.108', '1.2.1.101;1.2.1.ah', '4.1.1.116', '4.1.1.116', '1.14.13.9', '1.14.13.9', '1.13.12.3', '1.14.13.124', '1.14.13.125', '3.4.15.6', '3.4.19.9', '3.4.19.5', '3.4.19.7', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.13.99.3', '1.2.1.3', '1.4.1.3;1.4.1.4', '1.14.13.-', '1.14.13.-', '1.2.1.70;6.1.1.17', '1.14.13.91', '1.14.13.91', '4.1.1.65', '4.1.1.65', '4.1.1.65', '4.1.1.65', '4.1.1.65', '4.1.1.65', '4.1.1.65', '4.1.1.65', '4.1.1.65', '4.1.1.65', '4.1.1.65', '4.1.1.65', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.1.101', '3.5.1', '4.1.1.17;4.1.1.18;4.1.1.19;4.1.1.50', '1.4.3.14;1.4.3.2', '4.1.1.19;4.1.1.50', '4.1.1.20', '1.4.1.20;1.4.1.8;1.4.1.9', '1.14.14.8', '1.14.14.8', '1.13.11.90', '1.13.12.1', '1.13.12.1', '1.13.11.90', '1.11.2.6', '1.11.2.6', '4.1.1', '4.1.1.22;4.1.1.25;4.1.1.28', '4.1.1.15;4.1.1.29', '1.2.1;1.2.1.19;1.2.1.3', '1.2.1;1.2.1.88;1.5.1.12;1.5.99.8', '1.2.1;1.2.1.-;1.2.1.19;1.2.1.3', '4.1.1.19', '4.1.1.15', '1.2.1.19;1.2.1.3;1.2.1.8', '1.2.1.19;1.2.1.8', '1.4.3.3', '1.4.3.3']
38
144
MEMANTINE
5

100%|██████████| 11047/11047 [00:03<00:00, 3542.52it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3756.57it/s]
 50%|█████     | 136/271 [29:56<29:20, 13.04s/it]

rxndb num 431
failedrxn num 0
result_df 41
['3.10.1.2', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.3.1', '1.3.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.15.15', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.13.108', '1.14.13.108', '1.14.13.108', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.30', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5']
8
30
METAXALONE
5

100%|██████████| 11047/11047 [00:02<00:00, 4726.04it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3963.39it/s]
 51%|█████     | 137/271 [30:08<28:29, 12.76s/it]

rxndb num 174
failedrxn num 0
result_df 21
['1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.18.1', '1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.4', '1.14.13.4', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13', '1.14.13', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.18.1', '1.14.18.1', '3.2.1.78', '1.1.3.38', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.13.36', '1.14.13.36', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.82', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.35', '1.14.14.91', '1.14.14.91', '2.4.1.-', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.-', '1.14.13.-', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.88', '1.14.13.88', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.154', '3.2.1.87', '3.2.1.87', '3.4.15.6', '3.4.19.7', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.-.-.-', '1.-.-.-', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.1.101', '3.2.1.143', '3.2.1.143', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '2.6.1.114', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.11.2.6', '1.11.2.6', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127']
26
65
METHOCARBAMOL
5

100%|██████████| 11047/11047 [00:03<00:00, 3102.46it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3906.96it/s]
 51%|█████     | 138/271 [30:22<28:57, 13.07s/it]

rxndb num 1085
failedrxn num 0
result_df 64
['3.1.3.69', '1.1.1.14;1.1.1.6', '1.1.1.1;1.1.1.10;1.1.1.156;1.1.1.2;1.1.1.21;1.1.1.72;1.3.1.20', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.1.5', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.27', '3.1.3.3', '3.1.3;3.1.3.2', '3.1.3.74', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.1.1;1.1.1.10', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3.2;3.1.3.29;3.1.3.38', '1.1.1.137', '1.1.1.137;1.1.1.405', '1.1.1.69', '3.10.1.1', '3.1.3.22;3.1.3.23', '3.1.3.39', '1.1.1.148', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.5.1.75', '1.1.3.16', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.6', '1.14.13.6', '1.14.13.6', '1.14.13.6', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.101', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '3.1.3.40', '1.1.1.143', '1.1.1.142', '3.1.6.9', '3.1.6.10', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.1.1;1.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-;1.1.1.342', '1.1.1.226', '3.1.3.14', '1.1.1.62', '1.1.1.62', '1.1.1.53', '1.1.1.50', '1.1.1.53', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.14.13.219;1.14.13.7', '1.14.13.219;1.14.13.7', '1.14.13.219;1.14.13.7', '1.14.13.219;1.14.13.7', '1.1.1.166', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.2;1.1.1.21;1.1.1.261', '1.1.1.263', '3.1.3.69', '1.1.1.274', '1.1.1;1.1.1.-', '1.1.1.364', '1.14.13.-', '2.1.3.12', '1.14.13.-;1.6.5.2', '1.14.13.-;1.6.5.2', '1.14.13.-;1.6.5.2', '1.14.13.-;1.6.5.2', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '3.1.3.76', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '2.1.1.-', '1.14.-.-', '1.1.1.-', '1.1.1;1.1.1.-;1.1.1.50', '1.1.1.292', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.162', '1.1.1.-', '1.1.1.-', '1.1.1.-;1.1.1.341;4.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.274;1.1.1.346', '1.1.1.-;1.1.1.329', '3.1.3.-;3.1.3.88', '1.1.1.-', '1.1.1.213', '3.1.3.79', '1.1.3.-;1.1.3.45', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '3.1.3.80', '1.1.1.301', '3.1.3.85', '3.1.3.83', '2.1.3.-', '1.1.1.-;1.1.1.370', '1.1.1.-;1.1.1.371', '1.1.1.-;1.1.1.329', '1.1.1.335', '1.1.1.339;1.1.1.344', '1.1.1.355', '1.1.1.356', '1.1.1.356', '1.1.1.361', '3.1.3.92', '1.1.1.364', '1.1.1.367', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '6.1.2.2', '1.1.1.374', '1.1.1.385', '1.1.1.389', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.1.1.393', '3.3.2.14', '3.1.3.101', '3.1.3.-', '1.1.1.-', '1.1.1.-', '1.1.1.-', '3.1.3;3.1.3.-', '1.1.1.-', '1.1.1.402', '1.1.1.14;1.1.1.162;1.1.1.403', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.220', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '3.1.3.103', '1.1.1.251', '1.1.1.289', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.1.1.395', '1.1.1.-;1.1.1.395', '1.1.1.14;1.1.1.15', '1.1.1', '1.1.1.14', '1.1.3.11', '3.1.3.3', '3.1.3', '1.14.13', '3.1.3.25', '3.1.3.25', '3.1.3.-', '1.1.1;1.1.1.-', '3.1.3;3.1.3.-', '1.1.1.201', '1.1.1.-;1.1.1.50;1.1.1.52', '1.1.1.391', '5.4.99.30;5.4.99.9', '1.1.1', '1.1.1', '1.1.1.15', '3.1.3;3.1.3.-', '1.1.1;1.1.1.-;1.1.1.12', '1.1.1', '1.1.1', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.1.1.102', '1.1.1.145', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.1', '1.1.1', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.1.1', '3.1.3.50', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.1.1.101', '1.14.13', '1.1.1', '1.1.1', '3.1.3', '3.1.3.4', '1.1.1.201', '3.1.3.4', '1.1.1', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1', '1.1.1.M2', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.M11', '1.1.1.M11', '1.1.1.392', '1.1.1.393', '1.1.1.52', '1.1.1.391', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.52', '1.1.1.391', '1.1.1.392;1.1.1.50;1.1.1.52', '1.1.1.392', '1.1.1.393', '1.1.1.393', '3.1.3', '1.1.1.M28', '1.1.1.14;1.1.1.M29', '1.1.1', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '3.1.3;3.1.3.-;3.1.3.104;3.1.3.2;3.1.3.29', '3.1.3', '3.1.3;3.1.3.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1.140', '1.1.1.123', '1.1.1.159', '1.1.1.218', '3.1.6.14', '1.1.1.218', '3.1.3.29', '3.1.3.29', '1.1.1.149', '1.1.1.140;1.1.1.17', '3.1.3.33;3.1.3.5', '1.1.1.133', '1.1.1.239', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '2.3.2.2;6.3.1.2', '1.1.1.213;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.50', '1.1.1.292', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.1.1', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3', '3.1.3', '1.14.14.55', '3.2.1.78', '1.1.1.12;1.1.1.14', '1.1.1.12;1.1.1.14', '1.1.1.12', '1.1.1;1.1.1.10;1.1.1.405', '1.1.1.10', '3.1.3', '3.1.3', '1.1.1.146;1.1.1.159;1.1.1.50', '3.1.6.3', '1.1.99.13', '3.1.3.68', '1.1.1.162', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.-', '1.14.15.4', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.133', '1.14.15.4', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.55', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.82', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '1.1.1.-', '6.3.2.17', '3.2.1.65', '3.1.1.75', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.145;3.2.1.23', '3.2.1.110', '3.2.1.76', '3.2.1.31', '3.2.1.35', '1.1.1.125;1.1.1.127', '3.1.3.91', '3.6.1;3.6.1.-', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '3.2.1.137;3.2.1.78', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '2.4.1.-', '2.4.1.-', '1.14.-.-', '1.14.-.-', '1.1.1.-;1.1.1.146', '1.1.1;1.1.1.-;1.1.1.146;1.1.1.51', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '3.1.1.5', '3.1.3.23;3.1.3.29;3.1.3.9', '1.1.1.124;1.1.1.138;1.1.1.14;1.1.1.67;1.1.99.11;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.27', '1.1.1.166;1.1.1.24;1.1.1.282', '1.1.1.14;1.1.1.56', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '1.1.1.12;1.1.1.124;1.1.1.138;1.1.1.14;1.1.1.67;1.1.1.9;1.1.99.11;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.1.3.24', '1.1.1.58', '1.1.1.133', '3.1.3.12', '1.1.1.14;1.1.1.9', '1.1.1.213;1.1.1.50', '1.1.1.271', '1.1.1.124;1.1.1.138;1.1.1.21;1.1.1.287;1.1.1.67;1.1.99.11;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '1.1.1.124;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '2.3.2.7', '3.1.3.29', '1.1.1;1.1.1.148;1.1.1.209', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.3.-', '1.1.1.134;1.1.1.344', '1.1.1.159;1.1.1.50', '1.1.1.176', '1.1.1.16', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.1.1.174', '1.1.1.135;1.1.1.187', '1.1.1.187;1.1.1.281', '1.1.1.135;1.1.1.187', '1.1.1.187;1.1.1.281', '1.1.1.238', '1.14.13.74', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.1.1.146', '1.1.1.213;1.1.1.52', '3.1.3.63', '3.1.3.63', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.1.1.50', '1.1.1.209;1.1.1.50', '2.-.-.-', '1.1.1.266', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.74', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.1.1.282', '1.14.13.94', '1.14.13.96', '1.14.13.97', '3.1.3.21;3.1.3.25;3.1.3.29', '3.1.3.21;3.1.3.25', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.147', '1.1.1.18;1.1.1.369', '1.14.13.-', '1.1.1.380', '1.1.1.1;1.1.1.391', '1.1.1.-;1.1.1.146;1.1.1.209;1.1.1.213;1.1.1.392;1.1.1.50', '3.1.3.73', '1.1.1;1.1.1.-', '3.1.3', '3.1.3', '1.1.1.159', '1.1.1.-', '3.1.3.25', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.14.13.88', '1.14.13.88', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.1.1;1.1.1.10', '1.1.1.10;1.1.1.14;1.1.1.15', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.45', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.1.1.-;1.1.1.M53', '1.14.13.88', '1.14.13.88', '3.1.3', '3.1.3.68', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.1.1.414', '2.1.3', '2.1.3', '1.1.1.201', '1.1.1', '1.1.1.425', '3.1.3.M8', '1.1.1.266', '3.1.3.106;3.1.3.76', '1.1.1.367', '1.1.1.57', '1.1.1.406', '1.1.1.407', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.1.1.14', '1.1.1', '1.1.1.10', '1.1.3.10', '1.1.3.10', '3.1.3.58;3.1.3.9', '3.1.6.3', '3.2.1.14', '3.2.1.37', '3.2.1.37', '3.2.1.55', '3.2.1.55', '3.2.1.3;3.2.1.58;3.2.1.59', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.1.1.274', '3.1.1.75', '3.2.1.116', '3.2.1.137', '3.2.1.154', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.4.15.6', '3.4.19.9', '3.4.19.5', '3.4.19.7', '3.2.1.1', '1.1.1.-', '1.1.1.18', '1.7.3.-', '1.7.3.-', '1.7.3.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.-', '2.1.3.-', '3.2.1.2', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.15', '4.2.2.2', '6.2.1.3', '6.2.1.3', '6.2.1.3', '3.2.1.137', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.94', '1.14.13.96', '1.1.1.-', '3.1.3.27', '1.1.1.-', '1.14.13.88', '1.14.13.88', '1.14.13.184', '3.1.1.101', '3.1.3', '3.1.3.73', '4.2.1.67', '3.2.1.143', '3.2.1.143', '3.2.1.143', '3.1.3.73', '3.1.3', '3.1.3.73', '4.2.1.140;4.2.1.39', '3.1.3.73', '4.2.1.90', '3.1.3.73', '3.1.3.73', '4.2.1.6', '1.1.1.M51', '3.1.3.73', '1.1.1.M51', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.106', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '1.1.1.18', '3.1.3.25', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.1.1.184;1.1.1.189', '3.1.3.82', '3.1.3.29;3.1.3.50', '3.1.3.50', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1;1.1.1.51;1.1.1.62', '1.1.1.271', '1.1.1.271', '1.1.99.13', '3.1.3.58;3.1.3.9', '1.17.99.5', '1.14.13.97', '1.17.99.5', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.27', '1.14.14.27', '1.14.14.27', '1.14.14.27', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.1.5.3;1.1.99.5', '1.1.1.367', '1.1.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.395', '1.1.1', '1.14.13', '1.1.1.146', '1.1.1.239', '1.1.1.238', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '3.1.3.76', '3.1.3.76', '1.1.1.102', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '4.2.3;4.2.3.1', '1.1.1;1.1.1.69', '1.1.1.213;1.1.1.50', '3.1.3.-;3.1.3.104', '1.1.1.261', '3.1.3.1;3.1.3.19;3.1.3.2;3.1.3.25;3.1.3.29', '1.1.1.8;1.1.1.94;1.1.5.3', '1.1.1.49;1.1.1.8;1.1.1.94;1.3.1.20', '3.1.3.2;3.1.3.21']
52
349
METHOXSALEN
5

100%|██████████| 11047/11047 [00:03<00:00, 3391.65it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3434.99it/s]
 51%|█████▏    | 139/271 [30:36<29:24, 13.37s/it]

rxndb num 502
failedrxn num 0
result_df 46
['1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.6', '1.14.13.6', '1.14.13.6', '1.14.13.6', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.219;1.14.13.7', '1.14.13.219;1.14.13.7', '1.14.13.219;1.14.13.7', '1.14.13.219;1.14.13.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.6.5.2', '1.14.13.-;1.6.5.2', '1.14.13.-;1.6.5.2', '1.14.13.-;1.6.5.2', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.3.2.14', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.220', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.14.13', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.99', '1.14.99', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3;1.3.-.-', '1.14.13;1.14.14', '1.14.13;1.14.14', '1.14.13;1.14.14', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.1', '1.14.14.1', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.21', '1.14.13.21', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.82', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.76', '3.2.1.31', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '2.4.1.-', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.88', '1.14.13.88', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '3.2.1.14', '3.2.1.87', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '3.2.1.15', '4.2.2.2', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.88', '1.14.13.88', '3.2.1.143', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.27', '1.14.14.27', '1.14.14.27', '1.14.14.27', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127']
24
73
METHSUXIMIDE
5

100%|██████████| 11047/11047 [00:02<00:00, 4513.82it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4051.54it/s]
 52%|█████▏    | 140/271 [30:48<28:19, 12.97s/it]

rxndb num 194
failedrxn num 0
result_df 25
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.17.1.1', '1.17.1.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.1', '1.1.1.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.-.-', '1.14.13.-;1.14.13.161', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.25', '1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '1.14.14.55', '1.14.15.4', '1.14.15.4', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '3.2.1.14', '3.2.1.14', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '3.2.1.-', '3.2.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '3.5.2', '3.5.2', '1.14.13.149', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.1.1;1.1.1.206', '1.1.1;1.1.1.206']
16
45
METHYLPHENIDATE
5

100%|██████████| 11047/11047 [00:03<00:00, 2861.90it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4066.58it/s]
 52%|█████▏    | 141/271 [31:01<28:26, 13.13s/it]

rxndb num 280
failedrxn num 0
result_df 45
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.5.3.13;1.5.3.17', '1.5.3.13', '1.5.3.13;1.5.3.17', '2.5.1.46', '1.5.3.14;1.5.99.6', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.4', '1.14.13.4', '1.14.13.4', '3.1.1.70', '3.1.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.5.3.15;1.5.3.17', '1.5.1.-;1.5.1.43', '3.1.1.95', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.5.3.16', '1.5.3.14', '6.3.2', '6.3.2', '3.1.1', '3.1.1', '3.1.1.26', '1.14.14', '1.14.14', '1.14.14', '3.1.1.4', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '3.1.1', '1.5.3.14', '1.1.1.-', '3.1.1.3', '3.1.1.3', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '1.5.3.16', '1.1.1.179;1.3.1.20', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.1.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '3.4.21;3.4.21.104;3.4.21.42', '3.4.21;3.4.21.62', '3.4.16.5;3.4.21;3.4.21.62', '3.5.1.11', '1.1.1.47', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '6.3.2.17', '3.2.1.49;3.2.1.52', '3.2.1.18', '2.3.1.-', '3.1.1', '3.1.1.5', '1.5.3.11;1.5.3.13;1.5.3.16;1.5.3.17', '1.5.3;1.5.3.13;1.5.3.16;1.5.3.17', '1.14.12.19', '1.14.12.19', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '3.1.1.10', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.5.1.43', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.5.1.43', '3.2.1.14', '3.2.1.87', '3.4.15.6', '3.4.19.9', '3.4.19.5', '3.4.19.7', '3.2.1.-', '1.14.99.-', '1.14.99.-', '3.1.-.-', '3.1.-.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '3.1.1.5', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.1.101', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '1.14.13.149', '1.3.99.-', '1.3.99.-', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.11.2.6', '1.11.2.6', '1.11.2.6']
36
92
METHYSERGIDE MALEATE
5

100%|██████████| 11047/11047 [00:04<00:00, 2572.64it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3175.77it/s]
 52%|█████▏    | 142/271 [31:17<30:00, 13.96s/it]

rxndb num 494
failedrxn num 0
result_df 54
['3.5.1.94', '1.1.1.23', '3.1.3.15', '1.1.1.3', '1.1.1.3', '3.1.3.74', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.1.3.-', '6.3.2.1', '3.1.3.74', '3.5.1.92', '3.1.3.74', '1.1.1.1', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.6.2', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.1.3.23', '1.1.3.17', '3.1.3.39', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.5.1.22', '1.1.1.191;1.1.1.2;1.1.1.21', '6.3.2.23', '6.3.1.2;6.3.1.6', '3.5.1.65', '6.3.2.20', '3.1.6.9', '3.1.6.10', '3.5.1.24;3.5.1.74', '3.5.1.24', '1.14.13.72', '1.14.13.-', '1.14.13.-', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.5.1;1.5.1.-', '1.1.1;1.1.1.-;1.1.1.1', '1.14.13.15;1.14.15.15', '3.1.3.-;3.1.3.88', '1.14.13.-', '1.14.13.-', '6.3.2.36', '3.5.1.-', '6.3.2.44', '6.3.4.24', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.224', '1.14.13.224', '6.3.2.18', '3.1.3.3', '3.1.3', '6.3.2;6.3.2.-', '6.3.2', '6.3.2', '3.1.3.-', '3.1.3;3.1.3.-', '6.3.2', '3.4.11.25', '1.1.1;1.1.1.-', '1.14.13;1.14.13.-', '6.3.2.59', '6.3.2.59', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.13.235', '1.1.1', '3.1.3', '1.1.1', '3.4.13', '6.3.2', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '1.1.1', '1.1.1.1', '6.3.2', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.4', '3.5.1.115', '1.14.13.8', '1.14.13.8', '1.14.14.145', '1.14.14.145', '1.14.14.145', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.1.6.14', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.1.3.29', '1.14.15.15', '3.1.3.33;3.1.3.5', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14.25', '1.14.14.25', '3.5.1.23', '3.5.1.23', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '1.14.14.55', '1.14.14.55', '3.1.3', '3.1.3', '6.3.2.18', '1.14.15.4', '1.14.15.4', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.13.109', '1.2.1.74', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.14.1', '3.1.3.91', '3.6.1;3.6.1.-', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '6.3.1.11', '3.5.1.-;3.5.1.78', '6.3.1.8;6.3.1.9', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.5.1.4;3.5.1.99', '1.14.13.30', '3.1.3', '3.1.3.29', '3.1.3.-', '3.5.1.24;3.5.1.74', '1.1.1.23', '1.14.13.74', '1.14.13.74', '6.3.1.9', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.72', '1.1.1.273', '1.1.1.273', '1.1.1.273', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.78', '1.14.14.145', '1.14.13.97', '1.14.13.97', '1.14.-.-', '1.14.-.-', '3.5.1.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '6.3.1.13', '1.1.1.317', '1.1.1.317', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.1.1.1;1.1.1.161', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '6.3.1.10', '6.3.1.10', '3.5.1.90', '3.5.1.90', '1.1.99.1', '6.3.2.56;6.3.2.ad', '1.14.13.246', '1.1.1', '3.1.3.M8', '1.1.1.273', '3.5.1.60;3.5.1.99', '3.5.1.60', '3.5.1.60;3.5.1.99', '3.5.1.99', '3.5.1.99', '3.1.3.105', '3.5.1.60', '3.4', '3.2.1.14', '3.1.3.29', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.13.144', '3.4.15.6', '3.4.19.7', '3.2.1.-', '1.1.1.-', '1.13.99.3', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.-.-.-', '1.14.13.174', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.15.5', '1.14.15.5', '1.14.15.5', '1.1.1.1', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.176', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.194', '6.3.2;6.3.2.-', '6.3.2', '3.1.3.73', '3.1.3.73', '6.3.2', '6.3.2', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '6.3.2', '3.1.3.73', '6.3.2', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '1.1.1.1;1.1.1.161', '1.14.13.15;1.14.15.15', '6.3.2.37', '1.14.13.98', '1.14.13.98', '1.14.13.72', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '6.3.1.10', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.14.13.182', '1.14.13.182', '1.13.99.3', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '3.1.3.-', '3.1.3', '6.3.2.58', '6.3.2.58', '3.1.3.-;3.1.3.102;3.1.3.2', '3.5.1.115', '1.1.1;1.1.1.206', '1.13.11.11;1.13.11.52', '3.1.3.76', '4.2.3;4.2.3.1', '3.5.1.46', '1.1.1.1;1.1.1.190', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '1.1.1;1.1.1.1']
34
169
METICRANE
5

100%|██████████| 11047/11047 [00:02<00:00, 4335.97it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3807.37it/s]
 53%|█████▎    | 143/271 [31:30<28:59, 13.59s/it]

rxndb num 35
failedrxn num 0
result_df 15
['1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.209', '1.14.13.209', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '3.2.1.35', '3.2.1.35', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '2.6.1.114']
6
13
METITEPINE MALEATE
5

100%|██████████| 11047/11047 [00:04<00:00, 2447.26it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4316.45it/s]
 53%|█████▎    | 144/271 [31:44<28:58, 13.69s/it]

rxndb num 143
failedrxn num 0
result_df 27
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.8', '2.5.1.18', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '2.5.1.18', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.32']
5
19
METOCLOPRAMIDE
5

100%|██████████| 11047/11047 [00:02<00:00, 4207.39it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4135.10it/s]
 54%|█████▎    | 145/271 [31:57<28:05, 13.38s/it]

rxndb num 167
failedrxn num 0
result_df 29
['1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '3.5.1.40', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '3.8.1.7', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.180', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.-.-', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '3.3.2.14', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.14', '1.14.14', '1.14.19', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.2', '1.1.1.2', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.13.-', '1.14.13.-', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.35', '1.14.14.1', '2.4.1.-', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.9', '1.14.13.9', '3.2.1.14', '1.14.-.-', '3.4.15.6', '3.4.19.7', '1.3.98.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.15.5', '6.2.1.3', '1.14.13.91', '1.14.13.91', '3.2.1.143', '1.14.13.-', '1.14.13.-', '1.14.19.58', '1.14.14.8', '1.14.14.8', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.11.2.6', '1.11.2.6']
30
60
METOLAZONE
5

100%|██████████| 11047/11047 [00:03<00:00, 3636.40it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3779.21it/s]
 54%|█████▍    | 146/271 [32:10<27:58, 13.43s/it]

rxndb num 82
failedrxn num 0
result_df 25
['1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.8.1.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.2.1.35', '3.2.1.35', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '3.2.1.-', '3.2.1.-', '2.6.1.114']
7
16
METOPROLOL TARTRATE
5

100%|██████████| 11047/11047 [00:02<00:00, 3757.70it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3804.78it/s]
 54%|█████▍    | 147/271 [32:23<27:31, 13.32s/it]

rxndb num 927
failedrxn num 0
result_df 41
['3.1.3.69', '1.1.1.14;1.1.1.6', '1.1.1.1;1.1.1.10;1.1.1.156;1.1.1.2;1.1.1.21;1.1.1.72;1.3.1.20', '3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.27', '3.1.3.3', '3.1.3;3.1.3.2', '3.1.3.74', '1.5.3.13;1.5.3.17', '1.5.3.13', '1.5.3.13;1.5.3.17', '1.14.14.1', '1.14.14.1', '2.5.1.46', '3.1.3', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '1.5.3.14;1.5.99.6', '3.1.6.2', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.1.1;1.1.1.10', '1.14.18.1', '1.14.18.1', '3.1.3.2;3.1.3.29;3.1.3.38', '1.1.1.137', '1.1.1.137;1.1.1.405', '1.1.1.69', '3.1.3.22;3.1.3.23', '1.1.1;1.1.1.207', '3.1.3.39', '1.1.1.148', '1.14.14.1', '1.14.14.1', '1.1.3.16', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.1.1;1.1.1.208', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.147', '1.1.1.147', '1.1.1.101', '1.14.13.4', '1.14.13.4', '3.1.3.40', '1.1.1.143', '1.1.1.142', '3.1.6.9', '3.1.6.10', '1.1.1;1.1.1.-', '1.1.1.230', '1.-.-.-;1.1.1.342', '1.1.1.226', '3.1.3.14', '1.1.1.62', '1.1.1.62', '1.1.1.53', '1.1.1.50', '1.1.1.53', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.1.1.166', '1.14.13.-', '1.14.13.-', '1.1.1.2;1.1.1.21;1.1.1.261', '1.1.1.263', '1.1.1.270', '3.1.3.69', '1.1.1.274', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.297', '1.1.1;1.1.1.-', '1.1.1.364', '1.17.1.3', '1.17.1.3', '1.14.13.-', '1.17.1.3', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.1.1.270', '3.1.3.76', '1.14.13.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.1.1.-', '1.1.1;1.1.1.-;1.1.1.50', '1.-.-.-', '1.1.1.292', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.162', '1.1.1.-', '1.1.1.-', '1.1.1.-;1.1.1.341;4.2.1.-', '1.14.13.-', '1.14.13.-', '1.1.1.274;1.1.1.346', '1.1.1.-;1.1.1.329', '3.1.3.-;3.1.3.88', '1.1.1.297', '1.1.1.-', '1.1.1.239;1.1.1.62', '1.1.1.213', '1.1.1.209;1.1.1.213;1.1.1.357', '1.1.1.62', '3.1.3.79', '1.5.3.15;1.5.3.17', '1.5.1.-;1.5.1.43', '1.1.3.-;1.1.3.45', '1.1.1.297', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.1.1.301', '3.1.3.85', '1.14.-.-', '3.1.3.83', '1.1.1.-;1.1.1.329', '1.1.1.335', '1.1.1.340;1.14.13.-', '1.1.1.339;1.1.1.344', '1.1.1.355', '1.1.1.356', '1.1.1.356', '1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.361', '3.1.3.92', '1.1.1.364', '1.1.1.367', '1.11.2.5', '1.11.2.5', '1.5.1.48', '1.1.1.374', '1.1.1.385', '1.1.1.389', '1.14.13.209', '1.14.13.209', '1.1.1.393', '3.1.3.101', '3.1.3.-', '1.1.1.-', '1.1.1.-', '1.1.1.-', '3.1.3;3.1.3.-', '1.1.1.-', '1.1.1.402', '1.1.1.14;1.1.1.162;1.1.1.403', '1.14.-.-', '1.14.-.-', '2.1.1.-', '3.1.3.103', '1.1.1.251', '1.1.1.289', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.1.1.395', '1.1.1.-;1.1.1.395', '1.1.1.14;1.1.1.15', '1.1.1', '1.1.1.14', '1.1.3.11', '3.1.3.3', '3.1.3', '1.5.3.16', '1.5.3.14', '3.1.3.-', '1.1.1;1.1.1.-', '3.1.3;3.1.3.-', '1.1.1.201', '1.1.1.-;1.1.1.50;1.1.1.52', '1.1.1.391', '1.1.1.15', '1.1.1.-;1.1.1.270', '1.1.1;1.1.1.-;1.1.1.270', '1.1.1.-;1.1.1.270', '3.1.3;3.1.3.-', '1.1.1;1.1.1.-;1.1.1.12', '1.1.1', '1.1.1', '3.1.6;3.1.6.-', '1.1.1.102', '1.1.1.-;1.1.1.393', '1.1.1.145', '1.1.1;1.1.1.-', '1.14.14.133', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1', '1.1.1', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.1.1', '3.1.3.50', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.1.1.101', '1.14.13', '1.1.1', '1.1.1', '3.1.3', '3.1.6.c', '3.1.3.4', '1.1.1.201', '3.1.3.4', '1.1.1', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.1.1', '1.14.13', '1.1.1.M2', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.M11', '1.1.1.M11', '1.1.1.M11', '1.1.1.392', '1.1.1.393', '1.1.1.52', '1.1.1.391', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.52', '1.1.1.391', '1.1.1.392;1.1.1.50;1.1.1.52', '1.1.1.392', '1.1.1.393', '1.1.1.393', '3.1.3', '1.1.1.M28', '1.1.1.14;1.1.1.M29', '1.1.1', '1.5.3.14', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '3.1.3;3.1.3.-;3.1.3.104;3.1.3.2;3.1.3.29', '3.1.3', '3.1.3;3.1.3.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1.270', '1.1.1.270', '1.1.1.140', '1.1.1.123', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.2;1.1.1.213;1.1.1.239;1.1.1.62;1.3.1.20', '1.1.1.159', '1.1.1.218', '3.1.6.14', '1.1.1.218', '1.1.1.1', '1.1.1.188;1.1.1.213;1.1.1.50', '1.1.1.1', '3.1.3.29', '3.1.3.29', '1.14.15.15', '1.5.3.16', '1.1.1.149', '1.1.1.145', '1.1.1.1', '1.1.1.1', '1.1.1.1', '1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50;1.3.1.20', '1.1.1.140;1.1.1.17', '3.1.3.33;3.1.3.5', '1.1.1.133', '1.1.1.239;1.1.1.51', '1.1.1.239;1.1.1.51', '1.1.1.239', '1.1.1.184', '1.1.1;1.1.1.184;1.1.1.62', '1.1.1.184;1.1.1.2;1.1.1.62', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.213;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.50', '1.1.1.51', '1.14.13.126;1.14.15.16', '1.1.1;1.1.1.209', '1.1.1.292', '1.1.1', '1.1.1.209', '1.1.1.209', '1.1.1.209', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.1.1', '1.1.1.357;1.1.1.50', '1.1.1.210;1.1.1.357', '1.14.18.1', '1.14.18.1', '3.1.3', '3.1.3', '1.14.14.55', '3.2.1.78', '3.2.1.78', '1.1.1.184;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.50', '1.1.1.184;1.1.1.50', '1.1.1.12;1.1.1.14', '1.1.1.12;1.1.1.14', '1.1.1.12', '1.1.1;1.1.1.10;1.1.1.405', '1.1.1.10', '1.1.1;1.1.1.1', '3.1.3', '3.1.3', '1.1.1.146;1.1.1.159;1.1.1.50', '3.1.6.3', '1.1.99.13', '3.1.3.68', '1.1.1.162', '1.1.1.-', '1.14.15.4', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.1.1.133', '1.14.15.4', '1.14.15.6', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.296', '1.1.1.297', '1.14.13.36', '1.14.13.36', '3.2.1.154;3.2.1.26;3.2.1.80', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.55', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '1.1.1.-', '3.2.1.65', '3.2.1.145;3.2.1.23', '3.2.1.110', '1.1.1.125;1.1.1.127', '3.1.3.91', '3.6.1;3.6.1.-', '1.14.14.91', '1.14.14.91', '3.2.1.137;3.2.1.78', '1.1.1.104', '1.1.1.104', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '1.1.1.239;1.1.1.51', '1.1.1;1.1.1.239;1.1.1.62;1.1.1.64', '2.4.1.-', '1.1.1.104', '1.14.-.-', '1.14.-.-', '1.1.1.-;1.1.1.146', '1.1.1;1.1.1.-;1.1.1.146;1.1.1.51', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62;1.1.1.63', '1.1.1.184;1.1.1.2;1.1.1.213;1.1.1.51;1.1.1.64', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.2;1.1.1.209;1.1.1.21;1.1.1.213;1.1.1.50;1.3.1.20', '3.1.3.23;3.1.3.29;3.1.3.9', '1.1.1.124;1.1.1.138;1.1.1.14;1.1.1.67;1.1.99.11;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '3.1.3.27', '1.5.3.11;1.5.3.13;1.5.3.16;1.5.3.17', '1.5.3;1.5.3.13;1.5.3.16;1.5.3.17', '1.1.1.166;1.1.1.24;1.1.1.282', '1.1.1.14;1.1.1.56', '1.14.13.30', '1.14.14.1', '1.14.14.1', '3.1.3', '1.1.1.12;1.1.1.124;1.1.1.138;1.1.1.14;1.1.1.67;1.1.1.9;1.1.99.11;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.1.3.24', '1.1.1.58', '1.1.1.133', '3.1.3.12', '1.1.1.14;1.1.1.9', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '1.1.1.271', '1.1.1.124;1.1.1.138;1.1.1.21;1.1.1.287;1.1.1.67;1.1.99.11;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '1.1.1.124;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.1.3.29', '1.1.1;1.1.1.148;1.1.1.209', '3.1.3.-', '1.1.1.134;1.1.1.344', '1.1.1.159;1.1.1.50', '1.1.1.176', '1.1.1.206', '1.1.1.236', '1.1.1.16', '1.1.1.198', '1.1.1.227', '1.1.1.241', '1.1.1.174', '1.1.1.135;1.1.1.187', '1.1.1.187;1.1.1.281', '1.1.1.135;1.1.1.187', '1.1.1.187;1.1.1.281', '1.1.1.51', '1.1.1.51;1.1.1.62;1.1.1.64', '1.1.1.238', '1.14.13.74', '1.1.1.201', '1.1.1.146', '1.1.1.213;1.1.1.52', '3.1.3.63', '3.1.3.63', '1.1.1.152;1.1.1.184;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1.184;1.1.1.209;1.1.1.213;1.1.1.50', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.1.1.213;1.1.1.50', '1.1.1.50', '1.1.1.209;1.1.1.50', '1.1.1.213;1.1.1.50;1.1.1.51', '1.1.1.149;1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '2.-.-.-', '1.1.1.266', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.1.1.213;1.1.1.277;1.1.1.50', '1.14.13.79', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.1.1.282', '1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.278', '1.14.13.94', '1.14.13.96', '1.14.13.97', '3.1.3.21;3.1.3.25;3.1.3.29', '3.1.3.21;3.1.3.25', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.-.-', '1.14.-.-', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.147', '1.1.1.210;1.1.1.357;1.1.1.50;1.1.1.51', '1.14.13.-', '1.1.1.380', '1.1.1.1;1.1.1.391', '1.1.1.-;1.1.1.146;1.1.1.209;1.1.1.213;1.1.1.392;1.1.1.50', '3.1.3.73', '1.1.1;1.1.1.-', '3.1.3', '3.1.3', '1.1.1.159', '1.1.1.-', '1.1.1.270', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.1.1;1.1.1.10', '1.1.1.153', '1.1.1.10;1.1.1.14;1.1.1.15', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.213;1.1.1.50;1.1.1.51;1.1.1.53', '3.1.3.45', '1.1.1.-;1.1.1.M53', '1.14.13;1.14.13.-', '3.1.3', '3.1.3.68', '1.5.1.43', '1.1.1.414', '1.1.1.270', '1.1.1.270', '1.1.1.270', '1.1.1.201', '1.1.1', '3.1.3.M8', '1.1.1', '1.1.1.104', '1.1.1.322', '1.1.1.322', '1.1.1.266', '3.1.3.106;3.1.3.76', '1.1.1.367', '1.1.1.M48', '1.1.1.57', '1.1.1.406', '1.1.1.407', '1.1.1.64', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '1.14.13.9', '1.14.13.9', '1.5.1.43', '1.1.1;1.1.1.206', '1.1.1;1.1.1.206', '1.1.1', '1.1.1', '1.1.1', '1.14.14.70', '1.14.14.70', '1.1.1.14', '1.1.1', '1.1.1.10', '1.1.3.10', '1.1.3.10', '3.1.3.58;3.1.3.9', '3.1.6.3', '3.2.1.37', '3.2.1.37', '3.2.1.55', '3.2.1.55', '3.2.1.3;3.2.1.58;3.2.1.59', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.1.1.227', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.1.1.274', '1.1.1.297', '1.1.1.297', '1.14.-.-;1.14.13.-', '1.14.13.126', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.143', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.2.1.87', '3.2.1.1', '1.1.1.-', '1.7.3.-', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.-', '1.14.13.-', '1.14.13.-', '3.2.1.2', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.15.5', '1.1.1.-;1.1.1.270', '1.1.1.-;1.1.1.270', '1.14.13.79', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '3.2.1.137', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.96', '1.1.1.-', '3.1.3.27', '1.1.1.-', '1.1.1.-', '1.1.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.183', '1.14.13.184', '1.14.13.194', '3.1.3', '3.1.3.73', '3.2.1.143', '3.2.1.143', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.14.13.M64', '1.1.1.M51', '3.1.3.73', '1.1.1.M51', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.106', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '1.1.1.-;1.1.1.1;1.1.1.327', '1.1.1.270', '1.14.13.98', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.1.1.184;1.1.1.189', '3.1.3.82', '3.1.3.29;3.1.3.50', '3.1.3.50', '1.1.1.296', '1.1.1.296', '1.14.13.-', '1.14.13.-', '1.1.1;1.1.1.51;1.1.1.62', '1.14.13.-;1.14.15.6', '1.1.1.271', '1.1.1.271', '1.1;1.1.1;1.1.1.209;1.1.1.213', '1.1.1.1', '1.1.99.13', '3.1.3.58;3.1.3.9', '1.17.99.5', '1.1.1;1.1.1.184;1.1.1.210;1.1.1.50', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.2;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.3.1.20', '1.1.1.184;1.1.1.357', '1.14.13.97', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.1.5.3;1.1.99.5', '1.1.1.367', '1.1.1.-', '1.14.13.-', '1.14.13.-', '1.1.1.395', '1.1.1', '1.1.1.146', '1.1.1.64', '1.1.1.146', '1.1.1.146', '1.1.1.239', '1.1.1.239', '1.1.1.62', '1.1.1.270', '1.1.1.238', '1.11.2.6', '1.11.2.6', '1.1.1.206', '3.1.3.76', '3.1.3.76', '1.1.1.102', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '4.2.3;4.2.3.1', '1.1.1;1.1.1.69', '1.1.1.213;1.1.1.50', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '3.1.3.1;3.1.3.75', '1.1.1.261', '3.1.3.1;3.1.3.19;3.1.3.2;3.1.3.25;3.1.3.29', '1.1.1.8;1.1.1.94;1.1.5.3', '1.1.1.49;1.1.1.8;1.1.1.94;1.3.1.20', '3.1.3.2;3.1.3.21']
41
351
MEVASTATIN
5

100%|██████████| 11047/11047 [00:02<00:00, 3859.95it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3650.33it/s]
 55%|█████▍    | 148/271 [32:37<27:23, 13.36s/it]

rxndb num 2333
failedrxn num 0
result_df 198

100%|██████████| 11047/11047 [00:03<00:00, 2798.89it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3814.75it/s]
 55%|█████▍    | 149/271 [32:51<27:45, 13.65s/it]

rxndb num 157
failedrxn num 0
result_df 26
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190']
4
16
MIFEPRISTONE
5

100%|██████████| 11047/11047 [00:04<00:00, 2749.66it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4235.69it/s]
 55%|█████▌    | 150/271 [33:04<27:14, 13.51s/it]

rxndb num 2328
failedrxn num 0
result_df 151

100%|██████████| 11047/11047 [00:03<00:00, 3444.18it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4477.12it/s]
 56%|█████▌    | 151/271 [33:17<26:24, 13.20s/it]

rxndb num 167
failedrxn num 0
result_df 22
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.4.3.22;1.4.3.4', '1.4.3.10;1.4.3.21;1.4.3.22;1.4.3.6', '1.4.3.21;1.4.3.22;1.4.3.4;1.4.3.5;1.4.3.6;1.5.3.17', '1.14.13.59', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.4.3.13;1.4.3.21;1.4.3.22', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.187', '1.14.13.187', '1.14.13.195;1.14.13.196', '1.14.13.196', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.4.3.4', '1.4.3', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.4.3.M4', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.4.3.-;1.4.3.M3', '1.4.1.18', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.4.3.20', '1.14.13.11', '1.14.13.11', '1.14.13.11', '3.2.1.14', '3.4.15.6', '3.4.19.7', '3.2.1.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.M64', '1.14.13.149', '1.14.13', '1.1.1;1.1.1.206', '1.4.3.4']
15
48
MYCOPHENOLATE MOFETIL
5

100%|██████████| 11047/11047 [00:03<00:00, 3550.19it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3624.22it/s]
 56%|█████▌    | 152/271 [33:30<26:11, 13.21s/it]

rxndb num 798
failedrxn num 0
result_df 99
['1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.1.5', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1;1.14.14.25;1.14.14.55;1.14.14.57', '1.14.13.100', '1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.1.23', '3.1.6.1;3.1.6.2', '5.5.1.24', '3.1.1.22;3.1.1.75', '1.14.18.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.118;1.1.1.47', '1.1.1.119;1.1.1.47', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.63', '1.14.13.63', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.17.1.1', '1.17.1.1', '1.14.14.-;1.14.14.1', '3.1.1.70', '1.3.1.5', '1.3.1.5', '3.1.1.51', '3.1.1.60', '1.3.1.48', '1.3.1.48', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.14.13.22', '1.14.13.180', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.99.-', '1.14.13.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.3.1.-', '1.3.1.-', '1.14.13.-', '1.14.13.100;1.14.14.29', '1.14.13.-', '1.14.13.38', '1.14.14.-', '1.14.-.-', '1.14.13.-;1.14.13.161', '1.14.13;1.14.13.-', '1.11.2.5', '1.1.1.363;1.1.1.388', '1.1.1.390', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.217', '3.3.2.14', '2.1.1.-', '3.1.1.102', '1.14.13.-;1.14.13.M56', '1.3.1.114', '1.1.1.116', '1.3.1.34', '1.1.1.359;1.1.1.376;1.1.1.46', '1.3.3.6', '1.14.13', '6.3.2', '6.3.2', '3.1.1;3.1.1.1;3.1.1.3', '1.3.1', '1.3.1', '1.14.13;1.14.13.-', '1.3.1.93', '1.3.1.93', '1.14.14.133', '1.14.13;1.14.13.-', '3.1.1', '1.1.1', '1.1.1.415;1.1.1.ee', '1.14.13', '1.3.1', '1.3.1', '1.14.13', '3.1.1', '1.3.1.93', '1.3.1.93', '3.1.1.26', '1.14.14', '1.14.14', '3.1.1.4', '3.1.1.23', '3.1.1.23', '3.1.1.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.1', '1.3.1.93', '1.3.1.93', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1.114', '1.3.1', '1.3.1', '3.1.1', '1.1.1.-', '1.1.1', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '3.1.1.1;3.1.1.13;3.1.1.3', '3.1.1.1;3.1.1.3', '1.3.3.6', '3.1.1.3', '3.1.1.3', '1.14.14.1', '3.1.1.1', '1.3.1.48', '1.3.1.48', '1.3.1.48', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '1.14.15.15', '3.1.1.1;3.1.1.2', '3.1.1.1;3.1.1.2', '1.1.1.179;1.3.1.20', '1.1.1.179;1.3.1.20', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '3.1.6.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '3.4.21;3.4.21.62', '3.4.16.5;3.4.21;3.4.21.62', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.18.1', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '3.1.3.48', '3.1.3.2;3.1.3.48;3.1.3.76', '3.1.3.36;3.1.3.48', '1.1.1.121', '3.1.3.2', '1.1.1.47', '1.14.13.-', '1.14.13.-', '1.1.1.122', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.2.1.74', '1.14.13.-', '1.14.13.-', '3.4.11.5', '3.4.11.5', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.55', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.82', '3.2.1.15;3.2.1.82', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.145;3.2.1.23', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-;1.14.13.129', '3.2.1.35', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '2.3.1.-', '1.14.13.38', '1.14.13.234', '3.1.1', '1.14.14.91', '1.14.99.45', '3.2.1.137;3.2.1.78', '5.3.3.1', '5.3.3.1', '1.14.-.-', '1.3.1;1.3.1.-', '2.4.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-;1.14.13.129', '3.1.1.5', '3.1.1.5', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13;1.14.14.1', '1.14.13.30', '1.14.14.1', '5.5.1.24', '1.14.14.23', '1.14.13.17', '1.14.13.21;1.14.13.88', '1.14.13.16', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '3.1.1.10', '1.1.1.113', '1.14', '1.14.13.36', '1.14.13.56', '1.14.13.57', '1.3.1.104;1.3.1.38;1.3.1.8', '1.3.1.69', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.77', '1.14.13.76', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14.13.89', '1.3.1.104;1.3.1.38;1.3.1.44;1.3.1.8', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.13.-', '1.14.13.-', '1.14.13', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.-.-', '1.14.-.-', '1.14.13.240', '1.14.13.11', '1.14.13.103', '1.14.13.17', '1.14.-.-;1.14.13.-', '1.14.13.-;1.14.13.146', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1;1.3.1.44', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '2.3.1.-', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.89', '1.14.13.89', '1.14.19.41;1.3.1.-', '1.14.13.88', '1.14.13.88', '1.3.99.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.3.99.3', '1.1.1;1.3.99.3', '1.3.1.9', '1.1.1.363;1.1.1.388;1.1.1.47;1.1.1.49', '1.1.1.415', '1.3.1.-', '1.1.1', '1.17.3.M1', '1.14.13.M76', '1.14.13.M76', '1.3.1.42', '3.1.1.116', '1.1.1.376', '1.1.1.420', '1.14.13.9', '1.1.1.120', '3.2.1.14', '3.2.1.14', '1.1.1.121;1.1.1.175', '1.1.1.121', '1.1.1.179', '1.1.1.179', '3.2.1.37', '3.2.1.37', '1.1.1.46', '1.1.1.46', '3.2.1.55', '3.2.1.55', '3.2.1.3;3.2.1.58;3.2.1.59', '3.2.1.4', '3.2.1.4', '1.14.13.129', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.129', '1.1.1.121', '1.14.13.110', '1.14.-.-;1.14.13.-', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '1.14.13.99', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.4.19.7', '3.4.19.7', '3.2.1.1', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '3.2.1.2', '3.1.-.-', '3.1.-.-', '1.14.99.45', '1.14.13.-', '1.14.13.21', '1.3.1.-', '1.3.1.-', '1.3.3.-', '1.3.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.-.-.-', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.-', '1.14.13.72', '1.14.15.5', '1.14.13.129', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '3.2.1.15', '3.2.1.15', '4.2.2.2', '4.2.2.2', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '6.2.1.3', '6.2.1.3', '3.2.1.137', '1.1.1.117', '1.1.1.117', '1.1.1.117', '1.1.1.117', '1.14.13.103', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '3.1.1.5', '1.6.5.2', '1.6.5.2', '1.6.5.2', '1.6.5.2', '1.14.13.-', '1.14.13.-', '1.1.1.46', '1.1.1.46', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.194', '3.1.1.101', '3.1.1.101', '1.14.13', '1.3.1.114', '3.2.1.143', '3.2.1.143', '3.2.1.143', '3.2.1.143', '1.3.3.6', '1.14.13.100;1.14.13.17;1.14.13.60', '1.3.1.93', '1.14.13.99', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.3.3.6', '1.3.1.104;1.3.1.38;1.3.1.8', '3.1.1.1;3.1.1.84', '1.1.1.363;1.1.1.49', '1.3.99.-', '1.14.13.-', '1.14.13.116', '3.1.1.88', '1.14.13.122', '1.14.13.190', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13;1.14.14.1', '1.1.1.118', '1.1.1.120;1.1.1.179;1.1.1.359;1.1.1.360;1.1.1.47;1.1.1.48;1.3.1.20', '1.1.1.120', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.3.3.6;1.3.8.1;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.1.1.119', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.3.3.6', '1.3.3.6', '1.3.99.-', '1.1.1.121;1.1.1.359;1.1.1.47;1.1.1.48', '1.1.1.121', '1.14.14.12', '1.14.14.12', '1.3.1.10;1.3.1.38;1.3.1.8', '1.14.14.-', '1.14.14;1.14.14.-', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.1.1.363;1.1.1.47;1.1.1.49', '1.1.1.49', '2.6.1.114', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.11.2.6', '1.1.1.424', '3.1.1.3', '3.1.1.102', '1.14.13.3;1.14.14.9', '1.14.13.127']
46
237
NADOLOL
5

100%|██████████| 11047/11047 [00:02<00:00, 4562.83it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4134.22it/s]
 56%|█████▋    | 153/271 [33:42<25:02, 12.74s/it]

rxndb num 2366
failedrxn num 0
result_df 86

100%|██████████| 11047/11047 [00:03<00:00, 3051.44it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4340.57it/s]
 57%|█████▋    | 154/271 [33:55<25:01, 12.83s/it]

rxndb num 1016
failedrxn num 0
result_df 100
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.1.5', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.1.23', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '3.1.1.22;3.1.1.75', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.22', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.1.70', '3.1.1.51', '1.14.13.22', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.-.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.-.-', '1.14.13.-', '1.14.19.n5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '6.3.2', '6.3.2', '3.1.1;3.1.1.1;3.1.1.3', '1.3.1', '1.14.13;1.14.13.-', '1.14.14.133', '1.14.14.133', '1.14.14.133', '3.1.1', '1.3.1', '1.3.1', '3.1.1', '3.1.1.26', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.1.4', '3.1.1.23', '3.1.1.23', '3.1.1.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.1', '1.1.1.-', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.3.1', '3.1.1.1;3.1.1.13;3.1.1.3', '3.1.1.1;3.1.1.3', '3.1.1.3', '3.1.1.3', '3.1.1.1', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '1.14.15.15', '3.1.1.1;3.1.1.2', '3.1.1.1;3.1.1.2', '3.1.1.1;3.1.1.2', '1.1.1.179;1.3.1.20', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.22', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.3;1.3.1.120', '3.4.21;3.4.21.62', '3.4.16.5;3.4.21;3.4.21.62', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.1.1.47', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.2.1.74', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '6.3.2.17', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '2.3.1.-', '3.1.1', '1.14.-.-', '1.3.1;1.3.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.1.5', '3.1.1.5', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.15.3', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.16', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '3.1.1.10', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.-.-', '1.14.-.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.-.-;1.14.13.-', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.3.1.-', '1.14.19.41;1.3.1.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.-.-', '1.14.13.M76', '1.14.13.M76', '3.1.1.116', '1.1.1.420', '1.3.1.120', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-', '1.14.-.-;1.14.13.-', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '3.2.1.87', '3.2.1.87', '3.4.15.6', '3.4.19.9', '3.4.19.7', '1.14.-.-', '1.14.13.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.2.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '3.1.-.-', '3.1.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.15.5', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '3.1.1.5', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.156', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.194', '3.1.1.101', '1.14.13', '3.2.1.143', '3.2.1.143', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.3.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '3.1.1.3', '1.14.13.-', '1.14.-.-;1.14.13.-;1.14.13.cs']
37
124
NAFTOPIDIL
5

100%|██████████| 11047/11047 [00:03<00:00, 3397.63it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3407.09it/s]
 57%|█████▋    | 155/271 [34:09<25:41, 13.29s/it]

rxndb num 1566
failedrxn num 0
result_df 125

100%|██████████| 11047/11047 [00:04<00:00, 2451.60it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4010.41it/s]
 58%|█████▊    | 156/271 [34:23<25:55, 13.53s/it]

rxndb num 1580
failedrxn num 0
result_df 78

100%|██████████| 11047/11047 [00:03<00:00, 3006.06it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4289.46it/s]
 58%|█████▊    | 157/271 [34:36<25:13, 13.28s/it]

rxndb num 1113
failedrxn num 0
result_df 108
['1.2.1.-;1.2.1.21;1.2.1.22;1.2.1.3', '1.2.1.23;1.2.1.3', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.15', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.2.1.5', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '3.6.1.7', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.6', '1.14.13.6', '1.14.13.6', '1.14.13.6', '1.14.13.6', '1.14.13.6', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.2.1.33', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.2.1.40', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.1.1.173;1.1.1.378', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.219;1.14.13.7', '1.14.13.219;1.14.13.7', '1.14.13.219;1.14.13.7', '1.14.13.219;1.14.13.7', '1.14.13.219;1.14.13.7', '1.14.13.219;1.14.13.7', '1.14.13.-;1.14.13.20;1.14.13.7', '1.14.13.-;1.14.13.20;1.14.13.7', '1.14.13.-;1.14.13.20;1.14.13.7', '1.14.13.-;1.14.13.20;1.14.13.7', '1.14.13.-;1.14.13.20;1.14.13.7', '1.14.13.-;1.14.13.20;1.14.13.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.2.1.74', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '4.1.1', '1.14.13.-;1.6.5.2', '1.14.13.-;1.6.5.2', '1.14.13.-;1.6.5.2', '1.14.13.-;1.6.5.2', '1.14.13.-;1.6.5.2', '1.14.13.-;1.6.5.2', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.12.-', '1.14.12.-', '1.14.12.-', '1.14.12.-', '1.14.12.-', '1.14.12.-', '1.14.12.-', '1.14.12.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.-.-', '1.14.13.244;1.14.13.M20', '1.14.13.244;1.14.13.M20', '1.14.13.244;1.14.13.M20', '1.14.13.244;1.14.13.M20', '1.14.13.244;1.14.13.M20', '1.14.13.244;1.14.13.M20', '1.2.1.-;1.2.1.83', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.1.1.203', '1.1.1.203', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.3.2.14', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.220', '1.2.1.98', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13', '1.1.1.203', '1.2.1;1.2.1.-', '1.14.13;1.14.13.-', '1.2.1;1.2.1.-', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.1.1.-;1.1.1.377;1.1.1.378', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M33', '1.14.13.M33', '1.14.13.M33', '1.14.13.M33', '1.14.13.M33', '1.14.13.M33', '1.14.13;1.14.13.-', '1.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.11;1.11.2.1', '1.11;1.11.2.1', '1.11;1.11.2.1', '1.11;1.11.2.1', '1.11;1.11.2.1', '1.11;1.11.2.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.1', '1.14.14.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.2.1.3', '3.8.1.6', '3.8.1.6', '3.8.1.6', '3.8.1.6', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.12.9', '1.14.12.9', '1.14.12.9', '1.14.12.9', '1.14.12.9', '1.14.12.9', '1.14.12.9', '1.14.12.9', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.2.3.1', '1.14.13.72', '1.2.1.74', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.82', '3.5.1.41;3.5.1.89', '1.14.-.-', '1.14.-.-', '3.2.1.76', '3.2.1.31', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.-.-', '2.4.1.-', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.12', '1.14.13.12', '1.14.13.12', '1.14.13.12', '1.14.13.12', '1.14.13.12', '1.14.13.11;1.14.14.91', '1.14.13.11;1.14.14.91', '1.14.13.11;1.14.14.91', '1.14.13.11;1.14.14.91', '1.14.13.11;1.14.14.91', '1.14.13.11;1.14.14.91', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.2.1.3', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.72', '1.14.13.78', '1.14.13.79', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.-.-', '1.14.-.-', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.1.1.107;1.1.1.122', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.2.1.19;1.2.1.5', '1.2.1.19;1.2.1.3;1.2.1.39;1.2.1.5', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.2.1.101;1.2.1.ah', '1.2.1.-', '1.14.-.-', '1.14.-.-', '1.14.13.144', '3.2.1.87', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.2.1.-', '1.14.11.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.15.5', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '3.2.1.15', '4.2.2.2', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.2.1.5', '1.2.1.5', '1.2.1.5', '1.2.1.5', '1.2.1.5', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.194', '3.1.1.101', '1.14.13.236', '1.14.13.236', '1.14.13.236', '1.14.13.236', '1.14.13.236', '1.14.13.236', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.13.15', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.20', '1.14.14.20', '1.14.14.20', '1.14.14.20', '1.14.14.20', '1.14.14.20', '1.2.1.3;1.2.1.40', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.27', '1.14.14.27', '1.14.14.27', '1.14.14.27', '1.14.14.27', '1.14.14.27', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.2.1', '1.2.1', '1.2.1.3', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.2.1.29;1.2.1.3;1.2.1.5', '1.2.1.5', '1.2.1.3;1.2.1.5', '1.2.1.5', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.2.1.5', '1.2.1.3;1.2.1.5', '1.2.1.5', '1.2.1.29;1.2.1.5;1.2.1.53', '1.2.1.5', '1.2.1.3;1.2.1.5', '1.2.1.5']
29
116
NATEGLINIDE
5

100%|██████████| 11047/11047 [00:02<00:00, 4062.85it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3120.20it/s]
 58%|█████▊    | 158/271 [34:50<25:36, 13.60s/it]

rxndb num 950
failedrxn num 0
result_df 80
['6.3.2.2', '1.2.1.3;1.2.1.54', '1.2.1.-;1.2.1.99', '3.5.1.94', '2.3.2.-', '3.4.11.1', '6.3.2.3', '1.1.1.23', '1.14.13.9', '1.14.13.9', '1.14.13.9', '6.3.2.28;6.3.2.49', '3.4.13.18', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.4.14.6', '1.2.1.3', '1.2.1.20;1.2.1.88', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.15', '1.14.15.6', '6.3.2.1', '4.1.1.30', '3.5.1.92', '4.1.1.36', '6.3.2;6.3.2.5;6.3.2.51', '1.2.1.24;1.2.1.5;1.2.1.88;1.5.1.12', '1.5.1.12', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.5.1.18', '3.5.1.96', '1.2.1.16;1.2.1.24;1.2.1.26;1.2.1.3;1.2.1.79;1.2.1.88', '1.1.1.21;1.2.1.16;1.2.1.26;1.2.1.79', '1.2.1.3;1.2.1.47', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '6.3.2.13', '6.3.2.11', '1.14.18.1', '1.14.18.1', '1.14.18.1', '6.3.2.24', '6.3.2.11', '3.4.13.4', '6.3.2.11', '6.3.2.11', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.5.1.22', '6.3.2.23', '6.3.1.2;6.3.1.6', '3.5.1.65', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '6.3.2.20', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.2.1.40', '3.5.1.24;3.5.1.74', '3.5.1.24', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.2.1.4;1.2.1.63', '1.14.13.72', '1.2.1.74', '1.2.1.-;1.2.1.99', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.5.1;1.5.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.3.2.36', '1.14.-.-', '1.2.-.-', '1.2.-.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '6.3.2.35', '1.14.-.-', '1.2.1.-;1.2.1.M5', '6.3.2.38', '1.2.1.-;1.2.1.83', '6.3.1.17', '6.3.2.41;6.3.2.42', '3.4.17.21', '3.4.17.21', '6.3.2.42', '1.11.2.5', '1.11.2.5', '1.11.2.5', '3.5.1.-', '6.3.2.44', '6.3.4.24', '6.3.2.47', '6.3.2.47', '6.3.2.47', '6.3.2.47', '1.2.1;1.2.1.-;1.2.1.20', '3.5.1.118', '1.14.13.209', '1.14.13.209', '1.14.13.209', '6.3.2.49', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '6.3.2.18', '3.5.1.97', '3.5.1.97', '3.5.1.97', '6.3;6.3.-.-', '6.3;6.3.-.-', '6.3;6.3.-.-', '6.3;6.3.-.-', '6.3;6.3.-.-', '6.3;6.3.-.-', '6.3.-.-;6.3.2.52;6.3.2.M5', '6.3.-.-;6.3.2.52', '6.3.-.-;6.3.2.52', '6.3.-.-;6.3.2.52', '6.3.-.-;6.3.2.52', '6.3.-.-;6.3.2.52', '6.3.2;6.3.2.-', '6.3.2', '6.3.2', '6.3.2', '3.4.13.23', '3.4.11.25', '1.14.13;1.14.13.-', '1.3.1', '1.3.1', '1.2.1;1.2.1.-', '6.3.2.59', '6.3.2.59', '6.3.2.29', '3.4.11.2;3.4.13.23', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.14.14', '1.14.14', '1.14.14', '1.2.1', '6.3.2', '3.4.13', '6.3.2', '3.4.16', '3.4.11.7', '3.4.16', '3.4.11.7', '3.4.16;3.4.16.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '6.3.2.47', '1.2.1', '1.2.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '4.1.1.M3', '4.1.1.M3', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '1.2.1', '6.3;6.3.-.-', '6.3;6.3.-.-', '6.3;6.3.-.-', '6.3.2', '1.14.13;1.14.13.-', '3.4', '3.5.1;3.5.1.-', '3.5.1;3.5.1.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.2.1.3;1.2.1.8', '1.2.1;1.2.1.-', '3.4.13.18', '3.4.13.18', '3.4.13.18', '3.4.11.1;3.4.11.2;3.4.13.18;3.4.13.19', '3.4.13.18', '3.4.13.18', '3.4.13.18', '3.4.13.18', '3.4.13.18', '3.4.13.18', '3.5.1.115', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.5.1.23', '3.5.1.23', '3.5.1.23', '1.2.1.47', '3.5.1.23', '3.5.1.23', '3.5.1.23', '1.14.15.15', '1.2.1.19', '1.2.1.88', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.2.1.19;1.2.1.3', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.3;1.3.1.120', '1.2.1.26;1.2.1.4', '3.4.19.5', '3.5.1.23', '1.2.1.3;1.2.1.5', '6.3.1.2', '3.5.1.23', '1.14.13', '1.14.13', '1.14.13', '1.2.1.48;1.2.1.5', '1.2.1.48;1.2.1.5', '1.2.1.48', '1.2.1.26;1.2.1.3;1.2.1.48;1.2.1.5', '1.2.1.48', '1.2.1.48;1.2.1.5', '1.2.1.3', '6.3.4.2', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '6.3.2.2', '6.3.2.2', '3.4.13', '1.2.1.5', '1.2.1.5', '1.2.1.5', '1.2.1.3;1.2.1.5', '1.2.1.3;1.2.1.5', '3.5.1', '6.3.2.11', '6.3.2.11', '6.3.2.18', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.2.3.1', '1.14.13.72', '1.2.1.74', '1.2.1.74', '3.4.11.5', '3.4.11.5', '1.1.1.23;1.1.1.24', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '6.3.2.17', '6.3.2.17', '1.5.1.12;1.5.99.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '6.3.2.11', '6.3.2.11', '1.14.-.-', '1.3.1;1.3.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.3.1.11', '3.5.1.-;3.5.1.78', '6.3.1.8;6.3.1.9', '3.4.13.18;3.4.13.20;3.4.13.5', '1.14.13.15;1.14.15.15', '1.14.13.15;1.14.15.15', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.15.3', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.12.19', '1.14.12.19', '1.14.12.19', '3.5.1.4;3.5.1.99', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '6.3.2.7', '6.3.2.9', '6.3.2.11', '1.1.1.23', '1.14.13.46', '1.14.13.46', '6.3.2.13', '3.5.1.24;3.5.1.74', '1.2.1.31', '6.3.1.9', '3.4.13.4', '3.5.1.24', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.2.1.3', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.72', '1.14.13.91', '1.14.13.91', '1.14.13.91', '3.5.1.24', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.78', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.-.-', '1.14.-.-', '3.5.1.-', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '6.3.2.32', '1.14.-.-;1.14.13.-', '6.3.1.13', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.2.1.31', '1.3.1.-;1.3.1.72;1.3.1.M20', '1.3.1.-;1.3.1.71', '1.14.19.41;1.3.1.-', '6.3.2.8', '3.4.13.20;3.4.13.5', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.-.-', '1.2.1.95;1.2.1.z', '1.2.1.31', '6.3.1.10', '6.3.1.10', '3.5.1.90', '3.5.1.90', '1.2.1.3', '1.2.1;1.2.1.-;1.2.1.19;1.2.1.3;1.2.1.5', '6.3.2.56;6.3.2.ad', '6.3.2.-', '1.14.14.22;1.14.99.46', '6.3.2.52', '3.4.19.13', '3.4.17.b', '3.4.13.23', '6.3.2.2', '1.2.1.3', '3.5.1.68', '3.5.1.68', '3.5.1.60;3.5.1.99', '3.5.1.60', '3.5.1.60;3.5.1.99', '6.3.2.47', '3.5.1.99', '3.5.1.99', '3.4.17.13', '3.5.1.127', '3.5.1.127', '6.3.-.-', '1.2.1.101;1.2.1.ah', '6.3.2.53;6.3.2.aa', '6.3.2.11', '3.4.13.4', '3.4.13.4', '3.4.13.4', '3.4.13.4', '3.5.1.133;3.5.1.ah', '3.5.1.134', '1.2.1.-', '1.3.1.120', '3.4.13.23', '3.4.13.23', '3.5.1.60', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.4', '3.2.1.14', '3.2.1.14', '3.4.13.4', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-', '1.14.-.-;1.14.13.-', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '1.14.13.144', '3.4.15.6', '3.4.15.6', '3.4.19.9', '3.4.19.9', '3.4.19.5', '3.4.19.5', '3.4.19.7', '3.4.19.7', '1.2.1.5', '6.3.2.11', '1.14.13.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.2.1.-', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.2.-.-', '1.2.-.-', '1.2.1.-', '6.3.2.-', '1.14.99.-', '1.2.1.3', '1.14.11.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.15.5', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.2.1.70;6.1.1.17', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.2.1.5', '1.2.1.5', '1.2.1.5', '1.2.1.5', '1.2.1.5', '1.2.1.5', '1.2.1.5', '1.2.1.5', '1.2.1.5', '1.2.1.5', '1.2.1.5', '6.3.2.17', '6.3.2.17', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.159', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.194', '6.3.2;6.3.2.-', '3.1.1.101', '3.1.1.101', '3.4.13.23;3.4.13.a', '6.3.2', '3.4.13.23', '3.4.16.4', '3.4.13.23', '6.3.2', '6.3.2', '3.4.17.b', '3.4.13.23', '3.4.17.b', '3.4.13.23', '3.5.1', '3.4.13.23', '3.5.1', '3.4.17.b', '3.4.13.23', '3.4.16.4', '3.4.13.23', '6.3.2.49', '3.4.13.23', '6.3.2', '3.4.13.23', '3.4.13.23', '6.3.2', '6.3.2.33', '6.3.2.37', '6.3.2.37', '6.3.2.39', '1.14.13.15', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '6.3.1.10', '3.4.11.19;3.4.13;3.4.13.22;3.4.17.14', '6.3.2.4', '1.14.13.15', '1.3.99.-', '3.5.1.24', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.2.1.3;1.2.1.40', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '6.3.2.58', '6.3.2.58', '6.3.2.57', '6.3.2.57', '6.3.2.32', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.5.1', '5.2.1.M1', '3.5.1.115', '1.2.1', '1.2.1', '3.4.13.18', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1;1.1.1.206', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.2.1;1.2.1.19;1.2.1.3', '1.2.1;1.2.1.88;1.5.1.12;1.5.99.8', '3.4.13.18;3.4.13.20;3.4.13.3;3.4.13.5', '1.2.1;1.2.1.-;1.2.1.19;1.2.1.3', '3.5.1.46', '1.2.1.3;1.2.1.48;1.2.1.5', '1.2.1.19', '1.2.1.3;1.2.1.48;1.2.1.5', '1.2.1.48;1.2.1.5', '1.2.1.48', '1.2.1.3;1.2.1.48;1.2.1.5', '1.2.1.48', '1.2.1.3;1.2.1.5', '1.2.1.5', '1.2.1.3;1.2.1.36;1.2.1.48;1.2.1.5', '1.2.1.3;1.2.1.5', '1.2.1.3;1.2.1.48;1.2.1.5', '1.2.1.3;1.2.1.5', '3.4.11;3.4.11.1;3.4.11.2;3.4.11.23;3.4.13;3.4.13.-;3.4.13.18', '1.14.13.159', '1.14.13.-', '1.14.-.-;1.14.13.-;1.14.13.cs']
48
244
NEFAZODONE
5

100%|██████████| 11047/11047 [00:02<00:00, 3912.96it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4153.09it/s]
 59%|█████▊    | 159/271 [35:03<24:45, 13.27s/it]

rxndb num 247
failedrxn num 0
result_df 38
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.8.1.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.8', '3.8.1.8', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.35', '1.14.14.1', '2.4.1.-', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.87', '3.4.15.6', '1.3.98.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.-.-.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13', '3.2.1.143', '1.14.19.58', '3.6.1.18;3.6.1.9']
20
47
NEFOPAM
5

100%|██████████| 11047/11047 [00:03<00:00, 2804.55it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4401.33it/s]
 59%|█████▉    | 160/271 [35:15<24:20, 13.16s/it]

rxndb num 257
failedrxn num 0
result_df 23
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.8', '1.14.13.8', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.143', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9']
8
30
NEOSTIGMINE BROMIDE
5

100%|██████████| 11047/11047 [00:02<00:00, 4030.86it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3308.24it/s]
 59%|█████▉    | 161/271 [35:29<24:34, 13.40s/it]

rxndb num 293
failedrxn num 0
result_df 28
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.1.1', '3.1.1.1', '1.14.13.8', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.1;3.1.1.1;3.1.1.14;3.1.1.2;3.1.1.7;3.1.1.74;3.1.1.88;3.1.2.12;3.1.2.2', '3.1.1;3.1.1.1;3.1.1.2', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.8', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.1;3.1.1.1;3.1.1.2;3.1.1.74;3.1.1.88;3.1.2.12', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.35', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.2.1.3', '3.2.1.143', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127']
21
67
NEVIRAPINE
5

100%|██████████| 11047/11047 [00:02<00:00, 3692.79it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4226.25it/s]
 60%|█████▉    | 162/271 [35:42<23:37, 13.01s/it]

rxndb num 112
failedrxn num 0
result_df 18
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.61', '1.14.13.61', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.224', '1.14.13.224', '1.14.13.224', '1.14.13.224', '1.2.3.1', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '1.14.14.55', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.10', '1.14.13.10', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.2.3.1', '1.2.3.1', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.176', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '2.6.1.114', '1.14.14', '1.14.14', '1.14.14']
7
33
NICERGOLINE
5

100%|██████████| 11047/11047 [00:05<00:00, 2013.33it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3823.43it/s]
 60%|██████    | 163/271 [35:57<24:53, 13.83s/it]

rxndb num 449
failedrxn num 0
result_df 60
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.1.5', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.1.60', '1.14.13.180', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.13.-', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.224', '1.14.13.224', '1.14.13.224', '1.14.13.224', '1.14.13.224', '1.14.13.224', '1.3.1', '1.14.14.133', '3.1.1', '1.1.1.415;1.1.1.ee', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.235', '1.14.13.235', '1.14.13.235', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.8', '1.14.13.8', '1.2.3.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '1.14.14.55', '3.2.1.78', '3.2.1.78', '1.14.15.4', '1.14.15.4', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.13.-', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '1.14.-.-', '1.14.-.-', '3.1.1.5', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '2.-.-.-', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.79', '1.14.13.79', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.14.149', '1.14.14.149', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1.415', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '3.2.1.87', '3.2.1.87', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.13.99.3', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.156', '1.14.13.176', '1.14.13.176', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13', '3.2.1.143', '3.2.1.143', '1.14.13.98', '1.14.13.98', '3.1.1.1;3.1.1.84', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.182', '1.14.13.182', '1.13.99.3', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.13.11.11;1.13.11.52']
28
92
NITRENDIPINE
5

100%|██████████| 11047/11047 [00:02<00:00, 3980.73it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3159.48it/s]
 61%|██████    | 164/271 [36:12<25:10, 14.12s/it]

rxndb num 259
failedrxn num 0
result_df 53
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '3.1.1.70', '3.1.1.70', '1.7.1.9', '1.7.1.9', '1.7.1.-;1.7.1.16', '3.1.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.12.23', '1.14.12.23', '1.-.-.-;1.7.1', '1.7.1.-', '1.-.-.-', '1.12.99.6;1.2.7.1;1.2.7.4;1.2.99.2', '1.-.-.-', '1.7.1.-', '1.7.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.14.12.-;1.14.12.24', '1.14.12.-;1.14.12.24', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '3.1.1.95', '1.1.1.363;1.1.1.388', '1.1.1.363;1.1.1.388', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.1', '3.1.1', '3.1.1', '3.1.1', '3.1.1.4', '3.1.1.4', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.24', '1.14.12.24', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.13.M9', '1.1.1.-', '1.1.1.-', '1.14.12.23', '1.14.12.23', '1.7.1.16', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.7.1', '1.7.1.16', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.4.21;3.4.21.104;3.4.21.42', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '3.4.21;3.4.21.62', '3.4.21;3.4.21.62', '3.4.16.5;3.4.21;3.4.21.62', '3.4.16.5;3.4.21;3.4.21.62', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.25', '1.14.13.25', '1.14.13.25', '1.14.13.25', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.18', '1.14.-.-', '1.14.-.-', '3.2.1.35', '3.2.1.35', '3.2.1.35', '2.3.1.-', '2.3.1.-', '3.1.1', '3.1.1', '3.1.1.10', '3.1.1.10', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '2.-.-.-', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '2.3.1.-', '2.3.1.-', '1.1.1.363;1.1.1.388;1.1.1.47;1.1.1.49', '1.1.1.363;1.1.1.388;1.1.1.47;1.1.1.49', '1.14.14.22;1.14.99.46', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.2.1.14', '3.2.1.-', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.-.-', '3.1.-.-', '3.1.-.-', '3.1.-.-', '6.2.1.3', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '3.1.1.5', '3.1.1.5', '1.7.1.-', '1.7.1.-', '3.2.1.143', '3.2.1.143', '1.1.1.363;1.1.1.49', '1.1.1.363;1.1.1.49', '1.14.13.122', '1.14.13.122', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.1.1.363;1.1.1.47;1.1.1.49', '1.1.1.363;1.1.1.47;1.1.1.49', '1.1.1.49', '1.1.1.49', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.7.1.M3']
26
74
NIZATIDINE
5

100%|██████████| 11047/11047 [00:02<00:00, 3925.77it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4458.37it/s]
 61%|██████    | 165/271 [36:23<23:26, 13.27s/it]

rxndb num 71
failedrxn num 0
result_df 14
['2.1.1.49', '2.1.1.49', '2.1.1.49', '2.1.1.49', '2.1.1.115;2.1.1.140', '2.1.1.115;2.1.1.140', '2.1.1.115;2.1.1.140', '2.1.1.115;2.1.1.140', '2.1.1.115', '2.1.1.115', '2.1.1.115', '2.1.1.115', '2.1.1;2.1.1.115', '2.1.1;2.1.1.115', '2.1.1;2.1.1.115', '2.1.1;2.1.1.115', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '2.1.1.115', '2.1.1.115', '2.1.1.115', '2.1.1.115', '2.1.1.324', '2.1.1.324', '2.1.1.324', '2.1.1.324', '2.1.1.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '2.1.1.-;2.1.1.340', '2.1.1.-;2.1.1.340', '2.1.1.-;2.1.1.340', '2.1.1.-;2.1.1.340', '2.1.1', '2.1.1', '2.1.1', '2.1.1', '1.14.13.8', '3.4.11.5', '1.14.14.1', '2.1.1.115', '2.1.1.115', '2.1.1.115', '2.1.1.115', '2.1.1;2.1.1.-', '2.1.1;2.1.1.-', '2.1.1;2.1.1.-', '2.1.1;2.1.1.-', '2.1.1.49', '2.1.1.49', '2.1.1.49', '2.1.1.49', '1.14.14.22;1.14.99.46', '2.1.1.337', '2.1.1.337', '2.1.1.337', '2.1.1.337', '2.1.1.345', '2.1.1.345', '2.1.1.345', '2.1.1.345', '2.1.1.49', '2.1.1.49', '2.1.1.49', '2.1.1.49', '2.1.1.103', '2.1.1.103', '2.1.1.103', '2.1.1.103', '1.-.-.-']
6
17
NORETHINDRONE ACETATE
5

100%|██████████| 11047/11047 [00:04<00:00, 2701.88it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3580.67it/s]
 61%|██████▏   | 166/271 [36:38<23:55, 13.67s/it]

rxndb num 2232
failedrxn num 0
result_df 175

100%|██████████| 11047/11047 [00:03<00:00, 2957.33it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4030.18it/s]
 62%|██████▏   | 167/271 [36:51<23:32, 13.58s/it]

rxndb num 1744
failedrxn num 0
result_df 154

100%|██████████| 11047/11047 [00:04<00:00, 2308.97it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4324.78it/s]
 62%|██████▏   | 168/271 [37:05<23:29, 13.68s/it]

rxndb num 385
failedrxn num 0
result_df 64
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '3.1.1.60', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.3.2.14', '3.3.2.14', '3.3.2.14', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13', '1.14.13', '1.14.13', '1.1.1.415;1.1.1.ee', '1.14.13', '1.14.13', '1.14.13', '3.2.1.40', '3.2.1.40', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.2.1.21;3.2.1.23', '3.2.1.21;3.2.1.23', '3.2.1.22', '3.2.1.22', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.1.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '3.2.1.161;3.2.1.188;3.2.1.21;3.2.1.23;3.2.1.25;3.2.1.3;3.2.1.37;3.2.1.45;3.2.1.58;3.2.1.74', '3.2.1.161;3.2.1.188;3.2.1.21;3.2.1.23;3.2.1.25;3.2.1.3;3.2.1.37;3.2.1.45;3.2.1.58;3.2.1.74', '3.2.1.3', '3.2.1.3', '3.2.1;3.2.1.10;3.2.1.177;3.2.1.199;3.2.1.20;3.2.1.21;3.2.1.70', '3.2.1;3.2.1.10;3.2.1.177;3.2.1.199;3.2.1.20;3.2.1.21;3.2.1.70', '3.2.1.51', '3.2.1.51', '3.2.1.21;3.2.1.22;3.2.1.23', '3.2.1.21;3.2.1.22;3.2.1.23', '3.2.1.22;3.2.1.23;3.2.1.85', '3.2.1.22;3.2.1.23;3.2.1.85', '3.2.1.55', '3.2.1.55', '3.2.1.23', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.-', '1.14.13.-', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.82', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.21.8', '1.14.21.8', '3.2.1.76', '3.2.1.35', '1.14.14.91', '1.14.14.91', '1.14.14.91', '2.4.1.-', '2.4.1.-', '2.4.1.-', '2.4.1.-', '2.4.1.-', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.21.2', '1.14.21.2', '1.14.19.68;1.14.21.5', '1.14.19.68;1.14.21.5', '1.14.21.1', '1.14.21.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '3.2.1.20;3.2.1.22', '3.2.1.20;3.2.1.22', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.1.1.415', '3.2.1.14', '3.2.1.126', '3.2.1.126', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.2.1.87', '1.14.21.8', '1.14.21.8', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.15', '4.2.2.2', '6.2.1.3', '6.2.1.3', '6.2.1.3', '6.2.1.3', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13', '3.2.1.143', '3.2.1.143', '3.2.1.143', '3.2.1.143', '3.2.1.143', '3.2.1.143', '3.1.1.1;3.1.1.84', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.126', '3.2.1.126', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-']
25
92
OLANZAPINE
5

100%|██████████| 11047/11047 [00:03<00:00, 3255.39it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3716.59it/s]
 62%|██████▏   | 169/271 [37:19<23:15, 13.69s/it]

rxndb num 112
failedrxn num 0
result_df 20
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.8', '1.1.1.2', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.6.1.114']
6
20
OLMESARTAN MEDOXOMIL
5

100%|██████████| 11047/11047 [00:02<00:00, 3764.51it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4026.66it/s]
 63%|██████▎   | 170/271 [37:32<22:28, 13.35s/it]

rxndb num 719
failedrxn num 0
result_df 47
['3.1.3.74', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.27', '3.1.3.74', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.73', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '3.1.3.39', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.6.9', '3.1.6.10', '3.1.1.60', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.-;3.1.3.88', '3.1.3.79', '3.1.3.85', '1.14.-.-', '1.14.-.-', '3.1.3.83', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '3.1.3', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1.415;1.1.1.ee', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.4', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.6.14', '3.1.3.29', '1.14.15.15', '1.14.15.15', '3.1.3.33;3.1.3.5', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3.68', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '3.1.3.91', '3.6.1;3.6.1.-', '1.14.-.-', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '1.14.-.-', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.1.3.27', '1.14.13.30', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.24', '3.1.3.12', '3.1.3.29', '3.1.3.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.74', '1.14.13.74', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1.415', '3.1.3.M8', '3.1.3.106;3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '3.2.1.14', '3.2.1.14', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.2.1.1', '1.7.3.-', '1.7.3.-', '1.7.3.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.2', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.174', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.15.5', '1.14.15.5', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '3.1.3.27', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.194', '1.14.13.194', '1.14.13', '3.1.3', '3.1.3.73', '3.2.1.143', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.106', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.2.1.23', '1.14.13.98', '1.14.13.98', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '3.1.1.1;3.1.1.84', '3.1.3.82', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '2.6.1.114', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75']
27
153
OMEPRAZOLE
5

100%|██████████| 11047/11047 [00:04<00:00, 2693.00it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4404.08it/s]
 63%|██████▎   | 171/271 [37:45<22:04, 13.24s/it]

rxndb num 172
failedrxn num 0
result_df 33
['1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '2.1.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.99.50;1.14.99.51', '1.14.99.51', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.3.2.14', '3.3.2.14', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '1.14.13.224', '1.14.13.224', '1.14.13', '1.14.13', '1.14.13', '1.14.13.235', '1.14.13', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.2.1.35', '2.4.1.-', '2.4.1.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.176', '1.14.13.176', '1.14.13.176', '3.2.1.143', '3.2.1.143', '1.14.13.32', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '2.6.1.114', '2.6.1.114', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9']
14
45
ORPHENADRINE CITRATE
5

100%|██████████| 11047/11047 [00:02<00:00, 4121.02it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3616.61it/s]
 63%|██████▎   | 172/271 [37:58<21:43, 13.17s/it]

rxndb num 329
failedrxn num 0
result_df 23
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.8', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '2.6.1.114', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-']
10
29
OXAPROZIN
5

100%|██████████| 11047/11047 [00:02<00:00, 4544.67it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4078.38it/s]
 64%|██████▍   | 173/271 [38:09<20:45, 12.71s/it]

rxndb num 675
failedrxn num 0
result_df 75
['1.2.1.-;1.2.1.99', '1.1.1.23', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.2.1.3', '1.2.1.20;1.2.1.88', '1.14.13.15', '1.14.14.1', '1.2.1.24;1.2.1.5;1.2.1.88;1.5.1.12', '1.5.1.12', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.2.1.16;1.2.1.24;1.2.1.26;1.2.1.3;1.2.1.79;1.2.1.88', '1.1.1.21;1.2.1.16;1.2.1.26;1.2.1.79', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.2.1.5', '1.2.1.26;1.2.1.3', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.3.1.31', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.17.1.1', '1.17.1.1', '1.2.1.40', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.2.1.-;1.2.1.99', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.2.1.-;1.2.1.M5', '1.2.1.-;1.2.1.83', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.2.1;1.2.1.-;1.2.1.20', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.116', '1.1.1.359;1.1.1.376;1.1.1.46', '1.3.1.74', '1.3.1.117', '1.2.1;1.2.1.-', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.1', '1.14.13', '1.2.1', '1.1.1.-', '1.1.1', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.2.1.-;1.2.1.26;1.2.1.3', '1.1.1.179;1.3.1.20', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.2.1.26;1.2.1.4', '6.3.1.2', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.1.26;1.2.1.3;1.2.1.48;1.2.1.5', '1.2.1.3', '6.3.4.2', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.2.3.1', '3.4.11.5', '1.1.1.23;1.1.1.24', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.82', '6.3.2.17', '1.5.1.12;1.5.99.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.1.1.23', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.2.1.31', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '1.1.1.113', '1.3.1.11', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.2.1.3', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.94', '1.14.13.94', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.-', '1.14.13.-', '1.2.1.31', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.2.1.95;1.2.1.z', '1.2.1.31', '1.2.1.19;1.2.1.5', '1.2.1.19;1.2.1.3;1.2.1.39;1.2.1.5', '1.2.1.3', '1.3.1.n3', '1.3.1.n3', '1.1.1.376', '1.3.1.117', '1.2.1.101;1.2.1.ah', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '1.1.1.46', '1.1.1.46', '3.4.15.6', '3.4.19.9', '3.4.19.7', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.2.1.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.2.1.70;6.1.1.17', '1.1.1.117', '1.1.1.117', '1.1.1.117', '1.1.1.117', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.94', '1.14.13.94', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.46', '1.1.1.46', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.1.101', '1.14.13', '3.5.1', '1.14.13.15', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.17.99.5', '1.17.99.5', '1.2.1.3;1.2.1.40', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.2.1', '1.2.1', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1.424', '1.3.1.74', '1.2.1.29;1.2.1.3;1.2.1.5', '1.2.1.5', '1.2.1.3;1.2.1.5', '1.2.1.5', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.2.1.5', '1.2.1.29;1.2.1.5;1.2.1.53', '1.2.1;1.2.1.88;1.5.1.12;1.5.99.8', '1.2.1.5', '1.2.1.3;1.2.1.5', '1.2.1.5']
32
120
OXCARBAZEPINE
5

100%|██████████| 11047/11047 [00:02<00:00, 3781.18it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4137.99it/s]
 64%|██████▍   | 174/271 [38:22<20:24, 12.62s/it]

rxndb num 413
failedrxn num 0
result_df 69
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.1.1.219', '1.1.1.234', '1.1.1.234', '3.5.3.21', '1.1.1.234', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.219', '1.1.1.219', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.50', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1;1.1.1.2;1.1.1.213;1.1.1.50;1.3.1.20', '1.1.1.184;1.1.1.209;1.1.1.213;1.1.1.50', '1.1.1.184', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.1.1.219', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.1.1.50', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '3.2.1.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.1.1.112;1.1.1.184', '1.1.1.112;1.1.1.184;1.1.1.51', '1.1.1;1.1.1.112;1.1.1.184;1.1.1.213;1.1.1.50', '1.1.1.112;1.1.1.184;1.1.1.213;1.1.1.50;1.1.1.62;1.3.1.20', '1.3.1', '1.3.1.-', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14']
9
43
OXETHAZAINE
5

100%|██████████| 11047/11047 [00:02<00:00, 3903.76it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3789.40it/s]
 65%|██████▍   | 175/271 [38:35<20:33, 12.85s/it]

rxndb num 509
failedrxn num 0
result_df 31
['1.1.1.3', '1.1.1.3', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.27', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.1', '3.1.3', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.6.2', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.1.3.23', '1.1.3.17', '3.1.3.39', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.1.1.164;1.1.1.192', '1.1.1.191;1.1.1.2;1.1.1.21', '1.1.1.1;1.1.1.284;1.1.1.73', '1.1.1.150', '1.1.1.151', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.6.9', '3.1.6.10', '1.1.1.66', '4.99.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.1.1.2', '1.1.1.258', '4.3.3.-', '1.14.13.72', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.76', '1.1.1.183;1.1.1.71', '1.1.1.183;1.1.1.71', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.1', '1.14.14.-;1.14.14.1', '1.1.1;1.1.1.-;1.1.1.1', '1.14.13.15;1.14.15.15', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.-;3.1.3.88', '1.14.13.-', '1.14.13.-', '1.1.-.-', '1.14.-.-', '1.1.-.-', '1.14.-.-', '1.1.1.-;1.1.1.71', '1.1.1.-;1.1.1.71', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.1.1.-', '1.14.13.209', '1.14.13.209', '1.14.13.209', '3.1.3.-', '3.1.3;3.1.3.-', '1.1.1.400', '1.14.13.229', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.1.1;1.1.1.-;1.1.1.1;1.1.1.2;1.1.1.21', '3.1.3', '3.1.3.-', '1.1.1;1.1.1.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.1.1', '1.2.1', '3.1.6.c', '3.1.3.4', '3.1.3.4', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M41', '1.1.1', '1.1.1', '1.1.1.1', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.1.1;1.1.1.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.14.145', '1.14.14.145', '1.14.14.145', '1.1.1.2;1.1.1.71', '3.1.6.14', '1.1.1.2;1.1.1.21;1.1.1.71', '1.1.1.2;1.1.1.71', '3.1.3.29', '1.14.15.15', '1.14.15.15', '1.1.1.1', '1.1.1.184;1.1.1.21', '1.1.1.184;1.1.1.2;1.1.1.21;1.1.1.71', '1.1.1.21', '3.1.3.33;3.1.3.5', '1.1.1.1;1.1.1.71', '1.1.1.2', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.1', '1.1.1.1', '1.1.1.1;1.1.1.71', '1.14.13', '1.14.13', '1.14.13', '1.1.1.2', '3.1.3', '3.1.3', '1.1.1.1;1.1.1.284', '1.1.1;1.1.1.1;1.1.1.2;1.1.1.21;1.1.1.284;1.1.1.71', '1.1.1;1.1.1.2;1.1.1.21;1.1.1.71', '1.1.1.2;1.1.1.21;1.1.1.71', '1.1.1.1', '3.1.3', '3.1.3', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.109', '1.2.1.74', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.35', '1.1.1.1;1.1.1.2;1.1.1.265', '1.1.1.2;1.1.1.21;1.1.1.265', '3.1.3.91', '3.6.1;3.6.1.-', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.15.3', '3.1.3.27', '1.14.13.30', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.29', '1.1.1.32;1.1.1.88', '1.1.1.2;1.1.1.32;1.1.1.33', '3.1.3.-', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.72', '1.1.1.273', '1.1.1.273', '1.1.1.273', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.78', '1.14.14.145', '1.14.-.-', '1.14.-.-', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.-.-;1.14.13.-', '1.1.1.317', '1.1.1.317', '3.1.3.73', '3.1.3', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.1.1.1;1.1.1.161', '1.1.99.1', '1.14.13.246', '3.1.6.d', '1.1.1', '3.1.3.M8', '1.1.1.273', '3.1.3.106;3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '1.1.1', '1.1.1.71', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.1.1', '1.1.1', '3.2.1.14', '3.1.3.29', '1.14.13.-', '1.14.-.-', '1.14.-.-;1.14.13.-', '1.14.-.-;1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.13.144', '3.4.15.6', '3.4.19.7', '1.1.3.20', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.-', '3.2.1.-', '1.2.-.-', '1.1.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.15.5', '1.14.15.5', '1.14.15.5', '1.1.1.1', '1.1.3.20', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '3.1.3.27', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.194', '1.14.13.194', '3.1.1.101', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.106', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '1.1.1.1;1.1.1.161', '1.14.13.15;1.14.15.15', '1.14.13.72', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1', '1.1.1;1.1.1.206', '3.1.3.76', '3.1.3.76', '1.1.1.1;1.1.1.190', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '1.1.1;1.1.1.1', '3.1.3.1;3.1.3.75', '1.14.13.-', '1.14.-.-;1.14.13.-;1.14.13.cs']
30
133
OXYBUTYNIN CHLORIDE
5

100%|██████████| 11047/11047 [00:03<00:00, 3036.54it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3930.47it/s]
 65%|██████▍   | 176/271 [38:48<20:31, 12.96s/it]

rxndb num 979
failedrxn num 0
result_df 76
['3.1.3.69', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.1.5', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.27', '3.1.3.3', '3.1.3;3.1.3.2', '3.1.3.74', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.1.23', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.6.2', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3.2;3.1.3.29;3.1.3.38', '1.1.1.118;1.1.1.47', '1.1.1.119;1.1.1.47', '3.1.3.22;3.1.3.23', '3.1.3.39', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.14.13.4', '1.14.13.4', '3.1.6.9', '3.1.6.10', '3.1.1.70', '3.1.1.51', '3.1.3.69', '1.14.13.22', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.76', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.-;3.1.3.88', '3.1.3.79', '1.14.-.-', '1.2.-.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '3.1.3.80', '3.1.3.85', '1.14.-.-', '3.1.3.83', '1.14.13.-', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.1.1.363;1.1.1.388', '1.14.13.209', '1.14.13.209', '1.14.13.209', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.3.103', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.1.1.116', '1.1.1.359;1.1.1.376;1.1.1.46', '3.1.3.3', '3.1.3', '3.1.3.-', '3.1.3;3.1.3.-', '6.3.2', '6.3.2', '3.1.3;3.1.3.-', '3.1.1;3.1.1.1;3.1.1.3', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.3.1', '3.1.1', '1.1.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '3.1.1', '3.1.3', '3.1.3', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.50', '3.1.1.26', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.1.4', '3.1.1.23', '3.1.1.23', '3.1.1.13', '3.1.3', '3.1.6.c', '3.1.3.4', '3.1.3.4', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.1', '1.1.1.-', '1.1.1', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '3.1.3;3.1.3.-;3.1.3.104;3.1.3.2;3.1.3.29', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.1.1;3.1.1.13;3.1.1.3', '3.1.1.1;3.1.1.3', '3.1.1.3', '3.1.1.3', '3.1.1.1', '3.1.6.14', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.3.29', '3.1.3.29', '1.14.15.15', '3.1.1.1;3.1.1.2', '3.1.1.1;3.1.1.2', '3.1.1.1;3.1.1.2', '1.1.1.179;1.3.1.20', '1.1.1.179;1.3.1.20', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '3.4.21;3.4.21.62', '3.4.16.5;3.4.21;3.4.21.62', '3.1.3', '3.1.3', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '3.2.1.78', '1.1.1.121', '1.1.1.47', '3.1.3', '3.1.3', '3.1.6.3', '3.1.3.68', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.2.1.74', '1.14.13.36', '1.14.13.36', '1.14.13.36', '3.4.11.5', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.145;3.2.1.23', '3.2.1.110', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '2.3.1.-', '3.1.3.91', '3.6.1;3.6.1.-', '3.1.1', '3.2.1.137;3.2.1.78', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.34', '1.3.1;1.3.1.-', '1.3.1;1.3.1.-', '3.1.3.29', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.1.5', '3.1.1.5', '3.1.3.23;3.1.3.29;3.1.3.9', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.15.3', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.1.3.27', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.11;3.1.3.37', '3.1.3', '3.1.3.24', '3.1.3.12', '3.1.3.29', '3.1.3.-', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '3.1.1.10', '1.1.1.113', '3.1.3.63', '3.1.3.63', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.-.-', '1.14.-.-', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.-.-;1.14.13.-', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '2.3.1.-', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '3.1.3.45', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.3', '3.1.3.68', '1.1.1.363;1.1.1.388;1.1.1.47;1.1.1.49', '3.1.6.d', '1.14.13.M76', '1.14.13.M76', '3.1.3.M8', '3.1.1.116', '3.1.3.106;3.1.3.76', '1.1.1.376', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '1.1.1.420', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.1.3.58;3.1.3.9', '3.1.6.3', '1.1.1.120', '3.2.1.14', '1.1.1.46', '1.1.1.46', '3.2.1.3;3.2.1.58;3.2.1.59', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.1.1.121', '1.14.-.-', '1.14.-.-;1.14.13.-', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '3.2.1.116', '3.2.1.137', '3.2.1.154', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.4.15.6', '3.4.19.7', '3.2.1.1', '1.7.3.-', '1.14.13.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.2.-.-', '1.14.99.-', '1.14.99.-', '3.2.1.2', '3.1.-.-', '3.1.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.15.5', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '3.2.1.137', '1.1.1.117', '1.1.1.117', '1.1.1.117', '1.1.1.117', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '3.1.1.5', '3.1.3.27', '1.1.1.46', '1.1.1.46', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '3.1.1.101', '3.1.3', '3.1.3.73', '3.2.1.143', '3.1.3.73', '3.1.3', '3.1.3.73', '4.2.1.140;4.2.1.39', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '4.2.1.6', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.106', '3.1.3.73', '3.1.3', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '1.14.13.149', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3.7;3.1.3.97', '1.1.1.363;1.1.1.49', '3.1.3.82', '1.3.99.-', '1.3.99.-', '3.1.3.29;3.1.3.50', '3.1.3.50', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.1.88', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.1.1.118', '1.1.1.120;1.1.1.179;1.1.1.359;1.1.1.360;1.1.1.47;1.1.1.48;1.3.1.20', '1.1.1.120', '3.1.3.58;3.1.3.9', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.1.1.119', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.1.1.121;1.1.1.359;1.1.1.47;1.1.1.48', '1.1.1.121', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.1.1.363;1.1.1.47;1.1.1.49', '1.1.1.49', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1.424', '3.1.1.3', '3.1.3.76', '3.1.3.76', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '1.14.13.127', '4.2.3;4.2.3.1', '3.1.3;3.1.3.1;3.1.3.2', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '3.1.3.1;3.1.3.75', '1.14.13.-', '1.14.-.-;1.14.13.-;1.14.13.cs']
45
242
PACLITAXEL
5

100%|██████████| 11047/11047 [00:05<00:00, 2182.32it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3710.53it/s]

rxndb num 4056
failedrxn num 0

 65%|██████▌   | 177/271 [39:04<21:39, 13.82s/it]

result_df 480

100%|██████████| 11047/11047 [00:03<00:00, 3241.50it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3690.21it/s]
 66%|██████▌   | 178/271 [39:18<21:38, 13.97s/it]

rxndb num 740
failedrxn num 0
result_df 63
['3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.74', '3.1.3.74', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3.39', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.6.9', '3.1.6.10', '1.1.1.234', '1.17.1.3', '1.17.1.3', '1.1.1.234', '1.17.1.3', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.-;3.1.3.88', '3.1.3.79', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.1.1.349', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.1.1.362', '1.14.14', '1.14.14', '1.14.14', '1.14.99', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.348', '1.1.1.348', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '3.1.6.14', '3.1.3.29', '1.14.13;1.14.14', '3.1.3.33;3.1.3.5', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '3.1.3', '3.1.3', '3.1.3.68', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.13.21', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '3.1.3.91', '3.6.1;3.6.1.-', '1.1.1.246;1.1.1.348', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.24', '3.1.3.29', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.3.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '1.1.1.219', '3.1.3', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.14.13.88', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.M8', '3.1.3.105', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.1.1.50', '3.2.1.14', '3.1.3.29', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '3.4.15.6', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.13.99.3', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.88', '1.14.13.176', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13', '1.14.13', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.3.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.3.1', '1.3.1.-', '1.13.99.3', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '2.6.1.114', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '1.11.2.6', '1.11.2.6', '1.11.2.6', '3.1.3.76', '3.1.3.-;3.1.3.104']
31
126
PANTOPRAZOLE
5

100%|██████████| 11047/11047 [00:02<00:00, 3795.71it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3490.37it/s]
 66%|██████▌   | 179/271 [39:32<21:12, 13.83s/it]

rxndb num 236
failedrxn num 0
result_df 39
['1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.99.50;1.14.99.51', '1.14.99.51', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.3.2.14', '3.3.2.14', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '1.14.13.224', '1.14.13.224', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.235', '1.14.13', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.35', '2.4.1.-', '2.4.1.-', '2.4.1.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.3.3.8', '3.2.1.14', '3.2.1.87', '3.2.1.87', '3.2.1.87', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.2.1.3', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.176', '1.14.13.176', '1.14.13.176', '3.2.1.143', '3.2.1.143', '3.2.1.143', '1.14.13.32', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9']
18
55
PAPAVERINE
5

100%|██████████| 11047/11047 [00:03<00:00, 3394.22it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3609.68it/s]
 66%|██████▋   | 180/271 [39:46<21:09, 13.95s/it]

rxndb num 857
failedrxn num 0
result_df 81
['1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.17.1.5', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.6', '1.14.13.6', '1.14.13.6', '1.14.13.6', '1.14.13.6', '1.14.13.6', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.61', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-', '1.14.13.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.13.12.20', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.3.2.14', '3.3.2.14', '3.3.2.14', '3.3.2.14', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '1.14.13.224', '1.14.13.224', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.235', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.10', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '2.4.1.-', '2.4.1.-', '2.4.1.-', '2.4.1.-', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.88', '1.14.13.88', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.3.3.8', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.2.3.1', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.2.1.87', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.2.1.3', '6.2.1.3', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.88', '1.14.13.88', '1.14.13.176', '3.2.1.143', '3.2.1.143', '3.2.1.143', '3.2.1.143', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.182', '1.14.13.182', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9']
23
72
PAROXETINE
5

100%|██████████| 11047/11047 [00:02<00:00, 3702.93it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3545.28it/s]
 67%|██████▋   | 181/271 [40:00<20:55, 13.95s/it]

rxndb num 622
failedrxn num 0
result_df 75
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.5.3.13', '1.5.3.13', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '2.5.1.46', '2.5.1.46', '1.5.3.14;1.5.99.6', '1.5.3.14;1.5.99.6', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.5.1.-;1.5.1.43', '1.5.1.-;1.5.1.43', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.13.-', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '1.5.3.16', '1.5.3.16', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.2.1.40', '3.2.1.40', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.5.3.14', '1.5.3.14', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.5.3.16', '1.5.3.16', '3.2.1.21;3.2.1.23', '3.2.1.21;3.2.1.23', '3.2.1.22', '3.2.1.22', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '3.2.1.161;3.2.1.188;3.2.1.21;3.2.1.23;3.2.1.25;3.2.1.3;3.2.1.37;3.2.1.45;3.2.1.58;3.2.1.74', '3.2.1.161;3.2.1.188;3.2.1.21;3.2.1.23;3.2.1.25;3.2.1.3;3.2.1.37;3.2.1.45;3.2.1.58;3.2.1.74', '3.2.1.3', '3.2.1.3', '3.2.1;3.2.1.10;3.2.1.177;3.2.1.199;3.2.1.20;3.2.1.21;3.2.1.70', '3.2.1;3.2.1.10;3.2.1.177;3.2.1.199;3.2.1.20;3.2.1.21;3.2.1.70', '3.2.1.51', '3.2.1.51', '3.2.1.78', '3.2.1.78', '3.2.1.21;3.2.1.22;3.2.1.23', '3.2.1.21;3.2.1.22;3.2.1.23', '3.2.1.22;3.2.1.23;3.2.1.85', '3.2.1.22;3.2.1.23;3.2.1.85', '3.2.1.55', '3.2.1.55', '3.2.1.23', '3.2.1.23', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.-.-', '1.14.-.-', '1.14.21.8', '1.14.21.8', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '2.4.1.-', '2.4.1.-', '2.4.1.-', '1.14.-.-', '1.14.-.-', '1.5.3;1.5.3.13;1.5.3.16;1.5.3.17', '1.5.3;1.5.3.13;1.5.3.16;1.5.3.17', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '1.14.21.2', '1.14.21.2', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.19.68;1.14.21.5', '1.14.19.68;1.14.21.5', '1.14.21.1', '1.14.21.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.-', '1.14.13.-', '3.2.1.20;3.2.1.22', '3.2.1.20;3.2.1.22', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.5.1.43', '1.5.1.43', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.5.1.43', '1.5.1.43', '3.2.1.126', '3.2.1.126', '3.2.1.87', '3.2.1.87', '3.2.1.87', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.21.8', '1.14.21.8', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.184', '1.14.13.184', '3.2.1.143', '3.2.1.143', '3.2.1.143', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.126', '3.2.1.126', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6']
25
94
PENBUTOLOL SULFATE
5

100%|██████████| 11047/11047 [00:02<00:00, 4503.66it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3759.25it/s]
 67%|██████▋   | 182/271 [40:12<19:52, 13.40s/it]

rxndb num 1356
failedrxn num 0
result_df 64

100%|██████████| 11047/11047 [00:03<00:00, 3314.17it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4210.28it/s]
 68%|██████▊   | 183/271 [40:25<19:20, 13.19s/it]

rxndb num 810
failedrxn num 0
result_df 51
['1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.13;1.14.14.1;1.14.99.10', '1.14.13;1.14.99.10', '1.14.13.-;1.14.14.-;1.14.14.1', '1.1.1.148', '1.1.1.148', '1.1.3.16', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.17.1.1', '1.17.1.1', '1.3.1.5', '1.3.1.5', '1.1.1;1.1.1.-', '1.1.1;1.1.1.-', '1.1.1.230', '1.1.1.230', '1.1.1.62', '1.1.1.62', '1.1.1.62', '1.1.1.62', '1.1.1.146', '1.1.1.146', '1.1.1.53', '1.1.1.53', '1.1.1.50', '1.1.1.50', '1.1.1.53', '1.1.1.53', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.53', '1.1.1.270', '1.1.1.270', '1.14.13.181', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.270', '1.1.1.270', '1.17.3.2', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.13.12.-;1.14.13.178', '1.13.12.-;1.14.13.178', '1.13.12.-;1.14.13.178', '1.13.12.-;1.14.13.178', '1.13.12.-;1.14.13.178', '1.13.12.-;1.14.13.178', '1.13.12.-;1.14.13.178', '1.13.12.-;1.14.13.178', '1.13.12.-', '1.13.12.-', '1.13.12.-;1.14.13.179', '1.13.12.-;1.14.13.179', '1.13.12.-', '1.13.12.-', '1.14.13.128', '1.14.13.128', '1.13.12.-', '1.13.12.-', '1.13.12.-;1.14.13.178', '1.13.12.-;1.14.13.178', '1.13.12.-;1.14.13.178', '1.13.12.-;1.14.13.178', '1.13.12.-;1.14.13.179', '1.13.12.-;1.14.13.179', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.-', '1.1.1.-', '1.1.1;1.1.1.-;1.1.1.50', '1.1.1;1.1.1.-;1.1.1.50', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.239;1.1.1.62', '1.1.1.239;1.1.1.62', '1.1.1.213', '1.1.1.213', '1.1.1.149', '1.1.1.149', '1.1.1.209;1.1.1.213;1.1.1.357', '1.1.1.209;1.1.1.213;1.1.1.357', '1.1.1.62', '1.1.1.62', '1.14.-.-', '1.14.13.-;1.14.13.161', '1.1.1.335', '1.1.1.335', '1.1.1.340;1.14.13.-', '1.1.1.340;1.14.13.-', '1.1.1.352', '1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.374', '1.1.1.374', '1.1.1.393', '1.1.1.393', '1.1.1.-', '1.1.1.-', '1.1.1.395', '1.1.1.395', '1.1.1.-;1.1.1.395', '1.1.1.-;1.1.1.395', '1.3.3.6', '1.1.1.201', '1.1.1.201', '1.1.1.-;1.1.1.50;1.1.1.52', '1.1.1.-;1.1.1.50;1.1.1.52', '1.1.1.391', '1.1.1.391', '1.1.1.-;1.1.1.270', '1.1.1.-;1.1.1.270', '1.1.1;1.1.1.-;1.1.1.270', '1.1.1;1.1.1.-;1.1.1.270', '1.1.1.-;1.1.1.270', '1.1.1.-;1.1.1.270', '1.1.1.-;1.1.1.393', '1.1.1.-;1.1.1.393', '1.1.1.145', '1.1.1.145', '1.14.13;1.14.13.-', '1.3.1.93', '1.3.1.93', '1.1.1;1.1.1.-', '1.3.1.93', '1.3.1.93', '1.1.1', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1', '1.1.1', '1.1.1', '1.1.1.201', '1.1.1.201', '1.3.1.93', '1.3.1.93', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1', '1.14.13', '1.1.1.M11', '1.1.1.M11', '1.1.1.M11', '1.1.1.M11', '1.1.1.392', '1.1.1.392', '1.1.1.393', '1.1.1.393', '1.1.1.52', '1.1.1.52', '1.1.1.391', '1.1.1.391', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.52', '1.1.1.52', '1.1.1.391', '1.1.1.391', '1.1.1.392;1.1.1.50;1.1.1.52', '1.1.1.392;1.1.1.50;1.1.1.52', '1.1.1.392', '1.1.1.392', '1.1.1.393', '1.1.1.393', '1.1.1.393', '1.1.1.393', '1.3.1', '1.3.1', '1.17.1.4', '1.17.1.4', '1.1.1.270', '1.1.1.270', '1.1.1.270', '1.1.1.270', '1.3.3.6', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.2;1.1.1.213;1.1.1.239;1.1.1.62;1.3.1.20', '1.1.1;1.1.1.2;1.1.1.213;1.1.1.239;1.1.1.62;1.3.1.20', '1.1.1.149;1.1.1.62', '1.14.14.1', '1.1.1.159', '1.1.1.159', '1.3.1.48', '1.1.1.1', '1.1.1.1', '1.1.1.188;1.1.1.213;1.1.1.50', '1.1.1.1', '1.1.1.1', '1.14.15.15', '1.1.1.149', '1.1.1.145', '1.1.1.149;1.1.1.357', '1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50;1.3.1.20', '1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50;1.3.1.20', '1.1.1.239;1.1.1.51', '1.1.1.239;1.1.1.51', '1.1.1.239;1.1.1.51', '1.1.1.239;1.1.1.51', '1.1.1.239', '1.1.1.239', '1.1.1.184', '1.1.1.184', '1.1.1;1.1.1.184;1.1.1.62', '1.1.1;1.1.1.184;1.1.1.62', '1.1.1.184;1.1.1.2;1.1.1.62', '1.1.1.184;1.1.1.2;1.1.1.62', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.50', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.1.1.51', '1.1.1.51', '1.1.1.51', '1.1.1.51', '1.1.1;1.1.1.209', '1.1.1;1.1.1.209', '1.1.1', '1.1.1', '1.1.1.209', '1.1.1.209', '1.1.1.209', '1.1.1.209', '1.1.1.209', '1.1.1.149', '1.1.1.357;1.1.1.50', '1.1.1.210;1.1.1.357', '1.1.1.210;1.1.1.357', '1.1.1.184;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.50', '1.1.1.184;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.50', '1.1.1.184;1.1.1.50', '1.1.1.184;1.1.1.50', '1.1.1.146;1.1.1.159;1.1.1.50', '1.1.1.146;1.1.1.159;1.1.1.50', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '1.1.1.146', '1.1.1.146', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '3.2.1.35', '3.2.1.35', '1.17.5.-;1.17.5.2', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-', '1.1.1.239;1.1.1.51', '1.1.1.239;1.1.1.51', '1.1.1;1.1.1.239;1.1.1.62;1.1.1.64', '1.1.1;1.1.1.239;1.1.1.62;1.1.1.64', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.-;1.1.1.146', '1.1.1.-;1.1.1.146', '1.1.1;1.1.1.-;1.1.1.146;1.1.1.51', '1.1.1;1.1.1.-;1.1.1.146;1.1.1.51', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62;1.1.1.63', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62;1.1.1.63', '1.1.1.184;1.1.1.2;1.1.1.213;1.1.1.51;1.1.1.64', '1.1.1.184;1.1.1.2;1.1.1.213;1.1.1.51;1.1.1.64', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.2;1.1.1.209;1.1.1.21;1.1.1.213;1.1.1.50;1.3.1.20', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.2;1.1.1.209;1.1.1.21;1.1.1.213;1.1.1.50;1.3.1.20', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.30', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '1.1.1.149;1.1.1.210;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.149;1.1.1.62', '1.1.1;1.1.1.148;1.1.1.209', '1.1.1;1.1.1.148;1.1.1.209', '1.1.1.159;1.1.1.50', '1.1.1.159;1.1.1.50', '1.1.1.176', '1.1.1.176', '1.1.1.206', '1.1.1.206', '1.1.1.236', '1.1.1.236', '1.1.1.198', '1.1.1.198', '1.1.1.227', '1.1.1.227', '1.1.1.149;1.1.1.184;1.1.1.62', '1.1.1.238', '1.1.1.238', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.1.1.201', '1.1.1.201', '1.1.1.146', '1.1.1.146', '1.1.1.213;1.1.1.52', '1.1.1.213;1.1.1.52', '1.1.1.152;1.1.1.184;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1.152;1.1.1.184;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1.184;1.1.1.209;1.1.1.213;1.1.1.50', '1.1.1.184;1.1.1.209;1.1.1.213;1.1.1.50', '1.14.99.10', '1.3.1.104;1.3.1.38;1.3.1.8', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.209;1.1.1.50', '1.1.1.209;1.1.1.50', '1.1.1.213;1.1.1.50;1.1.1.51', '1.1.1.213;1.1.1.50;1.1.1.51', '1.1.1.149;1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.149;1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.1.1.213;1.1.1.277;1.1.1.50', '1.1.1.213;1.1.1.277;1.1.1.50', '1.3.1.104;1.3.1.38;1.3.1.44;1.3.1.8', '1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.278', '1.1.1.278', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.1.1.210;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1.210;1.1.1.357;1.1.1.50;1.1.1.51', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.1;1.1.1.391', '1.1.1.1;1.1.1.391', '1.1.1.-;1.1.1.146;1.1.1.209;1.1.1.213;1.1.1.392;1.1.1.50', '1.1.1.-;1.1.1.146;1.1.1.209;1.1.1.213;1.1.1.392;1.1.1.50', '1.1.1;1.3.1.44', '1.1.1.159', '1.1.1.159', '1.1.1.270', '1.1.1.270', '1.1.1.149;1.1.1.51', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.213;1.1.1.50;1.1.1.51;1.1.1.53', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.213;1.1.1.50;1.1.1.51;1.1.1.53', '1.1.1.-;1.1.1.M53', '1.1.1.-;1.1.1.M53', '1.3.99.-', '1.14.-.-', '1.14.-.-', '1.3.99.3', '1.1.1;1.3.99.3', '1.3.1.9', '1.1.1.21', '1.1.1.270', '1.1.1.270', '1.1.1.270', '1.1.1.270', '1.1.1.270', '1.1.1.270', '1.1.1.201', '1.1.1.201', '1.1.1', '1.1.1', '1.1.1.322', '1.1.1.322', '1.1.1.322', '1.1.1.322', '1.1.1.64', '1.1.1.64', '1.1.1', '1.1.1', '1.1.1', '1.1.1', '1.1.1', '1.1.1', '3.2.1.14', '3.2.1.14', '3.2.1.14', '1.1.1.227', '1.1.1.227', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-', '1.14.-.-', '3.4.15.6', '3.4.15.6', '3.4.15.6', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.-', '3.2.1.-', '3.2.1.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.1.1.352', '1.14.15.5', '1.1.1.-;1.1.1.270', '1.1.1.-;1.1.1.270', '1.1.1.-;1.1.1.270', '1.1.1.-;1.1.1.270', '1.14.14.1', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.1.1.-', '1.1.1.-', '1.1.1.-', '1.1.1.-', '1.1.1.-', '1.1.1.-', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.194', '1.1.1.M51', '1.1.1.M51', '1.1.1.M51', '1.1.1.M51', '1.3.3.6', '1.1.1.-;1.1.1.1;1.1.1.327', '1.1.1.-;1.1.1.1;1.1.1.327', '1.3.1.93', '1.1.1.270', '1.1.1.270', '1.3.3.6', '1.3.1.104;1.3.1.38;1.3.1.8', '1.1.1;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.51;1.1.1.62', '1.1;1.1.1;1.1.1.209;1.1.1.213', '1.1;1.1.1;1.1.1.209;1.1.1.213', '1.1.1.1', '1.1.1.1', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.1.1;1.1.1.184;1.1.1.210;1.1.1.50', '1.1.1;1.1.1.184;1.1.1.210;1.1.1.50', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.2;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.3.1.20', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.2;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.3.1.20', '1.1.1.184;1.1.1.357', '1.3.3.6;1.3.8.1;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.3.3.6', '1.3.3.6', '1.3.1.10;1.3.1.38;1.3.1.8', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.1.1.395', '1.1.1.395', '1.1.1.146', '1.1.1.146', '1.1.1.64', '1.1.1.64', '1.1.1.146', '1.1.1.146', '1.1.1.146', '1.1.1.146', '1.1.1.239', '1.1.1.239', '1.1.1.239', '1.1.1.239', '1.1.1.62', '1.1.1.62', '1.1.1.270', '1.1.1.270', '1.1.1.238', '1.1.1.238', '1.1.1.206', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50']
25
114
PERGOLIDE MESYLATE
5

100%|██████████| 11047/11047 [00:04<00:00, 2592.64it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3396.95it/s]
 68%|██████▊   | 184/271 [40:40<20:07, 13.88s/it]

rxndb num 221
failedrxn num 0
result_df 40
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '2.5.1.128', '2.5.1.128', '2.5.1.128', '2.5.1.128', '1.14.13.224', '1.14.13.224', '1.14.13.235', '1.14.13', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.13.11', '1.14.15.15', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.13', '1.14.13', '1.14.13', '1.13.11.52', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '1.13.11.52', '1.13.11.11;1.13.11.52', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.13.11.11;1.13.11.52', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.13.99.3', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.13.11.52', '1.14.13.174', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.5.1.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.M64', '1.14.13.M64', '1.14.13.182', '1.14.13.182', '1.13.99.3', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.13.11.52', '1.13.11.52', '1.-.-.-', '2.5.1;2.5.1.-;2.5.1.48']
12
44
PERICYAZINE
5

100%|██████████| 11047/11047 [00:03<00:00, 3211.37it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3714.91it/s]
 68%|██████▊   | 185/271 [40:54<19:51, 13.85s/it]

rxndb num 764
failedrxn num 0
result_df 73
['3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.74', '3.1.3.74', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3.39', '1.1.1.1;1.1.1.163;1.1.1.184;1.1.1.245;1.1.1.90', '1.1.1.148', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.147', '1.1.1.147', '3.1.6.9', '3.1.6.10', '1.1.1;1.1.1.-', '1.1.1.62', '1.1.1.62', '1.1.1.53', '1.1.1.50', '1.1.1.53', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.14.13.-;1.14.15.-;1.14.15.3', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.-;1.1.1.329', '3.1.3.-;3.1.3.88', '1.1.1.213', '1.1.1.209;1.1.1.213;1.1.1.357', '3.1.3.79', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '3.1.3.85', '1.1.1.-;1.1.1.329', '1.1.1.335', '1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.213;1.1.1.357;1.1.1.50', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.1.1.374', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.1.1.393', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.395', '1.1.1.-;1.1.1.395', '3.1.3', '3.1.3.-', '1.1.1.201', '1.1.1.-;1.1.1.50;1.1.1.52', '1.1.1.391', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.1.1.102', '1.1.1.145', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.1.1', '1.1.1', '3.1.3', '1.1.1.201', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1', '1.1.1', '1.14.13', '1.1.1.M11', '1.1.1.M11', '1.1.1.392', '1.1.1.393', '1.1.1.52', '1.1.1.391', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.52', '1.1.1.391', '1.1.1.392;1.1.1.50;1.1.1.52', '1.1.1.392', '1.1.1.393', '1.1.1.393', '1.1.1.159', '3.1.6.14', '1.1.1.1', '1.1.1.188;1.1.1.213;1.1.1.50', '3.1.3.29', '1.1.1.149', '1.1.1.145', '1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50;1.3.1.20', '3.1.3.33;3.1.3.5', '1.1.1.239;1.1.1.51', '1.1.1.184', '1.1.1;1.1.1.184;1.1.1.62', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.1.1.213;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.50', '1.1.1.51', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.1.1', '1.1.1.209', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.1.1.357;1.1.1.50', '3.2.1.78', '1.1.1.184;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.50', '1.1.1.184;1.1.1.50', '1.1.1.184;1.1.1.188;1.1.1.2', '3.1.3', '3.1.3', '1.1.1.146;1.1.1.159;1.1.1.50', '1.1.99.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.65', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '3.1.3.91', '3.6.1;3.6.1.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '1.1.1.239;1.1.1.51', '1.1.1;1.1.1.239;1.1.1.62;1.1.1.64', '1.1.1.-;1.1.1.146', '1.1.1;1.1.1.-;1.1.1.146;1.1.1.51', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.24', '3.1.3.12', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '3.1.3.29', '1.1.1;1.1.1.148;1.1.1.209', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.3.-', '1.1.1.159;1.1.1.50', '1.1.1.176', '1.1.1.206', '1.1.1.236', '1.1.1.238', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.1.1.146', '1.1.1.213;1.1.1.52', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.1.1.213;1.1.1.50', '1.1.1.50', '1.1.1.209;1.1.1.50', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.1;1.1.1.391', '1.1.1.-;1.1.1.146;1.1.1.209;1.1.1.213;1.1.1.392;1.1.1.50', '3.1.3.73', '1.1.1.159', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.213;1.1.1.50;1.1.1.51;1.1.1.53', '3.1.3.45', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.1.1.-;1.1.1.M53', '1.14.13;1.14.13.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.68', '1.1.1.270', '1.1.1.270', '3.1.3.M8', '1.1.1', '3.1.3.105', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.1', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.-', '3.2.1.2', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.1.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '1.1.1.M51', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.1.1;1.1.1.51;1.1.1.62', '1.14.13.-;1.14.15.6', '1.1.99.13', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.1.1;1.1.1.184;1.1.1.210;1.1.1.50', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.2;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.3.1.20', '1.1.1.184;1.1.1.357', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '1.1.1.395', '1.1.1.146', '1.1.1.239', '1.1.1.238', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1.206', '1.1.1.206', '1.1.1.102', '1.1.1.213;1.1.1.50', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '3.1.3.1;3.1.3.75']
27
163
PERINDOPRIL ERBUMINE
5

100%|██████████| 11047/11047 [00:02<00:00, 4159.28it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3950.35it/s]
 69%|██████▊   | 186/271 [41:07<19:02, 13.44s/it]

rxndb num 1372
failedrxn num 0
result_df 160
['1.2.1.3;1.2.1.54', '1.2.1.-;1.2.1.99', '3.4.13.18;3.4.13.9', '1.1.1.23', '3.1.1.5', '1.2.1.3', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.13.15', '4.1.1.30', '4.1.1.36', '1.2.1.24;1.2.1.5;1.2.1.88;1.5.1.12', '1.5.1.12', '3.1.1.23', '1.2.1.3;1.2.1.47', '3.1.1.22;3.1.1.75', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.2.1.40', '3.1.1.70', '3.1.1.51', '1.14.13.72', '1.2.1.74', '1.14.13.22', '1.14.13.181', '1.2.1.-;1.2.1.99', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.5.1;1.5.1.-', '1.5.1;1.5.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.2.1.-;1.2.1.M5', '6.3;6.3.-.-', '6.3.2', '6.3.2', '3.1.1;3.1.1.1;3.1.1.3', '1.14.13', '1.14.13;1.14.13.-', '1.3.1', '1.3.1', '1.2.1;1.2.1.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '3.1.1', '3.1.1.26', '3.1.1.4', '3.1.1.23', '3.1.1.23', '3.1.1.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '1.2.1', '3.1.1', '1.14.13;1.14.13.-', '1.1.1.-', '1.1.1.-', '3.1.1.1;3.1.1.13;3.1.1.3', '3.1.1.1;3.1.1.3', '3.1.1.3', '3.1.1.3', '3.1.1.1', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '1.2.1.47', '1.14.15.15', '1.14.15.15', '1.14.15.15', '3.1.1.1;3.1.1.2', '3.1.1.1;3.1.1.2', '3.1.1.1;3.1.1.2', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.2.1.19;1.2.1.3', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '3.4.21;3.4.21.62', '3.4.16.5;3.4.21;3.4.21.62', '6.3.1.2', '6.3.4.2', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.1.99.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.2.3.1', '1.14.13.72', '1.2.1.74', '1.2.1.74', '1.2.1.74', '3.4.11.5', '3.4.11.5', '3.4.11.5', '1.1.1.23;1.1.1.24', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '6.3.2.17', '6.3.2.17', '6.3.2.17', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '3.2.1.35', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '2.3.1.-', '3.1.1', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.3.1;1.3.1.-', '1.3.1;1.3.1.-', '1.3.1;1.3.1.-', '1.3.1;1.3.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.1.5', '3.1.1.5', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.30', '1.14.13.30', '1.14.13.30', '1.1.1.23', '1.2.1.31', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '3.1.1.10', '1.2.1.3', '2.-.-.-', '2.-.-.-', '1.14.13.72', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.78', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.11.-', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-;1.14.13.-', '1.14.-.-;1.14.13.-', '1.14.-.-;1.14.13.-', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.3.1.-', '1.2.1.31', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.2.1.95;1.2.1.z', '1.2.1.31', '1.2.1.3', '1.14.14.22;1.14.99.46', '1.2.1.3', '1.14.13.M76', '1.14.13.M76', '1.14.13.M76', '3.1.1.116', '1.2.1.-', '3.2.1.14', '3.2.1.14', '3.2.1.14', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-;1.14.13.-', '1.14.-.-;1.14.13.-', '1.14.-.-;1.14.13.-', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.144', '3.2.1.87', '3.4.15.6', '3.4.15.6', '3.4.15.6', '3.4.19.9', '3.4.19.9', '3.4.19.9', '3.4.19.7', '3.4.19.7', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.-', '3.2.1.-', '3.2.1.-', '1.2.1.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '3.1.-.-', '3.1.-.-', '1.14.11.-', '1.14.11.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.174', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.15.5', '1.14.15.5', '1.14.15.5', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.2.1.70;6.1.1.17', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '3.1.1.5', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.194', '1.14.13.194', '1.14.13.194', '3.1.1.101', '3.1.1.101', '3.1.1.101', '3.2.1.143', '3.5.1', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.15', '1.3.99.-', '1.3.99.-', '1.3.99.-', '1.3.99.-', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.2.1.3;1.2.1.40', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '3.6.1.18;3.6.1.9', '1.13.11.90', '1.2.1', '1.2.1', '1.13.11.90', '1.1.1;1.1.1.206', '3.1.1.3', '1.2.1;1.2.1.19;1.2.1.3', '1.2.1;1.2.1.-;1.2.1.19;1.2.1.3', '1.2.1.3;1.2.1.5', '1.2.1.5', '1.2.1.19;1.2.1.3;1.2.1.8', '1.2.1.19;1.2.1.8']
42
128
PHENACETIN
5

100%|██████████| 11047/11047 [00:03<00:00, 3504.58it/s]
100%|██████████| 27873/27873 [00:05<00:00, 4666.95it/s]
 69%|██████▉   | 187/271 [41:19<18:13, 13.02s/it]

rxndb num 231
failedrxn num 0
result_df 27
['1.14.13.9', '1.14.13.9', '3.1.1.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.7', '1.14.13.7', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.6', '1.14.13.6', '1.14.13.29', '1.14.13.29', '1.14.13.4', '1.14.13.4', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.7.1.12', '1.7.1.12', '1.14.13.219;1.14.13.7', '1.14.13.219;1.14.13.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.181', '1.14.13.-;1.6.5.2', '1.14.13.-;1.6.5.2', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.13.244;1.14.13.M20', '1.14.13.244;1.14.13.M20', '1.11.2.5', '1.11.2.5', '6.3.1.18', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.220', '1.14.-.-', '1.14.-.-', '2.1.1.-', '3.5.1.123', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '3.5.1', '1.14.13.M33', '1.14.13.M33', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '2.3.2.2;3.4.11.10;3.4.19.3', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.4.21.4;3.4.22;3.4.22.1', '3.1.1.3', '3.3.2.6;3.4.11.10;3.4.11.15', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '3.1.1;3.1.1.3', '1.14.13', '1.14.13', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.35', '1.14.14.91', '1.14.14.91', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.7', '1.14.13.7', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.140', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '1.14.18.2', '1.14.19.55', '1.14.19.55', '1.14.14.1', '1.14.14.1', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.4.19.7', '1.14.12.-', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.140', '3.5.1', '1.14.18.2', '1.14.13.-', '1.14.13.-', '1.14.14.20', '1.14.14.20', '1.14.14.8', '1.14.14.8', '1.14.14.27', '1.14.14.27', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.11.2.6', '1.11.2.6', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127']
32
85
PHENAZOPYRIDINE
5

100%|██████████| 11047/11047 [00:02<00:00, 4393.75it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3918.44it/s]
 69%|██████▉   | 188/271 [41:31<17:43, 12.81s/it]

rxndb num 114
failedrxn num 0
result_df 25
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.7.1.6', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.8.99.3;1.8.99.5', '1.8.99.3;1.8.99.5', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.1.1.2', '1.1.1.2', '1.1.1.2', '1.1.1.2', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.7.1.11', '1.7.1.11', '1.7.1.6', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.12.-', '1.14.12.-', '1.14.12.-', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.7.1.17;1.7.1.6', '1.7.1.M3', '1.7.1.M3']
6
17
PHENYTOIN SODIUM
5

100%|██████████| 11047/11047 [00:02<00:00, 4477.20it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4208.30it/s]
 70%|██████▉   | 189/271 [41:43<17:03, 12.48s/it]

rxndb num 108
failedrxn num 0
result_df 23
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.2.1.-', '3.2.1.-', '1.14.13.149', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14', '1.14.14', '1.14.14', '1.11.2.6', '1.11.2.6', '1.11.2.6']
15
36
PIDOTIMOD
5

100%|██████████| 11047/11047 [00:02<00:00, 4166.10it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4104.15it/s]
 70%|███████   | 190/271 [41:55<16:41, 12.36s/it]

rxndb num 323
failedrxn num 0
result_df 36
['1.2.1.3;1.2.1.54', '1.2.1.-;1.2.1.99', '3.5.1.94', '3.4.19.14', '2.3.2.2;3.4.19;3.4.19.13', '3.4.13.18;3.4.13.9', '1.1.1.23', '1.2.1.3', '1.14.13.15', '6.3.2.1', '4.1.1.30', '3.5.1.92', '4.1.1.36', '1.2.1.24;1.2.1.5;1.2.1.88;1.5.1.12', '1.5.1.12', '3.5.1.22', '6.3.2.23', '6.3.1.2;6.3.1.6', '3.5.1.65', '6.3.2.20', '1.17.1.1', '1.17.1.1', '1.2.1.40', '3.5.1.24;3.5.1.74', '3.5.1.24', '1.3.1.48', '1.3.1.48', '3.5.1.93', '1.2.1.-;1.2.1.99', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '6.3.2.36', '1.2.-.-', '1.2.-.-', '1.2.-.-', '1.2.1.-;1.2.1.M5', '3.5.1.-', '6.3.2.44', '6.3.4.24', '3.4.19.11', '3.5.1.70', '6.3.2.18', '6.3;6.3.-.-', '6.3.2;6.3.2.-', '1.3.3.6', '6.3.2', '6.3.2', '3.4.19.16', '3.4.19.16', '3.4.19.16', '3.4.19.16', '3.4.19.16', '3.4.19.16', '3.4.19.16', '6.3.2', '3.4.19.16', '3.4.11.25', '1.3.1.93', '1.3.1.93', '6.3.2.59', '6.3.2.59', '3.4.19.13;3.4.19.9', '1.3.1.93', '1.3.1.93', '6.3.2', '3.4.13;3.4.13.-', '6.3.2', '3.4.13', '6.3.2', '1.3.1.93', '1.3.1.93', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '1.3.1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '1.2.1', '6.3.2', '1.8.3', '3.4', '3.5.1.115', '1.3.3.6', '3.5.1.23', '3.5.1.23', '3.5.1.23', '1.3.1.48', '1.3.1.48', '1.3.1.48', '3.5.1.11', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.4.15.1;3.4.21.39', '1.2.1.19;1.2.1.3', '3.5.1.23', '6.3.1.2', '3.5.1.23', '6.3.4.2', '6.3.2.18', '1.2.3.1', '3.4.11.5', '3.4.11.5', '3.4.11.5', '1.1.1.23;1.1.1.24', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '6.3.2.17', '6.3.2.17', '6.3.2.17', '1.5.1.12;1.5.99.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '3.2.1.35', '6.3.1.11', '3.5.1.-;3.5.1.78', '6.3.1.8;6.3.1.9', '3.5.1.11', '3.5.1.4;3.5.1.99', '6.3.2.10', '1.1.1.23', '4.2.1.22', '3.5.1.24;3.5.1.74', '1.2.1.31', '6.3.1.9', '6.3.2.10', '1.3.1.104;1.3.1.38;1.3.1.8', '1.2.1.3', '2.-.-.-', '1.3.1.104;1.3.1.38;1.3.1.44;1.3.1.8', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '3.5.1.-', '6.3.1.13', '1.1.1;1.3.1.44', '1.2.1.31', '1.3.99.-', '1.2.1.95;1.2.1.z', '1.2.1.31', '1.3.99.3', '1.1.1;1.3.99.3', '1.3.1.9', '6.3.1.10', '6.3.1.10', '3.5.1.90', '3.5.1.90', '1.2.1.3', '1.2.1;1.2.1.-;1.2.1.19;1.2.1.3;1.2.1.5', '3.4.19.16', '6.3.2.56;6.3.2.ad', '1.14.14.22;1.14.99.46', '3.4.19.13', '1.3.1.42', '6.3.2.45', '3.5.1.60;3.5.1.99', '3.5.1.60', '3.5.1.60;3.5.1.99', '3.5.1.99', '3.5.1.99', '3.5.1.128', '1.1.1.420', '1.2.1.101;1.2.1.ah', '3.5.1.60', '3.4', '3.2.1.14', '3.2.1.14', '3.2.1.14', '3.4.15.6', '3.4.15.6', '3.4.15.6', '3.4.19.9', '3.4.19.9', '3.4.19.9', '3.4.19.5', '3.4.19.5', '3.4.19.5', '3.4.19.7', '3.4.19.7', '3.4.19.7', '3.2.1.-', '3.2.1.-', '3.2.1.-', '1.14.99.-', '1.2.1.3', '1.14.11.-', '1.14.99.-', '1.14.99.-', '3.5.1.28', '2.5.1.-', '1.2.1.70;6.1.1.17', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '6.3.2;6.3.2.-', '6.3.2', '6.3.2', '6.3.2', '3.4.19.16', '3.4.19.13', '3.4.19.13', '3.5.1', '3.4.19.13', '1.3.3.6', '3.4.19.13', '6.3.2', '3.4.19.13', '3.4.19.13', '6.3.2', '6.3.2.37', '1.3.1.93', '1.3.3.6', '1.3.1.104;1.3.1.38;1.3.1.8', '6.3.1.10', '1.14.13.15', '1.3.99.-', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.2.1.3;1.2.1.40', '1.3.3.6;1.3.8.1;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.3.3.6', '1.3.3.6', '1.3.1.10;1.3.1.38;1.3.1.8', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '6.3.2.58', '6.3.2.58', '3.5.1.115', '1.1.1;1.1.1.206', '1.1.1;1.1.1.206', '1.2.1;1.2.1.19;1.2.1.3', '1.2.1;1.2.1.88;1.5.1.12;1.5.99.8', '1.2.1;1.2.1.-;1.2.1.19;1.2.1.3', '3.5.1.46', '1.2.1.3;1.2.1.5', '1.2.1.5', '1.-.-.-', '4.2.1.22', '2.5.1;2.5.1.-;2.5.1.48']
38
139
PIMOZIDE
5

100%|██████████| 11047/11047 [00:03<00:00, 3383.32it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4154.28it/s]
 70%|███████   | 191/271 [42:08<16:39, 12.49s/it]

rxndb num 206
failedrxn num 0
result_df 37
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.12.16', '1.14.12.16', '1.14.13.61', '1.14.13.61', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.5.99.9', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13', '1.14.13;1.14.13.-', '1.14.13', '1.3.1', '1.3.1', '1.14.12.16', '1.14.12.16', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.8', '3.4.11.5', '1.14.14.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.4.15.6', '3.2.1.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.176', '1.14.13.176', '1.14.13.176', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182']
12
33
PITAVASTATIN CALCIUM
5

100%|██████████| 11047/11047 [00:04<00:00, 2234.98it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4043.46it/s]
 71%|███████   | 192/271 [42:22<17:24, 13.22s/it]

rxndb num 1980
failedrxn num 0
result_df 128

100%|██████████| 11047/11047 [00:03<00:00, 3313.96it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3414.84it/s]
 71%|███████   | 193/271 [42:37<17:39, 13.58s/it]

rxndb num 520
failedrxn num 0
result_df 52
['1.1.1.23', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.2.1.5', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.6.1.7', '1.17.1.5', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.19', '1.14.13.19', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.61', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '4.1.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.13.130', '1.2.1.-;1.2.1.83', '1.13.12.20', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.1.1.203', '1.1.1.203', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13.224', '1.14.13.224', '1.1.1.203', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.235', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.-', '1.2.3.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.-', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.2.3.1', '1.1.1.23;1.1.1.24', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.82', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.76', '3.2.1.31', '1.14.13.10', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '2.4.1.-', '1.14.13.30', '1.1.1.23', '1.14.13.12', '1.14.13.12', '1.14.13.12', '1.14.13.12', '1.14.13.12', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.21.3', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.2.1.3', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.1.1.107;1.1.1.122', '1.14.13.88', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.2.1.3', '1.14.14.22;1.14.99.46', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.2.1.101;1.2.1.ah', '1.2.3.1', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.87', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '3.2.1.15', '4.2.2.2', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.88', '1.14.13.176', '3.2.1.143', '1.14.13.182', '1.14.13.182', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.2.1.29;1.2.1.3;1.2.1.5', '1.2.1.5', '1.2.1.3;1.2.1.5', '1.2.1.5', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.2.1.5', '1.2.1.3;1.2.1.5', '1.2.1.5', '1.2.1.29;1.2.1.5;1.2.1.53', '1.2.1.5', '1.2.1.3;1.2.1.5', '1.2.1.5']
27
95
PRAZOSIN
5

100%|██████████| 11047/11047 [00:02<00:00, 3795.27it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4135.78it/s]
 72%|███████▏  | 194/271 [42:49<16:57, 13.22s/it]

rxndb num 297
failedrxn num 0
result_df 34
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.5.4.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '3.5.4.23', '1.14.13.61', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '2.1.1.-', '3.5.4.5', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.3.2.14', '3.3.2.14', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '3.5.4.20', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.5.4.1', '1.14.99', '1.14.99', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13;1.14.14', '1.14.13;1.14.14', '3.5.4.5', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.1', '1.14.14.1', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.8', '1.14.13.21', '1.14.13.21', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.35', '2.4.1.-', '2.4.1.-', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.5.4.1', '3.5.4.12', '3.5.4.13', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.4.15.6', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.176', '3.2.1.143', '3.2.1.143', '6.3.4.2', '3.5.4.13', '3.5.4.12', '3.5.4.5', '1.14.13.182', '1.14.13.182', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.5.4.14;3.5.4.5']
19
62
PREDNISONE
5

100%|██████████| 11047/11047 [00:04<00:00, 2286.99it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3955.12it/s]
 72%|███████▏  | 195/271 [43:04<17:13, 13.60s/it]

rxndb num 4112
failedrxn num 0
result_df 185

100%|██████████| 11047/11047 [00:02<00:00, 4271.81it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3796.58it/s]
 72%|███████▏  | 196/271 [43:17<16:46, 13.42s/it]

rxndb num 569
failedrxn num 0
result_df 52
['3.1.3.69', '3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.74', '3.1.3.74', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3.39', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.6.9', '3.1.6.10', '3.1.3.69', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.1.3.-;3.1.3.88', '3.1.3.79', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '3.1.3.85', '3.1.3.83', '3.1.3.92', '1.14.13.209', '1.14.13.209', '1.14.13.209', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.3.103', '3.1.3', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '1.14.14.133', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3', '3.1.6.c', '3.1.3.4', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '1.3.1', '3.1.6.14', '3.1.3.29', '3.1.3.29', '3.1.3.33;3.1.3.5', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.6.3', '3.1.3.68', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '3.2.1.154;3.2.1.26;3.2.1.80', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '3.2.1.65', '3.2.1.145;3.2.1.23', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '3.1.3.91', '3.6.1;3.6.1.-', '3.2.1.137;3.2.1.78', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.23;3.1.3.29;3.1.3.9', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.24', '3.1.3.12', '3.1.3.29', '3.1.3.-', '3.1.3.63', '3.1.3.63', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '3.1.3.45', '3.1.3.68', '3.1.3.M8', '3.1.3.105', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.1.3.58;3.1.3.9', '3.1.6.3', '3.2.1.3;3.2.1.58;3.2.1.59', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.1', '1.7.3.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '3.2.1.2', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.137', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '3.1.3.82', '1.3.99.-', '3.1.3.58;3.1.3.9', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '1.11.2.6', '1.11.2.6', '1.11.2.6', '3.1.3.76', '3.1.3.76', '4.2.3;4.2.3.1', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '3.1.3.1;3.1.3.75']
29
147
PRIMAQUINE PHOSPHATE
5

100%|██████████| 11047/11047 [00:02<00:00, 4154.67it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4188.48it/s]
 73%|███████▎  | 197/271 [43:28<15:56, 12.92s/it]

rxndb num 799
failedrxn num 0
result_df 61
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.4.3.22;1.4.3.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.4.3.21;1.4.3.22;1.4.3.4;1.4.3.6', '1.4.3.10;1.4.3.21;1.4.3.22;1.4.3.6', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.4.3.21;1.4.3.22;1.4.3.4;1.4.3.5;1.4.3.6;1.5.3.17', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.4.3.21;1.4.3.22;1.4.3.4;1.4.3.6;1.4.9.2;1.4.99.4', '1.14.13.59', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '5.4.3.3;5.4.3.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.61', '1.4.3.13;1.4.3.21;1.4.3.22', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.-.-', '1.14.13.187', '1.14.13.187', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.195;1.14.13.196', '1.14.13.196', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13.224', '1.14.13.224', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13', '1.4.3.4', '1.4.3', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '1.3.1', '1.14.13.235', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '1.14.13.M65', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.4.3.M4', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.2.3.1', '1.14.15.15', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.4.3.22', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-', '1.3.1;1.3.1.-', '2.4.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.4.3.-;1.4.3.M3', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.4.1.18', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '5.4.3.5', '5.4.3.5', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '5.4.3.3', '5.4.3.3', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.4.3.20', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.-.-', '1.14.-.-', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.13.88', '1.14.13.88', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.19.41;1.3.1.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.88', '1.14.13.88', '1.14.13.M66', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '3.2.1.87', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.15.5', '1.4.3.22', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.88', '1.14.13.88', '1.14.13.176', '1.14.13.176', '1.14.13.176', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.194', '3.2.1.143', '1.14.13.M64', '1.14.13.M64', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.3.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.182', '1.14.13.182', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.4.3.21;1.4.3.22;1.4.3.6', '1.4.3.21', '1.4.3.4', '1.4.3.21;1.4.3.4;1.4.3.6;1.4.9.2;1.4.99.4', '1.4.3.21;1.4.3.22;1.4.3.4', '1.4.3.22;1.4.3.6', '1.4.3.4']
30
107
PROCARBAZINE
5

100%|██████████| 11047/11047 [00:03<00:00, 3099.99it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4304.06it/s]
 73%|███████▎  | 198/271 [43:42<15:46, 12.96s/it]

rxndb num 40
failedrxn num 0
result_df 9
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '3.5.1.40', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.5.1;1.5.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.11.2.5', '1.11.2.5', '1.14.14', '1.14.14', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.13', '1.14.13', '1.14.18.1', '1.14.18.1', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.4.15.6', '3.4.19.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.11.2.6', '1.11.2.6']
12
19
PROMETHAZINE
5

100%|██████████| 11047/11047 [00:03<00:00, 3269.31it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3628.04it/s]
 73%|███████▎  | 199/271 [43:56<15:55, 13.27s/it]

rxndb num 76
failedrxn num 0
result_df 15
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.8', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13', '1.14.13.8', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13']
4
17
PYRIMETHAMINE
5

100%|██████████| 11047/11047 [00:02<00:00, 4550.38it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4376.65it/s]
 74%|███████▍  | 200/271 [44:07<15:07, 12.78s/it]

rxndb num 102
failedrxn num 0
result_df 28
['1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.5.4.1', '1.14.13.58', '1.14.13.58', '3.5.4.23', '3.8.1.7', '3.8.1.8', '3.5.4.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.97.1.-', '1.7.1.-', '1.7.1.-', '1.8.99.3;1.8.99.5', '1.8.99.3;1.8.99.5', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '3.5.4.5', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '3.5.4.-;3.5.4.26', '1.14.13.209', '1.14.13.209', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '3.5.4.20', '3.5.4.1', '3.5.4.3', '1.1.1.2', '1.1.1.2', '3.5.4.5', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '3.8.1.8', '3.5.4.-;3.5.99.-', '3.5.4.45;3.5.99.-', '1.14.14.1', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '3.5.4.11;3.5.4.24', '3.5.4.1', '3.5.4.12', '3.5.4.13', '1.14.13.9', '1.14.13.9', '1.3.98.-', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.6.6.8;1.7.1.7', '6.3.4.2', '3.5.4.13', '3.5.4.12', '3.5.4.5', '1.14.19.58', '3.5.4.14;3.5.4.5']
14
43
QUETIAPINE
5

100%|██████████| 11047/11047 [00:04<00:00, 2456.62it/s]
100%|██████████| 27873/27873 [00:05<00:00, 4779.32it/s]
 74%|███████▍  | 201/271 [44:20<14:51, 12.73s/it]

rxndb num 370
failedrxn num 0
result_df 39
['1.1.1.23', '3.1.3.15', '1.1.1.3', '1.1.1.3', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '3.1.3.-', '3.1.3.74', '1.1.1.1', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.1.3.23', '1.1.3.17', '3.1.3.39', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.1.1.191;1.1.1.2;1.1.1.21', '3.1.6.9', '3.1.6.10', '4.99.1.-', '1.1.3.39', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1;1.1.1.-;1.1.1.1', '1.14.13.15;1.14.15.15', '1.1.3.-;1.1.3.43', '3.1.3.-;3.1.3.88', '1.1.3.-;1.1.3.44', '1.1.3;1.1.3.-', '3.1.3.92', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3.101', '3.1.3.-', '1.1.3.-', '3.1.3;3.1.3.-', '3.1.3', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.1.1', '3.1.3', '1.1.1', '1.14.13', '1.14.13', '1.14.13.M9', '1.1.1', '1.1.1.1', '3.1.6.14', '3.1.3.29', '1.14.15.15', '3.1.3.33;3.1.3.5', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '3.1.3', '3.1.3', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.65', '3.1.3.91', '3.6.1;3.6.1.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.13.30', '3.1.3', '1.1.1.-', '1.1.1.136', '1.1.1.132', '3.1.3.29', '3.1.3.-', '1.1.1.23', '1.1.1.186', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.1.1.273', '1.1.1.273', '1.1.1.273', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.1.1.186', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.1.1.317', '1.1.1.317', '3.1.3.73', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.1.1.-;1.1.1.336', '1.1.1.22', '1.1.99.1', '3.1.3.M8', '1.1.1.273', '3.1.3.105', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.1.3.29', '3.2.1.87', '1.14.15.5', '1.14.15.5', '1.1.1.1', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.2.1.143', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '1.1.1.1;1.1.1.161', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '3.1.3.76', '1.1.1.1;1.1.1.190', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '1.1.1;1.1.1.1', '3.1.3.1;3.1.3.75']
20
104
QUINACRINE
5

100%|██████████| 11047/11047 [00:04<00:00, 2646.20it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3700.91it/s]
 75%|███████▍  | 202/271 [44:34<15:14, 13.25s/it]

rxndb num 658
failedrxn num 0
result_df 56
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.8.1.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '2.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '1.3.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.19', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.15.15', '1.14.15.15', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '1.14.-.-', '1.14.-.-', '1.3.1;1.3.1.-', '2.4.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.30', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.19.41;1.3.1.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.87', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.3.98.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.15.5', '1.14.15.5', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.176', '1.14.13.176', '1.14.13.176', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.194', '1.14.13.194', '3.2.1.143', '1.14.13.M64', '1.14.13.M64', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.3.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.19.58', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.19.59', '1.14.19.59', '1.14.19.60', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-']
21
70
QUINAPRIL
5

100%|██████████| 11047/11047 [00:03<00:00, 3471.57it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3714.57it/s]
 75%|███████▍  | 203/271 [44:48<15:01, 13.25s/it]

rxndb num 757
failedrxn num 0
result_df 82
['1.2.1.3;1.2.1.54', '1.2.1.-;1.2.1.99', '3.4.13.18;3.4.13.9', '1.1.1.23', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.1.5', '1.2.1.3', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.15', '4.1.1.30', '4.1.1.36', '1.2.1.24;1.2.1.5;1.2.1.88;1.5.1.12', '1.5.1.12', '3.1.1.23', '1.2.1.3;1.2.1.47', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.2.1.40', '3.1.1.70', '3.1.1.51', '1.14.13.72', '1.2.1.-;1.2.1.99', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.5.1;1.5.1.-', '1.5.1;1.5.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.-.-', '1.14.-.-', '1.2.1.-;1.2.1.M5', '1.2.1.-;1.2.1.83', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.3;6.3.-.-', '6.3.2', '6.3.2', '3.1.1;3.1.1.1;3.1.1.3', '1.14.13;1.14.13.-', '1.2.1;1.2.1.-', '3.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.1', '3.1.1.26', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.1.4', '3.1.1.23', '3.1.1.23', '3.1.1.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '4.1.1.M3', '4.1.1.M3', '1.2.1', '3.1.1', '1.1.1.-', '1.1.1.-', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '3.1.1.1;3.1.1.13;3.1.1.3', '3.1.1.1;3.1.1.3', '3.1.1.3', '3.1.1.3', '3.1.1.1', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '1.2.1.47', '3.1.1.1;3.1.1.2', '3.1.1.1;3.1.1.2', '3.1.1.1;3.1.1.2', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '1.2.1.19;1.2.1.3', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '3.4.21;3.4.21.62', '3.4.16.5;3.4.21;3.4.21.62', '6.3.1.2', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '6.3.4.2', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.2.3.1', '1.14.13.72', '3.4.11.5', '3.4.11.5', '3.4.11.5', '1.1.1.23;1.1.1.24', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '6.3.2.17', '6.3.2.17', '6.3.2.17', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '2.3.1.-', '3.1.1', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.1.5', '3.1.1.5', '1.14.13.30', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.23', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.2.1.31', '1.14.13.74', '1.14.13.74', '3.1.1.10', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.2.1.3', '2.-.-.-', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.72', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.79', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '2.3.1.-', '1.2.1.31', '1.2.1.95;1.2.1.z', '1.2.1.31', '1.2.1.3', '1.14.14.22;1.14.99.46', '1.2.1.3', '1.14.13.M76', '1.14.13.M76', '1.14.13.M76', '3.1.1.116', '1.2.1.101;1.2.1.ah', '1.2.1.-', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.2.1.14', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.87', '3.4.15.6', '3.4.15.6', '3.4.15.6', '3.4.19.9', '3.4.19.9', '3.4.19.9', '3.4.19.7', '3.4.19.7', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.2.1.-', '3.1.-.-', '3.1.-.-', '1.14.11.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.15.5', '1.14.15.5', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.2.1.70;6.1.1.17', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '3.1.1.5', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.184', '1.14.13.184', '1.14.13.194', '1.14.13.194', '3.1.1.101', '3.1.1.101', '3.1.1.101', '1.14.13', '1.14.13', '3.2.1.143', '3.5.1', '1.14.13.15', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.17.99.5', '1.17.99.5', '1.2.1.3;1.2.1.40', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '1.2.1', '1.2.1', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1;1.1.1.206', '3.1.1.3', '1.2.1;1.2.1.19;1.2.1.3', '1.2.1;1.2.1.-;1.2.1.19;1.2.1.3', '1.2.1.3;1.2.1.5', '1.2.1.5']
42
135
QUININE SULFATE
5

100%|██████████| 11047/11047 [00:02<00:00, 3887.68it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3100.99it/s]
 75%|███████▌  | 204/271 [45:02<15:18, 13.71s/it]

rxndb num 828
failedrxn num 0
result_df 70
['3.1.3.69', '3.1.3.15', '3.1.3.74', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.74', '3.1.3.74', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3.39', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.219', '3.1.6.9', '3.1.6.10', '1.1.1.219', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.1.1.234', '1.1.1.234', '1.14.13.61', '1.14.13.61', '3.1.3.69', '1.17.1.3', '1.17.1.3', '1.1.1.234', '1.17.1.3', '1.1.1.362', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.1.1.219', '1.1.1.219', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.1.3.-;3.1.3.88', '3.1.3.79', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '3.1.3.85', '1.1.1.349', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.3.2.14', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13.224', '1.14.13.224', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '3.1.3', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '1.3.1', '1.3.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.13.235', '1.1.1.362', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '1.1.1.348', '1.1.1.348', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.6.14', '3.1.3.29', '3.1.3.33;3.1.3.5', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '3.2.1.78', '3.2.1.78', '3.2.1.78', '1.1.1.184;1.1.1.209;1.1.1.213;1.1.1.50', '1.1.1.184', '3.1.3', '3.1.3', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.1.1.-', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.65', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '1.14.13.10', '1.14.13.10', '3.1.3.91', '3.6.1;3.6.1.-', '1.1.1.246;1.1.1.348', '1.1.1.219', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '2.4.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.24', '3.1.3.12', '3.1.3.29', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.3.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '2.-.-.-', '1.14.13.67;1.14.14.55', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '1.1.1.219', '3.1.3', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.14.13.88', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.45', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.68', '3.1.3.M8', '3.1.3.106;3.1.3.76', '1.14.13.-', '3.1.3.76', '3.1.3.105', '1.1.1.50', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.2.1.1', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.2', '1.14.11.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.11.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.88', '1.14.13.176', '1.14.13.176', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13', '3.1.3.73', '3.2.1.143', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.14.13.M64', '1.14.13.M64', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.1.1.112;1.1.1.184', '1.1.1.112;1.1.1.184;1.1.1.51', '1.1.1;1.1.1.112;1.1.1.184;1.1.1.213;1.1.1.50', '1.1.1.112;1.1.1.184;1.1.1.213;1.1.1.50;1.1.1.62;1.3.1.20', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.3.1', '1.3.1.-', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.422', '1.1.1.423', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1.422', '1.1.1.423', '3.1.3.76', '3.1.3.76', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '3.1.3.1;3.1.3.75']
34
170
RACECADOTRIL
5

100%|██████████| 11047/11047 [00:02<00:00, 4245.66it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3906.64it/s]
 76%|███████▌  | 205/271 [45:15<14:43, 13.39s/it]

rxndb num 633
failedrxn num 0
result_df 63
['3.5.1.94', '3.1.2.12;3.1.2.6', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '6.3.2.1', '3.5.1.92', '3.1.1.23', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '6.2.1.13', '3.1.2.13;3.1.2.6', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '6.2.1.9', '1.2.1.42', '1.1.1.118;1.1.1.47', '1.1.1.119;1.1.1.47', '1.1.1.34;1.1.1.88', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.5.1.22', '6.3.2.23', '6.3.1.2;6.3.1.6', '3.5.1.65', '6.3.2.20', '3.1.2.4;6.2.1.-', '3.1.1.70', '3.5.1.24;3.5.1.74', '3.5.1.24', '6.2.1.-', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.2.-', '3.1.2.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '6.2.1.-;6.2.1.40', '6.2.1.36', '6.3.2.36', '1.2.-.-', '1.2.-.-', '1.2.-.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.2.1.81', '3.1.2.29', '6.2.1.-;6.2.1.38', '3.1.2.30', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '3.5.1.-', '6.2.1.56;6.2.1.x', '6.2.1.3;6.2.1.41', '6.2.1.3;6.2.1.42', '6.3.2.44', '6.3.4.24', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.2;6.3.2.-', '6.3.2.18', '6.2.1.-;6.2.1.48', '3.5.1.97', '3.5.1.97', '3.5.1.97', '6.3.2;6.3.2.-', '6.3.2', '6.3.2', '6.3.2', '6.3.2', '6.3.2', '3.1.1;3.1.1.1;3.1.1.3', '6.2.1.3', '3.4.11.25', '6.2.1', '6.3.2.59', '6.3.2.59', '6.2.1', '1.2.1.10', '1.1.1', '1.2.1.42;1.2.1.n2', '3.1.1', '3.1.1.26', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.2', '3.1.1.4', '3.1.1.23', '3.1.1.23', '6.2.1', '6.2.1', '1.2.1.87', '1.2.1.87', '3.4.13', '6.3.2', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.1.84', '1.2.1.84', '1.2.1.84', '1.2.1.84', '1.2.1.84', '1.2.1.84', '1.2.1.84', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '6.2.1.60', '6.2.1.42', '1.2.1.84', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '3.1.1', '6.3.2', '6.2.1.26', '1.1.1.-', '1.8.3', '3.4', '3.1.2;3.1.2.20', '3.5.1.115', '3.1.2.26', '3.1.1.1;3.1.1.3', '3.1.2;3.1.2.1;3.1.2.2;3.1.2.20;3.1.2.23', '3.1.2.2', '3.1.2.2', '3.1.2;3.1.2.2;3.1.2.20', '3.5.1.23', '3.5.1.23', '3.1.1.3', '3.1.1.3', '3.5.1.23', '3.1.1.1', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.1.1.1;3.1.1.2', '3.1.1.1;3.1.1.2', '3.1.1.1;3.1.1.2', '1.2.1.-;1.2.1.57', '1.1.1.179;1.3.1.20', '1.1.1.88', '1.2.1.10', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '6.2.1.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '3.5.1.23', '3.4.21;3.4.21.62', '3.4.16.5;3.4.21;3.4.21.62', '3.5.1.23', '3.1.2;3.1.2.20;3.1.2.27;3.1.2.5', '3.2.1.78', '1.1.1.121', '1.1.1.47', '6.2.1.1', '6.3.2.18', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '3.4.11.5', '3.4.11.5', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '6.3.2.17', '6.3.2.17', '6.3.2.17', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '3.2.1.35', '2.3.1.-', '3.1.1', '1.14.-.-', '6.3.1.11', '3.5.1.-;3.5.1.78', '6.3.1.8;6.3.1.9', '1.1.1.34', '3.1.1.5', '2.8.3.25;3.1.2.2;3.1.2.27', '3.1.2.2;3.1.2.27', '3.5.1.4;3.5.1.99', '6.2.1.26', '3.1.2.2;3.1.2.20', '1.2.1.10;1.2.1.57', '6.2.1.1;6.2.1.17;6.2.1.2;6.2.1.3', '3.5.1.24;3.5.1.74', '3.1.2.4', '3.1.1.10', '6.3.1.9', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '3.5.1.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '6.3.1.13', '3.1.2.-;3.1.2.2;3.1.2.20', '2.3.1.-', '6.2.1.3', '6.3.1.10', '6.3.1.10', '3.5.1.90', '3.5.1.90', '1.2.1.10;1.2.1.57;1.2.1.87', '3.1.2;3.1.2.-;3.1.2.2;3.1.2.20', '3.1.2.2', '3.1.2.2', '6.2.1.3', '6.2.1.7', '2.3.1.5', '6.3.2.56;6.3.2.ad', '3.1.2', '6.2.1', '6.2.1', '6.2.1', '6.2.1.11', '3.5.1.60;3.5.1.99', '3.1.1.116', '6.2.1', '6.2.1.3', '3.5.1.60', '3.5.1.60;3.5.1.99', '3.5.1.99', '3.5.1.99', '3.5.1.60', '6.2.1.13', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.4', '1.1.1.120', '3.2.1.14', '3.2.1.14', '3.2.1.14', '6.2.1.7', '1.1.1.121', '1.14.-.-;1.14.13.-', '1.14.-.-', '3.2.1.154', '3.2.1.154', '3.2.1.154', '3.2.1.87', '3.4.15.6', '3.4.15.6', '3.4.15.6', '3.4.19.9', '3.4.19.9', '3.4.19.9', '3.4.19.5', '3.4.19.5', '3.4.19.5', '3.4.19.7', '3.4.19.7', '3.4.19.7', '6.2.1.3', '3.2.1.-', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.-.-', '3.1.-.-', '1.14.15.5', '2.5.1.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '3.1.1.5', '1.2.1.-', '1.2.1.-', '6.3.2;6.3.2.-', '3.1.1.101', '3.1.1.101', '3.1.1.101', '6.3.2', '3.2.1.143', '6.2.1.2', '6.2.1.2', '6.3.2', '6.3.2', '1.2.1.84', '4.2.1.140;4.2.1.39', '4.2.1.140;4.2.1.39', '4.2.1.140;4.2.1.39', '4.2.1.6', '4.2.1.6', '4.2.1.6', '6.3.2', '6.2.1.60', '6.3.2', '6.2.1.6', '1.2.1.-;1.2.1.10;1.2.1.57;1.2.1.87', '3.1.2;3.1.2.-;3.1.2.20;3.1.2.23', '3.1.2.-', '1.2.1.76', '3.1.2.2;3.1.2.3;6.2.1.4', '6.2.1.5', '6.2.1.7', '6.2.1.7', '6.2.1.3;6.2.1.7', '3.1.2.2', '3.1.2;3.1.2.-', '6.3.2.37', '6.2.1;6.2.1.1;6.2.1.2;6.2.1.3', '6.2.1.1;6.2.1.2', '6.2.1.2;6.2.1.30', '3.1.2.4', '3.1.2.4', '1.2.1.10;1.2.1.57', '2.3.1.226;2.3.1.31;2.3.3.10;2.3.3.13;3.1.2;3.1.2.1;3.1.2.17;3.1.2.2;3.1.2.20;3.1.2.23', '6.2.1.1;6.2.1.17', '6.3.1.10', '6.2.1.-', '3.1.2;3.1.2.2;3.1.2.20', '3.1.2;3.1.2.2;3.1.2.20', '3.1.2;3.1.2.2;3.1.2.20;3.1.2.22', '3.1.2.2', '3.1.2;3.1.2.1;3.1.2.2;3.1.2.20;3.1.2.23', '6.2.1.2;6.2.1.3', '6.2.1.2;6.2.1.3', '6.2.1;6.2.1.3', '6.2.1.3', '6.2.1.15', '6.2.1.18', '3.1.1.88', '3.1.2', '1.1.1.118', '1.1.1.120;1.1.1.179;1.1.1.359;1.1.1.360;1.1.1.47;1.1.1.48;1.3.1.20', '1.1.1.120', '6.2.1.28;6.2.1.7', '1.1.1.119', '2.3.1.9;3.1.2;3.1.2.-;3.1.2.2;3.1.2.20;3.1.2.22', '1.1.1.121;1.1.1.359;1.1.1.47;1.1.1.48', '1.1.1.121', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '6.3.2.58', '6.3.2.58', '3.6.1.18;3.6.1.9', '3.5.1.115', '3.5.1.51', '6.2.1.3', '6.2.1.3', '6.2.1.3', '6.2.1', '6.2.1', '6.2.1', '6.2.1.2', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1;1.1.1.206', '3.1.1.3', '1.2.1.80', '3.1.2;3.1.2.2;3.1.2.20;3.1.2.23', '3.5.1.46', '1.-.-.-', '6.2.1.14', '2.5.1;2.5.1.-;2.5.1.48']
40
199
RAMELTEON
5

100%|██████████| 11047/11047 [00:04<00:00, 2306.89it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4263.93it/s]
 76%|███████▌  | 206/271 [45:29<14:41, 13.57s/it]

rxndb num 626
failedrxn num 0
result_df 56
['3.5.1.94', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '6.3.2.1', '3.5.1.92', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '3.5.1.22', '6.3.2.23', '6.3.1.2;6.3.1.6', '3.5.1.65', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '6.3.2.20', '1.14.13.4', '1.14.13.4', '1.17.1.1', '1.17.1.1', '1.14.14.-;1.14.14.1', '3.5.1.24;3.5.1.74', '3.5.1.24', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '6.3.2.36', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.-.-', '1.3.1.95', '1.11.2.5', '1.11.2.5', '3.5.1.-', '6.3.2.44', '6.3.4.24', '1.14.13.209', '1.14.13.209', '1.14.-.-', '1.14.-.-', '2.1.1.-', '6.3.2.18', '6.3.2;6.3.2.-', '6.3.2', '6.3.2', '6.3.2', '1.14.13', '3.4.11.25', '1.14.13;1.14.13.-', '6.3.2.59', '6.3.2.59', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.4.13', '6.3.2', '1.3.3.6', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2', '3.4', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '3.5.1.115', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '1.14.15.15', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '3.5.1.23', '3.5.1.23', '1.14.13', '1.14.13', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '6.3.2.18', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-', '2.4.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.3.1.11', '3.5.1.-;3.5.1.78', '6.3.1.8;6.3.1.9', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.3.99.3', '3.5.1.4;3.5.1.99', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.5.1.24;3.5.1.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '6.3.1.9', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.-.-', '1.14.-.-', '3.5.1.-', '1.14.13.11', '1.14.13.11', '1.14.-.-;1.14.13.-', '6.3.1.13', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.3.1.10', '6.3.1.10', '3.5.1.90', '3.5.1.90', '6.3.2.56;6.3.2.ad', '3.5.1.60;3.5.1.99', '3.5.1.60', '3.5.1.60;3.5.1.99', '3.5.1.99', '3.5.1.99', '3.5.1.60', '1.14.13.9', '1.14.13.9', '3.4', '3.2.1.14', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-;1.14.13.-', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '3.2.1.87', '3.4.15.6', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.174', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.15.5', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.194', '6.3.2;6.3.2.-', '3.1.1.101', '1.14.13', '1.14.13', '6.3.2', '3.2.1.143', '6.3.2', '6.3.2', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '6.3.2', '6.3.2', '1.3.1.-;1.3.1.84', '6.3.2.37', '6.3.1.10', '1.14.13.-', '1.14.13.-', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '6.3.2.58', '6.3.2.58', '3.6.1.18;3.6.1.9', '3.5.1.115', '1.11.2.6', '1.11.2.6', '1.1.1;1.1.1.206', '1.14.13.127', '1.14.13.127', '3.5.1.46']
35
125
RAMIPRIL
5

100%|██████████| 11047/11047 [00:03<00:00, 3510.46it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3314.62it/s]
 76%|███████▋  | 207/271 [45:43<14:44, 13.82s/it]

rxndb num 1061
failedrxn num 0
result_df 129
['1.2.1.3;1.2.1.54', '1.2.1.-;1.2.1.99', '3.4.13.18;3.4.13.9', '1.1.1.23', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.1.5', '1.2.1.3', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.15', '4.1.1.30', '4.1.1.36', '1.2.1.24;1.2.1.5;1.2.1.88;1.5.1.12', '1.5.1.12', '3.1.1.23', '1.2.1.3;1.2.1.47', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.2.1.40', '3.1.1.70', '3.1.1.51', '1.14.13.72', '1.14.13.22', '1.2.1.-;1.2.1.99', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.5.1;1.5.1.-', '1.5.1;1.5.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.2.-.-', '1.2.-.-', '1.2.-.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.-.-', '1.14.-.-', '1.2.1.-;1.2.1.M5', '1.2.1.-;1.2.1.83', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.3;6.3.-.-', '6.3.2', '6.3.2', '3.1.1;3.1.1.1;3.1.1.3', '1.14.13;1.14.13.-', '1.3.1', '1.3.1', '1.2.1;1.2.1.-', '3.1.1', '3.1.1', '3.1.1.26', '1.14.14', '1.14.14', '1.14.14', '3.1.1.4', '3.1.1.23', '3.1.1.23', '3.1.1.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '1.2.1', '3.1.1', '1.1.1.-', '1.1.1.-', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '3.1.1.1;3.1.1.13;3.1.1.3', '3.1.1.1;3.1.1.3', '3.1.1.3', '3.1.1.3', '3.1.1.1', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '1.2.1.47', '1.14.15.15', '1.14.15.15', '3.1.1.1;3.1.1.2', '3.1.1.1;3.1.1.2', '3.1.1.1;3.1.1.2', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.2.1.19;1.2.1.3', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '3.4.21;3.4.21.62', '3.4.16.5;3.4.21;3.4.21.62', '6.3.1.2', '1.14.13', '1.14.13', '1.14.13', '6.3.4.2', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.2.3.1', '1.14.13.72', '3.4.11.5', '3.4.11.5', '3.4.11.5', '1.1.1.23;1.1.1.24', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '6.3.2.17', '6.3.2.17', '6.3.2.17', '1.5.1.12;1.5.99.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '3.2.1.35', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '2.3.1.-', '3.1.1', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.1.5', '3.1.1.5', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.23', '1.2.1.31', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '3.1.1.10', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.2.1.3', '2.-.-.-', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.72', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.78', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.-.-;1.14.13.-', '1.14.-.-;1.14.13.-', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.3.1.-', '1.2.1.31', '1.2.1.95;1.2.1.z', '1.2.1.31', '1.2.1.3', '1.14.14.22;1.14.99.46', '1.2.1.3', '1.14.13.M76', '1.14.13.M76', '1.14.13.M76', '3.1.1.116', '1.2.1.101;1.2.1.ah', '1.2.1.-', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.2.1.14', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-;1.14.13.-', '1.14.-.-;1.14.13.-', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.87', '3.4.15.6', '3.4.15.6', '3.4.15.6', '3.4.19.9', '3.4.19.9', '3.4.19.9', '3.4.19.5', '3.4.19.5', '3.4.19.5', '3.4.19.7', '3.4.19.7', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.-', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.2.1.-', '1.14.99.-', '1.14.99.-', '3.1.-.-', '3.1.-.-', '1.14.11.-', '1.14.11.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.15.5', '1.14.15.5', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.2.1.70;6.1.1.17', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '3.1.1.5', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '3.1.1.101', '3.1.1.101', '3.1.1.101', '3.2.1.143', '3.5.1', '1.14.13.15', '1.3.99.-', '1.3.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.2.1.3;1.2.1.40', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.6.1.18;3.6.1.9', '1.2.1', '1.2.1', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1;1.1.1.206', '3.1.1.3', '1.2.1;1.2.1.19;1.2.1.3', '1.2.1;1.2.1.88;1.5.1.12;1.5.99.8', '1.2.1;1.2.1.-;1.2.1.19;1.2.1.3', '1.2.1.3;1.2.1.5', '1.2.1.5']
46
142
RANITIDINE
5

100%|██████████| 11047/11047 [00:02<00:00, 4612.08it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4217.06it/s]
 77%|███████▋  | 208/271 [45:55<13:54, 13.24s/it]

rxndb num 130
failedrxn num 0
result_df 21
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '2.1.1.49', '2.1.1.49', '2.1.1.49', '2.1.1.49', '1.14.13.58', '1.14.13.58', '1.14.13.29', '1.14.13.29', '2.1.1.115;2.1.1.140', '2.1.1.115;2.1.1.140', '2.1.1.115;2.1.1.140', '2.1.1.115;2.1.1.140', '2.1.1.115', '2.1.1.115', '2.1.1.115', '2.1.1.115', '2.1.1;2.1.1.115', '2.1.1;2.1.1.115', '2.1.1;2.1.1.115', '2.1.1;2.1.1.115', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '2.1.1.115', '2.1.1.115', '2.1.1.115', '2.1.1.115', '1.14.13.209', '1.14.13.209', '2.1.1.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '2.1.1.324', '2.1.1.324', '2.1.1.324', '2.1.1.324', '2.1.1.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '2.1.1;2.1.1.-', '2.1.1;2.1.1.-', '2.1.1;2.1.1.-', '2.1.1;2.1.1.-', '2.1.1.-;2.1.1.340', '2.1.1.-;2.1.1.340', '2.1.1.-;2.1.1.340', '2.1.1.-;2.1.1.340', '2.1.1', '2.1.1', '2.1.1', '2.1.1', '1.14.13.8', '1.14.13', '1.14.13', '1.14.13.25', '1.14.13.25', '1.14.18.1', '1.14.18.1', '3.4.11.5', '1.14.14.1', '2.1.1.115', '2.1.1.115', '2.1.1.115', '2.1.1.115', '2.1.1;2.1.1.-', '2.1.1;2.1.1.-', '2.1.1;2.1.1.-', '2.1.1;2.1.1.-', '2.1.1.49', '2.1.1.49', '2.1.1.49', '2.1.1.49', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.14.22;1.14.99.46', '2.1.1.337', '2.1.1.337', '2.1.1.337', '2.1.1.337', '2.1.1.345', '2.1.1.345', '2.1.1.345', '2.1.1.345', '3.4.15.6', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '2.5.1.-', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.49', '2.1.1.49', '2.1.1.49', '2.1.1.49', '2.1.1.103', '2.1.1.103', '2.1.1.103', '2.1.1.103', '1.-.-.-', '2.5.1;2.5.1.-;2.5.1.48']
10
38
RANOLAZINE
5

100%|██████████| 11047/11047 [00:04<00:00, 2420.34it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4025.76it/s]
 77%|███████▋  | 209/271 [46:09<13:51, 13.42s/it]

rxndb num 1134
failedrxn num 0
result_df 83
['3.1.3.69', '3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.1.1.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.27', '3.1.3.3', '3.1.3.74', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.1.1;1.1.1.10', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.137', '1.1.1.137;1.1.1.405', '3.1.3.39', '1.1.1.148', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.3.16', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '3.1.3.40', '3.1.6.9', '3.1.6.10', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.1.1;1.1.1.-', '1.1.1.230', '3.4.22.40;3.5.1.72', '1.-.-.-;1.1.1.342', '1.1.1.62', '1.1.1.62', '1.1.1.53', '1.1.1.50', '1.1.1.53', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.166', '1.1.1.263', '3.1.3.69', '1.1.1.297', '1.1.1;1.1.1.-', '1.1.1.364', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '3.1.3.76', '1.14.13.-', '2.1.1.-', '2.1.1.-', '1.14.-.-', '1.1.1.-', '1.1.1;1.1.1.-;1.1.1.50', '1.1.1.292', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.162', '1.1.1.-', '1.1.1.-', '1.1.1.-;1.1.1.341;4.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.-;1.1.1.329', '3.1.3.-;3.1.3.88', '1.1.1.297', '1.1.1.-', '1.1.1.239;1.1.1.62', '1.1.1.213', '1.1.1.209;1.1.1.213;1.1.1.357', '1.1.1.62', '3.1.3.79', '1.1.3.-;1.1.3.45', '1.1.1.297', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.1.1.301', '3.1.3.85', '3.1.3.83', '1.1.1.-;1.1.1.329', '1.1.1.335', '1.1.1.339;1.1.1.344', '1.1.1.355', '1.1.1.356', '1.1.1.356', '1.1.1.361', '3.1.3.92', '1.1.1.364', '1.1.1.367', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '6.3.1.18', '1.1.1.374', '1.1.1.385', '1.1.1.389', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.1.1.393', '3.3.2.14', '3.1.3.101', '3.1.3.-', '1.1.1.-', '1.1.1.-', '1.1.1.-', '3.1.3;3.1.3.-', '1.1.1.-', '1.1.1.402', '1.1.1.14;1.1.1.162;1.1.1.403', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '3.1.3.103', '3.5.1.123', '1.1.1.251', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.1.1.395', '1.1.1.-;1.1.1.395', '1.1.1', '1.1.3.11', '3.1.3', '1.14.13', '3.1.3.-', '1.1.1;1.1.1.-', '3.1.3;3.1.3.-', '1.1.1.201', '1.1.1.-;1.1.1.50;1.1.1.52', '1.1.1.391', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.1.1.102', '1.1.1.-;1.1.1.393', '1.1.1.145', '1.14.14.133', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.1.1', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.1.1', '1.1.1', '3.1.3', '3.1.3.4', '1.1.1.201', '3.1.3.4', '1.1.1', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1', '1.1.1.M2', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.M11', '1.1.1.M11', '1.1.1.392', '1.1.1.393', '1.1.1.52', '1.1.1.391', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.52', '1.1.1.391', '1.1.1.392;1.1.1.50;1.1.1.52', '1.1.1.392', '1.1.1.393', '1.1.1.393', '3.5.1', '1.1.1.M28', '1.1.1.14;1.1.1.M29', '1.1.1', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1.140', '1.1.1.123', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.2;1.1.1.213;1.1.1.239;1.1.1.62;1.3.1.20', '1.1.1.159', '1.1.1.218', '3.1.6.14', '1.1.1.218', '1.1.1.1', '1.1.1.188;1.1.1.213;1.1.1.50', '1.1.1.1', '3.4.11.3;3.4.11.6;3.4.22.40', '3.1.3.29', '3.1.3.29', '2.3.2.2;3.4.11.10;3.4.19.3', '1.1.1.149', '1.1.1.145', '1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50;1.3.1.20', '1.1.1.140;1.1.1.17', '3.1.3.33;3.1.3.5', '1.1.1.133', '1.1.1.239;1.1.1.51', '1.1.1.239;1.1.1.51', '1.1.1.239', '1.1.1.184', '1.1.1;1.1.1.184;1.1.1.62', '1.1.1.184;1.1.1.2;1.1.1.62', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.213;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.50', '3.4.21.4;3.4.22;3.4.22.1', '1.1.1.51', '1.14.13.126;1.14.15.16', '1.1.1.292', '1.1.1', '3.3.2.6;3.4.11.10;3.4.11.15', '1.1.1.209', '1.1.1.209', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.1.1', '1.1.1.357;1.1.1.50', '1.1.1.210;1.1.1.357', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '1.14.14.55', '3.2.1.78', '1.1.1.184;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.50', '1.1.1.184;1.1.1.50', '1.1.1;1.1.1.10;1.1.1.405', '1.1.1.10', '3.1.3', '3.1.3', '1.1.1.146;1.1.1.159;1.1.1.50', '3.1.6.3', '1.1.99.13', '3.1.3.68', '1.1.1.162', '1.1.1.-', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.133', '1.14.15.4', '1.14.15.6', '1.1.1.297', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '3.4.11.5', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.55', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.82', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '1.1.1.-', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.145;3.2.1.23', '3.2.1.110', '3.2.1.35', '1.14.14.1', '1.1.1.125;1.1.1.127', '3.1.3.91', '3.6.1;3.6.1.-', '3.2.1.137;3.2.1.78', '1.1.1.104', '1.1.1.104', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '1.1.1.239;1.1.1.51', '1.1.1;1.1.1.239;1.1.1.62;1.1.1.64', '2.4.1.-', '2.4.1.-', '1.1.1.104', '1.14.-.-', '1.14.-.-', '1.1.1.-;1.1.1.146', '1.1.1;1.1.1.-;1.1.1.146;1.1.1.51', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.2;1.1.1.209;1.1.1.21;1.1.1.213;1.1.1.50;1.3.1.20', '3.1.3.23;3.1.3.29;3.1.3.9', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.13.-;1.14.13.95;1.14.18.8', '3.1.3.27', '1.1.1.166;1.1.1.24;1.1.1.282', '1.1.1.14;1.1.1.56', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.24', '1.1.1.133', '3.1.3.12', '1.1.1.14;1.1.1.9', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '1.1.1.271', '1.1.1.124;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.1.3.29', '1.1.1;1.1.1.148;1.1.1.209', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.3.-', '1.1.1.134;1.1.1.344', '1.1.1.159;1.1.1.50', '1.1.1.176', '1.1.1.206', '1.1.1.236', '1.1.1.241', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.1.1.174', '1.1.1.135;1.1.1.187', '1.1.1.187;1.1.1.281', '1.1.1.135;1.1.1.187', '1.1.1.187;1.1.1.281', '1.1.1.238', '1.14.13.74', '1.1.1.146', '1.1.1.213;1.1.1.52', '3.1.3.63', '3.1.3.63', '1.1.1.152;1.1.1.184;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1.184;1.1.1.209;1.1.1.213;1.1.1.50', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.1.1.213;1.1.1.50', '1.1.1.50', '1.1.1.209;1.1.1.50', '1.1.1.213;1.1.1.50;1.1.1.51', '1.1.1.149;1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '2.-.-.-', '1.1.1.266', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.1.1.213;1.1.1.277;1.1.1.50', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.1.1.282', '1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.278', '1.14.13.94', '1.14.13.96', '1.14.13.97', '1.14.13.140', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.1.1.210;1.1.1.357;1.1.1.50;1.1.1.51', '1.14.13.-', '1.1.1.1;1.1.1.391', '1.1.1.-;1.1.1.146;1.1.1.209;1.1.1.213;1.1.1.392;1.1.1.50', '3.1.3.73', '1.1.1;1.1.1.-', '3.1.3', '3.1.3', '1.1.1.159', '1.1.1.-', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '1.1.1;1.1.1.10', '1.1.1.153', '1.1.1.10;1.1.1.14;1.1.1.15', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.213;1.1.1.50;1.1.1.51;1.1.1.53', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.45', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.1.1.-;1.1.1.M53', '1.14.13;1.14.13.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.68', '1.1.1.201', '1.1.1.425', '3.1.3.M8', '1.1.1', '1.1.1.104', '1.1.1.266', '3.1.3.106;3.1.3.76', '1.1.1.367', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.1.1.14', '1.1.1', '1.1.1.10', '1.1.3.10', '1.1.3.10', '3.1.3.58;3.1.3.9', '3.1.6.3', '3.2.1.14', '3.2.1.37', '3.2.1.37', '3.2.1.55', '3.2.1.55', '3.2.1.3;3.2.1.58;3.2.1.59', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.1.1.297', '1.1.1.297', '1.14.13.126', '3.2.1.116', '3.2.1.154', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.2.1.87', '3.4.15.6', '3.4.19.7', '3.2.1.1', '1.1.1.-', '1.7.3.-', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.-', '1.14.13.-', '1.14.13.-', '3.2.1.2', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '3.2.1.137', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.96', '1.1.1.-', '3.1.3.27', '1.14.13.140', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.183', '1.14.13.184', '3.1.1.101', '3.1.3', '3.1.3.73', '3.2.1.143', '3.2.1.143', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.14.13.M64', '1.1.1.M51', '3.1.3.73', '1.1.1.M51', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.106', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.1.1.184;1.1.1.189', '3.1.3.82', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1;1.1.1.51;1.1.1.62', '1.14.13.-;1.14.15.6', '1.1.1.271', '1.1.1.271', '1.1;1.1.1;1.1.1.209;1.1.1.213', '1.1.1.1', '1.1.99.13', '3.1.3.58;3.1.3.9', '1.17.99.5', '1.1.1;1.1.1.184;1.1.1.210;1.1.1.50', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.2;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.3.1.20', '1.1.1.184;1.1.1.357', '1.14.13.97', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '2.6.1.114', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.1.1.367', '1.1.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.395', '1.1.1', '1.1.1.146', '1.1.1.64', '1.1.1.146', '1.1.1.146', '1.1.1.239', '1.1.1.62', '1.1.1.238', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1.206', '1.1.1;1.1.1.206', '3.1.3.76', '3.1.3.76', '1.1.1.102', '4.2.3;4.2.3.1', '1.1.1.213;1.1.1.50', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '3.1.3.1;3.1.3.75']
47
311
REBAMIPIDE
5

100%|██████████| 11047/11047 [00:03<00:00, 3595.88it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3689.85it/s]
 77%|███████▋  | 210/271 [46:23<13:42, 13.48s/it]

rxndb num 824
failedrxn num 0
result_df 133
['1.2.1.-;1.2.1.99', '1.1.1.23', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.2.1.3', '3.5.1.32', '1.14.13.15', '4.1.1.30', '4.1.1.36', '1.2.1.24;1.2.1.5;1.2.1.88;1.5.1.12', '1.5.1.12', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.6', '3.5.1.40', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.12.9', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.99.2', '1.14.99.2', '1.2.1.40', '3.8.1.7', '1.14.12.16', '1.14.13.61', '1.14.13.61', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.14.13.180', '1.2.1.-;1.2.1.99', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.2.1.-;1.2.1.M5', '1.2.1.-;1.2.1.83', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.1.1.203', '1.1.1.203', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.3;6.3.-.-', '6.3;6.3.-.-', '6.3;6.3.-.-', '6.3;6.3.-.-', '1.1.1.203', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.1', '1.14.19', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '4.1.1.M3', '4.1.1.M3', '1.2.1', '1.14.12.16', '1.1.1.-', '3.5.1;3.5.1.-', '1.1.1.179;1.3.1.20', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '6.3.1.2', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '6.3.4.2', '1.1.1.47', '3.8.1.6', '3.8.1.6', '3.8.1.6', '3.8.1.6', '3.8.1.6', '6.3.2.14', '6.3.2.14', '1.1.1.122', '1.14.12.9', '1.14.12.9', '1.14.12.9', '1.14.12.9', '1.14.12.9', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.2.3.1', '1.14.13.-', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.-', '3.4.11.5', '3.4.11.5', '3.4.11.5', '1.1.1.23;1.1.1.24', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.82', '3.2.1.15;3.2.1.82', '3.2.1.15;3.2.1.82', '6.3.2.17', '6.3.2.17', '6.3.2.17', '1.5.1.12;1.5.99.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.18', '3.2.1.31', '3.2.1.31', '3.2.1.31', '3.2.1.35', '3.2.1.35', '3.2.1.35', '1.14.13.10', '1.14.13.10', '6.3.2.12;6.3.2.17', '1.1.1.23', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.2.1.31', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.2.1.3', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.2.1.31', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.2.1.95;1.2.1.z', '1.2.1.31', '1.2.1.3', '1.14.14.22;1.14.99.46', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.2.1.101;1.2.1.ah', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.2.1.14', '1.1.1.121;1.1.1.175', '1.1.1.121', '1.1.1.179', '1.1.1.179', '3.4.15.6', '3.4.15.6', '3.4.15.6', '3.4.19.9', '3.4.19.9', '3.4.19.9', '3.4.19.5', '3.4.19.5', '3.4.19.5', '3.4.19.7', '3.4.19.7', '3.4.19.7', '1.3.98.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '3.2.1.15', '3.2.1.15', '3.2.1.15', '4.2.2.2', '4.2.2.2', '4.2.2.2', '1.2.1.70;6.1.1.17', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.176', '1.14.13.176', '1.14.13', '3.5.1', '1.14.13.15', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.19.58', '1.2.1.3;1.2.1.40', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.2.1.29;1.2.1.3;1.2.1.5', '1.2.1.5', '1.2.1.3;1.2.1.5', '1.2.1.5', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.2.1.3;1.2.1.5', '1.2.1.5', '1.2.1.29;1.2.1.5;1.2.1.53', '1.2.1;1.2.1.88;1.5.1.12;1.5.99.8', '1.2.1.5', '1.2.1.3;1.2.1.5', '1.2.1.5']
38
125
REPAGLINIDE
5

100%|██████████| 11047/11047 [00:02<00:00, 4267.58it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3873.49it/s]
 78%|███████▊  | 211/271 [46:35<13:13, 13.22s/it]

rxndb num 1112
failedrxn num 0
result_df 127
['3.5.1.94', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '6.3.2.1', '3.5.1.92', '1.2.3.1;1.2.3.8', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.2.1.67', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.5.1.22', '4.1.1.-', '6.3.2.23', '4.1.1.58', '6.3.1.2;6.3.1.6', '3.5.1.65', '6.3.2.20', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.19', '1.14.13.19', '3.5.1.24;3.5.1.74', '3.5.1.24', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.2.3.9', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.14.13.180', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.3.1.-', '1.3.1.-', '1.3.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.3.2.36', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.-.-', '1.14.-.-', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '3.5.1.-', '6.3.2.44', '6.3.4.24', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '6.3.2.18', '6.3.2;6.3.2.-', '6.3.2', '6.3.2', '6.3.2', '1.14.-.-', '1.14.-.-', '3.4.11.25', '6.3.2.59', '6.3.2.59', '1.1.1.415;1.1.1.ee', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.2.1.29', '3.4.13', '6.3.2', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2', '3.4', '4.1.1.-;4.1.1.98', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '4.1.1;4.1.1.-', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '4.1.1;4.1.1.-', '3.5.1.115', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '3.5.1.23', '3.5.1.23', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.3.1;1.2.3.8', '1.14.14.1', '1.2.1.3', '1.2.1.3', '3.2.1.78', '1.14.14.1', '1.14.14.1', '1.14.14.1', '6.3.2.18', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.-', '1.14.13.-', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '6.3.2.17', '6.3.2.17', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-', '1.14.-.-', '2.4.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.3.1.11', '3.5.1.-;3.5.1.78', '6.3.1.8;6.3.1.9', '1.14.13.15;1.14.15.15', '1.14.13.15;1.14.15.15', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.5.1.4;3.5.1.99', '1.14.13.30', '1.14.13.30', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.5.1.24;3.5.1.74', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '6.3.1.9', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.3.1.69', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.138', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.19.41;1.3.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.5.1.-', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.-.-;1.14.13.-', '1.14.-.-;1.14.13.-', '6.3.1.13', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '6.3.1.10', '6.3.1.10', '3.5.1.90', '3.5.1.90', '1.1.1.415', '6.3.2.56;6.3.2.ad', '1.14.14.22;1.14.99.46', '3.5.1.60;3.5.1.99', '4.1.1.98', '3.5.1.60', '3.5.1.60;3.5.1.99', '3.5.1.99', '3.5.1.99', '4.1.1.118', '3.5.1.60', '1.2.3.1', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.4', '3.2.1.14', '3.2.1.14', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.87', '3.4.15.6', '3.4.15.6', '3.4.19.9', '3.4.19.9', '3.4.19.7', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.188', '1.14.99.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.3.1.-', '1.3.1.-', '1.3.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.15.5', '1.14.15.5', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.138', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.194', '1.14.13.194', '6.3.2;6.3.2.-', '3.1.1.101', '3.1.1.101', '1.14.13', '6.3.2', '3.2.1.143', '6.3.2', '6.3.2', '6.3.2', '6.3.2', '6.3.2.37', '6.3.1.10', '1.3.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '6.3.2.58', '6.3.2.58', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.5.1.115', '1.14.13.M82', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1;1.1.1.206', '4.1.1;4.1.1.-', '3.5.1.46']
41
151
RESERPINE
5

100%|██████████| 11047/11047 [00:05<00:00, 1943.35it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4073.79it/s]
 78%|███████▊  | 212/271 [46:50<13:34, 13.81s/it]

rxndb num 913
failedrxn num 0
result_df 113
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.1.23', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.118;1.1.1.47', '1.1.1.119;1.1.1.47', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '3.1.1.70', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.1.1.173;1.1.1.378', '3.1.1.51', '3.1.1.60', '1.14.-.-', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.14.13.180', '3.1.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.1.95', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.13.-', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.1.1.203', '1.1.1.203', '1.1.1.363;1.1.1.388', '1.1.1.390', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.3.2.14', '3.3.2.14', '3.3.2.14', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '3.1.1.102', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.1.1.116', '1.1.1.359;1.1.1.376;1.1.1.46', '3.1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.1.1.203', '6.3.2', '6.3.2', '3.1.1;3.1.1.1;3.1.1.3', '1.3.1', '1.3.1', '1.1.1', '1.1.1.415;1.1.1.ee', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.1', '3.1.1', '3.1.1.95', '3.1.1.26', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13;1.14.13.-', '3.1.1.4', '3.1.1.23', '3.1.1.23', '3.1.1.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.-;1.1.1.377;1.1.1.378', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.1', '1.1.1.-', '1.1.1', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.1.1;3.1.1.13;3.1.1.3', '3.1.1.1;3.1.1.3', '3.1.1.3', '3.1.1.3', '3.1.1.1', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '1.1.1.179;1.3.1.20', '1.1.1.179;1.3.1.20', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '3.4.21;3.4.21.104;3.4.21.42', '3.4.21;3.4.21.62', '3.4.16.5;3.4.21;3.4.21.62', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '3.2.1.78', '3.2.1.78', '3.2.1.78', '3.2.1.78', '3.2.1.78', '1.1.1.121', '1.1.1.121', '1.1.1.47', '1.1.1.122', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.-', '3.4.11.5', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.82', '3.2.1.15;3.2.1.82', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.31', '3.2.1.31', '3.2.1.35', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '2.3.1.-', '3.1.1', '2.4.1.-', '2.4.1.-', '2.4.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.1.5', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '3.1.1.10', '1.1.1.113', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '2.-.-.-', '2.-.-.-', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.1.1.107;1.1.1.122', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '2.3.1.-', '1.14.13.88', '1.14.13.88', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.88', '1.14.13.88', '1.1.1.363;1.1.1.388;1.1.1.47;1.1.1.49', '1.1.1.415', '3.1.1.116', '1.1.1.376', '1.1.1.420', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.1.1.120', '3.2.1.14', '3.2.1.14', '1.1.1.121;1.1.1.175', '1.1.1.121', '1.1.1.179', '1.1.1.179', '1.1.1.46', '1.1.1.46', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.1.1.121', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.4.15.6', '3.4.15.6', '3.1.1.1', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.-.-', '3.1.-.-', '1.13.99.3', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.15', '3.2.1.15', '4.2.2.2', '4.2.2.2', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '6.2.1.3', '6.2.1.3', '6.2.1.3', '6.2.1.3', '1.1.1.117', '1.1.1.117', '1.1.1.117', '1.1.1.117', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '3.1.1.5', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.46', '1.1.1.46', '1.14.13.88', '1.14.13.88', '1.14.13.176', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '3.1.1.101', '3.1.1.101', '1.14.13', '3.2.1.143', '3.2.1.143', '3.2.1.143', '3.2.1.143', '3.2.1.143', '3.2.1.143', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '3.1.1.1;3.1.1.84', '1.1.1.363;1.1.1.49', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.182', '1.14.13.182', '1.13.99.3', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.1.1.118', '1.1.1.120;1.1.1.179;1.1.1.359;1.1.1.360;1.1.1.47;1.1.1.48;1.3.1.20', '1.1.1.120', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.1.1.119', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.1.1.121;1.1.1.359;1.1.1.47;1.1.1.48', '1.1.1.121', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.1.1.363;1.1.1.47;1.1.1.49', '1.1.1.49', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1.424', '3.1.1.102']
38
152
RILUZOLE
5

100%|██████████| 11047/11047 [00:03<00:00, 3115.87it/s]
100%|██████████| 27873/27873 [00:05<00:00, 4728.40it/s]
 79%|███████▊  | 213/271 [47:03<12:49, 13.28s/it]

rxndb num 67
failedrxn num 0
result_df 15
['1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.61', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.1.1.2', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.2.1.3', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.143', '1.14.13.236', '1.14.13.236', '1.14.13.236', '1.14.13.182', '1.14.13.182', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9']
10
24
RIMANTADINE
5

100%|██████████| 11047/11047 [00:02<00:00, 3696.02it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4135.73it/s]
 79%|███████▉  | 214/271 [47:15<12:30, 13.16s/it]

rxndb num 50
failedrxn num 0
result_df 14
['1.4.3.12', '3.10.1.2', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.3.1', '1.3.1', '1.14.15.15', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97']
7
12
RISPERIDONE
5

100%|██████████| 11047/11047 [00:03<00:00, 3363.18it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4033.01it/s]
 79%|███████▉  | 215/271 [47:28<12:14, 13.12s/it]

rxndb num 255
failedrxn num 0
result_df 41
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13', '1.14.13', '1.14.13;1.14.14', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.14', '3.4.15.6', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.13.99.3', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13', '1.14.13', '1.13.99.3', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '2.6.1.114', '1.14.14', '1.14.14', '1.14.14']
17
46
RITONAVIR
5

100%|██████████| 11047/11047 [00:03<00:00, 3167.25it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3402.98it/s]
 80%|███████▉  | 216/271 [47:44<12:36, 13.75s/it]

rxndb num 619
failedrxn num 0
result_df 66
['3.5.1.94', '3.1.3.69', '3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '3.1.3.-', '6.3.2.1', '3.1.3.74', '3.1.3.27', '3.5.1.92', '3.1.3.74', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '3.1.3.39', '1.1.3.16', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.5.1.22', '6.3.2.23', '6.3.1.2;6.3.1.6', '3.5.1.65', '6.3.2.20', '3.1.6.9', '3.1.6.10', '3.5.1.24;3.5.1.74', '3.5.1.24', '1.1.1.53', '1.1.1.50', '1.1.1.53', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '3.1.3.69', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.-', '1.1.1;1.1.1.-;1.1.1.50', '1.-.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.-;1.1.1.329', '3.1.3.-;3.1.3.88', '3.1.3.79', '6.3.2.36', '3.1.3.85', '1.14.-.-', '1.14.-.-', '1.1.1.-;1.1.1.329', '1.1.1.335', '3.1.3.92', '3.5.1.-', '1.1.1.374', '6.3.2.44', '6.3.4.24', '1.1.1.389', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.224', '1.14.13.224', '1.1.1.395', '1.1.1.-;1.1.1.395', '6.3.2.18', '3.1.3.3', '3.1.3', '6.3.2;6.3.2.-', '6.3.2', '6.3.2', '3.1.3.-', '1.1.1.201', '1.1.1.-;1.1.1.50;1.1.1.52', '1.1.1.391', '6.3.2', '3.1.3;3.1.3.-', '3.4.11.25', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.1.1.102', '1.1.1.145', '6.3.2.59', '6.3.2.59', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.13.235', '1.1.1', '1.1.1', '3.1.3', '3.4.13', '6.3.2', '1.1.1.201', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.392', '1.1.1.393', '1.1.1.52', '1.1.1.391', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.52', '1.1.1.391', '1.1.1.392;1.1.1.50;1.1.1.52', '1.1.1.392', '1.1.1.393', '1.1.1.393', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2', '3.4', '3.5.1.115', '3.5.1.23', '3.5.1.23', '3.5.1.23', '1.1.1.159', '3.1.6.14', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.1.3.29', '1.1.1.149', '3.1.3.33;3.1.3.5', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.213;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.50', '3.5.1.23', '3.5.1.23', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.2.1.78', '3.2.1.78', '3.2.1.78', '3.2.1.78', '3.2.1.78', '3.2.1.78', '3.1.3', '3.1.3', '1.1.1.146;1.1.1.159;1.1.1.50', '1.1.99.13', '3.1.3.68', '6.3.2.18', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.4.11.5', '3.4.11.5', '3.4.11.5', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '3.2.1.35', '1.1.1.125;1.1.1.127', '3.1.3.91', '3.6.1;3.6.1.-', '1.14.-.-', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '6.3.1.11', '3.5.1.-;3.5.1.78', '6.3.1.8;6.3.1.9', '1.1.1.-;1.1.1.146', '1.1.1;1.1.1.-;1.1.1.146;1.1.1.51', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.27', '3.5.1.4;3.5.1.99', '3.1.3', '3.1.3.24', '3.1.3.12', '3.1.3.29', '3.1.3.-', '1.1.1.159;1.1.1.50', '1.1.1.176', '3.5.1.24;3.5.1.74', '1.1.1.206', '1.1.1.236', '1.1.1.238', '1.14.13.74', '1.14.13.74', '1.14.13.74', '6.3.1.9', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.1.1.50', '1.1.1.209;1.1.1.50', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.94', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.5.1.-', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '6.3.1.13', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3', '3.1.3', '1.1.1.159', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.1.1.153', '1.1.1.-;1.1.1.M53', '6.3.1.10', '6.3.1.10', '3.5.1.90', '3.5.1.90', '6.3.2.56;6.3.2.ad', '1.1.1.201', '3.1.3.M8', '1.1.1', '3.5.1.60;3.5.1.99', '3.5.1.60', '3.5.1.60;3.5.1.99', '3.5.1.99', '3.5.1.99', '3.1.3.105', '3.5.1.60', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.4', '1.1.1', '3.2.1.14', '3.2.1.14', '3.2.1.14', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.4.15.6', '3.4.15.6', '3.4.15.6', '3.4.19.5', '3.4.19.5', '3.4.19.5', '3.4.19.7', '3.4.19.7', '3.4.19.7', '3.2.1.1', '3.2.1.-', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.-', '3.2.1.2', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.1.1.-', '3.1.3.27', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.3.2;6.3.2.-', '1.14.13', '1.14.13', '6.3.2', '3.1.3.73', '3.2.1.143', '3.1.3.73', '6.3.2', '6.3.2', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.14.13.M64', '1.1.1.M51', '3.1.3.73', '1.1.1.M51', '3.1.3.73', '6.3.2', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '6.3.2', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '6.3.2.37', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '6.3.1.10', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.1.99.13', '1.17.99.5', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3', '6.3.2.58', '6.3.2.58', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '3.5.1.115', '1.1.1.395', '1.1.1.238', '1.1.1.206', '1.1.1;1.1.1.206', '3.1.3.76', '1.1.1.102', '4.2.3;4.2.3.1', '3.5.1.46', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75']
34
197
RIVASTIGMINE TARTRATE
5

100%|██████████| 11047/11047 [00:02<00:00, 4384.07it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4377.25it/s]
 80%|████████  | 217/271 [47:55<11:44, 13.05s/it]

rxndb num 323
failedrxn num 0
result_df 34
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.5.1.27', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '3.1.1.1', '3.1.1.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '2.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.8', '3.1.1;3.1.1.1;3.1.1.14;3.1.1.2;3.1.1.7;3.1.1.74;3.1.1.88;3.1.2.12;3.1.2.2', '3.1.1;3.1.1.1;3.1.1.2', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.1;3.1.1.1;3.1.1.2;3.1.1.74;3.1.1.88;3.1.2.12', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.35', '1.14.14.1', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.4.19.7', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.2.1.3', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127']
25
66
RIZATRIPTAN BENZOATE
5

100%|██████████| 11047/11047 [00:04<00:00, 2702.88it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4417.79it/s]
 80%|████████  | 218/271 [48:08<11:35, 13.13s/it]

rxndb num 105
failedrxn num 0
result_df 25
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.224', '1.14.13.235', '1.14.13', '1.14.13;1.14.13.-', '1.14.13', '1.17.1.4', '1.17.1.4', '1.14.13.8', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.14.13', '1.14.13', '1.14.13', '1.13.11.52', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.13.11.52', '1.13.11.11;1.13.11.52', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.13.11.11;1.13.11.52', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.13.99.3', '1.13.11.52', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.176', '1.14.13.182', '1.14.13.182', '1.13.99.3', '1.13.11.52', '1.13.11.52']
8
27
ROPINIROLE
5

100%|██████████| 11047/11047 [00:02<00:00, 3906.50it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3653.31it/s]
 81%|████████  | 219/271 [48:21<11:20, 13.09s/it]

rxndb num 309
failedrxn num 0
result_df 34
['1.14.13.9', '1.14.13.9', '1.14.13.9', '3.1.1.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.4.22.40;3.5.1.72', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.11.2.5', '1.11.2.5', '1.11.2.5', '6.3.1.18', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.5.1.123', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.11.2.M1', '1.3.1', '3.5.1', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '3.4.11.3;3.4.11.6;3.4.22.40', '2.3.2.2;3.4.11.10;3.4.19.3', '1.14.15.15', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '3.4.21.4;3.4.22;3.4.22.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '3.3.2.6;3.4.11.10;3.4.11.15', '1.14.14.25', '1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '1.14.14.55', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.137', '1.14.13.138', '1.14.13.140', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.14.149', '1.14.14.149', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '3.4.15.6', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.174', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.15.5', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.137', '1.14.13.138', '1.14.13.140', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.194', '1.14.13.M64', '1.14.13.98', '1.14.13.98', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.1.1;1.1.1.206']
27
85
ROSIGLITAZONE MALEATE
5

100%|██████████| 11047/11047 [00:02<00:00, 4332.70it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4193.12it/s]
 81%|████████  | 220/271 [48:33<10:48, 12.72s/it]

rxndb num 246
failedrxn num 0
result_df 29
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '2.1.1.99', '2.1.1.99', '2.1.1.99', '2.1.1.99', '1.14.13.61', '1.14.13.61', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13.224', '1.14.13.224', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '2.1.1', '2.1.1', '2.1.1', '2.1.1', '1.2.3.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '1.14.13.10', '1.14.13.10', '2.4.1.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '2.1.1.M48', '2.1.1.M48', '2.1.1.M48', '2.1.1.M48', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.2.1.87', '3.4.15.6', '3.4.15.6', '3.4.19.7', '3.4.19.7', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.176', '1.14.13', '3.2.1.143', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '1.1.1;1.1.1.206', '1.-.-.-']
20
61
ROSUVASTATIN CALCIUM
5

100%|██████████| 11047/11047 [00:03<00:00, 2861.86it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3823.46it/s]
 82%|████████▏ | 221/271 [48:47<10:51, 13.02s/it]

rxndb num 401
failedrxn num 0
result_df 43
['1.1.1.157;1.1.1.35', '1.14.13.9', '1.14.13.9', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '3.1.5.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.-', '3.1.3.74', '3.1.3.74', '3.1.3.73', '3.1.3.73', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '4.2.1.17;4.2.1.74', '3.1.3.39', '3.1.3.39', '1.14.13.58', '1.14.13.58', '1.17.1.1', '1.17.1.1', '3.1.6.9', '3.1.6.9', '3.1.6.10', '3.1.6.10', '3.1.1.46', '1.1.1.-;1.1.1.35', '1.1.1.-', '1.1.1.262', '1.2.1.73', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.-;3.1.3.88', '3.1.3.-;3.1.3.88', '1.1.1.308', '3.1.3.83', '3.1.3.83', '1.1.1.334', '1.1.1.335', '1.1.1.335', '1.1.1.361', '1.1.1.361', '1.1.1.374', '1.1.1.374', '1.1.1.363;1.1.1.388', '1.1.1.390', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3;3.1.3.-', '3.1.3;3.1.3.-', '1.1.1.-', '1.1.1.-', '1.14.-.-', '1.14.-.-', '1.1.1.395', '1.1.1.395', '1.1.1.-;1.1.1.395', '1.1.1.-;1.1.1.395', '3.1.3', '3.1.3', '3.1.3.-', '3.1.3.-', '4.2.1;4.2.1.-', '1.1.1', '1.1.1', '1.1.1', '1.1.1', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.1.1.36', '1.1.1.35', '1.1.1;1.1.1.35', '1.1.1.145', '1.1.1.145', '4.2.1;4.2.1.-', '1.1.1.35', '4.2.1.134', '4.2.1.134', '4.2.1.-;4.2.1.134', '1.14.13', '1.14.13', '1.1.1.M19;1.1.1.n12', '3.1.1', '3.1.1', '3.1.1', '3.1.1', '1.1.1.330', '4.2.1.134', '1.1.1.330', '4.2.1.134', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '4.2.1.119', '1.1.1.M19', '4.2.1.119', '1.1.1.M19', '4.2.1.134', '1.1.1.330', '4.2.1.134', '1.1.1.330', '4.2.1.134', '4.2.1.134', '1.1.1.330', '4.2.1.134', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.1', '4.2.1.17', '1.1.1.211', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '4.2.1.134', '4.2.1.17', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.395', '4.2.1.17', '1.1.1.35', '4.2.1.17', '1.1.1.35', '4.2.1.17', '1.1.1.35', '1.2.1', '4.2.1.119', '4.2.1.119', '3.1.6.14', '3.1.6.14', '3.1.3.29', '3.1.3.29', '3.1.3.33;3.1.3.5', '3.1.3.33;3.1.3.5', '1.1.1.239', '1.1.1.239', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.91', '1.14.14.91', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '3.8.1.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '1.14.13.234', '3.1.3.91', '3.1.3.91', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '4.2.1;4.2.1.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '3.1.3.29', '1.1.1.211;1.1.1.35', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.29', '3.1.3.29', '3.1.3.-', '3.1.3.-', '1.14.13.74', '1.14.13.74', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '4.2.1.-', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3.73', '4.2.1.119', '3.1.2.2;4.2.1.107;4.2.1.119', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.1.1.-;1.1.1.M53', '1.1.1.-;1.1.1.M53', '4.2.1.17', '1.1.1.259;1.1.1.35', '4.2.1.-;4.2.1.150;4.2.1.17;4.2.1.74', '4.2.1.17;4.2.1.74', '4.2.1.17;4.2.1.74', '4.2.1.17;4.2.1.74', '1.1.1.363;1.1.1.388;1.1.1.47;1.1.1.49', '1.2.1.97', '1.14.14.22;1.14.99.46', '1.1.1', '3.1.3.M8', '3.1.3.M8', '1.1.1.-', '1.1.1.100', '1.1.1.100', '1.2.1.97', '1.2.1.97', '3.1.3.105', '3.1.3.105', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.1.3.29', '3.1.3.29', '3.2.1.-', '3.2.1.-', '1.1.1.36', '1.1.1.-', '1.1.1.35', '1.14.13.103', '1.14.13.103', '1.1.1.-', '1.1.1.-', '1.1.1.-', '1.1.1.100', '1.1.1.100', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.2;3.1.3.5', '1.1.1.211;1.1.1.35', '1.1.1.211;1.1.1.35', '1.1.1.211;1.1.1.35', '1.1.1.211;1.1.1.35', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.5.1', '4.2.1.-;4.2.1.119;4.2.1.134', '1.1.1.36', '1.1.1.36', '4.2.1.119', '4.2.1.119', '1.1.1.35', '4.2.1.17', '1.1.1.35', '4.2.1.17', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7;3.1.3.97', '3.1.3.7', '3.1.3.7', '1.1.1.363;1.1.1.49', '3.1.3.82', '3.1.3.82', '4.2.1.17;4.2.1.74', '1.1.1.211;1.1.1.35', '4.2.1.17;4.2.1.74', '1.1.1.211;1.1.1.35', '4.2.1.17;4.2.1.74', '1.1.1.211;1.1.1.35', '4.2.1.17;4.2.1.74', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.1.1.363;1.1.1.47;1.1.1.49', '1.1.1.49', '3.1.3.-', '3.1.3.-', '3.1.3', '3.1.3', '1.14.14', '1.14.14', '1.1.1.211;1.1.1.35', '3.1.3.-;3.1.3.102;3.1.3.2', '3.1.3.-;3.1.3.102;3.1.3.2', '4.2.1.17', '1.1.1.35', '1.1.1.395', '1.1.1.395', '1.1.1.35', '1.1.1.35', '1.1.1.35', '3.1.3.-;3.1.3.104', '3.1.3.-;3.1.3.104']
20
114
ROXATIDINE ACETATE
5

100%|██████████| 11047/11047 [00:02<00:00, 3916.21it/s]
100%|██████████| 27873/27873 [00:09<00:00, 3082.43it/s]
 82%|████████▏ | 222/271 [49:02<11:05, 13.58s/it]

rxndb num 777
failedrxn num 0
result_df 67
['3.5.1.94', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.1.5', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13;1.14.99.10', '1.14.14.1', '6.3.2.1', '3.5.1.92', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.1.23', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.118;1.1.1.47', '1.1.1.119;1.1.1.47', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.5.1.22', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '6.3.2.23', '6.3.1.2;6.3.1.6', '3.5.1.65', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '6.3.2.20', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '3.1.1.70', '3.5.1.24;3.5.1.74', '3.1.1.51', '3.5.1.24', '1.14.13.22', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.1.1.53', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.3.2.36', '1.2.-.-', '1.2.-.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.-.-', '1.14.19.n5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '3.5.1.-', '6.3.2.44', '6.3.4.24', '1.1.1.363;1.1.1.388', '1.1.1.390', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.1.1.116', '6.3.2.18', '1.1.1.359;1.1.1.376;1.1.1.46', '6.3.2;6.3.2.-', '6.3.2', '6.3.2', '6.3.2', '6.3.2', '6.3.2', '3.1.1;3.1.1.1;3.1.1.3', '3.4.11.25', '6.3.2.59', '6.3.2.59', '3.1.1', '3.1.1', '1.1.1', '3.1.1', '3.1.1.26', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.1.4', '3.1.1.23', '3.1.1.23', '3.4.13', '6.3.2', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '3.1.1', '3.1.1', '3.1.1', '3.1.1;3.1.1.-', '3.1.1', '1.3.1', '1.3.1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '3.1.1', '6.3.2', '1.1.1.-', '1.1.1', '3.4', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.3.1', '3.5.1.115', '3.1.1.1;3.1.1.3', '3.5.1.23', '3.5.1.23', '3.1.1.3', '3.1.1.3', '3.5.1.23', '3.1.1.1', '3.1.1.1', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.5.1.23', '3.5.1.23', '3.1.1.3', '3.5.1.23', '1.1.1.179;1.3.1.20', '1.1.1.179;1.3.1.20', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '3.5.1.23', '3.4.21;3.4.21.62', '3.4.16.5;3.4.21;3.4.21.62', '3.5.1.23', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.121', '1.1.1.47', '1.1.1.122', '6.3.2.18', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '3.4.11.5', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.82', '3.2.1.15;3.2.1.82', '6.3.2.17', '6.3.2.17', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '3.2.1.35', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '2.3.1.-', '3.1.1', '1.14.-.-', '2.4.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.3.1.11', '3.5.1.-;3.5.1.78', '6.3.1.8;6.3.1.9', '3.1.1.5', '3.1.1.5', '3.5.1.4;3.5.1.99', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.16', '3.5.1.24;3.5.1.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '3.1.1.10', '1.1.1.113', '6.3.1.9', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.99.10', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '3.1.1.80', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.1.80', '3.1.1.80', '1.14.-.-', '1.14.-.-', '3.5.1.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '6.3.1.13', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.1.94', '2.3.1.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '6.3.1.10', '6.3.1.10', '3.5.1.90', '3.5.1.90', '1.1.1.363;1.1.1.388;1.1.1.47;1.1.1.49', '3.1.1.105', '3.1.1.105', '6.3.2.56;6.3.2.ad', '3.5.1.M13', '3.1.1.80', '3.5.1.60;3.5.1.99', '3.1.1.116', '1.1.1.376', '3.5.1.60', '3.5.1.60;3.5.1.99', '3.5.1.99', '3.5.1.99', '1.1.1.420', '3.5.1.60', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.4', '3.1.1.33', '3.1.1.33', '1.1.1.120', '3.2.1.14', '3.2.1.14', '1.1.1.121;1.1.1.175', '1.1.1.121', '1.1.1.179', '1.1.1.179', '1.1.1.46', '1.1.1.46', '1.1.1.121', '3.1.1.53', '3.1.1.53', '3.1.1.53', '3.1.1.53', '1.14.-.-;1.14.13.-', '1.14.-.-', '1.14.-.-', '3.2.1.154', '3.2.1.154', '3.2.1.87', '3.2.1.87', '3.4.15.6', '3.4.15.6', '3.4.19.9', '3.4.19.9', '3.4.19.5', '3.4.19.5', '3.4.19.7', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '3.1.-.-', '3.1.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.15.5', '3.1.1.53', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '1.1.1.117', '1.1.1.117', '1.1.1.117', '1.1.1.117', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '3.1.1.5', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.46', '1.1.1.46', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '6.3.2;6.3.2.-', '3.1.1.101', '3.1.1.101', '6.3.2', '3.2.1.143', '3.2.1.143', '6.3.2', '6.3.2', '4.2.1.140;4.2.1.39', '4.2.1.140;4.2.1.39', '4.2.1.6', '4.2.1.6', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '6.3.2', '6.3.2', '6.3.2.37', '6.3.1.10', '1.1.1.363;1.1.1.49', '1.3.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.1', '3.1.1', '3.1.1', '1.17.1', '1.1.1.118', '1.1.1.120;1.1.1.179;1.1.1.359;1.1.1.360;1.1.1.47;1.1.1.48;1.3.1.20', '1.1.1.120', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.1.1.119', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.1.1.121;1.1.1.359;1.1.1.47;1.1.1.48', '1.1.1.121', '3.1.1.53', '3.1.1.53', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.1.1.363;1.1.1.47;1.1.1.49', '1.1.1.49', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '6.3.2.58', '6.3.2.58', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.5.1.115', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1.424', '1.1.1;1.1.1.206', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '3.1.1.7;3.1.1.8', '3.5.1.46']
42
181
SERTRALINE
5

100%|██████████| 11047/11047 [00:03<00:00, 2779.62it/s]
100%|██████████| 27873/27873 [00:05<00:00, 5140.63it/s]
 82%|████████▏ | 223/271 [49:14<10:31, 13.15s/it]

rxndb num 133
failedrxn num 0
result_df 16
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.5.3.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.97.1.-', '1.97.1.-', '1.5.3.-;1.5.3.19', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.3.98.-', '1.3.98.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.19.58', '1.14.19.58', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8']
8
21
SILDENAFIL CITRATE
5

100%|██████████| 11047/11047 [00:03<00:00, 3030.82it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3657.99it/s]
 83%|████████▎ | 224/271 [49:28<10:35, 13.52s/it]

rxndb num 140
failedrxn num 0
result_df 32
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '1.14.13.8', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '1.14.14.1', '1.14.-.-', '1.14.-.-', '2.4.1.-', '1.14.13.30', '1.14.13.30', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.94', '1.14.13.94', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '3.4.15.6', '3.4.15.6', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.13.174', '1.14.15.5', '1.14.15.5', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13', '3.2.1.143', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '3.6.1.18;3.6.1.9']
14
40
SOLIFENACIN SUCCINATE
5

100%|██████████| 11047/11047 [00:03<00:00, 3562.73it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3844.40it/s]
 83%|████████▎ | 225/271 [49:41<10:14, 13.36s/it]

rxndb num 844
failedrxn num 0
result_df 96
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.118;1.1.1.47', '1.1.1.119;1.1.1.47', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '3.1.1.70', '3.1.1.51', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.5.1;1.5.1.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.13.-', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.1.1.363;1.1.1.388', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.108', '1.14.14.108', '6.3.2', '6.3.2', '1.3.1', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.1', '3.1.1.26', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.1.4', '3.1.1.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '3.1.1', '1.1.1.-', '3.1.1.1;3.1.1.13;3.1.1.3', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '1.1.1.179;1.3.1.20', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '3.4.21;3.4.21.62', '3.4.16.5;3.4.21;3.4.21.62', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '1.14.14.55', '3.2.1.78', '3.2.1.78', '3.2.1.78', '1.1.1.121', '1.1.1.121', '1.1.1.47', '1.1.1.122', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.82', '6.3.2.17', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '2.3.1.-', '3.1.1', '1.14.-.-', '1.14.-.-', '3.1.1.5', '3.1.1.5', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '3.1.1.10', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '2.-.-.-', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '2.3.1.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.1.1.363;1.1.1.388;1.1.1.47;1.1.1.49', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.1.1.120', '3.2.1.14', '1.1.1.121;1.1.1.175', '1.1.1.121', '1.1.1.179', '1.1.1.179', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.1.1.121', '1.14.13.126', '1.14.13.126', '1.14.13.54', '3.2.1.87', '3.4.15.6', '3.4.19.9', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.-.-', '3.1.-.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.-.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '3.1.1.5', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '3.1.1.101', '3.2.1.143', '1.14.13.M64', '1.1.1.363;1.1.1.49', '1.1.1.118', '1.1.1.120;1.1.1.179;1.1.1.359;1.1.1.360;1.1.1.47;1.1.1.48;1.3.1.20', '1.1.1.120', '1.17.99.5', '1.17.99.5', '1.1.1.119', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.1.1.121;1.1.1.359;1.1.1.47;1.1.1.48', '1.1.1.121', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.1.1.363;1.1.1.47;1.1.1.49', '1.1.1.49', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127']
33
121
SOTALOL
5

100%|██████████| 11047/11047 [00:03<00:00, 3630.15it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4045.70it/s]
 83%|████████▎ | 226/271 [49:54<09:52, 13.17s/it]

rxndb num 153
failedrxn num 0
result_df 23
['1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '3.1.3.-', '3.1.3.27', '3.1.3.73', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3.39', '1.14.13.58', '1.14.13.58', '1.14.13.29', '1.14.13.29', '3.1.3.40', '3.1.6.9', '3.1.6.10', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.8.99.3;1.8.99.5', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.1.3.-;3.1.3.88', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '3.1.3.83', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '3.1.3.101', '3.1.3;3.1.3.-', '3.1.3', '3.1.3.-', '3.1.6;3.1.6.-', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '1.14.14', '1.14.14', '3.1.3', '1.14.13', '3.1.6.14', '3.1.3.29', '3.1.3.33;3.1.3.5', '1.14.18.1', '1.14.18.1', '1.14.14.91', '1.14.14.91', '3.1.3', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.35', '3.1.3.91', '3.6.1;3.6.1.-', '3.1.3.29', '3.1.3.27', '3.1.3', '3.1.3.29', '3.1.3.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.11', '1.14.13.11', '3.1.3.73', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.1.3.105', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.1.3.29', '3.4.15.6', '3.4.19.7', '1.7.3.-', '3.2.1.-', '3.1.3.27', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '3.1.3.82', '1.1.1', '1.1.1', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '1.1.1.422', '1.1.1.423', '1.11.2.6', '1.11.2.6', '1.1.1.422', '1.1.1.423', '4.2.3;4.2.3.1', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75']
23
79
SPIPERONE
5

100%|██████████| 11047/11047 [00:03<00:00, 3301.96it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3772.12it/s]
 84%|████████▍ | 227/271 [50:08<09:49, 13.40s/it]

rxndb num 386
failedrxn num 0
result_df 43
['3.5.1.94', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '6.3.2.1', '3.5.1.92', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.5.1.22', '6.3.2.23', '6.3.1.2;6.3.1.6', '3.5.1.65', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '6.3.2.20', '1.17.1.1', '1.17.1.1', '3.5.1.24;3.5.1.74', '3.5.1.24', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '6.3.2.36', '3.5.1.-', '6.3.2.44', '6.3.4.24', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.3.2.18', '6.3.2;6.3.2.-', '1.3.3.6', '6.3.2', '6.3.2', '6.3.2', '1.3.1.93', '1.3.1.93', '6.3.2.59', '6.3.2.59', '1.3.1.93', '1.3.1.93', '3.4.13', '6.3.2', '1.3.1.93', '1.3.1.93', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '1.1.1.348', '6.3.2', '3.4', '3.5.1.115', '1.3.3.6', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '3.5.1.23', '3.5.1.23', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '6.3.2.18', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.4.11.5', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '1.14.14.1', '6.3.1.11', '3.5.1.-;3.5.1.78', '6.3.1.8;6.3.1.9', '3.5.1.4;3.5.1.99', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.5.1.24;3.5.1.74', '6.3.1.9', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.3.1.104;1.3.1.38;1.3.1.8', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.3.1.104;1.3.1.38;1.3.1.44;1.3.1.8', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '3.5.1.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '6.3.1.13', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1;1.3.1.44', '1.3.99.-', '1.3.99.3', '1.1.1;1.3.99.3', '1.3.1.9', '6.3.1.10', '6.3.1.10', '3.5.1.90', '3.5.1.90', '6.3.2.56;6.3.2.ad', '3.5.1.60;3.5.1.99', '3.5.1.60', '3.5.1.60;3.5.1.99', '3.5.1.99', '3.5.1.99', '3.5.1.60', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.1.1.50', '3.4', '3.2.1.14', '3.2.1.14', '3.4.15.6', '3.4.15.6', '3.2.1.-', '3.2.1.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.3.2;6.3.2.-', '6.3.2', '6.3.2', '6.3.2', '1.3.3.6', '6.3.2', '6.3.2', '6.3.2.37', '1.3.1.93', '1.3.3.6', '1.3.1.104;1.3.1.38;1.3.1.8', '6.3.1.10', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.3.3.6;1.3.8.1;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.3.3.6', '1.3.3.6', '1.3.1.10;1.3.1.38;1.3.1.8', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '6.3.2.58', '6.3.2.58', '3.5.1.115', '1.1.1;1.1.1.206', '3.5.1.46']
26
94
SULFASALAZINE
5

100%|██████████| 11047/11047 [00:02<00:00, 3688.57it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4120.59it/s]
 84%|████████▍ | 228/271 [50:20<09:22, 13.07s/it]

rxndb num 576
failedrxn num 0
result_df 114
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.2.3.1;1.2.3.8', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.2.1.29;1.2.3.1', '1.2.1.29;1.2.3.1', '3.1.1.20', '3.1.1.20', '3.1.1.40', '3.1.1.40', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '4.1.1.46', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '4.1.1.62', '1.14.13.24', '4.1.1.-', '4.1.1.58', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '4.1.1.59', '1.14.13.19', '1.14.13.19', '1.14.13.180', '1.14.13.180', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '4.1.1.103', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.224', '1.2.1.19;1.2.1.24;1.2.1.29;1.2.1.3;1.2.1.5;1.2.1.88', '1.14.-.-', '1.14.13;1.14.13.-', '1.1.1.415;1.1.1.ee', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.2.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.24', '1.14.13.24', '1.2.1.19', '1.14.18.1', '1.2.1.5;1.2.1.88', '1.14.13.24', '1.14.13.24', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.13', '1.2.3.1;1.2.3.8', '1.2.1.3', '1.2.1.3', '3.1.3.48', '3.1.3.36;3.1.3.48', '3.1.3.48', '1.14.14.55', '3.1.3.48', '3.1.3.2', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.-', '1.14.13.-', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.82', '3.2.1.15;3.2.1.82', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '1.14.13', '3.1.3;3.1.3.2;3.1.3.48', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.1.1.415', '1.14.14.22;1.14.99.46', '4.1.1.118', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '3.2.1.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.91', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.14.8', '1.7.1.17;1.7.1.6', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13.M82', '1.14.13.M82', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6']
23
87
SULFINPYRAZONE
5

100%|██████████| 11047/11047 [00:02<00:00, 4228.74it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3732.84it/s]
 85%|████████▍ | 229/271 [50:34<09:15, 13.22s/it]

rxndb num 97
failedrxn num 0
result_df 23
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.12', '1.3;1.3.1.120', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.3.1.120', '3.2.1.14', '3.2.1.14', '3.2.1.-', '3.2.1.-', '1.14.13.32', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.1.1;1.1.1.206']
12
28
SULINDAC
5

100%|██████████| 11047/11047 [00:02<00:00, 3819.88it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4289.74it/s]
 85%|████████▍ | 230/271 [50:46<08:49, 12.91s/it]

rxndb num 243
failedrxn num 0
result_df 39
['1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.13.15', '1.14.14.1;1.14.14.25;1.14.14.55;1.14.14.57', '1.2.1.5', '1.14.14.-;1.14.14.1', '1.2.1.40', '1.14.13.72', '1.2.1.74', '1.2.1.73', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.100;1.14.14.29', '1.1.1.308', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.1.1.390', '1.14.13;1.14.13.-', '1.2.1;1.2.1.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13;1.14.13.-', '1.1.1.-', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.2.1.3;1.2.1.8', '1.14.14.1', '1.14.13.8;1.14.13.84', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.1', '1.14.14.1', '1.14.14.55', '1.14.14.55', '1.14.14.1', '1.14.12.9', '1.14.12.9', '1.14.12.9', '1.14.12.9', '1.14.12.9', '1.14.12.9', '1.14.15.4', '1.14.15.4', '1.14.13.72', '1.2.1.74', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.234', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.74', '1.14.13.74', '1.14.13.72', '1.14.13.74', '1.14.13.74', '1.14.13.78', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.76', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.94', '1.14.13.94', '1.14.13.97', '1.14.13.97', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.-.-', '1.14.-.-', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.17', '1.14.13.147', '1.14.13.147', '1.2.1.97', '1.2.1.97', '1.2.1.97', '1.2.1.-', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.144', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.2.1.-', '1.14.11.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.15.5', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.-.-', '1.14.-.-', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.94', '1.14.13.94', '1.14.13.184', '1.14.13.184', '1.14.13.194', '1.14.14.1', '1.14.13.32', '1.14.13.15', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.122', '1.17.99.5', '1.17.99.5', '1.2.1.3;1.2.1.40', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.2.1', '1.2.1', '1.2.1.5']
11
61
SULPIRIDE
5

100%|██████████| 11047/11047 [00:03<00:00, 3272.20it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4521.72it/s]
 85%|████████▌ | 231/271 [50:58<08:27, 12.70s/it]

rxndb num 141
failedrxn num 0
result_df 28
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '3.5.1.40', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.180', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '3.3.2.14', '2.1.1.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.13.-', '1.14.13.-', '3.4.11.5', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '1.14.14.1', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '1.14.13.11', '3.2.1.14', '3.2.1.14', '3.4.15.6', '3.4.15.6', '3.4.19.7', '3.4.19.7', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.15.5', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '3.2.1.143', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '3.6.1.18;3.6.1.9']
21
45
SUMATRIPTAN SUCCINATE
5

100%|██████████| 11047/11047 [00:02<00:00, 3946.20it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3670.60it/s]
 86%|████████▌ | 232/271 [51:11<08:19, 12.81s/it]

rxndb num 81
failedrxn num 0
result_df 21
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.235', '1.14.13', '1.14.13', '1.14.13.8', '1.14.13', '1.14.13', '1.14.13', '1.13.11.52', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.4.11.5', '3.2.1.35', '1.14.14.1', '1.13.11.52', '1.13.11.11;1.13.11.52', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.13.11.11;1.13.11.52', '1.14.13.11', '1.14.13.11', '1.14.13.11', '3.4.19.7', '1.13.99.3', '1.13.11.52', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.176', '1.14.13.182', '1.14.13.182', '1.13.99.3', '1.13.11.52', '1.13.11.52']
9
26
TACRINE
5

100%|██████████| 11047/11047 [00:03<00:00, 3431.54it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4119.82it/s]
 86%|████████▌ | 233/271 [51:24<08:08, 12.86s/it]

rxndb num 148
failedrxn num 0
result_df 35
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.99.2', '1.14.99.2', '1.14.12.16', '1.14.13.61', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.7.1.-', '1.8.99.3;1.8.99.5', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13', '1.14.13', '1.14.12.16', '1.1.1.2', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.12.-', '1.14.12.-', '1.14.12.-', '1.13.99.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.176', '1.14.13.M64', '1.14.13.M64', '1.14.13.182', '1.14.13.182', '1.13.99.3', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14', '1.14.14', '1.14.14', '1.14.14']
10
31
TACROLIMUS
5

100%|██████████| 11047/11047 [00:05<00:00, 2087.68it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3690.30it/s]

rxndb num 5241
failedrxn num 0

 86%|████████▋ | 234/271 [51:40<08:25, 13.65s/it]

result_df 421

100%|██████████| 11047/11047 [00:04<00:00, 2685.25it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3790.12it/s]
 87%|████████▋ | 235/271 [51:55<08:25, 14.03s/it]

rxndb num 638
failedrxn num 0
result_df 82
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.99.2', '1.14.99.2', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.12.16', '1.14.13.61', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.3.3.13', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13;1.14.13.-', '3.2.1.40', '3.2.1.40', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.12.16', '3.2.1.21;3.2.1.23', '3.2.1.21;3.2.1.23', '3.2.1.22', '3.2.1.22', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.2.1.161;3.2.1.188;3.2.1.21;3.2.1.23;3.2.1.25;3.2.1.3;3.2.1.37;3.2.1.45;3.2.1.58;3.2.1.74', '3.2.1.161;3.2.1.188;3.2.1.21;3.2.1.23;3.2.1.25;3.2.1.3;3.2.1.37;3.2.1.45;3.2.1.58;3.2.1.74', '3.2.1.3', '3.2.1.3', '3.2.1;3.2.1.10;3.2.1.177;3.2.1.199;3.2.1.20;3.2.1.21;3.2.1.70', '3.2.1;3.2.1.10;3.2.1.177;3.2.1.199;3.2.1.20;3.2.1.21;3.2.1.70', '3.2.1.51', '3.2.1.51', '3.2.1.78', '3.2.1.21;3.2.1.22;3.2.1.23', '3.2.1.21;3.2.1.22;3.2.1.23', '3.2.1.22;3.2.1.23;3.2.1.85', '3.2.1.22;3.2.1.23;3.2.1.85', '3.2.1.55', '3.2.1.55', '3.2.1.23', '3.2.1.23', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '1.14.21.8', '1.14.21.8', '3.2.1.35', '3.2.1.35', '2.4.1.-', '2.4.1.-', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.21.2', '1.14.21.2', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.19.68;1.14.21.5', '1.14.19.68;1.14.21.5', '1.14.21.1', '1.14.21.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '3.2.1.20;3.2.1.22', '3.2.1.20;3.2.1.22', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.2.1.126', '3.2.1.126', '3.2.1.87', '3.2.1.87', '3.4.15.6', '3.4.15.6', '3.4.19.7', '3.4.19.7', '1.14.21.8', '1.14.21.8', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.13.99.3', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.176', '1.14.13.176', '1.14.13.177', '1.14.13', '3.2.1.143', '3.2.1.143', '1.14.13.182', '1.14.13.182', '1.13.99.3', '3.2.1.126', '3.2.1.126', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.1.1;1.1.1.206', '1.1.1;1.1.1.206']
26
92
TAMSULOSIN HYDRCHLORIDE
5

100%|██████████| 11047/11047 [00:02<00:00, 3980.08it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3249.83it/s]
 87%|████████▋ | 236/271 [52:09<08:17, 14.23s/it]

rxndb num 356
failedrxn num 0
result_df 37
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.5.3.13', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '3.3.2.14', '2.1.1.-', '2.1.1.-', '2.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.35', '1.14.-.-', '1.14.-.-', '2.4.1.-', '2.4.1.-', '2.4.1.-', '1.14.13.30', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.4.15.6', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.15.5', '1.14.15.5', '6.2.1.3', '6.2.1.3', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '3.2.1.143', '3.2.1.143', '3.2.1.143', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-']
21
47
TEGASEROD MALEATE
5

100%|██████████| 11047/11047 [00:02<00:00, 3851.78it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3542.02it/s]
 87%|████████▋ | 237/271 [52:23<07:56, 14.00s/it]

rxndb num 510
failedrxn num 0
result_df 50
['1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.-.-', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.224', '1.14.13.224', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.14.13.235', '1.14.13', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.13.11', '1.3.1', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.15.15', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.13.11.52', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '3.5.3.25', '1.14.-.-', '1.3.1;1.3.1.-', '1.3.1;1.3.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.13.11.52', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.13.11.11;1.13.11.52', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.13.11.11;1.13.11.52', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.-.-', '1.14.-.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.13.11.52', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.174', '1.14.13.72', '1.14.15.5', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.176', '1.14.13.176', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '3.2.1.143', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.3.99.-', '1.3.99.-', '1.14.13.182', '1.14.13.182', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.13.11.52', '1.13.11.52']
21
62
TELMISARTAN
5

100%|██████████| 11047/11047 [00:04<00:00, 2580.28it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4289.71it/s]
 88%|████████▊ | 238/271 [52:37<07:41, 14.00s/it]

rxndb num 602
failedrxn num 0
result_df 61
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.2.3.1;1.2.3.8', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.99.2', '1.14.99.2', '1.14.99.2', '1.14.99.2', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13;1.14.13.-', '1.1.1.415;1.1.1.ee', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.12.16', '1.14.12.16', '4.1.1.-;4.1.1.98', '4.1.1;4.1.1.-', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '4.1.1;4.1.1.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.3.1;1.2.3.8', '1.2.1.3', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.8', '3.8.1.8', '3.4.11.5', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.30', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.79', '1.14.13.79', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.-.-;1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.415', '1.14.14.22;1.14.99.46', '4.1.1.98', '4.1.1.118', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.13.174', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.176', '1.14.13.176', '1.14.13.176', '1.14.13.176', '1.14.13.176', '1.14.13.194', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '2.6.1.114', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '4.1.1;4.1.1.-']
16
59
TENATOPRAZOLE
5

100%|██████████| 11047/11047 [00:02<00:00, 3791.81it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3595.82it/s]
 88%|████████▊ | 239/271 [52:51<07:27, 13.97s/it]

rxndb num 115
failedrxn num 0
result_df 27
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.61', '1.14.13.61', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '2.1.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.99.50;1.14.99.51', '1.14.99.51', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '3.3.2.14', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '1.14.13.224', '1.14.13.224', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.3.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '3.2.1.35', '2.4.1.-', '2.4.1.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.176', '1.14.13.176', '3.2.1.143', '3.2.1.143', '1.14.13.32', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '2.6.1.114', '2.6.1.114', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9']
14
44
TENOXICAM
5

100%|██████████| 11047/11047 [00:02<00:00, 3794.93it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3872.32it/s]
 89%|████████▊ | 240/271 [53:03<06:59, 13.55s/it]

rxndb num 238
failedrxn num 0
result_df 33
['3.1.3.74', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '3.1.3.74', '3.1.3.74', '3.1.3.73', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '3.1.3.39', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.1.3.40', '3.1.6.9', '3.1.6.10', '3.4.22.40;3.5.1.72', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.1.3.-;3.1.3.88', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.224', '1.14.13.224', '3.1.3', '3.1.3.-', '3.1.6;3.1.6.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.6.14', '3.4.11.3;3.4.11.6;3.4.22.40', '3.1.3.29', '2.3.2.2;3.4.11.10;3.4.19.3', '3.1.3.33;3.1.3.5', '3.4.21.4;3.4.22;3.4.22.1', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '3.1.3', '3.1.3', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '3.1.3.91', '3.6.1;3.6.1.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.29', '3.1.3.-', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.140', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '3.1.3.73', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.M8', '3.1.3.105', '3.2.1.14', '3.2.1.14', '3.1.3.29', '3.2.1.-', '3.2.1.-', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.140', '1.14.13.176', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '3.1.3.-;3.1.3.104']
20
85
TERAZOSIN
5

100%|██████████| 11047/11047 [00:03<00:00, 3541.98it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3568.81it/s]
 89%|████████▉ | 241/271 [53:17<06:51, 13.70s/it]

rxndb num 224
failedrxn num 0
result_df 38
['1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.5.4.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '3.5.4.23', '1.14.13.61', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '2.1.1.-', '3.5.4.5', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.19.n5', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '3.3.2.14', '3.3.2.14', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '3.5.4.20', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.5.4.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '3.5.4.5', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.35', '2.4.1.-', '2.4.1.-', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.89', '1.14.13.89', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.5.4.1', '3.5.4.12', '3.5.4.13', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.4.15.6', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.13.21', '1.14.13.21', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '6.2.1.3', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.176', '3.2.1.143', '3.2.1.143', '3.2.1.143', '6.3.4.2', '3.5.4.13', '3.5.4.12', '3.5.4.5', '1.14.13.182', '1.14.13.182', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.1.1;1.1.1.206', '3.5.4.14;3.5.4.5']
23
69
TERBINAFINE
5

100%|██████████| 11047/11047 [00:03<00:00, 3266.20it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4438.31it/s]
 89%|████████▉ | 242/271 [53:30<06:27, 13.35s/it]

rxndb num 98
failedrxn num 0
result_df 16
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.8', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-', '1.14.13.-', '1.13.12', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.108', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.78', '1.14.13.144', '1.14.13.-', '1.14.13.78', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190']
4
18
THIABENDAZOLE
5

100%|██████████| 11047/11047 [00:03<00:00, 2866.05it/s]
100%|██████████| 27873/27873 [00:05<00:00, 4725.65it/s]
 90%|████████▉ | 243/271 [53:43<06:09, 13.19s/it]

rxndb num 39
failedrxn num 0
result_df 7
['1.14.12.16', '1.14.12.16', '1.14.13.61', '1.14.13.61', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13', '1.14.12.16', '1.14.12.16', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-']
3
8
THIOTHIXENE
5

100%|██████████| 11047/11047 [00:03<00:00, 2801.06it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3421.43it/s]
 90%|█████████ | 244/271 [53:58<06:13, 13.83s/it]

rxndb num 145
failedrxn num 0
result_df 29
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.8', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.2.1.35', '1.14.14.1', '1.14.13.234', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-']
5
20
TIAPRIDE
5

100%|██████████| 11047/11047 [00:02<00:00, 4489.81it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3565.37it/s]
 90%|█████████ | 245/271 [54:11<05:52, 13.58s/it]

rxndb num 147
failedrxn num 0
result_df 24
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.5.1.40', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.180', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '3.3.2.14', '2.1.1.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.14.1', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.-', '1.14.13.-', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '1.14.14.1', '1.14.-.-', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.-.-', '1.14.-.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '1.14.-.-', '1.14.-.-', '3.4.15.6', '3.4.15.6', '3.4.19.7', '3.4.19.7', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.15.5', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '3.2.1.143', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '3.6.1.18;3.6.1.9']
21
45
TIMOLOL MALEATE
5

100%|██████████| 11047/11047 [00:03<00:00, 2885.23it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4244.09it/s]
 91%|█████████ | 246/271 [54:25<05:38, 13.54s/it]

rxndb num 375
failedrxn num 0
result_df 24
['3.1.3.15', '3.1.3.74', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.14.1', '3.1.3.-', '3.1.3.74', '3.1.3.27', '3.1.3.74', '1.5.3.13;1.5.3.17', '1.5.3.13', '1.5.3.13;1.5.3.17', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '3.1.3.39', '1.1.1.148', '1.1.3.16', '1.14.14.1', '3.1.6.9', '3.1.6.10', '1.1.1;1.1.1.-', '1.-.-.-;1.1.1.342', '1.1.1.62', '1.1.1.62', '1.1.1.53', '1.1.1.50', '1.1.1.53', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.263', '1.1.1;1.1.1.-', '1.1.1.364', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.-.-', '1.1.1.-', '1.1.1;1.1.1.-;1.1.1.50', '1.-.-.-', '1.1.1.292', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.-', '1.1.1.-', '1.1.1.-;1.1.1.341;4.2.1.-', '1.1.1.-;1.1.1.329', '3.1.3.-;3.1.3.88', '1.1.1.-', '1.1.1.213', '3.1.3.79', '1.5.3.15;1.5.3.17', '1.5.1.-;1.5.1.43', '1.1.3.-;1.1.3.45', '3.1.3.85', '1.14.-.-', '3.1.3.83', '1.1.1.-;1.1.1.329', '1.1.1.335', '1.1.1.339;1.1.1.344', '1.1.1.355', '1.1.1.356', '1.1.1.356', '1.1.1.361', '3.1.3.92', '1.1.1.364', '1.1.1.367', '1.1.1.374', '1.1.1.385', '1.1.1.393', '3.1.3.101', '3.1.3.-', '1.1.1.-', '1.1.1.-', '1.1.1.-', '3.1.3;3.1.3.-', '1.1.1.-', '2.1.1.-', '3.1.3.103', '1.1.1.395', '1.1.1.-;1.1.1.395', '3.1.3', '1.5.3.14', '3.1.3.-', '1.1.1.201', '1.1.1.-;1.1.1.50;1.1.1.52', '1.1.1.391', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.1.1.102', '1.1.1.145', '1.14.14.133', '1.1.1', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.1.1', '1.1.1', '1.1.1', '3.1.3', '1.1.1.201', '1.1.1', '1.1.1', '1.14.13', '1.1.1', '1.1.1.M2', '1.14.13', '1.1.1.392', '1.1.1.393', '1.1.1.52', '1.1.1.391', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.52', '1.1.1.391', '1.1.1.392;1.1.1.50;1.1.1.52', '1.1.1.392', '1.1.1.393', '1.1.1.393', '1.1.1', '1.1.1.159', '1.1.1.218', '3.1.6.14', '1.1.1.218', '3.1.3.29', '1.1.1.149', '3.1.3.33;3.1.3.5', '1.1.1.133', '1.1.1.239', '1.1.1.213;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.50', '1.14.13.126;1.14.15.16', '1.1.1.292', '3.1.3', '3.1.3', '3.2.1.78', '3.1.3', '3.1.3', '1.1.1.146;1.1.1.159;1.1.1.50', '1.1.99.13', '3.1.3.68', '1.1.1.133', '1.14.15.4', '1.14.15.6', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.65', '3.1.3.91', '3.6.1;3.6.1.-', '1.1.1.104', '1.1.1.104', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '2.4.1.-', '1.1.1.104', '1.14.-.-', '1.14.-.-', '1.1.1.-;1.1.1.146', '1.1.1;1.1.1.-;1.1.1.146;1.1.1.51', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.25', '3.1.3.27', '1.5.3.11;1.5.3.13;1.5.3.16;1.5.3.17', '1.14.13.30', '3.1.3', '3.1.3.24', '1.1.1.133', '3.1.3.12', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '1.1.1.271', '3.1.3.29', '1.1.1;1.1.1.148;1.1.1.209', '3.1.3.-', '1.1.1.134;1.1.1.344', '1.1.1.159;1.1.1.50', '1.1.1.176', '1.1.1.206', '1.1.1.236', '1.1.1.241', '1.1.1.135;1.1.1.187', '1.1.1.187;1.1.1.281', '1.1.1.135;1.1.1.187', '1.1.1.187;1.1.1.281', '1.1.1.238', '1.14.13.74', '1.1.1.146', '1.1.1.213;1.1.1.52', '1.1.1.213;1.1.1.50', '1.1.1.50', '1.1.1.209;1.1.1.50', '2.-.-.-', '1.1.1.266', '3.1.3.70', '1.14.13.74', '1.14.13.94', '1.14.13.96', '1.14.13.97', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.-.-', '1.14.-.-', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.-', '1.1.1.1;1.1.1.391', '1.1.1.-;1.1.1.146;1.1.1.209;1.1.1.213;1.1.1.392;1.1.1.50', '3.1.3.73', '1.1.1;1.1.1.-', '3.1.3', '3.1.3', '1.1.1.159', '1.1.1.-', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.1.1.153', '3.1.3.45', '1.1.1.-;1.1.1.M53', '1.14.13;1.14.13.-', '1.5.1.43', '1.1.1.201', '3.1.3.M8', '1.1.1', '1.1.1.104', '1.1.1.266', '1.1.1.367', '3.1.3.105', '1.5.1.43', '1.1.1', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.-.-', '1.14.-.-', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.2.1.87', '3.2.1.1', '1.7.3.-', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.1.1.-', '1.14.13.-', '1.14.13.-', '3.2.1.2', '1.14.13.-', '1.14.13.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.15.5', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '1.14.13.94', '1.14.13.96', '1.1.1.-', '3.1.3.27', '1.14.13.183', '1.14.13.184', '3.1.3', '3.1.3.73', '3.2.1.143', '3.2.1.143', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.14.13.M64', '1.1.1.M51', '3.1.3.73', '1.1.1.M51', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '1.14.13.98', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '3.1.3.82', '1.1.1;1.1.1.51;1.1.1.62', '1.14.13.-;1.14.15.6', '1.1.1.271', '1.1.1.271', '1.1.99.13', '1.17.99.5', '1.14.13.97', '1.17.99.5', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.1.1.367', '1.1.1.-', '1.1.1.395', '1.1.1', '1.1.1.238', '1.1.1.206', '3.1.3.76', '1.1.1.102', '1.1.1.213;1.1.1.50', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75']
27
185
TINIDAZOLE
5

100%|██████████| 11047/11047 [00:02<00:00, 4000.38it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3610.07it/s]
 91%|█████████ | 247/271 [54:38<05:26, 13.60s/it]

rxndb num 35
failedrxn num 0
result_df 12
['1.14.14.1', '1.7.1.9', '1.7.1.9', '1.7.1.-;1.7.1.16', '1.-.-.-;1.7.1', '1.7.1.-', '1.-.-.-', '1.12.99.6;1.2.7.1;1.2.7.4;1.2.99.2', '1.-.-.-', '1.7.1.-', '1.7.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.14.13.-', '1.14.13', '1.7.1.16', '1.7.1', '1.7.1.16', '3.2.1.35', '3.2.1.35', '1.14.14.22;1.14.99.46', '1.14.13.-', '1.7.1.-', '1.7.1.-', '2.6.1.114', '1.7.1.M3']
10
18
TOLAZAMIDE
5

100%|██████████| 11047/11047 [00:02<00:00, 4234.00it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3896.99it/s]
 92%|█████████▏| 248/271 [54:51<05:03, 13.20s/it]

rxndb num 43
failedrxn num 0
result_df 16
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '3.4.11.5', '3.4.11.5', '3.2.1.35', '3.2.1.35', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '3.4.15.6', '3.4.15.6', '3.4.19.7', '3.4.19.7', '2.6.1.114']
9
19
TOPOTECAN
5

100%|██████████| 11047/11047 [00:05<00:00, 2123.98it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3831.47it/s]
 92%|█████████▏| 249/271 [55:06<05:06, 13.92s/it]

rxndb num 1007
failedrxn num 0
result_df 70
['3.1.3.69', '3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.27', '3.1.3.74', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.1.23', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.6.2', '3.1.6.1;3.1.6.2', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.118;1.1.1.47', '1.1.1.119;1.1.1.47', '3.1.3.39', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.63', '1.14.13.63', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.4', '3.1.6.9', '3.1.6.10', '3.1.1.70', '1.14.13.19', '1.14.13.19', '1.1.1.173;1.1.1.378', '3.1.1.51', '1.14.13.-', '1.14.13.61', '1.14.13.61', '1.14.13.-', '3.1.3.69', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.-;3.1.3.88', '3.1.3.79', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '3.1.3.85', '1.14.-.-', '3.1.3.83', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.1.1.203', '1.1.1.203', '1.1.1.363;1.1.1.388', '1.1.1.390', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.103', '1.14.13.-;1.14.13.M56', '1.1.1.116', '1.1.1.359;1.1.1.376;1.1.1.46', '3.1.3', '3.1.3.-', '1.1.1.203', '6.3.2', '6.3.2', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.1', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.1.26', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.1.4', '3.1.1.23', '3.1.1.23', '3.1.1.13', '1.14.13', '1.14.13', '3.1.3', '1.1.1.-;1.1.1.377;1.1.1.378', '3.1.3.4', '3.1.3.4', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.1', '1.1.1.-', '1.1.1', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '3.1.3;3.1.3.-;3.1.3.104;3.1.3.2;3.1.3.29', '1.14.13;1.14.13.-', '1.14.13.8', '3.1.1.1;3.1.1.13;3.1.1.3', '3.1.1.3', '3.1.1.3', '3.1.6.14', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '1.2.3.1', '3.1.3.29', '3.1.3.29', '1.14.15.15', '1.1.1.179;1.3.1.20', '1.1.1.179;1.3.1.20', '3.1.3.33;3.1.3.5', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '3.1.6.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.91', '3.4.21;3.4.21.62', '3.4.16.5;3.4.21;3.4.21.62', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '1.14.14.55', '1.14.14.55', '3.1.3.48', '3.1.3.2;3.1.3.48;3.1.3.76', '3.1.3.36;3.1.3.48', '1.1.1.121', '3.1.3.2', '1.1.1.47', '3.1.3', '3.1.3', '3.1.6.3', '1.1.1.122', '3.1.3.68', '1.14.15.4', '1.14.15.4', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '3.2.1.154;3.2.1.26;3.2.1.80', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.55', '3.2.1.55', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.82', '3.2.1.15;3.2.1.82', '3.2.1.4;3.2.1.91', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '3.2.1.21;3.2.1.3', '3.2.1.65', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.145;3.2.1.23', '3.2.1.145;3.2.1.23', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.31', '3.2.1.31', '3.2.1.35', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '2.3.1.-', '1.14.13.10', '1.14.13.10', '3.1.3.91', '3.6.1;3.6.1.-', '1.14.13', '3.1.1', '3.2.1.137;3.2.1.78', '3.2.1.137;3.2.1.78', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '1.14.-.-', '1.14.-.-', '3.1.1.5', '3.1.3.23;3.1.3.29;3.1.3.9', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.1.3.27', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.11;3.1.3.37', '3.1.3', '3.1.3.24', '3.1.3.12', '3.1.3;3.1.3.2;3.1.3.48', '3.1.3.29', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.3.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '3.1.1.10', '1.1.1.113', '3.1.3.63', '3.1.3.63', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.21.3', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.185', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.-.-', '1.14.-.-', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.1.1.107;1.1.1.122', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3', '2.3.1.-', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '3.2.1.22;3.2.1.23', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.45', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.3.68', '1.1.1.363;1.1.1.388;1.1.1.47;1.1.1.49', '3.1.3.M8', '3.1.1.116', '3.1.3.106;3.1.3.76', '1.1.1.376', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '1.1.1.420', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.1.3.58;3.1.3.9', '3.1.6.3', '1.1.1.120', '3.2.1.14', '3.2.1.14', '1.1.1.121;1.1.1.175', '1.1.1.121', '1.1.1.179', '1.1.1.179', '3.2.1.37', '3.2.1.37', '3.2.1.37', '3.2.1.37', '1.1.1.46', '1.1.1.46', '3.2.1.55', '3.2.1.55', '3.2.1.55', '3.2.1.55', '3.2.1.3;3.2.1.58;3.2.1.59', '3.2.1.3;3.2.1.58;3.2.1.59', '3.1.3.29', '3.2.1.4', '3.2.1.4', '3.2.1.4', '3.2.1.4', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.1.1.121', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '3.2.1.116', '3.2.1.116', '3.2.1.60', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.4.15.6', '3.4.15.6', '3.2.1.1', '3.2.1.1', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.2', '3.2.1.2', '3.1.-.-', '3.1.-.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.174', '3.2.1.153;3.2.1.26;3.2.1.80', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.15.5', '3.2.1.15', '3.2.1.15', '4.2.2.2', '4.2.2.2', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '3.2.1.137', '3.2.1.137', '1.1.1.117', '1.1.1.117', '1.1.1.117', '1.1.1.117', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '3.1.1.5', '3.1.3.27', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.46', '1.1.1.46', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.176', '1.14.13.176', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '3.1.3', '3.1.3.73', '3.2.1.143', '3.1.3.73', '3.1.3', '3.1.3.73', '4.2.1.140;4.2.1.39', '4.2.1.140;4.2.1.39', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '4.2.1.6', '4.2.1.6', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.106', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '1.14.13.98', '1.14.13.98', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.1.1.363;1.1.1.49', '3.1.3.82', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.1.88', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.190', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.1.1.118', '1.1.1.120;1.1.1.179;1.1.1.359;1.1.1.360;1.1.1.47;1.1.1.48;1.3.1.20', '1.1.1.120', '3.1.3.58;3.1.3.9', '1.17.99.5', '1.17.99.5', '1.1.1.119', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.1.1.121;1.1.1.359;1.1.1.47;1.1.1.48', '1.1.1.121', '1.14.14.8', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.1.1.363;1.1.1.47;1.1.1.49', '1.1.1.49', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1.424', '3.1.3.76', '3.1.3.76', '1.14.13.3;1.14.14.9', '1.14.13.127', '4.2.3;4.2.3.1', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75']
39
258
TRANDOLAPRIL
5

100%|██████████| 11047/11047 [00:03<00:00, 3390.15it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3411.04it/s]
 92%|█████████▏| 250/271 [55:21<04:57, 14.17s/it]

rxndb num 1234
failedrxn num 0
result_df 145
['1.2.1.3;1.2.1.54', '1.2.1.-;1.2.1.99', '3.4.13.18;3.4.13.9', '1.1.1.23', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.1.5', '1.2.1.3', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.15', '4.1.1.30', '4.1.1.36', '1.2.1.24;1.2.1.5;1.2.1.88;1.5.1.12', '1.5.1.12', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.1.23', '1.2.1.3;1.2.1.47', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.2.1.40', '3.1.1.70', '3.1.1.51', '1.14.13.72', '1.14.13.22', '1.2.1.-;1.2.1.99', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.5.1;1.5.1.-', '1.5.1;1.5.1.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.-.-', '1.14.-.-', '1.2.1.-;1.2.1.M5', '1.2.1.-;1.2.1.83', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.3;6.3.-.-', '6.3.2', '6.3.2', '3.1.1;3.1.1.1;3.1.1.3', '1.14.13;1.14.13.-', '1.3.1', '1.3.1', '1.2.1;1.2.1.-', '3.1.1', '1.3.1', '1.3.1', '1.3.1', '3.1.1', '3.1.1.26', '1.14.14', '1.14.14', '1.14.14', '3.1.1.4', '3.1.1.23', '3.1.1.23', '3.1.1.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '1.2.1', '3.1.1', '1.1.1.-', '1.1.1.-', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '3.1.1.1;3.1.1.13;3.1.1.3', '3.1.1.1;3.1.1.3', '3.1.1.3', '3.1.1.3', '3.1.1.1', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '1.2.1.47', '1.14.15.15', '1.14.15.15', '3.1.1.1;3.1.1.2', '3.1.1.1;3.1.1.2', '3.1.1.1;3.1.1.2', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.2.1.19;1.2.1.3', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '3.4.21;3.4.21.62', '3.4.16.5;3.4.21;3.4.21.62', '6.3.1.2', '1.14.13', '1.14.13', '1.14.13', '6.3.4.2', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.2.3.1', '1.14.13.72', '3.4.11.5', '3.4.11.5', '3.4.11.5', '1.1.1.23;1.1.1.24', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '6.3.2.17', '6.3.2.17', '6.3.2.17', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '3.2.1.35', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '2.3.1.-', '3.1.1', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.1.5', '3.1.1.5', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.30', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.23', '1.2.1.31', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '3.1.1.10', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.2.1.3', '2.-.-.-', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.72', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.78', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.-.-;1.14.13.-', '1.14.-.-;1.14.13.-', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.3.1.-', '1.2.1.31', '1.2.1.95;1.2.1.z', '1.2.1.31', '1.2.1.3', '1.14.14.22;1.14.99.46', '1.2.1.3', '1.14.13.M76', '1.14.13.M76', '1.14.13.M76', '3.1.1.116', '1.2.1.101;1.2.1.ah', '1.2.1.-', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.2.1.14', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-;1.14.13.-', '1.14.-.-;1.14.13.-', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.87', '3.4.15.6', '3.4.15.6', '3.4.15.6', '3.4.19.9', '3.4.19.9', '3.4.19.9', '3.4.19.7', '3.4.19.7', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.-', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.2.1.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '3.1.-.-', '3.1.-.-', '1.14.11.-', '1.14.11.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.15.5', '1.14.15.5', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.2.1.70;6.1.1.17', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '3.1.1.5', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.194', '1.14.13.194', '3.1.1.101', '3.1.1.101', '3.1.1.101', '3.2.1.143', '3.5.1', '1.14.13.15', '1.3.99.-', '1.3.99.-', '1.3.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.2.1.3;1.2.1.40', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '1.2.1', '1.2.1', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1;1.1.1.206', '3.1.1.3', '1.2.1;1.2.1.19;1.2.1.3', '1.2.1;1.2.1.-;1.2.1.19;1.2.1.3', '1.2.1.3;1.2.1.5', '1.2.1.5']
45
143
TRANILAST
5

100%|██████████| 11047/11047 [00:02<00:00, 4440.43it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3597.22it/s]
 93%|█████████▎| 251/271 [55:34<04:34, 13.73s/it]

rxndb num 1065
failedrxn num 0
result_df 120
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.1.1.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.2.3.1;1.2.3.8', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.2.1.67', '1.2.1.28;1.2.1.64;1.2.1.96', '1.2.1.29;1.2.3.1', '1.2.1.29;1.2.3.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.1', '4.1.1.46', '4.1.1.24', '4.1.1.61', '1.2.1.7;1.2.1.96', '1.14.13.64', '1.14.13.64', '4.1.1.24', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '4.1.1.62', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.27', '1.14.13.27', '1.14.13.24', '4.1.1.-', '4.1.1.58', '1.2.1.-;1.2.1.3;1.2.1.65', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '4.1.1.59', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '4.1.1.52', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '3.4.22.40;3.5.1.72', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.2.3.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.2.1.78', '1.2.1.28;1.2.1.7', '4.1.2.61;4.2.1.101', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.180', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.2.1.7', '1.2.1.28;1.2.1.3;1.2.1.64', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '2.1.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '4.1.1.91', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '6.3.1.18', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.3.2.14', '3.3.2.14', '4.1.1.103', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '3.5.1.123', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.2.1;1.2.1.-;1.2.1.3', '1.2.1.19;1.2.1.24;1.2.1.29;1.2.1.3;1.2.1.5;1.2.1.88', '1.14.13.1', '1.3.1.74', '1.14.13', '1.14.13', '4.2.1.17', '1.3.1.117', '1.14.-.-', '1.14.-.-', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1.415;1.1.1.ee', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1', '1', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.2.1', '1.2.1.29', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.24', '1.14.13.24', '1.2.1.7', '1.2.1.7', '3.5.1', '4.1.1.-;4.1.1.98', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '4.1.1;4.1.1.-', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '4.1.1;4.1.1.-', '1.14.13.1', '1.14.13.1', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '2.3.2.2;3.4.11.10;3.4.19.3', '1.2.1.19', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.2.1.5;1.2.1.88', '3.4.21.4;3.4.22;3.4.22.1', '1.14.13.24', '1.14.13.24', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.3.1;1.2.3.8', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.2.1.3', '1.2.1.3', '1.2.1.3', '1.2.1.3', '1.2.1.3', '1.2.1.3;1.2.1.5', '1.14.14.57', '1.14.14.57', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.-', '1.14.13.-', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.82', '3.2.1.15;3.2.1.82', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.76', '3.2.1.76', '3.2.1.31', '3.2.1.31', '3.2.1.35', '3.2.1.35', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '2.4.1.-', '2.4.1.-', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.140', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.1.1.415', '1.14.14.22;1.14.99.46', '1.3.1.n3', '1.3.1.n3', '4.2.1.175', '4.1.1.98', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.3.1.117', '4.2.1.175', '4.1.1.118', '4.2.1.101', '1.2.3.1', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.2.1.87', '3.2.1.87', '3.4.19.7', '3.4.19.7', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.15', '3.2.1.15', '4.2.2.2', '4.2.2.2', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.140', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.1.101', '3.1.1.101', '3.2.1.143', '3.2.1.143', '4.1.2.61', '4.1.2.61', '4.1.2.41;4.1.2.61', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.M82', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.3.1.74', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '4.1.1;4.1.1.-', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127']
38
142
TRAZODONE
5

100%|██████████| 11047/11047 [00:03<00:00, 3005.70it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4624.52it/s]
 93%|█████████▎| 252/271 [55:46<04:15, 13.45s/it]

rxndb num 193
failedrxn num 0
result_df 31
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.8.1.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.224', '1.14.13.224', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.8', '3.8.1.8', '3.4.11.5', '1.14.14.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '3.4.15.6', '1.3.98.-', '3.2.1.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.19.58', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14']
10
30
TRIHEXYPHENIDYL
5

100%|██████████| 11047/11047 [00:02<00:00, 3764.96it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3706.71it/s]
 93%|█████████▎| 253/271 [56:00<04:02, 13.48s/it]

rxndb num 922
failedrxn num 0
result_df 77
['3.1.3.69', '3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.74', '3.1.3.27', '3.1.3.74', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3.22;3.1.3.23', '3.1.3.39', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.6.9', '3.1.6.10', '3.1.3.69', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.1.3.-;3.1.3.88', '3.1.3.79', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '3.1.3.85', '3.1.3.83', '1.14.13.-', '3.1.3.92', '1.14.13.209', '1.14.13.209', '1.14.13.209', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.3.103', '3.1.3', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '1.3.1', '1.14.14.133', '1.3.1', '1.3.1', '1.3.1', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.50', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3', '3.1.6.c', '3.1.3.4', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '1.3.1', '3.1.6.14', '3.1.3.29', '3.1.3.29', '3.1.3.33;3.1.3.5', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '3.1.3', '3.1.3', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '3.2.1.78', '3.1.3', '3.1.3', '3.1.6.3', '3.1.3.68', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '3.2.1.154;3.2.1.26;3.2.1.80', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '3.2.1.65', '3.2.1.145;3.2.1.23', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '3.1.3.91', '3.6.1;3.6.1.-', '3.2.1.137;3.2.1.78', '3.1.3.2;3.1.3.31;3.1.3.34', '1.3.1;1.3.1.-', '1.3.1;1.3.1.-', '1.3.1;1.3.1.-', '3.1.3.29', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.23;3.1.3.29;3.1.3.9', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '3.1.3.27', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.24', '3.1.3.12', '3.1.3.29', '3.1.3.-', '3.1.3.63', '3.1.3.63', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '3.1.3.45', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.3.68', '3.1.3.M8', '3.1.3.105', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.1.3.58;3.1.3.9', '3.1.6.3', '3.2.1.3;3.2.1.58;3.2.1.59', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.1', '1.7.3.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '3.2.1.2', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.137', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '3.1.3.27', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.156', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.82', '1.3.99.-', '1.3.99.-', '1.3.99.-', '3.1.3.29;3.1.3.50', '3.1.3.50', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '3.1.3.58;3.1.3.9', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '1.11.2.6', '1.11.2.6', '1.11.2.6', '3.1.3.76', '3.1.3.76', '4.2.3;4.2.3.1', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '3.1.3.1;3.1.3.75']
31
158
TRIMEBUTINE MALEATE
5

100%|██████████| 11047/11047 [00:02<00:00, 3859.98it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4022.78it/s]
 94%|█████████▎| 254/271 [56:12<03:44, 13.20s/it]

rxndb num 625
failedrxn num 0
result_df 67
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.1.5', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.19', '1.14.13.19', '3.1.1.60', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.180', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-', '2.1.1.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.13.8', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.-.-', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '3.3.2.14', '3.3.2.14', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13', '1.14.13', '1.14.13;1.14.13.-', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.1', '1.1.1.415;1.1.1.ee', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.15.15', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.1.1', '3.1.1.1', '1.14.13.8', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.-', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.82', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.76', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.-.-', '2.4.1.-', '2.4.1.-', '1.14.-.-', '1.14.-.-', '3.1.1.5', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.30', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.-.-', '1.14.-.-', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.1.1.415', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-', '1.14.-.-', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.174', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.15.5', '3.2.1.15', '4.2.2.2', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.184', '1.14.13.184', '1.14.13.194', '3.2.1.143', '3.2.1.143', '3.2.1.143', '3.1.1.1;3.1.1.84', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9']
27
96
TRIMETAZIDINE DIHYDROCHLORIDE
5

100%|██████████| 11047/11047 [00:02<00:00, 4183.62it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3441.26it/s]
 94%|█████████▍| 255/271 [56:26<03:33, 13.34s/it]

rxndb num 221
failedrxn num 0
result_df 32
['1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.5.3.13;1.5.3.17', '1.5.3.13', '1.5.3.13;1.5.3.17', '1.14.14.1', '1.14.14.1', '2.5.1.46', '1.5.3.14;1.5.99.6', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.14.13.4', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.5.3.15;1.5.3.17', '1.5.1.-;1.5.1.43', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '3.3.2.14', '3.3.2.14', '3.3.2.14', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.5.3.16', '1.5.3.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.5.3.14', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.5.3.16', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '2.4.1.-', '2.4.1.-', '2.4.1.-', '1.5.3.11;1.5.3.13;1.5.3.16;1.5.3.17', '1.5.3;1.5.3.13;1.5.3.16;1.5.3.17', '1.14.14.1', '1.14.14.1', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.88', '1.14.13.88', '1.5.1.43', '1.14.13.9', '1.14.13.9', '1.5.1.43', '3.2.1.87', '3.2.1.87', '3.2.1.87', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '6.2.1.3', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.143', '3.2.1.143', '3.2.1.143', '1.14.13.-', '1.14.13.-', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.11.2.6', '1.11.2.6']
21
58
TRIMETHOBENZAMIDE
5

100%|██████████| 11047/11047 [00:02<00:00, 4530.35it/s]
100%|██████████| 27873/27873 [00:06<00:00, 3988.14it/s]
 94%|█████████▍| 256/271 [56:38<03:14, 12.96s/it]

rxndb num 376
failedrxn num 0
result_df 52
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.5.1.40', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.180', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '3.3.2.14', '3.3.2.14', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13', '1.14.13', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.8', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.-', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '6.3.2.17', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.35', '1.14.14.1', '1.14.14.91', '1.14.14.91', '1.14.14.91', '2.4.1.-', '2.4.1.-', '2.4.1.-', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.4.15.6', '3.4.19.9', '3.4.19.7', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.2.1.3', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.1.101', '3.2.1.143', '3.2.1.143', '3.2.1.143', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.14.13.127', '1.14.13.127', '1.14.13.127']
27
71
TRIMIPRAMINE MALEATE
5

100%|██████████| 11047/11047 [00:04<00:00, 2614.02it/s]
100%|██████████| 27873/27873 [00:05<00:00, 4684.40it/s]
 95%|█████████▍| 257/271 [56:51<03:02, 13.02s/it]

rxndb num 85
failedrxn num 0
result_df 17
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.5.1.44', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13', '1.14.13.8', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.13.30', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.194', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190']
5
21
TRIPROLIDINE
5

100%|██████████| 11047/11047 [00:02<00:00, 3720.73it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4244.23it/s]
 95%|█████████▌| 258/271 [57:04<02:47, 12.90s/it]

rxndb num 126
failedrxn num 0
result_df 23
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.235', '1.2.3.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.M64', '1.3.99.-', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '2.6.1.114']
8
24
TROPISETRON
5

100%|██████████| 11047/11047 [00:03<00:00, 3582.94it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3715.44it/s]
 96%|█████████▌| 259/271 [57:17<02:35, 12.98s/it]

rxndb num 709
failedrxn num 0
result_df 59
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.17.1.5', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.99.2', '1.14.99.2', '1.14.12.16', '1.14.13.61', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.13.130', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.224', '1.14.13.224', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.14.133', '1.1.1.415;1.1.1.ee', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '1.3.1', '1.14.13.235', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.13.11', '1.14.12.16', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.8', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.1.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.13.11.52', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.13.-', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '1.3.1;1.3.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.13.11.52', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.13.11.11;1.13.11.52', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.13.11.11;1.13.11.52', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.13.88', '1.14.13.88', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.19.41;1.3.1.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.88', '1.14.13.88', '1.1.1.415', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '3.2.1.87', '3.4.15.6', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.13.11.52', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.88', '1.14.13.88', '1.14.13.176', '1.14.13.176', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '3.2.1.143', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '3.1.1.1;3.1.1.84', '1.3.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.182', '1.14.13.182', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.13.11.52', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.13.11.52']
33
102
TROSPIUM CHLORIDE
5

100%|██████████| 11047/11047 [00:03<00:00, 3162.75it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4030.23it/s]
 96%|█████████▌| 260/271 [57:31<02:25, 13.24s/it]

rxndb num 909
failedrxn num 0
result_df 92
['3.1.3.69', '3.1.3.74', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.74', '3.1.3.74', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.73', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3.39', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.14.13.4', '1.14.13.4', '3.1.6.9', '3.1.6.10', '3.1.1.70', '3.1.1.51', '3.1.3.69', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.1.3.-;3.1.3.88', '1.14.13.105', '3.1.3.79', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '3.1.3.85', '3.1.3.83', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.1.1.203', '1.1.1.203', '1.1.1.363;1.1.1.388', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.103', '1.14.14.108', '1.14.14.108', '3.1.3', '3.1.3.-', '1.1.1.203', '6.3.2', '6.3.2', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.14.14.133', '1.14.13', '1.14.13', '1.14.13', '3.1.1', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.1.26', '1.14.14', '1.14.14', '1.14.14', '3.1.1.4', '3.1.1.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3.4', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.1', '1.1.1.-', '1.14.13.105', '3.1.1.1;3.1.1.13;3.1.1.3', '3.1.6.14', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.3.29', '1.1.1.179;1.3.1.20', '3.1.3.33;3.1.3.5', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '3.4.21;3.4.21.62', '3.4.16.5;3.4.21;3.4.21.62', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '3.2.1.78', '3.2.1.78', '1.1.1.47', '3.1.3', '3.1.3', '1.1.1.122', '3.1.3.68', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.13.36', '1.14.13.36', '1.14.13.36', '3.4.11.5', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.82', '3.2.1.4;3.2.1.91', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.31', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '2.3.1.-', '3.1.3.91', '3.6.1;3.6.1.-', '3.1.1', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.1.5', '3.1.1.5', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.24', '3.1.3.12', '3.1.3.29', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.3.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '3.1.1.10', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3', '2.3.1.-', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.45', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.1.1.363;1.1.1.388;1.1.1.47;1.1.1.49', '3.1.3.M8', '3.1.3.105', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.1.1.420', '3.2.1.14', '1.1.1.121;1.1.1.175', '1.1.1.121', '1.1.1.179', '1.1.1.179', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.54', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.2.1.1', '1.14.13.-', '1.14.13.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '3.2.1.2', '3.1.-.-', '3.1.-.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '3.2.1.15', '4.2.2.2', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '3.1.1.5', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '3.1.1.101', '3.1.3', '3.1.3.73', '3.2.1.143', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '1.14.13.149', '3.2.1.23', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.1.1.363;1.1.1.49', '3.1.3.82', '3.1.1.88', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.1.1.363;1.1.1.47;1.1.1.49', '1.1.1.49', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '1.14.13.127', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75']
37
191
VALSARTAN
5

100%|██████████| 11047/11047 [00:03<00:00, 3290.75it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3421.78it/s]
 96%|█████████▋| 261/271 [57:46<02:16, 13.66s/it]

rxndb num 451
failedrxn num 0
result_df 64
['1.2.1.-;1.2.1.99', '3.4.13.18;3.4.13.9', '1.1.1.23', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.2.1.3', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.13.15', '4.1.1.30', '4.1.1.36', '1.2.1.3;1.2.1.47', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.17.1.1', '1.17.1.1', '1.2.1.40', '1.3.1.5', '1.3.1.5', '1.3.1.48', '1.3.1.48', '1.14.13.72', '1.14.13.181', '1.2.1.-;1.2.1.99', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.2.1.-;1.2.1.83', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '6.3;6.3.-.-', '1.3.3.6', '1.14.13;1.14.13.-', '1.2.1;1.2.1.-', '1.3.1.93', '1.3.1.93', '1.3.1.93', '1.3.1.93', '1.3.1.93', '1.3.1.93', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '1.3.1', '1.2.1', '1.1.1.-', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.3.3.6', '1.3.1.48', '1.3.1.48', '1.3.1.48', '1.2.1.47', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.99.1', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.72', '3.4.11.5', '3.4.11.5', '1.1.1.23;1.1.1.24', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.-.-', '1.14.-.-', '1.14.13.15;1.14.15.15', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.30', '1.14.13.30', '1.1.1.23', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.3.1.104;1.3.1.38;1.3.1.8', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.72', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.79', '1.3.1.104;1.3.1.38;1.3.1.44;1.3.1.8', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.-.-;1.14.13.-', '1.14.-.-;1.14.13.-', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1;1.3.1.44', '1.3.99.-', '1.3.99.3', '1.1.1;1.3.99.3', '1.3.1.9', '1.2.1.3', '1.14.14.22;1.14.99.46', '1.3.1.42', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-', '1.14.-.-', '3.4.15.6', '3.4.15.6', '3.4.19.7', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '3.2.1.-', '3.2.1.-', '1.2.1.-', '1.14.99.-', '1.14.99.-', '1.14.11.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.174', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.194', '1.14.13.194', '1.3.3.6', '1.3.1.93', '1.3.3.6', '1.3.1.104;1.3.1.38;1.3.1.8', '1.14.13.15', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.2.1.3;1.2.1.40', '1.3.3.6;1.3.8.1;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.3.3.6', '1.3.3.6', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.3.1.10;1.3.1.38;1.3.1.8', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.13.11.90', '1.2.1', '1.2.1', '1.13.11.90', '1.1.1;1.1.1.206', '1.2.1.19;1.2.1.3;1.2.1.8', '1.2.1.19;1.2.1.8']
26
85
VENLAFAXINE
5

100%|██████████| 11047/11047 [00:02<00:00, 4539.02it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3548.83it/s]
 97%|█████████▋| 262/271 [57:58<02:00, 13.39s/it]

rxndb num 766
failedrxn num 0
result_df 53
['3.1.3.69', '3.1.3.74', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.27', '3.1.3.74', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.6.2', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3.39', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.6', '1.14.13.6', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.14.13.4', '3.1.6.9', '3.1.6.10', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-', '1.14.13.-', '3.1.3.69', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.76', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '3.1.3.-;3.1.3.88', '3.1.3.79', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '3.1.3.85', '3.1.3.83', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '2.1.1.-', '3.1.3.103', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '3.1.3', '1.14.13', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '1.14.14.133', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3', '3.1.6.c', '3.1.3.4', '3.1.3.4', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '4.1.99.16', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.8', '3.1.6.14', '3.1.3.29', '1.1.1.1', '3.1.3.33;3.1.3.5', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '3.2.1.78', '3.1.3', '3.1.3', '3.1.6.3', '3.1.3.68', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.13.36', '1.14.13.36', '3.2.1.154;3.2.1.26;3.2.1.80', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '3.2.1.65', '3.2.1.145;3.2.1.23', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '3.1.3.91', '3.6.1;3.6.1.-', '3.2.1.137;3.2.1.78', '3.1.3.2;3.1.3.31;3.1.3.34', '1.3.1;1.3.1.-', '1.3.1;1.3.1.-', '3.1.3.29', '2.4.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.23;3.1.3.29;3.1.3.9', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.1.3.27', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.24', '3.1.3.12', '3.1.3.29', '3.1.3.-', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '3.1.3.63', '3.1.3.63', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '3.1.3.45', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.3.68', '3.1.6.d', '3.1.3.M8', '3.1.3.106;3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '3.1.3.58;3.1.3.9', '3.1.6.3', '3.2.1.3;3.2.1.58;3.2.1.59', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.2.1.1', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '3.2.1.2', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '3.2.1.137', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '3.1.3.27', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.106', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.82', '1.3.99.-', '1.3.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.190', '1.14.13.190', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '3.1.3.58;3.1.3.9', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.11.2.6', '1.11.2.6', '3.1.3.76', '3.1.3.76', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '4.2.3;4.2.3.1', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '3.1.3.1;3.1.3.75']
35
179
VERAPAMIL
5

100%|██████████| 11047/11047 [00:02<00:00, 4239.64it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3877.65it/s]
 97%|█████████▋| 263/271 [58:11<01:46, 13.29s/it]

rxndb num 887
failedrxn num 0
result_df 94
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.15.6', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.-.-', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '3.3.2.14', '3.3.2.14', '3.3.2.14', '3.3.2.14', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.8', '1.14.13.8', '1.14.15.15', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '3.2.1.78', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '1.14.-.-', '1.3.1;1.3.1.-', '2.4.1.-', '2.4.1.-', '2.4.1.-', '2.4.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.15;1.14.15.15', '1.14.13.15;1.14.15.15', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.46', '1.14.13.46', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.-.-', '1.14.-.-', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.3.1.-;1.3.1.72;1.3.1.M20', '1.3.1.-;1.3.1.71', '1.14.19.41;1.3.1.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-;1.14.13.-', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '1.14.13.141', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.2.1.87', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.15.5', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.159', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.194', '1.14.13', '1.14.13.M64', '1.14.13.M64', '1.14.13.15', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.3.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.14.13.159']
25
87
VILAZODONE
5

100%|██████████| 11047/11047 [00:03<00:00, 3308.92it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4471.47it/s]
 97%|█████████▋| 264/271 [58:24<01:30, 12.96s/it]

rxndb num 244
failedrxn num 0
result_df 46
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.10.1.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.224', '1.14.13.224', '1.14.13.235', '1.14.13', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.13.11', '1.3.1', '1.14.13;1.14.14', '1.14.13;1.14.14', '1.14.13;1.14.14', '2.3.2.2;6.3.1.2', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.13.11.52', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.14.1', '1.13.11.52', '1.13.11.11;1.13.11.52', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.13.11.11;1.13.11.52', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.4.15.6', '3.2.1.-', '1.13.99.3', '1.13.11.52', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.176', '1.14.13', '1.14.13', '1.14.13.M64', '1.14.13.M64', '1.3.99.-', '1.14.13.182', '1.14.13.182', '1.13.99.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.13.11.52', '1.13.11.52']
19
47
VINPOCETINE
5

100%|██████████| 11047/11047 [00:06<00:00, 1587.41it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4208.66it/s]
 98%|█████████▊| 265/271 [58:40<01:23, 13.89s/it]

rxndb num 768
failedrxn num 0
result_df 72
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.1.5', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.1.23', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.99.2', '1.14.99.2', '3.1.1.70', '3.1.1.51', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.3.2', '6.3.2', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.1', '1.3.1', '1.3.1', '3.1.1', '3.1.1.26', '3.1.1.4', '3.1.1.23', '3.1.1.23', '3.1.1.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '1.3.1', '3.1.1', '1.1.1.-', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '3.1.1.1;3.1.1.13;3.1.1.3', '3.1.1.1;3.1.1.3', '3.1.1.3', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '1.14.15.15', '1.14.15.15', '3.1.1.1;3.1.1.2', '3.1.1.1;3.1.1.2', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '3.4.21;3.4.21.62', '3.4.16.5;3.4.21;3.4.21.62', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.2.1.74', '3.4.11.5', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '2.3.1.-', '3.1.1', '1.14.-.-', '1.14.-.-', '1.3.1;1.3.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.1.5', '3.1.1.5', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.30', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '3.1.1.10', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.-;1.14.13.146', '1.14.13.-;1.14.13.146', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '2.3.1.-', '1.14.19.41;1.3.1.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.M76', '1.14.13.M76', '1.14.13.M76', '3.1.1.116', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.87', '3.4.15.6', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '3.1.-.-', '3.1.-.-', '1.13.99.3', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.-.-', '1.-.-.-', '1.14.13.174', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.15.5', '1.14.15.5', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '3.1.1.5', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.176', '1.14.13.176', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.194', '1.14.13.194', '1.14.13', '3.2.1.143', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.3.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.182', '1.14.13.182', '1.13.99.3', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.6.1.18;3.6.1.9', '3.1.1.3']
28
94
VORICONAZOLE
5

100%|██████████| 11047/11047 [00:02<00:00, 4020.16it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3650.31it/s]
 98%|█████████▊| 266/271 [58:53<01:08, 13.69s/it]

rxndb num 172
failedrxn num 0
result_df 23
['3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '3.1.3.74', '3.1.3.74', '3.1.3.73', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '3.1.3.39', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.1.3.-;3.1.3.88', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3;3.1.3.-', '1.14.13.224', '1.14.13.224', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.13', '1.17.1.4', '1.17.1.4', '3.1.3.33;3.1.3.5', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.17.3.2', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3.91', '3.6.1;3.6.1.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '3.1.3.73', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.1.3.M8', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '3.1.3.-;3.1.3.104']
10
52
WARFARIN
5

100%|██████████| 11047/11047 [00:02<00:00, 4314.27it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3514.80it/s]
 99%|█████████▊| 267/271 [59:06<00:54, 13.59s/it]

rxndb num 1666
failedrxn num 0
result_df 125

100%|██████████| 11047/11047 [00:03<00:00, 2806.24it/s]
100%|██████████| 27873/27873 [00:05<00:00, 4696.08it/s]
 99%|█████████▉| 268/271 [59:19<00:40, 13.36s/it]

rxndb num 125
failedrxn num 0
result_df 22
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.5.5.2', '1.14.13.61', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.224', '1.14.13.224', '1.14.13.224', '1.14.13.224', '1.14.13.235', '1.14.13.235', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.8', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.18.2', '6.3.4.20', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.7.1.13', '1.14.18.2', '1.14.13.182', '1.14.13.182', '1.1.1;1.1.1.206']
8
28
ZIDOVUDINE [AZT]
5

100%|██████████| 11047/11047 [00:02<00:00, 4255.57it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3751.26it/s]
 99%|█████████▉| 269/271 [59:32<00:26, 13.30s/it]

rxndb num 300
failedrxn num 0
result_df 34
['3.1.3.69', '1.1.1.23', '3.1.3.15', '3.1.3.74', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.74', '3.1.3.27', '3.1.3.74', '1.1.1.1', '3.1.3.73', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.1.3.23', '3.1.3.39', '3.1.3.40', '3.1.6.9', '3.1.6.10', '1.1.3.39', '3.1.3.69', '1.14.13.-', '2.4.2.4', '2.4.2.3;2.4.2.4', '1.1.1.1', '1.1.1.1', '1.1.3.-;1.1.3.43', '3.1.3.-;3.1.3.88', '1.1.3.-;1.1.3.44', '3.1.3.79', '3.1.3.85', '3.1.3.83', '1.1.3;1.1.3.-', '3.1.3.92', '2.4.2.57', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '3.1.3.101', '3.1.3.-', '1.1.3.-', '3.1.3;3.1.3.-', '1.14.13.224', '1.14.13.224', '3.1.3.103', '3.1.3', '1.1.1.1', '3.1.3.-', '5.4.99.30;5.4.99.9', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.13', '1.1.1', '3.1.3', '1.1.1', '1.14.13', '1.14.13', '1.1.3.48', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '4.2.1.M11', '1.1.1', '1.1.1.1', '3.1.6.14', '3.1.3.29', '3.1.3.33;3.1.3.5', '1.1.3.9', '3.2.1.78', '3.2.1.78', '2.4.2.2;2.4.2.3;2.4.2.4', '3.1.3', '3.1.3', '3.1.6.3', '3.1.3.68', '3.8.1.7', '1.14.15.4', '1.14.15.4', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.55', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.82', '3.2.1.15;3.2.1.82', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.145;3.2.1.23', '3.2.1.35', '3.2.1.35', '1.14.14.1', '3.1.3.91', '3.6.1;3.6.1.-', '3.2.1.137;3.2.1.78', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '3.1.3.23;3.1.3.29;3.1.3.9', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.27', '1.14.13.30', '3.1.3', '3.1.3.24', '2.4.2.2;2.4.2.3;2.4.2.4', '3.1.3.12', '1.1.1.-', '1.1.1.136', '1.1.1.132', '1.1.3.9', '3.1.3.29', '3.1.3.-', '1.1.1.23', '1.14.13.74', '1.14.13.74', '1.1.1.186', '2.-.-.-', '2.-.-.-', '3.1.3.70', '1.1.1.273', '1.1.1.273', '1.1.1.273', '1.14.13.74', '1.14.13.74', '1.1.1.186', '1.14.13.97', '1.14.13.97', '2.4.2.3;2.4.2.4', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.1.1.317', '1.1.1.317', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '3.1.3.45', '1.1.1.-;1.1.1.336', '1.1.1.22', '3.1.3.68', '2.4.2.1;2.4.2.2;2.4.2.23;2.4.2.3;2.4.2.4', '3.1.3.M8', '1.1.1.273', '3.1.3.105', '3.2.2.3;3.2.2.8', '3.1.3.58;3.1.3.9', '3.1.6.3', '3.2.2.3', '1.1.3.9', '1.1.3.9', '3.2.1.14', '3.2.1.14', '3.2.1.37', '3.2.1.37', '3.2.1.55', '3.2.1.55', '3.2.1.3;3.2.1.58;3.2.1.59', '3.1.3.29', '3.2.2.-;3.2.2.8', '3.2.1.4', '3.2.1.4', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.4.15.6', '3.4.15.6', '3.2.1.1', '1.7.3.-', '1.7.3.-', '1.7.3.-', '3.2.1.-', '3.2.1.-', '3.2.1.2', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.15.5', '1.14.15.5', '6.2.1.3', '3.2.1.137', '3.1.3.27', '3.1.3', '3.1.3.73', '3.2.1.143', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.73', '3.1.3', '1.1.1.2;1.1.1.20;1.1.1.21', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '2.4.2.2', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '3.2.2.3;3.2.2.8', '3.1.3.82', '3.1.3.58;3.1.3.9', '2.6.1.114', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '3.1.3.76', '1.1.1.1', '4.2.3;4.2.3.1', '3.1.3.-;3.1.3.104']
28
164
ZIPRASIDONE MESYLATE
5

100%|██████████| 11047/11047 [00:03<00:00, 3346.85it/s]
100%|██████████| 27873/27873 [00:07<00:00, 3858.05it/s]
100%|█████████▉| 270/271 [59:46<00:13, 13.31s/it]

rxndb num 164
failedrxn num 0
result_df 38
['3.1.1.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.8.1.7', '3.4.22.40;3.5.1.72', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '6.3.1.18', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.5.1.123', '1.14.13', '1.14.13', '1.11.2.M1', '3.5.1', '3.4.11.3;3.4.11.6;3.4.22.40', '2.3.2.2;3.4.11.10;3.4.19.3', '3.4.21.4;3.4.22;3.4.22.1', '3.3.2.6;3.4.11.10;3.4.11.15', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.4.11.5', '1.14.14.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.137', '1.14.13.138', '1.14.13.140', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '3.4.15.6', '1.3.98.-', '3.2.1.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.137', '1.14.13.138', '1.14.13.140', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13', '1.14.13', '1.14.19.58', '1.1.1;1.1.1.206']
19
47
ZOLPIDEM
5

100%|██████████| 11047/11047 [00:02<00:00, 3997.16it/s]
100%|██████████| 27873/27873 [00:06<00:00, 4177.20it/s]
100%|██████████| 271/271 [59:58<00:00, 13.28s/it]

rxndb num 130
failedrxn num 0
result_df 25
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.61', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.8', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.224', '1.14.13.224', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.235', '1.14.13.8', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.8', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.138', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.13.99.3', '1.14.-.-', '1.-.-.-', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.138', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.182', '1.14.13.182', '1.13.99.3', '2.6.1.114', '2.6.1.114', '1.13.99.3', '1.1.1;1.1.1.206']
9
32

In [12]:
result_df

,ID,reactant_smile,productsmile,rxn_smiles_basic,templateID,EC number,productsmile_num
0,rxn1,Cc1ccc(-c2nc3c(O)cc(C)cn3c2CC(=O)N(C)C)cc1.O,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1.O=O,Cc1ccc(-c2nc3c(O)cc(C)cn3c2CC(=O)N(C)C)cc1.O>>...,MNXR101068_reverse,1.14.13.-;1.14.14.-;1.14.14.1,1
1,rxn2,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)c(O)c1.O,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1.O=O,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)c(O)c1.O>>...,MNXR101068_reverse,1.14.13.-;1.14.14.-;1.14.14.1,1
2,rxn3,Cc1ccc(-c2nc3cc(O)c(C)cn3c2CC(=O)N(C)C)cc1.O,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1.O=O,Cc1ccc(-c2nc3cc(O)c(C)cn3c2CC(=O)N(C)C)cc1.O>>...,MNXR101068_reverse,1.14.13.-;1.14.14.-;1.14.14.1,1
3,rxn4,Cc1ccc2nc(-c3ccc(C)c(O)c3)c(CC(=O)N(C)C)n2c1.O,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1.O=O,Cc1ccc2nc(-c3ccc(C)c(O)c3)c(CC(=O)N(C)C)n2c1.O...,MNXR101068_reverse,1.14.13.-;1.14.14.-;1.14.14.1,1
4,rxn10,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1>>Cc1cc...,MNXR111073,1.14.13.-,1
5,rxn11,Cc1ccc2nc(-c3ccc(C)cc3)c(CC(=O)N(C)C)n2c1,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1,Cc1ccc2nc(-c3ccc(C)cc3)c(CC(=O)N(C)C)n2c1>>Cc1...,MNXR111073,1.14.13.-,1
6,rxn12,Cc1ccc2nc(-c3ccc(C)c(O)c3)c(CC(=O)N(C)C)n2c1,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1,Cc1ccc2nc(-c3ccc(C)c(O)c3)c(CC(=O)N(C)C)n2c1>>...,MNXR111073_reverse,1.14.13.-,1
7,rxn13,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)c(O)c1,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)c(O)c1>>Cc...,MNXR111073_reverse,1.14.13.-,1
8,rxn14,Cc1ccc(-c2nc3c(O)cc(C)cn3c2CC(=O)N(C)C)cc1,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1,Cc1ccc(-c2nc3c(O)cc(C)cn3c2CC(=O)N(C)C)cc1>>Cc...,MNXR111073_reverse,1.14.13.-,1
9,rxn15,Cc1ccc(-c2nc3cc(O)c(C)cn3c2CC(=O)N(C)C)cc1,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1,Cc1ccc(-c2nc3cc(O)c(C)cn3c2CC(=O)N(C)C)cc1>>Cc...,MNXR111073_reverse,1.14.13.-,1
10,rxn16,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)[N+](C)(C)[O-])c...,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1.O=O,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)[N+](C)(C)[O-])c...,MNXR111821_reverse,1.14.13.8,1
11,rxn21,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)[NH](C)C)cc1,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)[NH](C)C)cc1>>Cc...,MNXR111823_reverse,1.14.14.-;1.14.14.1,1
12,rxn22,Cc1ccc(-c2nc3ccc(C)cn3c2CC(O)N(C)C)cc1,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1,Cc1ccc(-c2nc3ccc(C)cn3c2CC(O)N(C)C)cc1>>Cc1ccc...,MNXR111832_reverse,1.14.14.-;1.14.14.1,1
13,rxn31,Cc1ccc(-c2nc3ccc(C)c(O)n3c2CC(=O)N(C)C)cc1.O,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1.O=O,Cc1ccc(-c2nc3ccc(C)c(O)n3c2CC(=O)N(C)C)cc1.O>>...,MNXR114432_reverse,1.14.13.-;1.14.13.224,1
15,rxn58,Cc1ccc2nc(-c3ccc(C)(O)cc3)c(CC(=O)N(C)C)n2c1,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1.[H]O[H],Cc1ccc2nc(-c3ccc(C)(O)cc3)c(CC(=O)N(C)C)n2c1>>...,MNXR134412,3.8.1.7,1
16,rxn59,Cc1ccc(-c2nc3ccc(C)(O)cn3c2CC(=O)N(C)C)cc1,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1.[H]O[H],Cc1ccc(-c2nc3ccc(C)(O)cn3c2CC(=O)N(C)C)cc1>>Cc...,MNXR134412,3.8.1.7,1
17,rxn60,Cc1ccc(O)(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1.[H]O[H],Cc1ccc(O)(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1>>Cc...,MNXR134412,3.8.1.7,1
18,rxn65,Cc1ccc(-c2nc3(O)ccc(C)cn3c2CC(=O)N(C)C)cc1,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1.[H]O[H],Cc1ccc(-c2nc3(O)ccc(C)cn3c2CC(=O)N(C)C)cc1>>Cc...,MNXR134579,3.8.1.8,1
19,rxn86,Cc1ccc(-c2nc3ccc(C)cn3c2C(O)C(=O)N(C)C)cc1.O,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1.O=O,Cc1ccc(-c2nc3ccc(C)cn3c2C(O)C(=O)N(C)C)cc1.O>>...,MNXR149911_reverse,1.14.13.138,1
24,rxn103,Cc1ccc(-c2nc3ccc(C)cn3c2[C@@H](O)C(=O)N(C)C)cc1.O,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1.O=O,Cc1ccc(-c2nc3ccc(C)cn3c2[C@@H](O)C(=O)N(C)C)cc...,MNXR176882,1.13.99.3,1
25,rxn104,Cc1ccc(-c2nc3ccc(C)cn3c2[C@H](O)C(=O)N(C)C)cc1.O,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1.O=O,Cc1ccc(-c2nc3ccc(C)cn3c2[C@H](O)C(=O)N(C)C)cc1...,MNXR177302_reverse,1.14.-.-,1
26,rxn126,Cc1ccc(-c2nc3ccc(C)cn3c2[C@@H](O)C(=O)N(C)C)cc...,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1.O=O.[H...,Cc1ccc(-c2nc3ccc(C)cn3c2[C@@H](O)C(=O)N(C)C)cc...,MNXR191714,1.13.99.3,1
27,rxn127,Cc1ccc(-c2nc3ccc(C=O)cn3c2CC(=O)N(C)C)cc1.O,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1.O=O,Cc1ccc(-c2nc3ccc(C=O)cn3c2CC(=O)N(C)C)cc1.O>>C...,MNXR192454_reverse,2.6.1.114,1
28,rxn128,Cc1ccc2nc(-c3ccc(C=O)cc3)c(CC(=O)N(C)C)n2c1.O,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1.O=O,Cc1ccc2nc(-c3ccc(C=O)cc3)c(CC(=O)N(C)C)n2c1.O>...,MNXR192454_reverse,2.6.1.114,1
29,rxn129,Cc1ccc(-c2nc3ccc(CO)cn3c2CC(=O)N(C)C)cc1.OO,Cc1ccc(-c2nc3ccc(C)cn3c2CC(=O)N(C)C)cc1.O=O.[H...,Cc1ccc(-c2nc3ccc(CO)cn3c2CC(=O)N(C)C)cc1.OO>>C...,MNXR193433,1.13.99.3,1

In [ ]:
result_num_df = pd.DataFrame(result_num)
result_num_df['ec3_list'] = result_num_df['ec3_list'].apply(lambda x:ast.literal_eval(x))
result_num_df['ec3_list'] = result_num_df['ec3_list'].apply(lambda x:[ec for ec in x if '-' not in ec])
result_num_df['ec3_num'] = result_num_df['ec3_list'].apply(lambda x:len(x))

result_num_df['ec4_list'] = result_num_df['ec4_list'].apply(lambda x:ast.literal_eval(x))
result_num_df['ec4_list'] = result_num_df['ec4_list'].apply(lambda x:[ec for ec in x if '-' not in ec])
result_num_df['ec4_num'] = result_num_df['ec4_list'].apply(lambda x:len(x))

result_num_df

,drug_name,reaction_num,ec4_num,ec4_list,ec3_num,ec3_list
0,ABACAVIR SULFATE,30,67,"[1.7.1, 3.1.3.2, 3.1.3.15, 3.1.3.88, 3.1.3.74,...",21,"[1.7.1, 4.2.1, 5.1.3, 1.1.3, 1.17.3, 2.7.1, 1...."
1,ACEBUTOLOL,74,387,"[1.14.13.147, 3.1.3.2, 1.14.13.58, 2.4.1.63, 3...",55,"[4.2.1, 1.21.1, 1.3.99, 3.4.19, 5.1.3, 1.10.3,..."
2,ACECAINIDE,21,50,"[1.11.2.5, 3.2.1.49, 1.14.13.58, 1.14.13.91, 1...",23,"[1.7.1, 4.2.1, 3.4.19, 5.1.3, 3.4.15, 1.14.18,..."
3,ALFUZOSIN,64,121,"[1.11.2.5, 1.14.13.147, 3.2.1.49, 1.14.13.58, ...",32,"[4.2.1, 1.3.99, 3.4.19, 5.1.3, 6.2.1, 3.4.15, ..."
4,ALMOTRIPTAN,30,27,"[1.13.11.11, 1.14.13.58, 1.14.13.91, 1.14.13.7...",10,"[1.14.13, 1.14.14, 1.3.99, 3.4.19, 3.2.1, 3.8...."
...,...,...,...,...,...,...
266,WARFARIN,125,173,"[1.11.2.5, 1.14.13.147, 3.2.1.67, 3.2.1.49, 1....",28,"[1.21.1, 4.2.1, 5.1.3, 1.10.3, 1.1.99, 1.1.3, ..."
267,ZALEPLON,22,26,"[6.3.4.20, 1.14.13.58, 1.14.13.91, 1.14.13.71,...",8,"[1.14.13, 6.3.4, 1.7.1, 1.14.14, 3.8.1, 1.1.1,..."
268,ZIDOVUDINE [AZT],34,152,"[3.2.1.153, 3.1.3.40, 3.1.3.2, 3.2.1.59, 3.2.1...",26,"[4.2.1, 5.1.3, 6.2.1, 4.2.3, 3.4.15, 1.1.3, 3...."
269,ZIPRASIDONE MESYLATE,38,43,"[1.14.13.137, 1.14.13.58, 1.14.13.91, 1.14.13....",19,"[3.4.19, 3.4.15, 1.3.98, 1.14.18, 6.3.1, 3.5.1..."
270,ZOLPIDEM,25,28,"[1.14.13.58, 1.14.13.91, 1.14.13.71, 1.14.13.1...",7,"[1.14.13, 1.14.14, 3.8.1, 2.6.1, 1.1.1, 1.13.9..."

In [14]:
result_num_df.to_csv('../../Results/ref1_alldrug_deg_result_filter.csv',index=None)  # top20 加去重