In [1]:
import pandas as pd
import numpy as np
import json
from rdkit import Chem
from rdkit.Chem import Draw
from rdkit.Chem import rdChemReactions
from rdkit.Chem.Draw import rdMolDraw2D
from rdkit.Chem.Draw import IPythonConsole
from IPython.display import SVG, display
from rdkit.Chem.Fingerprints import FingerprintMols
from rdkit import DataStructs
from rdkit.Chem import MACCSkeys
from rdkit.Chem import AllChem
import pandas as pd
import rdchiral
import itertools
import pickle
import sys
from tqdm import tqdm 
from rdchiral.main import rdchiralRun, rdchiralRunText, rdchiralReaction, rdchiralReactants
import cobra
from itertools import chain, combinations
import sys
import multiprocessing
from functools import partial
import matplotlib.pyplot as plt
import multiprocessing
from tqdm import tqdm
sys.path.append('../')

from common import *

### input and output

In [2]:
# step1
#input
mnxreac_smile_atom_mapping_rules_file_path = '../../Data/retrosynthesis/MNXreaction_smiles_atommap_rules_filter_0.2.csv'
mnxreac_smile_atom_mapping_rules_file_path = '/home/wuke/project/microbiome–drug/Results/MNXreaction_smiles_atommap_rules_filter_0.2.csv'
# target_drug_path = '../../Data/Drug/drug_Javdan_2020.csv'
target_drug_path = '../../Data/Drug/drug_Wu_2025.csv'

###output

In [3]:
def process_rule(rule_smiles, mets_total_smiles):
    score = []
    smiles = []
    if 'C' in rule_smiles or 'c' in rule_smiles:
        for j in mets_total_smiles:
            current_score = calculate_similarity(rule_smiles, j)
            if current_score > 0.3:               ########################################################################
                score.append(current_score)
                smiles.append(j)
    else:
        smiles.append(rule_smiles)
        score.append(1)

    if len(score) == 0:
        return rule_smiles, [], []
    elif len(score) > 50:
        top40_data = sorted(zip(score, smiles), reverse=True)[:50]
    else:
        top40_data = sorted(zip(score, smiles), reverse=True)
    
    top40_scores, top40_smiles = zip(*top40_data)
    
    return rule_smiles, list(top40_smiles), list(top40_scores)

####################################################################################

def count_carbons(smiles):
    """计算一个 SMILES 字符串中碳 (C) 的个数"""
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return 0
    return sum(1 for atom in mol.GetAtoms() if atom.GetSymbol() == 'C')

# def process_rule(rule_smiles, mets_total_smiles):
#     score = []
#     smiles = []
    
#     # 计算 rule_smiles 的碳原子数
#     rule_c_count = count_carbons(rule_smiles)

#     if 'C' in rule_smiles or 'c' in rule_smiles:
#         for j in mets_total_smiles:
#             # 计算当前代谢物的碳原子数
#             j_c_count = count_carbons(j)
            
#             # 根据 mets_total_smiles 的碳原子数目，确定允许的碳数目差
#             if j_c_count < 10:
#                 allowed_diff = 1
#             elif j_c_count < 15:
#                 allowed_diff = 2
#             else:
#                 allowed_diff = 3
            
#             # 仅在碳数目差符合要求时计算相似度
#             if abs(rule_c_count - j_c_count) <= allowed_diff:
#                 current_score = calculate_similarity(rule_smiles, j)
#                 if current_score > 0.3:
#                     score.append(current_score)
#                     smiles.append(j)
    
#     else:
#         smiles.append(rule_smiles)
#         score.append(1)

#     if len(score) == 0:
#         return rule_smiles, [], []
#     elif len(score) > 20:
#         top20_data = sorted(zip(score, smiles), reverse=True)[:20]
#     else:
#         top20_data = sorted(zip(score, smiles), reverse=True)
    
#     top20_scores, top20_smiles = zip(*top20_data)
    
#     return rule_smiles, list(top20_smiles), list(top20_scores)

# def process_rule(rule_smiles, mets_total_smiles):
#     score = []
#     smiles = []
    
#     # 计算 rule_smiles 的碳原子数
#     rule_c_count = count_carbons(rule_smiles)

#     if 'C' in rule_smiles or 'c' in rule_smiles:
#         for j in mets_total_smiles:
#             # 计算当前代谢物的碳原子数
#             j_c_count = count_carbons(j)
            
#             # 计算相似度
#             current_score = calculate_similarity(rule_smiles, j)
            
#             # 计算罚分
#             if rule_c_count!=0:
#                 if rule_c_count > j_c_count:
#                     penalty = (rule_c_count - j_c_count) / (rule_c_count) /10.216
#                 elif rule_c_count < j_c_count:
#                     penalty = (j_c_count - rule_c_count) / (rule_c_count) /8.828
#                 else:
#                     penalty = 0
#             else:
#                 penalty = 0
            
#             # 应用罚分
#             adjusted_score = max(0, current_score - penalty)

#             # 仅保留相似度大于0.3的结果
#             if adjusted_score > -5:
#                 score.append(adjusted_score)
#                 smiles.append(j)
    
#     else:
#         smiles.append(rule_smiles)
#         score.append(1)

#     if len(score) == 0:
#         return rule_smiles, [], []
#     # elif len(score) > 100:
#     #     top20_data = sorted(zip(score, smiles), reverse=True)[:100]
#     else:
#         top20_data = sorted(zip(score, smiles), reverse=True)
    
#     top20_scores, top20_smiles = zip(*top20_data)
    
#     return rule_smiles, list(top20_smiles), list(top20_scores)

# def process_rule(rule_smiles, mets_total_smiles):
#     score = []
#     smiles = []
    
#     # 计算 rule_smiles 的碳原子数
#     rule_c_count = count_carbons(rule_smiles)

#     if 'C' in rule_smiles or 'c' in rule_smiles:
#         for j in mets_total_smiles:
#             # 计算当前代谢物的碳原子数
#             j_c_count = count_carbons(j)
            
#             # 计算相似度
#             current_score = calculate_similarity(rule_smiles, j)
# # 最小满足条件的 N: 21.8108108108, M: 2.4864864865
#             # 计算罚分
#             if rule_c_count!=0:
#                 if rule_c_count > j_c_count:
#                     penalty = (rule_c_count - j_c_count) / (rule_c_count) /2.4864864865
#                 elif rule_c_count < j_c_count:
#                     penalty = (j_c_count - rule_c_count) / (rule_c_count) /21.8108108108
#                 else:
#                     penalty = 0
#             else:
#                 penalty = 0
            
#             # 应用罚分
#             adjusted_score = max(0, current_score - penalty)

#             # 仅保留相似度大于0.3的结果
#             if adjusted_score > 0.1:
#                 score.append(adjusted_score)
#                 smiles.append(j)
    
#     else:
#         smiles.append(rule_smiles)
#         score.append(1)

#     if len(score) == 0:
#         return rule_smiles, [], []
#     # elif len(score) > 20:
#     #     top20_data = sorted(zip(score, smiles), reverse=True)[:20]
#     else:
#         top20_data = sorted(zip(score, smiles), reverse=True)
    
#     top20_scores, top20_smiles = zip(*top20_data)
    
#     return rule_smiles, list(top20_smiles), list(top20_scores)

In [4]:
# for index,row in retrosys_smiles_calculate_similarity_pd.iterrows():
#     if row['rules_smiles'] not in row['smiles_in_mets_total_smiles']:
#         retrosys_smiles_calculate_similarity_pd.loc[index,'smiles_in_mets_total_smiles'] = row['smiles_in_mets_total_smiles'].append(row['rules_smiles'])

In [5]:
def process_retrorule(index_row, mets_total_smiles,retrosys_smiles_calculate_similarity_pd,heterologous_met_smiles):
    rxndb_list_tmp = []
    # newdbSmiles_tmp = []
    failedrxn_tmp = []
    index, row = index_row
    rxn_id, ECnumber, reactants, products = row['MNX_ID'], row['classifs'], row['substrate_smiles'], row['product_smiles']
    deprecated_equ_smiles, reactantSMARTs, productSMARTs, rule = row['deprecated_equ_smiles'], row['ReactantsSMARTs'], row['ProductSMARTs'], row['RetroRules']
    deprecated_equ_smiles = deprecated_equ_smiles.split('>>')
    if rxn_id not in ['MNXR101882', 'MNXR101884', 'MNXR101879', 'MNXR101885', 'MNXR101886', 'MNXR101887',
                        'MNXR103528', 'MNXR103575']:  # ATP NADH conversion stuff
        productSMARTs = productSMARTs.split('.')
        products = products.split('.')
        new_products_smiles = []
        scores = []
        
        if len(productSMARTs) == len(products):
            for x in range(len(productSMARTs)):  # prepare mets with substructure and sort the reactants combination
                new_products_smile_one,score_one = get_calculate_similarity(products[x],retrosys_smiles_calculate_similarity_pd)
                new_products_smiles.append(new_products_smile_one)
                scores.append(score_one)

            product_prepared = []
            scores_prepared = []
            for lst, score_lst in zip(new_products_smiles, scores):
                if heterologous_met_smiles in lst:
                    if len(new_products_smiles) == 1:  # if only one sub list
                        product_prepared.append([heterologous_met_smiles])
                        scores_prepared.append(score_lst)
                    else:
                        other_lists = [sub_lst for sub_lst in new_products_smiles if sub_lst != lst]
                        tmp_product = list(itertools.product([heterologous_met_smiles], *other_lists))
                        product_prepared += tmp_product

                        tmp_scores = list(itertools.product([score_lst[new_products_smiles.index(lst)]], *scores))
                        scores_prepared += tmp_scores
            # print('product_prepared',product_prepared,len(product_prepared))
            for m in range(0, len(product_prepared)):  # apply the rule and output the rxn
                smile = product_prepared[m]
                score = scores_prepared[m]
                
                if len(smile) > 1:
                    product_smile = '.'.join(smile)
                else:
                    product_smile = smile[0]

                retrorule_tmp = rule.split('>>')
                retrorule_tmp = '(' + retrorule_tmp[0] + ')>>' + '(' + retrorule_tmp[1] + ')'            
                product_smile_tmp = product_smile
                # print('retrorule_tmp',retrorule_tmp)
                # print('product_smile',product_smile)
                try:
                    # print('product_smile_tmp',product_smile_tmp)
                    product_mol = Chem.MolFromSmiles(product_smile_tmp)
                    reaction = AllChem.ReactionFromSmarts(retrorule_tmp)
                    reactant_smiles = reaction.RunReactants((product_mol,))
                    smiles = [Chem.MolToSmiles(x[0]) for x in reactant_smiles]
                    reactant_smiles = list(set(smiles))

                    for reactant_smile in reactant_smiles:
                        if len(deprecated_equ_smiles) > 0:
                            if deprecated_equ_smiles[0] == '':
                                reactant_smile_final = reactant_smile
                            else:
                                reactant_smile_final = reactant_smile + '.' + deprecated_equ_smiles[0]
                            if deprecated_equ_smiles[1] == '':
                                product_smile_final = product_smile_tmp
                            else:
                                product_smile_final = product_smile_tmp + '.' + deprecated_equ_smiles[1]
                        rxn_smiles = reactant_smile + '>>' + product_smile_tmp
                        rxn_smiles_final = reactant_smile_final + '>>' + product_smile_final
                        
                        tmp = {
                            'EC number': ECnumber,
                            'rule': rule,
                            'templateID': rxn_id,
                            'templateSubstrate': products,
                            'rxn_smiles_basic': rxn_smiles,
                            'rxn_smiles_final': rxn_smiles_final,
                            'reactant_smile': reactant_smile,
                            'productsmile': product_smile_tmp,
                            'similarity': score
                        }
                        if check_rule(tmp['rxn_smiles_basic'])=='blance':
                            rxndb_list_tmp.append(tmp)  
                            # mets_tmp = reactant_smile.split('.')      
                            # for reactant in mets_tmp:             
                            #     if reactant not in mets_total_smiles and reactant not in newdbSmiles_tmp:         
                            #         newdbSmiles_tmp.append(reactant)        
                except:
                    failedrxn_tmp.append(rxn_id)
                
    return(rxndb_list_tmp,failedrxn_tmp)

In [6]:
def process_ec_list(ec_list,topn):
    processed_set = set()
    
    for ec in ec_list:
        for sub_ec in ec.split(';'):
            parts = sub_ec.strip().split('.')
            if len(parts) >= 3:  # Only process EC numbers with at least 3 parts
                processed_set.add('.'.join(parts[:topn]))
    
    return list(processed_set)

# Example usage
input_ec_numbers = ['4.1.3.-', '3.1.3.1', '1.1.3.100;2.1.4.2']
output_ec_numbers = process_ec_list(input_ec_numbers,3)
print(output_ec_numbers)

['2.1.4', '3.1.3', '4.1.3', '1.1.3']

In [7]:
def check_productsmile(smiles):#only keep smiles with carbon
    smiles_lst = smiles.split('.')
    smiles_lst = [x for x in smiles_lst if smiles_has_carbon(x)]
    return len(smiles_lst)

In [8]:
rules_product_smiles_lst = []
retrorules = pd.read_csv(mnxreac_smile_atom_mapping_rules_file_path)
# retrorules = retrorules[retrorules['MNX_ID'].str.contains('MNXR97814')]
for index,row in retrorules.iterrows():
    tmp  = row['product_smiles'].split('.')
    for i in tmp:
        if i not in rules_product_smiles_lst:
            rules_product_smiles_lst.append(i)
print('rules_product_smiles_lst',len(rules_product_smiles_lst))

rules_product_smiles_lst 11047

In [9]:
target_drug = pd.read_csv(target_drug_path)
target_drug.rename(columns={'Drug Name':'drug_name','Drug Smiles':'drug_smiles',},inplace=True)
target_drug['drug_smiles'] = target_drug['drug_smiles'].apply(lambda x:x.replace('.Cl','').replace('.[Na+]',''))
target_drug = target_drug[target_drug['drug_smiles'].apply(lambda x:normalize_smiles(x)!=None)]
target_drug

,drug_name,drug_smiles
0,(R)-Elagolix,FC1=C(C2=C(C)N(CC3=C(C(F)(F)F)C=CC=C3F)C(N(C[C...
1,Acebutolol (hydrochloride),CCCC(NC1=CC=C(OCC(O)CNC(C)C)C(C(C)=O)=C1)=O
2,Acrivastine,O=C(O)/C=C/C1=NC(/C(C2=CC=C(C)C=C2)=C/CN3CCCC3...
3,Adoprazine,FC1=CC=C(C2=CN=CC(CN3CCN(C4=C5OCCOC5=CC=C4)CC3...
4,Almorexant,CNC([C@@H](C1=CC=CC=C1)N2CCC3=CC(OC)=C(OC)C=C3...
...,...,...
122,Volinanserin,FC1=CC=C(CCN2CCC([C@@]([H])(O)C3=CC=CC(OC)=C3O...
123,Vortioxetine (hydrobromide),CC1=CC=C(SC2=CC=CC=C2N3CCNCC3)C(C)=C1.[H]Br
124,Xanomeline (oxalate),CN1CCC=C(C2=NSN=C2OCCCCCC)C1.O=C(O)C(O)=O
125,Zafirlukast,O=C(OC1CCCC1)NC2=CC3=C(N(C)C=C3CC4=CC=C(C(NS(=...
126,Zuclopenthixol,OCCN1CCN(CC/C=C2C3=C(SC4=C\2C=CC=C4)C=CC(Cl)=C...

In [10]:
# for index,row in target_drug.iterrows():
#     print('====================',row['drug_name'],'====================')
#     draw_smiles(row['drug_smiles'])
#     draw_smiles(row['product_smiles'])
# break

In [11]:
# 读取gut clean ec预测结果
with open('../../Results/AGORA2_strain_eclist_top3.pkl', 'rb') as f:
    loaded_top3 = pickle.load(f)

with open('../../Results/AGORA2_strain_eclist_top4.pkl', 'rb') as f:
    loaded_top4 = pickle.load(f)

print("读取完成！")
print(f"Top3 列表长度：{len(loaded_top3)}")
print(f"Top4 列表长度：{len(loaded_top4)}")

读取完成！
Top3 列表长度：252
Top4 列表长度：4948

## byproduct prediction

In [12]:
result_num = {'drug_name':[],
              'reaction_num':[],
              'ec4_num':[],
              'ec4_list':[],
              'ec3_num':[],
              'ec3_list':[],
            #   'success_predict':[],
            #   'success_ecnumber':[],
              }
# filter_info = {'drug_carbon':[],
#                'success_carbon':[],
#                'error_carbon':[],
#                'success_sim_score':[],
#                'error_sim_score':[],
#                }

for index,row in tqdm(target_drug.iterrows(),total=len(target_drug)):
    print(row['drug_name'])
    heterologous_met_smiles = row['drug_smiles']
    # heterologous_met_smiles = 'FC1=CNC(=O)NC1=O'
    # heterologous_met_smiles = 'N[C@@H](CC1=CC(O)=C(O)C=C1)C(O)=O'
    # heterologous_met_smiles = '[NH3+][C@@H](Cc1ccc(O)c(O)c1)C(=O)[O-]' ######## L-dopa
    heterologous_met_smiles = normalize_smiles(heterologous_met_smiles)
    # model_met = target_drug['smiles'].to_list()
    # model_met = [heterologous_met_smiles,heterologous_met_smiles,heterologous_met_smiles,'O=C([O-])CCC(=O)C(=O)[O-]']
    model_met = [heterologous_met_smiles,heterologous_met_smiles,heterologous_met_smiles,'O=C([O-])CCC(=O)C(=O)[O-]',
                 'C[S+](CC[C@@H](C(=O)[O-])N)C[C@@H]1[C@H]([C@H]([C@@H](O1)N2C=NC3=C(N=CN=C32)N)O)O',
                 'C1=NC(=C2C(=N1)N(C=N2)[C@H]3[C@@H]([C@@H]([C@H](O3)CSCC[C@@H](C(=O)O)N)O)O)N',
                 'O=C(O)[C@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@H]1O',# β-D-葡萄糖醛酸
                 'CC(=O)SCCNC(=O)CCNC(=O)[C@@H](C(C)(C)COP(=O)(O)OP(=O)(O)OC[C@@H]1[C@H]([C@H]([C@@H](O1)N2C=NC3=C(N=CN=C32)N)O)OP(=O)(O)O)O', # Acetyl-CoA
                 ]
    new_met = []

    # add heterologous_met_smiles to model_met list
    new_model_and_heterologous_met = model_met + new_met
    new_model_and_heterologous_met.append(heterologous_met_smiles)
    new_model_and_heterologous_met = [smile for smile in new_model_and_heterologous_met if '.' not in smile]
    new_model_and_heterologous_met = [smile for smile in new_model_and_heterologous_met if 'C' in smile or 'c' in smile] ###只筛第一轮
    print(len(new_model_and_heterologous_met))
    #calculate similarity
    num_processes = 100
    pool = multiprocessing.Pool(num_processes)
    retrosys_smiles_calculate_similarity = {'rules_smiles': [],
                                            'smiles_in_mets_total_smiles': [],
                                            'scores': []}


    process_rule_partial = partial(process_rule, mets_total_smiles=new_model_and_heterologous_met)
    for result in tqdm(pool.imap(process_rule_partial, rules_product_smiles_lst, chunksize=100), total=len(rules_product_smiles_lst)):
        if result[0] not in retrosys_smiles_calculate_similarity['rules_smiles']:
            retrosys_smiles_calculate_similarity['rules_smiles'].append(result[0]) 
            retrosys_smiles_calculate_similarity['smiles_in_mets_total_smiles'].append(result[1]) 
            retrosys_smiles_calculate_similarity['scores'].append(result[2]) 
    pool.close()
    pool.join()

    retrosys_smiles_calculate_similarity_pd = pd.DataFrame(retrosys_smiles_calculate_similarity)
    
##############################################
    # for index4, row4 in retrosys_smiles_calculate_similarity_pd.iterrows():
    #     if row4['rules_smiles'] not in row4['smiles_in_mets_total_smiles']:
    #         # 修改 DataFrame 中嵌套的列表
    #         retrosys_smiles_calculate_similarity_pd.at[index4, 'smiles_in_mets_total_smiles'].append(row4['rules_smiles'])
##############################################
    rxndb_list = [] 
    # newdbSmiles = []
    failedrxn = []
    num_processes =100  #  adjust the number of processes according to your needs
    pool = multiprocessing.Pool(num_processes)
    # Execute in parallel using process pool

    # Create a partial function that passes mets_total_smiles and mets_total_mol as default parameters to the process_retrorule function
    process_retrorule_partial = partial(process_retrorule, mets_total_smiles=new_model_and_heterologous_met,retrosys_smiles_calculate_similarity_pd = retrosys_smiles_calculate_similarity_pd,heterologous_met_smiles = heterologous_met_smiles)

    # Using the process pool to execute in parallel, the chunksize parameter is placed inside the imap function.
    for result in tqdm(pool.imap(process_retrorule_partial, retrorules.iterrows(), chunksize=100), total=len(retrorules)):
        # if result == ([], [], []):
        #     pass
        # else:
        #     print(result)
        if result[0] :  #  check if the result is not empty
            rxndb_list.extend(result[0]) 
        # if result[1] is not None:
        #     newdbSmiles.extend(result[1])
        if result[1]:
            failedrxn.extend(result[1])  

    pool.close()
    pool.join()

    rxndb = {}
    for i, rxn_dict in enumerate(rxndb_list):
        # generate a unique key for each reaction, for example "rxn0"，"rxn1"，"rxn2"，...
        key = f'rxn{i+1}'
        # merge to the dictionary
        rxndb[key] = rxn_dict
    # with open(rxndb_path, 'w') as json_file:
    #     json.dump(rxndb, json_file)

    # with open(rxndb_path, 'r') as f:
    #     rxndb = json.load(f)
    print('rxndb num',len(rxndb))
    print('failedrxn num',len(failedrxn))

    ecnumber_list = []
    for _,x in rxndb.items():
        ec_list = x['EC number'].split(';')
        ec_list = process_ec_list(ec_list,3)
        ecnumber_list += ec_list

    ecnumber_list = list(set(ecnumber_list))   
    result_df = {'ID':[],
            'reactant_smile':[],
            'productsmile':[],
            'rxn_smiles_basic':[],
            'templateID':[],
            'EC number':[],}

    for k,v in rxndb.items():
        result_df['ID'].append(k)
        result_df['reactant_smile'].append(v['reactant_smile'])
        result_df['productsmile'].append(v['productsmile'])
        result_df['rxn_smiles_basic'].append(v['rxn_smiles_basic'])
        result_df['templateID'].append(v['templateID'])
        result_df['EC number'].append(v['EC number'])

    result_df = pd.DataFrame({'ID': result_df['ID'],
                        'reactant_smile': result_df['reactant_smile'],
                        'productsmile': result_df['productsmile'],
                        'rxn_smiles_basic': result_df['rxn_smiles_basic'],
                        'templateID': result_df['templateID'],
                        'EC number': result_df['EC number'],
                        })

    result_df.drop_duplicates(subset=['reactant_smile', 'productsmile'], inplace=True)
    result_df.reset_index(drop=True, inplace=True)

    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.OO']
    result_df = result_df[result_df['productsmile']!='OO.'+ heterologous_met_smiles]
    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.O=C=O']
    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.O=S([O-])[O-]']
    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.[SH-]']
    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.O=P([O-])([O-])OP(=O)([O-])O']
    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.II']
    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.[NH4+]']
    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.[Br-]']

    result_df['productsmile_num'] = result_df['productsmile'].apply(lambda x: check_productsmile(x))
    result_df = result_df[result_df['productsmile_num']==1]


    # error_ec = ['1.2.1', '1.14.13', '1.14.14', '1.14.18', '1.1.1', '3.1.3' ,'1.21.1','1.22.1','1.1.1','3.1.6'] #1.10.3#3.1.6
    error_ec = []
    if len(result_df)>0:
        result_df['EC number'] = result_df['EC number'].apply(lambda x:x.split(';'))
        result_df = result_df[~result_df['EC number'].apply(lambda ec_list: all('.'.join(x.split('.')[0:3]) in error_ec for x in ec_list))]
        result_df['EC number'] = result_df['EC number'].apply(lambda x:';'.join(x))
        
        # 过滤 DataFrame，使得 "EC number" 列中的有 EC 号都属于 gut_ec
        # gut_ec_list_top3 = loaded_top3
        # result_df['EC number'] = result_df['EC number'].apply(lambda x:x.split(';'))
        # result_df = result_df[result_df['EC number'].apply(lambda ec_list: any('.'.join(x.split('.')[0:3]) in gut_ec_list_top3 for x in ec_list))]
        # result_df['EC number'] = result_df['EC number'].apply(lambda x:';'.join(x))        
    try:
        res = result_df['reactant_smile'].to_list()
        ec_lst = []
        for k,v in rxndb.items():
            if v['reactant_smile'] in res:
                ec_lst.append(v['EC number'])
    except:
        ec_lst = []
        pass
    # print(row['name'],len(result_df))
    # print(row['name'],ec_lst)
    print('result_df',len(result_df))
    print(ec_lst)
    ec_lst_4 = process_ec_list(ec_lst,4)
    ec_lst_3 = process_ec_list(ec_lst,3)
    print(len(ec_lst_3))
    print(len(ec_lst_4))
    
    result_num['drug_name'].append(row['drug_name'])
    result_num['reaction_num'].append(len(result_df))
    result_num['ec4_num'].append(len(ec_lst_4))
    result_num['ec4_list'].append(str(ec_lst_4))
    result_num['ec3_num'].append(len(ec_lst_3))
    result_num['ec3_list'].append(str(ec_lst_3))
    
    # success_predict = 0
    # success_ecnumber = []
    # success_ID = []
    # if row['product_smiles'] != 'unknown' and row['drug_name'] != 'Lactulose':
    #     target_smiles = row['product_smiles'].split('.')[0]
    #     for index2,row2 in result_df.iterrows():
    #         smiles_list = row2['reactant_smile'].split('.')
    #         if any(compare_smiles_inchikey(smiles,target_smiles) for smiles in smiles_list):
    #             success_predict =1
    #             success_ID.append(row2['ID'])
    #             tmp_ec_lst = row2['EC number'].split(';')
    #             success_ecnumber+=process_ec_list(tmp_ec_lst,3)
    
    # result_num['success_predict'].append(success_predict)
    # result_num['success_ecnumber'].append(str(list(set(success_ecnumber))))
    
    
    # drug_carbon = calculate_carbon_count(heterologous_met_smiles)
    # success_sim_score = []
    # success_carbon = []
    # error_carbon = []
    # error_sim_score = []
    # # for tmpid,tmp_result in rxndb.items():
    # #     if tmpid in result_df['ID']:
    # for index3,row3 in result_df.iterrows():
    #     if row3['ID'] in success_ID:
    #         success_sim_score.append(min(rxndb[row3['ID']]['similarity']))
    #         success_carbon.append(max(calculate_carbon_count(tmp_smiles) for tmp_smiles in rxndb[row3['ID']]['templateSubstrate']))
    #     else:
    #         error_sim_score.append(min(rxndb[row3['ID']]['similarity']))
    #         error_carbon.append(max(calculate_carbon_count(tmp_smiles) for tmp_smiles in rxndb[row3['ID']]['templateSubstrate']))

    # filter_info['drug_carbon'].append(drug_carbon)
    # filter_info['success_carbon'].append(success_carbon)
    # filter_info['error_carbon'].append(error_carbon)
    # filter_info['success_sim_score'].append(success_sim_score)
    # filter_info['error_sim_score'].append(error_sim_score)
     
    # # 保存结果
    # # 保存 drug_degration_ec 到 JSON 文件
    # drug_degration_ec_path = os.path.join(output_dir, 'drug_degration_ec.json')
    # with open(drug_degration_ec_path, 'w') as json_file:
    #     json.dump(drug_degration_ec, json_file, indent=4)

    # # 保存 result_df 到 CSV 文件
    # result_df_path = os.path.join(output_dir, 'result_df.csv')
    # # 保存结果时，使用追加模式（mode='a'）
    # result_df.to_csv(result_df_path, index=False, mode='a', header=not os.path.exists(result_df_path))

  0%|          | 0/126 [00:00<?, ?it/s]

(R)-Elagolix
9

100%|██████████| 11047/11047 [00:08<00:00, 1299.77it/s]
100%|██████████| 27873/27873 [00:10<00:00, 2630.19it/s]
  1%|          | 1/126 [00:21<44:57, 21.58s/it]

rxndb num 3071
failedrxn num 0
result_df 173

100%|██████████| 11047/11047 [00:05<00:00, 1866.39it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2021.25it/s]
  2%|▏         | 2/126 [00:46<49:03, 23.73s/it]

rxndb num 1801
failedrxn num 0
result_df 80

100%|██████████| 11047/11047 [00:06<00:00, 1642.89it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2275.97it/s]
  2%|▏         | 3/126 [01:09<47:46, 23.30s/it]

rxndb num 638
failedrxn num 0
result_df 42
['3.1.3.15', '3.1.3.74', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.2.1.5', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '3.1.3.74', '3.1.3.74', '3.1.3.73', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '4.1.2.61;4.2.1.101', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.2.1.5', '1.2.1.5', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.-;3.1.3.88', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '4.2.1.17', '1.14.13', '1.3.1.117', '1.14.13;1.14.13.-', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13;1.14.13.-', '1.1.1.-', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.2.3.1', '3.1.3.33;3.1.3.5', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.1.3', '3.1.3', '3.1.3', '1.14.13.-', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.2.1.74', '3.4.11.5', '3.1.3.91', '3.6.1;3.6.1.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.79', '1.14.13.79', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.1.3.M8', '4.2.1.175', '1.3.1.117', '4.2.1.175', '4.2.1.101', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.-.-', '1.14.-.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '4.1.2.61', '4.1.2.61', '4.1.2.41;4.1.2.61', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '2.6.1.114', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '1.2.1', '3.1.3.2;3.1.3.75']
18
69
Adoprazine
9

100%|██████████| 11047/11047 [00:07<00:00, 1419.31it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2196.33it/s]
  3%|▎         | 4/126 [01:34<48:18, 23.76s/it]

rxndb num 342
failedrxn num 0
result_df 29
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '2.1.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '1.14.13.224', '1.14.13.224', '1.14.13.224', '1.14.13.224', '1.2.3.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '2.4.1.-', '2.4.1.-', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.2.1.3', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '3.2.1.143', '3.2.1.143', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9']
11
32
Almorexant
9

100%|██████████| 11047/11047 [00:06<00:00, 1620.80it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2226.14it/s]
  4%|▍         | 5/126 [01:58<48:13, 23.92s/it]

rxndb num 3594
failedrxn num 0
result_df 104
['3.5.1.94', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '6.3.2.1', '3.5.1.92', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '6.3.1.2;6.3.4.12', '3.5.1.36', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.5.1.22', '6.3.2.23', '6.3.1.2;6.3.1.6', '3.5.1.65', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '6.3.2.20', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '3.5.1.24;3.5.1.74', '3.5.1.24', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.3.2.36', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '3.5.1.-', '6.3.2.44', '6.3.4.24', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.3.2.14', '3.3.2.14', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '6.3.2.18', '6.3.2;6.3.2.-', '1.14.13', '1.14.13', '6.3.2', '6.3.2', '6.3.2', '6.3.2.59', '6.3.2.59', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.4.13', '6.3.2', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2', '3.4', '1.14.13', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '3.5.1.115', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '3.5.1.23', '3.5.1.23', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '1.14.14.55', '6.3.2.18', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '2.4.1.-', '2.4.1.-', '1.14.-.-', '1.14.-.-', '6.3.1.11', '3.5.1.-;3.5.1.78', '6.3.1.8;6.3.1.9', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.5.1.4;3.5.1.99', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.5.1.24;3.5.1.74', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '6.3.1.9', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '3.5.1.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '6.3.1.13', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '6.3.1.10', '6.3.1.10', '3.5.1.90', '3.5.1.90', '6.3.2.56;6.3.2.ad', '3.5.1.60;3.5.1.99', '3.5.1.60', '3.5.1.60;3.5.1.99', '3.5.1.99', '3.5.1.99', '3.5.1.60', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.4', '3.2.1.14', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '3.4.15.6', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '6.3.2;6.3.2.-', '1.14.13', '1.14.13', '6.3.2', '3.2.1.143', '3.2.1.143', '6.3.2', '6.3.2', '6.3.2', '6.3.2', '1.14.13.149', '6.3.2.37', '6.3.1.10', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '6.3.2.58', '6.3.2.58', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.5.1.115', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1;1.1.1.206', '3.5.1.46']
32
119
Ambrisentan
9

100%|██████████| 11047/11047 [00:06<00:00, 1825.92it/s]
100%|██████████| 27873/27873 [00:14<00:00, 1949.46it/s]
  5%|▍         | 6/126 [02:22<48:08, 24.07s/it]

rxndb num 1178
failedrxn num 0
result_df 62
['3.1.3.69', '3.1.3.74', '1.2.1.5', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '3.1.3.74', '3.1.3.74', '3.1.3.73', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.118;1.1.1.47', '1.1.1.119;1.1.1.47', '3.1.3.39', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.6', '1.14.13.6', '1.14.13.6', '1.14.13.6', '3.1.3.40', '3.1.6.9', '3.1.6.10', '1.1.1.173;1.1.1.378', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.61', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.69', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.2.1.5', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.-;3.1.3.88', '3.1.3.79', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '3.1.3.85', '3.1.3.83', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.1.1.203', '1.1.1.203', '1.1.1.363;1.1.1.388', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '3.1.3.103', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '3.1.3', '3.1.3.-', '1.1.1.203', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.1.1.-;1.1.1.377;1.1.1.378', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.6.14', '3.1.3.29', '1.1.1.179;1.3.1.20', '3.1.3.33;3.1.3.5', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3', '3.2.1.78', '1.1.1.121', '1.1.1.121', '1.1.1.47', '1.1.3.38', '3.1.3', '3.1.3', '3.1.6.3', '1.1.1.122', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.55', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.82', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.145;3.2.1.23', '3.2.1.76', '3.2.1.31', '3.2.1.35', '1.14.13.10', '3.1.3.91', '3.6.1;3.6.1.-', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '3.2.1.137;3.2.1.78', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '2.4.1.-', '3.1.3.23;3.1.3.29;3.1.3.9', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.24', '3.1.3.12', '3.1.3.29', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.3.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.1.1.186', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.1.1.186', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.1.1.107;1.1.1.122', '3.1.3.73', '3.1.3', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.45', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.1.1.363;1.1.1.388;1.1.1.47;1.1.1.49', '1.14.13.246', '3.1.3.M8', '3.1.3.105', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.1.1.420', '3.1.3.58;3.1.3.9', '3.1.6.3', '1.1.1.120', '3.2.1.14', '1.1.1.121;1.1.1.175', '1.1.1.121', '1.1.1.179', '1.1.1.179', '3.2.1.37', '3.2.1.37', '3.2.1.3;3.2.1.58;3.2.1.59', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.1.1.121', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.2.1.87', '3.2.1.1', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.2', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.15', '4.2.2.2', '6.2.1.3', '6.2.1.3', '3.2.1.137', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.73', '3.2.1.143', '3.2.1.143', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.2.1.23', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.1.1.363;1.1.1.49', '3.1.3.82', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.182', '1.14.13.182', '1.1.1.118', '1.1.1.120;1.1.1.179;1.1.1.359;1.1.1.360;1.1.1.47;1.1.1.48;1.3.1.20', '1.1.1.120', '3.1.3.58;3.1.3.9', '1.1.1.119', '1.1.1.121;1.1.1.359;1.1.1.47;1.1.1.48', '1.1.1.121', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.1.1.363;1.1.1.47;1.1.1.49', '1.1.1.49', '2.6.1.114', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '3.1.3.-;3.1.3.104']
33
181
Anamorelin (hydrochloride)
5

100%|██████████| 11047/11047 [00:03<00:00, 3104.54it/s]
100%|██████████| 27873/27873 [00:11<00:00, 2476.70it/s]
  6%|▌         | 7/126 [02:40<43:46, 22.07s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Aprepitant
9

100%|██████████| 11047/11047 [00:06<00:00, 1648.98it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2188.15it/s]
  6%|▋         | 8/126 [03:04<44:35, 22.67s/it]

rxndb num 409
failedrxn num 0
result_df 25
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '2.4.1.247', '2.4.1.247', '3.2.1.-;3.2.1.21', '3.2.1.-;3.2.1.21', '3.2.1.21', '3.2.1.21', '3.2.1.21', '3.2.1.21', '2.4.1.-;2.4.1.282', '2.4.1.-;2.4.1.282', '3.2.1.187', '3.2.1.187', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '2.4.1.320', '2.4.1.320', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '2.4.1.332', '2.4.1.332', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.150', '3.2.1.150', '3.2.1.159', '3.2.1.159', '3.2.1.52', '3.2.1.52', '3.2.1', '3.2.1', '3.2.1.149', '3.2.1.149', '3.2.1.149', '3.2.1.149', '3.2.1.194', '3.2.1.194', '3.2.1.195', '3.2.1.195', '1.14.13', '1.14.13;1.14.13.-', '2.4.1.230', '2.4.1.230', '3.2.1.40', '3.2.1.40', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '3.2.1.70', '3.2.1.70', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.2.1.21', '3.2.1.81', '3.2.1.81', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.35', '1.14.-.-', '3.2.1.22', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '3.2.1.21', '3.2.1.21', '3.2.1', '3.2.1', '3.2.1', '3.2.1', '2.4.1.359;2.4.1.dr', '2.4.1.359;2.4.1.dr', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.104', '3.2.1.104', '3.2.1.104', '3.2.1.104', '3.2.1.22', '3.2.1.22', '3.2.1.117', '3.2.1.117', '3.2.1.74', '3.2.1.74', '2.4.1.247', '2.4.1.247', '2.4.1.247', '2.4.1.247', '1.14.-.-', '2.4.1.280', '2.4.1.280', '3.2.1.87', '3.2.1.87', '3.4.15.6', '2.3.1.-', '2.3.1.-', '2.3.1.-', '2.3.1.-', '3.2.1.-', '3.2.1.177', '3.2.1.177', '3.2.1.159', '3.2.1.159', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.-.-.-', '6.2.1.3', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.143', '3.2.1.143', '3.2.1', '3.2.1', '3.2.1.119', '3.2.1.119', '2.4.1.211', '2.4.1.211', '3.2.1.118', '3.2.1.118', '3.2.1.117', '3.2.1.117', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.2.1.118', '3.2.1.118', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.2.1.214', '3.2.1.214', '3.2.1.37', '3.2.1.37', '3.2.1.37', '3.2.1.37', '3.2.1.20', '3.2.1.20']
18
72
Aripiprazole
9

100%|██████████| 11047/11047 [00:06<00:00, 1718.02it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2214.43it/s]
  7%|▋         | 9/126 [03:27<44:30, 22.83s/it]

rxndb num 763
failedrxn num 0
result_df 71
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.1.1.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.17.1.1', '1.17.1.1', '3.8.1.7', '3.8.1.7', '3.4.22.40;3.5.1.72', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.19.n5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '6.3.1.18', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '3.5.1.123', '1.3.1.117', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.5.1', '1.3.1', '3.4.11.3;3.4.11.6;3.4.22.40', '2.3.2.2;3.4.11.10;3.4.19.3', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '3.4.21.4;3.4.22;3.4.22.1', '3.3.2.6;3.4.11.10;3.4.11.15', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '2.4.1.-', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.140', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.3.1.n3', '1.3.1.n3', '1.3.1.117', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.87', '3.4.15.6', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.3.98.-', '1.3.98.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.140', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.88', '1.14.13.88', '1.14.13', '3.2.1.143', '1.14.19.58', '1.14.19.58', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '1.1.1;1.1.1.206']
35
87
Atrasentan (hydrochloride)
9

100%|██████████| 11047/11047 [00:06<00:00, 1751.21it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2055.64it/s]

rxndb num 2628
failedrxn num 0

  8%|▊         | 10/126 [03:51<44:49, 23.18s/it]

result_df 105
['3.1.3.69', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.2.1.5', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.27', '3.1.3.74', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.73', '3.1.6.2', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.1.1.118;1.1.1.47', '1.1.1.119;1.1.1.47', '3.1.3.39', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '3.1.6.9', '3.1.6.10', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '3.1.3.69', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.2.1.5', '1.2.1.5', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.-;3.1.3.88', '3.1.3.79', '3.1.3.85', '1.14.-.-', '1.14.13.-', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.1.1.363;1.1.1.388', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.3.2.14', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.1.1.116', '1.1.1.359;1.1.1.376;1.1.1.46', '3.1.3', '1.14.13', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.14.13;1.14.13.-', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '1.3.1', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3.4', '3.1.3.4', '3.2.1.40', '3.2.1.40', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.-', '1.1.1', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.6.14', '3.1.3.29', '1.14.15.15', '1.1.1.179;1.3.1.20', '1.1.1.179;1.3.1.20', '3.1.3.33;3.1.3.5', '3.2.1.21;3.2.1.23', '3.2.1.21;3.2.1.23', '3.2.1.22', '3.2.1.22', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.2.1.161;3.2.1.188;3.2.1.21;3.2.1.23;3.2.1.25;3.2.1.3;3.2.1.37;3.2.1.45;3.2.1.58;3.2.1.74', '3.2.1.161;3.2.1.188;3.2.1.21;3.2.1.23;3.2.1.25;3.2.1.3;3.2.1.37;3.2.1.45;3.2.1.58;3.2.1.74', '3.2.1.3', '3.2.1.3', '3.2.1;3.2.1.10;3.2.1.177;3.2.1.199;3.2.1.20;3.2.1.21;3.2.1.70', '3.2.1;3.2.1.10;3.2.1.177;3.2.1.199;3.2.1.20;3.2.1.21;3.2.1.70', '3.1.3', '3.1.3', '3.2.1.51', '3.2.1.51', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '3.2.1.78', '3.2.1.78', '3.2.1.21;3.2.1.22;3.2.1.23', '3.2.1.21;3.2.1.22;3.2.1.23', '3.2.1.22;3.2.1.23;3.2.1.85', '3.2.1.22;3.2.1.23;3.2.1.85', '1.1.1.121', '1.1.1.121', '3.2.1.55', '3.2.1.55', '1.1.1.47', '3.1.3', '3.1.3', '3.2.1.23', '3.2.1.23', '3.1.3.68', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.21.8', '1.14.21.8', '3.2.1.35', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '3.1.3.91', '3.6.1;3.6.1.-', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.34', '1.3.1;1.3.1.-', '3.1.3.29', '2.4.1.-', '2.4.1.-', '2.4.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.1.3.27', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.24', '3.1.3.12', '3.1.3.29', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.3.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.1.1.113', '1.14.21.2', '1.14.21.2', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.19.68;1.14.21.5', '1.14.19.68;1.14.21.5', '1.14.21.1', '1.14.21.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.-.-', '1.14.-.-', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3', '3.2.1.20;3.2.1.22', '3.2.1.20;3.2.1.22', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.19.41;1.3.1.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.1.1.363;1.1.1.388;1.1.1.47;1.1.1.49', '1.14.13.246', '3.1.3.M8', '3.1.3.106;3.1.3.76', '1.1.1.376', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '1.1.1.420', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.1.1.120', '3.2.1.14', '3.2.1.14', '1.1.1.46', '1.1.1.46', '3.2.1.55', '3.2.1.55', '3.1.3.29', '3.2.1.4', '3.2.1.4', '3.2.1.126', '3.2.1.126', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.1.1.121', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.4.15.6', '3.4.15.6', '3.4.19.7', '3.4.19.7', '3.2.1.1', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.21.8', '1.14.21.8', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '3.2.1.2', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.174', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.15.5', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '6.2.1.3', '1.1.1.117', '1.1.1.117', '1.1.1.117', '1.1.1.117', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '3.1.3.27', '1.1.1.46', '1.1.1.46', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.194', '3.1.1.101', '3.1.1.101', '3.1.3', '3.1.3.73', '3.2.1.143', '3.2.1.143', '3.2.1.143', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.106', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.1.1.363;1.1.1.49', '1.3.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.1.1.118', '1.1.1.120;1.1.1.179;1.1.1.359;1.1.1.360;1.1.1.47;1.1.1.48;1.3.1.20', '1.1.1.120', '3.2.1.126', '3.2.1.126', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.1.1.119', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.1.1.121;1.1.1.359;1.1.1.47;1.1.1.48', '1.1.1.121', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.1.1.363;1.1.1.47;1.1.1.49', '1.1.1.49', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.2.1', '1.1.1.424', '1.1.1;1.1.1.206', '3.1.3.76', '3.1.3.76', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75']
36
216
Avosentan
9

100%|██████████| 11047/11047 [00:06<00:00, 1596.83it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2030.52it/s]
  9%|▊         | 11/126 [04:15<44:59, 23.47s/it]

rxndb num 2034
failedrxn num 0
result_df 42
['1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '3.3.2.14', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '1.14.13.224', '1.14.13.224', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.35', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.21.3', '1.14.21.3', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '3.2.1.14', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.2.1.3', '6.2.1.3', '6.2.1.3', '1.14.13.176', '3.2.1.143', '3.2.1.143', '3.2.1.143', '2.6.1.114', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9']
16
40
Azilsartan (medoxomil)
9

100%|██████████| 11047/11047 [00:07<00:00, 1557.52it/s]
100%|██████████| 27873/27873 [00:15<00:00, 1763.94it/s]
 10%|▉         | 12/126 [04:42<46:09, 24.30s/it]

rxndb num 773
failedrxn num 0
result_df 107
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.1.1.60', '1.14.13.180', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.1.1.415;1.1.1.ee', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.-', '1.14.13.-', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '3.2.1.35', '1.14.-.-', '2.4.1.-', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.1.1.415', '3.2.1.14', '3.2.1.14', '3.2.1.14', '1.14.-.-', '3.2.1.87', '3.2.1.87', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.15.5', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.176', '1.14.13.176', '1.14.13.176', '3.2.1.143', '3.2.1.143', '3.1.1.1;3.1.1.84', '1.14.13.182', '1.14.13.182', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '2.6.1.114', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9']
18
56
Balovaptan
9

100%|██████████| 11047/11047 [00:07<00:00, 1451.48it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2128.19it/s]
 10%|█         | 13/126 [05:05<45:22, 24.09s/it]

rxndb num 305
failedrxn num 0
result_df 31
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.8.1.7', '1.14.13.61', '1.14.13.61', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13.224', '1.14.13.224', '1.2.3.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.8', '3.8.1.8', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.3.98.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.176', '3.2.1.143', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.19.58', '3.6.1.18;3.6.1.9']
12
32
Bambuterol hydrochloride
5

100%|██████████| 11047/11047 [00:03<00:00, 3072.58it/s]
100%|██████████| 27873/27873 [00:11<00:00, 2526.95it/s]
 11%|█         | 14/126 [05:23<41:17, 22.12s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Basimglurant
9

100%|██████████| 11047/11047 [00:05<00:00, 1864.06it/s]
100%|██████████| 27873/27873 [00:11<00:00, 2390.58it/s]
 12%|█▏        | 15/126 [05:43<40:05, 21.67s/it]

rxndb num 129
failedrxn num 0
result_df 15
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.224', '1.14.13.224', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.8', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.13.99.3']
4
17
BI-671800
9

100%|██████████| 11047/11047 [00:06<00:00, 1588.73it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2124.66it/s]
 13%|█▎        | 16/126 [06:07<40:34, 22.13s/it]

rxndb num 554
failedrxn num 0
result_df 40
['3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.2.1.5', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '3.1.3.-', '3.1.3.74', '3.1.3.73', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3.39', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.8', '3.1.6.9', '3.1.6.10', '1.14.13.180', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.2.1.5', '1.2.1.5', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.2.1.5', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.1.3.-;3.1.3.88', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3', '3.1.3.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.6.14', '3.1.3.29', '3.1.3.33;3.1.3.5', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.8', '1.14.13.-', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '3.1.3.91', '3.6.1;3.6.1.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.29', '3.1.3.-', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.140', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '3.1.3.73', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.1.3.M8', '3.1.3.105', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.1.3.29', '3.4.15.6', '3.4.15.6', '3.4.19.7', '3.4.19.7', '3.2.1.-', '3.2.1.-', '1.14.13.8', '1.14.13.8', '1.14.13.8', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.140', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '3.1.3.-;3.1.3.104']
21
77
Blonanserin
9

100%|██████████| 11047/11047 [00:07<00:00, 1521.95it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2194.05it/s]
 13%|█▎        | 17/126 [06:30<40:41, 22.40s/it]

rxndb num 120
failedrxn num 0
result_df 22
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.182', '1.14.13.182']
4
17
Brexpiprazole
9

100%|██████████| 11047/11047 [00:07<00:00, 1461.13it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2243.30it/s]
 14%|█▍        | 18/126 [06:53<40:46, 22.65s/it]

rxndb num 544
failedrxn num 0
result_df 40
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.61', '1.14.13.61', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.19.n5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.35', '1.14.13.10', '1.14.13.10', '2.4.1.-', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.14', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.176', '3.2.1.143', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9']
17
48
Buspirone (hydrochloride)
5

100%|██████████| 11047/11047 [00:04<00:00, 2649.03it/s]
100%|██████████| 27873/27873 [00:11<00:00, 2454.48it/s]
 15%|█▌        | 19/126 [07:12<38:22, 21.52s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Camicinal
9

100%|██████████| 11047/11047 [00:06<00:00, 1582.65it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2226.66it/s]
 16%|█▌        | 20/126 [07:35<38:48, 21.96s/it]

rxndb num 274
failedrxn num 0
result_df 30
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.5.1;1.5.1.-', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.14.13.138', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '3.2.1.14', '3.4.15.6', '3.4.19.7', '3.2.1.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.138', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.M64', '1.1.1;1.1.1.206']
14
37
Candesartan Cilexetil
9

100%|██████████| 11047/11047 [00:07<00:00, 1493.44it/s]
100%|██████████| 27873/27873 [00:10<00:00, 2740.01it/s]
 17%|█▋        | 21/126 [07:56<38:14, 21.85s/it]

rxndb num 913
failedrxn num 0
result_df 60
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.1.1.60', '1.14.13.180', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.2.1.187', '3.2.1.187', '2.4.1.320', '2.4.1.320', '2.4.1.329', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.4.1.216', '3.2.1.159', '3.2.1.159', '3.2.1.159', '3.2.1.52', '3.2.1.52', '3.2.1', '3.2.1', '3.2.1.149', '3.2.1.149', '3.2.1.149', '3.2.1.149', '1.1.1.415;1.1.1.ee', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.2.1.194', '3.2.1.194', '3.2.1.195', '3.2.1.195', '3.2.1.40', '3.2.1.40', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '1.14.13.M9', '2.4.1.7', '3.2.1.81', '3.2.1.81', '3.2.1.22', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.13.-', '1.14.13.-', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '1.14.-.-', '1.14.-.-', '2.4.1.-', '1.14.13.30', '1.14.13.30', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.1.1.415', '3.2.1.21', '3.2.1.21', '3.2.1', '3.2.1', '3.2.1', '3.2.1', '3.2.1.128', '3.2.1.128', '3.2.1.14', '3.2.1.14', '3.2.1.104', '3.2.1.104', '3.2.1.104', '3.2.1.104', '3.2.1.105', '3.2.1.105', '1.14.-.-', '1.14.-.-', '2.4.1.280', '2.4.1.280', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.4.15.6', '3.4.15.6', '2.3.1.-', '2.3.1.-', '2.3.1.-', '2.3.1.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '3.2.1.-', '3.2.1.159', '3.2.1.159', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.15.5', '1.14.15.5', '6.2.1.3', '6.2.1.3', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.176', '1.14.13.176', '1.14.13.176', '3.2.1.143', '3.2.1.143', '3.2.1.143', '3.2.1.143', '3.2.1', '3.2.1', '3.1.1.1;3.1.1.84', '3.2.1.119', '3.2.1.119', '2.4.1.211', '2.4.1.211', '1.14.13.182', '1.14.13.182', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '2.4.1.216', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.2.1.51']
21
86
Cariprazine (hydrochloride)
5

100%|██████████| 11047/11047 [00:03<00:00, 3435.57it/s]
100%|██████████| 27873/27873 [00:09<00:00, 2948.62it/s]
 17%|█▋        | 22/126 [08:12<34:31, 19.92s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Carteolol hydrochloride
9

100%|██████████| 11047/11047 [00:06<00:00, 1699.85it/s]
100%|██████████| 27873/27873 [00:14<00:00, 1939.30it/s]
 18%|█▊        | 23/126 [08:35<36:06, 21.04s/it]

rxndb num 1501
failedrxn num 0
result_df 55
['3.1.3.69', '3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.1.1.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.27', '3.1.3.3', '3.1.3.74', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.6.2', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.1.1;1.1.1.10', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.137', '1.1.1.137;1.1.1.405', '3.1.3.22;3.1.3.23', '1.1.1;1.1.1.207', '3.1.3.39', '1.1.1.148', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.3.16', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.1.1;1.1.1.208', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.147', '1.1.1.147', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.17.1.1', '1.17.1.1', '1.14.14.-;1.14.14.1', '3.1.6.9', '3.1.6.10', '1.14.13.19', '1.14.13.19', '1.1.1;1.1.1.-', '1.1.1.230', '3.4.22.40;3.5.1.72', '1.-.-.-;1.1.1.342', '1.1.1.62', '1.1.1.62', '1.1.1.146', '1.1.1.53', '1.1.1.50', '1.1.1.53', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.1.1.166', '1.1.1.263', '1.1.1.270', '3.1.3.69', '1.1.1.297', '1.1.1;1.1.1.-', '1.1.1.364', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.270', '3.1.3.76', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.-', '1.1.1;1.1.1.-;1.1.1.50', '1.-.-.-', '1.1.1.292', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.-', '1.1.1.-', '1.1.1.-;1.1.1.341;4.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.-;1.1.1.329', '3.1.3.-;3.1.3.88', '1.1.1.297', '1.1.1.-', '1.1.1.239;1.1.1.62', '1.1.1.213', '1.1.1.209;1.1.1.213;1.1.1.357', '1.1.1.62', '3.1.3.79', '1.1.3.-;1.1.3.45', '1.1.1.297', '1.14.14.-;1.14.14.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.1.1.301', '3.1.3.85', '1.14.-.-', '3.1.3.83', '1.1.1.323', '1.1.1.323', '1.1.1.-;1.1.1.329', '1.1.1.335', '1.1.1.340;1.14.13.-', '1.1.1.339;1.1.1.344', '1.1.1.355', '1.1.1.356', '1.1.1.356', '1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.361', '3.1.3.92', '1.1.1.364', '1.1.1.367', '1.11.2.5', '1.11.2.5', '1.11.2.5', '6.3.1.18', '1.1.1.374', '1.1.1.385', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.1.1.393', '3.1.3.101', '3.1.3.-', '1.1.1.-', '1.1.1.-', '1.1.1.-', '3.1.3;3.1.3.-', '1.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '3.1.3.103', '3.5.1.123', '1.1.1.289', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.1.1.395', '1.1.1.-;1.1.1.395', '1.1.1.14;1.1.1.15', '1.1.1', '1.1.1.14', '1.1.3.11', '3.1.3.3', '3.1.3', '1.3.1.74', '3.1.3.-', '1.1.1;1.1.1.-', '3.1.3;3.1.3.-', '1.3.1.117', '1.1.1.201', '1.1.1.-;1.1.1.50;1.1.1.52', '1.1.1.391', '1.1.1.15', '1.1.1.-;1.1.1.270', '1.1.1;1.1.1.-;1.1.1.270', '1.1.1.-;1.1.1.270', '3.1.3;3.1.3.-', '1.1.1;1.1.1.-;1.1.1.12', '1.1.1', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.1.1.102', '1.1.1.-;1.1.1.393', '1.1.1.145', '1.14.13;1.14.13.-', '1.1.1;1.1.1.-', '1.1.1;1.1.1.-', '1.14.14.133', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.1.1', '3.1.3.50', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.1.1', '1.1.1', '3.1.3', '3.1.3.4', '1.1.1.201', '3.1.3.4', '1.1.1', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1', '1.14.13', '1.1.1.M2', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.M11', '1.1.1.M11', '1.1.1.M11', '1.1.1.392', '1.1.1.393', '1.1.1.52', '1.1.1.391', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.52', '1.1.1.391', '1.1.1.392;1.1.1.50;1.1.1.52', '1.1.1.392', '1.1.1.393', '1.1.1.393', '3.5.1', '3.1.3', '1.1.1', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1.270', '1.1.1.270', '1.1.1.123', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.2;1.1.1.213;1.1.1.239;1.1.1.62;1.3.1.20', '1.1.1.159', '1.1.1.218', '3.1.6.14', '1.1.1.218', '1.1.1.1', '1.1.1.188;1.1.1.213;1.1.1.50', '1.1.1.1', '3.4.11.3;3.4.11.6;3.4.22.40', '3.1.3.29', '3.1.3.29', '2.3.2.2;3.4.11.10;3.4.19.3', '1.14.15.15', '1.1.1.149', '1.1.1.145', '1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50;1.3.1.20', '3.1.3.33;3.1.3.5', '1.1.1.133', '1.1.1.239;1.1.1.51', '1.1.1.239;1.1.1.51', '1.1.1.239', '1.1.1.184', '1.1.1;1.1.1.184;1.1.1.62', '1.1.1.184;1.1.1.2;1.1.1.62', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.213;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.50', '3.4.21.4;3.4.22;3.4.22.1', '1.1.1.51', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.1.1;1.1.1.209', '1.1.1.292', '1.1.1', '3.3.2.6;3.4.11.10;3.4.11.15', '1.1.1.209', '1.1.1.209', '1.1.1.209', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.1.1', '1.1.1.357;1.1.1.50', '1.1.1.210;1.1.1.357', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '1.14.14.55', '1.14.14.55', '1.14.14.55', '3.2.1.78', '1.1.1.184;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.50', '1.1.1.184;1.1.1.50', '1.1.1.12;1.1.1.14', '1.1.1.12;1.1.1.14', '1.1.1.12', '1.1.1;1.1.1.10;1.1.1.405', '3.1.3', '3.1.3', '1.1.1.146;1.1.1.159;1.1.1.50', '3.1.6.3', '1.1.99.13', '3.1.3.68', '1.1.1.-', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.146', '1.1.1.133', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.1.1.297', '1.14.13.36', '1.14.13.36', '1.14.13.36', '3.4.11.5', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.55', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '1.1.1.-', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.145;3.2.1.23', '3.2.1.110', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '3.1.3.91', '3.6.1;3.6.1.-', '3.2.1.137;3.2.1.78', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '1.1.1.239;1.1.1.51', '1.1.1;1.1.1.239;1.1.1.62;1.1.1.64', '2.4.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.-;1.1.1.146', '1.1.1;1.1.1.-;1.1.1.146;1.1.1.51', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62;1.1.1.63', '1.1.1.184;1.1.1.2;1.1.1.213;1.1.1.51;1.1.1.64', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.2;1.1.1.209;1.1.1.21;1.1.1.213;1.1.1.50;1.3.1.20', '3.1.3.23;3.1.3.29;3.1.3.9', '1.1.1.124;1.1.1.138;1.1.1.14;1.1.1.67;1.1.99.11;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.1.3.27', '1.1.1.166;1.1.1.24;1.1.1.282', '1.1.1.14;1.1.1.56', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '1.1.1.12;1.1.1.124;1.1.1.138;1.1.1.14;1.1.1.67;1.1.1.9;1.1.99.11;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.1.3.24', '1.1.1.133', '3.1.3.12', '1.1.1.14;1.1.1.9', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '1.1.1.271', '1.1.1.124;1.1.1.138;1.1.1.21;1.1.1.287;1.1.1.67;1.1.99.11;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '1.1.1.124;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.1.3.29', '1.1.1;1.1.1.148;1.1.1.209', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.3.-', '1.1.1.134;1.1.1.344', '1.1.1.159;1.1.1.50', '1.1.1.176', '1.1.1.206', '1.1.1.236', '1.1.1.16', '1.1.1.198', '1.1.1.227', '1.1.1.241', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.1.1.174', '1.1.1.135;1.1.1.187', '1.1.1.187;1.1.1.281', '1.1.1.135;1.1.1.187', '1.1.1.187;1.1.1.281', '1.1.1.51', '1.1.1.51;1.1.1.62;1.1.1.64', '1.1.1.238', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.1.1.201', '1.1.1.146', '1.1.1.213;1.1.1.52', '3.1.3.63', '3.1.3.63', '1.1.1.152;1.1.1.184;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1.184;1.1.1.209;1.1.1.213;1.1.1.50', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.1.1.213;1.1.1.50', '1.1.1.50', '1.1.1.209;1.1.1.50', '1.1.1.213;1.1.1.50;1.1.1.51', '1.1.1.149;1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '2.-.-.-', '1.1.1.266', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.1.1.213;1.1.1.277;1.1.1.50', '1.14.13.79', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.1.1.282', '1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.278', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.140', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.-.-', '1.14.-.-', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.1.1.210;1.1.1.357;1.1.1.50;1.1.1.51', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.1;1.1.1.391', '1.1.1.-;1.1.1.146;1.1.1.209;1.1.1.213;1.1.1.392;1.1.1.50', '3.1.3.73', '1.1.1;1.1.1.-', '3.1.3', '3.1.3', '1.1.1.159', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.1.1.-', '1.1.1.270', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.14.13.88', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '1.1.1;1.1.1.10', '1.1.1.153', '1.1.1.10;1.1.1.14;1.1.1.15', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.213;1.1.1.50;1.1.1.51;1.1.1.53', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.45', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.1.1.-;1.1.1.M53', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.88', '3.1.3', '3.1.3.68', '1.1.1.270', '1.1.1.270', '1.1.1.270', '1.1.1.201', '1.1.1.425', '3.1.3.M8', '1.1.1', '1.1.1.322', '1.1.1.322', '1.1.1.323', '1.1.1.323', '1.3.1.n3', '1.3.1.n3', '1.1.1.266', '3.1.3.106;3.1.3.76', '1.1.1.367', '1.1.1.M48', '1.1.1.406', '1.1.1.407', '1.1.1.64', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '1.3.1.117', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.1.1', '1.1.1', '1.14.14.70', '1.14.14.70', '1.1.1.14', '1.1.1', '1.1.1.10', '1.1.3.10', '1.1.3.10', '3.1.3.58;3.1.3.9', '3.1.6.3', '3.2.1.14', '3.2.1.37', '3.2.1.37', '3.2.1.55', '3.2.1.55', '3.2.1.3;3.2.1.58;3.2.1.59', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.1.1.227', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.1.1.297', '1.1.1.297', '1.14.-.-;1.14.13.-', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.143', '1.1.1.323', '1.1.1.323', '3.2.1.116', '3.2.1.137', '3.2.1.154', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.4.15.6', '3.4.19.5', '3.4.19.7', '3.2.1.1', '1.1.1.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.-', '1.14.13.-', '1.14.13.-', '3.2.1.2', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.15.5', '1.1.1.-;1.1.1.270', '1.1.1.-;1.1.1.270', '1.14.13.79', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '3.2.1.137', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.1.1.-', '3.1.3.27', '1.1.1.-', '1.1.1.-', '1.14.13.140', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.88', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.194', '3.1.1.101', '1.14.13', '3.1.3', '3.1.3.73', '3.2.1.143', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.14.13.M64', '1.1.1.M51', '3.1.3.73', '1.1.1.M51', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.106', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '1.1.1.-;1.1.1.1;1.1.1.327', '1.1.1.270', '1.14.13.98', '1.14.13.98', '1.14.13.98', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.1.1.184;1.1.1.189', '3.1.3.82', '3.1.3.29;3.1.3.50', '3.1.3.50', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1;1.1.1.51;1.1.1.62', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.1.1.271', '1.1.1.271', '1.1;1.1.1;1.1.1.209;1.1.1.213', '1.1.1.1', '1.1.99.13', '3.1.3.58;3.1.3.9', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.1.1;1.1.1.184;1.1.1.210;1.1.1.50', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.2;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.3.1.20', '1.1.1.184;1.1.1.357', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '1.1.1.367', '1.1.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.395', '1.1.1', '1.1.1.146', '1.1.1.64', '1.1.1.146', '1.1.1.146', '1.1.1.239', '1.1.1.239', '1.1.1.62', '1.1.1.270', '1.1.1.238', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1.206', '1.1.1;1.1.1.206', '3.1.3.76', '3.1.3.76', '1.1.1.102', '1.14.13.127', '1.14.13.127', '1.14.13.127', '4.2.3;4.2.3.1', '1.1.1.213;1.1.1.50', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '3.1.3.1;3.1.3.75']
45
335
Carvedilol
9

100%|██████████| 11047/11047 [00:07<00:00, 1516.88it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2012.64it/s]
 19%|█▉        | 24/126 [08:59<37:09, 21.86s/it]

rxndb num 3772
failedrxn num 0
result_df 133

100%|██████████| 11047/11047 [00:06<00:00, 1630.01it/s]
100%|██████████| 27873/27873 [00:13<00:00, 1993.08it/s]
 20%|█▉        | 25/126 [09:23<37:45, 22.43s/it]

rxndb num 617
failedrxn num 0
result_df 46
['3.1.3.69', '3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.2.1.5', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '3.1.3.-', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.3', '3.1.3.74', '3.1.3', '3.1.3.73', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3.39', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.1.6.9', '3.1.6.10', '3.8.1.7', '3.1.3.69', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.2.1.5', '1.2.1.5', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.1.3.-;3.1.3.88', '3.1.3.79', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '3.1.3.85', '3.1.3.92', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.3', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3', '3.1.3.4', '3.1.3.4', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.-', '3.1.6.14', '3.1.3.29', '1.1.1.179;1.3.1.20', '3.1.3.33;3.1.3.5', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.47', '3.1.3', '3.1.3', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '6.3.2.17', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.110', '3.1.3.91', '3.6.1;3.6.1.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3', '3.1.3.24', '3.1.3.12', '3.1.3.29', '3.1.3.-', '1.1.1.186', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.1.1.186', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '3.1.3.73', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.1.3.68', '3.1.3.M8', '3.1.3.106;3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.1.3.29', '3.2.1.4', '3.2.1.4', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.4.15.6', '3.4.19.9', '3.2.1.1', '1.3.98.-', '3.2.1.-', '3.2.1.2', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.1.101', '3.1.3.73', '3.2.1.143', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.106', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.14.19.58', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '3.1.3.76', '3.1.3.76', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '3.1.3.1;3.1.3.75']
31
118
Chlorpheniramine (maleate)
5

100%|██████████| 11047/11047 [00:03<00:00, 2765.84it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2312.14it/s]
 21%|██        | 26/126 [09:42<35:35, 21.36s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Chlorprothixene
9

100%|██████████| 11047/11047 [00:07<00:00, 1510.15it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2145.48it/s]
 21%|██▏       | 27/126 [10:05<36:09, 21.91s/it]

rxndb num 187
failedrxn num 0
result_df 17
['3.8.1.7', '1.14.13.8', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.8', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13.145', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190']
4
18
Cisapride
9

100%|██████████| 11047/11047 [00:06<00:00, 1585.26it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2135.74it/s]
 22%|██▏       | 28/126 [10:28<36:25, 22.30s/it]

rxndb num 1929
failedrxn num 0
result_df 69
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.5.1.40', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.8.1.7', '1.14.13.180', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.5.1;1.5.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.19.n5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-', '3.3.2.14', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.19', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.3.1', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.2', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.2.1.78', '3.2.1.78', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.13.-', '1.14.13.-', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.35', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '2.4.1.-', '2.4.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.4.15.6', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.3.98.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '3.2.1.143', '3.2.1.143', '3.2.1.143', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.19.58', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6']
32
76
Clonidine (hydrochloride)
9

100%|██████████| 11047/11047 [00:06<00:00, 1753.32it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2237.72it/s]
 23%|██▎       | 29/126 [10:50<35:46, 22.13s/it]

rxndb num 81
failedrxn num 0
result_df 12
['1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '3.8.1.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.97.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '3.8.1.7', '3.8.1.7', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.9', '1.14.13.9', '1.3.98.-', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.19.58']
6
16
Clopidogrel (hydrogen sulfate)
5

100%|██████████| 11047/11047 [00:03<00:00, 2999.40it/s]
100%|██████████| 27873/27873 [00:11<00:00, 2494.46it/s]
 24%|██▍       | 30/126 [11:08<33:18, 20.82s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Cyclobenzaprine (hydrochloride)
9

100%|██████████| 11047/11047 [00:06<00:00, 1583.67it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2253.29it/s]
 25%|██▍       | 31/126 [11:30<33:55, 21.43s/it]

rxndb num 304
failedrxn num 0
result_df 16
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.13.100', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.8', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1;1.14.14.55', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.48', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.8', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.6', '1.14.15.6', '1.14.13.234', '1.14.13.48', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.14.23', '1.14.13.17', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.79', '1.14.13.79', '1.14.13.77', '1.14.13.76', '1.14.13.-', '1.14.13.-', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.-;1.14.14.149', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.13.99;1.14.99', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.14.70', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.121', '1.14.13;1.14.13.143', '1.14.13;1.14.13.143', '1.14.13.145', '1.14.13.99', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.48', '1.14.13.79', '1.14.13.79', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.100;1.14.13.17;1.14.13.60', '1.14.13.99', '1.14.13.98', '1.14.13.98', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.106', '1.14.13.106', '1.14.13', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.80;1.14.14.53', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-']
8
52
Darusentan
9

100%|██████████| 11047/11047 [00:06<00:00, 1660.04it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2154.24it/s]
 25%|██▌       | 32/126 [11:54<34:35, 22.08s/it]

rxndb num 2302
failedrxn num 0
result_df 64
['3.1.3.69', '3.1.3.74', '1.2.1.5', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '3.1.3.-', '3.1.3.74', '3.1.3.74', '3.1.3.73', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.118;1.1.1.47', '1.1.1.119;1.1.1.47', '3.1.3.39', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '3.1.3.40', '3.1.6.9', '3.1.6.10', '1.14.13.19', '1.14.13.19', '1.1.1.173;1.1.1.378', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.61', '3.1.3.69', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '2.1.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.2.1.5', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.1.3.-;3.1.3.88', '3.1.3.79', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '3.1.3.85', '3.1.3.83', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.1.1.203', '1.1.1.203', '1.1.1.363;1.1.1.388', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '3.1.3.103', '3.1.3', '1.14.13', '3.1.3.-', '1.1.1.203', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.1.1.-;1.1.1.377;1.1.1.378', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.-', '3.1.6.14', '3.1.3.29', '1.1.1.179;1.3.1.20', '3.1.3.33;3.1.3.5', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.2.1.78', '1.1.1.121', '1.1.1.121', '1.1.1.47', '3.1.3', '3.1.3', '1.1.1.122', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.55', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.82', '3.2.1.4;3.2.1.91', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.76', '3.2.1.31', '3.2.1.35', '1.14.13.10', '3.1.3.91', '3.6.1;3.6.1.-', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '2.4.1.-', '2.4.1.-', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.24', '3.1.3.12', '3.1.3.29', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.3.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.1.1.186', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.1.1.186', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.1.1.107;1.1.1.122', '3.1.3.73', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.45', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.1.1.363;1.1.1.388;1.1.1.47;1.1.1.49', '1.14.13.246', '3.1.3.M8', '3.1.3.105', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.1.1.120', '3.2.1.14', '1.1.1.121;1.1.1.175', '1.1.1.121', '1.1.1.179', '1.1.1.179', '3.2.1.37', '3.2.1.37', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.1.1.121', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.2.1.1', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.2', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '3.2.1.15', '4.2.2.2', '6.2.1.3', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.73', '3.2.1.143', '3.2.1.143', '3.2.1.143', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.2.1.23', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.1.1.363;1.1.1.49', '3.1.3.82', '1.14.13.182', '1.14.13.182', '1.1.1.118', '1.1.1.120;1.1.1.179;1.1.1.359;1.1.1.360;1.1.1.47;1.1.1.48;1.3.1.20', '1.1.1.120', '1.1.1.119', '1.1.1.121;1.1.1.359;1.1.1.47;1.1.1.48', '1.1.1.121', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.1.1.363;1.1.1.47;1.1.1.49', '1.1.1.49', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '3.1.3.-;3.1.3.104']
30
160
Dexpramipexole (dihydrochloride)
5

100%|██████████| 11047/11047 [00:04<00:00, 2576.64it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2308.44it/s]
 26%|██▌       | 33/126 [12:15<33:31, 21.63s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Doxazosin (mesylate)
5

100%|██████████| 11047/11047 [00:03<00:00, 2844.30it/s]
100%|██████████| 27873/27873 [00:10<00:00, 2549.12it/s]
 27%|██▋       | 34/126 [12:33<31:30, 20.55s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
E7046
9

100%|██████████| 11047/11047 [00:07<00:00, 1431.99it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2242.68it/s]
 28%|██▊       | 35/126 [12:57<32:53, 21.68s/it]

rxndb num 928
failedrxn num 0
result_df 90
['3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '3.1.3.-', '3.1.3.74', '3.1.3.74', '3.1.3.73', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3.39', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.1.3.40', '3.1.6.9', '3.1.6.10', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.-.-', '1.14.13.180', '1.14.13.-', '1.2.1.-', '1.14.13.1', '1.2.1.-', '1.14.13.1', '1.14.13.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-', '2.1.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.1.3.-;3.1.3.88', '3.1.3.79', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.2.1.96', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '3.1.3', '3.1.3.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.1.1.415;1.1.1.ee', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.6.14', '3.1.3.29', '3.1.3.33;3.1.3.5', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.2.1.3', '1.2.1.3', '1.2.1.3', '1.2.1.3', '3.1.3', '3.1.3', '3.1.3.68', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.-', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.82', '3.2.1.15;3.2.1.82', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '3.1.3.91', '3.6.1;3.6.1.-', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '2.4.1.-', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.24', '3.1.3.29', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.3.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.21.3', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '3.1.3.73', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '4.1.1.-', '4.1.1.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.1.1.415', '3.1.3.M8', '3.1.3.105', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.1.3.29', '3.2.1.87', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '3.2.1.15', '3.2.1.15', '4.2.2.2', '4.2.2.2', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.73', '3.2.1.143', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '3.1.3.-;3.1.3.104']
26
109
Famotidine
9

100%|██████████| 11047/11047 [00:07<00:00, 1383.24it/s]
100%|██████████| 27873/27873 [00:10<00:00, 2639.71it/s]
 29%|██▊       | 36/126 [13:19<32:41, 21.80s/it]

rxndb num 48
failedrxn num 0
result_df 9
['3.5.3.1', '1.14.13.39;1.14.14.47', '1.14.13.39;1.14.14.47', '3.2.1.35', '1.14.13.97', '1.14.13.97', '3.5.3.15', '3.4.15.6', '2.5.1.-', '1.-.-.-', '2.5.1;2.5.1.-;2.5.1.48']
7
11
Fasiglifam
9

100%|██████████| 11047/11047 [00:09<00:00, 1196.21it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2058.83it/s]
 29%|██▉       | 37/126 [13:45<34:07, 23.01s/it]

rxndb num 1841
failedrxn num 0
result_df 114
['3.1.3.69', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.27', '3.1.3.74', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3.73', '3.1.6.2', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.1.1.118;1.1.1.47', '1.1.1.119;1.1.1.47', '3.1.3.39', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.17.1.1', '1.17.1.1', '1.14.14.-;1.14.14.1', '3.1.6.9', '3.1.6.10', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.1.1.173;1.1.1.378', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '3.1.3.69', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.2.1.5', '1.2.1.5', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.-;3.1.3.88', '3.1.3.79', '3.1.3.80', '3.1.3.85', '3.1.3.83', '1.14.19.n5', '1.1.1.363;1.1.1.388', '1.1.1.390', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '3.1.3;3.1.3.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '3.1.3.103', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.1.1.116', '1.1.1.359;1.1.1.376;1.1.1.46', '3.1.3', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.-;1.1.1.377;1.1.1.378', '3.1.3.4', '3.1.3.4', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13;1.14.13.-', '1.1.1.-', '1.1.1', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.3.1', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.6.14', '3.1.3.29', '1.1.1.179;1.3.1.20', '1.1.1.179;1.3.1.20', '3.1.3.33;3.1.3.5', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '3.1.3', '3.1.3', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '3.2.1.78', '1.1.1.121', '1.1.1.47', '3.1.3', '3.1.3', '3.1.6.3', '1.1.1.122', '3.1.3.68', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.55', '3.2.1.15;3.2.1.82', '3.2.1.15;3.2.1.82', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.145;3.2.1.23', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '3.1.3.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '3.2.1.137;3.2.1.78', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '2.4.1.-', '2.4.1.-', '2.4.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.23;3.1.3.29;3.1.3.9', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.1.3.27', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.24', '3.1.3.12', '3.1.3.29', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.3.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.1.1.113', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.45', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.68', '1.1.1.363;1.1.1.388;1.1.1.47;1.1.1.49', '1.14.13.246', '3.1.3.M8', '3.1.3.106;3.1.3.76', '1.1.1.376', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '1.1.1.420', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.58;3.1.3.9', '3.1.6.3', '1.1.1.120', '3.2.1.14', '3.2.1.14', '1.1.1.121;1.1.1.175', '1.1.1.121', '1.1.1.179', '1.1.1.179', '3.2.1.37', '3.2.1.37', '1.1.1.46', '1.1.1.46', '3.2.1.55', '3.2.1.55', '3.2.1.3;3.2.1.58;3.2.1.59', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.1.1.121', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.2.1.1', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.2', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '6.2.1.3', '3.2.1.137', '1.1.1.117', '1.1.1.117', '1.1.1.117', '1.1.1.117', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '3.1.3.27', '1.1.1.46', '1.1.1.46', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '3.1.1.101', '3.1.1.101', '3.1.3', '3.1.3.73', '3.2.1.143', '3.2.1.143', '3.2.1.143', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.106', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.2.1.23', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.1.1.363;1.1.1.49', '3.1.3.82', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.1.1.118', '1.1.1.120;1.1.1.179;1.1.1.359;1.1.1.360;1.1.1.47;1.1.1.48;1.3.1.20', '1.1.1.120', '3.1.3.58;3.1.3.9', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.1.1.119', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.1.1.121;1.1.1.359;1.1.1.47;1.1.1.48', '1.1.1.121', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.1.1.363;1.1.1.47;1.1.1.49', '1.1.1.49', '2.6.1.114', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.2.1', '1.1.1.424', '3.1.3.76', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127']
31
201
Fesoterodine (fumarate)
5

100%|██████████| 11047/11047 [00:04<00:00, 2224.71it/s]
100%|██████████| 27873/27873 [00:11<00:00, 2384.12it/s]
 30%|███       | 38/126 [14:05<32:24, 22.10s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Fevipiprant
9

100%|██████████| 11047/11047 [00:08<00:00, 1269.86it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2154.47it/s]
 31%|███       | 39/126 [14:30<33:28, 23.09s/it]

rxndb num 390
failedrxn num 0
result_df 32
['1.2.1.5', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.14.1', '3.1.3.73', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '3.1.3.39', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.2.1.5', '1.2.1.5', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.390', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.224', '1.14.13.224', '3.1.3', '3.1.6;3.1.6.-', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.-', '1.2.3.1', '3.1.3.33;3.1.3.5', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.1', '3.1.3', '3.1.3', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.2.1.35', '3.2.1.35', '3.1.3.91', '3.6.1;3.6.1.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '3.1.3.73', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.1.3.M8', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.176', '1.14.13', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '2.6.1.114', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '3.1.3.-;3.1.3.104']
15
55
Fezolinetant
9

100%|██████████| 11047/11047 [00:07<00:00, 1462.59it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2093.50it/s]
 32%|███▏      | 40/126 [14:56<34:01, 23.74s/it]

rxndb num 83
failedrxn num 0
result_df 11
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.91', '1.14.13.91', '2.6.1.114']
5
18
Filorexant
9

100%|██████████| 11047/11047 [00:08<00:00, 1292.25it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2254.32it/s]
 33%|███▎      | 41/126 [15:20<33:44, 23.82s/it]

rxndb num 651
failedrxn num 0
result_df 35
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.61', '1.14.13.61', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13.224', '1.14.13.224', '1.14.13.224', '1.14.13.224', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.2.3.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '1.14.13.10', '1.14.13.10', '2.4.1.-', '1.14.13.30', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.14', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.176', '1.14.13.194', '3.2.1.143', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '2.6.1.114', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-']
19
55
Fimasartan
9

100%|██████████| 11047/11047 [00:08<00:00, 1272.81it/s]
100%|██████████| 27873/27873 [00:10<00:00, 2732.94it/s]
 33%|███▎      | 42/126 [15:42<32:36, 23.29s/it]

rxndb num 290
failedrxn num 0
result_df 29
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.8', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13', '1.14.13.8', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.8', '3.8.1.8', '1.14.13.30', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.194', '2.6.1.114']
5
22
Glycopyrrolate
5

100%|██████████| 11047/11047 [00:03<00:00, 2874.61it/s]
100%|██████████| 27873/27873 [00:08<00:00, 3444.01it/s]
 34%|███▍      | 43/126 [15:57<29:01, 20.99s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
GSK1292263
9

100%|██████████| 11047/11047 [00:08<00:00, 1278.19it/s]
100%|██████████| 27873/27873 [00:11<00:00, 2414.53it/s]
 35%|███▍      | 44/126 [16:20<29:34, 21.64s/it]

rxndb num 153
failedrxn num 0
result_df 23
['1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '2.1.1.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.3.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.1', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.2.1.35', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.176', '3.2.1.143', '3.6.1.18;3.6.1.9']
10
27
GSK163090
9

100%|██████████| 11047/11047 [00:08<00:00, 1351.46it/s]
100%|██████████| 27873/27873 [00:11<00:00, 2365.98it/s]
 36%|███▌      | 45/126 [16:43<29:46, 22.06s/it]

rxndb num 393
failedrxn num 0
result_df 35
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.61', '1.14.13.61', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.2.3.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '3.2.1.14', '3.4.15.6', '3.2.1.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.176', '1.14.13', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '2.6.1.114']
14
33
GSK598809
9

100%|██████████| 11047/11047 [00:08<00:00, 1375.05it/s]
100%|██████████| 27873/27873 [00:10<00:00, 2583.32it/s]
 37%|███▋      | 46/126 [17:06<29:30, 22.13s/it]

rxndb num 125
failedrxn num 0
result_df 22
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.8', '3.8.1.8', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.32', '2.6.1.114']
5
20
Guanfacine (hydrochloride)
5

100%|██████████| 11047/11047 [00:03<00:00, 2965.38it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2248.08it/s]
 37%|███▋      | 47/126 [17:24<27:46, 21.10s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Homatropine (Bromide)
5

100%|██████████| 11047/11047 [00:03<00:00, 2770.63it/s]
100%|██████████| 27873/27873 [00:11<00:00, 2393.42it/s]
 38%|███▊      | 48/126 [17:43<26:23, 20.30s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Ibutamoren (Mesylate)
5

100%|██████████| 11047/11047 [00:03<00:00, 3055.19it/s]
100%|██████████| 27873/27873 [00:11<00:00, 2419.64it/s]
 39%|███▉      | 49/126 [18:01<25:13, 19.66s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Idalopirdine Hydrochloride
9

100%|██████████| 11047/11047 [00:06<00:00, 1761.69it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2301.22it/s]
 40%|███▉      | 50/126 [18:24<26:03, 20.57s/it]

rxndb num 582
failedrxn num 0
result_df 55
['1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.61', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.224', '1.14.13.224', '1.14.13.235', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.13.11', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.13.11.52', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '2.4.1.-', '1.13.11.52', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.13.11.11;1.13.11.52', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.13.11.11;1.13.11.52', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.13.99.3', '1.13.11.52', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13', '3.2.1.143', '1.14.13.182', '1.14.13.182', '1.13.99.3', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.6.1.18;3.6.1.9', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.13.11.52', '1.13.11.52']
18
44
Iloperidone
9

100%|██████████| 11047/11047 [00:06<00:00, 1593.34it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2068.49it/s]
 40%|████      | 51/126 [18:49<27:30, 22.01s/it]

rxndb num 1999
failedrxn num 0
result_df 64
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.7.1.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.219', '1.1.1.219', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.1.1.234', '1.1.1.234', '1.1.1.234', '1.1.1.362', '1.14.13.180', '1.14.13.180', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '1.1.1.219', '1.1.1.219', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.-.-', '1.1.1.349', '1.14.19.n5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.3.2.14', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.362', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.99', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.348', '1.1.1.348', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.3.1', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.14', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.1', '3.2.1.78', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.13.21', '1.1.1.-', '1.14.13.-', '1.14.13.-', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.-.-', '1.14.-.-', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.1.1.246;1.1.1.348', '1.1.1.219', '1.14.-.-', '2.4.1.-', '2.4.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.-.-', '1.14.-.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.219', '1.14.13.88', '1.14.13.88', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.1.1.50', '3.2.1.14', '1.14.-.-', '1.14.-.-', '3.2.1.87', '3.2.1.87', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.15.5', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.88', '1.14.13.88', '1.14.13.176', '3.2.1.143', '3.2.1.143', '1.3.1', '1.3.1.-', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-']
24
76
Imaradenant
9

100%|██████████| 11047/11047 [00:05<00:00, 1874.54it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2148.39it/s]
 41%|████▏     | 52/126 [19:12<27:35, 22.37s/it]

rxndb num 64
failedrxn num 0
result_df 17
['3.8.1.8', '3.5.4.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.8.99.3;1.8.99.5', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '3.5.4.-;3.5.4.26', '1.14.13.-', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.5.4.3', '1.1.1.2', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.1', '1.14.14.1', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.8', '3.5.4.-;3.5.99.-', '3.5.4.45;3.5.99.-', '1.14.14.1', '1.6.6.8;1.7.1.7']
9
19
Intepirdine
9

100%|██████████| 11047/11047 [00:06<00:00, 1637.39it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2144.27it/s]
 42%|████▏     | 53/126 [19:36<27:35, 22.68s/it]

rxndb num 245
failedrxn num 0
result_df 27
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.2.3.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.2.1.35', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.176', '1.14.13.176', '1.14.14.21']
6
20
Ketanserin (tartrate)
5

100%|██████████| 11047/11047 [00:03<00:00, 2900.34it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2312.63it/s]
 43%|████▎     | 54/126 [19:55<26:01, 21.68s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Ketotifen (fumarate)
5

100%|██████████| 11047/11047 [00:03<00:00, 3402.19it/s]
100%|██████████| 27873/27873 [00:11<00:00, 2385.13it/s]
 44%|████▎     | 55/126 [20:13<24:29, 20.69s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Lafutidine
9

100%|██████████| 11047/11047 [00:07<00:00, 1445.62it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2040.75it/s]
 44%|████▍     | 56/126 [20:39<25:55, 22.23s/it]

rxndb num 376
failedrxn num 0
result_df 27
['3.5.1.94', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '6.3.2.1', '3.5.1.92', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.5.1.22', '6.3.2.23', '6.3.1.2;6.3.1.6', '3.5.1.65', '6.3.2.20', '3.5.1.24;3.5.1.74', '3.5.1.24', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '6.3.2.36', '3.5.1.-', '6.3.2.44', '6.3.4.24', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13.224', '6.3.2.18', '6.3.2;6.3.2.-', '6.3.2', '6.3.2', '6.3.2', '6.3.2.59', '6.3.2.59', '3.5.1.123', '6.3.2', '3.4.13', '6.3.2', '6.3.2', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2', '3.4', '3.5.1.115', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '3.5.1.23', '3.5.1.23', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.1', '1.14.14.1', '6.3.2.18', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.4.11.5', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '2.4.1.-', '6.3.1.11', '3.5.1.-;3.5.1.78', '6.3.1.8;6.3.1.9', '3.5.1.4;3.5.1.99', '3.5.1.24;3.5.1.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '6.3.1.9', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.14.13.97', '3.5.1.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '6.3.1.13', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.3.1.10', '6.3.1.10', '3.5.1.90', '3.5.1.90', '6.3.2.56;6.3.2.ad', '3.5.1.60;3.5.1.99', '3.5.1.60', '3.5.1.60;3.5.1.99', '3.5.1.99', '3.5.1.99', '3.5.1.60', '3.2.1.14', '3.2.1.14', '3.2.1.87', '3.4.15.6', '3.4.15.6', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.3.2;6.3.2.-', '6.3.2', '3.2.1.143', '6.3.2', '6.3.2', '6.3.2', '6.3.2', '6.3.2.37', '6.3.1.10', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '6.3.2.58', '6.3.2.58', '3.6.1.18;3.6.1.9', '3.5.1.115', '6.3.1', '1.1.1;1.1.1.206', '3.5.1.46', '1.-.-.-']
26
87
Latrepirdine (dihydrochloride)
9

100%|██████████| 11047/11047 [00:09<00:00, 1196.06it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2250.90it/s]
 45%|████▌     | 57/126 [21:04<26:36, 23.13s/it]

rxndb num 370
failedrxn num 0
result_df 30
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.224', '1.14.13.224', '1.2.3.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.2.3.1', '1.13.99.3', '1.14.-.-', '1.14.-.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.176', '1.14.13.176', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.14.13.190', '1.13.99.3', '2.6.1.114', '2.6.1.114']
8
25
Lofexidine
9

100%|██████████| 11047/11047 [00:07<00:00, 1498.42it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2142.62it/s]
 46%|████▌     | 58/126 [21:28<26:31, 23.40s/it]

rxndb num 138
failedrxn num 0
result_df 24
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.18.1', '1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.13.20', '1.14.13.20', '3.8.1.7', '1.14.13.50', '1.14.13.50', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '2.1.1.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.14', '1.14.14', '1.14.13.M9', '1.14.13.20', '1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.1', '1.14.14.1', '1.14.13.50', '1.14.13.50', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.14.-', '1.3.98.-', '1.14.13.-', '1.14.13.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.143', '1.14.19.55', '1.14.19.55', '1.14.19.58', '3.6.1.18;3.6.1.9', '1.11.2.6', '1.11.2.6']
14
33
Loratadine
9

100%|██████████| 11047/11047 [00:09<00:00, 1198.54it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2210.47it/s]
 47%|████▋     | 59/126 [21:53<26:33, 23.79s/it]

rxndb num 264
failedrxn num 0
result_df 35
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.8.1.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.224', '1.14.13.224', '3.1.1', '1.14.13', '1.14.13.M9', '1.2.3.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.234', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.79', '1.14.13.79', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.3.3.8', '1.3.98.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '3.2.1.143', '1.14.13.182', '1.14.13.182', '1.14.19.58', '3.6.1.18;3.6.1.9']
13
36
Losartan (potassium)
5

100%|██████████| 11047/11047 [00:04<00:00, 2250.67it/s]
100%|██████████| 27873/27873 [00:10<00:00, 2642.70it/s]
 48%|████▊     | 60/126 [22:11<24:21, 22.15s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Loxapine (succinate)
5

100%|██████████| 11047/11047 [00:05<00:00, 1887.88it/s]
100%|██████████| 27873/27873 [00:10<00:00, 2723.26it/s]
 48%|████▊     | 61/126 [22:31<23:05, 21.32s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Lumateperone (Tosylate)
5

100%|██████████| 11047/11047 [00:03<00:00, 2807.97it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2211.67it/s]
 49%|████▉     | 62/126 [22:51<22:17, 20.90s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Maraviroc
9

100%|██████████| 11047/11047 [00:07<00:00, 1471.08it/s]
100%|██████████| 27873/27873 [00:14<00:00, 1890.62it/s]
 50%|█████     | 63/126 [23:17<23:35, 22.47s/it]

rxndb num 215
failedrxn num 0
result_df 30
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '3.5.1.92', '1.14.13.58', '1.14.13.58', '1.14.13.58', '6.3.1.2;6.3.1.6', '3.5.1.65', '6.3.2.20', '3.5.1.24;3.5.1.74', '3.5.1.24', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.5.1.-', '6.3.4.24', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '6.3.2.18', '6.3.2', '6.3.2', '6.3.2.59', '6.3.2.59', '3.4.13', '6.3.2', '1.14.13', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2', '3.5.1.115', '1.3;1.3.1.120', '1.14.13', '1.14.13', '1.14.13', '6.3.2.18', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.8', '3.8.1.8', '1.14.-.-', '1.14.13.30', '3.5.1.24;3.5.1.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.3.1.10', '6.3.1.10', '3.5.1.90', '3.5.1.90', '3.5.1.60;3.5.1.99', '3.5.1.99', '3.5.1.99', '1.3.1.120', '3.5.1.60', '1.14.-.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.3.2;6.3.2.-', '6.3.2', '6.3.2', '6.3.2', '6.3.2', '6.3.2', '6.3.2.37', '6.3.1.10', '2.6.1.114', '3.5.1.115', '1.1.1;1.1.1.206']
13
46
Mavorixafor (trihydrochloride)
5

100%|██████████| 11047/11047 [00:02<00:00, 3685.98it/s]
100%|██████████| 27873/27873 [00:09<00:00, 3007.99it/s]
 51%|█████     | 64/126 [23:32<20:55, 20.24s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Melatonin
9

100%|██████████| 11047/11047 [00:08<00:00, 1292.67it/s]
100%|██████████| 27873/27873 [00:11<00:00, 2379.92it/s]
 52%|█████▏    | 65/126 [23:55<21:33, 21.21s/it]

rxndb num 1725
failedrxn num 0
result_df 39
['3.5.1.94', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13;1.14.99.10', '6.3.2.1', '3.5.1.92', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '3.5.1.17', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.5.1.21', '3.5.1.62', '3.5.1.33', '2.3.1.32', '3.5.1;3.5.1.-;3.5.1.63', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.5.1.22', '6.3.2.23', '6.3.1.2;6.3.1.6', '3.5.1.65', '1.14.14.1', '1.14.14.1', '1.14.14.1', '6.3.2.20', '1.14.13.4', '1.14.13.4', '1.14.13.4', '3.5.1.24;3.5.1.74', '3.5.1.17', '3.5.1.24', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.61', '3.5.1.25', '1.14.13.181', '3.5.1.48', '3.5.1.76;3.5.1.85', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.5.1.-;3.5.1.112', '3.5.1.-;3.5.1.113', '6.3.2.36', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.-.-', '1.11.2.5', '1.11.2.5', '1.11.2.5', '3.5.1.-', '6.3.2.44', '6.3.4.24', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.216', '1.14.13.216', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13.224', '1.14.13.224', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '6.3.2.18', '6.3.2;6.3.2.-', '1.14.13', '6.3.2', '6.3.2', '6.3.2', '3.4.11.25', '3.5.1.-;3.5.1.136', '6.3.2.59', '6.3.2.59', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13.235', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.5.1', '1.14.13', '1.14.13;1.14.13.-', '3.4.13', '6.3.2', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.13.11', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2', '3.4', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '3.5.1.105', '3.5.1.115', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.48', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '1.14.15.15', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '3.5.1.23', '3.5.1.23', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '1.13.11.52', '6.3.2.18', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.35', '1.14.13.10', '1.14.-.-', '2.4.1.-', '6.3.1.11', '3.5.1.-;3.5.1.78', '6.3.1.8;6.3.1.9', '3.5.1.103', '1.13.11.52', '3.5.1.4;3.5.1.99', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.13.11.11;1.13.11.52', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.5.1.24;3.5.1.74', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '6.3.1.9', '1.14.99.10', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.13.11.11;1.13.11.52', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.-.-', '1.14.-.-', '3.5.1.-', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '6.3.1.13', '1.14.13.88', '1.14.13.88', '6.3.1.10', '6.3.1.10', '3.5.1.90', '3.5.1.90', '1.14.18.2', '6.3.2.56;6.3.2.ad', '3.5.1.108', '3.5.1.60;3.5.1.99', '3.5.1.60', '3.5.1.60;3.5.1.99', '3.5.1.99', '3.5.1.99', '3.5.1.62', '3.5.1.85', '3.5.1.60', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.4', '3.5.1.33', '3.2.1.14', '1.14.-.-', '1.14.-.-', '3.4.15.6', '3.4.19.7', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.13.99.3', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.13.11.52', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.15.5', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.88', '1.14.13.176', '1.14.13.176', '1.14.13.194', '6.3.2;6.3.2.-', '1.14.13', '6.3.2', '3.2.1.143', '6.3.2', '6.3.2', '6.3.2', '6.3.2', '1.14.18.2', '6.3.2.37', '6.3.1.10', '3.5.1.25', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.182', '1.14.13.182', '1.13.99.3', '3.5.1.108', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '6.3.2.58', '6.3.2.58', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.5.1.115', '3.5.1', '3.5.1.108', '3.5.1.108', '3.5.1.108', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1;1.1.1.206', '1.13.11.52', '3.5.1.108', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.13.11.52', '3.5.1.63', '3.5.1.46']
35
139
Metoprolol (Succinate)
5

100%|██████████| 11047/11047 [00:03<00:00, 2785.51it/s]
100%|██████████| 27873/27873 [00:10<00:00, 2543.65it/s]
 52%|█████▏    | 66/126 [24:15<20:40, 20.68s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Mirabegron
9

100%|██████████| 11047/11047 [00:06<00:00, 1678.75it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2124.38it/s]
 53%|█████▎    | 67/126 [24:39<21:15, 21.62s/it]

rxndb num 563
failedrxn num 0
result_df 48
['3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.1.1.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '3.1.3.-', '3.1.3.74', '3.1.3.74', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3.39', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.1.3.40', '3.1.6.9', '3.1.6.10', '3.4.22.40;3.5.1.72', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.1.3.-;3.1.3.88', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '3.1.3.92', '6.3.1.18', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.5.1.123', '3.1.3.3', '3.1.3', '3.1.3.-', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3', '1.14.13', '1.14.13', '1.14.13', '3.5.1', '1.14.13', '3.1.6.14', '3.4.11.3;3.4.11.6;3.4.22.40', '3.1.3.29', '2.3.2.2;3.4.11.10;3.4.19.3', '3.1.3.33;3.1.3.5', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.4.21.4;3.4.22;3.4.22.1', '3.3.2.6;3.4.11.10;3.4.11.15', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.35', '3.1.3.91', '3.6.1;3.6.1.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3', '3.1.3.29', '3.1.3.-', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.138', '1.14.13.140', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '3.1.3.73', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.1.3.M8', '3.1.3.105', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.1.1.50', '3.2.1.14', '3.1.3.29', '3.4.15.6', '3.4.19.5', '3.4.19.7', '3.2.1.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.138', '1.14.13.140', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1;1.1.1.206', '3.1.3.76', '4.2.3;4.2.3.1', '3.1.3.-;3.1.3.104', '3.1.3.1;3.1.3.75']
31
103
MK-0557
9

100%|██████████| 11047/11047 [00:07<00:00, 1490.73it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2223.90it/s]
 54%|█████▍    | 68/126 [25:03<21:32, 22.28s/it]

rxndb num 718
failedrxn num 0
result_df 65
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.107', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.4.22.40;3.5.1.72', '1.14.13.61', '1.14.13.61', '1.14.13.180', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '6.3.1.18', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.224', '1.14.13.224', '1.14.13.224', '1.14.13.224', '1.14.13.224', '1.14.13.224', '3.5.1.123', '1.3.1', '1.1.1.415;1.1.1.ee', '1.14.13.235', '1.14.13.235', '1.14.13.235', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.4.11.3;3.4.11.6;3.4.22.40', '2.3.2.2;3.4.11.10;3.4.19.3', '3.4.21.4;3.4.22;3.4.22.1', '3.3.2.6;3.4.11.10;3.4.11.15', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.3;1.3.1.120', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.1.1.107', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.-', '1.14.13.-', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.140', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.1.1.415', '1.3.1.120', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.4.15.6', '3.4.15.6', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.140', '1.14.13.88', '1.14.13.88', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '3.2.1.143', '3.1.1.1;3.1.1.84', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '1.1.1;1.1.1.206']
26
83
MK-3207 (Hydrochloride)
9

100%|██████████| 11047/11047 [00:08<00:00, 1319.60it/s]
100%|██████████| 27873/27873 [00:11<00:00, 2411.45it/s]
 55%|█████▍    | 69/126 [25:28<22:05, 23.25s/it]

rxndb num 629
failedrxn num 0
result_df 56
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.1.1.1', '3.1.1.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.4.22.40;3.5.1.72', '3.4.22.40;3.5.1.72', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '6.3.1.18', '6.3.1.18', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.224', '1.14.13.224', '3.5.1.123', '3.5.1.123', '1.14.13.235', '1.14.13', '1.14.13', '3.5.1', '3.5.1', '1.2.3.1', '3.4.11.3;3.4.11.6;3.4.22.40', '3.4.11.3;3.4.11.6;3.4.22.40', '2.3.2.2;3.4.11.10;3.4.19.3', '2.3.2.2;3.4.11.10;3.4.19.3', '3.4.21.4;3.4.22;3.4.22.1', '3.4.21.4;3.4.22;3.4.22.1', '3.3.2.6;3.4.11.10;3.4.11.15', '3.3.2.6;3.4.11.10;3.4.11.15', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.4.11.5', '3.4.11.5', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '3.2.1.35', '3.2.1.35', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.140', '1.14.13.140', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.2.1.14', '3.4.15.6', '3.4.15.6', '3.4.15.6', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.-', '3.2.1.-', '3.2.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.140', '1.14.13.140', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13', '1.14.13', '1.14.13.182', '1.14.13.182', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.1.1;1.1.1.206', '1.1.1;1.1.1.206', '1.1.1;1.1.1.206']
24
66
Molindone (hydrochloride)
5

100%|██████████| 11047/11047 [00:03<00:00, 2968.40it/s]
100%|██████████| 27873/27873 [00:10<00:00, 2567.62it/s]
 56%|█████▌    | 70/126 [25:46<20:20, 21.80s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Naftopidil
9

100%|██████████| 11047/11047 [00:07<00:00, 1550.42it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2029.98it/s]
 56%|█████▋    | 71/126 [26:12<21:01, 22.94s/it]

rxndb num 3364
failedrxn num 0
result_df 125

100%|██████████| 11047/11047 [00:09<00:00, 1116.65it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2194.36it/s]
 57%|█████▋    | 72/126 [26:38<21:23, 23.76s/it]

rxndb num 732
failedrxn num 0
result_df 49
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.1.60', '1.14.13.180', '1.97.1.-', '1.97.1.-', '1.97.1.-', '1.97.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.224', '1.14.13.224', '1.14.13.224', '1.14.13.224', '1.14.13.224', '1.14.13.224', '1.3.1', '1.14.14.133', '3.1.1', '1.1.1.415;1.1.1.ee', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.235', '1.14.13.235', '1.14.13.235', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.2.3.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14.25', '1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '1.14.14.55', '1.14.15.4', '1.14.15.4', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.13.-', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-', '1.14.-.-', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '2.-.-.-', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.79', '1.14.13.79', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.14.149', '1.14.14.149', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1.415', '3.2.1.14', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '3.2.1.87', '3.2.1.87', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.156', '1.14.13.176', '1.14.13.176', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13', '3.2.1.143', '3.2.1.143', '1.14.13.98', '1.14.13.98', '3.1.1.1;3.1.1.84', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.182', '1.14.13.182', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.13.11.11;1.13.11.52']
23
82
Olmesartan (medoxomil)
9

100%|██████████| 11047/11047 [00:07<00:00, 1462.93it/s]
100%|██████████| 27873/27873 [00:14<00:00, 1967.21it/s]
 58%|█████▊    | 73/126 [27:03<21:28, 24.31s/it]

rxndb num 1099
failedrxn num 0
result_df 73
['3.1.3.15', '3.1.3.74', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.27', '3.1.3.74', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.73', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '3.1.3.39', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.6.9', '3.1.6.10', '3.1.1.60', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.-;3.1.3.88', '3.1.3.79', '3.1.3.85', '1.14.-.-', '1.14.-.-', '3.1.3.83', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '3.1.3', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1.415;1.1.1.ee', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.4', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.6.14', '3.1.3.29', '1.14.15.15', '1.14.15.15', '3.1.3.33;3.1.3.5', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3.68', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '3.1.3.91', '3.6.1;3.6.1.-', '1.14.-.-', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '1.14.-.-', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.1.3.27', '1.14.13.30', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.24', '3.1.3.12', '3.1.3.29', '3.1.3.-', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.1.1.415', '3.1.3.M8', '3.1.3.106;3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '3.2.1.14', '3.2.1.14', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.4.15.6', '3.4.15.6', '3.2.1.1', '1.7.3.-', '1.7.3.-', '1.7.3.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.2', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.174', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.15.5', '1.14.15.5', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '3.1.3.27', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13', '3.1.3', '3.1.3.73', '3.2.1.143', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.106', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '3.1.1.1;3.1.1.84', '3.1.3.82', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '2.6.1.114', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.76', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75']
28
148
Olodanrigan
9

100%|██████████| 11047/11047 [00:07<00:00, 1481.60it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2184.99it/s]
 59%|█████▊    | 74/126 [27:27<20:57, 24.18s/it]

rxndb num 2974
failedrxn num 0
result_df 140
['3.1.3.69', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.2.1.5', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.74', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.73', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.118;1.1.1.47', '1.1.1.119;1.1.1.47', '3.1.3.39', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '3.1.6.9', '3.1.6.10', '1.14.13.19', '1.14.13.19', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.69', '1.17.1.3', '1.17.1.3', '1.14.13.-', '1.17.1.3', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-', '2.1.1.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.2.1.5', '1.2.1.5', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.2.1.5', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.-;3.1.3.88', '3.1.3.79', '1.14.14.-;1.14.14.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '3.1.3.85', '3.1.3.83', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.1.1.203', '1.1.1.203', '1.1.1.363;1.1.1.388', '1.1.1.390', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.3.2.14', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '3.1.3.103', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.1.1.116', '1.1.1.359;1.1.1.376;1.1.1.46', '3.1.3', '1.14.13', '3.1.3.-', '1.1.1.203', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3', '3.1.3.4', '3.1.3.4', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.-', '1.1.1', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.6.14', '3.1.3.29', '1.1.1.179;1.3.1.20', '1.1.1.179;1.3.1.20', '3.1.3.33;3.1.3.5', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.4.13.9', '3.4.13.9', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3', '3.1.3', '3.2.1.78', '1.1.1.121', '1.1.1.121', '1.1.1.47', '3.1.3', '3.1.3', '3.1.6.3', '1.1.1.122', '3.1.3.68', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '3.4.11.5', '3.4.11.5', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.55', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.82', '3.2.1.15;3.2.1.82', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.145;3.2.1.23', '3.2.1.76', '3.2.1.76', '3.2.1.31', '3.2.1.31', '3.2.1.35', '3.2.1.35', '3.1.3.91', '3.6.1;3.6.1.-', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '3.2.1.137;3.2.1.78', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '2.4.1.-', '2.4.1.-', '3.1.3.23;3.1.3.29;3.1.3.9', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.24', '3.1.3.12', '3.1.3.29', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.3.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.1.1.113', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.1.1.107;1.1.1.122', '3.1.3.73', '3.1.3', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.45', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.68', '1.1.1.363;1.1.1.388;1.1.1.47;1.1.1.49', '1.14.13.246', '3.1.3.M8', '3.1.3.106;3.1.3.76', '1.1.1.376', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '1.1.1.420', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.58;3.1.3.9', '3.1.6.3', '1.1.1.120', '3.2.1.14', '3.2.1.14', '1.1.1.121;1.1.1.175', '1.1.1.121', '1.1.1.179', '1.1.1.179', '3.2.1.37', '3.2.1.37', '1.1.1.46', '1.1.1.46', '3.2.1.55', '3.2.1.55', '3.2.1.3;3.2.1.58;3.2.1.59', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.1.1.121', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.2.1.87', '3.4.15.6', '3.4.15.6', '3.4.19.7', '3.4.19.7', '3.2.1.1', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.2', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.15', '3.2.1.15', '4.2.2.2', '4.2.2.2', '6.2.1.3', '6.2.1.3', '3.2.1.137', '1.1.1.117', '1.1.1.117', '1.1.1.117', '1.1.1.117', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.1.1.46', '1.1.1.46', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.1.101', '3.1.1.101', '1.14.13', '3.1.3', '3.1.3.73', '3.2.1.143', '3.2.1.143', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.106', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '1.14.13.149', '3.2.1.23', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.1.1.363;1.1.1.49', '3.1.3.82', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.118', '1.1.1.120;1.1.1.179;1.1.1.359;1.1.1.360;1.1.1.47;1.1.1.48;1.3.1.20', '1.1.1.120', '3.1.3.58;3.1.3.9', '1.1.1.119', '1.1.1.121;1.1.1.359;1.1.1.47;1.1.1.48', '1.1.1.121', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.1.1.363;1.1.1.47;1.1.1.49', '1.1.1.49', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.2.1', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1.424', '1.1.1;1.1.1.206', '3.1.3.76', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '3.1.3.-;3.1.3.104']
37
203
Otilonium (bromide)
5

100%|██████████| 11047/11047 [00:03<00:00, 2880.10it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2213.54it/s]
 60%|█████▉    | 75/126 [27:47<19:33, 23.00s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Oxybutynin (chloride)
5

100%|██████████| 11047/11047 [00:04<00:00, 2586.53it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2319.92it/s]
 60%|██████    | 76/126 [28:07<18:24, 22.09s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Ozanimod
9

100%|██████████| 11047/11047 [00:06<00:00, 1829.27it/s]
100%|██████████| 27873/27873 [00:15<00:00, 1821.82it/s]
 61%|██████    | 77/126 [28:32<18:40, 22.86s/it]

rxndb num 1317
failedrxn num 0
result_df 74
['3.1.3.69', '1.1.1.23', '3.1.3.15', '1.1.1.3', '1.1.1.3', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.74', '3.1.3.74', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.1', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.1.3.23', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3.39', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.1.1.191;1.1.1.2;1.1.1.21', '1.1.1.150', '1.1.1.151', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.6.9', '3.1.6.10', '1.14.13.19', '1.14.13.19', '1.1.1.1;1.1.1.90', '4.3.3.-', '1.14.13.72', '3.1.3.69', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.1', '1.14.14.-;1.14.14.1', '1.1.1.1', '1.14.13.15;1.14.15.15', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.-;3.1.3.88', '3.1.3.79', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '3.1.3.85', '1.14.-.-', '3.1.3.83', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '3.1.3', '1.1.1.1', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.1.1;1.1.1.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.1.1', '3.1.3', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.3.48', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '1.1.1', '1.1.1.1', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.14.145', '3.1.6.14', '3.1.3.29', '1.14.15.15', '1.14.15.15', '3.1.3.33;3.1.3.5', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '1.1.1.2;1.1.1.21', '1.14.14.55', '1.14.14.55', '3.2.1.78', '3.1.3', '3.1.3', '3.1.6.3', '3.1.3.68', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '3.2.1.154;3.2.1.26;3.2.1.80', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '3.2.1.65', '3.2.1.145;3.2.1.23', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '3.1.3.91', '3.6.1;3.6.1.-', '3.2.1.137;3.2.1.78', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '2.4.1.-', '1.14.-.-', '1.14.-.-', '3.1.3.23;3.1.3.29;3.1.3.9', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.30', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.24', '3.1.3.12', '3.1.3.29', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.3.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.1.1.23', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.72', '3.1.3.70', '1.1.1.273', '1.1.1.273', '1.1.1.273', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.-.-', '1.14.-.-', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.-.-;1.14.13.-', '1.1.1.317', '1.1.1.317', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.1.1.1;1.1.1.161', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.45', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.88', '1.14.13.88', '3.1.3.68', '1.14.13.246', '3.1.3.M8', '1.1.1.273', '3.1.3.105', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.1.3.58;3.1.3.9', '3.1.6.3', '3.2.1.55', '3.2.1.55', '3.2.1.3;3.2.1.58;3.2.1.59', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.2.1.1', '1.7.3.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.-', '3.2.1.2', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.15.5', '1.14.15.5', '1.14.15.5', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '3.2.1.137', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.1.1.71', '1.1.1.71', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.88', '1.14.13.88', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.194', '1.14.13', '3.1.3', '3.1.3.73', '3.2.1.143', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.73', '3.1.3', '1.1.1.2;1.1.1.20;1.1.1.21', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '1.1.1.1;1.1.1.161', '1.14.13.15;1.14.15.15', '1.14.13.98', '1.14.13.98', '1.14.13.72', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '3.1.3.82', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '3.1.3.58;3.1.3.9', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '3.1.3.76', '3.1.3.76', '1.1.1.1', '1.1.1.1;1.1.1.190', '3.1.3.-;3.1.3.104']
33
193
Pardoprunox (hydrochloride)
5

100%|██████████| 11047/11047 [00:03<00:00, 3259.41it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2272.33it/s]
 62%|██████▏   | 78/126 [28:51<17:24, 21.77s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Pavinetant
9

100%|██████████| 11047/11047 [00:09<00:00, 1110.99it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2109.91it/s]
 63%|██████▎   | 79/126 [29:18<18:09, 23.19s/it]

rxndb num 388
failedrxn num 0
result_df 36
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.8.99.3;1.8.99.5', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13', '1.14.12.16', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.-', '1.14.13.-', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.-', '3.2.1.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.176', '1.14.13.176', '1.14.13.182', '1.14.13.182']
8
27
Pericyazine
9

100%|██████████| 11047/11047 [00:08<00:00, 1296.78it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2163.08it/s]
 63%|██████▎   | 80/126 [29:43<18:15, 23.81s/it]

rxndb num 818
failedrxn num 0
result_df 42
['3.1.3.74', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.74', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.73', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.1.1.1;1.1.1.163;1.1.1.184;1.1.1.245;1.1.1.90', '1.1.1.148', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.147', '1.1.1.147', '1.1.1.62', '1.1.1.62', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.270', '1.14.13.-;1.14.15.-;1.14.15.3', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.270', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.1.3.-;3.1.3.88', '1.1.1.213', '1.1.1.335', '1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.374', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.1.1.393', '3.1.3.-', '3.1.3;3.1.3.-', '1.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.395', '1.1.1.-;1.1.1.395', '3.1.3', '1.1.1.-;1.1.1.270', '1.1.1.145', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.1.1', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.270', '1.1.1.270', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.2;1.1.1.213;1.1.1.239;1.1.1.62;1.3.1.20', '1.1.1.1', '1.1.1.188;1.1.1.213;1.1.1.50', '1.1.1.145', '3.1.3.33;3.1.3.5', '1.1.1.239;1.1.1.51', '1.1.1.239;1.1.1.51', '1.1.1.184', '1.1.1;1.1.1.184;1.1.1.62', '1.1.1.184;1.1.1.2;1.1.1.62', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.1.1', '1.1.1.209', '1.1.1.209', '1.1.1.357;1.1.1.50', '1.1.1.210;1.1.1.357', '1.1.1.184;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.50', '1.1.1.184;1.1.1.50', '1.1.1.184;1.1.1.188;1.1.1.2', '3.1.3', '3.1.3', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '3.1.3.91', '3.6.1;3.6.1.-', '3.1.3.2;3.1.3.31;3.1.3.34', '1.1.1.239;1.1.1.51', '1.1.1;1.1.1.239;1.1.1.62;1.1.1.64', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.2;1.1.1.209;1.1.1.21;1.1.1.213;1.1.1.50;1.3.1.20', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '1.1.1;1.1.1.148;1.1.1.209', '1.1.1.206', '1.1.1.236', '1.1.1.201', '1.1.1.213;1.1.1.52', '1.1.1.152;1.1.1.184;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1.184;1.1.1.209;1.1.1.213;1.1.1.50', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.1.1.213;1.1.1.50', '1.1.1.209;1.1.1.50', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.1.1.210;1.1.1.357;1.1.1.50;1.1.1.51', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.1;1.1.1.391', '1.1.1.-;1.1.1.146;1.1.1.209;1.1.1.213;1.1.1.392;1.1.1.50', '3.1.3.73', '1.1.1.270', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.213;1.1.1.50;1.1.1.51;1.1.1.53', '1.1.1.-;1.1.1.M53', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1.270', '1.1.1.270', '1.1.1.270', '3.1.3.M8', '1.1.1', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.-;1.1.1.270', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.1.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.14.13.M64', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '1.1.1.270', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.1.1;1.1.1.51;1.1.1.62', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.1.1;1.1.1.184;1.1.1.210;1.1.1.50', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.2;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.3.1.20', '1.1.1.184;1.1.1.357', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '1.1.1.395', '1.1.1.270', '1.1.1.206', '1.1.1.206', '1.1.1.213;1.1.1.50', '3.1.3.-;3.1.3.104']
14
99
PF-04418948
9

100%|██████████| 11047/11047 [00:06<00:00, 1694.65it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2031.43it/s]
 64%|██████▍   | 81/126 [30:09<18:15, 24.34s/it]

rxndb num 2353
failedrxn num 0
result_df 125
['3.1.3.69', '3.1.3.74', '1.2.1.5', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '3.1.3.-', '3.1.3.74', '3.1.3.74', '3.1.3.73', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.118;1.1.1.47', '1.1.1.119;1.1.1.47', '3.1.3.39', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.1.6.9', '3.1.6.10', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '3.1.3.69', '1.14.13.180', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '2.1.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.2.1.5', '1.2.1.5', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.2.1.5', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.1.3.-;3.1.3.88', '3.1.3.79', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '3.1.3.85', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.1.1.363;1.1.1.388', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '3.3.2.14', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '3.1.3.103', '3.1.3', '1.14.13', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.-', '3.1.6.14', '3.1.3.29', '1.1.1.179;1.3.1.20', '3.1.3.33;3.1.3.5', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.121', '1.1.1.47', '3.1.3', '3.1.3', '3.1.3.68', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.-', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '3.1.3.91', '3.6.1;3.6.1.-', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '2.4.1.-', '2.4.1.-', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.24', '3.1.3.12', '3.1.3.29', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.3.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '3.1.3.73', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.45', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.1.1.363;1.1.1.388;1.1.1.47;1.1.1.49', '1.14.13.246', '3.1.3.M8', '3.1.3.105', '1.1.1.420', '1.1.1.120', '3.2.1.14', '3.2.1.14', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.1.1.121', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.2.1.87', '3.2.1.1', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.2', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.153;3.2.1.26;3.2.1.80', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3', '3.1.3.73', '3.2.1.143', '3.2.1.143', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.2.1.23', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.1.1.363;1.1.1.49', '1.1.1.118', '1.1.1.120;1.1.1.179;1.1.1.359;1.1.1.360;1.1.1.47;1.1.1.48;1.3.1.20', '1.1.1.120', '1.1.1.119', '1.1.1.121;1.1.1.359;1.1.1.47;1.1.1.48', '1.1.1.121', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.1.1.363;1.1.1.47;1.1.1.49', '1.1.1.49', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.2.1', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '3.1.3.-;3.1.3.104']
27
142
Pimavanserin tartrate
5

100%|██████████| 11047/11047 [00:03<00:00, 3003.69it/s]
100%|██████████| 27873/27873 [00:11<00:00, 2369.69it/s]
 65%|██████▌   | 82/126 [30:28<16:48, 22.91s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Pindolol
9

100%|██████████| 11047/11047 [00:07<00:00, 1549.11it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2163.61it/s]
 66%|██████▌   | 83/126 [30:52<16:40, 23.27s/it]

rxndb num 1409
failedrxn num 0
result_df 51
['3.1.3.69', '1.1.1.14;1.1.1.6', '1.1.1.1;1.1.1.10;1.1.1.156;1.1.1.2;1.1.1.21;1.1.1.72;1.3.1.20', '3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.27', '3.1.3.3', '3.1.3.74', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.6.2', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.1.1;1.1.1.10', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3.22;3.1.3.23', '3.1.3.39', '1.1.1.148', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.3.16', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.147', '1.1.1.147', '3.1.3.40', '3.1.6.9', '3.1.6.10', '1.14.13.19', '1.14.13.19', '1.1.1;1.1.1.-', '1.-.-.-;1.1.1.342', '1.1.1.62', '1.1.1.62', '1.1.1.53', '1.1.1.50', '1.1.1.53', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.14.13.61', '1.14.13.61', '1.1.1.2;1.1.1.21;1.1.1.261', '1.1.1.263', '1.1.1.270', '3.1.3.69', '1.1.1.297', '1.1.1;1.1.1.-', '1.1.1.364', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.1.1.270', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.1.1.-', '1.1.1;1.1.1.-;1.1.1.50', '1.-.-.-', '1.1.1.292', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.162', '1.1.1.-', '1.1.1.-', '1.1.1.-;1.1.1.341;4.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.-;1.1.1.329', '3.1.3.-;3.1.3.88', '1.1.1.297', '1.1.1.-', '1.1.1.239;1.1.1.62', '1.1.1.213', '1.1.1.209;1.1.1.213;1.1.1.357', '1.1.1.62', '3.1.3.79', '1.1.3.-;1.1.3.45', '1.1.1.297', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.13.130', '3.1.3.85', '1.14.-.-', '3.1.3.83', '1.1.1.323', '1.1.1.323', '1.1.1.-;1.1.1.329', '1.1.1.335', '1.1.1.339;1.1.1.344', '1.1.1.355', '1.1.1.356', '1.1.1.356', '1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.361', '3.1.3.92', '1.1.1.364', '1.1.1.367', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.1.1.374', '1.1.1.385', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.1.1.393', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3.101', '3.1.3.-', '1.1.1.-', '1.1.1.-', '1.1.1.-', '3.1.3;3.1.3.-', '1.1.1.-', '1.1.1.14;1.1.1.162;1.1.1.403', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13.224', '1.14.13.224', '3.1.3.103', '1.1.1.289', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.1.1.395', '1.1.1.-;1.1.1.395', '1.1.1.14;1.1.1.15', '1.1.1', '1.1.1.14', '1.1.3.11', '3.1.3.3', '3.1.3', '3.1.3.-', '3.1.3;3.1.3.-', '1.1.1.201', '1.1.1.-;1.1.1.50;1.1.1.52', '1.1.1.391', '1.1.1.15', '1.1.1.-;1.1.1.270', '1.1.1;1.1.1.-;1.1.1.270', '1.1.1.-;1.1.1.270', '3.1.3;3.1.3.-', '1.1.1;1.1.1.-;1.1.1.12', '1.1.1', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.1.1.102', '1.1.1.145', '1.1.1;1.1.1.-', '1.1.1;1.1.1.-', '1.14.14.133', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.13.235', '1.14.13.235', '1.1.1', '3.1.3.50', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13;1.14.13.-', '1.14.13', '1.1.1', '1.1.1', '3.1.3', '3.1.3.4', '1.1.1.201', '1.1.1', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1', '1.1.1.M2', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.11.2.M1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.M11', '1.1.1.M11', '1.1.1.392', '1.1.1.393', '1.1.1.52', '1.1.1.391', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.52', '1.1.1.391', '1.1.1.392;1.1.1.50;1.1.1.52', '1.1.1.392', '1.1.1.393', '1.1.1.393', '3.1.3', '1.1.1.M28', '1.1.1.14;1.1.1.M29', '1.1.1', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.13.11', '3.1.3', '3.1.3;3.1.3.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1.270', '1.1.1.270', '1.1.1.123', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.2;1.1.1.213;1.1.1.239;1.1.1.62;1.3.1.20', '1.1.1.159', '1.1.1.218', '3.1.6.14', '1.1.1.218', '1.1.1.1', '1.1.1.188;1.1.1.213;1.1.1.50', '1.1.1.1', '3.1.3.29', '3.1.3.29', '1.14.15.15', '1.1.1.149', '1.1.1.145', '1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50;1.3.1.20', '3.1.3.33;3.1.3.5', '1.1.1.133', '1.1.1.239;1.1.1.51', '1.1.1.239;1.1.1.51', '1.1.1.184', '1.1.1;1.1.1.184;1.1.1.62', '1.1.1.184;1.1.1.2;1.1.1.62', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.213;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.50', '1.1.1.51', '1.14.13.126;1.14.15.16', '1.1.1;1.1.1.209', '1.1.1.292', '1.1.1', '1.1.1.209', '1.1.1.209', '1.1.1.209', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.1.1.357;1.1.1.50', '1.1.1.210;1.1.1.357', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '1.14.14.55', '3.2.1.78', '3.2.1.78', '1.1.1.184;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.50', '1.1.1.184;1.1.1.50', '1.1.1.12;1.1.1.14', '1.1.1.12;1.1.1.14', '1.1.1.12', '1.1.1;1.1.1.10;1.1.1.405', '1.1.1.10', '3.1.3', '3.1.3', '1.1.1.146;1.1.1.159;1.1.1.50', '3.1.6.3', '1.1.99.13', '3.1.3.68', '1.14.16.-', '1.1.1.162', '1.1.1.-', '1.14.15.4', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.133', '1.14.15.4', '1.14.15.6', '1.1.1.297', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '3.2.1.154;3.2.1.26;3.2.1.80', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.55', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '1.1.1.-', '3.2.1.65', '3.2.1.145;3.2.1.23', '3.2.1.110', '1.14.13.10', '1.14.13.10', '3.1.3.91', '3.6.1;3.6.1.-', '3.2.1.137;3.2.1.78', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '1.1.1.239;1.1.1.51', '1.1.1;1.1.1.239;1.1.1.62;1.1.1.64', '2.4.1.-', '1.14.-.-', '1.14.-.-', '1.1.1.-;1.1.1.146', '1.1.1;1.1.1.-;1.1.1.146;1.1.1.51', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62;1.1.1.63', '1.1.1.184;1.1.1.2;1.1.1.213;1.1.1.51;1.1.1.64', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.2;1.1.1.209;1.1.1.21;1.1.1.213;1.1.1.50;1.3.1.20', '3.1.3.23;3.1.3.29;3.1.3.9', '1.1.1.124;1.1.1.138;1.1.1.14;1.1.1.67;1.1.99.11;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '3.1.3.27', '1.1.1.14;1.1.1.56', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '1.1.1.12;1.1.1.124;1.1.1.138;1.1.1.14;1.1.1.67;1.1.1.9;1.1.99.11;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.1.3.24', '1.1.1.133', '3.1.3.12', '1.1.1.14;1.1.1.9', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '1.1.1.271', '1.1.1.124;1.1.1.138;1.1.1.21;1.1.1.287;1.1.1.67;1.1.99.11;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '1.1.1.124;1.14.13.50;2.5.1.18;2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.1.3.29', '1.13.11.17', '1.14.16.-', '1.1.1;1.1.1.148;1.1.1.209', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.3.-', '1.1.1.134;1.1.1.344', '1.1.1.159;1.1.1.50', '1.1.1.176', '1.1.1.206', '1.1.1.236', '1.1.1.16', '1.1.1.198', '1.1.1.227', '1.1.1.241', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.1.1.174', '1.1.1.135;1.1.1.187', '1.1.1.187;1.1.1.281', '1.1.1.135;1.1.1.187', '1.1.1.187;1.1.1.281', '1.1.1.51', '1.1.1.51;1.1.1.62;1.1.1.64', '1.1.1.238', '1.14.13.74', '1.1.1.201', '1.1.1.146', '1.1.1.213;1.1.1.52', '1.1.1.152;1.1.1.184;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1.184;1.1.1.209;1.1.1.213;1.1.1.50', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.1.1.213;1.1.1.50', '1.1.1.50', '1.1.1.209;1.1.1.50', '1.1.1.213;1.1.1.50;1.1.1.51', '1.1.1.149;1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '2.-.-.-', '1.1.1.266', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.1.1.213;1.1.1.277;1.1.1.50', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.278', '1.14.13.94', '1.14.13.96', '1.14.13.97', '3.1.3.21;3.1.3.25;3.1.3.29', '3.1.3.21;3.1.3.25', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.137', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.-.-', '1.14.-.-', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.147', '1.1.1.210;1.1.1.357;1.1.1.50;1.1.1.51', '1.14.13.-', '1.1.1.1;1.1.1.391', '1.1.1.-;1.1.1.146;1.1.1.209;1.1.1.213;1.1.1.392;1.1.1.50', '3.1.3.73', '1.1.1;1.1.1.-', '3.1.3', '3.1.3', '1.1.1.159', '1.1.1.-', '1.1.1.270', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.14.13.88', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '1.1.1;1.1.1.10', '1.1.1.153', '1.1.1.10;1.1.1.14;1.1.1.15', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.213;1.1.1.50;1.1.1.51;1.1.1.53', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.45', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.1.1.-;1.1.1.M53', '1.14.13;1.14.13.-', '1.14.13.88', '3.1.3', '3.1.3.68', '1.1.1.270', '1.1.1.270', '1.1.1.270', '1.1.1.201', '1.1.1.425', '3.1.3.M8', '1.1.1', '1.1.1.323', '1.1.1.323', '1.1.1.266', '3.1.3.106;3.1.3.76', '1.1.1.367', '1.1.1.406', '1.1.1.407', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.1.1', '1.1.1', '1.1.1.14', '1.1.1', '1.1.1.10', '1.1.3.10', '1.1.3.10', '3.1.3.58;3.1.3.9', '3.1.6.3', '3.2.1.37', '3.2.1.37', '3.2.1.55', '3.2.1.55', '3.2.1.3;3.2.1.58;3.2.1.59', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.1.1.227', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.1.1.297', '1.1.1.297', '1.14.13.126', '1.14.-.-', '1.14.-.-', '1.1.1.323', '1.1.1.323', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.2.1.1', '1.1.1.-', '1.7.3.-', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.-', '1.14.13.-', '1.14.13.-', '3.2.1.2', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.72', '1.14.15.5', '1.1.1.-;1.1.1.270', '1.1.1.-;1.1.1.270', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '3.2.1.137', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.96', '1.1.1.-', '3.1.3.27', '1.14.13.137', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.88', '1.14.13.176', '1.14.13.176', '1.14.13.183', '1.14.13.184', '3.1.3', '3.1.3.73', '3.2.1.143', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.14.13.M64', '1.1.1.M51', '3.1.3.73', '1.1.1.M51', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.106', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '1.1.1.-;1.1.1.1;1.1.1.327', '1.1.1.270', '1.14.13.98', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '3.1.3.82', '3.1.3.29;3.1.3.50', '3.1.3.50', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.1.1;1.1.1.51;1.1.1.62', '1.14.13.-;1.14.15.6', '1.1.1.271', '1.1.1.271', '1.1;1.1.1;1.1.1.209;1.1.1.213', '1.1.1.1', '1.1.99.13', '3.1.3.58;3.1.3.9', '1.17.99.5', '1.1.1;1.1.1.184;1.1.1.210;1.1.1.50', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.2;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.3.1.20', '1.1.1.184;1.1.1.357', '1.14.13.97', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '1.1.5.3;1.1.99.5', '1.1.1.367', '1.1.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.395', '1.1.1', '1.1.1.146', '1.1.1.64', '1.1.1.146', '1.1.1.239', '1.1.1.62', '1.1.1.270', '1.1.1.238', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1.206', '3.1.3.76', '3.1.3.76', '1.1.1.102', '4.2.3;4.2.3.1', '1.1.1.213;1.1.1.50', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '3.1.3.1;3.1.3.75', '1.1.1.261', '3.1.3.1;3.1.3.19;3.1.3.2;3.1.3.25;3.1.3.29', '1.1.1.8;1.1.1.94;1.1.5.3', '1.1.1.49;1.1.1.8;1.1.1.94;1.3.1.20', '3.1.3.2;3.1.3.21']
38
311
Piribedil
9

100%|██████████| 11047/11047 [00:07<00:00, 1452.59it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2257.09it/s]
 67%|██████▋   | 84/126 [31:16<16:28, 23.53s/it]

rxndb num 244
failedrxn num 0
result_df 27
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '2.1.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '1.14.13.224', '1.14.13.224', '1.14.13.235', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.2.1.22', '3.2.1.22', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.2.1.161;3.2.1.188;3.2.1.21;3.2.1.23;3.2.1.25;3.2.1.3;3.2.1.37;3.2.1.45;3.2.1.58;3.2.1.74', '3.2.1.161;3.2.1.188;3.2.1.21;3.2.1.23;3.2.1.25;3.2.1.3;3.2.1.37;3.2.1.45;3.2.1.58;3.2.1.74', '3.2.1.3', '3.2.1.3', '3.2.1;3.2.1.10;3.2.1.177;3.2.1.199;3.2.1.20;3.2.1.21;3.2.1.70', '3.2.1;3.2.1.10;3.2.1.177;3.2.1.199;3.2.1.20;3.2.1.21;3.2.1.70', '3.2.1.21;3.2.1.22;3.2.1.23', '3.2.1.21;3.2.1.22;3.2.1.23', '3.2.1.22;3.2.1.23;3.2.1.85', '3.2.1.22;3.2.1.23;3.2.1.85', '1.14.14.55', '3.2.1.55', '3.2.1.55', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.8', '1.14.21.8', '1.14.21.8', '2.4.1.-', '2.4.1.-', '1.14.21.2', '1.14.21.2', '1.14.19.68;1.14.21.5', '1.14.19.68;1.14.21.5', '1.14.21.1', '1.14.21.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '3.2.1.20;3.2.1.22', '3.2.1.20;3.2.1.22', '1.14.21.8', '1.14.21.8', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '6.2.1.3', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.143', '3.2.1.143', '1.14.13.182', '1.14.13.182', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9']
13
57
Ponesimod
9

100%|██████████| 11047/11047 [00:06<00:00, 1642.04it/s]
100%|██████████| 27873/27873 [00:14<00:00, 1889.57it/s]
 67%|██████▋   | 85/126 [31:42<16:29, 24.14s/it]

rxndb num 1791
failedrxn num 0
result_df 69
['3.1.3.69', '3.1.3.69', '3.1.3.74', '3.1.3.74', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.-', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.74', '3.1.3.27', '3.1.3.27', '3.1.3.74', '3.1.3.74', '1.1.1.1', '3.1.3', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.1.3.23', '3.1.3.39', '3.1.3.39', '1.1.3.16', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '3.1.3.40', '3.1.3.40', '3.1.6.9', '3.1.6.9', '3.1.6.10', '3.1.6.10', '1.14.13.19', '1.14.13.19', '1.1.1;1.1.1.-', '3.8.1.7', '1.-.-.-;1.1.1.342', '1.1.1.62', '1.1.1.62', '1.1.1.53', '1.1.1.50', '1.1.1.53', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.263', '1.1.3.39', '1.14.13.72', '3.1.3.69', '3.1.3.69', '1.1.1;1.1.1.-', '1.1.1.364', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.-', '1.1.1;1.1.1.-;1.1.1.50', '1.-.-.-', '1.1.1.292', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.-', '1.1.1.-', '1.1.1.-;1.1.1.341;4.2.1.-', '1.14.13.15;1.14.15.15', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.-;1.1.1.329', '1.1.3.-;1.1.3.43', '3.1.3.-;3.1.3.88', '3.1.3.-;3.1.3.88', '1.1.3.-;1.1.3.44', '1.1.1.-', '1.1.1.213', '3.1.3.79', '3.1.3.79', '1.1.3.-;1.1.3.45', '3.1.3.85', '3.1.3.85', '1.14.-.-', '3.1.3.83', '3.1.3.83', '1.1.1.-;1.1.1.329', '1.1.1.335', '1.1.1.339;1.1.1.344', '1.1.3;1.1.3.-', '1.1.1.355', '1.1.1.356', '1.1.1.356', '3.1.3.92', '3.1.3.92', '1.1.1.364', '1.1.1.367', '1.1.1.374', '1.1.1.385', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '3.1.3.101', '3.1.3.101', '3.1.3.-', '3.1.3.-', '1.1.1.-', '1.1.3.-', '1.1.1.-', '1.1.1.-', '3.1.3;3.1.3.-', '3.1.3;3.1.3.-', '1.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '3.1.3.103', '3.1.3.103', '1.1.1.395', '1.1.1.-;1.1.1.395', '3.1.3', '3.1.3', '1.1.1.1', '3.1.3.-', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.1.1.145', '1.1.1;1.1.1.-', '1.14.13;1.14.13.-', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.1.1', '1.1.1', '1.1.1', '1.1.1', '3.1.3', '3.1.3', '1.1.1', '3.1.3.4', '3.1.3.4', '1.1.1', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1', '1.14.19', '1.1.1.M2', '1.1.3.48', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '1.1.1.M11', '1.1.1.M11', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1', '4.2.1.M11', '1.1.1', '1.1.1.1', '1.1.1.218', '3.1.6.14', '3.1.6.14', '1.1.1.218', '3.1.3.29', '3.1.3.29', '1.14.15.15', '1.1.1.149', '3.1.3.33;3.1.3.5', '3.1.3.33;3.1.3.5', '1.1.1.133', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.213;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.50', '1.14.13.126;1.14.15.16', '1.1.1.292', '1.1.3.9', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '1.14.14.55', '3.2.1.78', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '1.1.99.13', '3.1.3.68', '3.1.3.68', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.133', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '3.2.1.154;3.2.1.26;3.2.1.80', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.4;3.2.1.91', '3.2.1.65', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.35', '3.1.3.91', '3.1.3.91', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '3.1.3.29', '2.4.1.-', '1.1.1.-;1.1.1.146', '1.1.1;1.1.1.-;1.1.1.146;1.1.1.51', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.27', '3.1.3.27', '1.14.13.30', '3.1.3', '3.1.3', '3.1.3.24', '3.1.3.24', '1.1.1.133', '3.1.3.12', '3.1.3.12', '1.1.1.-', '1.1.1.271', '1.1.1.136', '1.1.1.132', '3.1.3.29', '3.1.3.29', '3.1.3.-', '3.1.3.-', '1.1.1.134;1.1.1.344', '1.1.1.206', '1.1.1.236', '1.1.1.135;1.1.1.187', '1.1.1.187;1.1.1.281', '1.1.1.135;1.1.1.187', '1.1.1.187;1.1.1.281', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.1.1.186', '1.1.1.146', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.1.1.50', '1.1.1.209;1.1.1.50', '2.-.-.-', '1.1.1.266', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.72', '3.1.3.70', '3.1.3.70', '1.1.1.273', '1.1.1.273', '1.1.1.273', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.1.1.186', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.68', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.1.1.317', '1.1.1.317', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3.73', '1.1.1;1.1.1.-', '3.1.3', '3.1.3', '3.1.3', '1.1.1.-', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.1.1.1;1.1.1.161', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.45', '3.1.3.45', '1.1.1.-;1.1.1.336', '1.1.1.22', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.1.1.-;1.1.1.M53', '3.1.3.68', '3.1.3.68', '1.14.13.246', '1.1.1.201', '3.1.3.M8', '3.1.3.M8', '1.1.1', '1.1.1.273', '1.1.1.266', '3.1.3.106;3.1.3.76', '3.1.3.106;3.1.3.76', '1.1.1.367', '3.1.3.106;3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.106', '3.1.3.76', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '3.1.3.105', '1.1.1', '3.2.1.14', '3.2.1.55', '3.2.1.55', '3.2.1.55', '3.2.1.55', '3.1.3.29', '3.1.3.29', '3.2.1.4', '3.2.1.4', '3.2.1.4', '3.2.1.4', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.-.-', '1.14.-.-', '3.2.1.116', '3.2.1.116', '3.2.1.60', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.4.15.6', '3.2.1.1', '3.2.1.1', '1.7.3.-', '1.7.3.-', '1.3.98.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.-', '3.2.1.2', '3.2.1.2', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.174', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.15.5', '1.14.15.5', '1.14.15.5', '1.14.-.-', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.1.1.-', '3.1.3.27', '3.1.3.27', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.184', '1.14.13.194', '3.1.3', '3.1.3', '3.1.3.73', '3.1.3.73', '3.2.1.143', '3.1.3.73', '3.1.3.73', '3.1.3', '3.1.3', '3.1.3.73', '3.1.3.73', '3.3.2', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.1.1.M51', '3.1.3.73', '3.1.3.73', '1.1.1.M51', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.106', '3.1.3.106', '3.1.3.73', '3.1.3.73', '3.1.3', '3.1.3', '1.1.1.2;1.1.1.20;1.1.1.21', '3.1.3.2;3.1.3.5', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.5.1', '3.2.1.23', '3.2.1.23', '1.1.1.1;1.1.1.161', '1.14.13.15;1.14.15.15', '1.14.13.72', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7;3.1.3.97', '3.1.3.7', '3.1.3.7', '1.1.1.184;1.1.1.189', '3.1.3.82', '3.1.3.82', '1.14.19.58', '1.1.1.271', '1.1.1.271', '1.1.99.13', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '2.6.1.114', '3.1.3.-', '3.1.3.-', '3.1.3', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '1.1.1.367', '1.1.1.-', '1.1.1.395', '1.1.1', '1.1.1;1.1.1.206', '3.1.3.76', '3.1.3.76', '3.1.3.76', '3.1.3.76', '1.1.1.1', '3.1.3.-;3.1.3.104', '3.1.3.-;3.1.3.104', '1.-.-.-']
31
215
Proglumide
9

100%|██████████| 11047/11047 [00:05<00:00, 1872.25it/s]
100%|██████████| 27873/27873 [00:14<00:00, 1943.02it/s]
 68%|██████▊   | 86/126 [32:06<16:00, 24.02s/it]

rxndb num 1126
failedrxn num 0
result_df 66
['3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.2.1.5', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.27', '3.1.3.3', '3.1.3', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.5.1.40', '3.1.3.39', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.17.1.1', '1.17.1.1', '3.1.6.9', '3.1.6.10', '1.3.1.5', '1.3.1.5', '1.3.1.48', '1.3.1.48', '1.14.13.180', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.76', '1.2.1.-', '1.2.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.2.1.5', '1.2.1.5', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.2.1.5', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.5.1;1.5.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.-;3.1.3.88', '1.14.-.-', '1.2.-.-', '1.2.-.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.-.-', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.3', '3.1.3', '1.3.3.6', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.13', '1.3.1.93', '1.3.1.93', '1.3.1.93', '1.3.1.93', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.14', '1.14.14', '1.14.14', '3.1.3', '3.1.6.c', '3.1.3.4', '1.3.1.93', '3.1.3.4', '1.3.1.93', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.1;1.2.1.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '1.2.1', '1.3.1', '1.3.1', '1.14.13;1.14.13.-', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.3.3.6', '1.3.1.48', '1.3.1.48', '1.3.1.48', '3.1.6.14', '3.1.3.29', '3.1.3.29', '1.14.15.15', '1.1.1.179;1.3.1.20', '3.1.3.33;3.1.3.5', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.1.1.47', '3.1.3', '3.1.3', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.13.-', '3.4.11.5', '3.4.11.5', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '6.3.2.17', '6.3.2.17', '6.3.2.17', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.18', '3.2.1.110', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '3.2.1.35', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '3.1.3.91', '3.6.1;3.6.1.-', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.15.3', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.1.3.27', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.29', '3.1.3.-', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '3.1.3.63', '3.1.3.63', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.3.1.104;1.3.1.38;1.3.1.8', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.3.1.104;1.3.1.38;1.3.1.44;1.3.1.8', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.-.-;1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '1.1.1;1.3.1.44', '3.1.3', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.3.99.-', '1.3.99.3', '1.1.1;1.3.99.3', '1.3.1.9', '1.3.1.-', '1.14.13.246', '3.1.6.d', '3.1.3.M8', '1.3.1.42', '3.1.3.106;3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.2.1.14', '3.1.3.29', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-', '1.14.-.-;1.14.13.-', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '3.4.15.6', '3.4.15.6', '3.4.15.6', '3.4.19.9', '3.4.19.9', '3.4.19.9', '3.4.19.5', '3.4.19.5', '3.4.19.5', '3.4.19.7', '3.4.19.7', '3.4.19.7', '1.2.1.5', '1.14.13.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.-', '3.2.1.-', '3.2.1.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.174', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.15.5', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.2.1.5', '3.1.3.27', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '3.1.1.101', '3.1.1.101', '3.1.1.101', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '3.1.3.73', '1.3.3.6', '3.1.3.73', '3.1.3.73', '3.1.3.106', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '1.3.1.93', '1.3.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '1.3.1.104;1.3.1.38;1.3.1.8', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.3.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.3.3.6;1.3.8.1;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.3.3.6', '1.3.3.6', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.3.1.10;1.3.1.38;1.3.1.8', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '5.2.1.M1', '1.2.1', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.3.1.74', '1.1.1;1.1.1.206', '3.1.3.76', '3.1.3.76', '4.2.3;4.2.3.1', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '3.1.3.1;3.1.3.75', '1.14.13.-', '1.14.-.-;1.14.13.-;1.14.13.cs']
40
152
Prucalopride
9

100%|██████████| 11047/11047 [00:06<00:00, 1671.62it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2047.45it/s]
 69%|██████▉   | 87/126 [32:29<15:33, 23.93s/it]

rxndb num 561
failedrxn num 0
result_df 43
['1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.5.1.40', '1.14.14.1', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.8.1.7', '1.14.13.180', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.5.1;1.5.1.-', '1.14.13.-', '1.14.19.n5', '1.11.2.5', '1.14.13.209', '1.14.13.-', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.-.-', '2.1.1.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '1.1.1.2', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '3.2.1.78', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.13.-', '1.14.13.-', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '2.4.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.14.1', '1.14.13.52;1.14.14.88', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.11', '1.14.13.103', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.9', '3.2.1.14', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '3.2.1.87', '3.2.1.87', '3.4.15.6', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.3.98.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13', '3.2.1.143', '3.2.1.143', '1.14.19.58', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9']
27
75
Ranitidine (hydrochloride)
9

100%|██████████| 11047/11047 [00:06<00:00, 1714.01it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2191.31it/s]
 70%|██████▉   | 88/126 [32:52<14:55, 23.55s/it]

rxndb num 363
failedrxn num 0
result_df 13
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.58', '1.14.13.58', '1.14.13.29', '1.14.13.29', '1.14.13.-', '1.14.13.-', '1.14.13.8', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.8', '1.14.13', '1.14.13', '1.14.13.25', '1.14.13.25', '1.14.18.1', '1.14.18.1', '3.4.11.5', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.14.22;1.14.99.46', '3.4.15.6', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '2.5.1.-', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.-.-.-', '2.5.1;2.5.1.-;2.5.1.48']
9
28
Rauwolscine (hydrochloride)
5

100%|██████████| 11047/11047 [00:04<00:00, 2534.44it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2213.83it/s]
 71%|███████   | 89/126 [33:13<13:59, 22.70s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Relugolix
9

100%|██████████| 11047/11047 [00:06<00:00, 1635.52it/s]
100%|██████████| 27873/27873 [00:13<00:00, 1995.60it/s]
 71%|███████▏  | 90/126 [33:37<13:56, 23.22s/it]

rxndb num 1304
failedrxn num 0
result_df 34
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.14.13.8', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.8', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '3.2.1.35', '2.4.1.-', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.140', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '3.2.1.14', '3.2.1.14', '3.2.1.14', '3.2.1.-', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.2.1.3', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.140', '1.14.13.176', '1.14.13.176', '3.2.1.143', '3.2.1.143', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9']
14
38
Reparixin (L-lysine salt)
5

100%|██████████| 11047/11047 [00:03<00:00, 3020.55it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2223.31it/s]
 72%|███████▏  | 91/126 [33:57<12:56, 22.18s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Risperidone
9

100%|██████████| 11047/11047 [00:09<00:00, 1193.32it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2097.56it/s]
 73%|███████▎  | 92/126 [34:23<13:14, 23.37s/it]

rxndb num 256
failedrxn num 0
result_df 26
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13;1.14.14', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13', '1.14.13', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '2.6.1.114', '1.14.14', '1.14.14', '1.14.14']
8
31
Rolapitant
9

100%|██████████| 11047/11047 [00:08<00:00, 1285.44it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2168.67it/s]
 74%|███████▍  | 93/126 [34:49<13:12, 24.03s/it]

rxndb num 1123
failedrxn num 0
result_df 69
['3.5.1.94', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '6.3.2.1', '3.5.1.92', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.5.1.22', '6.3.2.23', '6.3.1.2;6.3.1.6', '3.5.1.65', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '6.3.2.20', '1.17.1.1', '1.17.1.1', '1.14.14.-;1.14.14.1', '1.3.1.5', '1.3.1.5', '3.5.1.24;3.5.1.74', '3.5.1.24', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '6.3.2.36', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.-.-', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '3.5.1.-', '6.3.2.44', '6.3.4.24', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.3.2.18', '6.3.2;6.3.2.-', '1.3.3.6', '6.3.2', '6.3.2', '6.3.2', '1.3.1.93', '1.3.1.93', '6.3.2.59', '6.3.2.59', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1.93', '1.3.1.93', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.4.13', '6.3.2', '1.3.1.93', '1.3.1.93', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '1.3.1', '1.3.1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2', '3.4', '3.5.1.115', '1.3.3.6', '3.5.1.23', '3.5.1.23', '3.5.1.23', '1.3.1.48', '1.3.1.48', '3.5.1.23', '3.5.1.23', '3.5.1.23', '1.14.15.15', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '3.5.1.23', '3.5.1.23', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '6.3.2.18', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-', '1.3.1;1.3.1.-', '1.3.1;1.3.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.3.1.11', '3.5.1.-;3.5.1.78', '6.3.1.8;6.3.1.9', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.5.1.4;3.5.1.99', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.5.1.24;3.5.1.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '6.3.1.9', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.3.1.104;1.3.1.38;1.3.1.8', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.3.1.104;1.3.1.38;1.3.1.44;1.3.1.8', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.-.-', '1.14.-.-', '3.5.1.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '6.3.1.13', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1;1.3.1.44', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.3.99.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.3.99.3', '1.1.1;1.3.99.3', '1.3.1.9', '6.3.1.10', '6.3.1.10', '3.5.1.90', '3.5.1.90', '6.3.2.56;6.3.2.ad', '3.5.1.60;3.5.1.99', '3.5.1.60', '3.5.1.60;3.5.1.99', '3.5.1.99', '3.5.1.99', '3.5.1.60', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.4', '3.2.1.14', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '3.2.1.87', '3.4.15.6', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.72', '1.14.15.5', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '6.3.2;6.3.2.-', '6.3.2', '3.2.1.143', '6.3.2', '6.3.2', '1.3.3.6', '6.3.2', '6.3.2', '6.3.2.37', '1.3.1.93', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.3.3.6', '1.3.1.104;1.3.1.38;1.3.1.8', '6.3.1.10', '1.3.99.-', '1.3.99.-', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.3.3.6;1.3.8.1;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.3.3.6', '1.3.3.6', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.3.1.10;1.3.1.38;1.3.1.8', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '6.3.2.58', '6.3.2.58', '3.6.1.18;3.6.1.9', '3.5.1.115', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1;1.1.1.206', '3.5.1.46']
36
130
Sarpogrelate (hydrochloride)
9

100%|██████████| 11047/11047 [00:07<00:00, 1491.15it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2077.97it/s]
 75%|███████▍  | 94/126 [35:14<13:00, 24.40s/it]

rxndb num 3614
failedrxn num 0
result_df 160

100%|██████████| 11047/11047 [00:08<00:00, 1344.36it/s]
100%|██████████| 27873/27873 [00:11<00:00, 2353.54it/s]
 75%|███████▌  | 95/126 [35:38<12:32, 24.28s/it]

rxndb num 1763
failedrxn num 0
result_df 22
['1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '2.1.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '3.3.2.14', '3.3.2.14', '2.1.1.-', '2.1.1.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.2.1.35', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.2.1.3', '6.2.1.3', '3.2.1.143', '3.2.1.143', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9']
9
24
Selexipag
9

100%|██████████| 11047/11047 [00:06<00:00, 1825.30it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2290.00it/s]
 76%|███████▌  | 96/126 [36:01<11:52, 23.75s/it]

rxndb num 237
failedrxn num 0
result_df 27
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '1.14.-.-', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.14', '3.2.1.14', '1.14.-.-', '3.4.15.6', '3.4.15.6', '3.2.1.-', '3.2.1.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '3.2.1.143', '3.6.1.18;3.6.1.9', '1.1.1;1.1.1.206']
15
36
Sertindole
9

100%|██████████| 11047/11047 [00:07<00:00, 1464.21it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2241.57it/s]
 77%|███████▋  | 97/126 [36:24<11:24, 23.59s/it]

rxndb num 239
failedrxn num 0
result_df 31
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.8.1.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.224', '1.14.13.224', '1.14.13.235', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.4.11.5', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.3.98.-', '3.2.1.-', '2.5.1.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.176', '1.14.13.182', '1.14.13.182', '1.14.19.58']
9
29
Setipiprant
9

100%|██████████| 11047/11047 [00:08<00:00, 1341.51it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2315.08it/s]
 78%|███████▊  | 98/126 [36:48<11:05, 23.78s/it]

rxndb num 747
failedrxn num 0
result_df 42
['3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.2.1.5', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '3.1.3.-', '3.1.3.73', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.1.6.9', '3.1.6.10', '1.14.13.61', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.2.1.5', '1.2.1.5', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.1.3.-;3.1.3.88', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3', '3.1.3.-', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.-', '3.1.3.33;3.1.3.5', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.4.11.5', '3.4.11.5', '6.3.2.17', '6.3.2.17', '3.2.1.18', '3.2.1.18', '3.1.3.91', '3.6.1;3.6.1.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.29', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '3.1.3.73', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.1.3.M8', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.1.3.29', '3.4.15.6', '3.4.15.6', '3.4.19.9', '3.4.19.9', '3.4.19.7', '3.4.19.7', '3.2.1.-', '3.2.1.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.176', '3.1.1.101', '3.1.1.101', '1.14.13', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.14.13.182', '1.14.13.182', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '1.2.1', '3.1.3.76', '3.1.3.-;3.1.3.104']
17
67
Setiptiline (maleate)
5

100%|██████████| 11047/11047 [00:04<00:00, 2733.85it/s]
100%|██████████| 27873/27873 [00:11<00:00, 2356.85it/s]
 79%|███████▊  | 99/126 [37:08<10:09, 22.57s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Silodosin
9

100%|██████████| 11047/11047 [00:06<00:00, 1635.00it/s]
100%|██████████| 27873/27873 [00:14<00:00, 1920.67it/s]
 79%|███████▉  | 100/126 [37:32<10:02, 23.18s/it]

rxndb num 1407
failedrxn num 0
result_df 93
['3.1.3.69', '1.1.1.23', '3.1.3.15', '1.1.1.3', '1.1.1.3', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.27', '3.1.3.74', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.1', '3.1.3', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.6.2', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.1.3.23', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.3.17', '3.10.1.1', '3.1.3.39', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.1.1.191;1.1.1.2;1.1.1.21', '1.1.1.150', '1.1.1.151', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.6.9', '3.1.6.10', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.72', '3.1.3.69', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.14.13.180', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.76', '2.1.1.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.5.1;1.5.1.-', '1.1.1;1.1.1.-;1.1.1.1', '1.14.13.15;1.14.15.15', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.-;3.1.3.88', '3.1.3.79', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '3.1.3.85', '1.14.-.-', '3.1.3.83', '1.14.19.n5', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '3.1.3.103', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '3.1.3', '1.1.1.1', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.1.1;1.1.1.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.1.1', '3.1.3', '1.1.1', '3.1.3.4', '3.1.3.4', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.3.48', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1', '1.1.1.1', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.3.1', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.14.145', '3.1.6.14', '3.1.3.29', '1.14.15.15', '1.14.15.15', '3.1.3.33;3.1.3.5', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '2.3.2.2;6.3.1.2', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '1.14.14.55', '1.14.14.55', '3.2.1.78', '3.1.3', '3.1.3', '3.1.3.68', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.13.-', '1.14.13.-', '3.4.11.5', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '3.1.3.91', '3.6.1;3.6.1.-', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '2.4.1.-', '2.4.1.-', '1.14.-.-', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.1.3.27', '1.14.13.30', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.24', '3.1.3.12', '2.3.2.7', '3.1.3.29', '1.1.1.32;1.1.1.88', '1.1.1.2;1.1.1.32;1.1.1.33', '3.1.3.-', '1.1.1.23', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.72', '3.1.3.70', '1.1.1.273', '1.1.1.273', '1.1.1.273', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.78', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.-.-', '1.14.-.-', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.1.1.317', '1.1.1.317', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3', '1.14.14.149', '1.14.14.149', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.1.1.1;1.1.1.161', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.45', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.3.68', '1.1.99.1', '1.14.13.246', '3.1.3.M8', '1.1.1.273', '3.1.3.106;3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-;1.14.13.-', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.2.1.87', '3.4.15.6', '3.4.19.7', '3.2.1.1', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.-', '3.2.1.2', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.15.5', '1.14.15.5', '1.14.15.5', '1.1.1.1', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.1.1.71', '1.1.1.71', '3.1.3.27', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.194', '1.14.13.194', '1.14.13', '1.14.13', '3.1.3', '3.1.3.73', '3.2.1.143', '3.2.1.143', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.106', '3.1.3.73', '3.1.3', '1.1.1.2;1.1.1.20;1.1.1.21', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '1.1.1.1;1.1.1.161', '1.14.13.15;1.14.15.15', '1.14.13.98', '1.14.13.98', '1.14.13.72', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '3.1.3.82', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '3.1.3.76', '3.1.3.76', '1.1.1.1', '4.2.3;4.2.3.1', '1.1.1.1;1.1.1.190', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '1.1.1;1.1.1.1']
42
201
Sitaxsentan (sodium)
9

100%|██████████| 11047/11047 [00:05<00:00, 1954.33it/s]
100%|██████████| 27873/27873 [00:10<00:00, 2565.17it/s]
 80%|████████  | 101/126 [37:52<09:13, 22.16s/it]

rxndb num 236
failedrxn num 0
result_df 36
['1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.8.1.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '2.1.1.-', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '3.2.1.40', '3.2.1.40', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.348', '3.2.1.21;3.2.1.23', '3.2.1.21;3.2.1.23', '3.2.1.22', '3.2.1.22', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.13', '1.14.13', '1.14.13', '3.2.1.161;3.2.1.188;3.2.1.21;3.2.1.23;3.2.1.25;3.2.1.3;3.2.1.37;3.2.1.45;3.2.1.58;3.2.1.74', '3.2.1.161;3.2.1.188;3.2.1.21;3.2.1.23;3.2.1.25;3.2.1.3;3.2.1.37;3.2.1.45;3.2.1.58;3.2.1.74', '3.2.1.3', '3.2.1.3', '3.2.1;3.2.1.10;3.2.1.177;3.2.1.199;3.2.1.20;3.2.1.21;3.2.1.70', '3.2.1;3.2.1.10;3.2.1.177;3.2.1.199;3.2.1.20;3.2.1.21;3.2.1.70', '3.2.1.51', '3.2.1.51', '3.2.1.21;3.2.1.22;3.2.1.23', '3.2.1.21;3.2.1.22;3.2.1.23', '3.2.1.22;3.2.1.23;3.2.1.85', '3.2.1.22;3.2.1.23;3.2.1.85', '3.2.1.55', '3.2.1.55', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '1.14.21.8', '1.14.21.8', '3.2.1.35', '3.2.1.35', '2.4.1.-', '2.4.1.-', '1.14.21.2', '1.14.21.2', '1.14.19.68;1.14.21.5', '1.14.19.68;1.14.21.5', '1.14.21.1', '1.14.21.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '3.2.1.20;3.2.1.22', '3.2.1.20;3.2.1.22', '3.2.1.14', '3.2.1.14', '1.3.98.-', '1.14.21.8', '1.14.21.8', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '6.2.1.3', '6.2.1.3', '1.14.13', '3.2.1.143', '3.2.1.143', '1.14.19.58', '1.14.14.7;1.14.19.9', '2.6.1.114', '2.6.1.114', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9']
19
63
Sograzepide
9

100%|██████████| 11047/11047 [00:06<00:00, 1718.46it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2062.13it/s]
 81%|████████  | 102/126 [38:15<08:57, 22.40s/it]

rxndb num 836
failedrxn num 0
result_df 47
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.1.1.53', '1.1.1.53', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.-', '1.1.1.-', '1.1.1;1.1.1.-;1.1.1.50', '1.1.1;1.1.1.-;1.1.1.50', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.213', '1.1.1.213', '1.1.1.335', '1.1.1.335', '1.1.1.374', '1.1.1.374', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.1.1.-', '1.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.224', '1.14.13.224', '1.1.1.395', '1.1.1.395', '1.1.1.-;1.1.1.395', '1.1.1.-;1.1.1.395', '1.1.1.201', '1.1.1.201', '1.1.1.-;1.1.1.50;1.1.1.52', '1.1.1.-;1.1.1.50;1.1.1.52', '1.1.1.391', '1.1.1.391', '1.1.1.145', '1.1.1.145', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.392;1.1.1.50;1.1.1.52', '1.1.1.392;1.1.1.50;1.1.1.52', '1.1.1.393', '1.1.1.393', '1.1.1.159', '1.1.1.159', '1.2.3.1', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.50', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.18', '1.14.-.-', '3.2.1.35', '3.2.1.35', '3.2.1.35', '1.14.-.-', '1.14.13.30', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.1.1.159;1.1.1.50', '1.1.1.159;1.1.1.50', '1.1.1.176', '1.1.1.176', '1.1.1.206', '1.1.1.206', '1.1.1.236', '1.1.1.236', '1.1.1.238', '1.1.1.238', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.1.1.50', '1.1.1.50', '1.1.1.209;1.1.1.50', '1.1.1.209;1.1.1.50', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.140', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.1.1.153', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.1.1.-;1.1.1.M53', '1.1.1.-;1.1.1.M53', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.3.3.8', '1.1.1.201', '1.1.1.201', '1.1.1', '1.1.1', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.1.1', '1.1.1', '3.2.1.14', '3.2.1.14', '3.2.1.14', '1.14.-.-', '3.4.15.6', '3.4.15.6', '3.4.15.6', '3.2.1.-', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.1.1.-', '1.1.1.-', '1.14.13.140', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.176', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.1.1.395', '1.1.1.395', '1.1.1.238', '1.1.1.238', '1.1.1;1.1.1.206', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50']
14
64
Sparsentan
9

100%|██████████| 11047/11047 [00:07<00:00, 1458.22it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2113.02it/s]
 82%|████████▏ | 103/126 [38:39<08:47, 22.95s/it]

rxndb num 368
failedrxn num 0
result_df 41
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.2.1.35', '3.2.1.35', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '3.2.1.143', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '2.6.1.114', '2.6.1.114', '3.6.1.18;3.6.1.9', '1.1.1;1.1.1.206']
10
30
Talnetant
9

100%|██████████| 11047/11047 [00:06<00:00, 1598.68it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2089.90it/s]
 83%|████████▎ | 104/126 [39:03<08:33, 23.32s/it]

rxndb num 2098
failedrxn num 0
result_df 141

100%|██████████| 11047/11047 [00:06<00:00, 1725.66it/s]
100%|██████████| 27873/27873 [00:11<00:00, 2481.26it/s]
 83%|████████▎ | 105/126 [39:24<07:54, 22.59s/it]

rxndb num 772
failedrxn num 0
result_df 49
['3.5.1.94', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '6.3.2.1', '3.5.1.92', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.5.1.22', '6.3.2.23', '6.3.1.2;6.3.1.6', '3.5.1.65', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '6.3.2.20', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.17.1.1', '1.17.1.1', '1.14.14.-;1.14.14.1', '3.5.1.24;3.5.1.74', '3.5.1.24', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.3.2.36', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.-.-', '1.3.1.95', '1.11.2.5', '1.11.2.5', '1.11.2.5', '3.5.1.-', '6.3.2.44', '6.3.4.24', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '6.3.2.18', '6.3.2;6.3.2.-', '6.3.2', '6.3.2', '6.3.2', '1.14.13', '3.4.11.25', '1.14.13;1.14.13.-', '6.3.2.59', '6.3.2.59', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.4.13', '6.3.2', '1.3.3.6', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2', '3.4', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '3.5.1.115', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '3.5.1.23', '1.14.15.15', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '3.5.1.23', '3.5.1.23', '1.14.13', '1.14.13', '1.14.13', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '6.3.2.18', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-', '2.4.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.3.1.11', '3.5.1.-;3.5.1.78', '6.3.1.8;6.3.1.9', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.3.99.3', '3.5.1.4;3.5.1.99', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.5.1.24;3.5.1.74', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '6.3.1.9', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.-.-', '1.14.-.-', '3.5.1.-', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.-.-;1.14.13.-', '6.3.1.13', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.88', '6.3.1.10', '6.3.1.10', '3.5.1.90', '3.5.1.90', '6.3.2.56;6.3.2.ad', '3.5.1.60;3.5.1.99', '3.5.1.60', '3.5.1.60;3.5.1.99', '3.5.1.99', '3.5.1.99', '3.5.1.60', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.4', '3.2.1.14', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-;1.14.13.-', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '3.2.1.87', '3.4.15.6', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.174', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.15.5', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.88', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.194', '6.3.2;6.3.2.-', '3.1.1.101', '1.14.13', '6.3.2', '3.2.1.143', '6.3.2', '6.3.2', '1.14.13.M64', '1.14.13.M64', '6.3.2', '6.3.2', '1.3.1.-;1.3.1.84', '6.3.2.37', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '6.3.1.10', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '6.3.2.58', '6.3.2.58', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.5.1.115', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1;1.1.1.206', '3.5.1.46']
36
135
Telcagepant
9

100%|██████████| 11047/11047 [00:07<00:00, 1439.39it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2127.45it/s]
 84%|████████▍ | 106/126 [39:49<07:43, 23.17s/it]

rxndb num 450
failedrxn num 0
result_df 38
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.5.99.9', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.224', '1.14.13.224', '1.14.13', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.17.1.4', '1.2.3.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.8', '3.8.1.8', '3.4.11.5', '3.4.11.5', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '3.2.1.35', '1.17.5.-;1.17.5.2', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.2.1.14', '3.4.15.6', '3.4.15.6', '3.4.15.6', '3.2.1.-', '3.2.1.-', '3.2.1.-', '1.14.14.1', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.176', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.1.1;1.1.1.206']
17
46
Telmisartan
9

100%|██████████| 11047/11047 [00:07<00:00, 1553.04it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2120.47it/s]
 85%|████████▍ | 107/126 [40:13<07:23, 23.36s/it]

rxndb num 1415
failedrxn num 0
result_df 65
['3.1.3.15', '3.1.3.74', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.73', '3.1.6.2', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '3.1.3.39', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.99.2', '1.14.99.2', '1.14.99.2', '1.14.99.2', '4.1.1.98', '1.14.13.180', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '3.1.3', '1.14.13;1.14.13.-', '1.1.1.415;1.1.1.ee', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.12.16', '1.14.12.16', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.15.15', '3.1.3.33;3.1.3.5', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14.25', '1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '1.2.1.3', '1.14.14.55', '1.14.14.55', '3.1.3', '3.1.3', '1.14.15.4', '1.14.15.4', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.6', '1.14.15.6', '3.8.1.8', '3.8.1.8', '1.14.13.-', '1.14.13.-', '3.4.11.5', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '3.1.3.91', '3.6.1;3.6.1.-', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.79', '1.14.13.79', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.-.-', '1.14.-.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '4.1.1.-', '4.1.1.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1.415', '3.1.3.M8', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.-.-.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.13.174', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.15.5', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.176', '1.14.13.176', '1.14.13.176', '1.14.13.176', '1.14.13.176', '1.14.13.176', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.194', '1.14.13', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '1.14.13.98', '1.14.13.98', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '2.6.1.114', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75']
20
93
Thioridazine (hydrochloride)
5

100%|██████████| 11047/11047 [00:04<00:00, 2565.75it/s]
100%|██████████| 27873/27873 [00:10<00:00, 2540.07it/s]
 86%|████████▌ | 108/126 [40:32<06:36, 22.04s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Ticagrelor
9

100%|██████████| 11047/11047 [00:06<00:00, 1585.99it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2052.61it/s]
 87%|████████▋ | 109/126 [40:56<06:25, 22.67s/it]

rxndb num 1962
failedrxn num 0
result_df 96
['3.1.3.69', '3.1.3.69', '3.1.3.69', '1.1.1.23', '3.1.3.15', '3.1.3.15', '3.1.3.15', '3.1.3.74', '3.1.3.74', '3.1.3.74', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.31;3.1.3.5', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '3.1.5.1', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.-', '3.1.3.-', '3.1.3.74', '3.1.3.74', '3.1.3.74', '3.1.3.27', '3.1.3.27', '3.1.3.27', '3.1.3.74', '3.1.3.74', '3.1.3.74', '1.1.1.1', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.1.3.23', '1.1.1.137', '1.1.1.137', '1.1.1.137;1.1.1.405', '1.1.1.137;1.1.1.405', '3.1.3.39', '3.1.3.39', '3.1.3.39', '1.1.1.148', '1.1.1.148', '1.1.3.16', '1.1.3.16', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.1.1.191;1.1.1.2;1.1.1.21', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.6.9', '3.1.6.9', '3.1.6.9', '3.1.6.10', '3.1.6.10', '3.1.6.10', '1.1.1;1.1.1.-', '1.1.1;1.1.1.-', '1.-.-.-;1.1.1.342', '1.-.-.-;1.1.1.342', '1.1.1.62', '1.1.1.62', '1.1.1.62', '1.1.1.62', '1.1.1.53', '1.1.1.53', '1.1.1.50', '1.1.1.50', '1.1.1.53', '1.1.1.53', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.263', '1.1.1.263', '1.1.3.39', '1.14.13.72', '3.1.3.69', '3.1.3.69', '3.1.3.69', '1.1.1;1.1.1.-', '1.1.1;1.1.1.-', '1.1.1.364', '1.1.1.364', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.-', '1.1.1.-', '1.1.1;1.1.1.-;1.1.1.50', '1.1.1;1.1.1.-;1.1.1.50', '1.-.-.-', '1.1.1.292', '1.1.1.292', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.1', '1.1.1.-', '1.1.1.-', '1.1.1.-', '1.1.1.-', '1.1.1.-;1.1.1.341;4.2.1.-', '1.1.1.-;1.1.1.341;4.2.1.-', '1.14.13.15;1.14.15.15', '1.1.1.-;1.1.1.329', '1.1.1.-;1.1.1.329', '1.1.3.-;1.1.3.43', '3.1.3.-;3.1.3.88', '3.1.3.-;3.1.3.88', '3.1.3.-;3.1.3.88', '1.1.3.-;1.1.3.44', '1.1.1.-', '1.1.1.-', '1.1.1.213', '1.1.1.213', '3.1.3.79', '3.1.3.79', '3.1.3.79', '1.1.3.-;1.1.3.45', '1.1.3.-;1.1.3.45', '1.1.1.301', '1.1.1.301', '3.1.3.85', '3.1.3.85', '3.1.3.85', '1.14.-.-', '3.1.3.83', '3.1.3.83', '3.1.3.83', '1.1.1.-;1.1.1.329', '1.1.1.-;1.1.1.329', '1.1.1.335', '1.1.1.335', '1.1.1.339;1.1.1.344', '1.1.1.339;1.1.1.344', '1.1.3;1.1.3.-', '1.1.1.355', '1.1.1.355', '1.1.1.356', '1.1.1.356', '1.1.1.356', '1.1.1.356', '1.1.1.361', '1.1.1.361', '3.1.3.92', '3.1.3.92', '3.1.3.92', '1.1.1.364', '1.1.1.364', '1.1.1.367', '1.1.1.367', '1.1.1.374', '1.1.1.374', '1.1.1.385', '1.1.1.385', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3.101', '3.1.3.101', '3.1.3.101', '3.1.3.-', '3.1.3.-', '3.1.3.-', '1.1.1.-', '1.1.1.-', '1.1.3.-', '1.1.1.-', '1.1.1.-', '1.1.1.-', '1.1.1.-', '3.1.3;3.1.3.-', '3.1.3;3.1.3.-', '3.1.3;3.1.3.-', '1.1.1.-', '1.1.1.-', '1.1.1.402', '1.1.1.402', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.395', '1.1.1.395', '1.1.1.-;1.1.1.395', '1.1.1.-;1.1.1.395', '1.1.1', '1.1.1', '3.1.3', '3.1.3', '3.1.3', '1.1.1.1', '3.1.3.-', '3.1.3.-', '3.1.3.-', '1.1.1;1.1.1.-', '1.1.1;1.1.1.-', '1.1.1.201', '1.1.1.201', '1.1.1.-;1.1.1.50;1.1.1.52', '1.1.1.-;1.1.1.50;1.1.1.52', '1.1.1.391', '1.1.1.391', '3.1.3;3.1.3.-', '3.1.3;3.1.3.-', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.1.1.102', '1.1.1.102', '1.1.1.145', '1.1.1.145', '1.1.1', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.34', '3.1.3.34', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.1.1', '1.1.1', '1.1.1', '1.1.1', '1.1.1', '1.1.1', '1.1.1', '3.1.3', '3.1.3', '3.1.3', '1.1.1', '1.1.1.201', '1.1.1.201', '1.1.1', '1.1.1', '1.1.1', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1', '1.1.1', '1.1.1.M2', '1.1.1.M2', '1.1.3.48', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '1.1.1.M11', '1.1.1.M11', '1.1.1.M11', '1.1.1.M11', '1.1.1.392', '1.1.1.392', '1.1.1.393', '1.1.1.393', '1.1.1.52', '1.1.1.52', '1.1.1.391', '1.1.1.391', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.52', '1.1.1.52', '1.1.1.391', '1.1.1.391', '1.1.1.392;1.1.1.50;1.1.1.52', '1.1.1.392;1.1.1.50;1.1.1.52', '1.1.1.392', '1.1.1.392', '1.1.1.393', '1.1.1.393', '1.1.1.393', '1.1.1.393', '1.1.1', '1.1.1', '1.1.1', '1.1.1.1', '1.1.1.159', '1.1.1.159', '1.1.1.218', '1.1.1.218', '3.1.6.14', '3.1.6.14', '3.1.6.14', '1.1.1.218', '1.1.1.218', '3.1.3.29', '3.1.3.29', '3.1.3.29', '1.14.15.15', '1.1.1.149', '1.1.1.149', '3.1.3.33;3.1.3.5', '3.1.3.33;3.1.3.5', '3.1.3.33;3.1.3.5', '1.1.1.133', '1.1.1.133', '1.1.1.239', '1.1.1.239', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.50', '1.1.1.405', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.1.1.292', '1.1.1.292', '1.1.3.9', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.1.1', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.2.1.78', '3.2.1.78', '3.2.1.78', '3.2.1.78', '3.2.1.78', '3.2.1.78', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '1.1.1.146;1.1.1.159;1.1.1.50', '1.1.1.146;1.1.1.159;1.1.1.50', '3.1.6.3', '3.1.6.3', '3.1.6.3', '1.1.99.13', '1.1.99.13', '3.1.3.68', '3.1.3.68', '3.1.3.68', '1.1.1.-', '1.1.1.-', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.133', '1.1.1.133', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '3.8.1.8', '3.8.1.8', '3.2.1.154;3.2.1.26;3.2.1.80', '3.2.1.154;3.2.1.26;3.2.1.80', '3.2.1.154;3.2.1.26;3.2.1.80', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.4;3.2.1.91', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '3.2.1.21;3.2.1.3', '3.2.1.21;3.2.1.3', '1.1.1.-', '1.1.1.-', '3.2.1.65', '3.2.1.65', '3.2.1.65', '3.2.1.145;3.2.1.23', '3.2.1.145;3.2.1.23', '3.2.1.145;3.2.1.23', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '3.1.3.91', '3.1.3.91', '3.1.3.91', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.2.1.137;3.2.1.78', '3.2.1.137;3.2.1.78', '3.2.1.137;3.2.1.78', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '3.1.3.29', '3.1.3.29', '1.1.1.405', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.-;1.1.1.146', '1.1.1.-;1.1.1.146', '1.1.1;1.1.1.-;1.1.1.146;1.1.1.51', '1.1.1;1.1.1.-;1.1.1.146;1.1.1.51', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '3.1.3.23;3.1.3.29;3.1.3.9', '3.1.3.23;3.1.3.29;3.1.3.9', '3.1.3.23;3.1.3.29;3.1.3.9', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.27', '3.1.3.27', '3.1.3.27', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3', '3.1.3', '3.1.3.24', '3.1.3.24', '3.1.3.24', '1.1.1.133', '1.1.1.133', '3.1.3.12', '3.1.3.12', '3.1.3.12', '1.1.1.-', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '1.1.1.271', '1.1.1.271', '1.1.1.136', '1.1.1.132', '1.1.3.9', '3.1.3.29', '3.1.3.29', '3.1.3.29', '1.1.1;1.1.1.148;1.1.1.209', '1.1.1;1.1.1.148;1.1.1.209', '3.1.3.-', '3.1.3.-', '3.1.3.-', '1.1.1.134;1.1.1.344', '1.1.1.134;1.1.1.344', '1.1.1.159;1.1.1.50', '1.1.1.159;1.1.1.50', '1.1.1.176', '1.1.1.176', '1.1.1.206', '1.1.1.206', '1.1.1.236', '1.1.1.236', '1.1.1.23', '1.1.1.135;1.1.1.187', '1.1.1.135;1.1.1.187', '1.1.1.187;1.1.1.281', '1.1.1.187;1.1.1.281', '1.1.1.135;1.1.1.187', '1.1.1.135;1.1.1.187', '1.1.1.187;1.1.1.281', '1.1.1.187;1.1.1.281', '1.1.1.238', '1.1.1.238', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.1.1.186', '1.1.1.146', '1.1.1.146', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.1.1.50', '1.1.1.50', '1.1.1.209;1.1.1.50', '1.1.1.209;1.1.1.50', '2.-.-.-', '2.-.-.-', '2.-.-.-', '2.-.-.-', '1.1.1.266', '1.1.1.266', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.72', '3.1.3.70', '3.1.3.70', '3.1.3.70', '1.1.1.273', '1.1.1.273', '1.1.1.273', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.1.1.186', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.68', '3.1.3.68', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.1.1.317', '1.1.1.317', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.1.1;1.1.1.-', '1.1.1;1.1.1.-', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '1.1.1.159', '1.1.1.159', '1.1.1.-', '1.1.1.-', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.1.1.1;1.1.1.161', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '3.2.1.22;3.2.1.23', '3.2.1.22;3.2.1.23', '1.1.1.153', '3.1.3.45', '3.1.3.45', '3.1.3.45', '1.1.1.-;1.1.1.336', '1.1.1.22', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.1.1.-;1.1.1.M53', '1.1.1.-;1.1.1.M53', '3.1.3.68', '3.1.3.68', '3.1.3.68', '1.14.13.246', '1.1.1.201', '1.1.1.201', '1.1.1.425', '1.1.1.425', '3.1.3.M8', '3.1.3.M8', '3.1.3.M8', '1.1.1', '1.1.1', '1.1.1.273', '1.1.1.266', '1.1.1.266', '3.1.3.106;3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.106;3.1.3.76', '1.1.1.367', '1.1.1.367', '3.1.3.106;3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.106', '3.1.3.106', '3.1.3.76', '3.1.3.76', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '3.1.3.105', '3.1.3.105', '1.14.13', '1.1.1', '1.1.1', '1.1.3.10', '1.1.3.10', '1.1.3.10', '1.1.3.10', '3.1.3.58;3.1.3.9', '3.1.3.58;3.1.3.9', '3.1.3.58;3.1.3.9', '3.1.6.3', '3.1.6.3', '3.1.6.3', '1.1.3.9', '1.1.3.9', '3.2.1.55', '3.2.1.55', '3.2.1.55', '3.2.1.55', '3.2.1.55', '3.2.1.55', '3.2.1.3;3.2.1.58;3.2.1.59', '3.2.1.3;3.2.1.58;3.2.1.59', '3.2.1.3;3.2.1.58;3.2.1.59', '3.1.3.29', '3.1.3.29', '3.1.3.29', '3.2.1.4', '3.2.1.4', '3.2.1.4', '3.2.1.4', '3.2.1.4', '3.2.1.4', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '3.2.1.116', '3.2.1.116', '3.2.1.116', '3.2.1.60', '3.2.1.60', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.2.1.1', '3.2.1.1', '3.2.1.1', '1.1.1.-', '1.1.1.-', '1.7.3.-', '1.7.3.-', '1.7.3.-', '1.7.3.-', '1.7.3.-', '1.7.3.-', '1.7.3.-', '1.7.3.-', '1.7.3.-', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.-', '1.1.1.-', '3.2.1.2', '3.2.1.2', '3.2.1.2', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.174', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '3.2.1.153;3.2.1.26;3.2.1.80', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.15.5', '1.14.15.5', '1.14.15.5', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '3.2.1.137', '3.2.1.137', '3.2.1.137', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.1.1.-', '1.1.1.-', '3.1.3.27', '3.1.3.27', '3.1.3.27', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.184', '1.14.13.184', '1.14.13.194', '3.1.3', '3.1.3', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.2.1.143', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3', '3.1.3', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.1.1.M51', '1.1.1.M51', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.1.1.M51', '1.1.1.M51', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.106', '3.1.3.106', '3.1.3.106', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3', '3.1.3', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.2;3.1.3.5', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.5.1', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.1.3;3.1.3.-;3.1.3.4', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '3.2.1.23', '3.2.1.23', '1.1.1.1;1.1.1.161', '1.14.13.32', '1.14.13.15;1.14.15.15', '1.14.13.72', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7;3.1.3.97', '3.1.3.7;3.1.3.97', '3.1.3.7', '3.1.3.7', '3.1.3.7', '3.1.3.82', '3.1.3.82', '3.1.3.82', '1.1.1;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.51;1.1.1.62', '1.1.1.271', '1.1.1.271', '1.1.1.271', '1.1.1.271', '1.1.99.13', '1.1.99.13', '3.1.3.58;3.1.3.9', '3.1.3.58;3.1.3.9', '3.1.3.58;3.1.3.9', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3.-', '3.1.3.-', '3.1.3', '3.1.3', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '3.1.3.-;3.1.3.102;3.1.3.2', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '1.1.1.367', '1.1.1.367', '1.1.1.-', '1.1.1.-', '1.1.1.395', '1.1.1.395', '1.1.1', '1.1.1', '1.1.1.146', '1.1.1.146', '1.1.1.239', '1.1.1.239', '1.1.1.238', '1.1.1.238', '1.1.1.206', '1.1.1.206', '3.1.3.76', '3.1.3.76', '3.1.3.76', '3.1.3.76', '3.1.3.76', '3.1.3.76', '1.1.1.102', '1.1.1.102', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '1.1.1.1;1.1.1.190', '3.1.3.-;3.1.3.104', '3.1.3.-;3.1.3.104', '3.1.3.-;3.1.3.104']
26
240
Timapiprant
9

100%|██████████| 11047/11047 [00:07<00:00, 1555.85it/s]
100%|██████████| 27873/27873 [00:11<00:00, 2413.38it/s]
 87%|████████▋ | 110/126 [41:18<06:02, 22.68s/it]

rxndb num 940
failedrxn num 0
result_df 73
['3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.2.1.5', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.74', '3.1.3.74', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.73', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3.39', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.99.2', '1.14.99.2', '1.14.12.16', '1.14.13.61', '1.14.13.61', '1.14.13.61', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.1.3.-;3.1.3.88', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3', '3.1.3.-', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.12.16', '1.1.1.-', '1.2.3.1', '3.1.3.33;3.1.3.5', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.4.11.5', '3.1.3.91', '3.6.1;3.6.1.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '3.1.3.73', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.1.3.M8', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13.176', '1.14.13.176', '1.14.13.176', '1.14.13.176', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '2.6.1.114', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '1.2.1', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '3.1.3.-;3.1.3.104']
20
73
Tolterodine (tartrate)
5

100%|██████████| 11047/11047 [00:03<00:00, 2890.40it/s]
100%|██████████| 27873/27873 [00:10<00:00, 2707.51it/s]
 88%|████████▊ | 111/126 [41:36<05:17, 21.18s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Tolvaptan
9

100%|██████████| 11047/11047 [00:07<00:00, 1523.73it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2133.90it/s]
 89%|████████▉ | 112/126 [42:00<05:08, 22.07s/it]

rxndb num 1914
failedrxn num 0
result_df 150
['3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.74', '3.1.3.74', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.73', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3.39', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.219', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '3.1.6.9', '3.1.6.10', '1.1.1.219', '1.1.1.234', '3.8.1.7', '1.1.1.234', '1.17.1.3', '1.17.1.3', '1.1.1.234', '1.17.1.3', '1.1.1.362', '1.14.13.180', '1.14.13.180', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.219', '1.1.1.219', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.-;3.1.3.88', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.1.1.349', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3', '3.1.3.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.1.1.362', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.19', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.348', '1.1.1.348', '3.1.6.14', '3.1.3.29', '3.1.3.33;3.1.3.5', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.1.1.184;1.1.1.209;1.1.1.213;1.1.1.50', '1.1.1.184', '3.1.3', '3.1.3', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.13.-', '1.1.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.4.11.5', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '3.1.3.91', '3.6.1;3.6.1.-', '1.1.1.246;1.1.1.348', '1.1.1.219', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.29', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.3.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.140', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '1.1.1.219', '3.1.3', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.M8', '3.1.3.105', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.1.1.50', '3.2.1.14', '3.2.1.14', '3.1.3.29', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '3.4.15.6', '3.4.15.6', '3.4.19.7', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.3.98.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.-.-', '1.-.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.140', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.1.1.112;1.1.1.184', '1.1.1.112;1.1.1.184;1.1.1.51', '1.1.1;1.1.1.112;1.1.1.184;1.1.1.213;1.1.1.50', '1.1.1.112;1.1.1.184;1.1.1.213;1.1.1.50;1.1.1.62;1.3.1.20', '1.14.19.58', '1.3.1', '1.3.1.-', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '2.6.1.114', '2.6.1.114', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '3.1.3.76', '3.1.3.-;3.1.3.104']
32
131
Tozadenant
9

100%|██████████| 11047/11047 [00:07<00:00, 1538.17it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2230.01it/s]
 90%|████████▉ | 113/126 [42:24<04:54, 22.69s/it]

rxndb num 1727
failedrxn num 0
result_df 38
['3.1.3.15', '3.1.3.74', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.15.6', '3.1.3.-', '3.1.3.74', '3.1.3.27', '3.1.3.74', '1.14.14.1', '1.14.14.1', '3.1.3.73', '3.1.6.2', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '3.1.3.39', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.6.9', '3.1.6.10', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.1.3.-;3.1.3.88', '3.1.3.79', '1.14.-.-', '3.1.3.92', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '3.1.3', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '3.1.6.14', '3.1.3.29', '1.14.15.15', '3.1.3.33;3.1.3.5', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '1.14.14.55', '1.14.14.55', '3.1.3', '3.1.3', '3.1.3.68', '1.14.15.4', '1.14.15.4', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '3.1.3.91', '3.6.1;3.6.1.-', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '2.4.1.-', '1.14.-.-', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.1.3.27', '1.14.13.30', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.24', '3.1.3.29', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.3.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.140', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.-.-', '1.14.-.-', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.1.3', '1.14.14.149', '1.14.14.149', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.14.13.88', '1.14.13.88', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.3.M8', '3.1.3.105', '3.2.1.14', '3.1.3.29', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '3.2.1.87', '3.2.1.87', '3.4.15.6', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.15.5', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '3.1.3.27', '1.14.13.140', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.176', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '3.1.3', '3.1.3.73', '3.2.1.143', '3.2.1.143', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '1.14.13.98', '1.14.13.98', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.1.3.76', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75']
22
121
Trimebutine (maleate)
5

100%|██████████| 11047/11047 [00:04<00:00, 2519.28it/s]
100%|██████████| 27873/27873 [00:10<00:00, 2558.65it/s]
 90%|█████████ | 114/126 [42:44<04:20, 21.67s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Trimethobenzamide hydrochloride
9

100%|██████████| 11047/11047 [00:06<00:00, 1680.82it/s]
100%|██████████| 27873/27873 [00:11<00:00, 2346.61it/s]
 91%|█████████▏| 115/126 [43:06<04:01, 21.93s/it]

rxndb num 2937
failedrxn num 0
result_df 49
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.5.1.40', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.180', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '1.14.13.8', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '3.3.2.14', '3.3.2.14', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.8', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.-', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.35', '1.14.14.91', '1.14.14.91', '1.14.14.91', '2.4.1.-', '2.4.1.-', '2.4.1.-', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.4.15.6', '3.4.19.7', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.2.1.3', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '3.1.1.101', '3.2.1.143', '3.2.1.143', '3.2.1.143', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.11.2.6', '1.11.2.6', '1.11.2.6']
26
68
Trospium (chloride)
5

100%|██████████| 11047/11047 [00:03<00:00, 2897.30it/s]
100%|██████████| 27873/27873 [00:11<00:00, 2390.08it/s]
 92%|█████████▏| 116/126 [43:25<03:31, 21.11s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Umeclidinium (bromide)
5

100%|██████████| 11047/11047 [00:03<00:00, 2779.83it/s]
100%|██████████| 27873/27873 [00:11<00:00, 2401.82it/s]
 93%|█████████▎| 117/126 [43:45<03:05, 20.60s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Valsartan
9

100%|██████████| 11047/11047 [00:07<00:00, 1535.87it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2298.91it/s]
 94%|█████████▎| 118/126 [44:07<02:49, 21.16s/it]

rxndb num 1173
failedrxn num 0
result_df 74
['3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.2.1.5', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.74', '3.1.3.27', '3.1.3.74', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '3.1.3.39', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.17.1.1', '1.17.1.1', '3.1.6.9', '3.1.6.10', '1.3.1.5', '1.3.1.5', '1.3.1.48', '1.3.1.48', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.2.1.5', '1.2.1.5', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.-;3.1.3.88', '1.14.-.-', '1.14.-.-', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3', '1.3.3.6', '3.1.3.-', '1.3.1.93', '1.3.1.93', '1.3.1', '1.3.1.93', '1.3.1.93', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.3.1.93', '1.3.1.93', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '1.3.1', '1.1.1.-', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.3.3.6', '1.3.1.48', '1.3.1.48', '1.3.1.48', '3.1.6.14', '3.1.3.29', '1.14.15.15', '1.14.15.15', '3.1.3.33;3.1.3.5', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '3.4.13.9', '3.4.13.9', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.8.1.8', '3.4.11.5', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.35', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '3.1.3.91', '3.6.1;3.6.1.-', '1.14.-.-', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.13.15;1.14.15.15', '1.14.13.15;1.14.15.15', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.1.3.27', '1.14.13.30', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.29', '3.1.3.-', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.3.1.104;1.3.1.38;1.3.1.8', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.3.1.104;1.3.1.38;1.3.1.44;1.3.1.8', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '1.1.1;1.3.1.44', '3.1.3', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.3.99.-', '1.3.99.3', '1.1.1;1.3.99.3', '1.3.1.9', '1.14.13.246', '3.1.3.M8', '3.1.3.105', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.1.3.29', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.4.15.6', '3.4.15.6', '3.4.19.7', '3.4.19.7', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.-', '3.2.1.-', '1.14.13.-;1.14.13.188', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.174', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.15.5', '1.14.15.5', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '3.1.3.27', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.194', '1.14.13.194', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.3.3.6', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '1.3.1.93', '1.3.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '1.3.1.104;1.3.1.38;1.3.1.8', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.3.99.-', '1.3.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.3.3.6;1.3.8.1;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.3.3.6', '1.3.3.6', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.3.1.10;1.3.1.38;1.3.1.8', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '1.2.1', '1.1.1;1.1.1.206', '3.1.3.76', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75']
31
121
Velneperit
9

100%|██████████| 11047/11047 [00:06<00:00, 1667.52it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2273.63it/s]
 94%|█████████▍| 119/126 [44:29<02:29, 21.37s/it]

rxndb num 98
failedrxn num 0
result_df 18
['1.14.13.58', '1.14.13.58', '3.4.22.40;3.5.1.72', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '6.3.1.18', '1.14.13.209', '1.14.13.209', '3.5.1.123', '3.5.1', '1.2.3.1', '3.4.11.3;3.4.11.6;3.4.22.40', '2.3.2.2;3.4.11.10;3.4.19.3', '3.4.21.4;3.4.22;3.4.22.1', '3.3.2.6;3.4.11.10;3.4.11.15', '1.3;1.3.1.120', '1.14.13', '1.14.13', '1.14.14.55', '3.8.1.7', '3.2.1.35', '3.2.1.35', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.3.1.120', '3.4.15.6', '3.4.15.6', '1.14.13.176', '1.14.13.182', '1.14.13.182']
15
33
Vicriviroc (maleate)
5

100%|██████████| 11047/11047 [00:03<00:00, 2968.51it/s]
100%|██████████| 27873/27873 [00:11<00:00, 2491.84it/s]
 95%|█████████▌| 120/126 [44:47<02:02, 20.37s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Vilazodone (Hydrochloride)
5

100%|██████████| 11047/11047 [00:03<00:00, 2919.96it/s]
100%|██████████| 27873/27873 [00:11<00:00, 2505.30it/s]
 96%|█████████▌| 121/126 [45:06<01:40, 20.01s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Volinanserin
9

100%|██████████| 11047/11047 [00:08<00:00, 1275.20it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2201.53it/s]
 97%|█████████▋| 122/126 [45:31<01:25, 21.44s/it]

rxndb num 3668
failedrxn num 0
result_df 69
['3.1.3.69', '3.1.3.74', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.74', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.73', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '3.1.3.39', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.219', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '3.1.6.9', '3.1.6.10', '1.1.1.219', '1.14.13.19', '1.14.13.19', '1.1.1.234', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.-.-', '1.14.-.-', '1.1.1.234', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.69', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.1.1.234', '1.17.1.3', '1.17.1.3', '1.1.1.362', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '1.1.1.219', '1.1.1.219', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.-;3.1.3.88', '3.1.3.79', '3.1.3.85', '3.1.3.83', '1.1.1.349', '1.14.13.-', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '3.3.2.14', '3.3.2.14', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '3.1.3', '1.14.13', '1.14.13', '3.1.3.-', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '1.3.1', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.1.1.362', '1.14.13', '1.14.13', '3.1.3.4', '3.1.3.4', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.348', '1.1.1.348', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.6.14', '3.1.3.29', '3.1.3.33;3.1.3.5', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3', '3.1.3', '1.14.14.55', '1.14.14.55', '3.2.1.78', '3.1.3', '3.1.3', '3.1.6.3', '3.1.3.68', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.1.1.-', '3.2.1.154;3.2.1.26;3.2.1.80', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.55', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '3.2.1.65', '3.2.1.145;3.2.1.23', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '3.1.3.91', '3.6.1;3.6.1.-', '1.1.1.246;1.1.1.348', '1.1.1.219', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '3.2.1.137;3.2.1.78', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '2.4.1.-', '2.4.1.-', '1.14.-.-', '1.14.-.-', '3.1.3.23;3.1.3.29;3.1.3.9', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.24', '3.1.3.12', '3.1.3.29', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.3.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '2.-.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.-', '1.14.13.-', '3.1.3.73', '1.1.1.219', '3.1.3', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.45', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.68', '3.1.3.M8', '3.1.3.105', '1.1.1.50', '3.1.3.58;3.1.3.9', '3.1.6.3', '3.2.1.37', '3.2.1.37', '3.2.1.3;3.2.1.58;3.2.1.59', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.2.1.87', '3.2.1.1', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.2', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '3.2.1.137', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13', '1.14.13', '3.1.3', '3.1.3.73', '3.2.1.143', '3.2.1.143', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.2.1.23', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '3.1.3.82', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.3.1', '1.3.1.-', '3.1.3.58;3.1.3.9', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.76', '3.1.3.76', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75']
31
174
Vortioxetine (hydrobromide)
5

100%|██████████| 11047/11047 [00:06<00:00, 1586.55it/s]
100%|██████████| 27873/27873 [00:10<00:00, 2635.10it/s]
 98%|█████████▊| 123/126 [45:52<01:03, 21.19s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Xanomeline (oxalate)
5

100%|██████████| 11047/11047 [00:03<00:00, 2930.79it/s]
100%|██████████| 27873/27873 [00:11<00:00, 2412.75it/s]
 98%|█████████▊| 124/126 [46:11<00:41, 20.51s/it]

rxndb num 0
failedrxn num 0
result_df 0
[]
0
0
Zafirlukast
9

100%|██████████| 11047/11047 [00:07<00:00, 1531.67it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2107.08it/s]
 99%|█████████▉| 125/126 [46:35<00:21, 21.66s/it]

rxndb num 2089
failedrxn num 0
result_df 65
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.180', '1.14.13.180', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.13.12.20', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '3.3.2.14', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13.224', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.13.-', '1.14.13.-', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.18', '1.14.-.-', '1.14.-.-', '3.2.1.35', '3.2.1.35', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.140', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.14', '3.2.1.14', '3.2.1.14', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.-', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.140', '1.14.13.176', '1.14.13.176', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '3.2.1.143', '3.2.1.143', '1.14.13.182', '1.14.13.182', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '2.6.1.114', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.13.11.11;1.13.11.52']
19
60
Zuclopenthixol
9

100%|██████████| 11047/11047 [00:07<00:00, 1515.06it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2280.89it/s]
100%|██████████| 126/126 [46:58<00:00, 22.37s/it]

rxndb num 557
failedrxn num 0
result_df 42
['1.1.1.23', '3.1.3.15', '3.1.3.74', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.1.1.1', '3.1.3.73', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.1.3.23', '1.1.3.17', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.1.1.191;1.1.1.2;1.1.1.21', '1.1.1.150', '1.1.1.151', '3.8.1.7', '4.99.1.-', '4.3.3.-', '1.14.13.72', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1;1.1.1.-;1.1.1.1', '3.1.3.-;3.1.3.88', '1.14.13.-', '1.14.13.-', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '3.1.3.-', '3.1.3', '1.1.1;1.1.1.-', '1.14.13;1.14.13.-', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.1.1', '1.14.13', '1.14.13', '1.1.1', '1.1.1.1', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.14.145', '1.14.14.145', '1.14.14.145', '3.1.3.33;3.1.3.5', '3.1.3', '3.1.3', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.13.109', '3.1.3.91', '3.6.1;3.6.1.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.13.30', '1.1.1.23', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.72', '1.1.1.273', '1.1.1.273', '1.1.1.273', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.78', '1.14.14.145', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.1.1.317', '1.1.1.317', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.1.99.1', '1.1.1', '3.1.3.M8', '1.1.1.273', '1.14.13.-', '1.14.13.144', '1.3.98.-', '1.14.13.-', '1.1.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.15.5', '1.14.15.5', '1.1.1.1', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.1.1.71', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.194', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '1.14.13.100;1.14.13.17;1.14.13.60', '1.14.13.72', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '1.14.19.58', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '1.1.1.1;1.1.1.190', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '1.1.1;1.1.1.1', '3.1.3.1;3.1.3.75']
15
77

In [13]:
rxndb

{'rxn1': {'EC number': '1.1.1.23',
  'rule': '[C:1]-[CH2;D2;+0:2]-[OH;D1;+0:4].[OH2;D0;+0:3]>>[C:1]-[C;H0;D3;+0:2](-[O-;H0;D1:3])=[O;H0;D1;+0:4]',
  'templateID': 'MNXR100587',
  'templateSubstrate': ['[NH3+][C@H](CO)Cc1c[nH]cn1', '[H]O[H]'],
  'rxn_smiles_basic': 'O=C([O-])CN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.[H]O[H]',
  'rxn_smiles_final': 'O=C([O-])CN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](O)[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1.NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](O)[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1.[H+].[H+].[H+]>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.[H]O[H].NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](O)[C@@H]3O)[C@@H](O)[C@H]2O)c1.NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](O)[C@@H]3O)[C@@H](O)[C@H]2O)c1',
  'reactant_smile': 'O=C([O-])CN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1',
  'productsmile': 'OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.[H]O[H]',
  'similarity': (0.4117647058823529, 0.4117647058823529, 1)},
 'rxn2': {'EC number': '3.1.3.15',
  'rule': '[C:1]-[OH;D1;+0:2].[O;-;D1;H0:4]-[P;H0;D4;+0:3](-[O;-;D1;H0:5])(=[O;D1;H0:6])-[OH;D1;+0:7]>>[C:1]-[O;H0;D2;+0:2]-[P;H0;D4;+0:3](-[O;-;D1;H0:4])(-[O;-;D1;H0:5])=[O;D1;H0:6].[OH2;D0;+0:7]',
  'templateID': 'MNXR100642_reverse',
  'templateSubstrate': ['[NH3+][C@H](CO)Cc1c[nH]cn1', 'O=P([O-])([O-])O'],
  'rxn_smiles_basic': 'O.O=P([O-])([O-])OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=P([O-])([O-])O',
  'rxn_smiles_final': 'O.O=P([O-])([O-])OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=P([O-])([O-])O',
  'reactant_smile': 'O.O=P([O-])([O-])OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1',
  'productsmile': 'OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=P([O-])([O-])O',
  'similarity': (0.4117647058823529, 0.4117647058823529, 1)},
 'rxn3': {'EC number': '3.1.3.74',
  'rule': '[C:1]-[OH;D1;+0:2].[O-;H0;D1:7]-[P;H0;D4;+0:3](-[O;-;D1;H0:5])(=[O;D1;H0:6])-[OH;D1;+0:4]>>[C:1]-[O;H0;D2;+0:2]-[P;H0;D4;+0:3](-[O-;H0;D1:4])(-[O;-;D1;H0:5])=[O;D1;H0:6].[OH2;D0;+0:7]',
  'templateID': 'MNXR100763',
  'templateSubstrate': ['Cc1ncc(CO)c(C[NH3+])c1O', 'O=P([O-])([O-])O'],
  'rxn_smiles_basic': 'O.O=P([O-])([O-])OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=P([O-])([O-])O',
  'rxn_smiles_final': 'O.O=P([O-])([O-])OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=P([O-])([O-])O',
  'reactant_smile': 'O.O=P([O-])([O-])OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1',
  'productsmile': 'OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=P([O-])([O-])O',
  'similarity': (0.3974358974358974, 0.3974358974358974, 1)},
 'rxn4': {'EC number': '1.14.13.-;1.14.14.-;1.14.14.1',
  'rule': '[O;H0;D1;+0:1]=[O;H0;D1;+0:2].[c:4]:[cH;D2;+0:3]:[c:5]>>[OH2;D0;+0:1].[OH;D1;+0:2]-[c;H0;D3;+0:3](:[c:4]):[c:5]',
  'templateID': 'MNXR101068_reverse',
  'templateSubstrate': ['O=O', 'CCN(CC)CC(=O)Nc1c(C)cccc1C'],
  'rxn_smiles_basic': 'O.OCCN1CCN(CCC=C2c3cc(Cl)ccc3Sc3c(O)cccc32)CC1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O',
  'rxn_smiles_final': 'O.OCCN1CCN(CCC=C2c3cc(Cl)ccc3Sc3c(O)cccc32)CC1.NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)c1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O.[H+].NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1',
  'reactant_smile': 'O.OCCN1CCN(CCC=C2c3cc(Cl)ccc3Sc3c(O)cccc32)CC1',
  'productsmile': 'OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O',
  'similarity': (0.4027777777777778, 1, 0.40789473684210525)},
 'rxn5': {'EC number': '1.14.13.-;1.14.14.-;1.14.14.1',
  'rule': '[O;H0;D1;+0:1]=[O;H0;D1;+0:2].[c:4]:[cH;D2;+0:3]:[c:5]>>[OH2;D0;+0:1].[OH;D1;+0:2]-[c;H0;D3;+0:3](:[c:4]):[c:5]',
  'templateID': 'MNXR101068_reverse',
  'templateSubstrate': ['O=O', 'CCN(CC)CC(=O)Nc1c(C)cccc1C'],
  'rxn_smiles_basic': 'O.OCCN1CCN(CCC=C2c3ccccc3Sc3cc(O)c(Cl)cc32)CC1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O',
  'rxn_smiles_final': 'O.OCCN1CCN(CCC=C2c3ccccc3Sc3cc(O)c(Cl)cc32)CC1.NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)c1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O.[H+].NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1',
  'reactant_smile': 'O.OCCN1CCN(CCC=C2c3ccccc3Sc3cc(O)c(Cl)cc32)CC1',
  'productsmile': 'OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O',
  'similarity': (0.4027777777777778, 1, 0.40789473684210525)},
 'rxn6': {'EC number': '1.14.13.-;1.14.14.-;1.14.14.1',
  'rule': '[O;H0;D1;+0:1]=[O;H0;D1;+0:2].[c:4]:[cH;D2;+0:3]:[c:5]>>[OH2;D0;+0:1].[OH;D1;+0:2]-[c;H0;D3;+0:3](:[c:4]):[c:5]',
  'templateID': 'MNXR101068_reverse',
  'templateSubstrate': ['O=O', 'CCN(CC)CC(=O)Nc1c(C)cccc1C'],
  'rxn_smiles_basic': 'O.OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)c(O)c32)CC1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O',
  'rxn_smiles_final': 'O.OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)c(O)c32)CC1.NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)c1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O.[H+].NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1',
  'reactant_smile': 'O.OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)c(O)c32)CC1',
  'productsmile': 'OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O',
  'similarity': (0.4027777777777778, 1, 0.40789473684210525)},
 'rxn7': {'EC number': '1.14.13.-;1.14.14.-;1.14.14.1',
  'rule': '[O;H0;D1;+0:1]=[O;H0;D1;+0:2].[c:4]:[cH;D2;+0:3]:[c:5]>>[OH2;D0;+0:1].[OH;D1;+0:2]-[c;H0;D3;+0:3](:[c:4]):[c:5]',
  'templateID': 'MNXR101068_reverse',
  'templateSubstrate': ['O=O', 'CCN(CC)CC(=O)Nc1c(C)cccc1C'],
  'rxn_smiles_basic': 'O.OCCN1CCN(CCC=C2c3ccc(O)cc3Sc3ccc(Cl)cc32)CC1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O',
  'rxn_smiles_final': 'O.OCCN1CCN(CCC=C2c3ccc(O)cc3Sc3ccc(Cl)cc32)CC1.NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)c1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O.[H+].NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1',
  'reactant_smile': 'O.OCCN1CCN(CCC=C2c3ccc(O)cc3Sc3ccc(Cl)cc32)CC1',
  'productsmile': 'OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O',
  'similarity': (0.4027777777777778, 1, 0.40789473684210525)},
 'rxn8': {'EC number': '1.14.13.-;1.14.14.-;1.14.14.1',
  'rule': '[O;H0;D1;+0:1]=[O;H0;D1;+0:2].[c:4]:[cH;D2;+0:3]:[c:5]>>[OH2;D0;+0:1].[OH;D1;+0:2]-[c;H0;D3;+0:3](:[c:4]):[c:5]',
  'templateID': 'MNXR101068_reverse',
  'templateSubstrate': ['O=O', 'CCN(CC)CC(=O)Nc1c(C)cccc1C'],
  'rxn_smiles_basic': 'O.OCCN1CCN(CCC=C2c3cc(Cl)ccc3Sc3cccc(O)c32)CC1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O',
  'rxn_smiles_final': 'O.OCCN1CCN(CCC=C2c3cc(Cl)ccc3Sc3cccc(O)c32)CC1.NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)c1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O.[H+].NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1',
  'reactant_smile': 'O.OCCN1CCN(CCC=C2c3cc(Cl)ccc3Sc3cccc(O)c32)CC1',
  'productsmile': 'OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O',
  'similarity': (0.4027777777777778, 1, 0.40789473684210525)},
 'rxn9': {'EC number': '1.14.13.-;1.14.14.-;1.14.14.1',
  'rule': '[O;H0;D1;+0:1]=[O;H0;D1;+0:2].[c:4]:[cH;D2;+0:3]:[c:5]>>[OH2;D0;+0:1].[OH;D1;+0:2]-[c;H0;D3;+0:3](:[c:4]):[c:5]',
  'templateID': 'MNXR101068_reverse',
  'templateSubstrate': ['O=O', 'CCN(CC)CC(=O)Nc1c(C)cccc1C'],
  'rxn_smiles_basic': 'O.OCCN1CCN(CCC=C2c3cc(O)ccc3Sc3ccc(Cl)cc32)CC1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O',
  'rxn_smiles_final': 'O.OCCN1CCN(CCC=C2c3cc(O)ccc3Sc3ccc(Cl)cc32)CC1.NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)c1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O.[H+].NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1',
  'reactant_smile': 'O.OCCN1CCN(CCC=C2c3cc(O)ccc3Sc3ccc(Cl)cc32)CC1',
  'productsmile': 'OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O',
  'similarity': (0.4027777777777778, 1, 0.40789473684210525)},
 'rxn10': {'EC number': '1.14.13.-;1.14.14.-;1.14.14.1',
  'rule': '[O;H0;D1;+0:1]=[O;H0;D1;+0:2].[c:4]:[cH;D2;+0:3]:[c:5]>>[OH2;D0;+0:1].[OH;D1;+0:2]-[c;H0;D3;+0:3](:[c:4]):[c:5]',
  'templateID': 'MNXR101068_reverse',
  'templateSubstrate': ['O=O', 'CCN(CC)CC(=O)Nc1c(C)cccc1C'],
  'rxn_smiles_basic': 'O.OCCN1CCN(CCC=C2c3ccccc3Sc3c(O)cc(Cl)cc32)CC1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O',
  'rxn_smiles_final': 'O.OCCN1CCN(CCC=C2c3ccccc3Sc3c(O)cc(Cl)cc32)CC1.NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)c1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O.[H+].NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1',
  'reactant_smile': 'O.OCCN1CCN(CCC=C2c3ccccc3Sc3c(O)cc(Cl)cc32)CC1',
  'productsmile': 'OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O',
  'similarity': (0.4027777777777778, 1, 0.40789473684210525)},
 'rxn11': {'EC number': '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89',
  'rule': '[C:1]-[OH;D1;+0:2].[O-;H0;D1:7]-[P;H0;D4;+0:3](-[O;-;D1;H0:5])(=[O;D1;H0:6])-[OH;D1;+0:4]>>[C:1]-[O;H0;D2;+0:2]-[P;H0;D4;+0:3](-[O-;H0;D1:4])(-[O;-;D1;H0:5])=[O;D1;H0:6].[OH2;D0;+0:7]',
  'templateID': 'MNXR102028',
  'templateSubstrate': ['O=c1ccn([C@H]2C[C@H](O)[C@@H](CO)O2)c(=O)[nH]1',
   'O=P([O-])([O-])O'],
  'rxn_smiles_basic': 'O.O=P([O-])([O-])OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=P([O-])([O-])O',
  'rxn_smiles_final': 'O.O=P([O-])([O-])OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=P([O-])([O-])O',
  'reactant_smile': 'O.O=P([O-])([O-])OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1',
  'productsmile': 'OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=P([O-])([O-])O',
  'similarity': (0.6756756756756757, 0.6756756756756757, 1)},
 'rxn12': {'EC number': '3.1.3.31;3.1.3.5',
  'rule': '[C:1]-[OH;D1;+0:2].[O-;H0;D1:7]-[P;H0;D4;+0:3](-[O;-;D1;H0:5])(=[O;D1;H0:6])-[OH;D1;+0:4]>>[C:1]-[O;H0;D2;+0:2]-[P;H0;D4;+0:3](-[O-;H0;D1:4])(-[O;-;D1;H0:5])=[O;D1;H0:6].[OH2;D0;+0:7]',
  'templateID': 'MNXR102031',
  'templateSubstrate': ['O=c1[nH]cnc2c1ncn2[C@H]1C[C@H](O)[C@@H](CO)O1',
   'O=P([O-])([O-])O'],
  'rxn_smiles_basic': 'O.O=P([O-])([O-])OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=P([O-])([O-])O',
  'rxn_smiles_final': 'O.O=P([O-])([O-])OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=P([O-])([O-])O',
  'reactant_smile': 'O.O=P([O-])([O-])OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1',
  'productsmile': 'OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=P([O-])([O-])O',
  'similarity': (0.8, 0.8, 1)},
 'rxn13': {'EC number': '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89',
  'rule': '[C:1]-[OH;D1;+0:2].[O-;H0;D1:7]-[P;H0;D4;+0:3](-[O;-;D1;H0:5])(=[O;D1;H0:6])-[OH;D1;+0:4]>>[C:1]-[O;H0;D2;+0:2]-[P;H0;D4;+0:3](-[O-;H0;D1:4])(-[O;-;D1;H0:5])=[O;D1;H0:6].[OH2;D0;+0:7]',
  'templateID': 'MNXR102033',
  'templateSubstrate': ['Nc1ccn([C@H]2C[C@H](O)[C@@H](CO)O2)c(=O)n1',
   'O=P([O-])([O-])O'],
  'rxn_smiles_basic': 'O.O=P([O-])([O-])OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=P([O-])([O-])O',
  'rxn_smiles_final': 'O.O=P([O-])([O-])OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=P([O-])([O-])O',
  'reactant_smile': 'O.O=P([O-])([O-])OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1',
  'productsmile': 'OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=P([O-])([O-])O',
  'similarity': (0.726027397260274, 0.726027397260274, 1)},
 'rxn14': {'EC number': '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89',
  'rule': '[C:1]-[OH;D1;+0:2].[O-;H0;D1:7]-[P;H0;D4;+0:3](-[O;-;D1;H0:5])(=[O;D1;H0:6])-[OH;D1;+0:4]>>[C:1]-[O;H0;D2;+0:2]-[P;H0;D4;+0:3](-[O-;H0;D1:4])(-[O;-;D1;H0:5])=[O;D1;H0:6].[OH2;D0;+0:7]',
  'templateID': 'MNXR102035',
  'templateSubstrate': ['Cc1cn([C@H]2C[C@H](O)[C@@H](CO)O2)c(=O)[nH]c1=O',
   'O=P([O-])([O-])O'],
  'rxn_smiles_basic': 'O.O=P([O-])([O-])OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=P([O-])([O-])O',
  'rxn_smiles_final': 'O.O=P([O-])([O-])OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=P([O-])([O-])O',
  'reactant_smile': 'O.O=P([O-])([O-])OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1',
  'productsmile': 'OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=P([O-])([O-])O',
  'similarity': (0.6666666666666666, 0.6666666666666666, 1)},
 'rxn15': {'EC number': '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89',
  'rule': '[C:1]-[OH;D1;+0:2].[O-;H0;D1:7]-[P;H0;D4;+0:3](-[O;-;D1;H0:5])(=[O;D1;H0:6])-[OH;D1;+0:4]>>[C:1]-[O;H0;D2;+0:2]-[P;H0;D4;+0:3](-[O-;H0;D1:4])(-[O;-;D1;H0:5])=[O;D1;H0:6].[OH2;D0;+0:7]',
  'templateID': 'MNXR102036',
  'templateSubstrate': ['Nc1ncnc2c1ncn2[C@H]1C[C@H](O)[C@@H](CO)O1',
   'O=P([O-])([O-])O'],
  'rxn_smiles_basic': 'O.O=P([O-])([O-])OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=P([O-])([O-])O',
  'rxn_smiles_final': 'O.O=P([O-])([O-])OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=P([O-])([O-])O',
  'reactant_smile': 'O.O=P([O-])([O-])OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1',
  'productsmile': 'OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=P([O-])([O-])O',
  'similarity': (0.7971014492753623, 0.7971014492753623, 1)},
 'rxn16': {'EC number': '3.1.5.1',
  'rule': '[#8:1]-[P;H0;D4;+0:2](-[O-;H0;D1:7])(-[O;-;D1;H0:3])=[O;D1;H0:4].[C:6]-[OH;D1;+0:5]>>[#8:1]-[P;H0;D4;+0:2](-[O;-;D1;H0:3])(=[O;D1;H0:4])-[O;H0;D2;+0:5]-[C:6].[OH2;D0;+0:7]',
  'templateID': 'MNXR102057_reverse',
  'templateSubstrate': ['O=P([O-])([O-])OP(=O)([O-])OP(=O)([O-])[O-]',
   'Nc1nc2c(ncn2[C@H]2C[C@H](O)[C@@H](CO)O2)c(=O)[nH]1'],
  'rxn_smiles_basic': 'O.O=P([O-])([O-])OP(=O)([O-])OP(=O)([O-])OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=P([O-])([O-])OP(=O)([O-])OP(=O)([O-])[O-]',
  'rxn_smiles_final': 'O.O=P([O-])([O-])OP(=O)([O-])OP(=O)([O-])OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=P([O-])([O-])OP(=O)([O-])OP(=O)([O-])[O-].[H+]',
  'reactant_smile': 'O.O=P([O-])([O-])OP(=O)([O-])OP(=O)([O-])OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1',
  'productsmile': 'OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=P([O-])([O-])OP(=O)([O-])OP(=O)([O-])[O-]',
  'similarity': (0.7341772151898734, 1, 0.7945205479452054)},
 'rxn17': {'EC number': '1.14.15.4',
  'rule': '[C:1]-[CH2;D2;+0:2]-[C:3].[O;H0;D1;+0:5]=[O;H0;D1;+0:4]>>[C:1]-[C@H;D3;+0:2](-[C:3])-[OH;D1;+0:4].[OH2;D0;+0:5]',
  'templateID': 'MNXR102250_reverse',
  'templateSubstrate': ['C[C@]12CC[C@H]3[C@@H](CCC4=CC(=O)CC[C@@]43C)[C@@H]1CC[C@@H]2C(=O)CO',
   'O=O'],
  'rxn_smiles_basic': 'O.OCCN1CCN(C[C@H](O)C=C2c3ccccc3Sc3ccc(Cl)cc32)CC1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O',
  'rxn_smiles_final': 'O.OCCN1CCN(C[C@H](O)C=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)c1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O.[H+].NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1',
  'reactant_smile': 'O.OCCN1CCN(C[C@H](O)C=C2c3ccccc3Sc3ccc(Cl)cc32)CC1',
  'productsmile': 'OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O',
  'similarity': (0.3655913978494624, 0.3655913978494624, 1)},
 'rxn18': {'EC number': '1.14.15.4',
  'rule': '[C:1]-[CH2;D2;+0:2]-[C:3].[O;H0;D1;+0:5]=[O;H0;D1;+0:4]>>[C:1]-[C@H;D3;+0:2](-[C:3])-[OH;D1;+0:4].[OH2;D0;+0:5]',
  'templateID': 'MNXR102250_reverse',
  'templateSubstrate': ['C[C@]12CC[C@H]3[C@@H](CCC4=CC(=O)CC[C@@]43C)[C@@H]1CC[C@@H]2C(=O)CO',
   'O=O'],
  'rxn_smiles_basic': 'O.OCCN1CCN(C[C@@H](O)C=C2c3ccccc3Sc3ccc(Cl)cc32)CC1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O',
  'rxn_smiles_final': 'O.OCCN1CCN(C[C@@H](O)C=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)c1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O.[H+].NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1',
  'reactant_smile': 'O.OCCN1CCN(C[C@@H](O)C=C2c3ccccc3Sc3ccc(Cl)cc32)CC1',
  'productsmile': 'OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O',
  'similarity': (0.3655913978494624, 0.3655913978494624, 1)},
 'rxn19': {'EC number': '1.14.15.4',
  'rule': '[C:1]-[CH2;D2;+0:2]-[C:3].[O;H0;D1;+0:4]=[O;H0;D1;+0:5]>>[C:1]-[C@@H;D3;+0:2](-[C:3])-[OH;D1;+0:4].[OH2;D0;+0:5]',
  'templateID': 'MNXR102251_reverse',
  'templateSubstrate': ['C[C@]12CC[C@H]3[C@@H](CCC4=CC(=O)CC[C@@]43C)[C@@H]1CC[C@]2(O)C(=O)CO',
   'O=O'],
  'rxn_smiles_basic': 'O.OCCN1CCN(C[C@H](O)C=C2c3ccccc3Sc3ccc(Cl)cc32)CC1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O',
  'rxn_smiles_final': 'O.OCCN1CCN(C[C@H](O)C=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)c1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O.[H+].NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1',
  'reactant_smile': 'O.OCCN1CCN(C[C@H](O)C=C2c3ccccc3Sc3ccc(Cl)cc32)CC1',
  'productsmile': 'OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O',
  'similarity': (0.43010752688172044, 0.43010752688172044, 1)},
 'rxn20': {'EC number': '1.14.15.4',
  'rule': '[C:1]-[CH2;D2;+0:2]-[C:3].[O;H0;D1;+0:4]=[O;H0;D1;+0:5]>>[C:1]-[C@@H;D3;+0:2](-[C:3])-[OH;D1;+0:4].[OH2;D0;+0:5]',
  'templateID': 'MNXR102251_reverse',
  'templateSubstrate': ['C[C@]12CC[C@H]3[C@@H](CCC4=CC(=O)CC[C@@]43C)[C@@H]1CC[C@]2(O)C(=O)CO',
   'O=O'],
  'rxn_smiles_basic': 'O.OCCN1CCN(C[C@@H](O)C=C2c3ccccc3Sc3ccc(Cl)cc32)CC1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O',
  'rxn_smiles_final': 'O.OCCN1CCN(C[C@@H](O)C=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)c1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O.[H+].NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1',
  'reactant_smile': 'O.OCCN1CCN(C[C@@H](O)C=C2c3ccccc3Sc3ccc(Cl)cc32)CC1',
  'productsmile': 'OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1.O=O',
  'similarity': (0.43010752688172044, 0.43010752688172044, 1)},
 'rxn21': {'EC number': '1.1.1.1',
  'rule': '[C:1]-[CH2;D2;+0:2]-[OH;D1;+0:3]>>[C:1]-[CH;D2;+0:2]=[O;H0;D1;+0:3]',
  'templateID': 'MNXR103538',
  'templateSubstrate': ['OCCc1c[nH]c2ccc(O)cc12'],
  'rxn_smiles_basic': 'O=CCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1>>OCCN1CCN(CCC=C2c3ccccc3Sc3ccc(Cl)cc32)CC1',

In [14]:
result_num_df = pd.DataFrame(result_num)
result_num_df['ec3_list'] = result_num_df['ec3_list'].apply(lambda x:ast.literal_eval(x))
result_num_df['ec3_list'] = result_num_df['ec3_list'].apply(lambda x:[ec for ec in x if '-' not in ec])
result_num_df['ec3_num'] = result_num_df['ec3_list'].apply(lambda x:len(x))

result_num_df['ec4_list'] = result_num_df['ec4_list'].apply(lambda x:ast.literal_eval(x))
result_num_df['ec4_list'] = result_num_df['ec4_list'].apply(lambda x:[ec for ec in x if '-' not in ec])
result_num_df['ec4_num'] = result_num_df['ec4_list'].apply(lambda x:len(x))

result_num_df

,drug_name,reaction_num,ec4_num,ec4_list,ec3_num,ec3_list
0,(R)-Elagolix,173,194,"[2.6.1.114, 3.1.3.39, 1.17.1.1, 3.2.1.60, 3.1....",38,"[1.22.1, 1.10.3, 3.6.1, 2.6.1, 1.3.3, 1.11.2, ..."
1,Acebutolol (hydrochloride),80,381,"[1.1.1.362, 3.1.3.97, 3.2.1.60, 3.1.3.50, 1.1....",54,"[4.2.2, 1.22.1, 1.7.3, 1.10.3, 1.3.99, 2.3.2, ..."
2,Acrivastine,42,63,"[1.14.14.1, 1.14.13.209, 1.14.13.91, 4.1.2.41,...",17,"[3.1.5, 4.2.1, 1.14.18, 3.1.6, 1.14.13, 1.2.1,..."
3,Adoprazine,29,27,"[1.14.14.1, 1.14.13.209, 1.14.13.91, 1.14.13.9...",10,"[1.14.14, 2.1.1, 1.14.18, 2.4.1, 1.14.13, 3.6...."
4,Almorexant,104,109,"[3.5.1.94, 3.5.1.23, 6.3.2.56, 3.5.1.36, 3.5.1...",30,"[1.22.1, 1.10.3, 3.6.1, 6.2.1, 1.11.2, 1.21.1,..."
...,...,...,...,...,...,...
121,Volinanserin,69,159,"[1.1.1.362, 3.1.3.39, 3.2.1.60, 3.1.3.97, 3.2....",28,"[3.6.1, 1.11.2, 1.14.19, 1.14.3, 4.1.3, 3.8.1,..."
122,Vortioxetine (hydrobromide),0,0,[],0,[]
123,Xanomeline (oxalate),0,0,[],0,[]
124,Zafirlukast,65,55,"[1.14.13.180, 1.14.14.1, 1.14.13.209, 1.14.13....",18,"[3.6.1, 1.13.11, 2.6.1, 4.1.3, 3.8.1, 1.17.99,..."
125,Zuclopenthixol,42,69,"[3.1.3.97, 1.14.13.72, 1.14.15.4, 3.1.3.104, 1...",15,"[3.1.5, 1.1.99, 1.1.3, 1.14.18, 4.3.3, 1.14.13..."

In [15]:
result_num_df[result_num_df['drug_name']=='Carvedilol']

,drug_name,reaction_num,ec4_num,ec4_list,ec3_num,ec3_list
23,Carvedilol,133,322,"[3.1.3.97, 3.2.1.60, 3.1.3.50, 1.1.1.15, 1.1.1...",37,"[1.22.1, 1.7.3, 1.10.3, 3.6.1, 1.14.12, 1.11.2..."

In [16]:
result_num_df.to_csv('../../Results/ref3_drug_deg_result_filter.csv',index=None)