In [1]:
import pandas as pd
import numpy as np
import json
from rdkit import Chem
from rdkit.Chem import Draw
from rdkit.Chem import rdChemReactions
from rdkit.Chem.Draw import rdMolDraw2D
from rdkit.Chem.Draw import IPythonConsole
from IPython.display import SVG, display
from rdkit.Chem.Fingerprints import FingerprintMols
from rdkit import DataStructs
from rdkit.Chem import MACCSkeys
from rdkit.Chem import AllChem
import pandas as pd
import rdchiral
import itertools
import pickle
import sys
from tqdm import tqdm 
from rdchiral.main import rdchiralRun, rdchiralRunText, rdchiralReaction, rdchiralReactants
import cobra
from itertools import chain, combinations
import sys
import multiprocessing
from functools import partial
import matplotlib.pyplot as plt
import multiprocessing
from tqdm import tqdm
sys.path.append('../')

from common import *

### input and output

In [2]:
# step1
#input
mnxreac_smile_atom_mapping_rules_file_path = './merged_atommap_rules.csv'
target_drug_path = '../../Data/Drug/drugs_metabolites_db_v5.1.12.xlsx'
###output
result_all_file = "../../Results/drugbank_all_result_newrules.csv"

In [3]:
def process_rule(rule_smiles, mets_total_smiles):
    score = []
    smiles = []
    if 'C' in rule_smiles or 'c' in rule_smiles:
        for j in mets_total_smiles:
            current_score = calculate_similarity(rule_smiles, j)
            if current_score > 0.3:               ########################################################################
                score.append(current_score)
                smiles.append(j)
    else:
        smiles.append(rule_smiles)
        score.append(1)

    if len(score) == 0:
        return rule_smiles, [], []
    elif len(score) > 50:
        top40_data = sorted(zip(score, smiles), reverse=True)[:50]
    else:
        top40_data = sorted(zip(score, smiles), reverse=True)
    
    top40_scores, top40_smiles = zip(*top40_data)
    
    return rule_smiles, list(top40_smiles), list(top40_scores)

####################################################################################

def count_carbons(smiles):
    """计算一个 SMILES 字符串中碳 (C) 的个数"""
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return 0
    return sum(1 for atom in mol.GetAtoms() if atom.GetSymbol() == 'C')


def process_rule(rule_smiles, mets_total_smiles):
    score = []
    smiles = []
    
    # 计算 rule_smiles 的碳原子数
    rule_c_count = count_carbons(rule_smiles)

    if 'C' in rule_smiles or 'c' in rule_smiles:
        for j in mets_total_smiles:
            # 计算当前代谢物的碳原子数
            j_c_count = count_carbons(j)
            
            # 计算相似度
            current_score = calculate_similarity(rule_smiles, j)
            
            # 计算罚分
            if rule_c_count!=0:
                if rule_c_count > j_c_count:
                    penalty = (rule_c_count - j_c_count) / (rule_c_count) /10.216
                elif rule_c_count < j_c_count:
                    penalty = (j_c_count - rule_c_count) / (rule_c_count) /8.828
                else:
                    penalty = 0
            else:
                penalty = 0
            
            # 应用罚分
            adjusted_score = max(0, current_score - penalty)

            # 仅保留相似度大于0.3的结果
            if adjusted_score > -100:
                score.append(adjusted_score)
                smiles.append(j)
    
    else:
        smiles.append(rule_smiles)
        score.append(1)

    if len(score) == 0:
        return rule_smiles, [], []
    # elif len(score) > 100:
    #     top20_data = sorted(zip(score, smiles), reverse=True)[:100]
    else:
        top20_data = sorted(zip(score, smiles), reverse=True)
    
    top20_scores, top20_smiles = zip(*top20_data)
    
    return rule_smiles, list(top20_smiles), list(top20_scores)

In [4]:
def process_retrorule(index_row, mets_total_smiles,retrosys_smiles_calculate_similarity_pd,heterologous_met_smiles):
    rxndb_list_tmp = []
    # newdbSmiles_tmp = []
    failedrxn_tmp = []
    index, row = index_row
    rxn_id, ECnumber, reactants, products = row['MNX_ID'], row['classifs'], row['substrate_smiles'], row['product_smiles']
    deprecated_equ_smiles, reactantSMARTs, productSMARTs, rule = row['deprecated_equ_smiles'], row['ReactantsSMARTs'], row['ProductSMARTs'], row['RetroRules']
    deprecated_equ_smiles = deprecated_equ_smiles.split('>>')
    if rxn_id not in ['MNXR101882', 'MNXR101884', 'MNXR101879', 'MNXR101885', 'MNXR101886', 'MNXR101887',
                        'MNXR103528', 'MNXR103575']:  # ATP NADH conversion stuff
        productSMARTs = productSMARTs.split('.')
        products = products.split('.')
        new_products_smiles = []
        scores = []
        
        if len(productSMARTs) == len(products):
            for x in range(len(productSMARTs)):  # prepare mets with substructure and sort the reactants combination
                new_products_smile_one,score_one = get_calculate_similarity(products[x],retrosys_smiles_calculate_similarity_pd)
                new_products_smiles.append(new_products_smile_one)
                scores.append(score_one)

            product_prepared = []
            scores_prepared = []
            for lst, score_lst in zip(new_products_smiles, scores):
                if heterologous_met_smiles in lst:
                    if len(new_products_smiles) == 1:  # if only one sub list
                        product_prepared.append([heterologous_met_smiles])
                        scores_prepared.append(score_lst)
                    else:
                        other_lists = [sub_lst for sub_lst in new_products_smiles if sub_lst != lst]
                        tmp_product = list(itertools.product([heterologous_met_smiles], *other_lists))
                        product_prepared += tmp_product

                        tmp_scores = list(itertools.product([score_lst[new_products_smiles.index(lst)]], *scores))
                        scores_prepared += tmp_scores
            # print('product_prepared',product_prepared,len(product_prepared))
            for m in range(0, len(product_prepared)):  # apply the rule and output the rxn
                smile = product_prepared[m]
                score = scores_prepared[m]
                
                if len(smile) > 1:
                    product_smile = '.'.join(smile)
                else:
                    product_smile = smile[0]

                retrorule_tmp = rule.split('>>')
                retrorule_tmp = '(' + retrorule_tmp[0] + ')>>' + '(' + retrorule_tmp[1] + ')'            
                product_smile_tmp = product_smile
                # print('retrorule_tmp',retrorule_tmp)
                # print('product_smile',product_smile)
                try:
                    # print('product_smile_tmp',product_smile_tmp)
                    product_mol = Chem.MolFromSmiles(product_smile_tmp)
                    reaction = AllChem.ReactionFromSmarts(retrorule_tmp)
                    reactant_smiles = reaction.RunReactants((product_mol,))
                    smiles = [Chem.MolToSmiles(x[0]) for x in reactant_smiles]
                    reactant_smiles = list(set(smiles))

                    for reactant_smile in reactant_smiles:
                        if len(deprecated_equ_smiles) > 0:
                            if deprecated_equ_smiles[0] == '':
                                reactant_smile_final = reactant_smile
                            else:
                                reactant_smile_final = reactant_smile + '.' + deprecated_equ_smiles[0]
                            if deprecated_equ_smiles[1] == '':
                                product_smile_final = product_smile_tmp
                            else:
                                product_smile_final = product_smile_tmp + '.' + deprecated_equ_smiles[1]
                        rxn_smiles = reactant_smile + '>>' + product_smile_tmp
                        rxn_smiles_final = reactant_smile_final + '>>' + product_smile_final
                        
                        tmp = {
                            'EC number': ECnumber,
                            'rule': rule,
                            'templateID': rxn_id,
                            'templateSubstrate': products,
                            'rxn_smiles_basic': rxn_smiles,
                            'rxn_smiles_final': rxn_smiles_final,
                            'reactant_smile': reactant_smile,
                            'productsmile': product_smile_tmp,
                            'similarity': score
                        }
                        if check_rule(tmp['rxn_smiles_basic'])=='blance':
                            rxndb_list_tmp.append(tmp)  
                            # mets_tmp = reactant_smile.split('.')      
                            # for reactant in mets_tmp:             
                            #     if reactant not in mets_total_smiles and reactant not in newdbSmiles_tmp:         
                            #         newdbSmiles_tmp.append(reactant)        
                except:
                    failedrxn_tmp.append(rxn_id)
                
    return(rxndb_list_tmp,failedrxn_tmp)

In [5]:
def process_ec_list(ec_list,topn):
    processed_set = set()
    
    for ec in ec_list:
        for sub_ec in ec.split(';'):
            parts = sub_ec.strip().split('.')
            if len(parts) >= 3:  # Only process EC numbers with at least 3 parts
                processed_set.add('.'.join(parts[:topn]))
    
    return list(processed_set)

# Example usage
input_ec_numbers = ['4.1.3.-', '3.1.3.1', '1.1.3.100;2.1.4.2']
output_ec_numbers = process_ec_list(input_ec_numbers,3)
print(output_ec_numbers)

['2.1.4', '4.1.3', '3.1.3', '1.1.3']

In [6]:
def check_productsmile(smiles):#only keep smiles with carbon
    smiles_lst = smiles.split('.')
    smiles_lst = [x for x in smiles_lst if smiles_has_carbon(x)]
    return len(smiles_lst)

In [7]:
rules_product_smiles_lst = []
retrorules = pd.read_csv(mnxreac_smile_atom_mapping_rules_file_path)
# retrorules = retrorules[retrorules['MNX_ID'].str.contains('MNXR97814')]
for index,row in retrorules.iterrows():
    tmp  = row['product_smiles'].split('.')
    for i in tmp:
        if i not in rules_product_smiles_lst:
            rules_product_smiles_lst.append(i)
print('rules_product_smiles_lst',len(rules_product_smiles_lst))

/home/wuke/anaconda3/envs/AIGEM/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3457: DtypeWarning: Columns (1,2,4,8) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

rules_product_smiles_lst 14792

In [8]:
target_drug = pd.read_excel(target_drug_path)
target_drug.rename(columns={'metabolites_smiles':'product_smiles'},inplace=True)
# target_drug = target_drug[target_drug['drug_name']=='digitoxin']
# target_drug = target_drug.loc[0:2,:]
# target_drug = target_drug.iloc[error_index[300:],:].reset_index(drop=True)
target_drug = target_drug[target_drug['drug_smiles'].apply(lambda x:normalize_smiles(x)!=None)]
target_drug = target_drug[['drugbank_id','drug_name','drug_smiles','product_smiles','our_predicitions','MicrobeRX_predicitions']]
target_drug

,drugbank_id,drug_name,drug_smiles,product_smiles,our_predicitions,MicrobeRX_predicitions
0,DB00091,Cyclosporine,CC[C@@H]1NC(=O)[C@H]([C@H](O)[C@H](C)C\C=C\C)N...,CC[C@@H]1NC(=O)[C@H]([C@H](O)[C@H](C)C\C=C\C)N...,NaN,NaN
1,DB01120,Gliclazide,[H][C@@]12CCC[C@]1([H])CN(C2)NC(=O)NS(=O)(=O)C...,[H][C@@]12CCC[C@]1([H])CN(C2)N=C(O)NS(=O)(=O)C...,NaN,yes
2,DB01132,Pioglitazone,CCC1=CN=C(CCOC2=CC=C(CC3SC(=O)NC3=O)C=C2)C=C1,OC1=CC=C(CC2SC(=O)NC2=O)C=C1,NaN,yes
3,DB01131,Proguanil,CC(C)NC(=N)NC(=N)NC1=CC=C(Cl)C=C1,NC(=N)NC(=N)NC1=CC=C(Cl)C=C1,NaN,yes
4,DB01131,Proguanil,CC(C)NC(=N)NC(=N)NC1=CC=C(Cl)C=C1,CC1(C)N=C(N)N=C(N)N1C1=CC=C(Cl)C=C1,NaN,yes
...,...,...,...,...,...,...
1269,DB00643,Mebendazole,COC(=O)NC1=NC2=C(N1)C=C(C=C2)C(=O)C1=CC=CC=C1,N=C1NC2=C(N1)C=C(C=C2)C(=O)C1=CC=CC=C1,NaN,NaN
1270,DB00641,Simvastatin,[H][C@]12[C@H](C[C@@H](C)C=C1C=C[C@H](C)[C@@H]...,[H][C@@](O)(CC[C@@]1([H])[C@@H](C)C=CC2=C[C@H]...,NaN,yes
1271,DB00641,Simvastatin,[H][C@]12[C@H](C[C@@H](C)C=C1C=C[C@H](C)[C@@H]...,[H]O[C@@]1([H])C([H])([H])C(=O)O[C@]([H])(C([H...,NaN,NaN
1272,DB00641,Simvastatin,[H][C@]12[C@H](C[C@@H](C)C=C1C=C[C@H](C)[C@@H]...,[H]O[C@@]1([H])C([H])([H])C(=O)O[C@]([H])(C([H...,NaN,yes
1273,DB06701,Dexmethylphenidate,[H][C@@](C(=O)OC)(C1=CC=CC=C1)[C@@]1([H])CCCCN1,[H][C@@](C(=O)OC)(C1=CC=C(O)C=C1)[C@@]1([H])CC...,NaN,yes

In [9]:
# # 读取gut clean ec预测结果
# with open('../../Results/AGORA2_strain_eclist_top3_common.pkl', 'rb') as f:
#     loaded_top3 = pickle.load(f)

# with open('../../Results/AGORA2_strain_eclist_top4_common.pkl', 'rb') as f:
#     loaded_top4 = pickle.load(f)

# print("读取完成！")
# print(f"Top3 列表长度：{len(loaded_top3)}")
# print(f"Top4 列表长度：{len(loaded_top4)}")

## byproduct prediction

In [10]:
result_num = {'drug_name':[],
              'reaction_num':[],
              'ec4_num':[],
              'ec4_list':[],
              'ec3_num':[],
              'ec3_list':[],
              'success_predict':[],
              'success_ecnumber':[],
              }
# filter_info = {'drug_carbon':[],
#                'success_carbon':[],
#                'error_carbon':[],
#                'success_sim_score':[],
#                'error_sim_score':[],
#                }
# 循环开始前，删掉旧文件
if os.path.exists(result_all_file):
    os.remove(result_all_file)
# target_drug = target_drug.iloc[1140:,:]
for index,row in tqdm(target_drug.iterrows(),total=len(target_drug)):
    print(row['drug_name'])
    heterologous_met_smiles = row['drug_smiles']
    # heterologous_met_smiles = 'FC1=CNC(=O)NC1=O'
    # heterologous_met_smiles = 'N[C@@H](CC1=CC(O)=C(O)C=C1)C(O)=O'
    # heterologous_met_smiles = '[NH3+][C@@H](Cc1ccc(O)c(O)c1)C(=O)[O-]' ######## L-dopa
    heterologous_met_smiles = normalize_smiles(heterologous_met_smiles)
    # model_met = target_drug['smiles'].to_list()
    model_met = [heterologous_met_smiles,heterologous_met_smiles,heterologous_met_smiles,'O=C([O-])CCC(=O)C(=O)[O-]',
                 'C[S+](CC[C@@H](C(=O)[O-])N)C[C@@H]1[C@H]([C@H]([C@@H](O1)N2C=NC3=C(N=CN=C32)N)O)O',
                 'C1=NC(=C2C(=N1)N(C=N2)[C@H]3[C@@H]([C@@H]([C@H](O3)CSCC[C@@H](C(=O)O)N)O)O)N',
                 'O=C(O)[C@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@H]1O',# β-D-葡萄糖醛酸
                 'CC(=O)SCCNC(=O)CCNC(=O)[C@@H](C(C)(C)COP(=O)(O)OP(=O)(O)OC[C@@H]1[C@H]([C@H]([C@@H](O1)N2C=NC3=C(N=CN=C32)N)O)OP(=O)(O)O)O', # Acetyl-CoA
                 ]
    new_met = []

    # add heterologous_met_smiles to model_met list
    new_model_and_heterologous_met = model_met + new_met
    new_model_and_heterologous_met.append(heterologous_met_smiles)
    new_model_and_heterologous_met = [smile for smile in new_model_and_heterologous_met if '.' not in smile]
    new_model_and_heterologous_met = [smile for smile in new_model_and_heterologous_met if 'C' in smile or 'c' in smile] ###只筛第一轮
    # print(len(new_model_and_heterologous_met))
    #calculate similarity
    num_processes = 100
    pool = multiprocessing.Pool(num_processes)
    retrosys_smiles_calculate_similarity = {'rules_smiles': [],
                                            'smiles_in_mets_total_smiles': [],
                                            'scores': []}


    process_rule_partial = partial(process_rule, mets_total_smiles=new_model_and_heterologous_met)
    for result in tqdm(pool.imap(process_rule_partial, rules_product_smiles_lst, chunksize=200), total=len(rules_product_smiles_lst)):
        if result[0] not in retrosys_smiles_calculate_similarity['rules_smiles']:
            retrosys_smiles_calculate_similarity['rules_smiles'].append(result[0]) 
            retrosys_smiles_calculate_similarity['smiles_in_mets_total_smiles'].append(result[1]) 
            retrosys_smiles_calculate_similarity['scores'].append(result[2]) 
    pool.close()
    pool.join()

    retrosys_smiles_calculate_similarity_pd = pd.DataFrame(retrosys_smiles_calculate_similarity)
##############################################
    # for index4, row4 in retrosys_smiles_calculate_similarity_pd.iterrows():
    #     if row4['rules_smiles'] not in row4['smiles_in_mets_total_smiles']:
    #         # 修改 DataFrame 中嵌套的列表
    #         retrosys_smiles_calculate_similarity_pd.at[index4, 'smiles_in_mets_total_smiles'].append(row4['rules_smiles'])
##############################################
    rxndb_list = [] 
    # newdbSmiles = []
    failedrxn = []
    num_processes =100  #  adjust the number of processes according to your needs
    pool = multiprocessing.Pool(num_processes)
    # Execute in parallel using process pool

    # Create a partial function that passes mets_total_smiles and mets_total_mol as default parameters to the process_retrorule function
    process_retrorule_partial = partial(process_retrorule, mets_total_smiles=new_model_and_heterologous_met,retrosys_smiles_calculate_similarity_pd = retrosys_smiles_calculate_similarity_pd,heterologous_met_smiles = heterologous_met_smiles)

    # Using the process pool to execute in parallel, the chunksize parameter is placed inside the imap function.
    for result in tqdm(pool.imap(process_retrorule_partial, retrorules.iterrows(), chunksize=200), total=len(retrorules)):
        # if result == ([], [], []):
        #     pass
        # else:
        #     print(result)
        if result is not None:
            if result[0] :  #  check if the result is not empty
                rxndb_list.extend(result[0]) 
            # if result[1] is not None:
            #     newdbSmiles.extend(result[1])
            if result[1]:
                failedrxn.extend(result[1])  

    pool.close()
    pool.join()

    rxndb = {}
    for i, rxn_dict in enumerate(rxndb_list):
        # generate a unique key for each reaction, for example "rxn0"，"rxn1"，"rxn2"，...
        key = f'rxn{i+1}'
        # merge to the dictionary
        rxndb[key] = rxn_dict

    # print('rxndb num',len(rxndb))
    # print('failedrxn num',len(failedrxn))

    ecnumber_list = []
    for _,x in rxndb.items():
        ec_list = x['EC number'].split(';')
        ec_list = process_ec_list(ec_list,3)
        ecnumber_list += ec_list

    ecnumber_list = list(set(ecnumber_list))   
    result_df = {'ID':[],
            'reactant_smile':[],
            'productsmile':[],
            'rxn_smiles_basic':[],
            'templateID':[],
            'EC number':[],}

    for k,v in rxndb.items():
        result_df['ID'].append(k)
        result_df['reactant_smile'].append(v['reactant_smile'])
        result_df['productsmile'].append(v['productsmile'])
        result_df['rxn_smiles_basic'].append(v['rxn_smiles_basic'])
        result_df['templateID'].append(v['templateID'])
        result_df['EC number'].append(v['EC number'])

    result_df = pd.DataFrame({'ID': result_df['ID'],
                        'reactant_smile': result_df['reactant_smile'],
                        'productsmile': result_df['productsmile'],
                        'rxn_smiles_basic': result_df['rxn_smiles_basic'],
                        'templateID': result_df['templateID'],
                        'EC number': result_df['EC number'],
                        })

    result_df.drop_duplicates(subset=['reactant_smile', 'productsmile'], inplace=True)
    result_df.reset_index(drop=True, inplace=True)

    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.OO']
    result_df = result_df[result_df['productsmile']!='OO.'+ heterologous_met_smiles]
    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.O=C=O']
    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.O=S([O-])[O-]']
    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.[SH-]']
    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.O=P([O-])([O-])OP(=O)([O-])O']
    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.II']
    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.[NH4+]']
    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.[Br-]']
    
    try:
        res = result_df['reactant_smile'].to_list()
        ec_lst = []
        for k,v in rxndb.items():
            if v['reactant_smile'] in res:
                ec_lst.append(v['EC number'])
    except:
        ec_lst = []
        pass
    # print('result_df',len(result_df))
    # print(ec_lst)
    ec_lst_4 = process_ec_list(ec_lst,4)
    ec_lst_3 = process_ec_list(ec_lst,3)
    # print(len(ec_lst_3))
    # print(len(ec_lst_4))
    
    result_num['drug_name'].append(row['drug_name'])
    result_num['reaction_num'].append(len(result_df))
    result_num['ec4_num'].append(len(ec_lst_4))
    result_num['ec4_list'].append(str(ec_lst_4))
    result_num['ec3_num'].append(len(ec_lst_3))
    result_num['ec3_list'].append(str(ec_lst_3))
    
    success_predict = 0
    success_ecnumber = []
    success_ID = []
    if row['product_smiles'] != 'unknown' and row['drug_name'] != 'Lactulose':
        target_smiles = row['product_smiles'].split('.')[0]
        for index2,row2 in result_df.iterrows():
            smiles_list = row2['reactant_smile'].split('.')
            if any(compare_smiles_inchikey(smiles,target_smiles) for smiles in smiles_list):
                success_predict =1
                print(1)
                success_ID.append(row2['ID'])
                tmp_ec_lst = row2['EC number'].split(';')
                success_ecnumber+=process_ec_list(tmp_ec_lst,3)
    
    result_num['success_predict'].append(success_predict)
    result_num['success_ecnumber'].append(str(list(set(success_ecnumber))))

  0%|          | 0/1274 [00:00<?, ?it/s]

Cyclosporine

100%|██████████| 14792/14792 [00:10<00:00, 1351.27it/s]
100%|██████████| 34899/34899 [00:14<00:00, 2480.67it/s]

1
1

  0%|          | 1/1274 [00:30<10:43:07, 30.31s/it]

Gliclazide

100%|██████████| 14792/14792 [00:10<00:00, 1464.17it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3105.13it/s]

1
1
1

  0%|          | 2/1274 [00:53<9:19:17, 26.38s/it]

Pioglitazone

100%|██████████| 14792/14792 [00:08<00:00, 1655.35it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3159.79it/s]

1

  0%|          | 3/1274 [01:16<8:40:09, 24.55s/it]

Proguanil

100%|██████████| 14792/14792 [00:08<00:00, 1804.00it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3141.19it/s]
  0%|          | 4/1274 [01:37<8:14:22, 23.36s/it]

Proguanil

100%|██████████| 14792/14792 [00:08<00:00, 1740.97it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3273.19it/s]
  0%|          | 5/1274 [01:59<8:00:02, 22.70s/it]

1
Rabeprazole

100%|██████████| 14792/14792 [00:09<00:00, 1603.39it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3027.91it/s]
  0%|          | 6/1274 [02:22<8:05:32, 22.98s/it]

Tolbutamide

100%|██████████| 14792/14792 [00:08<00:00, 1716.93it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3256.20it/s]

1
1

  1%|          | 7/1274 [02:44<7:57:30, 22.61s/it]

Gliclazide

100%|██████████| 14792/14792 [00:09<00:00, 1622.80it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3373.11it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

  1%|          | 8/1274 [03:06<7:51:26, 22.34s/it]

Gliclazide

100%|██████████| 14792/14792 [00:09<00:00, 1589.21it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3193.58it/s]

1
1
1
1

  1%|          | 9/1274 [03:29<7:53:04, 22.44s/it]

1
1
Gliclazide

100%|██████████| 14792/14792 [00:09<00:00, 1622.63it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3179.99it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

  1%|          | 10/1274 [03:51<7:53:57, 22.50s/it]

Pioglitazone

100%|██████████| 14792/14792 [00:09<00:00, 1606.07it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3122.34it/s]
  1%|          | 11/1274 [04:14<7:56:53, 22.65s/it]

Gliclazide

100%|██████████| 14792/14792 [00:08<00:00, 1677.62it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3168.60it/s]

1
1
1
1
1

  1%|          | 12/1274 [04:37<7:54:12, 22.55s/it]

1
Gliclazide

100%|██████████| 14792/14792 [00:09<00:00, 1621.02it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3165.05it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

  1%|          | 13/1274 [04:59<7:55:01, 22.60s/it]

Gliclazide

100%|██████████| 14792/14792 [00:08<00:00, 1698.83it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3163.47it/s]

1
1
1
1
1

  1%|          | 14/1274 [05:21<7:51:20, 22.44s/it]

1
Amiodarone

100%|██████████| 14792/14792 [00:09<00:00, 1604.19it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3108.34it/s]
  1%|          | 15/1274 [05:45<7:55:42, 22.67s/it]

Nifedipine

100%|██████████| 14792/14792 [00:09<00:00, 1637.90it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3114.41it/s]
  1%|▏         | 16/1274 [06:08<7:56:45, 22.74s/it]

1
Nifedipine

100%|██████████| 14792/14792 [00:08<00:00, 1669.85it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3051.96it/s]

1
1
1
1
1
1
1
1
1
1

  1%|▏         | 17/1274 [06:31<7:58:08, 22.82s/it]

1
1
Cefuroxime

100%|██████████| 14792/14792 [00:09<00:00, 1561.21it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3156.65it/s]
  1%|▏         | 18/1274 [06:54<7:59:41, 22.92s/it]

Pioglitazone

100%|██████████| 14792/14792 [00:09<00:00, 1608.29it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3208.68it/s]

1
1

  1%|▏         | 19/1274 [07:16<7:57:58, 22.85s/it]

1
1
1
1
Pioglitazone

100%|██████████| 14792/14792 [00:08<00:00, 1664.94it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2974.07it/s]
  2%|▏         | 20/1274 [07:40<7:59:33, 22.95s/it]

1
Capecitabine

100%|██████████| 14792/14792 [00:09<00:00, 1614.68it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3255.92it/s]

1

  2%|▏         | 21/1274 [08:02<7:57:09, 22.85s/it]

Doxepin

100%|██████████| 14792/14792 [00:09<00:00, 1540.66it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3060.15it/s]
  2%|▏         | 22/1274 [08:26<8:02:46, 23.14s/it]

Gemifloxacin

100%|██████████| 14792/14792 [00:09<00:00, 1531.97it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3104.29it/s]
  2%|▏         | 23/1274 [08:50<8:05:46, 23.30s/it]

Nefazodone

100%|██████████| 14792/14792 [00:09<00:00, 1602.20it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2878.41it/s]
  2%|▏         | 24/1274 [09:14<8:11:02, 23.57s/it]

Nefazodone

100%|██████████| 14792/14792 [00:09<00:00, 1598.43it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3317.17it/s]
  2%|▏         | 25/1274 [09:36<8:03:56, 23.25s/it]

Nefazodone

100%|██████████| 14792/14792 [00:09<00:00, 1550.91it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3004.91it/s]

1
1
1
1
1
1
1
1

  2%|▏         | 26/1274 [10:01<8:09:47, 23.55s/it]

Doxepin

100%|██████████| 14792/14792 [00:09<00:00, 1562.21it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3036.08it/s]

1
1
1
1
1

  2%|▏         | 27/1274 [10:24<8:10:25, 23.60s/it]

1
Doxepin

100%|██████████| 14792/14792 [00:09<00:00, 1570.41it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3179.06it/s]

1

  2%|▏         | 28/1274 [10:48<8:07:41, 23.48s/it]

1
Doxepin

100%|██████████| 14792/14792 [00:09<00:00, 1529.58it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3075.45it/s]

1
1
1
1

  2%|▏         | 29/1274 [11:11<8:09:34, 23.59s/it]

1
1
1
1
Sulfinpyrazone

100%|██████████| 14792/14792 [00:09<00:00, 1622.08it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3005.56it/s]
  2%|▏         | 30/1274 [11:35<8:09:42, 23.62s/it]

1
Pioglitazone

100%|██████████| 14792/14792 [00:08<00:00, 1721.06it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3258.68it/s]

1
1
1
1
1

  2%|▏         | 31/1274 [11:57<7:58:44, 23.11s/it]

1
1
1
1
Sulfinpyrazone

100%|██████████| 14792/14792 [00:09<00:00, 1596.19it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2956.37it/s]
  3%|▎         | 32/1274 [12:21<8:04:48, 23.42s/it]

1
Carvedilol

100%|██████████| 14792/14792 [00:09<00:00, 1570.66it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3048.55it/s]

1
1
1

  3%|▎         | 33/1274 [12:45<8:10:26, 23.71s/it]

Carvedilol

100%|██████████| 14792/14792 [00:09<00:00, 1515.30it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3157.65it/s]

1
1
1
1

  3%|▎         | 34/1274 [13:09<8:11:45, 23.79s/it]

1
1
Carvedilol

100%|██████████| 14792/14792 [00:09<00:00, 1511.37it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3159.02it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

  3%|▎         | 35/1274 [13:33<8:12:21, 23.84s/it]

Carvedilol

100%|██████████| 14792/14792 [00:09<00:00, 1583.75it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3045.04it/s]

1
1
1
1

  3%|▎         | 36/1274 [13:57<8:12:53, 23.89s/it]

1
1
Carvedilol

100%|██████████| 14792/14792 [00:09<00:00, 1503.05it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3050.99it/s]

1
1
1
1

  3%|▎         | 37/1274 [14:22<8:14:49, 24.00s/it]

1
1
Carvedilol

100%|██████████| 14792/14792 [00:09<00:00, 1539.12it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3042.56it/s]

1
1
1
1

  3%|▎         | 38/1274 [14:46<8:16:46, 24.12s/it]

1
1
Cefuroxime

100%|██████████| 14792/14792 [00:08<00:00, 1652.90it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3335.02it/s]
  3%|▎         | 39/1274 [15:08<8:03:04, 23.47s/it]

Rosuvastatin

100%|██████████| 14792/14792 [00:09<00:00, 1602.71it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3375.15it/s]
  3%|▎         | 40/1274 [15:31<7:57:06, 23.20s/it]

Bupropion

100%|██████████| 14792/14792 [00:08<00:00, 1774.49it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3311.87it/s]
  3%|▎         | 41/1274 [15:52<7:43:34, 22.56s/it]

1
1
1
Amoxicillin

100%|██████████| 14792/14792 [00:08<00:00, 1682.09it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3231.40it/s]
  3%|▎         | 42/1274 [16:14<7:41:56, 22.50s/it]

Clonazepam

100%|██████████| 14792/14792 [00:09<00:00, 1620.12it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3235.61it/s]

1

  3%|▎         | 43/1274 [16:36<7:41:04, 22.47s/it]

1
Glipizide

100%|██████████| 14792/14792 [00:09<00:00, 1599.54it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3441.36it/s]

1
1
1
1

  3%|▎         | 44/1274 [16:58<7:37:08, 22.30s/it]

1
Glipizide

100%|██████████| 14792/14792 [00:09<00:00, 1619.28it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3251.28it/s]

1
1
1
1
1
1
1
1
1

  4%|▎         | 45/1274 [17:21<7:37:55, 22.36s/it]

1
1
1
Glipizide

100%|██████████| 14792/14792 [00:09<00:00, 1617.60it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3101.89it/s]

1
1
1
1

  4%|▎         | 46/1274 [17:44<7:42:52, 22.62s/it]

1
Oxybutynin

100%|██████████| 14792/14792 [00:09<00:00, 1583.38it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3161.35it/s]
  4%|▎         | 47/1274 [18:07<7:44:22, 22.71s/it]

Oxybutynin

100%|██████████| 14792/14792 [00:08<00:00, 1705.47it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3292.38it/s]

1
1
1
1

  4%|▍         | 48/1274 [18:29<7:39:30, 22.49s/it]

Amoxicillin

100%|██████████| 14792/14792 [00:08<00:00, 1701.65it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3284.09it/s]

1
1
1

  4%|▍         | 49/1274 [18:51<7:38:26, 22.45s/it]

1
Amoxicillin

100%|██████████| 14792/14792 [00:09<00:00, 1591.28it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3203.48it/s]

1
1
1

  4%|▍         | 50/1274 [19:14<7:40:52, 22.59s/it]

Promethazine

100%|██████████| 14792/14792 [00:09<00:00, 1564.62it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3238.88it/s]
  4%|▍         | 51/1274 [19:37<7:39:44, 22.55s/it]

1
Amoxicillin

100%|██████████| 14792/14792 [00:09<00:00, 1573.01it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3261.32it/s]
  4%|▍         | 52/1274 [20:00<7:41:41, 22.67s/it]

Amoxicillin

100%|██████████| 14792/14792 [00:08<00:00, 1673.08it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2922.72it/s]

1
1
1
1
1
1

  4%|▍         | 53/1274 [20:23<7:47:07, 22.95s/it]

1
Praziquantel

100%|██████████| 14792/14792 [00:09<00:00, 1508.63it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3096.14it/s]

1
1
1
1

  4%|▍         | 54/1274 [20:47<7:51:26, 23.19s/it]

1
Ibuprofen

100%|██████████| 14792/14792 [00:08<00:00, 1747.18it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3556.21it/s]

1
1
1
1
1
1

  4%|▍         | 55/1274 [21:08<7:35:09, 22.40s/it]

Ibuprofen

100%|██████████| 14792/14792 [00:08<00:00, 1727.13it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3389.10it/s]
  4%|▍         | 56/1274 [21:29<7:28:06, 22.07s/it]

1
1
1
1
1
1
Ibuprofen

100%|██████████| 14792/14792 [00:08<00:00, 1758.27it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3343.67it/s]

1
1

  4%|▍         | 57/1274 [21:50<7:22:50, 21.83s/it]

Ibuprofen

100%|██████████| 14792/14792 [00:08<00:00, 1762.88it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2933.10it/s]

1
1

  5%|▍         | 58/1274 [22:13<7:27:35, 22.08s/it]

Clonazepam

100%|██████████| 14792/14792 [00:08<00:00, 1691.07it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3220.33it/s]

1
1

  5%|▍         | 59/1274 [22:35<7:28:03, 22.13s/it]

Promethazine

100%|██████████| 14792/14792 [00:09<00:00, 1559.38it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3124.40it/s]
  5%|▍         | 60/1274 [22:58<7:34:08, 22.45s/it]

1
1
1
1
1
1
1
1
Rosuvastatin

100%|██████████| 14792/14792 [00:09<00:00, 1609.04it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3236.45it/s]
  5%|▍         | 61/1274 [23:21<7:36:48, 22.60s/it]

Benzocaine

100%|██████████| 14792/14792 [00:08<00:00, 1830.65it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3353.64it/s]
  5%|▍         | 62/1274 [23:42<7:24:15, 21.99s/it]

1
1
1
Leflunomide

100%|██████████| 14792/14792 [00:08<00:00, 1726.97it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3266.82it/s]
  5%|▍         | 63/1274 [24:03<7:21:49, 21.89s/it]

1
Fluvastatin

100%|██████████| 14792/14792 [00:08<00:00, 1667.30it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2740.98it/s]

1
1
1
1

  5%|▌         | 64/1274 [24:28<7:39:04, 22.76s/it]

1
1
Fluvastatin

100%|██████████| 14792/14792 [00:08<00:00, 1657.35it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3370.06it/s]
  5%|▌         | 65/1274 [24:50<7:35:15, 22.59s/it]

Fluvastatin

100%|██████████| 14792/14792 [00:09<00:00, 1637.60it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3125.60it/s]

1
1
1
1

  5%|▌         | 66/1274 [25:14<7:40:29, 22.87s/it]

1
1
Fluvastatin

100%|██████████| 14792/14792 [00:08<00:00, 1657.58it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2826.92it/s]

1
1
1
1

  5%|▌         | 67/1274 [25:38<7:50:16, 23.38s/it]

1
1
Fluvastatin

100%|██████████| 14792/14792 [00:09<00:00, 1587.66it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3357.98it/s]

1
1
1
1

  5%|▌         | 68/1274 [26:01<7:46:21, 23.20s/it]

1
1
Aminobenzoic acid

100%|██████████| 14792/14792 [00:08<00:00, 1798.76it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3289.24it/s]
  5%|▌         | 69/1274 [26:23<7:35:23, 22.68s/it]

1
Benzocaine

100%|██████████| 14792/14792 [00:08<00:00, 1737.00it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3354.03it/s]
  5%|▌         | 70/1274 [26:44<7:26:35, 22.26s/it]

1
Promethazine

100%|██████████| 14792/14792 [00:09<00:00, 1531.30it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3126.61it/s]
  6%|▌         | 71/1274 [27:07<7:31:19, 22.51s/it]

1
Benzocaine

100%|██████████| 14792/14792 [00:08<00:00, 1801.85it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3194.61it/s]
  6%|▌         | 72/1274 [27:29<7:24:18, 22.18s/it]

1
Pilocarpine

100%|██████████| 14792/14792 [00:08<00:00, 1842.94it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3224.54it/s]
  6%|▌         | 73/1274 [27:50<7:17:32, 21.86s/it]

1
1
1
1
Pilocarpine

100%|██████████| 14792/14792 [00:08<00:00, 1797.83it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3413.07it/s]
  6%|▌         | 74/1274 [28:10<7:09:16, 21.46s/it]

1
1
Pilocarpine

100%|██████████| 14792/14792 [00:08<00:00, 1750.73it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3352.25it/s]
  6%|▌         | 75/1274 [28:32<7:08:20, 21.43s/it]

1
1
Atorvastatin

100%|██████████| 14792/14792 [00:09<00:00, 1547.47it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3111.78it/s]

1
1
1

  6%|▌         | 76/1274 [28:56<7:26:02, 22.34s/it]

Atorvastatin

100%|██████████| 14792/14792 [00:09<00:00, 1554.87it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3200.46it/s]

1
1
1
1
1
1

  6%|▌         | 77/1274 [29:20<7:36:22, 22.88s/it]

1
Atorvastatin

100%|██████████| 14792/14792 [00:09<00:00, 1604.98it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2879.86it/s]

1
1
1
1
1

  6%|▌         | 78/1274 [29:45<7:49:38, 23.56s/it]

1
Bupropion

100%|██████████| 14792/14792 [00:08<00:00, 1829.66it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3214.01it/s]
  6%|▌         | 79/1274 [30:06<7:34:46, 22.83s/it]

1
1
1
1
1
1
1
Bupropion

100%|██████████| 14792/14792 [00:08<00:00, 1821.10it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3257.16it/s]
  6%|▋         | 80/1274 [30:28<7:25:29, 22.39s/it]

1
1
1
1
Aripiprazole

100%|██████████| 14792/14792 [00:09<00:00, 1510.16it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3176.89it/s]

1

  6%|▋         | 81/1274 [30:52<7:33:19, 22.80s/it]

1
Clarithromycin

100%|██████████| 14792/14792 [00:09<00:00, 1495.62it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2920.35it/s]

1
1
1
1
1
1
1
1
1
1
1
1

  6%|▋         | 82/1274 [31:17<7:50:17, 23.67s/it]

Halofantrine

100%|██████████| 14792/14792 [00:09<00:00, 1538.21it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2912.93it/s]
  7%|▋         | 83/1274 [31:42<7:54:28, 23.90s/it]

Anastrozole

100%|██████████| 14792/14792 [00:08<00:00, 1678.05it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3074.32it/s]
  7%|▋         | 84/1274 [32:04<7:45:26, 23.47s/it]

Anastrozole

100%|██████████| 14792/14792 [00:08<00:00, 1721.88it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2937.64it/s]
  7%|▋         | 85/1274 [32:27<7:41:26, 23.29s/it]

Anastrozole

100%|██████████| 14792/14792 [00:08<00:00, 1701.97it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3278.33it/s]
  7%|▋         | 86/1274 [32:48<7:30:30, 22.75s/it]

Anastrozole

100%|██████████| 14792/14792 [00:08<00:00, 1778.65it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3204.57it/s]
  7%|▋         | 87/1274 [33:10<7:21:16, 22.31s/it]

1
1
1
Estazolam

100%|██████████| 14792/14792 [00:09<00:00, 1548.79it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3227.28it/s]
  7%|▋         | 88/1274 [33:33<7:24:55, 22.51s/it]

1
Clarithromycin

100%|██████████| 14792/14792 [00:10<00:00, 1449.93it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2828.57it/s]

1
1
1
1
1
1
1
1

  7%|▋         | 89/1274 [33:59<7:48:23, 23.72s/it]

Levetiracetam

100%|██████████| 14792/14792 [00:08<00:00, 1802.55it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3330.16it/s]

1
1
1
1
1
1
1
1
1
1
1
1

  7%|▋         | 90/1274 [34:20<7:32:54, 22.95s/it]

Budesonide

100%|██████████| 14792/14792 [00:12<00:00, 1225.28it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2999.24it/s]
  7%|▋         | 91/1274 [34:47<7:54:17, 24.06s/it]

1
Zopiclone

100%|██████████| 14792/14792 [00:09<00:00, 1575.86it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3301.60it/s]
  7%|▋         | 92/1274 [35:09<7:43:28, 23.53s/it]

1
1
Zopiclone

100%|██████████| 14792/14792 [00:09<00:00, 1604.23it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3177.15it/s]
  7%|▋         | 93/1274 [35:32<7:38:51, 23.31s/it]

1
Zopiclone

100%|██████████| 14792/14792 [00:09<00:00, 1584.43it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3129.26it/s]

1
1
1
1

  7%|▋         | 94/1274 [35:55<7:36:45, 23.22s/it]

Zopiclone

100%|██████████| 14792/14792 [00:09<00:00, 1614.36it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3266.22it/s]
  7%|▋         | 95/1274 [36:18<7:31:20, 22.97s/it]

1
Captopril

100%|██████████| 14792/14792 [00:08<00:00, 1772.05it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3244.28it/s]
  8%|▊         | 96/1274 [36:39<7:21:56, 22.51s/it]

Flecainide

100%|██████████| 14792/14792 [00:08<00:00, 1672.42it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2967.22it/s]
  8%|▊         | 97/1274 [37:02<7:25:22, 22.70s/it]

1
Oxymorphone

100%|██████████| 14792/14792 [00:12<00:00, 1141.68it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3159.44it/s]
  8%|▊         | 98/1274 [37:29<7:48:38, 23.91s/it]

Dantrolene

100%|██████████| 14792/14792 [00:08<00:00, 1731.06it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3006.03it/s]

1
1
1

  8%|▊         | 99/1274 [37:51<7:40:17, 23.50s/it]

Budesonide

100%|██████████| 14792/14792 [00:11<00:00, 1306.34it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3069.19it/s]

1
1
1

  8%|▊         | 100/1274 [38:17<7:52:05, 24.13s/it]

Oxymorphone

100%|██████████| 14792/14792 [00:11<00:00, 1237.21it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3048.70it/s]

1
1
1

  8%|▊         | 101/1274 [38:43<8:03:06, 24.71s/it]

1
1
Metoclopramide

100%|██████████| 14792/14792 [00:08<00:00, 1737.03it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3372.89it/s]
  8%|▊         | 102/1274 [39:05<7:43:21, 23.72s/it]

Aripiprazole

100%|██████████| 14792/14792 [00:09<00:00, 1541.83it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3223.45it/s]
  8%|▊         | 103/1274 [39:27<7:38:39, 23.50s/it]

1
Aripiprazole

100%|██████████| 14792/14792 [00:09<00:00, 1566.05it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3051.33it/s]
  8%|▊         | 104/1274 [39:51<7:39:42, 23.57s/it]

1
Levodopa

100%|██████████| 14792/14792 [00:08<00:00, 1702.97it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3347.75it/s]

1

  8%|▊         | 105/1274 [40:13<7:29:10, 23.05s/it]

Levodopa

100%|██████████| 14792/14792 [00:07<00:00, 1859.02it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3479.64it/s]

1

  8%|▊         | 106/1274 [40:34<7:14:16, 22.31s/it]

1
Dexamethasone

100%|██████████| 14792/14792 [00:10<00:00, 1371.28it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3266.70it/s]

1
1
1

  8%|▊         | 107/1274 [40:58<7:26:36, 22.96s/it]

Dexamethasone

100%|██████████| 14792/14792 [00:10<00:00, 1454.22it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3053.23it/s]

1
1
1
1
1
1
1
1
1

  8%|▊         | 108/1274 [41:23<7:34:37, 23.39s/it]

1
1
1
Dexamethasone

100%|██████████| 14792/14792 [00:10<00:00, 1357.32it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3250.38it/s]

1
1
1
1
1
1
1
1
1

  9%|▊         | 109/1274 [41:47<7:42:01, 23.80s/it]

1
1
1
Saquinavir

100%|██████████| 14792/14792 [00:10<00:00, 1391.97it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2874.91it/s]

1
1
1
1
1
1
1
1
1
1
1
1

  9%|▊         | 110/1274 [42:15<8:03:00, 24.90s/it]

Budesonide

100%|██████████| 14792/14792 [00:11<00:00, 1287.04it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2913.89it/s]

1
1
1
1
1
1
1
1
1
1
1
1

  9%|▊         | 111/1274 [42:41<8:12:28, 25.41s/it]

Saquinavir

100%|██████████| 14792/14792 [00:10<00:00, 1439.66it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2842.09it/s]

1
1
1
1
1
1
1
1
1
1
1
1

  9%|▉         | 112/1274 [43:09<8:22:29, 25.95s/it]

Saquinavir

100%|██████████| 14792/14792 [00:10<00:00, 1437.67it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2940.88it/s]

1
1
1

  9%|▉         | 113/1274 [43:35<8:26:16, 26.16s/it]

Saquinavir

100%|██████████| 14792/14792 [00:10<00:00, 1440.16it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2849.24it/s]
  9%|▉         | 114/1274 [44:02<8:28:24, 26.30s/it]

Quetiapine

100%|██████████| 14792/14792 [00:09<00:00, 1497.71it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2783.63it/s]
  9%|▉         | 115/1274 [44:27<8:21:42, 25.97s/it]

1
Quetiapine

100%|██████████| 14792/14792 [00:10<00:00, 1478.37it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3025.51it/s]

1
1
1
1
1

  9%|▉         | 116/1274 [44:51<8:11:53, 25.49s/it]

1
Quetiapine

100%|██████████| 14792/14792 [00:09<00:00, 1531.51it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3071.83it/s]
  9%|▉         | 117/1274 [45:15<8:01:35, 24.97s/it]

Budesonide

100%|██████████| 14792/14792 [00:11<00:00, 1267.29it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3232.17it/s]

1
1
1
1
1
1
1
1
1
1
1
1

  9%|▉         | 118/1274 [45:41<8:04:18, 25.14s/it]

Oxymorphone

100%|██████████| 14792/14792 [00:12<00:00, 1212.75it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3201.58it/s]
  9%|▉         | 119/1274 [46:06<8:06:45, 25.29s/it]

Oxymorphone

100%|██████████| 14792/14792 [00:12<00:00, 1219.85it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2948.73it/s]

1
1
1

  9%|▉         | 120/1274 [46:33<8:15:08, 25.74s/it]

1
1
1
1
Bupropion

100%|██████████| 14792/14792 [00:08<00:00, 1802.52it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3061.10it/s]

1
1
1
1
1

  9%|▉         | 121/1274 [46:55<7:53:07, 24.62s/it]

1
Itraconazole

100%|██████████| 14792/14792 [00:10<00:00, 1418.65it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2908.30it/s]

1
1
1
1
1
1
1
1
1
1
1
1

 10%|▉         | 122/1274 [47:21<7:58:59, 24.95s/it]

Orphenadrine

100%|██████████| 14792/14792 [00:08<00:00, 1736.11it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3181.70it/s]

1
1
1
1
1
1
1
1

 10%|▉         | 123/1274 [47:43<7:43:17, 24.15s/it]

Moclobemide

100%|██████████| 14792/14792 [00:08<00:00, 1714.36it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3226.76it/s]
 10%|▉         | 124/1274 [48:05<7:28:59, 23.43s/it]

1
Moclobemide

100%|██████████| 14792/14792 [00:08<00:00, 1752.65it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3052.85it/s]
 10%|▉         | 125/1274 [48:27<7:21:29, 23.05s/it]

Moclobemide

100%|██████████| 14792/14792 [00:08<00:00, 1708.30it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3151.30it/s]
 10%|▉         | 126/1274 [48:49<7:15:08, 22.74s/it]

1
1
Moclobemide

100%|██████████| 14792/14792 [00:08<00:00, 1740.86it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3125.49it/s]
 10%|▉         | 127/1274 [49:11<7:10:57, 22.54s/it]

1
1
1
1
1
1
Procarbazine

100%|██████████| 14792/14792 [00:08<00:00, 1753.48it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3129.15it/s]
 10%|█         | 128/1274 [49:33<7:06:27, 22.33s/it]

Procarbazine

100%|██████████| 14792/14792 [00:08<00:00, 1807.83it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3104.53it/s]
 10%|█         | 129/1274 [49:55<7:02:45, 22.15s/it]

Terazosin

100%|██████████| 14792/14792 [00:09<00:00, 1549.31it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3141.02it/s]
 10%|█         | 130/1274 [50:18<7:09:15, 22.51s/it]

Phenobarbital

100%|██████████| 14792/14792 [00:08<00:00, 1762.39it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3299.09it/s]

1
1
1
1

 10%|█         | 131/1274 [50:39<7:02:28, 22.18s/it]

1
1
Terazosin

100%|██████████| 14792/14792 [00:09<00:00, 1522.27it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2878.40it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

 10%|█         | 132/1274 [51:04<7:15:40, 22.89s/it]

Terazosin

100%|██████████| 14792/14792 [00:09<00:00, 1580.20it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3245.90it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

 10%|█         | 133/1274 [51:27<7:13:46, 22.81s/it]

Bupropion

100%|██████████| 14792/14792 [00:08<00:00, 1788.72it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3226.75it/s]
 11%|█         | 134/1274 [51:48<7:06:21, 22.44s/it]

1
1
1
1
1
1
1
Bupropion

100%|██████████| 14792/14792 [00:08<00:00, 1785.98it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3320.72it/s]
 11%|█         | 135/1274 [52:09<6:58:36, 22.05s/it]

1
1
1
1
1
1
1
Bupropion

100%|██████████| 14792/14792 [00:08<00:00, 1782.39it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3273.69it/s]
 11%|█         | 136/1274 [52:31<6:54:15, 21.84s/it]

1
1
1
1
1
1
1
Bupropion

100%|██████████| 14792/14792 [00:08<00:00, 1775.38it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3217.95it/s]

1
1
1
1
1

 11%|█         | 137/1274 [52:52<6:51:02, 21.69s/it]

1
Bupropion

100%|██████████| 14792/14792 [00:08<00:00, 1775.12it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3352.78it/s]
 11%|█         | 138/1274 [53:13<6:47:30, 21.52s/it]

1
1
1
Orphenadrine

100%|██████████| 14792/14792 [00:08<00:00, 1762.04it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3391.34it/s]
 11%|█         | 139/1274 [53:34<6:44:43, 21.40s/it]

Escitalopram

100%|██████████| 14792/14792 [00:09<00:00, 1581.82it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3113.05it/s]

1
1
1
1
1
1
1
1

 11%|█         | 140/1274 [53:57<6:54:00, 21.91s/it]

Oxymorphone

100%|██████████| 14792/14792 [00:12<00:00, 1224.46it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3341.43it/s]
 11%|█         | 141/1274 [54:23<7:12:20, 22.90s/it]

1
1
Naloxone

100%|██████████| 14792/14792 [00:12<00:00, 1215.81it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3155.76it/s]

1
1
1

 11%|█         | 142/1274 [54:49<7:29:22, 23.82s/it]

1
1
Oxymorphone

100%|██████████| 14792/14792 [00:12<00:00, 1214.65it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3455.97it/s]
 11%|█         | 143/1274 [55:13<7:34:53, 24.13s/it]

1
1
Oxymorphone

100%|██████████| 14792/14792 [00:12<00:00, 1224.86it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3094.29it/s]

1
1
1
1

 11%|█▏        | 144/1274 [55:40<7:46:06, 24.75s/it]

Oxymorphone

100%|██████████| 14792/14792 [00:12<00:00, 1197.13it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3222.80it/s]
 11%|█▏        | 145/1274 [56:05<7:51:27, 25.06s/it]

1
Clindamycin

100%|██████████| 14792/14792 [00:09<00:00, 1620.52it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3294.37it/s]

1
1
1
1
1

 11%|█▏        | 146/1274 [56:28<7:37:17, 24.32s/it]

Clindamycin

100%|██████████| 14792/14792 [00:08<00:00, 1687.46it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3394.58it/s]

1
1

 12%|█▏        | 147/1274 [56:50<7:23:11, 23.60s/it]

1
1
Domperidone

100%|██████████| 14792/14792 [00:10<00:00, 1474.75it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3063.54it/s]
 12%|█▏        | 148/1274 [57:14<7:26:29, 23.79s/it]

Naloxone

100%|██████████| 14792/14792 [00:12<00:00, 1221.92it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3150.06it/s]

1
1
1

 12%|█▏        | 149/1274 [57:40<7:39:17, 24.50s/it]

1
Naloxone

100%|██████████| 14792/14792 [00:12<00:00, 1212.51it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3084.18it/s]
 12%|█▏        | 150/1274 [58:06<7:48:27, 25.01s/it]

Escitalopram

100%|██████████| 14792/14792 [00:08<00:00, 1736.79it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3361.05it/s]
 12%|█▏        | 151/1274 [58:28<7:27:59, 23.94s/it]

Propafenone

100%|██████████| 14792/14792 [00:09<00:00, 1636.44it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3107.39it/s]
 12%|█▏        | 152/1274 [58:51<7:23:55, 23.74s/it]

Propafenone

100%|██████████| 14792/14792 [00:08<00:00, 1646.47it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3082.61it/s]

1
1
1
1

 12%|█▏        | 153/1274 [59:14<7:20:38, 23.58s/it]

1
1
Propafenone

100%|██████████| 14792/14792 [00:08<00:00, 1685.44it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3155.58it/s]
 12%|█▏        | 154/1274 [59:37<7:14:18, 23.27s/it]

Propafenone

100%|██████████| 14792/14792 [00:08<00:00, 1664.04it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3197.19it/s]

1
1
1
1

 12%|█▏        | 155/1274 [1:00:00<7:10:47, 23.10s/it]

1
1
Propafenone

100%|██████████| 14792/14792 [00:08<00:00, 1706.65it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3146.76it/s]
 12%|█▏        | 156/1274 [1:00:22<7:08:04, 22.97s/it]

Propafenone

100%|██████████| 14792/14792 [00:08<00:00, 1647.54it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3310.74it/s]

1
1
1
1

 12%|█▏        | 157/1274 [1:00:45<7:03:22, 22.74s/it]

1
1
Escitalopram

100%|██████████| 14792/14792 [00:08<00:00, 1657.16it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3012.14it/s]

1
1

 12%|█▏        | 158/1274 [1:01:08<7:05:04, 22.85s/it]

Gatifloxacin

100%|██████████| 14792/14792 [00:09<00:00, 1631.13it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3206.01it/s]
 12%|█▏        | 159/1274 [1:01:30<7:01:21, 22.67s/it]

Melphalan

100%|██████████| 14792/14792 [00:08<00:00, 1762.83it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3425.92it/s]
 13%|█▎        | 160/1274 [1:01:51<6:51:01, 22.14s/it]

Melphalan

100%|██████████| 14792/14792 [00:08<00:00, 1731.46it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3298.38it/s]

1

 13%|█▎        | 161/1274 [1:02:12<6:48:05, 22.00s/it]

Acetylsalicylic acid

100%|██████████| 14792/14792 [00:08<00:00, 1797.28it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3324.28it/s]
 13%|█▎        | 162/1274 [1:02:34<6:43:34, 21.78s/it]

Fexofenadine

100%|██████████| 14792/14792 [00:09<00:00, 1564.60it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3104.39it/s]
 13%|█▎        | 163/1274 [1:02:57<6:53:53, 22.35s/it]

Felbamate

100%|██████████| 14792/14792 [00:08<00:00, 1778.55it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3251.11it/s]
 13%|█▎        | 164/1274 [1:03:19<6:48:25, 22.08s/it]

1
1
Felbamate

100%|██████████| 14792/14792 [00:08<00:00, 1795.95it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3486.89it/s]

1
1
1
1
1

 13%|█▎        | 165/1274 [1:03:39<6:39:58, 21.64s/it]

1
Felbamate

100%|██████████| 14792/14792 [00:08<00:00, 1766.66it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3494.53it/s]

1
1
1

 13%|█▎        | 166/1274 [1:04:00<6:34:57, 21.39s/it]

Acetylsalicylic acid

100%|██████████| 14792/14792 [00:08<00:00, 1798.04it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3436.46it/s]
 13%|█▎        | 167/1274 [1:04:21<6:31:52, 21.24s/it]

1
Acetylsalicylic acid

100%|██████████| 14792/14792 [00:08<00:00, 1786.35it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3203.53it/s]
 13%|█▎        | 168/1274 [1:04:43<6:34:07, 21.38s/it]

Acetylsalicylic acid

100%|██████████| 14792/14792 [00:08<00:00, 1832.37it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3332.22it/s]

1
1
1
1

 13%|█▎        | 169/1274 [1:05:04<6:32:49, 21.33s/it]

Salmeterol

100%|██████████| 14792/14792 [00:08<00:00, 1674.00it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2948.25it/s]
 13%|█▎        | 170/1274 [1:05:28<6:46:19, 22.08s/it]

Rizatriptan

100%|██████████| 14792/14792 [00:08<00:00, 1693.83it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3212.98it/s]
 13%|█▎        | 171/1274 [1:05:50<6:46:33, 22.12s/it]

Salmeterol

100%|██████████| 14792/14792 [00:08<00:00, 1687.82it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3206.89it/s]

1
1

 14%|█▎        | 172/1274 [1:06:13<6:48:04, 22.22s/it]

1
1
1
1
Oxymetazoline

100%|██████████| 14792/14792 [00:08<00:00, 1704.72it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3425.00it/s]
 14%|█▎        | 173/1274 [1:06:34<6:42:02, 21.91s/it]

1
Maprotiline

100%|██████████| 14792/14792 [00:10<00:00, 1418.33it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3291.19it/s]

1
1
1

 14%|█▎        | 174/1274 [1:06:58<6:51:54, 22.47s/it]

1
1
1
Maprotiline

100%|██████████| 14792/14792 [00:10<00:00, 1444.04it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3323.29it/s]

1
1
1

 14%|█▎        | 175/1274 [1:07:21<6:55:07, 22.66s/it]

1
1
1
Maprotiline

100%|██████████| 14792/14792 [00:10<00:00, 1433.14it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3050.08it/s]

1
1
1
1
1
1
1
1
1

 14%|█▍        | 176/1274 [1:07:45<7:03:31, 23.14s/it]

Famotidine

100%|██████████| 14792/14792 [00:08<00:00, 1715.23it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2924.02it/s]
 14%|█▍        | 177/1274 [1:08:08<7:01:28, 23.05s/it]

1
1
1
Cyclobenzaprine

100%|██████████| 14792/14792 [00:09<00:00, 1573.96it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3330.17it/s]
 14%|█▍        | 178/1274 [1:08:30<6:56:39, 22.81s/it]

1
1
1
1
1
1
1
1
Rizatriptan

100%|██████████| 14792/14792 [00:08<00:00, 1682.27it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3224.31it/s]

1
1
1
1
1

 14%|█▍        | 179/1274 [1:08:52<6:52:04, 22.58s/it]

1
Rizatriptan

100%|██████████| 14792/14792 [00:08<00:00, 1682.71it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3312.51it/s]
 14%|█▍        | 180/1274 [1:09:14<6:48:12, 22.39s/it]

1
1
Buprenorphine

100%|██████████| 14792/14792 [00:15<00:00, 945.92it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2890.67it/s]

1
1
1
1

 14%|█▍        | 181/1274 [1:09:45<7:33:53, 24.92s/it]

Methylprednisolone

100%|██████████| 14792/14792 [00:10<00:00, 1449.74it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3030.36it/s]

1
1
1

 14%|█▍        | 182/1274 [1:10:09<7:32:13, 24.85s/it]

Methyldopa

100%|██████████| 14792/14792 [00:08<00:00, 1675.87it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3083.48it/s]

1
1
1

 14%|█▍        | 183/1274 [1:10:33<7:21:53, 24.30s/it]

1
Methyldopa

100%|██████████| 14792/14792 [00:08<00:00, 1819.39it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3463.67it/s]
 14%|█▍        | 184/1274 [1:10:53<7:01:16, 23.19s/it]

Zaleplon

100%|██████████| 14792/14792 [00:09<00:00, 1575.27it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3110.03it/s]
 15%|█▍        | 185/1274 [1:11:16<7:01:01, 23.20s/it]

Pindolol

100%|██████████| 14792/14792 [00:09<00:00, 1600.90it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3330.43it/s]
 15%|█▍        | 186/1274 [1:11:39<6:55:32, 22.92s/it]

1
1
Pindolol

100%|██████████| 14792/14792 [00:08<00:00, 1741.76it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3339.02it/s]

1
1
1

 15%|█▍        | 187/1274 [1:12:00<6:46:52, 22.46s/it]

Methylprednisolone

100%|██████████| 14792/14792 [00:10<00:00, 1395.43it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3190.75it/s]

1
1
1

 15%|█▍        | 188/1274 [1:12:25<6:58:16, 23.11s/it]

Methylprednisolone

100%|██████████| 14792/14792 [00:10<00:00, 1443.53it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3018.75it/s]

1
1
1

 15%|█▍        | 189/1274 [1:12:50<7:07:39, 23.65s/it]

Methylprednisolone

100%|██████████| 14792/14792 [00:10<00:00, 1468.26it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2915.13it/s]

1

 15%|█▍        | 190/1274 [1:13:14<7:13:43, 24.01s/it]

Rizatriptan

100%|██████████| 14792/14792 [00:08<00:00, 1702.16it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3178.59it/s]

1
1
1
1
1

 15%|█▍        | 191/1274 [1:13:36<7:02:43, 23.42s/it]

1
Methylprednisolone

100%|██████████| 14792/14792 [00:10<00:00, 1429.94it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3342.15it/s]

1

 15%|█▌        | 192/1274 [1:14:00<7:02:40, 23.44s/it]

1
Methylprednisolone

100%|██████████| 14792/14792 [00:10<00:00, 1436.98it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3224.62it/s]

1
1
1

 15%|█▌        | 193/1274 [1:14:24<7:05:45, 23.63s/it]

Norgestrel

100%|██████████| 14792/14792 [00:10<00:00, 1408.58it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3069.85it/s]

1
1

 15%|█▌        | 194/1274 [1:14:49<7:10:46, 23.93s/it]

Norgestimate

100%|██████████| 14792/14792 [00:10<00:00, 1401.84it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3315.51it/s]

1
1
1
1

 15%|█▌        | 195/1274 [1:15:13<7:10:17, 23.93s/it]

Hydromorphone

100%|██████████| 14792/14792 [00:12<00:00, 1211.73it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3206.02it/s]

1
1
1

 15%|█▌        | 196/1274 [1:15:38<7:19:29, 24.46s/it]

1
Hydromorphone

100%|██████████| 14792/14792 [00:12<00:00, 1198.04it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2852.83it/s]

1
1
1

 15%|█▌        | 197/1274 [1:16:06<7:34:31, 25.32s/it]

1
1
Hydromorphone

100%|██████████| 14792/14792 [00:12<00:00, 1195.91it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2790.86it/s]

1
1
1

 16%|█▌        | 198/1274 [1:16:33<7:44:44, 25.91s/it]

1
1
Cyclobenzaprine

100%|██████████| 14792/14792 [00:09<00:00, 1525.19it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2968.21it/s]
 16%|█▌        | 199/1274 [1:16:57<7:34:13, 25.35s/it]

Buprenorphine

100%|██████████| 14792/14792 [00:15<00:00, 973.94it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3122.65it/s]
 16%|█▌        | 200/1274 [1:17:26<7:51:53, 26.36s/it]

Thalidomide

100%|██████████| 14792/14792 [00:08<00:00, 1680.66it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3133.81it/s]

1
1
1
1

 16%|█▌        | 201/1274 [1:17:48<7:30:31, 25.19s/it]

1
1
Flupentixol

100%|██████████| 14792/14792 [00:10<00:00, 1411.80it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3099.79it/s]

1

 16%|█▌        | 202/1274 [1:18:13<7:27:33, 25.05s/it]

Granisetron

100%|██████████| 14792/14792 [00:09<00:00, 1583.43it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2938.22it/s]

1
1
1
1

 16%|█▌        | 203/1274 [1:18:37<7:20:24, 24.67s/it]

Quinapril

100%|██████████| 14792/14792 [00:09<00:00, 1596.45it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3024.07it/s]

1
1
1
1

 16%|█▌        | 204/1274 [1:19:01<7:16:29, 24.48s/it]

Quinapril

100%|██████████| 14792/14792 [00:09<00:00, 1631.18it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3020.23it/s]
 16%|█▌        | 205/1274 [1:19:25<7:13:09, 24.31s/it]

Emtricitabine

100%|██████████| 14792/14792 [00:08<00:00, 1724.99it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3323.56it/s]
 16%|█▌        | 206/1274 [1:19:46<6:56:55, 23.42s/it]

1
1
1
Emtricitabine

100%|██████████| 14792/14792 [00:08<00:00, 1810.09it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3471.84it/s]
 16%|█▌        | 207/1274 [1:20:06<6:40:45, 22.54s/it]

Emtricitabine

100%|██████████| 14792/14792 [00:08<00:00, 1736.80it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3269.48it/s]
 16%|█▋        | 208/1274 [1:20:28<6:35:58, 22.29s/it]

1
1
1
1
1
Emtricitabine

100%|██████████| 14792/14792 [00:08<00:00, 1720.70it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3251.98it/s]
 16%|█▋        | 209/1274 [1:20:50<6:32:29, 22.11s/it]

1
1
1
1
1
Flupentixol

100%|██████████| 14792/14792 [00:09<00:00, 1508.15it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2905.25it/s]

1

 16%|█▋        | 210/1274 [1:21:14<6:44:50, 22.83s/it]

Triazolam

100%|██████████| 14792/14792 [00:09<00:00, 1578.37it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3111.62it/s]
 17%|█▋        | 211/1274 [1:21:37<6:44:50, 22.85s/it]

1
Flupentixol

100%|██████████| 14792/14792 [00:09<00:00, 1522.62it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3137.99it/s]
 17%|█▋        | 212/1274 [1:22:01<6:49:41, 23.15s/it]

1
Guaifenesin

100%|██████████| 14792/14792 [00:08<00:00, 1821.09it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3203.51it/s]

1

 17%|█▋        | 213/1274 [1:22:23<6:41:12, 22.69s/it]

1
1
Terbutaline

100%|██████████| 14792/14792 [00:08<00:00, 1800.87it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3081.25it/s]
 17%|█▋        | 214/1274 [1:22:44<6:36:28, 22.44s/it]

1
1
1
1
Terbutaline

100%|██████████| 14792/14792 [00:08<00:00, 1761.80it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3079.33it/s]
 17%|█▋        | 215/1274 [1:23:07<6:35:04, 22.38s/it]

1
1
1
1
Benzonatate

100%|██████████| 14792/14792 [00:09<00:00, 1582.31it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2998.94it/s]

1

 17%|█▋        | 216/1274 [1:23:30<6:41:24, 22.76s/it]

Benzphetamine

100%|██████████| 14792/14792 [00:08<00:00, 1754.02it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2892.26it/s]
 17%|█▋        | 217/1274 [1:23:53<6:42:31, 22.85s/it]

Benzphetamine

100%|██████████| 14792/14792 [00:08<00:00, 1731.89it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3456.42it/s]
 17%|█▋        | 218/1274 [1:24:14<6:31:58, 22.27s/it]

Granisetron

100%|██████████| 14792/14792 [00:09<00:00, 1589.14it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3212.73it/s]

1
1
1
1

 17%|█▋        | 219/1274 [1:24:37<6:34:50, 22.46s/it]

1
1
Triazolam

100%|██████████| 14792/14792 [00:09<00:00, 1553.26it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3238.08it/s]

1

 17%|█▋        | 220/1274 [1:25:00<6:36:53, 22.59s/it]

1
Buprenorphine

100%|██████████| 14792/14792 [00:14<00:00, 1003.00it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2954.74it/s]
 17%|█▋        | 221/1274 [1:25:29<7:11:58, 24.61s/it]

Repaglinide

100%|██████████| 14792/14792 [00:09<00:00, 1590.70it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3277.92it/s]

1
1
1
1
1
1
1
1
1

 17%|█▋        | 222/1274 [1:25:52<7:02:02, 24.07s/it]

1
1
1
1
Ketotifen

100%|██████████| 14792/14792 [00:09<00:00, 1518.96it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3242.04it/s]

1
1
1
1

 18%|█▊        | 223/1274 [1:26:15<6:56:40, 23.79s/it]

Ketotifen

100%|██████████| 14792/14792 [00:09<00:00, 1510.27it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3233.54it/s]

1
1
1

 18%|█▊        | 224/1274 [1:26:39<6:52:44, 23.59s/it]

Ketotifen

100%|██████████| 14792/14792 [00:09<00:00, 1514.96it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3270.13it/s]
 18%|█▊        | 225/1274 [1:27:02<6:50:41, 23.49s/it]

Almotriptan

100%|██████████| 14792/14792 [00:09<00:00, 1538.76it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3322.60it/s]

1
1
1
1
1
1
1
1

 18%|█▊        | 226/1274 [1:27:24<6:44:50, 23.18s/it]

Almotriptan

100%|██████████| 14792/14792 [00:08<00:00, 1675.25it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3106.11it/s]

1
1

 18%|█▊        | 227/1274 [1:27:47<6:41:08, 22.99s/it]

Metronidazole

100%|██████████| 14792/14792 [00:08<00:00, 1762.19it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3076.90it/s]
 18%|█▊        | 228/1274 [1:28:09<6:36:20, 22.73s/it]

1
1
Repaglinide

100%|██████████| 14792/14792 [00:09<00:00, 1598.89it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3126.43it/s]
 18%|█▊        | 229/1274 [1:28:32<6:40:13, 22.98s/it]

Zonisamide

100%|██████████| 14792/14792 [00:08<00:00, 1700.88it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3222.04it/s]
 18%|█▊        | 230/1274 [1:28:54<6:34:44, 22.69s/it]

Ethanol

100%|██████████| 14792/14792 [00:07<00:00, 1928.25it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3580.98it/s]
 18%|█▊        | 231/1274 [1:29:14<6:18:47, 21.79s/it]

1
1
1
1
1
1
1
1
1
Zonisamide

100%|██████████| 14792/14792 [00:09<00:00, 1642.42it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3312.64it/s]
 18%|█▊        | 232/1274 [1:29:36<6:18:59, 21.82s/it]

Quinidine

100%|██████████| 14792/14792 [00:09<00:00, 1599.59it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3272.11it/s]
 18%|█▊        | 233/1274 [1:29:59<6:23:44, 22.12s/it]

1
1
Quinidine

100%|██████████| 14792/14792 [00:09<00:00, 1634.65it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3177.74it/s]
 18%|█▊        | 234/1274 [1:30:22<6:26:30, 22.30s/it]

1
Ondansetron

100%|██████████| 14792/14792 [00:09<00:00, 1567.99it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3341.83it/s]

1
1
1
1

 18%|█▊        | 235/1274 [1:30:44<6:26:59, 22.35s/it]

1
1
Ondansetron

100%|██████████| 14792/14792 [00:09<00:00, 1501.69it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3361.17it/s]

1
1
1
1

 19%|█▊        | 236/1274 [1:31:07<6:27:35, 22.40s/it]

1
1
Ondansetron

100%|██████████| 14792/14792 [00:09<00:00, 1488.07it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3075.45it/s]

1
1
1
1

 19%|█▊        | 237/1274 [1:31:30<6:34:56, 22.85s/it]

1
1
Ethanol

100%|██████████| 14792/14792 [00:07<00:00, 1889.58it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3454.39it/s]
 19%|█▊        | 238/1274 [1:31:51<6:21:16, 22.08s/it]

1
1
1
Methyldopa

100%|██████████| 14792/14792 [00:08<00:00, 1803.15it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3550.47it/s]
 19%|█▉        | 239/1274 [1:32:11<6:12:15, 21.58s/it]

Methyldopa

100%|██████████| 14792/14792 [00:08<00:00, 1776.76it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2988.81it/s]
 19%|█▉        | 240/1274 [1:32:34<6:16:45, 21.86s/it]

1
Ezetimibe

100%|██████████| 14792/14792 [00:08<00:00, 1694.33it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2853.28it/s]

1
1
1

 19%|█▉        | 241/1274 [1:32:58<6:28:47, 22.58s/it]

1
Ketoconazole

100%|██████████| 14792/14792 [00:09<00:00, 1572.55it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3210.54it/s]
 19%|█▉        | 242/1274 [1:33:21<6:31:54, 22.79s/it]

Irbesartan

100%|██████████| 14792/14792 [00:09<00:00, 1613.68it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3154.49it/s]

1
1
1
1
1
1
1
1
1

 19%|█▉        | 243/1274 [1:33:44<6:32:43, 22.85s/it]

1
1
1
Irbesartan

100%|██████████| 14792/14792 [00:09<00:00, 1575.80it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3164.33it/s]

1
1
1
1
1
1
1
1
1

 19%|█▉        | 244/1274 [1:34:08<6:34:59, 23.01s/it]

1
1
1
Irbesartan

100%|██████████| 14792/14792 [00:09<00:00, 1560.48it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3305.69it/s]
 19%|█▉        | 245/1274 [1:34:30<6:33:06, 22.92s/it]

1
Ketoconazole

100%|██████████| 14792/14792 [00:09<00:00, 1552.67it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3022.62it/s]
 19%|█▉        | 246/1274 [1:34:54<6:37:44, 23.21s/it]

1
Ketoconazole

100%|██████████| 14792/14792 [00:09<00:00, 1561.86it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3016.05it/s]

1

 19%|█▉        | 247/1274 [1:35:18<6:41:07, 23.43s/it]

1
Ketoconazole

100%|██████████| 14792/14792 [00:09<00:00, 1507.31it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3131.70it/s]

1
1
1
1

 19%|█▉        | 248/1274 [1:35:42<6:42:17, 23.53s/it]

1
1
Ketoconazole

100%|██████████| 14792/14792 [00:09<00:00, 1509.14it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3140.60it/s]
 20%|█▉        | 249/1274 [1:36:06<6:43:26, 23.62s/it]

Ketoconazole

100%|██████████| 14792/14792 [00:09<00:00, 1585.63it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2983.60it/s]
 20%|█▉        | 250/1274 [1:36:30<6:44:22, 23.69s/it]

1
Irbesartan

100%|██████████| 14792/14792 [00:09<00:00, 1543.46it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3037.52it/s]
 20%|█▉        | 251/1274 [1:36:54<6:45:17, 23.77s/it]

1
Mycophenolic acid

100%|██████████| 14792/14792 [00:09<00:00, 1619.00it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3346.63it/s]

1
1

 20%|█▉        | 252/1274 [1:37:16<6:38:39, 23.40s/it]

Mycophenolic acid

100%|██████████| 14792/14792 [00:09<00:00, 1618.84it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3377.45it/s]

1
1
1

 20%|█▉        | 253/1274 [1:37:38<6:31:14, 22.99s/it]

1
Mycophenolic acid

100%|██████████| 14792/14792 [00:08<00:00, 1695.77it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3294.06it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

 20%|█▉        | 254/1274 [1:38:00<6:25:29, 22.68s/it]

Felodipine

100%|██████████| 14792/14792 [00:08<00:00, 1667.51it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3057.61it/s]
 20%|██        | 255/1274 [1:38:23<6:25:32, 22.70s/it]

1
Isosorbide mononitrate

100%|██████████| 14792/14792 [00:08<00:00, 1764.63it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3363.31it/s]
 20%|██        | 256/1274 [1:38:44<6:16:30, 22.19s/it]

1
1
1
Isosorbide mononitrate

100%|██████████| 14792/14792 [00:08<00:00, 1733.37it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3089.95it/s]
 20%|██        | 257/1274 [1:39:06<6:15:46, 22.17s/it]

1
Isosorbide mononitrate

100%|██████████| 14792/14792 [00:08<00:00, 1773.43it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3369.56it/s]
 20%|██        | 258/1274 [1:39:27<6:09:10, 21.80s/it]

Irbesartan

100%|██████████| 14792/14792 [00:09<00:00, 1503.20it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3168.22it/s]

1
1
1
1
1
1
1
1
1

 20%|██        | 259/1274 [1:39:50<6:17:22, 22.31s/it]

1
1
1
Irbesartan

100%|██████████| 14792/14792 [00:09<00:00, 1553.46it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2940.29it/s]
 20%|██        | 260/1274 [1:40:14<6:25:09, 22.79s/it]

Ezetimibe

100%|██████████| 14792/14792 [00:08<00:00, 1645.74it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3141.16it/s]

1
1

 20%|██        | 261/1274 [1:40:37<6:26:28, 22.89s/it]

Thalidomide

100%|██████████| 14792/14792 [00:08<00:00, 1665.78it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3295.12it/s]

1
1
1
1
1
1
1
1
1
1
1

 21%|██        | 262/1274 [1:40:59<6:20:54, 22.58s/it]

1
1
Thalidomide

100%|██████████| 14792/14792 [00:09<00:00, 1617.06it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3469.67it/s]
 21%|██        | 263/1274 [1:41:21<6:15:00, 22.26s/it]

1
Thalidomide

100%|██████████| 14792/14792 [00:08<00:00, 1646.09it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3156.43it/s]

1
1
1

 21%|██        | 264/1274 [1:41:43<6:16:02, 22.34s/it]

1
Thalidomide

100%|██████████| 14792/14792 [00:08<00:00, 1674.81it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3211.15it/s]

1
1
1

 21%|██        | 265/1274 [1:42:06<6:15:05, 22.30s/it]

1
Thalidomide

100%|██████████| 14792/14792 [00:09<00:00, 1579.99it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3214.04it/s]

1
1
1
1

 21%|██        | 266/1274 [1:42:28<6:16:22, 22.40s/it]

1
1
Thalidomide

100%|██████████| 14792/14792 [00:08<00:00, 1693.11it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3430.66it/s]
 21%|██        | 267/1274 [1:42:49<6:10:12, 22.06s/it]

1
1
Thalidomide

100%|██████████| 14792/14792 [00:08<00:00, 1689.60it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3268.61it/s]
 21%|██        | 268/1274 [1:43:12<6:10:20, 22.09s/it]

Thalidomide

100%|██████████| 14792/14792 [00:08<00:00, 1688.05it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3311.18it/s]

1
1

 21%|██        | 269/1274 [1:43:33<6:08:54, 22.02s/it]

Selegiline

100%|██████████| 14792/14792 [00:08<00:00, 1805.51it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3334.39it/s]
 21%|██        | 270/1274 [1:43:54<6:02:29, 21.66s/it]

Mercaptopurine

100%|██████████| 14792/14792 [00:08<00:00, 1745.91it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3517.83it/s]
 21%|██▏       | 271/1274 [1:44:15<5:55:58, 21.29s/it]

Selegiline

100%|██████████| 14792/14792 [00:08<00:00, 1700.00it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3208.70it/s]
 21%|██▏       | 272/1274 [1:44:37<5:59:30, 21.53s/it]

1
1
1
1
Tolterodine

100%|██████████| 14792/14792 [00:08<00:00, 1701.22it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3276.27it/s]

1

 21%|██▏       | 273/1274 [1:44:59<6:02:09, 21.71s/it]

1
Tolterodine

100%|██████████| 14792/14792 [00:08<00:00, 1698.22it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3278.73it/s]
 22%|██▏       | 274/1274 [1:45:21<6:04:01, 21.84s/it]

Procainamide

100%|██████████| 14792/14792 [00:08<00:00, 1689.17it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3222.23it/s]
 22%|██▏       | 275/1274 [1:45:43<6:03:53, 21.86s/it]

Mercaptopurine

100%|██████████| 14792/14792 [00:08<00:00, 1753.60it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3320.38it/s]
 22%|██▏       | 276/1274 [1:46:04<6:00:12, 21.66s/it]

Mercaptopurine

100%|██████████| 14792/14792 [00:08<00:00, 1833.61it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3650.64it/s]
 22%|██▏       | 277/1274 [1:46:24<5:50:24, 21.09s/it]

1
Mercaptopurine

100%|██████████| 14792/14792 [00:08<00:00, 1708.28it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3236.44it/s]
 22%|██▏       | 278/1274 [1:46:46<5:53:44, 21.31s/it]

1
1
1
1
1
1
1
1
Guanfacine

100%|██████████| 14792/14792 [00:08<00:00, 1735.39it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3250.06it/s]
 22%|██▏       | 279/1274 [1:47:07<5:54:39, 21.39s/it]

1
1
1
1
1
1
Minocycline

100%|██████████| 14792/14792 [00:10<00:00, 1441.40it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3100.62it/s]

1
1
1
1
1
1

 22%|██▏       | 280/1274 [1:47:32<6:11:02, 22.40s/it]

1
Minocycline

100%|██████████| 14792/14792 [00:10<00:00, 1357.22it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3150.64it/s]

1
1
1
1
1
1
1
1

 22%|██▏       | 281/1274 [1:47:57<6:24:33, 23.24s/it]

Isotretinoin

100%|██████████| 14792/14792 [00:09<00:00, 1621.53it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3310.42it/s]
 22%|██▏       | 282/1274 [1:48:20<6:19:12, 22.94s/it]

1
Frovatriptan

100%|██████████| 14792/14792 [00:09<00:00, 1613.83it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3329.48it/s]
 22%|██▏       | 283/1274 [1:48:42<6:14:58, 22.70s/it]

Frovatriptan

100%|██████████| 14792/14792 [00:09<00:00, 1548.25it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3192.66it/s]
 22%|██▏       | 284/1274 [1:49:05<6:15:44, 22.77s/it]

Frovatriptan

100%|██████████| 14792/14792 [00:09<00:00, 1586.94it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3237.40it/s]
 22%|██▏       | 285/1274 [1:49:27<6:14:14, 22.70s/it]

1
Azathioprine

100%|██████████| 14792/14792 [00:08<00:00, 1739.31it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3353.95it/s]
 22%|██▏       | 286/1274 [1:49:48<6:05:12, 22.18s/it]

Dimenhydrinate

100%|██████████| 14792/14792 [00:05<00:00, 2631.62it/s]
100%|██████████| 34899/34899 [00:08<00:00, 4148.71it/s]
 23%|██▎       | 287/1274 [1:50:04<5:36:02, 20.43s/it]

Dimenhydrinate

100%|██████████| 14792/14792 [00:05<00:00, 2584.92it/s]
100%|██████████| 34899/34899 [00:08<00:00, 4130.86it/s]
 23%|██▎       | 288/1274 [1:50:21<5:15:34, 19.20s/it]

Isotretinoin

100%|██████████| 14792/14792 [00:08<00:00, 1716.98it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3392.64it/s]

1
1
1
1
1
1
1
1
1

 23%|██▎       | 289/1274 [1:50:42<5:26:00, 19.86s/it]

1
1
1
Ethinylestradiol

100%|██████████| 14792/14792 [00:10<00:00, 1422.95it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3282.28it/s]

1
1
1

 23%|██▎       | 290/1274 [1:51:06<5:45:29, 21.07s/it]

1
Minocycline

100%|██████████| 14792/14792 [00:10<00:00, 1368.84it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3053.04it/s]

1
1
1
1

 23%|██▎       | 291/1274 [1:51:32<6:07:55, 22.46s/it]

Ethinylestradiol

100%|██████████| 14792/14792 [00:10<00:00, 1438.96it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3126.03it/s]

1
1
1
1
1
1
1
1
1

 23%|██▎       | 292/1274 [1:51:56<6:16:28, 23.00s/it]

1
1
1
Ethinylestradiol

100%|██████████| 14792/14792 [00:10<00:00, 1469.93it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3038.64it/s]

1
1
1
1
1
1
1
1
1

 23%|██▎       | 293/1274 [1:52:20<6:22:59, 23.42s/it]

1
1
1
Ethinylestradiol

100%|██████████| 14792/14792 [00:10<00:00, 1405.51it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3136.56it/s]

1
1

 23%|██▎       | 294/1274 [1:52:45<6:26:46, 23.68s/it]

1
1
1
1
Ethinylestradiol

100%|██████████| 14792/14792 [00:10<00:00, 1400.40it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2953.15it/s]

1
1
1
1
1
1
1

 23%|██▎       | 295/1274 [1:53:10<6:34:25, 24.17s/it]

Ethinylestradiol

100%|██████████| 14792/14792 [00:10<00:00, 1435.54it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3259.80it/s]

1
1
1
1

 23%|██▎       | 296/1274 [1:53:34<6:32:16, 24.07s/it]

1
1
1
Ethinylestradiol

100%|██████████| 14792/14792 [00:10<00:00, 1435.59it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3041.28it/s]

1
1
1
1

 23%|██▎       | 297/1274 [1:53:59<6:35:22, 24.28s/it]

Ezetimibe

100%|██████████| 14792/14792 [00:09<00:00, 1606.46it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2929.59it/s]

1
1

 23%|██▎       | 298/1274 [1:54:23<6:34:24, 24.25s/it]

Salbutamol

100%|██████████| 14792/14792 [00:08<00:00, 1762.31it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3414.91it/s]

1
1
1

 23%|██▎       | 299/1274 [1:54:44<6:19:11, 23.33s/it]

1
Hydroxyurea

100%|██████████| 14792/14792 [00:08<00:00, 1779.94it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3244.61it/s]
 24%|██▎       | 300/1274 [1:55:05<6:08:50, 22.72s/it]

1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
Hydroxyurea

100%|██████████| 14792/14792 [00:07<00:00, 1860.84it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3399.75it/s]
 24%|██▎       | 301/1274 [1:55:26<5:57:22, 22.04s/it]

Hydroxyurea

100%|██████████| 14792/14792 [00:07<00:00, 1870.26it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3630.44it/s]
 24%|██▎       | 302/1274 [1:55:45<5:45:46, 21.34s/it]

Glyburide

100%|██████████| 14792/14792 [00:09<00:00, 1577.76it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3189.73it/s]

1
1
1
1
1
1
1
1
1

 24%|██▍       | 303/1274 [1:56:09<5:54:30, 21.91s/it]

1
1
1
Glyburide

100%|██████████| 14792/14792 [00:09<00:00, 1614.63it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3248.15it/s]

1
1
1
1
1
1
1
1
1

 24%|██▍       | 304/1274 [1:56:31<5:57:54, 22.14s/it]

1
1
1
Glyburide

100%|██████████| 14792/14792 [00:09<00:00, 1590.32it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3035.27it/s]

1
1
1
1

 24%|██▍       | 305/1274 [1:56:55<6:04:17, 22.56s/it]

1
Glyburide

100%|██████████| 14792/14792 [00:09<00:00, 1593.08it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3256.31it/s]

1
1
1
1

 24%|██▍       | 306/1274 [1:57:18<6:05:25, 22.65s/it]

1
Glyburide

100%|██████████| 14792/14792 [00:09<00:00, 1595.34it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3242.67it/s]

1
1
1
1
1
1
1
1
1

 24%|██▍       | 307/1274 [1:57:41<6:05:40, 22.69s/it]

1
1
1
1
Sulfamethoxazole

100%|██████████| 14792/14792 [00:08<00:00, 1787.32it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3081.12it/s]
 24%|██▍       | 308/1274 [1:58:03<6:02:03, 22.49s/it]

1
1
1
Sulfamethoxazole

100%|██████████| 14792/14792 [00:08<00:00, 1772.71it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3256.70it/s]
 24%|██▍       | 309/1274 [1:58:24<5:56:21, 22.16s/it]

Sulfamethoxazole

100%|██████████| 14792/14792 [00:08<00:00, 1730.28it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3127.33it/s]
 24%|██▍       | 310/1274 [1:58:46<5:54:43, 22.08s/it]

1
Sulfamethoxazole

100%|██████████| 14792/14792 [00:08<00:00, 1660.84it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2940.98it/s]
 24%|██▍       | 311/1274 [1:59:09<5:59:44, 22.41s/it]

1
1
Balsalazide

100%|██████████| 14792/14792 [00:09<00:00, 1618.74it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2965.59it/s]

1

 24%|██▍       | 312/1274 [1:59:33<6:05:44, 22.81s/it]

Balsalazide

100%|██████████| 14792/14792 [00:09<00:00, 1602.24it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3122.41it/s]

1

 25%|██▍       | 313/1274 [1:59:56<6:07:39, 22.95s/it]

Cinacalcet

100%|██████████| 14792/14792 [00:09<00:00, 1574.69it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2891.41it/s]
 25%|██▍       | 314/1274 [2:00:20<6:13:42, 23.36s/it]

Cinacalcet

100%|██████████| 14792/14792 [00:08<00:00, 1648.83it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3168.87it/s]
 25%|██▍       | 315/1274 [2:00:43<6:10:41, 23.19s/it]

Metyrapone

100%|██████████| 14792/14792 [00:08<00:00, 1769.81it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3356.68it/s]
 25%|██▍       | 316/1274 [2:01:05<6:01:28, 22.64s/it]

1
1
1
Letrozole

100%|██████████| 14792/14792 [00:08<00:00, 1714.92it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3287.96it/s]
 25%|██▍       | 317/1274 [2:01:26<5:55:48, 22.31s/it]

Aripiprazole

100%|██████████| 14792/14792 [00:09<00:00, 1599.21it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3139.36it/s]

1
1
1
1
1

 25%|██▍       | 318/1274 [2:01:49<5:58:57, 22.53s/it]

1
Aripiprazole

100%|██████████| 14792/14792 [00:09<00:00, 1567.49it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3345.04it/s]

1
1
1
1
1

 25%|██▌       | 319/1274 [2:02:12<5:58:01, 22.49s/it]

1
Cyclosporine

100%|██████████| 14792/14792 [00:10<00:00, 1375.34it/s]
100%|██████████| 34899/34899 [00:14<00:00, 2481.01it/s]

1
1
1
1

 25%|██▌       | 320/1274 [2:02:42<6:35:38, 24.88s/it]

Fluticasone furoate

100%|██████████| 14792/14792 [00:11<00:00, 1342.41it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3192.80it/s]

1
1
1
1
1

 25%|██▌       | 321/1274 [2:03:07<6:36:08, 24.94s/it]

Dolutegravir

100%|██████████| 14792/14792 [00:09<00:00, 1517.90it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3074.95it/s]
 25%|██▌       | 322/1274 [2:03:31<6:30:15, 24.60s/it]

Levomilnacipran

100%|██████████| 14792/14792 [00:08<00:00, 1740.33it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3176.57it/s]

1
1
1
1
1

 25%|██▌       | 323/1274 [2:03:53<6:16:54, 23.78s/it]

1
Levomilnacipran

100%|██████████| 14792/14792 [00:08<00:00, 1801.45it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3456.23it/s]
 25%|██▌       | 324/1274 [2:04:13<6:01:18, 22.82s/it]

Dabrafenib

100%|██████████| 14792/14792 [00:09<00:00, 1559.73it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3080.89it/s]

1
1
1

 26%|██▌       | 325/1274 [2:04:37<6:04:45, 23.06s/it]

Trametinib

100%|██████████| 14792/14792 [00:09<00:00, 1561.49it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2924.89it/s]
 26%|██▌       | 326/1274 [2:05:01<6:11:23, 23.51s/it]

Trametinib

100%|██████████| 14792/14792 [00:10<00:00, 1457.13it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3089.86it/s]

1
1

 26%|██▌       | 327/1274 [2:05:26<6:15:14, 23.77s/it]

Dimethyl fumarate

100%|██████████| 14792/14792 [00:08<00:00, 1829.66it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3516.41it/s]
 26%|██▌       | 328/1274 [2:05:46<5:57:05, 22.65s/it]

1
1
1
1
1
1
1
1
1
1
1
1
Fluticasone furoate

100%|██████████| 14792/14792 [00:10<00:00, 1376.49it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3238.92it/s]
 26%|██▌       | 329/1274 [2:06:10<6:04:55, 23.17s/it]

Dolutegravir

100%|██████████| 14792/14792 [00:09<00:00, 1511.34it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3073.89it/s]
 26%|██▌       | 330/1274 [2:06:34<6:06:59, 23.33s/it]

1
Bedaquiline

100%|██████████| 14792/14792 [00:09<00:00, 1511.79it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3094.77it/s]

1
1
1
1

 26%|██▌       | 331/1274 [2:06:58<6:12:10, 23.68s/it]

1
1
1
1
Linagliptin

100%|██████████| 14792/14792 [00:09<00:00, 1518.83it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3041.37it/s]

1

 26%|██▌       | 332/1274 [2:07:23<6:14:06, 23.83s/it]

1
Linagliptin

100%|██████████| 14792/14792 [00:09<00:00, 1495.31it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3148.75it/s]
 26%|██▌       | 333/1274 [2:07:46<6:13:13, 23.80s/it]

1
Linagliptin

100%|██████████| 14792/14792 [00:09<00:00, 1513.37it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3160.46it/s]
 26%|██▌       | 334/1274 [2:08:10<6:12:23, 23.77s/it]

1
Linagliptin

100%|██████████| 14792/14792 [00:10<00:00, 1464.01it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3017.55it/s]

1
1
1

 26%|██▋       | 335/1274 [2:08:35<6:16:01, 24.03s/it]

Linagliptin

100%|██████████| 14792/14792 [00:09<00:00, 1513.92it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2934.01it/s]

1

 26%|██▋       | 336/1274 [2:08:59<6:17:49, 24.17s/it]

1
Ruxolitinib

100%|██████████| 14792/14792 [00:09<00:00, 1630.19it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3161.34it/s]

1
1
1
1
1
1
1
1
1
1
1

 26%|██▋       | 337/1274 [2:09:22<6:10:18, 23.71s/it]

1
1
Dolutegravir

100%|██████████| 14792/14792 [00:10<00:00, 1472.06it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3170.95it/s]

1
1
1

 27%|██▋       | 338/1274 [2:09:46<6:10:26, 23.75s/it]

1
Dolutegravir

100%|██████████| 14792/14792 [00:09<00:00, 1512.92it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2983.86it/s]
 27%|██▋       | 339/1274 [2:10:10<6:11:41, 23.85s/it]

Ruxolitinib

100%|██████████| 14792/14792 [00:08<00:00, 1647.46it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2856.06it/s]

1
1
1
1
1
1
1
1
1
1
1

 27%|██▋       | 340/1274 [2:10:33<6:10:07, 23.78s/it]

1
1
Tedizolid phosphate

100%|██████████| 14792/14792 [00:09<00:00, 1640.91it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3157.10it/s]

1

 27%|██▋       | 341/1274 [2:10:56<6:03:07, 23.35s/it]

Ibrutinib

100%|██████████| 14792/14792 [00:09<00:00, 1594.00it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3216.94it/s]
 27%|██▋       | 342/1274 [2:11:19<6:02:11, 23.32s/it]

1
Ibrutinib

100%|██████████| 14792/14792 [00:09<00:00, 1552.84it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3135.71it/s]
 27%|██▋       | 343/1274 [2:11:42<6:00:46, 23.25s/it]

Ibrutinib

100%|██████████| 14792/14792 [00:09<00:00, 1485.53it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3079.99it/s]
 27%|██▋       | 344/1274 [2:12:06<6:04:20, 23.51s/it]

1
Ibrutinib

100%|██████████| 14792/14792 [00:09<00:00, 1533.58it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3263.36it/s]
 27%|██▋       | 345/1274 [2:12:29<6:01:55, 23.38s/it]

Ibrutinib

100%|██████████| 14792/14792 [00:09<00:00, 1553.75it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3052.96it/s]
 27%|██▋       | 346/1274 [2:12:53<6:03:49, 23.52s/it]

Netupitant

100%|██████████| 14792/14792 [00:09<00:00, 1537.15it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3213.94it/s]
 27%|██▋       | 347/1274 [2:13:17<6:03:24, 23.52s/it]

Netupitant

100%|██████████| 14792/14792 [00:09<00:00, 1564.16it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3231.01it/s]

1
1
1
1

 27%|██▋       | 348/1274 [2:13:40<6:01:12, 23.40s/it]

Empagliflozin

100%|██████████| 14792/14792 [00:08<00:00, 1652.64it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3060.65it/s]

1
1
1

 27%|██▋       | 349/1274 [2:14:03<6:02:12, 23.50s/it]

Macitentan

100%|██████████| 14792/14792 [00:09<00:00, 1618.59it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3139.37it/s]

1

 27%|██▋       | 350/1274 [2:14:26<5:58:08, 23.26s/it]

Empagliflozin

100%|██████████| 14792/14792 [00:09<00:00, 1524.19it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3375.19it/s]

1
1
1
1
1

 28%|██▊       | 351/1274 [2:14:50<5:59:03, 23.34s/it]

Empagliflozin

100%|██████████| 14792/14792 [00:09<00:00, 1625.48it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3194.62it/s]
 28%|██▊       | 352/1274 [2:15:13<5:58:34, 23.33s/it]

Bisacodyl

100%|██████████| 14792/14792 [00:09<00:00, 1612.58it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3432.45it/s]
 28%|██▊       | 353/1274 [2:15:35<5:51:09, 22.88s/it]

Inositol nicotinate

100%|██████████| 14792/14792 [00:10<00:00, 1439.83it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2842.69it/s]

1
1

 28%|██▊       | 354/1274 [2:16:00<6:01:42, 23.59s/it]

Sofosbuvir

100%|██████████| 14792/14792 [00:09<00:00, 1618.47it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3210.19it/s]

1
1
1

 28%|██▊       | 355/1274 [2:16:23<5:58:00, 23.37s/it]

Macitentan

100%|██████████| 14792/14792 [00:09<00:00, 1612.55it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3183.86it/s]
 28%|██▊       | 356/1274 [2:16:46<5:55:00, 23.20s/it]

Macitentan

100%|██████████| 14792/14792 [00:09<00:00, 1607.23it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3120.44it/s]
 28%|██▊       | 357/1274 [2:17:09<5:52:32, 23.07s/it]

Ruxolitinib

100%|██████████| 14792/14792 [00:09<00:00, 1598.90it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3071.10it/s]
 28%|██▊       | 358/1274 [2:17:32<5:51:51, 23.05s/it]

1
Fidaxomicin

100%|██████████| 14792/14792 [00:11<00:00, 1342.97it/s]
100%|██████████| 34899/34899 [00:13<00:00, 2536.80it/s]

1
1
1
1

 28%|██▊       | 359/1274 [2:18:02<6:24:54, 25.24s/it]

Idelalisib

100%|██████████| 14792/14792 [00:09<00:00, 1551.13it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3340.98it/s]
 28%|██▊       | 360/1274 [2:18:25<6:13:32, 24.52s/it]

1
Artemether

100%|██████████| 14792/14792 [00:10<00:00, 1425.70it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3348.35it/s]

1
1
1
1
1

 28%|██▊       | 361/1274 [2:18:48<6:07:25, 24.15s/it]

Dexmethylphenidate

100%|██████████| 14792/14792 [00:08<00:00, 1690.26it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3206.49it/s]

1
1
1
1

 28%|██▊       | 362/1274 [2:19:10<5:57:22, 23.51s/it]

1
1
Desvenlafaxine

100%|██████████| 14792/14792 [00:08<00:00, 1739.40it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3454.72it/s]

1
1
1
1
1
1
1

 28%|██▊       | 363/1274 [2:19:31<5:45:20, 22.75s/it]

1
Desvenlafaxine

100%|██████████| 14792/14792 [00:08<00:00, 1705.72it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3447.75it/s]

1

 29%|██▊       | 364/1274 [2:19:52<5:38:06, 22.29s/it]

1
Desvenlafaxine

100%|██████████| 14792/14792 [00:08<00:00, 1657.93it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3321.06it/s]

1
1
1

 29%|██▊       | 365/1274 [2:20:14<5:36:52, 22.24s/it]

1
Desvenlafaxine

100%|██████████| 14792/14792 [00:08<00:00, 1734.45it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3511.85it/s]

1
1
1
1

 29%|██▊       | 366/1274 [2:20:35<5:30:37, 21.85s/it]

1
Desvenlafaxine

100%|██████████| 14792/14792 [00:08<00:00, 1772.32it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3539.19it/s]

1
1
1
1

 29%|██▉       | 367/1274 [2:20:56<5:24:23, 21.46s/it]

1
1
1
Betahistine

100%|██████████| 14792/14792 [00:07<00:00, 1902.25it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3456.12it/s]
 29%|██▉       | 368/1274 [2:21:16<5:17:40, 21.04s/it]

Artemether

100%|██████████| 14792/14792 [00:09<00:00, 1485.27it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3487.53it/s]
 29%|██▉       | 369/1274 [2:21:38<5:23:51, 21.47s/it]

Dexmethylphenidate

100%|██████████| 14792/14792 [00:08<00:00, 1777.75it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2981.23it/s]

1
1
1
1
1
1
1
1
1
1
1
1

 29%|██▉       | 370/1274 [2:22:01<5:27:56, 21.77s/it]

Artemether

100%|██████████| 14792/14792 [00:10<00:00, 1453.60it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3405.90it/s]
 29%|██▉       | 371/1274 [2:22:24<5:32:44, 22.11s/it]

Artemether

100%|██████████| 14792/14792 [00:10<00:00, 1445.21it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3611.70it/s]

1
1
1
1
1

 29%|██▉       | 372/1274 [2:22:46<5:32:54, 22.14s/it]

Dabigatran etexilate

100%|██████████| 14792/14792 [00:09<00:00, 1637.40it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3249.21it/s]

1
1
1
1
1

 29%|██▉       | 373/1274 [2:23:09<5:38:08, 22.52s/it]

Dabigatran etexilate

100%|██████████| 14792/14792 [00:09<00:00, 1524.32it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3143.81it/s]
 29%|██▉       | 374/1274 [2:23:34<5:45:16, 23.02s/it]

Dalfampridine

100%|██████████| 14792/14792 [00:07<00:00, 1856.26it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3525.81it/s]
 29%|██▉       | 375/1274 [2:23:54<5:31:27, 22.12s/it]

1
Dalfampridine

100%|██████████| 14792/14792 [00:07<00:00, 1883.17it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3345.30it/s]
 30%|██▉       | 376/1274 [2:24:14<5:24:22, 21.67s/it]

1
1
1
1
1
1
1
Isavuconazonium

100%|██████████| 14792/14792 [00:09<00:00, 1557.87it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3146.65it/s]

1
1

 30%|██▉       | 377/1274 [2:24:38<5:32:40, 22.25s/it]

Dexmethylphenidate

100%|██████████| 14792/14792 [00:08<00:00, 1744.36it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3512.22it/s]
 30%|██▉       | 378/1274 [2:24:59<5:26:42, 21.88s/it]

1
Lumefantrine

100%|██████████| 14792/14792 [00:10<00:00, 1452.27it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3266.71it/s]
 30%|██▉       | 379/1274 [2:25:23<5:35:35, 22.50s/it]

Fingolimod

100%|██████████| 14792/14792 [00:08<00:00, 1760.82it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3433.45it/s]

1
1
1

 30%|██▉       | 380/1274 [2:25:44<5:28:57, 22.08s/it]

Chloramphenicol

100%|██████████| 14792/14792 [00:08<00:00, 1665.81it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3429.87it/s]
 30%|██▉       | 381/1274 [2:26:05<5:25:31, 21.87s/it]

Vismodegib

100%|██████████| 14792/14792 [00:08<00:00, 1700.61it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3445.70it/s]

1
1
1
1

 30%|██▉       | 382/1274 [2:26:27<5:24:02, 21.80s/it]

1
1
Vismodegib

100%|██████████| 14792/14792 [00:08<00:00, 1646.97it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3374.40it/s]

1
1
1
1

 30%|███       | 383/1274 [2:26:49<5:25:07, 21.89s/it]

1
1
Vismodegib

100%|██████████| 14792/14792 [00:08<00:00, 1677.39it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3257.06it/s]

1
1
1
1

 30%|███       | 384/1274 [2:27:11<5:25:49, 21.97s/it]

1
1
Lurasidone

100%|██████████| 14792/14792 [00:10<00:00, 1471.33it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3167.44it/s]

1
1
1
1
1

 30%|███       | 385/1274 [2:27:35<5:33:52, 22.53s/it]

Lurasidone

100%|██████████| 14792/14792 [00:10<00:00, 1435.10it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3129.48it/s]
 30%|███       | 386/1274 [2:27:59<5:40:12, 22.99s/it]

Chloramphenicol

100%|██████████| 14792/14792 [00:08<00:00, 1789.75it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3512.30it/s]

1
1
1

 30%|███       | 387/1274 [2:28:20<5:29:33, 22.29s/it]

Chloramphenicol

100%|██████████| 14792/14792 [00:08<00:00, 1767.55it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3392.63it/s]

1
1
1

 30%|███       | 388/1274 [2:28:41<5:24:39, 21.99s/it]

Chloramphenicol

100%|██████████| 14792/14792 [00:08<00:00, 1848.79it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3399.83it/s]
 31%|███       | 389/1274 [2:29:02<5:18:20, 21.58s/it]

Beta carotene

100%|██████████| 14792/14792 [00:08<00:00, 1683.98it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3520.73it/s]
 31%|███       | 390/1274 [2:29:23<5:16:11, 21.46s/it]

Chloramphenicol

100%|██████████| 14792/14792 [00:08<00:00, 1776.16it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3516.87it/s]
 31%|███       | 391/1274 [2:29:43<5:12:28, 21.23s/it]

Chloramphenicol

100%|██████████| 14792/14792 [00:08<00:00, 1751.46it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3577.39it/s]

1

 31%|███       | 392/1274 [2:30:04<5:10:03, 21.09s/it]

Chloramphenicol

100%|██████████| 14792/14792 [00:08<00:00, 1828.21it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3447.67it/s]
 31%|███       | 393/1274 [2:30:25<5:07:29, 20.94s/it]

Chloramphenicol

100%|██████████| 14792/14792 [00:08<00:00, 1748.50it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3719.50it/s]

1
1

 31%|███       | 394/1274 [2:30:45<5:03:33, 20.70s/it]

1
Triethylenetetramine

100%|██████████| 14792/14792 [00:07<00:00, 1862.03it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3487.87it/s]
 31%|███       | 395/1274 [2:31:05<5:01:16, 20.56s/it]

1
1
Tiopronin

100%|██████████| 14792/14792 [00:07<00:00, 1961.93it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3534.82it/s]
 31%|███       | 396/1274 [2:31:25<4:56:18, 20.25s/it]

1
1
1
1
1
Betaine

100%|██████████| 14792/14792 [00:07<00:00, 1938.21it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3632.02it/s]
 31%|███       | 397/1274 [2:31:44<4:53:24, 20.07s/it]

1
1
1
1
1
1
1
1
1
Ibrutinib

100%|██████████| 14792/14792 [00:09<00:00, 1600.26it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3303.02it/s]
 31%|███       | 398/1274 [2:32:07<5:03:54, 20.82s/it]

1
Sodium oxybate

100%|██████████| 14792/14792 [00:05<00:00, 2540.73it/s]
100%|██████████| 34899/34899 [00:08<00:00, 4297.36it/s]
 31%|███▏      | 399/1274 [2:32:23<4:41:49, 19.32s/it]

Aripiprazole

100%|██████████| 14792/14792 [00:09<00:00, 1624.82it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3255.64it/s]
 31%|███▏      | 400/1274 [2:32:45<4:54:12, 20.20s/it]

Asunaprevir

100%|██████████| 14792/14792 [00:09<00:00, 1557.33it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3292.05it/s]
 31%|███▏      | 401/1274 [2:33:08<5:06:13, 21.05s/it]

alpha-Linolenic acid

100%|██████████| 14792/14792 [00:07<00:00, 1861.58it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3565.51it/s]
 32%|███▏      | 402/1274 [2:33:29<5:03:30, 20.88s/it]

Opicapone

100%|██████████| 14792/14792 [00:08<00:00, 1693.08it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3618.94it/s]

1
1
1

 32%|███▏      | 403/1274 [2:33:49<5:03:22, 20.90s/it]

1
Opicapone

100%|██████████| 14792/14792 [00:08<00:00, 1655.36it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3214.21it/s]
 32%|███▏      | 404/1274 [2:34:12<5:09:40, 21.36s/it]

Opicapone

100%|██████████| 14792/14792 [00:08<00:00, 1748.79it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3424.58it/s]

1

 32%|███▏      | 405/1274 [2:34:33<5:08:48, 21.32s/it]

Opicapone

100%|██████████| 14792/14792 [00:08<00:00, 1664.48it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3616.93it/s]

1

 32%|███▏      | 406/1274 [2:34:54<5:06:52, 21.21s/it]

Opicapone

100%|██████████| 14792/14792 [00:08<00:00, 1716.46it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3180.41it/s]

1

 32%|███▏      | 407/1274 [2:35:16<5:11:00, 21.52s/it]

Opicapone

100%|██████████| 14792/14792 [00:08<00:00, 1740.11it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3398.08it/s]

1
1
1

 32%|███▏      | 408/1274 [2:35:38<5:10:27, 21.51s/it]

1
Asunaprevir

100%|██████████| 14792/14792 [00:09<00:00, 1486.81it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3201.83it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

 32%|███▏      | 409/1274 [2:36:02<5:22:06, 22.34s/it]

Aripiprazole

100%|██████████| 14792/14792 [00:09<00:00, 1558.58it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3451.91it/s]

1

 32%|███▏      | 410/1274 [2:36:24<5:21:29, 22.33s/it]

1
Asunaprevir

100%|██████████| 14792/14792 [00:10<00:00, 1424.40it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3134.04it/s]
 32%|███▏      | 411/1274 [2:36:49<5:31:47, 23.07s/it]

Asunaprevir

100%|██████████| 14792/14792 [00:09<00:00, 1508.50it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3213.04it/s]
 32%|███▏      | 412/1274 [2:37:13<5:35:52, 23.38s/it]

Alectinib

100%|██████████| 14792/14792 [00:10<00:00, 1390.74it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3383.61it/s]
 32%|███▏      | 413/1274 [2:37:37<5:35:36, 23.39s/it]

1
Alectinib

100%|██████████| 14792/14792 [00:10<00:00, 1368.98it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3153.09it/s]
 32%|███▏      | 414/1274 [2:38:01<5:41:10, 23.80s/it]

1
Alectinib

100%|██████████| 14792/14792 [00:10<00:00, 1399.56it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3321.96it/s]
 33%|███▎      | 415/1274 [2:38:25<5:40:00, 23.75s/it]

Alectinib

100%|██████████| 14792/14792 [00:10<00:00, 1345.71it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3287.97it/s]
 33%|███▎      | 416/1274 [2:38:49<5:42:27, 23.95s/it]

Selexipag

100%|██████████| 14792/14792 [00:08<00:00, 1707.79it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3194.58it/s]
 33%|███▎      | 417/1274 [2:39:12<5:36:06, 23.53s/it]

alpha-Linolenic acid

100%|██████████| 14792/14792 [00:08<00:00, 1731.06it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3461.87it/s]
 33%|███▎      | 418/1274 [2:39:34<5:27:40, 22.97s/it]

Hydromorphone

100%|██████████| 14792/14792 [00:12<00:00, 1215.23it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3306.12it/s]

1
1
1

 33%|███▎      | 419/1274 [2:39:59<5:36:32, 23.62s/it]

1
1
Oxyquinoline

100%|██████████| 14792/14792 [00:07<00:00, 1859.79it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3415.00it/s]
 33%|███▎      | 420/1274 [2:40:20<5:23:52, 22.75s/it]

Prednisone

100%|██████████| 14792/14792 [00:10<00:00, 1418.91it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3267.78it/s]

1
1
1

 33%|███▎      | 421/1274 [2:40:44<5:29:07, 23.15s/it]

Dexmethylphenidate

100%|██████████| 14792/14792 [00:08<00:00, 1785.16it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3439.47it/s]
 33%|███▎      | 422/1274 [2:41:05<5:19:10, 22.48s/it]

1
Dexmethylphenidate

100%|██████████| 14792/14792 [00:08<00:00, 1765.44it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3505.38it/s]

1
1
1
1
1
1
1
1
1
1
1
1

 33%|███▎      | 423/1274 [2:41:25<5:10:48, 21.91s/it]

Dexmethylphenidate

100%|██████████| 14792/14792 [00:08<00:00, 1807.27it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3411.50it/s]
 33%|███▎      | 424/1274 [2:41:46<5:06:16, 21.62s/it]

1
Melphalan

100%|██████████| 14792/14792 [00:08<00:00, 1825.07it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3314.51it/s]
 33%|███▎      | 425/1274 [2:42:07<5:03:23, 21.44s/it]

Melphalan

100%|██████████| 14792/14792 [00:08<00:00, 1781.16it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3612.01it/s]

1

 33%|███▎      | 426/1274 [2:42:27<4:57:59, 21.08s/it]

Prednisone

100%|██████████| 14792/14792 [00:10<00:00, 1420.81it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3410.35it/s]

1
1
1
1
1
1
1
1
1

 34%|███▎      | 427/1274 [2:42:51<5:07:56, 21.81s/it]

1
1
1
Prednisone

100%|██████████| 14792/14792 [00:10<00:00, 1437.78it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3427.53it/s]

1
1
1
1
1
1
1
1
1

 34%|███▎      | 428/1274 [2:43:14<5:13:42, 22.25s/it]

1
1
1
Prednisone

100%|██████████| 14792/14792 [00:10<00:00, 1387.51it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3435.74it/s]

1
1
1

 34%|███▎      | 429/1274 [2:43:38<5:18:57, 22.65s/it]

Hydromorphone

100%|██████████| 14792/14792 [00:11<00:00, 1249.28it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3277.52it/s]

1
1
1

 34%|███▍      | 430/1274 [2:44:03<5:29:03, 23.39s/it]

1
1
Prednisone

100%|██████████| 14792/14792 [00:10<00:00, 1391.68it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3539.41it/s]

1
1
1

 34%|███▍      | 431/1274 [2:44:26<5:27:49, 23.33s/it]

Prednisolone

100%|██████████| 14792/14792 [00:10<00:00, 1439.58it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3418.51it/s]

1
1
1

 34%|███▍      | 432/1274 [2:44:50<5:28:00, 23.37s/it]

Prednisolone

100%|██████████| 14792/14792 [00:10<00:00, 1381.66it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3171.79it/s]

1
1
1
1
1
1
1
1
1

 34%|███▍      | 433/1274 [2:45:14<5:33:18, 23.78s/it]

1
1
1
Prednisolone

100%|██████████| 14792/14792 [00:10<00:00, 1410.01it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3408.85it/s]

1
1
1
1
1
1
1
1
1

 34%|███▍      | 434/1274 [2:45:38<5:32:25, 23.74s/it]

1
1
1
Prednisolone

100%|██████████| 14792/14792 [00:10<00:00, 1452.67it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3442.82it/s]

1
1
1

 34%|███▍      | 435/1274 [2:46:01<5:30:19, 23.62s/it]

Prednisolone

100%|██████████| 14792/14792 [00:10<00:00, 1438.47it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3083.26it/s]

1
1
1

 34%|███▍      | 436/1274 [2:46:26<5:33:30, 23.88s/it]

Prednisolone

100%|██████████| 14792/14792 [00:10<00:00, 1426.75it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3418.42it/s]

1
1
1

 34%|███▍      | 437/1274 [2:46:49<5:31:35, 23.77s/it]

Oxyquinoline

100%|██████████| 14792/14792 [00:08<00:00, 1744.88it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3516.91it/s]
 34%|███▍      | 438/1274 [2:47:10<5:18:37, 22.87s/it]

1
1
1
Calcifediol

100%|██████████| 14792/14792 [00:09<00:00, 1611.85it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3508.20it/s]

1
1
1
1
1
1
1
1
1
1
1
1

 34%|███▍      | 439/1274 [2:47:32<5:15:10, 22.65s/it]

Palbociclib

100%|██████████| 14792/14792 [00:09<00:00, 1492.46it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3421.42it/s]

1
1
1
1
1
1
1
1
1

 35%|███▍      | 440/1274 [2:47:55<5:15:53, 22.73s/it]

1
1
1
Palbociclib

100%|██████████| 14792/14792 [00:09<00:00, 1535.83it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3188.80it/s]
 35%|███▍      | 441/1274 [2:48:18<5:18:16, 22.93s/it]

1
Nintedanib

100%|██████████| 14792/14792 [00:09<00:00, 1509.97it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3333.63it/s]

1
1
1
1
1
1
1
1
1
1

 35%|███▍      | 442/1274 [2:48:42<5:20:18, 23.10s/it]

Umeclidinium

100%|██████████| 14792/14792 [00:08<00:00, 1666.98it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3188.18it/s]

1
1
1
1

 35%|███▍      | 443/1274 [2:49:05<5:17:44, 22.94s/it]

1
1
Umeclidinium

100%|██████████| 14792/14792 [00:09<00:00, 1546.57it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3330.13it/s]
 35%|███▍      | 444/1274 [2:49:27<5:15:23, 22.80s/it]

Palbociclib

100%|██████████| 14792/14792 [00:09<00:00, 1538.83it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3342.12it/s]
 35%|███▍      | 445/1274 [2:49:50<5:15:18, 22.82s/it]

Palbociclib

100%|██████████| 14792/14792 [00:09<00:00, 1511.34it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3142.78it/s]
 35%|███▌      | 446/1274 [2:50:13<5:18:02, 23.05s/it]

Palbociclib

100%|██████████| 14792/14792 [00:10<00:00, 1475.03it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3325.75it/s]
 35%|███▌      | 447/1274 [2:50:37<5:17:49, 23.06s/it]

Palbociclib

100%|██████████| 14792/14792 [00:09<00:00, 1584.83it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3124.52it/s]
 35%|███▌      | 448/1274 [2:51:00<5:18:13, 23.12s/it]

Palbociclib

100%|██████████| 14792/14792 [00:09<00:00, 1530.33it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3227.31it/s]

1

 35%|███▌      | 449/1274 [2:51:23<5:17:46, 23.11s/it]

1
Idebenone

100%|██████████| 14792/14792 [00:08<00:00, 1765.07it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3834.60it/s]
 35%|███▌      | 450/1274 [2:51:43<5:04:46, 22.19s/it]

Palbociclib

100%|██████████| 14792/14792 [00:09<00:00, 1538.99it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3385.59it/s]
 35%|███▌      | 451/1274 [2:52:06<5:06:15, 22.33s/it]

1
Palbociclib

100%|██████████| 14792/14792 [00:09<00:00, 1568.64it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3173.99it/s]
 35%|███▌      | 452/1274 [2:52:29<5:09:20, 22.58s/it]

1
Palbociclib

100%|██████████| 14792/14792 [00:09<00:00, 1596.43it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3336.01it/s]
 36%|███▌      | 453/1274 [2:52:51<5:08:11, 22.52s/it]

Palbociclib

100%|██████████| 14792/14792 [00:09<00:00, 1596.91it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3032.26it/s]
 36%|███▌      | 454/1274 [2:53:15<5:11:48, 22.82s/it]

Palbociclib

100%|██████████| 14792/14792 [00:09<00:00, 1584.86it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3099.75it/s]

1

 36%|███▌      | 455/1274 [2:53:38<5:12:56, 22.93s/it]

1
Palbociclib

100%|██████████| 14792/14792 [00:09<00:00, 1555.75it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3181.26it/s]

1
1
1
1
1
1
1
1
1

 36%|███▌      | 456/1274 [2:54:01<5:13:36, 23.00s/it]

1
1
1
Palbociclib

100%|██████████| 14792/14792 [00:09<00:00, 1530.67it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3271.82it/s]

1
1
1
1
1
1

 36%|███▌      | 457/1274 [2:54:24<5:13:31, 23.02s/it]

1
Nintedanib

100%|██████████| 14792/14792 [00:09<00:00, 1526.40it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2915.25it/s]

1
1
1
1

 36%|███▌      | 458/1274 [2:54:49<5:21:42, 23.66s/it]

Benzydamine

100%|██████████| 14792/14792 [00:08<00:00, 1647.19it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3378.28it/s]

1

 36%|███▌      | 459/1274 [2:55:11<5:14:11, 23.13s/it]

1
Methyl salicylate

100%|██████████| 14792/14792 [00:08<00:00, 1802.52it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3439.41it/s]

1

 36%|███▌      | 460/1274 [2:55:32<5:03:41, 22.39s/it]

Tegafur

100%|██████████| 14792/14792 [00:07<00:00, 1849.06it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3362.37it/s]
 36%|███▌      | 461/1274 [2:55:53<4:57:11, 21.93s/it]

1
Xylose

100%|██████████| 14792/14792 [00:07<00:00, 1922.95it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3523.97it/s]

1
1

 36%|███▋      | 462/1274 [2:56:13<4:49:31, 21.39s/it]

Dexpanthenol

100%|██████████| 14792/14792 [00:08<00:00, 1847.42it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3466.19it/s]

1

 36%|███▋      | 463/1274 [2:56:33<4:45:42, 21.14s/it]

1
Tipiracil

100%|██████████| 14792/14792 [00:08<00:00, 1747.03it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3458.28it/s]
 36%|███▋      | 464/1274 [2:56:54<4:43:49, 21.02s/it]

Tenofovir alafenamide

100%|██████████| 14792/14792 [00:09<00:00, 1636.01it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2796.44it/s]

1
1
1
1

 36%|███▋      | 465/1274 [2:57:18<4:57:07, 22.04s/it]

Sacubitril

100%|██████████| 14792/14792 [00:08<00:00, 1682.68it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2828.56it/s]

1
1
1
1

 37%|███▋      | 466/1274 [2:57:43<5:05:53, 22.71s/it]

Rolapitant

100%|██████████| 14792/14792 [00:09<00:00, 1595.50it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3092.48it/s]

1
1
1
1
1
1
1
1
1

 37%|███▋      | 467/1274 [2:58:06<5:08:02, 22.90s/it]

1
1
1
Picosulfuric acid

100%|██████████| 14792/14792 [00:09<00:00, 1601.84it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3435.81it/s]
 37%|███▋      | 468/1274 [2:58:28<5:02:17, 22.50s/it]

Brexpiprazole

100%|██████████| 14792/14792 [00:09<00:00, 1569.46it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3021.05it/s]
 37%|███▋      | 469/1274 [2:58:52<5:07:57, 22.95s/it]

1
Benzydamine

100%|██████████| 14792/14792 [00:08<00:00, 1711.46it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3222.70it/s]

1
1
1
1
1
1
1
1

 37%|███▋      | 470/1274 [2:59:14<5:05:30, 22.80s/it]

Eslicarbazepine acetate

100%|██████████| 14792/14792 [00:09<00:00, 1566.10it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3396.90it/s]

1
1
1
1

 37%|███▋      | 471/1274 [2:59:37<5:04:12, 22.73s/it]

Calcium carbimide

100%|██████████| 14792/14792 [00:05<00:00, 2627.25it/s]
100%|██████████| 34899/34899 [00:08<00:00, 4209.91it/s]
 37%|███▋      | 472/1274 [2:59:53<4:37:03, 20.73s/it]

Coenzyme M

100%|██████████| 14792/14792 [00:07<00:00, 1889.90it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3680.57it/s]
 37%|███▋      | 473/1274 [3:00:12<4:32:34, 20.42s/it]

1
1
1
1
1
1
1
Trimebutine

100%|██████████| 14792/14792 [00:08<00:00, 1712.75it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3321.08it/s]

1

 37%|███▋      | 474/1274 [3:00:34<4:37:27, 20.81s/it]

1
Trimebutine

100%|██████████| 14792/14792 [00:08<00:00, 1661.32it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3184.57it/s]

1
1
1
1

 37%|███▋      | 475/1274 [3:00:57<4:43:26, 21.28s/it]

1
1
1
1
Tetracaine

100%|██████████| 14792/14792 [00:08<00:00, 1801.50it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3378.64it/s]
 37%|███▋      | 476/1274 [3:01:17<4:41:41, 21.18s/it]

Tetracaine

100%|██████████| 14792/14792 [00:08<00:00, 1816.27it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3443.17it/s]
 37%|███▋      | 477/1274 [3:01:38<4:39:21, 21.03s/it]

Isavuconazonium

100%|██████████| 14792/14792 [00:09<00:00, 1563.86it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3063.54it/s]
 38%|███▊      | 478/1274 [3:02:02<4:49:44, 21.84s/it]

Bosutinib

100%|██████████| 14792/14792 [00:09<00:00, 1585.54it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3216.32it/s]

1
1
1

 38%|███▊      | 479/1274 [3:02:25<4:54:20, 22.21s/it]

Bosutinib

100%|██████████| 14792/14792 [00:09<00:00, 1569.61it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3101.72it/s]

1
1
1
1

 38%|███▊      | 480/1274 [3:02:48<4:59:13, 22.61s/it]

Dextroamphetamine

100%|██████████| 14792/14792 [00:08<00:00, 1823.05it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3476.02it/s]
 38%|███▊      | 481/1274 [3:03:09<4:50:18, 21.97s/it]

1
1
1
1
1
1
Ursodeoxycholic acid

100%|██████████| 14792/14792 [00:10<00:00, 1378.11it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3478.75it/s]

1
1
1
1

 38%|███▊      | 482/1274 [3:03:33<4:57:01, 22.50s/it]

Phendimetrazine

100%|██████████| 14792/14792 [00:08<00:00, 1810.72it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3584.73it/s]
 38%|███▊      | 483/1274 [3:03:53<4:47:52, 21.84s/it]

1
1
1
1
Metamfetamine

100%|██████████| 14792/14792 [00:07<00:00, 1877.30it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3223.82it/s]
 38%|███▊      | 484/1274 [3:04:14<4:44:29, 21.61s/it]

1
1
1
1
1
1
Metamfetamine

100%|██████████| 14792/14792 [00:08<00:00, 1776.15it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3543.86it/s]
 38%|███▊      | 485/1274 [3:04:34<4:39:25, 21.25s/it]

Metamfetamine

100%|██████████| 14792/14792 [00:07<00:00, 1919.71it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3717.47it/s]
 38%|███▊      | 486/1274 [3:04:54<4:30:40, 20.61s/it]

1
1
1
1
1
1
1
1
1
Metamfetamine

100%|██████████| 14792/14792 [00:07<00:00, 1894.35it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3617.71it/s]
 38%|███▊      | 487/1274 [3:05:13<4:27:17, 20.38s/it]

Metamfetamine

100%|██████████| 14792/14792 [00:07<00:00, 1893.53it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3570.55it/s]
 38%|███▊      | 488/1274 [3:05:33<4:24:43, 20.21s/it]

Phenazopyridine

100%|██████████| 14792/14792 [00:08<00:00, 1756.42it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3540.91it/s]
 38%|███▊      | 489/1274 [3:05:54<4:26:17, 20.35s/it]

1
Quazepam

100%|██████████| 14792/14792 [00:09<00:00, 1626.47it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3491.90it/s]
 38%|███▊      | 490/1274 [3:06:15<4:29:50, 20.65s/it]

Phenazopyridine

100%|██████████| 14792/14792 [00:08<00:00, 1788.22it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3391.21it/s]
 39%|███▊      | 491/1274 [3:06:36<4:30:50, 20.75s/it]

1
Phenazopyridine

100%|██████████| 14792/14792 [00:08<00:00, 1804.91it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3288.00it/s]

1
1
1
1

 39%|███▊      | 492/1274 [3:06:58<4:32:37, 20.92s/it]

1
1
1
Antipyrine

100%|██████████| 14792/14792 [00:08<00:00, 1824.65it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3468.35it/s]
 39%|███▊      | 493/1274 [3:07:18<4:30:28, 20.78s/it]

1
1
Antipyrine

100%|██████████| 14792/14792 [00:08<00:00, 1821.61it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3664.88it/s]
 39%|███▉      | 494/1274 [3:07:38<4:26:17, 20.48s/it]

1
1
1
1
1
1
Antipyrine

100%|██████████| 14792/14792 [00:08<00:00, 1757.35it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3442.52it/s]
 39%|███▉      | 495/1274 [3:07:59<4:27:49, 20.63s/it]

1
1
Antipyrine

100%|██████████| 14792/14792 [00:07<00:00, 1874.10it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3650.96it/s]
 39%|███▉      | 496/1274 [3:08:19<4:23:54, 20.35s/it]

Acenocoumarol

100%|██████████| 14792/14792 [00:08<00:00, 1667.94it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3437.19it/s]

1
1
1
1

 39%|███▉      | 497/1274 [3:08:40<4:29:15, 20.79s/it]

1
1
Ursodeoxycholic acid

100%|██████████| 14792/14792 [00:10<00:00, 1447.86it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3646.41it/s]

1
1
1

 39%|███▉      | 498/1274 [3:09:03<4:36:40, 21.39s/it]

Solifenacin

100%|██████████| 14792/14792 [00:09<00:00, 1579.37it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3146.71it/s]

1
1

 39%|███▉      | 499/1274 [3:09:26<4:43:35, 21.96s/it]

1
1
1
1
Acenocoumarol

100%|██████████| 14792/14792 [00:09<00:00, 1619.16it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3454.00it/s]

1
1
1
1

 39%|███▉      | 500/1274 [3:09:48<4:43:15, 21.96s/it]

1
1
Thymol

100%|██████████| 14792/14792 [00:07<00:00, 1852.05it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3660.35it/s]
 39%|███▉      | 501/1274 [3:10:08<4:33:42, 21.24s/it]

1
1
1
1
1
1
1
Lauric acid

100%|██████████| 14792/14792 [00:08<00:00, 1843.12it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3398.94it/s]

1
1
1

 39%|███▉      | 502/1274 [3:10:29<4:31:37, 21.11s/it]

Fusidic acid

100%|██████████| 14792/14792 [00:10<00:00, 1387.48it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3467.61it/s]

1

 39%|███▉      | 503/1274 [3:10:53<4:43:28, 22.06s/it]

1
Fusidic acid

100%|██████████| 14792/14792 [00:10<00:00, 1425.84it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3412.31it/s]
 40%|███▉      | 504/1274 [3:11:16<4:48:24, 22.47s/it]

Cholic Acid

100%|██████████| 14792/14792 [00:10<00:00, 1450.71it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3132.98it/s]

1
1

 40%|███▉      | 505/1274 [3:11:41<4:56:42, 23.15s/it]

Vorinostat

100%|██████████| 14792/14792 [00:08<00:00, 1802.81it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3300.41it/s]
 40%|███▉      | 506/1274 [3:12:03<4:49:49, 22.64s/it]

Thymol

100%|██████████| 14792/14792 [00:08<00:00, 1793.50it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3734.67it/s]
 40%|███▉      | 507/1274 [3:12:22<4:38:29, 21.79s/it]

1
Thymol

100%|██████████| 14792/14792 [00:08<00:00, 1793.27it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3516.44it/s]
 40%|███▉      | 508/1274 [3:12:43<4:33:48, 21.45s/it]

1
1
1
1
1
1
1
Camphor

100%|██████████| 14792/14792 [00:08<00:00, 1753.21it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3568.47it/s]
 40%|███▉      | 509/1274 [3:13:04<4:29:47, 21.16s/it]

1
1
1
1
1
1
1
1
1
1
1
1
Lopinavir

100%|██████████| 14792/14792 [00:09<00:00, 1536.85it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3304.66it/s]

1
1

 40%|████      | 510/1274 [3:13:27<4:39:30, 21.95s/it]

Camphor

100%|██████████| 14792/14792 [00:08<00:00, 1840.43it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3357.52it/s]
 40%|████      | 511/1274 [3:13:48<4:34:20, 21.57s/it]

1
1
1
1
1
1
1
1
1
1
1
1
Roflumilast

100%|██████████| 14792/14792 [00:08<00:00, 1653.05it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3571.63it/s]
 40%|████      | 512/1274 [3:14:09<4:32:32, 21.46s/it]

1
Pheniramine

100%|██████████| 14792/14792 [00:08<00:00, 1763.21it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3373.65it/s]

1
1
1
1
1
1
1
1

 40%|████      | 513/1274 [3:14:31<4:31:25, 21.40s/it]

Hydroxychloroquine

100%|██████████| 14792/14792 [00:08<00:00, 1726.89it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3391.20it/s]
 40%|████      | 514/1274 [3:14:52<4:31:46, 21.46s/it]

Hydroxychloroquine

100%|██████████| 14792/14792 [00:08<00:00, 1728.16it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3200.54it/s]
 40%|████      | 515/1274 [3:15:14<4:33:40, 21.63s/it]

Hydroxychloroquine

100%|██████████| 14792/14792 [00:08<00:00, 1697.24it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3456.10it/s]

1

 41%|████      | 516/1274 [3:15:36<4:32:24, 21.56s/it]

Lopinavir

100%|██████████| 14792/14792 [00:09<00:00, 1546.78it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3290.35it/s]

1
1

 41%|████      | 517/1274 [3:15:59<4:40:23, 22.22s/it]

Acenocoumarol

100%|██████████| 14792/14792 [00:08<00:00, 1651.42it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3224.46it/s]

1
1
1
1

 41%|████      | 518/1274 [3:16:22<4:42:34, 22.43s/it]

1
1
Tiotropium

100%|██████████| 14792/14792 [00:08<00:00, 1661.59it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3262.93it/s]
 41%|████      | 519/1274 [3:16:44<4:41:10, 22.35s/it]

1
Midostaurin

100%|██████████| 14792/14792 [00:18<00:00, 814.08it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3102.69it/s]

1
1
1
1

 41%|████      | 520/1274 [3:17:18<5:21:51, 25.61s/it]

Dasatinib

100%|██████████| 14792/14792 [00:09<00:00, 1565.54it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2959.76it/s]
 41%|████      | 521/1274 [3:17:42<5:15:10, 25.11s/it]

Dextroamphetamine

100%|██████████| 14792/14792 [00:08<00:00, 1805.14it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3476.04it/s]
 41%|████      | 522/1274 [3:18:02<4:57:00, 23.70s/it]

1
1
1
1
1
1
Dextroamphetamine

100%|██████████| 14792/14792 [00:08<00:00, 1847.50it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3527.77it/s]
 41%|████      | 523/1274 [3:18:22<4:43:14, 22.63s/it]

1
1
1
1
1
1
1
Lisdexamfetamine

100%|██████████| 14792/14792 [00:08<00:00, 1715.86it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3456.72it/s]

1
1
1

 41%|████      | 524/1274 [3:18:43<4:37:07, 22.17s/it]

Lisdexamfetamine

100%|██████████| 14792/14792 [00:08<00:00, 1744.79it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3444.12it/s]

1
1
1

 41%|████      | 525/1274 [3:19:04<4:32:37, 21.84s/it]

Dasatinib

100%|██████████| 14792/14792 [00:09<00:00, 1608.95it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3292.63it/s]

1

 41%|████▏     | 526/1274 [3:19:27<4:33:51, 21.97s/it]

1
Dasatinib

100%|██████████| 14792/14792 [00:09<00:00, 1540.30it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2868.86it/s]

1
1
1
1
1

 41%|████▏     | 527/1274 [3:19:51<4:42:46, 22.71s/it]

1
Dasatinib

100%|██████████| 14792/14792 [00:09<00:00, 1516.30it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3164.86it/s]

1

 41%|████▏     | 528/1274 [3:20:14<4:45:12, 22.94s/it]

1
Dasatinib

100%|██████████| 14792/14792 [00:09<00:00, 1580.79it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2909.64it/s]

1

 42%|████▏     | 529/1274 [3:20:38<4:48:49, 23.26s/it]

Hydralazine

100%|██████████| 14792/14792 [00:08<00:00, 1750.01it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3400.87it/s]
 42%|████▏     | 530/1274 [3:20:59<4:39:41, 22.56s/it]

Olsalazine

100%|██████████| 14792/14792 [00:08<00:00, 1714.64it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3601.97it/s]

1
1
1

 42%|████▏     | 531/1274 [3:21:20<4:32:27, 22.00s/it]

1
Olsalazine

100%|██████████| 14792/14792 [00:08<00:00, 1749.61it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3094.48it/s]

1

 42%|████▏     | 532/1274 [3:21:42<4:32:15, 22.02s/it]

Isocarboxazid

100%|██████████| 14792/14792 [00:08<00:00, 1804.53it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3490.32it/s]
 42%|████▏     | 533/1274 [3:22:02<4:25:26, 21.49s/it]

Gemfibrozil

100%|██████████| 14792/14792 [00:08<00:00, 1701.91it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3379.70it/s]

1
1
1
1

 42%|████▏     | 534/1274 [3:22:24<4:25:18, 21.51s/it]

1
1
Gemfibrozil

100%|██████████| 14792/14792 [00:08<00:00, 1828.89it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3275.56it/s]

1

 42%|████▏     | 535/1274 [3:22:45<4:24:32, 21.48s/it]

1
Gemfibrozil

100%|██████████| 14792/14792 [00:08<00:00, 1769.97it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3167.57it/s]

1
1

 42%|████▏     | 536/1274 [3:23:07<4:25:54, 21.62s/it]

Aripiprazole

100%|██████████| 14792/14792 [00:09<00:00, 1573.76it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3235.53it/s]
 42%|████▏     | 537/1274 [3:23:30<4:29:07, 21.91s/it]

Dextroamphetamine

100%|██████████| 14792/14792 [00:08<00:00, 1821.29it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3428.12it/s]
 42%|████▏     | 538/1274 [3:23:50<4:23:14, 21.46s/it]

1
Hydralazine

100%|██████████| 14792/14792 [00:08<00:00, 1713.52it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3461.24it/s]
 42%|████▏     | 539/1274 [3:24:11<4:21:37, 21.36s/it]

Tiotropium

100%|██████████| 14792/14792 [00:09<00:00, 1639.24it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3312.10it/s]
 42%|████▏     | 540/1274 [3:24:33<4:23:47, 21.56s/it]

1
Ephedrine

100%|██████████| 14792/14792 [00:08<00:00, 1843.07it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3542.31it/s]
 42%|████▏     | 541/1274 [3:24:54<4:18:54, 21.19s/it]

1
1
1
1
1
1
1
1
1
Danazol

100%|██████████| 14792/14792 [00:11<00:00, 1326.07it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3162.45it/s]
 43%|████▎     | 542/1274 [3:25:19<4:31:34, 22.26s/it]

Danazol

100%|██████████| 14792/14792 [00:11<00:00, 1265.82it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3504.68it/s]
 43%|████▎     | 543/1274 [3:25:43<4:37:36, 22.79s/it]

Drospirenone

100%|██████████| 14792/14792 [00:12<00:00, 1185.36it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3013.12it/s]
 43%|████▎     | 544/1274 [3:26:09<4:51:42, 23.98s/it]

1
Colchicine

100%|██████████| 14792/14792 [00:09<00:00, 1517.38it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3402.76it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

 43%|████▎     | 545/1274 [3:26:32<4:46:54, 23.61s/it]

Colchicine

100%|██████████| 14792/14792 [00:09<00:00, 1534.89it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3393.43it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

 43%|████▎     | 546/1274 [3:26:55<4:43:23, 23.36s/it]

Colchicine

100%|██████████| 14792/14792 [00:09<00:00, 1493.73it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3218.62it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

 43%|████▎     | 547/1274 [3:27:18<4:43:34, 23.40s/it]

Ephedrine

100%|██████████| 14792/14792 [00:07<00:00, 1891.86it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3377.76it/s]
 43%|████▎     | 548/1274 [3:27:39<4:33:21, 22.59s/it]

Mestranol

100%|██████████| 14792/14792 [00:10<00:00, 1461.36it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3100.38it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

 43%|████▎     | 549/1274 [3:28:03<4:37:21, 22.95s/it]

Hydralazine

100%|██████████| 14792/14792 [00:08<00:00, 1730.31it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3334.51it/s]
 43%|████▎     | 550/1274 [3:28:24<4:30:19, 22.40s/it]

Mestranol

100%|██████████| 14792/14792 [00:09<00:00, 1506.78it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3161.60it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

 43%|████▎     | 551/1274 [3:28:47<4:33:22, 22.69s/it]

Cilazapril

100%|██████████| 14792/14792 [00:09<00:00, 1616.21it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3014.90it/s]

1
1
1
1

 43%|████▎     | 552/1274 [3:29:11<4:37:05, 23.03s/it]

Hydralazine

100%|██████████| 14792/14792 [00:08<00:00, 1818.66it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3316.40it/s]
 43%|████▎     | 553/1274 [3:29:32<4:28:40, 22.36s/it]

Hydralazine

100%|██████████| 14792/14792 [00:08<00:00, 1752.25it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3310.33it/s]
 43%|████▎     | 554/1274 [3:29:53<4:23:57, 22.00s/it]

1
1
1
1
Hydralazine

100%|██████████| 14792/14792 [00:09<00:00, 1624.43it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3244.03it/s]
 44%|████▎     | 555/1274 [3:30:15<4:24:03, 22.04s/it]

Hydralazine

100%|██████████| 14792/14792 [00:08<00:00, 1837.09it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3313.25it/s]
 44%|████▎     | 556/1274 [3:30:36<4:18:55, 21.64s/it]

Hydralazine

100%|██████████| 14792/14792 [00:08<00:00, 1764.01it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3220.99it/s]
 44%|████▎     | 557/1274 [3:30:57<4:18:02, 21.59s/it]

Phenol

100%|██████████| 14792/14792 [00:07<00:00, 1849.84it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3402.29it/s]
 44%|████▍     | 558/1274 [3:31:18<4:13:08, 21.21s/it]

1
1
1
1
1
1
Benzoic acid

100%|██████████| 14792/14792 [00:07<00:00, 1897.22it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3406.51it/s]
 44%|████▍     | 559/1274 [3:31:38<4:10:25, 21.01s/it]

1
1
Eucalyptol

100%|██████████| 14792/14792 [00:08<00:00, 1724.17it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3253.62it/s]
 44%|████▍     | 560/1274 [3:32:00<4:12:00, 21.18s/it]

1
1
1
1
1
1
1
1
1
1
1
1
Silodosin

100%|██████████| 14792/14792 [00:09<00:00, 1604.21it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3306.42it/s]
 44%|████▍     | 561/1274 [3:32:22<4:16:31, 21.59s/it]

Nalmefene

100%|██████████| 14792/14792 [00:12<00:00, 1224.75it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3439.49it/s]

1
1
1
1

 44%|████▍     | 562/1274 [3:32:47<4:27:57, 22.58s/it]

Lacosamide

100%|██████████| 14792/14792 [00:08<00:00, 1757.21it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3473.54it/s]

1
1
1
1

 44%|████▍     | 563/1274 [3:33:08<4:21:34, 22.07s/it]

Prasugrel

100%|██████████| 14792/14792 [00:08<00:00, 1657.02it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3313.85it/s]

1
1

 44%|████▍     | 564/1274 [3:33:30<4:21:03, 22.06s/it]

1
Silodosin

100%|██████████| 14792/14792 [00:09<00:00, 1575.64it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3274.90it/s]

1
1
1
1
1
1

 44%|████▍     | 565/1274 [3:33:53<4:23:07, 22.27s/it]

Silodosin

100%|██████████| 14792/14792 [00:09<00:00, 1557.94it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3259.56it/s]
 44%|████▍     | 566/1274 [3:34:16<4:25:26, 22.50s/it]

Silodosin

100%|██████████| 14792/14792 [00:09<00:00, 1573.85it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3210.49it/s]

1
1

 45%|████▍     | 567/1274 [3:34:39<4:27:48, 22.73s/it]

1
Silodosin

100%|██████████| 14792/14792 [00:08<00:00, 1651.01it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3197.47it/s]
 45%|████▍     | 568/1274 [3:35:02<4:27:04, 22.70s/it]

Silodosin

100%|██████████| 14792/14792 [00:09<00:00, 1573.80it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3123.91it/s]
 45%|████▍     | 569/1274 [3:35:25<4:29:07, 22.90s/it]

1
Nalmefene

100%|██████████| 14792/14792 [00:11<00:00, 1234.02it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3023.45it/s]
 45%|████▍     | 570/1274 [3:35:52<4:40:55, 23.94s/it]

Silodosin

100%|██████████| 14792/14792 [00:09<00:00, 1549.16it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3140.70it/s]

1

 45%|████▍     | 571/1274 [3:36:15<4:39:09, 23.83s/it]

1
Silodosin

100%|██████████| 14792/14792 [00:09<00:00, 1574.98it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2947.47it/s]

1
1
1

 45%|████▍     | 572/1274 [3:36:40<4:40:36, 23.98s/it]

Tapentadol

100%|██████████| 14792/14792 [00:08<00:00, 1825.11it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3277.63it/s]

1
1
1
1
1
1
1
1

 45%|████▍     | 573/1274 [3:37:01<4:30:35, 23.16s/it]

Tapentadol

100%|██████████| 14792/14792 [00:08<00:00, 1763.55it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3446.50it/s]

1
1
1

 45%|████▌     | 574/1274 [3:37:22<4:22:36, 22.51s/it]

1
Tapentadol

100%|██████████| 14792/14792 [00:08<00:00, 1827.70it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3571.94it/s]
 45%|████▌     | 575/1274 [3:37:42<4:14:09, 21.82s/it]

1
Tapentadol

100%|██████████| 14792/14792 [00:08<00:00, 1805.41it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3419.93it/s]

1
1
1
1

 45%|████▌     | 576/1274 [3:38:03<4:11:12, 21.59s/it]

1
1
Lasofoxifene

100%|██████████| 14792/14792 [00:09<00:00, 1610.28it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3063.22it/s]

1
1
1
1
1

 45%|████▌     | 577/1274 [3:38:27<4:17:36, 22.18s/it]

1
1
Nalmefene

100%|██████████| 14792/14792 [00:11<00:00, 1239.96it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3442.41it/s]

1
1
1

 45%|████▌     | 578/1274 [3:38:51<4:25:41, 22.90s/it]

1
Avanafil

100%|██████████| 14792/14792 [00:09<00:00, 1593.85it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3163.04it/s]

1
1
1
1
1
1
1
1
1

 45%|████▌     | 579/1274 [3:39:15<4:27:08, 23.06s/it]

1
1
1
Eucalyptol

100%|██████████| 14792/14792 [00:07<00:00, 1853.49it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3352.59it/s]
 46%|████▌     | 580/1274 [3:39:35<4:17:51, 22.29s/it]

1
1
1
1
1
1
1
1
1
1
1
1
Ambrisentan

100%|██████████| 14792/14792 [00:09<00:00, 1633.70it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3275.01it/s]

1

 46%|████▌     | 581/1274 [3:39:58<4:18:27, 22.38s/it]

1
Midostaurin

100%|██████████| 14792/14792 [00:17<00:00, 822.85it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2953.24it/s]
 46%|████▌     | 582/1274 [3:40:31<4:57:31, 25.80s/it]

1
Prucalopride

100%|██████████| 14792/14792 [00:09<00:00, 1632.46it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3284.34it/s]
 46%|████▌     | 583/1274 [3:40:53<4:43:58, 24.66s/it]

Prucalopride

100%|██████████| 14792/14792 [00:08<00:00, 1670.74it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3423.32it/s]

1
1
1
1
1

 46%|████▌     | 584/1274 [3:41:15<4:32:44, 23.72s/it]

1
Prucalopride

100%|██████████| 14792/14792 [00:09<00:00, 1614.97it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3451.94it/s]
 46%|████▌     | 585/1274 [3:41:37<4:25:53, 23.15s/it]

1
Prucalopride

100%|██████████| 14792/14792 [00:09<00:00, 1627.06it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3321.93it/s]
 46%|████▌     | 586/1274 [3:41:59<4:22:06, 22.86s/it]

Prucalopride

100%|██████████| 14792/14792 [00:08<00:00, 1643.82it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3445.16it/s]

1
1
1

 46%|████▌     | 587/1274 [3:42:20<4:16:49, 22.43s/it]

Prucalopride

100%|██████████| 14792/14792 [00:08<00:00, 1644.02it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3344.55it/s]

1
1
1
1

 46%|████▌     | 588/1274 [3:42:42<4:15:08, 22.32s/it]

Ambrisentan

100%|██████████| 14792/14792 [00:09<00:00, 1638.43it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3386.09it/s]

1
1

 46%|████▌     | 589/1274 [3:43:04<4:13:49, 22.23s/it]

Levocetirizine

100%|██████████| 14792/14792 [00:08<00:00, 1679.39it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3323.08it/s]
 46%|████▋     | 590/1274 [3:43:26<4:12:11, 22.12s/it]

1
1
Saxagliptin

100%|██████████| 14792/14792 [00:09<00:00, 1599.74it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3326.01it/s]
 46%|████▋     | 591/1274 [3:43:49<4:12:47, 22.21s/it]

1
1
Dapagliflozin

100%|██████████| 14792/14792 [00:08<00:00, 1682.98it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3280.82it/s]

1
1

 46%|████▋     | 592/1274 [3:44:11<4:13:31, 22.30s/it]

1
1
Dapagliflozin

100%|██████████| 14792/14792 [00:08<00:00, 1677.17it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3238.54it/s]

1
1
1

 47%|████▋     | 593/1274 [3:44:34<4:14:04, 22.38s/it]

Dapagliflozin

100%|██████████| 14792/14792 [00:09<00:00, 1642.06it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3152.68it/s]

1
1
1
1

 47%|████▋     | 594/1274 [3:44:57<4:16:43, 22.65s/it]

1
Levocetirizine

100%|██████████| 14792/14792 [00:08<00:00, 1674.93it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3400.51it/s]
 47%|████▋     | 595/1274 [3:45:19<4:12:43, 22.33s/it]

Levocetirizine

100%|██████████| 14792/14792 [00:08<00:00, 1718.41it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3444.52it/s]
 47%|████▋     | 596/1274 [3:45:40<4:09:32, 22.08s/it]

Levocetirizine

100%|██████████| 14792/14792 [00:08<00:00, 1707.59it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3449.71it/s]
 47%|████▋     | 597/1274 [3:46:02<4:07:24, 21.93s/it]

Lasofoxifene

100%|██████████| 14792/14792 [00:09<00:00, 1547.45it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3290.32it/s]

1
1
1
1
1
1

 47%|████▋     | 598/1274 [3:46:25<4:10:51, 22.27s/it]

1
Rufinamide

100%|██████████| 14792/14792 [00:08<00:00, 1718.49it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3422.14it/s]
 47%|████▋     | 599/1274 [3:46:46<4:06:30, 21.91s/it]

1
Pentaerythritol tetranitrate

100%|██████████| 14792/14792 [00:07<00:00, 1871.66it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3634.14it/s]
 47%|████▋     | 600/1274 [3:47:05<3:57:47, 21.17s/it]

Dronedarone

100%|██████████| 14792/14792 [00:09<00:00, 1538.35it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3200.84it/s]
 47%|████▋     | 601/1274 [3:47:29<4:04:49, 21.83s/it]

Vildagliptin

100%|██████████| 14792/14792 [00:09<00:00, 1566.01it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3345.47it/s]

1
1

 47%|████▋     | 602/1274 [3:47:51<4:07:07, 22.06s/it]

Vildagliptin

100%|██████████| 14792/14792 [00:10<00:00, 1476.31it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3306.08it/s]
 47%|████▋     | 603/1274 [3:48:14<4:09:51, 22.34s/it]

Vildagliptin

100%|██████████| 14792/14792 [00:09<00:00, 1548.58it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3504.37it/s]

1

 47%|████▋     | 604/1274 [3:48:36<4:07:52, 22.20s/it]

1
1
Lorcaserin

100%|██████████| 14792/14792 [00:08<00:00, 1805.31it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3501.83it/s]
 47%|████▋     | 605/1274 [3:48:57<4:01:28, 21.66s/it]

Lorcaserin

100%|██████████| 14792/14792 [00:08<00:00, 1763.96it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3498.77it/s]
 48%|████▊     | 606/1274 [3:49:17<3:57:47, 21.36s/it]

1
Nebivolol

100%|██████████| 14792/14792 [00:09<00:00, 1568.09it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3326.38it/s]

1
1
1
1
1

 48%|████▊     | 607/1274 [3:49:40<4:01:05, 21.69s/it]

1
Dronedarone

100%|██████████| 14792/14792 [00:09<00:00, 1593.08it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3286.22it/s]
 48%|████▊     | 608/1274 [3:50:02<4:03:53, 21.97s/it]

Tetrabenazine

100%|██████████| 14792/14792 [00:09<00:00, 1586.01it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3371.04it/s]

1
1
1
1
1

 48%|████▊     | 609/1274 [3:50:25<4:04:39, 22.07s/it]

1
Pentaerythritol tetranitrate

100%|██████████| 14792/14792 [00:07<00:00, 1857.70it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3549.24it/s]
 48%|████▊     | 610/1274 [3:50:45<3:57:17, 21.44s/it]

1
Tetrabenazine

100%|██████████| 14792/14792 [00:09<00:00, 1552.56it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3485.49it/s]

1
1
1
1
1

 48%|████▊     | 611/1274 [3:51:06<3:58:19, 21.57s/it]

1
Flunarizine

100%|██████████| 14792/14792 [00:08<00:00, 1681.02it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3276.99it/s]
 48%|████▊     | 612/1274 [3:51:29<3:59:30, 21.71s/it]

Flunarizine

100%|██████████| 14792/14792 [00:09<00:00, 1621.14it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3285.77it/s]

1
1
1
1

 48%|████▊     | 613/1274 [3:51:51<4:01:07, 21.89s/it]

1
1
Flunarizine

100%|██████████| 14792/14792 [00:09<00:00, 1620.48it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3355.29it/s]
 48%|████▊     | 614/1274 [3:52:13<4:01:13, 21.93s/it]

Cyproterone acetate

100%|██████████| 14792/14792 [00:10<00:00, 1378.24it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3383.25it/s]

1
1
1
1
1
1
1
1
1

 48%|████▊     | 615/1274 [3:52:37<4:06:57, 22.48s/it]

1
1
1
Estrone sulfate

100%|██████████| 14792/14792 [00:09<00:00, 1518.64it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3262.94it/s]
 48%|████▊     | 616/1274 [3:53:00<4:07:56, 22.61s/it]

Estrone sulfate

100%|██████████| 14792/14792 [00:10<00:00, 1429.40it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3338.61it/s]

1

 48%|████▊     | 617/1274 [3:53:23<4:09:42, 22.80s/it]

Vildagliptin

100%|██████████| 14792/14792 [00:09<00:00, 1580.74it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3276.92it/s]
 49%|████▊     | 618/1274 [3:53:45<4:08:52, 22.76s/it]

1
Vildagliptin

100%|██████████| 14792/14792 [00:09<00:00, 1499.05it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3339.82it/s]
 49%|████▊     | 619/1274 [3:54:08<4:08:57, 22.81s/it]

Milnacipran

100%|██████████| 14792/14792 [00:08<00:00, 1820.12it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3467.08it/s]
 49%|████▊     | 620/1274 [3:54:29<4:00:34, 22.07s/it]

Milnacipran

100%|██████████| 14792/14792 [00:08<00:00, 1772.42it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3481.22it/s]
 49%|████▊     | 621/1274 [3:54:50<3:56:18, 21.71s/it]

Pentaerythritol tetranitrate

100%|██████████| 14792/14792 [00:08<00:00, 1821.92it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3447.75it/s]
 49%|████▉     | 622/1274 [3:55:10<3:51:50, 21.33s/it]

Pentaerythritol tetranitrate

100%|██████████| 14792/14792 [00:08<00:00, 1785.65it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3441.71it/s]
 49%|████▉     | 623/1274 [3:55:31<3:48:56, 21.10s/it]

Pizotifen

100%|██████████| 14792/14792 [00:09<00:00, 1550.02it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3257.93it/s]
 49%|████▉     | 624/1274 [3:55:53<3:53:28, 21.55s/it]

Cariprazine

100%|██████████| 14792/14792 [00:08<00:00, 1710.21it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3377.47it/s]
 49%|████▉     | 625/1274 [3:56:15<3:52:52, 21.53s/it]

Cariprazine

100%|██████████| 14792/14792 [00:08<00:00, 1647.40it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3438.39it/s]

1
1
1
1
1
1
1
1

 49%|████▉     | 626/1274 [3:56:36<3:52:25, 21.52s/it]

Abiraterone

100%|██████████| 14792/14792 [00:10<00:00, 1420.37it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3292.46it/s]
 49%|████▉     | 627/1274 [3:57:00<4:00:04, 22.26s/it]

1
Abiraterone

100%|██████████| 14792/14792 [00:10<00:00, 1400.87it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3310.32it/s]

1
1

 49%|████▉     | 628/1274 [3:57:24<4:05:32, 22.81s/it]

1
Apremilast

100%|██████████| 14792/14792 [00:09<00:00, 1636.87it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3363.18it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

 49%|████▉     | 629/1274 [3:57:47<4:03:32, 22.65s/it]

Telaprevir

100%|██████████| 14792/14792 [00:09<00:00, 1514.85it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3201.01it/s]

1

 49%|████▉     | 630/1274 [3:58:10<4:06:08, 22.93s/it]

Dexlansoprazole

100%|██████████| 14792/14792 [00:09<00:00, 1635.08it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3388.09it/s]
 50%|████▉     | 631/1274 [3:58:32<4:02:10, 22.60s/it]

Dexlansoprazole

100%|██████████| 14792/14792 [00:08<00:00, 1700.40it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3232.86it/s]
 50%|████▉     | 632/1274 [3:58:54<4:00:45, 22.50s/it]

1
1
1
1
Dexlansoprazole

100%|██████████| 14792/14792 [00:08<00:00, 1666.33it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3408.69it/s]
 50%|████▉     | 633/1274 [3:59:16<3:57:11, 22.20s/it]

1
Dexlansoprazole

100%|██████████| 14792/14792 [00:08<00:00, 1716.00it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3212.29it/s]

1
1
1
1
1
1
1
1

 50%|████▉     | 634/1274 [3:59:38<3:56:10, 22.14s/it]

1
1
1
1
Ataluren

100%|██████████| 14792/14792 [00:08<00:00, 1679.94it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3091.63it/s]
 50%|████▉     | 635/1274 [4:00:01<3:58:04, 22.35s/it]

Pirfenidone

100%|██████████| 14792/14792 [00:08<00:00, 1800.02it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3438.67it/s]

1
1
1

 50%|████▉     | 636/1274 [4:00:21<3:52:06, 21.83s/it]

Tacrolimus

100%|██████████| 14792/14792 [00:10<00:00, 1359.00it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2886.83it/s]

1
1
1
1

 50%|█████     | 637/1274 [4:00:49<4:10:31, 23.60s/it]

Tacrolimus

100%|██████████| 14792/14792 [00:10<00:00, 1368.58it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2750.32it/s]

1
1
1
1

 50%|█████     | 638/1274 [4:01:17<4:25:02, 25.00s/it]

Tacrolimus

100%|██████████| 14792/14792 [00:10<00:00, 1349.22it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2918.07it/s]

1
1
1
1

 50%|█████     | 639/1274 [4:01:45<4:33:01, 25.80s/it]

Acetohexamide

100%|██████████| 14792/14792 [00:08<00:00, 1659.86it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3422.75it/s]

1
1
1
1
1

 50%|█████     | 640/1274 [4:02:06<4:19:01, 24.51s/it]

Zolpidem

100%|██████████| 14792/14792 [00:08<00:00, 1727.40it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3160.06it/s]
 50%|█████     | 641/1274 [4:02:29<4:11:20, 23.82s/it]

1
Hyoscyamine

100%|██████████| 14792/14792 [00:08<00:00, 1743.64it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3440.73it/s]

1
1

 50%|█████     | 642/1274 [4:02:50<4:02:42, 23.04s/it]

1
1
Hyoscyamine

100%|██████████| 14792/14792 [00:08<00:00, 1677.31it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3360.35it/s]

1
1
1

 50%|█████     | 643/1274 [4:03:12<3:58:35, 22.69s/it]

1
Methocarbamol

100%|██████████| 14792/14792 [00:08<00:00, 1773.71it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3394.02it/s]

1
1
1
1

 51%|█████     | 644/1274 [4:03:33<3:53:26, 22.23s/it]

1
1
Methocarbamol

100%|██████████| 14792/14792 [00:08<00:00, 1782.16it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3064.47it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

 51%|█████     | 645/1274 [4:03:55<3:52:54, 22.22s/it]

Methylphenidate

100%|██████████| 14792/14792 [00:08<00:00, 1778.19it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3289.06it/s]

1
1
1
1
1
1
1
1
1
1
1
1

 51%|█████     | 646/1274 [4:04:16<3:49:45, 21.95s/it]

Spironolactone

100%|██████████| 14792/14792 [00:10<00:00, 1363.65it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3197.05it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1

 51%|█████     | 647/1274 [4:04:41<3:58:14, 22.80s/it]

Rosiglitazone

100%|██████████| 14792/14792 [00:08<00:00, 1663.25it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3214.88it/s]

1
1
1
1

 51%|█████     | 648/1274 [4:05:03<3:56:33, 22.67s/it]

1
1
1
Zolpidem

100%|██████████| 14792/14792 [00:09<00:00, 1631.99it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3011.56it/s]

1

 51%|█████     | 649/1274 [4:05:27<3:58:07, 22.86s/it]

1
1
Rosiglitazone

100%|██████████| 14792/14792 [00:08<00:00, 1653.84it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3266.24it/s]
 51%|█████     | 650/1274 [4:05:49<3:55:12, 22.62s/it]

Rosiglitazone

100%|██████████| 14792/14792 [00:08<00:00, 1720.73it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2936.45it/s]

1
1
1
1

 51%|█████     | 651/1274 [4:06:12<3:55:27, 22.68s/it]

1
1
1
Rosiglitazone

100%|██████████| 14792/14792 [00:08<00:00, 1692.71it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3313.04it/s]

1
1
1
1
1
1

 51%|█████     | 652/1274 [4:06:33<3:52:10, 22.40s/it]

Rosiglitazone

100%|██████████| 14792/14792 [00:08<00:00, 1733.12it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3327.62it/s]
 51%|█████▏    | 653/1274 [4:06:55<3:48:39, 22.09s/it]

Eszopiclone

100%|██████████| 14792/14792 [00:09<00:00, 1642.73it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3375.84it/s]
 51%|█████▏    | 654/1274 [4:07:16<3:46:26, 21.91s/it]

1
1
Eszopiclone

100%|██████████| 14792/14792 [00:09<00:00, 1621.35it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3232.02it/s]

1
1
1
1

 51%|█████▏    | 655/1274 [4:07:39<3:47:43, 22.07s/it]

Eszopiclone

100%|██████████| 14792/14792 [00:09<00:00, 1592.97it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3346.34it/s]
 51%|█████▏    | 656/1274 [4:08:01<3:47:43, 22.11s/it]

1
Zolpidem

100%|██████████| 14792/14792 [00:08<00:00, 1734.80it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3320.63it/s]

1

 52%|█████▏    | 657/1274 [4:08:23<3:46:06, 21.99s/it]

1
Famciclovir

100%|██████████| 14792/14792 [00:08<00:00, 1738.54it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3445.81it/s]

1
1
1
1
1

 52%|█████▏    | 658/1274 [4:08:44<3:43:06, 21.73s/it]

1
1
Progesterone

100%|██████████| 14792/14792 [00:10<00:00, 1435.55it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3597.54it/s]

1
1
1

 52%|█████▏    | 659/1274 [4:09:06<3:45:33, 22.01s/it]

Trimethoprim

100%|██████████| 14792/14792 [00:08<00:00, 1768.64it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3271.93it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

 52%|█████▏    | 660/1274 [4:09:28<3:43:12, 21.81s/it]

Liothyronine

100%|██████████| 14792/14792 [00:08<00:00, 1715.93it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3397.96it/s]
 52%|█████▏    | 661/1274 [4:09:49<3:42:26, 21.77s/it]

1
Liothyronine

100%|██████████| 14792/14792 [00:08<00:00, 1743.48it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3339.05it/s]

1
1

 52%|█████▏    | 662/1274 [4:10:11<3:41:50, 21.75s/it]

Levothyroxine

100%|██████████| 14792/14792 [00:08<00:00, 1805.36it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3498.24it/s]

1
1

 52%|█████▏    | 663/1274 [4:10:32<3:37:54, 21.40s/it]

Lansoprazole

100%|██████████| 14792/14792 [00:08<00:00, 1651.11it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3596.87it/s]
 52%|█████▏    | 664/1274 [4:10:53<3:36:28, 21.29s/it]

1
Lansoprazole

100%|██████████| 14792/14792 [00:08<00:00, 1704.12it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3285.11it/s]
 52%|█████▏    | 665/1274 [4:11:15<3:38:04, 21.48s/it]

Trimethoprim

100%|██████████| 14792/14792 [00:08<00:00, 1707.78it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3400.04it/s]
 52%|█████▏    | 666/1274 [4:11:36<3:37:08, 21.43s/it]

Trimethoprim

100%|██████████| 14792/14792 [00:08<00:00, 1744.80it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3423.03it/s]
 52%|█████▏    | 667/1274 [4:11:57<3:35:30, 21.30s/it]

1
1
1
1
Trimethoprim

100%|██████████| 14792/14792 [00:08<00:00, 1730.12it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3251.37it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

 52%|█████▏    | 668/1274 [4:12:19<3:36:41, 21.45s/it]

Trifluridine

100%|██████████| 14792/14792 [00:08<00:00, 1737.93it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3299.07it/s]
 53%|█████▎    | 669/1274 [4:12:40<3:36:43, 21.49s/it]

Trimethoprim

100%|██████████| 14792/14792 [00:08<00:00, 1700.43it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3572.37it/s]
 53%|█████▎    | 670/1274 [4:13:01<3:34:35, 21.32s/it]

1
Trimethoprim

100%|██████████| 14792/14792 [00:08<00:00, 1727.61it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3456.13it/s]
 53%|█████▎    | 671/1274 [4:13:22<3:33:50, 21.28s/it]

1
Cyproheptadine

100%|██████████| 14792/14792 [00:09<00:00, 1570.76it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3295.27it/s]
 53%|█████▎    | 672/1274 [4:13:45<3:37:04, 21.63s/it]

Prochlorperazine

100%|██████████| 14792/14792 [00:09<00:00, 1545.05it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3540.96it/s]

1
1
1
1
1

 53%|█████▎    | 673/1274 [4:14:07<3:37:27, 21.71s/it]

1
Prochlorperazine

100%|██████████| 14792/14792 [00:09<00:00, 1580.10it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3352.46it/s]
 53%|█████▎    | 674/1274 [4:14:29<3:39:26, 21.94s/it]

1
Prochlorperazine

100%|██████████| 14792/14792 [00:09<00:00, 1521.88it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3047.57it/s]

1
1
1
1

 53%|█████▎    | 675/1274 [4:14:53<3:44:30, 22.49s/it]

Trifluridine

100%|██████████| 14792/14792 [00:08<00:00, 1779.98it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3397.03it/s]

1
1
1
1

 53%|█████▎    | 676/1274 [4:15:14<3:39:24, 22.01s/it]

Griseofulvin

100%|██████████| 14792/14792 [00:09<00:00, 1599.35it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3300.17it/s]
 53%|█████▎    | 677/1274 [4:15:36<3:40:06, 22.12s/it]

Progesterone

100%|██████████| 14792/14792 [00:09<00:00, 1494.64it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3488.45it/s]

1
1
1
1
1
1
1
1
1

 53%|█████▎    | 678/1274 [4:15:59<3:41:37, 22.31s/it]

1
1
1
Prazosin

100%|██████████| 14792/14792 [00:09<00:00, 1545.44it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3139.37it/s]
 53%|█████▎    | 679/1274 [4:16:22<3:44:09, 22.60s/it]

Omeprazole

100%|██████████| 14792/14792 [00:08<00:00, 1668.66it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3266.29it/s]
 53%|█████▎    | 680/1274 [4:16:45<3:42:42, 22.50s/it]

1
1
Trimethadione

100%|██████████| 14792/14792 [00:08<00:00, 1839.60it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3472.00it/s]
 53%|█████▎    | 681/1274 [4:17:05<3:35:31, 21.81s/it]

1
1
1
1
Diltiazem

100%|██████████| 14792/14792 [00:09<00:00, 1592.46it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3356.08it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

 54%|█████▎    | 682/1274 [4:17:28<3:37:41, 22.06s/it]

Diltiazem

100%|██████████| 14792/14792 [00:09<00:00, 1628.19it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3058.68it/s]

1
1
1
1

 54%|█████▎    | 683/1274 [4:17:51<3:41:22, 22.47s/it]

Diltiazem

100%|██████████| 14792/14792 [00:09<00:00, 1625.60it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3318.61it/s]

1
1
1
1

 54%|█████▎    | 684/1274 [4:18:13<3:40:17, 22.40s/it]

1
1
1
1
Terfenadine

100%|██████████| 14792/14792 [00:09<00:00, 1569.03it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3090.47it/s]
 54%|█████▍    | 685/1274 [4:18:37<3:43:07, 22.73s/it]

1
Pyrazinamide

100%|██████████| 14792/14792 [00:07<00:00, 1869.66it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3214.55it/s]
 54%|█████▍    | 686/1274 [4:18:58<3:37:18, 22.17s/it]

1
1
1
1
1
Omeprazole

100%|██████████| 14792/14792 [00:09<00:00, 1605.71it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3220.30it/s]

1

 54%|█████▍    | 687/1274 [4:19:20<3:38:11, 22.30s/it]

1
1
Omeprazole

100%|██████████| 14792/14792 [00:08<00:00, 1664.12it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3283.91it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

 54%|█████▍    | 688/1274 [4:19:42<3:37:36, 22.28s/it]

Clobazam

100%|██████████| 14792/14792 [00:08<00:00, 1658.50it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3228.33it/s]

1
1
1
1

 54%|█████▍    | 689/1274 [4:20:05<3:37:32, 22.31s/it]

1
1
Omeprazole

100%|██████████| 14792/14792 [00:08<00:00, 1710.62it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3104.27it/s]

1

 54%|█████▍    | 690/1274 [4:20:27<3:37:33, 22.35s/it]

1
1
1
Atenolol

100%|██████████| 14792/14792 [00:08<00:00, 1824.13it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3406.39it/s]

1
1

 54%|█████▍    | 691/1274 [4:20:48<3:33:14, 21.95s/it]

1
Atenolol

100%|██████████| 14792/14792 [00:08<00:00, 1771.76it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3227.38it/s]

1
1
1
1

 54%|█████▍    | 692/1274 [4:21:10<3:32:10, 21.87s/it]

1
1
1
Olanzapine

100%|██████████| 14792/14792 [00:09<00:00, 1549.15it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3214.99it/s]
 54%|█████▍    | 693/1274 [4:21:33<3:34:41, 22.17s/it]

Olanzapine

100%|██████████| 14792/14792 [00:09<00:00, 1537.69it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3255.39it/s]
 54%|█████▍    | 694/1274 [4:21:56<3:36:53, 22.44s/it]

Olanzapine

100%|██████████| 14792/14792 [00:09<00:00, 1500.02it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3207.26it/s]

1

 55%|█████▍    | 695/1274 [4:22:19<3:39:22, 22.73s/it]

1
Olanzapine

100%|██████████| 14792/14792 [00:09<00:00, 1559.55it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3202.80it/s]
 55%|█████▍    | 696/1274 [4:22:42<3:39:31, 22.79s/it]

1
1
1
1
Clobazam

100%|██████████| 14792/14792 [00:08<00:00, 1737.01it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3378.05it/s]

1
1
1
1
1

 55%|█████▍    | 697/1274 [4:23:04<3:35:15, 22.38s/it]

Tioguanine

100%|██████████| 14792/14792 [00:08<00:00, 1728.09it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3439.89it/s]
 55%|█████▍    | 698/1274 [4:23:24<3:30:29, 21.93s/it]

Digoxin

100%|██████████| 14792/14792 [00:12<00:00, 1219.42it/s]
100%|██████████| 34899/34899 [00:20<00:00, 1661.86it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1

 55%|█████▍    | 699/1274 [4:24:02<4:15:35, 26.67s/it]

Treprostinil

100%|██████████| 14792/14792 [00:09<00:00, 1587.82it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3306.58it/s]
 55%|█████▍    | 700/1274 [4:24:25<4:04:56, 25.60s/it]

Digoxin

100%|██████████| 14792/14792 [00:12<00:00, 1181.76it/s]
100%|██████████| 34899/34899 [00:20<00:00, 1722.31it/s]

1
1
1

 55%|█████▌    | 701/1274 [4:25:03<4:37:50, 29.09s/it]

Phenylephrine

100%|██████████| 14792/14792 [00:08<00:00, 1785.81it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3285.76it/s]
 55%|█████▌    | 702/1274 [4:25:24<4:15:24, 26.79s/it]

Triamterene

100%|██████████| 14792/14792 [00:09<00:00, 1609.64it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3318.86it/s]

1
1
1
1
1

 55%|█████▌    | 703/1274 [4:25:46<4:01:59, 25.43s/it]

1
Mexiletine

100%|██████████| 14792/14792 [00:08<00:00, 1797.15it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3336.26it/s]
 55%|█████▌    | 704/1274 [4:26:07<3:49:34, 24.17s/it]

1
1
1
1
1
1
Mexiletine

100%|██████████| 14792/14792 [00:08<00:00, 1779.33it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3078.55it/s]
 55%|█████▌    | 705/1274 [4:26:29<3:42:29, 23.46s/it]

1
1
Treprostinil

100%|██████████| 14792/14792 [00:09<00:00, 1579.08it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3262.92it/s]

1
1

 55%|█████▌    | 706/1274 [4:26:53<3:42:21, 23.49s/it]

Treprostinil

100%|██████████| 14792/14792 [00:09<00:00, 1591.14it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3241.22it/s]
 55%|█████▌    | 707/1274 [4:27:16<3:40:59, 23.39s/it]

Treprostinil

100%|██████████| 14792/14792 [00:09<00:00, 1538.41it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3177.64it/s]
 56%|█████▌    | 708/1274 [4:27:40<3:41:43, 23.50s/it]

Chlorzoxazone

100%|██████████| 14792/14792 [00:07<00:00, 1876.95it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2949.14it/s]
 56%|█████▌    | 709/1274 [4:28:02<3:36:39, 23.01s/it]

1
1
1
1
1
1
1
Mirtazapine

100%|██████████| 14792/14792 [00:09<00:00, 1508.31it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3242.69it/s]

1
1
1
1

 56%|█████▌    | 710/1274 [4:28:25<3:36:02, 22.98s/it]

1
1
Mirtazapine

100%|██████████| 14792/14792 [00:10<00:00, 1441.70it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3065.18it/s]

1
1
1
1

 56%|█████▌    | 711/1274 [4:28:49<3:38:45, 23.31s/it]

Mirtazapine

100%|██████████| 14792/14792 [00:09<00:00, 1498.03it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3167.41it/s]
 56%|█████▌    | 712/1274 [4:29:12<3:38:13, 23.30s/it]

1
Clozapine

100%|██████████| 14792/14792 [00:09<00:00, 1502.85it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3103.15it/s]
 56%|█████▌    | 713/1274 [4:29:35<3:38:36, 23.38s/it]

Clozapine

100%|██████████| 14792/14792 [00:09<00:00, 1528.05it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3407.00it/s]
 56%|█████▌    | 714/1274 [4:29:58<3:35:30, 23.09s/it]

1
Clozapine

100%|██████████| 14792/14792 [00:09<00:00, 1531.77it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3172.48it/s]

1
1
1
1

 56%|█████▌    | 715/1274 [4:30:21<3:35:29, 23.13s/it]

Mefloquine

100%|██████████| 14792/14792 [00:08<00:00, 1652.56it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3195.39it/s]
 56%|█████▌    | 716/1274 [4:30:43<3:32:23, 22.84s/it]

Loratadine

100%|██████████| 14792/14792 [00:09<00:00, 1508.89it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3244.37it/s]
 56%|█████▋    | 717/1274 [4:31:06<3:32:46, 22.92s/it]

Prazosin

100%|██████████| 14792/14792 [00:09<00:00, 1567.93it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2954.69it/s]
 56%|█████▋    | 718/1274 [4:31:30<3:35:14, 23.23s/it]

Tacrolimus

100%|██████████| 14792/14792 [00:10<00:00, 1422.48it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2891.19it/s]

1
1
1
1

 56%|█████▋    | 719/1274 [4:31:57<3:45:38, 24.39s/it]

Buspirone

100%|██████████| 14792/14792 [00:09<00:00, 1538.94it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3207.54it/s]

1
1
1
1
1
1
1
1
1

 57%|█████▋    | 720/1274 [4:32:20<3:41:03, 23.94s/it]

1
1
1
Oxycodone

100%|██████████| 14792/14792 [00:12<00:00, 1214.44it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3393.12it/s]

1
1
1

 57%|█████▋    | 721/1274 [4:32:45<3:43:30, 24.25s/it]

Oxycodone

100%|██████████| 14792/14792 [00:11<00:00, 1232.89it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3416.49it/s]

1
1
1
1

 57%|█████▋    | 722/1274 [4:33:10<3:44:03, 24.35s/it]

Oxycodone

100%|██████████| 14792/14792 [00:12<00:00, 1230.07it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3126.44it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

 57%|█████▋    | 723/1274 [4:33:36<3:47:55, 24.82s/it]

Zidovudine

100%|██████████| 14792/14792 [00:08<00:00, 1705.57it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3240.81it/s]
 57%|█████▋    | 724/1274 [4:33:58<3:39:44, 23.97s/it]

Zidovudine

100%|██████████| 14792/14792 [00:08<00:00, 1728.16it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3228.05it/s]

1
1
1

 57%|█████▋    | 725/1274 [4:34:20<3:33:44, 23.36s/it]

Buspirone

100%|██████████| 14792/14792 [00:09<00:00, 1569.56it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3027.89it/s]

1
1
1
1
1
1
1
1
1
1
1

 57%|█████▋    | 726/1274 [4:34:43<3:33:25, 23.37s/it]

1
1
Buspirone

100%|██████████| 14792/14792 [00:09<00:00, 1603.49it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3034.81it/s]

1
1
1
1

 57%|█████▋    | 727/1274 [4:35:07<3:33:20, 23.40s/it]

1
1
Buspirone

100%|██████████| 14792/14792 [00:09<00:00, 1564.54it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3121.04it/s]
 57%|█████▋    | 728/1274 [4:35:30<3:32:41, 23.37s/it]

1
Flutamide

100%|██████████| 14792/14792 [00:08<00:00, 1824.81it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3600.26it/s]

1
1
1

 57%|█████▋    | 729/1274 [4:35:50<3:23:15, 22.38s/it]

Buspirone

100%|██████████| 14792/14792 [00:09<00:00, 1529.05it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2874.98it/s]
 57%|█████▋    | 730/1274 [4:36:14<3:27:31, 22.89s/it]

Celecoxib

100%|██████████| 14792/14792 [00:08<00:00, 1655.53it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3269.44it/s]

1

 57%|█████▋    | 731/1274 [4:36:36<3:24:46, 22.63s/it]

1
Raloxifene

100%|██████████| 14792/14792 [00:09<00:00, 1527.01it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2903.42it/s]
 57%|█████▋    | 732/1274 [4:37:01<3:30:39, 23.32s/it]

Raloxifene

100%|██████████| 14792/14792 [00:09<00:00, 1533.21it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3120.54it/s]
 58%|█████▊    | 733/1274 [4:37:25<3:32:45, 23.60s/it]

Raloxifene

100%|██████████| 14792/14792 [00:09<00:00, 1578.72it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3201.83it/s]
 58%|█████▊    | 734/1274 [4:37:49<3:32:22, 23.60s/it]

Lenalidomide

100%|██████████| 14792/14792 [00:08<00:00, 1685.32it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3393.29it/s]

1

 58%|█████▊    | 735/1274 [4:38:10<3:26:32, 22.99s/it]

Lenalidomide

100%|██████████| 14792/14792 [00:09<00:00, 1634.24it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3318.90it/s]

1
1
1
1

 58%|█████▊    | 736/1274 [4:38:32<3:23:40, 22.71s/it]

1
1
Oxycodone

100%|██████████| 14792/14792 [00:11<00:00, 1260.43it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3246.95it/s]

1
1
1

 58%|█████▊    | 737/1274 [4:38:58<3:29:42, 23.43s/it]

Tolmetin

100%|██████████| 14792/14792 [00:08<00:00, 1737.69it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3437.93it/s]

1
1

 58%|█████▊    | 738/1274 [4:39:19<3:22:43, 22.69s/it]

Chlorpromazine

100%|██████████| 14792/14792 [00:09<00:00, 1622.22it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3181.23it/s]
 58%|█████▊    | 739/1274 [4:39:41<3:22:10, 22.67s/it]

1
Ritonavir

100%|██████████| 14792/14792 [00:09<00:00, 1580.04it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2890.95it/s]
 58%|█████▊    | 740/1274 [4:40:06<3:27:47, 23.35s/it]

Dextrothyroxine

100%|██████████| 14792/14792 [00:08<00:00, 1728.17it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3029.58it/s]

1
1
1

 58%|█████▊    | 741/1274 [4:40:29<3:25:58, 23.19s/it]

1
Dextrothyroxine

100%|██████████| 14792/14792 [00:08<00:00, 1692.61it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3382.19it/s]

1
1
1

 58%|█████▊    | 742/1274 [4:40:50<3:21:19, 22.71s/it]

1
Nitazoxanide

100%|██████████| 14792/14792 [00:08<00:00, 1816.43it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3557.03it/s]
 58%|█████▊    | 743/1274 [4:41:11<3:15:47, 22.12s/it]

Nitazoxanide

100%|██████████| 14792/14792 [00:08<00:00, 1729.69it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3458.25it/s]

1
1
1

 58%|█████▊    | 744/1274 [4:41:32<3:12:40, 21.81s/it]

1
Ritonavir

100%|██████████| 14792/14792 [00:09<00:00, 1536.25it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3216.61it/s]

1
1

 58%|█████▊    | 745/1274 [4:41:56<3:17:56, 22.45s/it]

Ritonavir

100%|██████████| 14792/14792 [00:09<00:00, 1573.65it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3005.21it/s]

1
1
1
1

 59%|█████▊    | 746/1274 [4:42:21<3:22:25, 23.00s/it]

Ritonavir

100%|██████████| 14792/14792 [00:09<00:00, 1545.18it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3006.81it/s]
 59%|█████▊    | 747/1274 [4:42:45<3:26:46, 23.54s/it]

Haloperidol

100%|██████████| 14792/14792 [00:08<00:00, 1656.43it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3307.37it/s]
 59%|█████▊    | 748/1274 [4:43:07<3:22:38, 23.12s/it]

Cimetidine

100%|██████████| 14792/14792 [00:08<00:00, 1752.09it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3496.81it/s]
 59%|█████▉    | 749/1274 [4:43:28<3:15:43, 22.37s/it]

1
1
1
Haloperidol

100%|██████████| 14792/14792 [00:08<00:00, 1667.70it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3112.36it/s]
 59%|█████▉    | 750/1274 [4:43:51<3:16:26, 22.49s/it]

Haloperidol

100%|██████████| 14792/14792 [00:09<00:00, 1635.30it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2993.65it/s]
 59%|█████▉    | 751/1274 [4:44:14<3:18:19, 22.75s/it]

Haloperidol

100%|██████████| 14792/14792 [00:08<00:00, 1735.22it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3158.06it/s]

1
1

 59%|█████▉    | 752/1274 [4:44:37<3:16:42, 22.61s/it]

Haloperidol

100%|██████████| 14792/14792 [00:08<00:00, 1646.29it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3385.73it/s]

1
1
1

 59%|█████▉    | 753/1274 [4:44:58<3:14:37, 22.41s/it]

Haloperidol

100%|██████████| 14792/14792 [00:08<00:00, 1667.29it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3436.30it/s]
 59%|█████▉    | 754/1274 [4:45:20<3:11:57, 22.15s/it]

Haloperidol

100%|██████████| 14792/14792 [00:09<00:00, 1609.69it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3270.10it/s]
 59%|█████▉    | 755/1274 [4:45:42<3:12:11, 22.22s/it]

Cimetidine

100%|██████████| 14792/14792 [00:08<00:00, 1751.70it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3330.41it/s]
 59%|█████▉    | 756/1274 [4:46:04<3:09:01, 21.90s/it]

1
1
1
Chlorpromazine

100%|██████████| 14792/14792 [00:09<00:00, 1570.96it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3229.49it/s]
 59%|█████▉    | 757/1274 [4:46:27<3:11:40, 22.24s/it]

Chlorpromazine

100%|██████████| 14792/14792 [00:09<00:00, 1574.56it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3251.72it/s]

1
1
1
1
1
1
1
1

 59%|█████▉    | 758/1274 [4:46:49<3:12:20, 22.36s/it]

Nabumetone

100%|██████████| 14792/14792 [00:08<00:00, 1793.86it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3485.99it/s]

1
1
1
1
1
1
1
1
1
1
1

 60%|█████▉    | 759/1274 [4:47:10<3:07:50, 21.88s/it]

1
1
Dronabinol

100%|██████████| 14792/14792 [00:09<00:00, 1575.32it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3324.26it/s]

1
1
1
1
1
1
1
1
1

 60%|█████▉    | 760/1274 [4:47:33<3:09:35, 22.13s/it]

1
1
1
Dronabinol

100%|██████████| 14792/14792 [00:09<00:00, 1552.05it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3439.16it/s]

1
1
1
1
1
1
1
1
1

 60%|█████▉    | 761/1274 [4:47:55<3:09:16, 22.14s/it]

1
1
1
1
Dronabinol

100%|██████████| 14792/14792 [00:09<00:00, 1524.04it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3289.80it/s]

1
1
1
1
1
1
1
1
1

 60%|█████▉    | 762/1274 [4:48:18<3:10:48, 22.36s/it]

1
1
1
1
Dronabinol

100%|██████████| 14792/14792 [00:09<00:00, 1562.93it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3611.35it/s]

1
1
1
1
1
1
1
1
1

 60%|█████▉    | 763/1274 [4:48:39<3:08:17, 22.11s/it]

1
1
1
Dronabinol

100%|██████████| 14792/14792 [00:09<00:00, 1573.36it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3464.70it/s]

1
1
1
1
1
1
1
1
1

 60%|█████▉    | 764/1274 [4:49:01<3:07:52, 22.10s/it]

1
1
1
Dronabinol

100%|██████████| 14792/14792 [00:09<00:00, 1559.91it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3313.67it/s]

1
1
1

 60%|██████    | 765/1274 [4:49:24<3:08:33, 22.23s/it]

Dronabinol

100%|██████████| 14792/14792 [00:09<00:00, 1608.79it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3310.81it/s]

1
1
1
1
1
1
1
1
1

 60%|██████    | 766/1274 [4:49:46<3:08:12, 22.23s/it]

1
1
1
1
Dronabinol

100%|██████████| 14792/14792 [00:09<00:00, 1606.09it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3406.92it/s]

1
1
1
1
1
1
1
1
1

 60%|██████    | 767/1274 [4:50:08<3:07:25, 22.18s/it]

1
1
1
1
Dronabinol

100%|██████████| 14792/14792 [00:09<00:00, 1542.46it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3383.10it/s]

1
1
1
1
1
1
1
1
1

 60%|██████    | 768/1274 [4:50:31<3:08:03, 22.30s/it]

1
1
1
Montelukast

100%|██████████| 14792/14792 [00:09<00:00, 1527.93it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3225.45it/s]

1
1

 60%|██████    | 769/1274 [4:50:55<3:13:27, 22.98s/it]

Dronabinol

100%|██████████| 14792/14792 [00:09<00:00, 1523.70it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3252.04it/s]

1
1
1

 60%|██████    | 770/1274 [4:51:18<3:12:55, 22.97s/it]

Tenoxicam

100%|██████████| 14792/14792 [00:09<00:00, 1641.52it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3334.74it/s]
 61%|██████    | 771/1274 [4:51:40<3:10:24, 22.71s/it]

1
1
Quinine

100%|██████████| 14792/14792 [00:09<00:00, 1618.65it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3247.84it/s]
 61%|██████    | 772/1274 [4:52:03<3:09:45, 22.68s/it]

1
1
Ketorolac

100%|██████████| 14792/14792 [00:08<00:00, 1693.76it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3334.25it/s]

1
1
1
1

 61%|██████    | 773/1274 [4:52:25<3:07:12, 22.42s/it]

1
1
Ketorolac

100%|██████████| 14792/14792 [00:08<00:00, 1683.31it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3427.96it/s]

1
1

 61%|██████    | 774/1274 [4:52:46<3:04:48, 22.18s/it]

Nabumetone

100%|██████████| 14792/14792 [00:08<00:00, 1713.45it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3339.11it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

 61%|██████    | 775/1274 [4:53:08<3:03:44, 22.09s/it]

Nabumetone

100%|██████████| 14792/14792 [00:08<00:00, 1760.28it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3383.35it/s]

1
1
1
1

 61%|██████    | 776/1274 [4:53:30<3:01:53, 21.91s/it]

Dronabinol

100%|██████████| 14792/14792 [00:09<00:00, 1539.12it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3439.12it/s]

1
1
1
1
1

 61%|██████    | 777/1274 [4:53:52<3:02:33, 22.04s/it]

1
Montelukast

100%|██████████| 14792/14792 [00:09<00:00, 1546.16it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3097.92it/s]

1
1
1

 61%|██████    | 778/1274 [4:54:17<3:09:40, 22.94s/it]

Chlorpromazine

100%|██████████| 14792/14792 [00:09<00:00, 1567.64it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3472.21it/s]
 61%|██████    | 779/1274 [4:54:39<3:06:40, 22.63s/it]

Fluoxetine

100%|██████████| 14792/14792 [00:08<00:00, 1771.15it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3217.36it/s]
 61%|██████    | 780/1274 [4:55:01<3:04:11, 22.37s/it]

Chlorpromazine

100%|██████████| 14792/14792 [00:09<00:00, 1550.94it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3193.25it/s]

1

 61%|██████▏   | 781/1274 [4:55:24<3:05:27, 22.57s/it]

1
Chlorpromazine

100%|██████████| 14792/14792 [00:09<00:00, 1618.73it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3374.07it/s]

1
1
1
1

 61%|██████▏   | 782/1274 [4:55:46<3:03:34, 22.39s/it]

1
1
Duloxetine

100%|██████████| 14792/14792 [00:08<00:00, 1668.86it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3300.92it/s]

1
1
1
1
1

 61%|██████▏   | 783/1274 [4:56:08<3:02:37, 22.32s/it]

1
Duloxetine

100%|██████████| 14792/14792 [00:08<00:00, 1706.82it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3180.81it/s]

1
1
1
1
1

 62%|██████▏   | 784/1274 [4:56:30<3:02:19, 22.33s/it]

1
Duloxetine

100%|██████████| 14792/14792 [00:08<00:00, 1719.23it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3504.59it/s]

1
1
1
1
1

 62%|██████▏   | 785/1274 [4:56:52<2:59:18, 22.00s/it]

1
Fluoxetine

100%|██████████| 14792/14792 [00:08<00:00, 1790.36it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3446.78it/s]
 62%|██████▏   | 786/1274 [4:57:12<2:56:14, 21.67s/it]

1
Fluoxetine

100%|██████████| 14792/14792 [00:08<00:00, 1741.57it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3380.55it/s]

1
1
1
1
1
1
1
1
1

 62%|██████▏   | 787/1274 [4:57:34<2:54:54, 21.55s/it]

Montelukast

100%|██████████| 14792/14792 [00:09<00:00, 1613.27it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3105.67it/s]

1
1
1

 62%|██████▏   | 788/1274 [4:57:58<3:01:21, 22.39s/it]

Montelukast

100%|██████████| 14792/14792 [00:10<00:00, 1474.26it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3161.42it/s]

1
1
1

 62%|██████▏   | 789/1274 [4:58:23<3:07:26, 23.19s/it]

Montelukast

100%|██████████| 14792/14792 [00:09<00:00, 1552.13it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3117.19it/s]

1
1
1
1
1
1

 62%|██████▏   | 790/1274 [4:58:48<3:11:19, 23.72s/it]

Montelukast

100%|██████████| 14792/14792 [00:09<00:00, 1489.50it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3107.32it/s]

1
1
1
1
1
1

 62%|██████▏   | 791/1274 [4:59:13<3:14:54, 24.21s/it]

Montelukast

100%|██████████| 14792/14792 [00:10<00:00, 1468.51it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2963.33it/s]

1
1
1

 62%|██████▏   | 792/1274 [4:59:39<3:18:47, 24.75s/it]

Montelukast

100%|██████████| 14792/14792 [00:09<00:00, 1493.18it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3220.98it/s]

1
1
1

 62%|██████▏   | 793/1274 [5:00:04<3:18:05, 24.71s/it]

Montelukast

100%|██████████| 14792/14792 [00:09<00:00, 1539.07it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3144.17it/s]

1
1
1

 62%|██████▏   | 794/1274 [5:00:29<3:18:09, 24.77s/it]

Montelukast

100%|██████████| 14792/14792 [00:09<00:00, 1538.25it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2970.85it/s]

1
1
1
1
1
1

 62%|██████▏   | 795/1274 [5:00:55<3:19:33, 25.00s/it]

Montelukast

100%|██████████| 14792/14792 [00:09<00:00, 1533.33it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3177.49it/s]

1
1
1
1
1
1

 62%|██████▏   | 796/1274 [5:01:19<3:18:12, 24.88s/it]

Olanzapine

100%|██████████| 14792/14792 [00:09<00:00, 1530.37it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3200.23it/s]

1
1
1
1

 63%|██████▎   | 797/1274 [5:01:42<3:13:38, 24.36s/it]

1
1
Methadone

100%|██████████| 14792/14792 [00:08<00:00, 1750.77it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3356.98it/s]
 63%|██████▎   | 798/1274 [5:02:04<3:06:33, 23.51s/it]

1
Ipratropium

100%|██████████| 14792/14792 [00:08<00:00, 1701.55it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3363.33it/s]
 63%|██████▎   | 799/1274 [5:02:25<3:01:10, 22.89s/it]

Caffeine

100%|██████████| 14792/14792 [00:08<00:00, 1771.74it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3137.50it/s]
 63%|██████▎   | 800/1274 [5:02:47<2:58:18, 22.57s/it]

1
1
1
1
1
Ticlopidine

100%|██████████| 14792/14792 [00:08<00:00, 1725.97it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3420.09it/s]
 63%|██████▎   | 801/1274 [5:03:08<2:54:26, 22.13s/it]

1
Ticlopidine

100%|██████████| 14792/14792 [00:08<00:00, 1697.57it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3353.70it/s]
 63%|██████▎   | 802/1274 [5:03:30<2:52:19, 21.91s/it]

Sildenafil

100%|██████████| 14792/14792 [00:09<00:00, 1634.80it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3417.12it/s]

1
1
1
1

 63%|██████▎   | 803/1274 [5:03:51<2:51:23, 21.83s/it]

Sildenafil

100%|██████████| 14792/14792 [00:09<00:00, 1523.46it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3201.82it/s]
 63%|██████▎   | 804/1274 [5:04:14<2:54:22, 22.26s/it]

Caffeine

100%|██████████| 14792/14792 [00:08<00:00, 1745.43it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3387.26it/s]
 63%|██████▎   | 805/1274 [5:04:35<2:50:53, 21.86s/it]

1
1
1
1
1
Caffeine

100%|██████████| 14792/14792 [00:08<00:00, 1839.43it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3438.23it/s]
 63%|██████▎   | 806/1274 [5:04:56<2:46:41, 21.37s/it]

1
1
1
1
1
1
1
Caffeine

100%|██████████| 14792/14792 [00:08<00:00, 1818.13it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3346.42it/s]
 63%|██████▎   | 807/1274 [5:05:16<2:45:08, 21.22s/it]

1
1
1
1
1
1
1
1
1
1
Erythromycin

100%|██████████| 14792/14792 [00:09<00:00, 1496.89it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2889.46it/s]

1
1
1
1
1
1
1
1

 63%|██████▎   | 808/1274 [5:05:42<2:54:59, 22.53s/it]

Ticlopidine

100%|██████████| 14792/14792 [00:08<00:00, 1688.53it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3413.46it/s]
 64%|██████▎   | 809/1274 [5:06:03<2:51:37, 22.14s/it]

1
1
Oseltamivir

100%|██████████| 14792/14792 [00:07<00:00, 1849.97it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3458.40it/s]

1
1
1
1

 64%|██████▎   | 810/1274 [5:06:24<2:47:50, 21.70s/it]

Fluconazole

100%|██████████| 14792/14792 [00:08<00:00, 1729.61it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3393.75it/s]
 64%|██████▎   | 811/1274 [5:06:45<2:46:16, 21.55s/it]

1
1
Tramadol

100%|██████████| 14792/14792 [00:08<00:00, 1776.18it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3394.80it/s]

1
1
1
1
1
1
1
1

 64%|██████▎   | 812/1274 [5:07:06<2:45:16, 21.46s/it]

Tramadol

100%|██████████| 14792/14792 [00:08<00:00, 1721.03it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3384.08it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

 64%|██████▍   | 813/1274 [5:07:28<2:44:58, 21.47s/it]

Phentermine

100%|██████████| 14792/14792 [00:07<00:00, 1872.91it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3576.77it/s]
 64%|██████▍   | 814/1274 [5:07:48<2:40:29, 20.93s/it]

1
1
Phentermine

100%|██████████| 14792/14792 [00:07<00:00, 1875.67it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3469.51it/s]
 64%|██████▍   | 815/1274 [5:08:08<2:38:27, 20.71s/it]

1
1
1
1
1
1
Carbidopa

100%|██████████| 14792/14792 [00:08<00:00, 1802.66it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3370.56it/s]
 64%|██████▍   | 816/1274 [5:08:29<2:38:57, 20.82s/it]

Ticlopidine

100%|██████████| 14792/14792 [00:08<00:00, 1708.84it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3288.75it/s]
 64%|██████▍   | 817/1274 [5:08:51<2:40:30, 21.07s/it]

1
Ticlopidine

100%|██████████| 14792/14792 [00:08<00:00, 1736.73it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3276.66it/s]
 64%|██████▍   | 818/1274 [5:09:12<2:41:14, 21.22s/it]

1
Carbidopa

100%|██████████| 14792/14792 [00:08<00:00, 1764.83it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3372.55it/s]
 64%|██████▍   | 819/1274 [5:09:33<2:41:15, 21.27s/it]

Citalopram

100%|██████████| 14792/14792 [00:08<00:00, 1685.57it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3312.55it/s]

1
1

 64%|██████▍   | 820/1274 [5:09:55<2:41:58, 21.41s/it]

Lovastatin

100%|██████████| 14792/14792 [00:09<00:00, 1579.14it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3350.48it/s]

1

 64%|██████▍   | 821/1274 [5:10:18<2:44:16, 21.76s/it]

Indinavir

100%|██████████| 14792/14792 [00:09<00:00, 1512.74it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3057.02it/s]
 65%|██████▍   | 822/1274 [5:10:43<2:50:48, 22.67s/it]

Glimepiride

100%|██████████| 14792/14792 [00:09<00:00, 1599.90it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3315.37it/s]

1
1
1

 65%|██████▍   | 823/1274 [5:11:05<2:50:28, 22.68s/it]

Nelfinavir

100%|██████████| 14792/14792 [00:09<00:00, 1556.97it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3195.27it/s]

1
1
1
1
1
1

 65%|██████▍   | 824/1274 [5:11:29<2:53:25, 23.12s/it]

1
Nelfinavir

100%|██████████| 14792/14792 [00:09<00:00, 1577.25it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3127.46it/s]

1
1
1

 65%|██████▍   | 825/1274 [5:11:53<2:54:52, 23.37s/it]

Eletriptan

100%|██████████| 14792/14792 [00:09<00:00, 1615.38it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3245.19it/s]
 65%|██████▍   | 826/1274 [5:12:16<2:53:06, 23.18s/it]

1
Eletriptan

100%|██████████| 14792/14792 [00:08<00:00, 1650.97it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3290.21it/s]

1
1
1
1

 65%|██████▍   | 827/1274 [5:12:38<2:50:47, 22.93s/it]

Citalopram

100%|██████████| 14792/14792 [00:08<00:00, 1653.51it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3308.02it/s]
 65%|██████▍   | 828/1274 [5:13:00<2:47:38, 22.55s/it]

Ticlopidine

100%|██████████| 14792/14792 [00:08<00:00, 1751.86it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3388.15it/s]
 65%|██████▌   | 829/1274 [5:13:21<2:44:22, 22.16s/it]

1
Citalopram

100%|██████████| 14792/14792 [00:09<00:00, 1636.75it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3162.21it/s]

1
1
1
1
1
1
1
1

 65%|██████▌   | 830/1274 [5:13:44<2:44:47, 22.27s/it]

Torasemide

100%|██████████| 14792/14792 [00:08<00:00, 1765.90it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3283.34it/s]

1
1
1
1

 65%|██████▌   | 831/1274 [5:14:06<2:43:17, 22.12s/it]

1
1
Torasemide

100%|██████████| 14792/14792 [00:08<00:00, 1727.22it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3379.82it/s]
 65%|██████▌   | 832/1274 [5:14:27<2:41:33, 21.93s/it]

Torasemide

100%|██████████| 14792/14792 [00:08<00:00, 1758.78it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3371.69it/s]

1
1
1

 65%|██████▌   | 833/1274 [5:14:49<2:39:55, 21.76s/it]

Torasemide

100%|██████████| 14792/14792 [00:09<00:00, 1642.66it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3245.46it/s]

1

 65%|██████▌   | 834/1274 [5:15:11<2:40:10, 21.84s/it]

1
1
Midodrine

100%|██████████| 14792/14792 [00:08<00:00, 1742.80it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3262.78it/s]

1
1
1

 66%|██████▌   | 835/1274 [5:15:32<2:39:16, 21.77s/it]

Ticlopidine

100%|██████████| 14792/14792 [00:08<00:00, 1719.53it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3409.45it/s]
 66%|██████▌   | 836/1274 [5:15:53<2:37:10, 21.53s/it]

1
1
1
1
1
1
Carbidopa

100%|██████████| 14792/14792 [00:08<00:00, 1796.82it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3269.73it/s]
 66%|██████▌   | 837/1274 [5:16:15<2:36:58, 21.55s/it]

Carbidopa

100%|██████████| 14792/14792 [00:08<00:00, 1743.66it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3265.70it/s]
 66%|██████▌   | 838/1274 [5:16:37<2:37:08, 21.63s/it]

Ipratropium

100%|██████████| 14792/14792 [00:08<00:00, 1700.45it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3399.70it/s]

1
1

 66%|██████▌   | 839/1274 [5:16:58<2:36:10, 21.54s/it]

1
1
Folic acid

100%|██████████| 14792/14792 [00:09<00:00, 1607.01it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3138.53it/s]
 66%|██████▌   | 840/1274 [5:17:21<2:40:09, 22.14s/it]

1
1
Pravastatin

100%|██████████| 14792/14792 [00:08<00:00, 1683.23it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3350.87it/s]
 66%|██████▌   | 841/1274 [5:17:44<2:40:39, 22.26s/it]

1
Calcifediol

100%|██████████| 14792/14792 [00:09<00:00, 1571.53it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3412.75it/s]

1
1
1
1
1
1
1
1
1
1
1
1

 66%|██████▌   | 842/1274 [5:18:07<2:41:31, 22.43s/it]

Cholecalciferol

100%|██████████| 14792/14792 [00:08<00:00, 1671.13it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3301.33it/s]

1
1

 66%|██████▌   | 843/1274 [5:18:29<2:40:54, 22.40s/it]

Cholecalciferol

100%|██████████| 14792/14792 [00:08<00:00, 1657.90it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3428.73it/s]
 66%|██████▌   | 844/1274 [5:18:51<2:40:16, 22.36s/it]

Vitamin E

100%|██████████| 14792/14792 [00:09<00:00, 1611.34it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3361.83it/s]

1
1
1
1
1
1

 66%|██████▋   | 845/1274 [5:19:14<2:40:44, 22.48s/it]

Vitamin A

100%|██████████| 14792/14792 [00:08<00:00, 1763.36it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3369.80it/s]

1
1
1
1
1
1
1
1
1
1
1

 66%|██████▋   | 846/1274 [5:19:35<2:37:46, 22.12s/it]

1
1
Folic acid

100%|██████████| 14792/14792 [00:09<00:00, 1633.87it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3106.28it/s]

1

 66%|██████▋   | 847/1274 [5:19:59<2:40:25, 22.54s/it]

1
Ergocalciferol

100%|██████████| 14792/14792 [00:08<00:00, 1677.93it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3354.71it/s]

1
1

 67%|██████▋   | 848/1274 [5:20:21<2:39:45, 22.50s/it]

Pravastatin

100%|██████████| 14792/14792 [00:08<00:00, 1665.22it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3444.39it/s]
 67%|██████▋   | 849/1274 [5:20:44<2:39:02, 22.45s/it]

1
Ergocalciferol

100%|██████████| 14792/14792 [00:08<00:00, 1680.18it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3429.37it/s]
 67%|██████▋   | 850/1274 [5:21:06<2:37:39, 22.31s/it]

Ergocalciferol

100%|██████████| 14792/14792 [00:08<00:00, 1675.24it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3648.21it/s]
 67%|██████▋   | 851/1274 [5:21:27<2:34:27, 21.91s/it]

Ergocalciferol

100%|██████████| 14792/14792 [00:09<00:00, 1623.06it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3403.36it/s]

1
1

 67%|██████▋   | 852/1274 [5:21:49<2:34:56, 22.03s/it]

Glycine

100%|██████████| 14792/14792 [00:07<00:00, 1924.47it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3380.40it/s]
 67%|██████▋   | 853/1274 [5:22:09<2:30:49, 21.50s/it]

L-Glutamine

100%|██████████| 14792/14792 [00:07<00:00, 1851.83it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3262.39it/s]

1
1
1
1
1
1
1
1
1
1

 67%|██████▋   | 854/1274 [5:22:30<2:29:32, 21.36s/it]

1
1
1
1
1
1
Biotin

100%|██████████| 14792/14792 [00:08<00:00, 1786.17it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3164.33it/s]
 67%|██████▋   | 855/1274 [5:22:52<2:30:11, 21.51s/it]

Cyanocobalamin

100%|██████████| 14792/14792 [00:13<00:00, 1115.44it/s]
100%|██████████| 34899/34899 [00:16<00:00, 2066.33it/s]
 67%|██████▋   | 856/1274 [5:23:42<3:28:58, 30.00s/it]

Pravastatin

100%|██████████| 14792/14792 [00:08<00:00, 1722.97it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3183.97it/s]

1
1

 67%|██████▋   | 857/1274 [5:24:05<3:13:37, 27.86s/it]

Pravastatin

100%|██████████| 14792/14792 [00:08<00:00, 1692.31it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3274.79it/s]

1
1

 67%|██████▋   | 858/1274 [5:24:28<3:02:58, 26.39s/it]

Carbidopa

100%|██████████| 14792/14792 [00:08<00:00, 1795.02it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3517.60it/s]
 67%|██████▋   | 859/1274 [5:24:48<2:50:31, 24.65s/it]

Amphetamine

100%|██████████| 14792/14792 [00:08<00:00, 1816.60it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3578.17it/s]
 68%|██████▊   | 860/1274 [5:25:08<2:40:23, 23.25s/it]

1
1
1
1
1
1
1
Carbidopa

100%|██████████| 14792/14792 [00:07<00:00, 1861.28it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3311.15it/s]
 68%|██████▊   | 861/1274 [5:25:29<2:35:22, 22.57s/it]

Lorazepam

100%|██████████| 14792/14792 [00:08<00:00, 1655.34it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3327.69it/s]

1
1

 68%|██████▊   | 862/1274 [5:25:52<2:34:15, 22.46s/it]

Cevimeline

100%|██████████| 14792/14792 [00:08<00:00, 1656.37it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3591.07it/s]
 68%|██████▊   | 863/1274 [5:26:12<2:30:26, 21.96s/it]

Cevimeline

100%|██████████| 14792/14792 [00:08<00:00, 1657.00it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3406.49it/s]
 68%|██████▊   | 864/1274 [5:26:34<2:29:07, 21.82s/it]

Cevimeline

100%|██████████| 14792/14792 [00:08<00:00, 1700.67it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3359.15it/s]
 68%|██████▊   | 865/1274 [5:26:55<2:27:51, 21.69s/it]

Cevimeline

100%|██████████| 14792/14792 [00:08<00:00, 1654.96it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3437.80it/s]
 68%|██████▊   | 866/1274 [5:27:16<2:26:38, 21.57s/it]

Amphetamine

100%|██████████| 14792/14792 [00:08<00:00, 1743.52it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3387.67it/s]
 68%|██████▊   | 867/1274 [5:27:37<2:25:00, 21.38s/it]

1
Amphetamine

100%|██████████| 14792/14792 [00:07<00:00, 1870.99it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3290.58it/s]
 68%|██████▊   | 868/1274 [5:27:58<2:23:17, 21.18s/it]

1
1
1
1
1
1
Pravastatin

100%|██████████| 14792/14792 [00:08<00:00, 1669.81it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3507.89it/s]
 68%|██████▊   | 869/1274 [5:28:20<2:24:01, 21.34s/it]

Baclofen

100%|██████████| 14792/14792 [00:08<00:00, 1844.58it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3602.23it/s]
 68%|██████▊   | 870/1274 [5:28:40<2:20:50, 20.92s/it]

Ramipril

100%|██████████| 14792/14792 [00:09<00:00, 1640.66it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3234.54it/s]

1
1
1
1

 68%|██████▊   | 871/1274 [5:29:03<2:24:11, 21.47s/it]

Valsartan

100%|██████████| 14792/14792 [00:08<00:00, 1654.27it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3292.56it/s]

1
1
1
1
1
1
1
1
1

 68%|██████▊   | 872/1274 [5:29:25<2:26:04, 21.80s/it]

1
1
1
Fluvoxamine

100%|██████████| 14792/14792 [00:08<00:00, 1726.10it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3554.98it/s]
 69%|██████▊   | 873/1274 [5:29:46<2:24:08, 21.57s/it]

Fluvoxamine

100%|██████████| 14792/14792 [00:08<00:00, 1757.93it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3319.88it/s]

1
1
1
1

 69%|██████▊   | 874/1274 [5:30:07<2:23:19, 21.50s/it]

Pravastatin

100%|██████████| 14792/14792 [00:08<00:00, 1695.84it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3460.97it/s]
 69%|██████▊   | 875/1274 [5:30:29<2:23:55, 21.64s/it]

Pravastatin

100%|██████████| 14792/14792 [00:09<00:00, 1642.76it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3295.15it/s]

1
1
1
1
1
1
1
1
1
1
1
1

 69%|██████▉   | 876/1274 [5:30:52<2:25:48, 21.98s/it]

Lovastatin

100%|██████████| 14792/14792 [00:09<00:00, 1642.64it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3216.47it/s]

1

 69%|██████▉   | 877/1274 [5:31:15<2:27:19, 22.27s/it]

1
Lovastatin

100%|██████████| 14792/14792 [00:09<00:00, 1643.17it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3340.70it/s]
 69%|██████▉   | 878/1274 [5:31:38<2:27:11, 22.30s/it]

Pregabalin

100%|██████████| 14792/14792 [00:08<00:00, 1793.29it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3257.32it/s]
 69%|██████▉   | 879/1274 [5:31:59<2:24:39, 21.97s/it]

Desogestrel

100%|██████████| 14792/14792 [00:10<00:00, 1411.74it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3340.02it/s]

1
1
1
1
1
1
1
1
1

 69%|██████▉   | 880/1274 [5:32:22<2:27:24, 22.45s/it]

1
1
1
Desogestrel

100%|██████████| 14792/14792 [00:10<00:00, 1454.58it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3406.28it/s]
 69%|██████▉   | 881/1274 [5:32:45<2:28:21, 22.65s/it]

1
Desogestrel

100%|██████████| 14792/14792 [00:10<00:00, 1451.53it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3219.23it/s]

1
1
1
1
1
1
1
1
1
1

 69%|██████▉   | 882/1274 [5:33:09<2:30:01, 22.96s/it]

1
1
1
1
Desogestrel

100%|██████████| 14792/14792 [00:10<00:00, 1437.85it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3062.20it/s]

1
1
1
1
1
1
1
1
1
1

 69%|██████▉   | 883/1274 [5:33:33<2:32:17, 23.37s/it]

1
1
1
1
Desogestrel

100%|██████████| 14792/14792 [00:10<00:00, 1404.64it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3472.97it/s]

1
1
1
1
1
1
1
1
1

 69%|██████▉   | 884/1274 [5:33:57<2:31:22, 23.29s/it]

1
1
1
Desogestrel

100%|██████████| 14792/14792 [00:10<00:00, 1438.85it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3239.60it/s]

1
1

 69%|██████▉   | 885/1274 [5:34:20<2:32:03, 23.45s/it]

1
1
Desogestrel

100%|██████████| 14792/14792 [00:10<00:00, 1442.10it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3199.57it/s]

1
1
1
1
1
1
1
1
1

 70%|██████▉   | 886/1274 [5:34:44<2:32:12, 23.54s/it]

1
1
1
Desogestrel

100%|██████████| 14792/14792 [00:09<00:00, 1483.50it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3374.14it/s]

1
1
1
1
1
1
1
1
1

 70%|██████▉   | 887/1274 [5:35:07<2:30:19, 23.31s/it]

1
1
1
Atomoxetine

100%|██████████| 14792/14792 [00:08<00:00, 1780.32it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3472.90it/s]

1
1
1
1

 70%|██████▉   | 888/1274 [5:35:28<2:24:59, 22.54s/it]

1
1
Desogestrel

100%|██████████| 14792/14792 [00:10<00:00, 1467.12it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3440.83it/s]

1
1
1
1
1
1
1
1
1
1

 70%|██████▉   | 889/1274 [5:35:51<2:25:25, 22.66s/it]

1
1
1
1
Atomoxetine

100%|██████████| 14792/14792 [00:08<00:00, 1786.86it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3307.80it/s]

1
1
1
1
1
1
1
1
1

 70%|██████▉   | 890/1274 [5:36:12<2:22:33, 22.27s/it]

Desvenlafaxine

100%|██████████| 14792/14792 [00:08<00:00, 1691.62it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3365.21it/s]
 70%|██████▉   | 891/1274 [5:36:34<2:21:06, 22.11s/it]

Desvenlafaxine

100%|██████████| 14792/14792 [00:08<00:00, 1757.67it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3277.48it/s]

1
1
1
1
1
1

 70%|███████   | 892/1274 [5:36:55<2:19:48, 21.96s/it]

1
1
Venlafaxine

100%|██████████| 14792/14792 [00:08<00:00, 1695.38it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3310.37it/s]

1
1
1
1
1
1
1
1

 70%|███████   | 893/1274 [5:37:17<2:18:54, 21.88s/it]

Venlafaxine

100%|██████████| 14792/14792 [00:08<00:00, 1755.97it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3261.54it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

 70%|███████   | 894/1274 [5:37:39<2:17:58, 21.79s/it]

Disopyramide

100%|██████████| 14792/14792 [00:08<00:00, 1740.45it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3329.09it/s]
 70%|███████   | 895/1274 [5:38:00<2:17:38, 21.79s/it]

Liothyronine

100%|██████████| 14792/14792 [00:08<00:00, 1725.32it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3242.50it/s]

1
1
1

 70%|███████   | 896/1274 [5:38:23<2:17:59, 21.90s/it]

1
Desogestrel

100%|██████████| 14792/14792 [00:09<00:00, 1490.35it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3188.91it/s]

1
1
1
1
1
1
1
1
1
1

 70%|███████   | 897/1274 [5:38:46<2:20:19, 22.33s/it]

1
1
1
1
Zolmitriptan

100%|██████████| 14792/14792 [00:08<00:00, 1678.90it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3333.10it/s]

1
1

 70%|███████   | 898/1274 [5:39:08<2:18:55, 22.17s/it]

Temazepam

100%|██████████| 14792/14792 [00:08<00:00, 1648.39it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3323.84it/s]

1
1
1
1
1

 71%|███████   | 899/1274 [5:39:30<2:18:13, 22.11s/it]

Hydromorphone

100%|██████████| 14792/14792 [00:11<00:00, 1247.02it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3374.07it/s]

1
1
1

 71%|███████   | 900/1274 [5:39:54<2:22:45, 22.90s/it]

1
Ipratropium

100%|██████████| 14792/14792 [00:08<00:00, 1726.93it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3471.40it/s]
 71%|███████   | 901/1274 [5:40:15<2:18:56, 22.35s/it]

Ipratropium

100%|██████████| 14792/14792 [00:08<00:00, 1662.23it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3379.95it/s]
 71%|███████   | 902/1274 [5:40:37<2:18:01, 22.26s/it]

Ethambutol

100%|██████████| 14792/14792 [00:07<00:00, 1906.27it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3477.81it/s]
 71%|███████   | 903/1274 [5:40:58<2:13:36, 21.61s/it]

1
Indomethacin

100%|██████████| 14792/14792 [00:08<00:00, 1655.43it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3315.70it/s]
 71%|███████   | 904/1274 [5:41:20<2:14:28, 21.81s/it]

Indomethacin

100%|██████████| 14792/14792 [00:08<00:00, 1746.38it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3362.70it/s]

1
1

 71%|███████   | 905/1274 [5:41:42<2:14:13, 21.82s/it]

Indomethacin

100%|██████████| 14792/14792 [00:09<00:00, 1603.65it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3432.52it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

 71%|███████   | 906/1274 [5:42:04<2:14:35, 21.95s/it]

Hydromorphone

100%|██████████| 14792/14792 [00:12<00:00, 1230.44it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3339.52it/s]

1
1
1
1

 71%|███████   | 907/1274 [5:42:29<2:19:51, 22.87s/it]

Nortriptyline

100%|██████████| 14792/14792 [00:09<00:00, 1584.13it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3400.89it/s]

1
1
1
1
1
1
1
1
1

 71%|███████▏  | 908/1274 [5:42:51<2:17:37, 22.56s/it]

Zolmitriptan

100%|██████████| 14792/14792 [00:08<00:00, 1726.28it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3195.12it/s]

1
1
1
1
1
1
1
1

 71%|███████▏  | 909/1274 [5:43:13<2:16:15, 22.40s/it]

Nortriptyline

100%|██████████| 14792/14792 [00:09<00:00, 1603.17it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3214.10it/s]
 71%|███████▏  | 910/1274 [5:43:35<2:15:58, 22.41s/it]

1
1
1
1
1
1
Amitriptyline

100%|██████████| 14792/14792 [00:09<00:00, 1561.11it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3485.41it/s]

1
1
1
1
1
1

 72%|███████▏  | 911/1274 [5:43:57<2:14:14, 22.19s/it]

Amitriptyline

100%|██████████| 14792/14792 [00:08<00:00, 1662.05it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3187.21it/s]

1
1
1
1
1
1

 72%|███████▏  | 912/1274 [5:44:19<2:14:03, 22.22s/it]

Amitriptyline

100%|██████████| 14792/14792 [00:09<00:00, 1629.56it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3265.29it/s]
 72%|███████▏  | 913/1274 [5:44:42<2:13:59, 22.27s/it]

1
1
1
1
1
1
1
1
Acetaminophen

100%|██████████| 14792/14792 [00:08<00:00, 1804.79it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3277.61it/s]
 72%|███████▏  | 914/1274 [5:45:03<2:11:31, 21.92s/it]

1
Acetaminophen

100%|██████████| 14792/14792 [00:08<00:00, 1785.22it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3206.07it/s]

1
1
1
1

 72%|███████▏  | 915/1274 [5:45:24<2:10:45, 21.86s/it]

Acetaminophen

100%|██████████| 14792/14792 [00:07<00:00, 1871.79it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3020.89it/s]

1
1
1
1

 72%|███████▏  | 916/1274 [5:45:46<2:10:20, 21.85s/it]

Liothyronine

100%|██████████| 14792/14792 [00:08<00:00, 1708.33it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3175.58it/s]
 72%|███████▏  | 917/1274 [5:46:09<2:10:51, 21.99s/it]

Liothyronine

100%|██████████| 14792/14792 [00:08<00:00, 1740.32it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3497.57it/s]
 72%|███████▏  | 918/1274 [5:46:30<2:08:50, 21.71s/it]

Liothyronine

100%|██████████| 14792/14792 [00:08<00:00, 1775.42it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3223.68it/s]

1

 72%|███████▏  | 919/1274 [5:46:52<2:08:55, 21.79s/it]

1
Ranolazine

100%|██████████| 14792/14792 [00:08<00:00, 1661.13it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3139.85it/s]
 72%|███████▏  | 920/1274 [5:47:14<2:10:31, 22.12s/it]

Benzatropine

100%|██████████| 14792/14792 [00:09<00:00, 1643.19it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3199.29it/s]
 72%|███████▏  | 921/1274 [5:47:37<2:10:28, 22.18s/it]

1
Benzatropine

100%|██████████| 14792/14792 [00:09<00:00, 1608.99it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3399.31it/s]
 72%|███████▏  | 922/1274 [5:47:58<2:09:01, 21.99s/it]

Ranolazine

100%|██████████| 14792/14792 [00:09<00:00, 1636.91it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3188.10it/s]

1

 72%|███████▏  | 923/1274 [5:48:21<2:09:54, 22.21s/it]

1
Ranolazine

100%|██████████| 14792/14792 [00:09<00:00, 1630.19it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3147.69it/s]

1
1

 73%|███████▎  | 924/1274 [5:48:44<2:11:01, 22.46s/it]

Ranolazine

100%|██████████| 14792/14792 [00:09<00:00, 1591.12it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3154.12it/s]

1

 73%|███████▎  | 925/1274 [5:49:07<2:11:23, 22.59s/it]

Ranolazine

100%|██████████| 14792/14792 [00:09<00:00, 1620.79it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3064.05it/s]
 73%|███████▎  | 926/1274 [5:49:30<2:12:28, 22.84s/it]

Ranolazine

100%|██████████| 14792/14792 [00:08<00:00, 1657.88it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3296.88it/s]
 73%|███████▎  | 927/1274 [5:49:53<2:10:47, 22.62s/it]

Ranolazine

100%|██████████| 14792/14792 [00:09<00:00, 1625.01it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3197.21it/s]
 73%|███████▎  | 928/1274 [5:50:15<2:10:03, 22.55s/it]

Topiramate

100%|██████████| 14792/14792 [00:09<00:00, 1585.85it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3305.24it/s]
 73%|███████▎  | 929/1274 [5:50:37<2:09:05, 22.45s/it]

Ranolazine

100%|██████████| 14792/14792 [00:08<00:00, 1709.86it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3338.26it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

 73%|███████▎  | 930/1274 [5:50:59<2:07:26, 22.23s/it]

Ranolazine

100%|██████████| 14792/14792 [00:09<00:00, 1596.34it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3213.07it/s]

1
1
1
1

 73%|███████▎  | 931/1274 [5:51:22<2:08:06, 22.41s/it]

1
1
Ranolazine

100%|██████████| 14792/14792 [00:09<00:00, 1642.07it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3193.74it/s]

1
1
1
1

 73%|███████▎  | 932/1274 [5:51:44<2:08:17, 22.51s/it]

1
1
Cladribine

100%|██████████| 14792/14792 [00:08<00:00, 1767.24it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3329.41it/s]

1

 73%|███████▎  | 933/1274 [5:52:06<2:06:16, 22.22s/it]

Butalbital

100%|██████████| 14792/14792 [00:08<00:00, 1780.59it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3443.10it/s]
 73%|███████▎  | 934/1274 [5:52:27<2:03:30, 21.79s/it]

1
1
1
1
1
1
Butalbital

100%|██████████| 14792/14792 [00:08<00:00, 1731.56it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3349.78it/s]
 73%|███████▎  | 935/1274 [5:52:48<2:01:43, 21.54s/it]

1
Temazepam

100%|██████████| 14792/14792 [00:08<00:00, 1740.48it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3436.24it/s]
 73%|███████▎  | 936/1274 [5:53:09<2:01:02, 21.49s/it]

Benzatropine

100%|██████████| 14792/14792 [00:09<00:00, 1590.72it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3334.09it/s]

1
1
1
1

 74%|███████▎  | 937/1274 [5:53:31<2:01:59, 21.72s/it]

Ziprasidone

100%|██████████| 14792/14792 [00:09<00:00, 1594.36it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3294.90it/s]
 74%|███████▎  | 938/1274 [5:53:54<2:03:11, 22.00s/it]

1
Ziprasidone

100%|██████████| 14792/14792 [00:09<00:00, 1569.99it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3257.98it/s]
 74%|███████▎  | 939/1274 [5:54:17<2:03:59, 22.21s/it]

Ziprasidone

100%|██████████| 14792/14792 [00:09<00:00, 1540.26it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3141.98it/s]
 74%|███████▍  | 940/1274 [5:54:40<2:05:23, 22.53s/it]

Topiramate

100%|██████████| 14792/14792 [00:09<00:00, 1614.97it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3531.87it/s]
 74%|███████▍  | 941/1274 [5:55:01<2:03:21, 22.23s/it]

1
1
1
1
1
Topiramate

100%|██████████| 14792/14792 [00:09<00:00, 1628.94it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3470.04it/s]
 74%|███████▍  | 942/1274 [5:55:23<2:02:07, 22.07s/it]

1
1
1
1
1
Topiramate

100%|██████████| 14792/14792 [00:09<00:00, 1624.08it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3409.27it/s]
 74%|███████▍  | 943/1274 [5:55:45<2:01:10, 21.97s/it]

Ropinirole

100%|██████████| 14792/14792 [00:08<00:00, 1747.42it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3335.13it/s]
 74%|███████▍  | 944/1274 [5:56:06<1:59:41, 21.76s/it]

Metoprolol

100%|██████████| 14792/14792 [00:08<00:00, 1757.54it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3523.74it/s]
 74%|███████▍  | 945/1274 [5:56:27<1:57:15, 21.38s/it]

Metoprolol

100%|██████████| 14792/14792 [00:08<00:00, 1781.14it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3257.96it/s]

1
1
1
1

 74%|███████▍  | 946/1274 [5:56:48<1:57:19, 21.46s/it]

Metoprolol

100%|██████████| 14792/14792 [00:08<00:00, 1738.08it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3330.01it/s]
 74%|███████▍  | 947/1274 [5:57:10<1:57:01, 21.47s/it]

1
1
1
1
1
1
Anagrelide

100%|██████████| 14792/14792 [00:09<00:00, 1577.31it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3341.93it/s]
 74%|███████▍  | 948/1274 [5:57:32<1:57:46, 21.68s/it]

1
1
Phenytoin

100%|██████████| 14792/14792 [00:08<00:00, 1817.37it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3522.72it/s]

1
1
1
1

 74%|███████▍  | 949/1274 [5:57:52<1:55:08, 21.26s/it]

1
Dapsone

100%|██████████| 14792/14792 [00:08<00:00, 1706.95it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3492.60it/s]
 75%|███████▍  | 950/1274 [5:58:13<1:54:34, 21.22s/it]

1
Dapsone

100%|██████████| 14792/14792 [00:08<00:00, 1780.06it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3309.25it/s]
 75%|███████▍  | 951/1274 [5:58:35<1:54:10, 21.21s/it]

1
1
1
Cabergoline

100%|██████████| 14792/14792 [00:10<00:00, 1397.54it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3291.38it/s]
 75%|███████▍  | 952/1274 [5:58:58<1:58:00, 21.99s/it]

Ziprasidone

100%|██████████| 14792/14792 [00:09<00:00, 1562.02it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3255.45it/s]
 75%|███████▍  | 953/1274 [5:59:21<1:59:03, 22.25s/it]

1
Ziprasidone

100%|██████████| 14792/14792 [00:09<00:00, 1564.23it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3233.29it/s]
 75%|███████▍  | 954/1274 [5:59:44<1:59:24, 22.39s/it]

Ziprasidone

100%|██████████| 14792/14792 [00:09<00:00, 1554.70it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3169.37it/s]
 75%|███████▍  | 955/1274 [6:00:07<2:00:21, 22.64s/it]

Dextromethorphan

100%|██████████| 14792/14792 [00:10<00:00, 1442.67it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3390.72it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

 75%|███████▌  | 956/1274 [6:00:30<2:00:43, 22.78s/it]

Dextromethorphan

100%|██████████| 14792/14792 [00:10<00:00, 1394.90it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3342.81it/s]

1
1
1
1

 75%|███████▌  | 957/1274 [6:00:54<2:01:46, 23.05s/it]

Albendazole

100%|██████████| 14792/14792 [00:08<00:00, 1717.86it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3383.65it/s]
 75%|███████▌  | 958/1274 [6:01:15<1:58:29, 22.50s/it]

1
1
Riluzole

100%|██████████| 14792/14792 [00:08<00:00, 1760.98it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3311.82it/s]
 75%|███████▌  | 959/1274 [6:01:37<1:56:16, 22.15s/it]

1
1
1
1
1
1
Modafinil

100%|██████████| 14792/14792 [00:08<00:00, 1763.22it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3449.21it/s]

1
1
1
1
1
1

 75%|███████▌  | 960/1274 [6:01:57<1:53:58, 21.78s/it]

1
1
1
1
1
Zileuton

100%|██████████| 14792/14792 [00:08<00:00, 1759.31it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3370.04it/s]
 75%|███████▌  | 961/1274 [6:02:19<1:52:32, 21.57s/it]

Zileuton

100%|██████████| 14792/14792 [00:08<00:00, 1658.48it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3341.62it/s]
 76%|███████▌  | 962/1274 [6:02:40<1:52:17, 21.59s/it]

1
Zileuton

100%|██████████| 14792/14792 [00:08<00:00, 1752.05it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3351.60it/s]
 76%|███████▌  | 963/1274 [6:03:02<1:51:40, 21.55s/it]

1
1
Zileuton

100%|██████████| 14792/14792 [00:08<00:00, 1775.21it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3319.63it/s]

1
1
1
1

 76%|███████▌  | 964/1274 [6:03:23<1:51:09, 21.52s/it]

1
1
1
Riluzole

100%|██████████| 14792/14792 [00:08<00:00, 1775.40it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3314.23it/s]
 76%|███████▌  | 965/1274 [6:03:44<1:50:15, 21.41s/it]

1
1
1
Riluzole

100%|██████████| 14792/14792 [00:08<00:00, 1724.38it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3133.07it/s]
 76%|███████▌  | 966/1274 [6:04:06<1:50:44, 21.57s/it]

1
1
1
1
1
1
Riluzole

100%|██████████| 14792/14792 [00:08<00:00, 1712.33it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3266.24it/s]
 76%|███████▌  | 967/1274 [6:04:28<1:50:28, 21.59s/it]

1
1
1
1
1
1
Etodolac

100%|██████████| 14792/14792 [00:09<00:00, 1594.57it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3229.37it/s]

1
1
1
1

 76%|███████▌  | 968/1274 [6:04:51<1:51:50, 21.93s/it]

1
1
Meclizine

100%|██████████| 14792/14792 [00:09<00:00, 1610.70it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3167.92it/s]

1

 76%|███████▌  | 969/1274 [6:05:14<1:53:07, 22.25s/it]

1
Meclizine

100%|██████████| 14792/14792 [00:08<00:00, 1678.14it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3372.19it/s]

1
1
1
1

 76%|███████▌  | 970/1274 [6:05:36<1:52:23, 22.18s/it]

1
1
Esomeprazole

100%|██████████| 14792/14792 [00:09<00:00, 1558.31it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3481.40it/s]

1

 76%|███████▌  | 971/1274 [6:05:57<1:51:36, 22.10s/it]

1
1
1
Esomeprazole

100%|██████████| 14792/14792 [00:09<00:00, 1577.59it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3346.99it/s]

1
1
1
1
1
1
1
1
1
1
1
1

 76%|███████▋  | 972/1274 [6:06:20<1:52:02, 22.26s/it]

1
Esomeprazole

100%|██████████| 14792/14792 [00:09<00:00, 1636.98it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3407.05it/s]
 76%|███████▋  | 973/1274 [6:06:42<1:51:14, 22.18s/it]

1
1
Esomeprazole

100%|██████████| 14792/14792 [00:08<00:00, 1682.34it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3397.88it/s]
 76%|███████▋  | 974/1274 [6:07:04<1:50:16, 22.06s/it]

Risperidone

100%|██████████| 14792/14792 [00:09<00:00, 1510.50it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3129.38it/s]

1
1

 77%|███████▋  | 975/1274 [6:07:27<1:52:11, 22.51s/it]

1
1
1
1
Etodolac

100%|██████████| 14792/14792 [00:09<00:00, 1557.12it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3307.28it/s]

1
1
1
1

 77%|███████▋  | 976/1274 [6:07:50<1:51:55, 22.54s/it]

1
1
Etodolac

100%|██████████| 14792/14792 [00:09<00:00, 1627.19it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3516.97it/s]

1
1

 77%|███████▋  | 977/1274 [6:08:12<1:50:10, 22.26s/it]

Nateglinide

100%|██████████| 14792/14792 [00:08<00:00, 1736.35it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3470.48it/s]

1

 77%|███████▋  | 978/1274 [6:08:33<1:48:34, 22.01s/it]

Isotretinoin

100%|██████████| 14792/14792 [00:08<00:00, 1771.10it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3367.44it/s]

1
1

 77%|███████▋  | 979/1274 [6:08:54<1:47:07, 21.79s/it]

Methimazole

100%|██████████| 14792/14792 [00:07<00:00, 1874.28it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3081.41it/s]
 77%|███████▋  | 980/1274 [6:09:15<1:45:49, 21.60s/it]

1
Methimazole

100%|██████████| 14792/14792 [00:08<00:00, 1847.19it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3647.56it/s]
 77%|███████▋  | 981/1274 [6:09:35<1:42:20, 20.96s/it]

1
Methimazole

100%|██████████| 14792/14792 [00:07<00:00, 1852.92it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3631.51it/s]
 77%|███████▋  | 982/1274 [6:09:54<1:39:56, 20.53s/it]

1
Clopidogrel

100%|██████████| 14792/14792 [00:08<00:00, 1654.94it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3365.63it/s]
 77%|███████▋  | 983/1274 [6:10:16<1:41:27, 20.92s/it]

1
Clopidogrel

100%|██████████| 14792/14792 [00:09<00:00, 1614.29it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3249.02it/s]

1
1
1
1
1
1
1
1
1
1

 77%|███████▋  | 984/1274 [6:10:39<1:43:21, 21.38s/it]

1
1
Alitretinoin

100%|██████████| 14792/14792 [00:08<00:00, 1739.22it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3316.34it/s]

1
1

 77%|███████▋  | 985/1274 [6:11:00<1:43:23, 21.47s/it]

Isotretinoin

100%|██████████| 14792/14792 [00:08<00:00, 1785.54it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3200.20it/s]

1
1

 77%|███████▋  | 986/1274 [6:11:22<1:43:26, 21.55s/it]

Tretinoin

100%|██████████| 14792/14792 [00:08<00:00, 1758.90it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3396.68it/s]

1
1

 77%|███████▋  | 987/1274 [6:11:43<1:42:27, 21.42s/it]

Ethotoin

100%|██████████| 14792/14792 [00:08<00:00, 1753.38it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3209.32it/s]

1
1
1
1
1

 78%|███████▊  | 988/1274 [6:12:05<1:42:36, 21.53s/it]

1
Tretinoin

100%|██████████| 14792/14792 [00:08<00:00, 1774.88it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3364.22it/s]
 78%|███████▊  | 989/1274 [6:12:27<1:42:09, 21.51s/it]

Tretinoin

100%|██████████| 14792/14792 [00:08<00:00, 1763.21it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3380.19it/s]

1
1

 78%|███████▊  | 990/1274 [6:12:48<1:41:37, 21.47s/it]

Tretinoin

100%|██████████| 14792/14792 [00:08<00:00, 1755.23it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3307.57it/s]

1
1

 78%|███████▊  | 991/1274 [6:13:09<1:41:12, 21.46s/it]

1
Tretinoin

100%|██████████| 14792/14792 [00:08<00:00, 1835.63it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3471.59it/s]

1
1
1

 78%|███████▊  | 992/1274 [6:13:30<1:39:53, 21.25s/it]

Tretinoin

100%|██████████| 14792/14792 [00:08<00:00, 1779.81it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3548.60it/s]
 78%|███████▊  | 993/1274 [6:13:51<1:38:55, 21.12s/it]

1
Tretinoin

100%|██████████| 14792/14792 [00:07<00:00, 1870.82it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3463.27it/s]
 78%|███████▊  | 994/1274 [6:14:12<1:38:01, 21.01s/it]

1
Tretinoin

100%|██████████| 14792/14792 [00:08<00:00, 1811.83it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3283.64it/s]

1
1
1
1
1
1
1
1
1

 78%|███████▊  | 995/1274 [6:14:33<1:38:21, 21.15s/it]

1
1
1
Nateglinide

100%|██████████| 14792/14792 [00:08<00:00, 1718.58it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3240.38it/s]

1
1

 78%|███████▊  | 996/1274 [6:14:55<1:39:22, 21.45s/it]

Nateglinide

100%|██████████| 14792/14792 [00:08<00:00, 1774.00it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3323.41it/s]

1
1

 78%|███████▊  | 997/1274 [6:15:17<1:39:01, 21.45s/it]

Warfarin

100%|██████████| 14792/14792 [00:09<00:00, 1633.54it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3257.59it/s]

1
1
1
1
1
1
1
1
1
1
1

 78%|███████▊  | 998/1274 [6:15:39<1:40:00, 21.74s/it]

1
1
1
1
1
Mycophenolate mofetil

100%|██████████| 14792/14792 [00:09<00:00, 1547.31it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3057.82it/s]

1
1

 78%|███████▊  | 999/1274 [6:16:03<1:42:10, 22.29s/it]

1
1
Eplerenone

100%|██████████| 14792/14792 [00:12<00:00, 1203.34it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3180.44it/s]

1
1
1
1
1
1
1
1
1
1
1
1

 78%|███████▊  | 1000/1274 [6:16:29<1:47:05, 23.45s/it]

Nitrofurantoin

100%|██████████| 14792/14792 [00:08<00:00, 1747.26it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3394.10it/s]
 79%|███████▊  | 1001/1274 [6:16:50<1:43:03, 22.65s/it]

1
1
Moexipril

100%|██████████| 14792/14792 [00:09<00:00, 1610.92it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3137.42it/s]

1
1
1
1

 79%|███████▊  | 1002/1274 [6:17:13<1:43:54, 22.92s/it]

Flurazepam

100%|██████████| 14792/14792 [00:09<00:00, 1628.40it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3358.34it/s]
 79%|███████▊  | 1003/1274 [6:17:35<1:42:16, 22.65s/it]

Flurazepam

100%|██████████| 14792/14792 [00:08<00:00, 1675.90it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3217.08it/s]

1
1
1

 79%|███████▉  | 1004/1274 [6:17:58<1:41:30, 22.56s/it]

Mycophenolic acid

100%|██████████| 14792/14792 [00:08<00:00, 1705.18it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3363.35it/s]

1
1

 79%|███████▉  | 1005/1274 [6:18:19<1:40:05, 22.33s/it]

1
1
1
1
Mycophenolate mofetil

100%|██████████| 14792/14792 [00:09<00:00, 1581.84it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3239.33it/s]
 79%|███████▉  | 1006/1274 [6:18:42<1:40:11, 22.43s/it]

Mycophenolate mofetil

100%|██████████| 14792/14792 [00:09<00:00, 1573.87it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3261.31it/s]
 79%|███████▉  | 1007/1274 [6:19:04<1:39:41, 22.40s/it]

Tamsulosin

100%|██████████| 14792/14792 [00:08<00:00, 1679.92it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3385.08it/s]

1
1
1

 79%|███████▉  | 1008/1274 [6:19:26<1:38:32, 22.23s/it]

Mycophenolate mofetil

100%|██████████| 14792/14792 [00:09<00:00, 1635.97it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3353.86it/s]

1
1

 79%|███████▉  | 1009/1274 [6:19:48<1:38:11, 22.23s/it]

1
1
Mycophenolate mofetil

100%|██████████| 14792/14792 [00:09<00:00, 1620.13it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3423.68it/s]
 79%|███████▉  | 1010/1274 [6:20:10<1:37:33, 22.17s/it]

Mycophenolate mofetil

100%|██████████| 14792/14792 [00:09<00:00, 1598.58it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3230.33it/s]

1
1
1
1
1

 79%|███████▉  | 1011/1274 [6:20:33<1:38:03, 22.37s/it]

Trovafloxacin

100%|██████████| 14792/14792 [00:09<00:00, 1579.02it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3034.01it/s]
 79%|███████▉  | 1012/1274 [6:20:57<1:39:01, 22.68s/it]

Midazolam

100%|██████████| 14792/14792 [00:09<00:00, 1584.38it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3281.57it/s]
 80%|███████▉  | 1013/1274 [6:21:19<1:38:29, 22.64s/it]

1
Midazolam

100%|██████████| 14792/14792 [00:09<00:00, 1563.92it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3325.52it/s]

1

 80%|███████▉  | 1014/1274 [6:21:42<1:38:03, 22.63s/it]

1
Midazolam

100%|██████████| 14792/14792 [00:09<00:00, 1549.18it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3188.61it/s]

1
1

 80%|███████▉  | 1015/1274 [6:22:05<1:38:28, 22.81s/it]

Eplerenone

100%|██████████| 14792/14792 [00:12<00:00, 1220.11it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3501.69it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

 80%|███████▉  | 1016/1274 [6:22:30<1:40:42, 23.42s/it]

Tamsulosin

100%|██████████| 14792/14792 [00:08<00:00, 1699.74it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3387.72it/s]
 80%|███████▉  | 1017/1274 [6:22:52<1:38:12, 22.93s/it]

Nateglinide

100%|██████████| 14792/14792 [00:08<00:00, 1717.99it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3319.76it/s]

1
1
1
1

 80%|███████▉  | 1018/1274 [6:23:14<1:36:23, 22.59s/it]

1
1
Norethisterone

100%|██████████| 14792/14792 [00:09<00:00, 1488.13it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3339.79it/s]

1
1

 80%|███████▉  | 1019/1274 [6:23:37<1:36:36, 22.73s/it]

1
Nateglinide

100%|██████████| 14792/14792 [00:08<00:00, 1665.97it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3429.52it/s]

1
1

 80%|████████  | 1020/1274 [6:23:58<1:34:58, 22.44s/it]

Nateglinide

100%|██████████| 14792/14792 [00:08<00:00, 1768.44it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3264.75it/s]

1
1
1
1
1
1

 80%|████████  | 1021/1274 [6:24:20<1:33:49, 22.25s/it]

Nitroglycerin

100%|██████████| 14792/14792 [00:08<00:00, 1823.61it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3409.14it/s]
 80%|████████  | 1022/1274 [6:24:41<1:31:27, 21.78s/it]

Nitroglycerin

100%|██████████| 14792/14792 [00:07<00:00, 1916.92it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3485.31it/s]
 80%|████████  | 1023/1274 [6:25:01<1:28:39, 21.19s/it]

Nitroglycerin

100%|██████████| 14792/14792 [00:07<00:00, 1881.61it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3423.68it/s]
 80%|████████  | 1024/1274 [6:25:21<1:27:05, 20.90s/it]

Adefovir dipivoxil

100%|██████████| 14792/14792 [00:09<00:00, 1613.09it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3314.43it/s]
 80%|████████  | 1025/1274 [6:25:43<1:28:21, 21.29s/it]

Norethisterone

100%|██████████| 14792/14792 [00:10<00:00, 1439.31it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3420.38it/s]

1
1

 81%|████████  | 1026/1274 [6:26:06<1:30:05, 21.80s/it]

1
Flurbiprofen

100%|██████████| 14792/14792 [00:08<00:00, 1761.41it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3306.69it/s]

1
1

 81%|████████  | 1027/1274 [6:26:28<1:29:24, 21.72s/it]

Tamsulosin

100%|██████████| 14792/14792 [00:08<00:00, 1665.68it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3343.16it/s]

1
1
1
1

 81%|████████  | 1028/1274 [6:26:49<1:29:09, 21.75s/it]

1
1
Flurbiprofen

100%|██████████| 14792/14792 [00:08<00:00, 1705.34it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3535.66it/s]

1
1
1
1

 81%|████████  | 1029/1274 [6:27:10<1:27:46, 21.50s/it]

1
1
Diethylcarbamazine

100%|██████████| 14792/14792 [00:08<00:00, 1785.22it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3464.75it/s]
 81%|████████  | 1030/1274 [6:27:31<1:26:16, 21.22s/it]

1
Lamivudine

100%|██████████| 14792/14792 [00:08<00:00, 1842.92it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3533.55it/s]

1

 81%|████████  | 1031/1274 [6:27:51<1:24:45, 20.93s/it]

Lamivudine

100%|██████████| 14792/14792 [00:08<00:00, 1740.06it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3342.88it/s]

1
1
1

 81%|████████  | 1032/1274 [6:28:13<1:24:56, 21.06s/it]

Lamivudine

100%|██████████| 14792/14792 [00:08<00:00, 1777.44it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3477.95it/s]
 81%|████████  | 1033/1274 [6:28:33<1:24:09, 20.95s/it]

1
1
1
Tamsulosin

100%|██████████| 14792/14792 [00:09<00:00, 1640.91it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3401.98it/s]

1
1
1
1

 81%|████████  | 1034/1274 [6:28:55<1:25:11, 21.30s/it]

1
1
Tamsulosin

100%|██████████| 14792/14792 [00:08<00:00, 1732.18it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3314.51it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

 81%|████████  | 1035/1274 [6:29:17<1:25:13, 21.39s/it]

Etoposide

100%|██████████| 14792/14792 [00:11<00:00, 1288.08it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3033.53it/s]

1
1
1

 81%|████████▏ | 1036/1274 [6:29:44<1:31:11, 22.99s/it]

1
Etoposide

100%|██████████| 14792/14792 [00:10<00:00, 1358.62it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3073.58it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1

 81%|████████▏ | 1037/1274 [6:30:09<1:33:57, 23.79s/it]

Etoposide

100%|██████████| 14792/14792 [00:11<00:00, 1331.09it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3087.89it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1

 81%|████████▏ | 1038/1274 [6:30:35<1:36:14, 24.47s/it]

Loperamide

100%|██████████| 14792/14792 [00:09<00:00, 1600.03it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3253.42it/s]

1
1
1
1

 82%|████████▏ | 1039/1274 [6:30:58<1:33:59, 24.00s/it]

1
1
1
1
Temozolomide

100%|██████████| 14792/14792 [00:08<00:00, 1816.84it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3439.01it/s]
 82%|████████▏ | 1040/1274 [6:31:19<1:29:22, 22.92s/it]

1
Temozolomide

100%|██████████| 14792/14792 [00:08<00:00, 1716.39it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3181.77it/s]
 82%|████████▏ | 1041/1274 [6:31:40<1:27:45, 22.60s/it]

1
Pseudoephedrine

100%|██████████| 14792/14792 [00:08<00:00, 1829.48it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3399.68it/s]
 82%|████████▏ | 1042/1274 [6:32:01<1:25:13, 22.04s/it]

1
1
1
1
1
1
1
1
1
Perphenazine

100%|██████████| 14792/14792 [00:09<00:00, 1503.50it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3098.20it/s]
 82%|████████▏ | 1043/1274 [6:32:25<1:27:04, 22.62s/it]

1
Perphenazine

100%|██████████| 14792/14792 [00:09<00:00, 1507.89it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3342.06it/s]

1

 82%|████████▏ | 1044/1274 [6:32:48<1:26:49, 22.65s/it]

Donepezil

100%|██████████| 14792/14792 [00:09<00:00, 1592.87it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3154.46it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

 82%|████████▏ | 1045/1274 [6:33:11<1:26:53, 22.77s/it]

Oxazepam

100%|██████████| 14792/14792 [00:09<00:00, 1598.90it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3289.06it/s]

1
1

 82%|████████▏ | 1046/1274 [6:33:34<1:26:15, 22.70s/it]

Loperamide

100%|██████████| 14792/14792 [00:09<00:00, 1601.98it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3267.30it/s]
 82%|████████▏ | 1047/1274 [6:33:56<1:25:41, 22.65s/it]

1
Terbinafine

100%|██████████| 14792/14792 [00:08<00:00, 1740.78it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3446.42it/s]

1
1
1

 82%|████████▏ | 1048/1274 [6:34:18<1:23:59, 22.30s/it]

Loperamide

100%|██████████| 14792/14792 [00:09<00:00, 1627.05it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3318.08it/s]
 82%|████████▏ | 1049/1274 [6:34:40<1:23:32, 22.28s/it]

Mifepristone

100%|██████████| 14792/14792 [00:10<00:00, 1398.31it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3261.13it/s]

1
1
1

 82%|████████▏ | 1050/1274 [6:35:04<1:25:39, 22.94s/it]

Mifepristone

100%|██████████| 14792/14792 [00:10<00:00, 1366.85it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3332.52it/s]

1
1
1
1

 82%|████████▏ | 1051/1274 [6:35:28<1:26:32, 23.28s/it]

Temazepam

100%|██████████| 14792/14792 [00:09<00:00, 1641.43it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3489.04it/s]

1
1
1
1
1

 83%|████████▎ | 1052/1274 [6:35:50<1:24:31, 22.84s/it]

Levomenthol

100%|██████████| 14792/14792 [00:08<00:00, 1802.12it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3389.03it/s]
 83%|████████▎ | 1053/1274 [6:36:11<1:21:52, 22.23s/it]

1
1
Tadalafil

100%|██████████| 14792/14792 [00:10<00:00, 1373.87it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3218.91it/s]

1
1

 83%|████████▎ | 1054/1274 [6:36:35<1:23:49, 22.86s/it]

1
Orciprenaline

100%|██████████| 14792/14792 [00:08<00:00, 1755.64it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3334.33it/s]

1
1
1
1

 83%|████████▎ | 1055/1274 [6:36:56<1:21:33, 22.34s/it]

Terbinafine

100%|██████████| 14792/14792 [00:08<00:00, 1764.51it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3288.88it/s]
 83%|████████▎ | 1056/1274 [6:37:18<1:20:18, 22.11s/it]

1
1
Terbinafine

100%|██████████| 14792/14792 [00:08<00:00, 1689.66it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3403.65it/s]
 83%|████████▎ | 1057/1274 [6:37:40<1:19:40, 22.03s/it]

1
1
Oxcarbazepine

100%|██████████| 14792/14792 [00:09<00:00, 1604.75it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3200.35it/s]

1
1
1

 83%|████████▎ | 1058/1274 [6:38:03<1:20:06, 22.25s/it]

Prednisone

100%|██████████| 14792/14792 [00:10<00:00, 1422.73it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3514.56it/s]

1
1
1

 83%|████████▎ | 1059/1274 [6:38:26<1:20:32, 22.48s/it]

Ranitidine

100%|██████████| 14792/14792 [00:08<00:00, 1741.45it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3460.80it/s]
 83%|████████▎ | 1060/1274 [6:38:47<1:18:36, 22.04s/it]

1
1
1
Ranitidine

100%|██████████| 14792/14792 [00:08<00:00, 1727.25it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3352.97it/s]
 83%|████████▎ | 1061/1274 [6:39:08<1:17:32, 21.84s/it]

1
1
Ranitidine

100%|██████████| 14792/14792 [00:08<00:00, 1734.22it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3279.74it/s]
 83%|████████▎ | 1062/1274 [6:39:29<1:16:45, 21.72s/it]

1
1
1
1
1
1
1
1
1
1
1
1
Vardenafil

100%|██████████| 14792/14792 [00:09<00:00, 1554.80it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2820.84it/s]
 83%|████████▎ | 1063/1274 [6:39:54<1:19:19, 22.56s/it]

Prednisone

100%|██████████| 14792/14792 [00:10<00:00, 1434.87it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3280.58it/s]

1
1
1
1
1
1
1
1
1

 84%|████████▎ | 1064/1274 [6:40:18<1:20:16, 22.94s/it]

1
1
1
Prednisone

100%|██████████| 14792/14792 [00:10<00:00, 1460.82it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3273.70it/s]

1
1
1
1
1
1
1
1
1

 84%|████████▎ | 1065/1274 [6:40:41<1:20:34, 23.13s/it]

1
1
1
Prednisone

100%|██████████| 14792/14792 [00:10<00:00, 1433.44it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3321.96it/s]

1
1
1

 84%|████████▎ | 1066/1274 [6:41:05<1:20:35, 23.25s/it]

Prednisone

100%|██████████| 14792/14792 [00:10<00:00, 1444.93it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3305.56it/s]

1
1
1

 84%|████████▍ | 1067/1274 [6:41:29<1:20:45, 23.41s/it]

Terbinafine

100%|██████████| 14792/14792 [00:08<00:00, 1715.39it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3410.17it/s]

1
1
1
1

 84%|████████▍ | 1068/1274 [6:41:50<1:18:31, 22.87s/it]

Prednisolone

100%|██████████| 14792/14792 [00:10<00:00, 1449.74it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3483.56it/s]

1
1
1

 84%|████████▍ | 1069/1274 [6:42:13<1:18:21, 22.93s/it]

Prednisolone

100%|██████████| 14792/14792 [00:10<00:00, 1472.55it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3323.29it/s]

1
1
1
1
1
1
1
1
1

 84%|████████▍ | 1070/1274 [6:42:37<1:18:23, 23.06s/it]

1
1
1
Prednisolone

100%|██████████| 14792/14792 [00:10<00:00, 1413.43it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3318.32it/s]

1
1
1
1
1
1
1
1
1

 84%|████████▍ | 1071/1274 [6:43:01<1:18:51, 23.31s/it]

1
1
1
Prednisolone

100%|██████████| 14792/14792 [00:10<00:00, 1411.43it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3262.50it/s]

1
1
1

 84%|████████▍ | 1072/1274 [6:43:25<1:19:09, 23.51s/it]

Prednisolone

100%|██████████| 14792/14792 [00:10<00:00, 1423.42it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3165.87it/s]

1
1
1

 84%|████████▍ | 1073/1274 [6:43:49<1:19:35, 23.76s/it]

Prednisolone

100%|██████████| 14792/14792 [00:09<00:00, 1483.46it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3302.02it/s]

1
1
1

 84%|████████▍ | 1074/1274 [6:44:12<1:18:52, 23.66s/it]

Terbinafine

100%|██████████| 14792/14792 [00:08<00:00, 1719.21it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3317.70it/s]
 84%|████████▍ | 1075/1274 [6:44:34<1:16:28, 23.06s/it]

Meloxicam

100%|██████████| 14792/14792 [00:08<00:00, 1670.23it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3564.07it/s]

1

 84%|████████▍ | 1076/1274 [6:44:55<1:14:07, 22.46s/it]

1
1
1
Indapamide

100%|██████████| 14792/14792 [00:08<00:00, 1657.31it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3373.96it/s]

1
1
1
1

 85%|████████▍ | 1077/1274 [6:45:17<1:13:06, 22.27s/it]

1
Indapamide

100%|██████████| 14792/14792 [00:09<00:00, 1601.58it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3294.37it/s]

1
1
1
1

 85%|████████▍ | 1078/1274 [6:45:39<1:12:55, 22.32s/it]

1
1
Estradiol

100%|██████████| 14792/14792 [00:10<00:00, 1452.90it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3456.81it/s]
 85%|████████▍ | 1079/1274 [6:46:02<1:13:21, 22.57s/it]

Estradiol

100%|██████████| 14792/14792 [00:09<00:00, 1499.35it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3285.77it/s]
 85%|████████▍ | 1080/1274 [6:46:26<1:13:57, 22.87s/it]

Estradiol

100%|██████████| 14792/14792 [00:10<00:00, 1469.98it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3274.29it/s]

1
1
1
1

 85%|████████▍ | 1081/1274 [6:46:50<1:14:08, 23.05s/it]

Estradiol

100%|██████████| 14792/14792 [00:09<00:00, 1497.85it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3346.91it/s]

1
1
1
1

 85%|████████▍ | 1082/1274 [6:47:13<1:13:54, 23.10s/it]

Estradiol

100%|██████████| 14792/14792 [00:09<00:00, 1502.68it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3269.48it/s]

1
1

 85%|████████▌ | 1083/1274 [6:47:36<1:13:42, 23.16s/it]

Estradiol

100%|██████████| 14792/14792 [00:10<00:00, 1439.85it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3379.02it/s]
 85%|████████▌ | 1084/1274 [6:47:59<1:13:33, 23.23s/it]

Estradiol

100%|██████████| 14792/14792 [00:09<00:00, 1498.54it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3269.83it/s]

1
1
1
1

 85%|████████▌ | 1085/1274 [6:48:23<1:13:09, 23.23s/it]

Estradiol

100%|██████████| 14792/14792 [00:10<00:00, 1472.90it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3266.75it/s]
 85%|████████▌ | 1086/1274 [6:48:46<1:12:49, 23.24s/it]

1
Estradiol

100%|██████████| 14792/14792 [00:10<00:00, 1453.97it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3241.30it/s]

1
1
1

 85%|████████▌ | 1087/1274 [6:49:10<1:12:52, 23.38s/it]

1
Indapamide

100%|██████████| 14792/14792 [00:08<00:00, 1656.75it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3237.75it/s]
 85%|████████▌ | 1088/1274 [6:49:32<1:11:33, 23.08s/it]

1
Phenelzine

100%|██████████| 14792/14792 [00:07<00:00, 1852.75it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3484.42it/s]
 85%|████████▌ | 1089/1274 [6:49:52<1:08:31, 22.23s/it]

1
1
1
1
1
1
Phenelzine

100%|██████████| 14792/14792 [00:07<00:00, 1872.24it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3481.77it/s]
 86%|████████▌ | 1090/1274 [6:50:12<1:06:10, 21.58s/it]

Phenelzine

100%|██████████| 14792/14792 [00:07<00:00, 1904.45it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3423.68it/s]
 86%|████████▌ | 1091/1274 [6:50:33<1:04:39, 21.20s/it]

Nalidixic acid

100%|██████████| 14792/14792 [00:08<00:00, 1748.09it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3380.73it/s]
 86%|████████▌ | 1092/1274 [6:50:54<1:04:15, 21.18s/it]

1
1
Oxcarbazepine

100%|██████████| 14792/14792 [00:09<00:00, 1615.73it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3271.40it/s]
 86%|████████▌ | 1093/1274 [6:51:16<1:05:14, 21.63s/it]

Oxcarbazepine

100%|██████████| 14792/14792 [00:09<00:00, 1606.16it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3428.61it/s]
 86%|████████▌ | 1094/1274 [6:51:38<1:05:12, 21.73s/it]

1
Oxcarbazepine

100%|██████████| 14792/14792 [00:08<00:00, 1653.52it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3193.08it/s]

1
1
1

 86%|████████▌ | 1095/1274 [6:52:01<1:05:49, 22.06s/it]

Estradiol

100%|██████████| 14792/14792 [00:10<00:00, 1463.28it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3259.70it/s]
 86%|████████▌ | 1096/1274 [6:52:25<1:06:47, 22.51s/it]

1
Estradiol

100%|██████████| 14792/14792 [00:10<00:00, 1453.60it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3207.00it/s]

1
1
1
1
1
1
1

 86%|████████▌ | 1097/1274 [6:52:49<1:07:27, 22.87s/it]

Estradiol

100%|██████████| 14792/14792 [00:10<00:00, 1444.50it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3117.53it/s]
 86%|████████▌ | 1098/1274 [6:53:13<1:08:17, 23.28s/it]

1
Estradiol

100%|██████████| 14792/14792 [00:09<00:00, 1514.72it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3130.60it/s]

1
1
1
1
1

 86%|████████▋ | 1099/1274 [6:53:37<1:08:24, 23.45s/it]

Pentoxifylline

100%|██████████| 14792/14792 [00:08<00:00, 1661.29it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3330.10it/s]
 86%|████████▋ | 1100/1274 [6:53:58<1:06:32, 22.94s/it]

1
1
1
1
1
1
1
1
1
1
Pentoxifylline

100%|██████████| 14792/14792 [00:08<00:00, 1763.53it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3321.78it/s]
 86%|████████▋ | 1101/1274 [6:54:20<1:04:49, 22.48s/it]

Pentoxifylline

100%|██████████| 14792/14792 [00:08<00:00, 1691.86it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3384.01it/s]
 86%|████████▋ | 1102/1274 [6:54:41<1:03:30, 22.16s/it]

Pentoxifylline

100%|██████████| 14792/14792 [00:08<00:00, 1655.00it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3382.90it/s]

1
1
1
1

 87%|████████▋ | 1103/1274 [6:55:03<1:02:48, 22.04s/it]

Pentoxifylline

100%|██████████| 14792/14792 [00:08<00:00, 1689.44it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3220.29it/s]

1
1
1
1

 87%|████████▋ | 1104/1274 [6:55:25<1:02:35, 22.09s/it]

Tazarotene

100%|██████████| 14792/14792 [00:09<00:00, 1640.36it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3288.82it/s]

1

 87%|████████▋ | 1105/1274 [6:55:47<1:02:19, 22.12s/it]

Sulfapyridine

100%|██████████| 14792/14792 [00:08<00:00, 1769.57it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3403.47it/s]

1
1
1
1

 87%|████████▋ | 1106/1274 [6:56:08<1:00:58, 21.78s/it]

1
1
Sulfapyridine

100%|██████████| 14792/14792 [00:08<00:00, 1680.19it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3556.63it/s]
 87%|████████▋ | 1107/1274 [6:56:29<59:48, 21.49s/it]

Primidone

100%|██████████| 14792/14792 [00:08<00:00, 1774.85it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3179.18it/s]
 87%|████████▋ | 1108/1274 [6:56:51<59:40, 21.57s/it]

Primidone

100%|██████████| 14792/14792 [00:08<00:00, 1752.23it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3270.48it/s]
 87%|████████▋ | 1109/1274 [6:57:12<59:19, 21.57s/it]

1
Perindopril

100%|██████████| 14792/14792 [00:08<00:00, 1700.94it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3214.89it/s]
 87%|████████▋ | 1110/1274 [6:57:35<59:42, 21.85s/it]

Perindopril

100%|██████████| 14792/14792 [00:08<00:00, 1652.24it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3199.30it/s]

1
1
1
1

 87%|████████▋ | 1111/1274 [6:57:58<1:00:05, 22.12s/it]

Perindopril

100%|██████████| 14792/14792 [00:09<00:00, 1616.03it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3075.42it/s]

1
1

 87%|████████▋ | 1112/1274 [6:58:21<1:00:48, 22.52s/it]

Mefenamic acid

100%|██████████| 14792/14792 [00:08<00:00, 1734.53it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3359.74it/s]

1

 87%|████████▋ | 1113/1274 [6:58:43<59:33, 22.20s/it]

1
Estradiol

100%|██████████| 14792/14792 [00:10<00:00, 1456.45it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3067.94it/s]
 87%|████████▋ | 1114/1274 [6:59:07<1:00:36, 22.73s/it]

1
Warfarin

100%|██████████| 14792/14792 [00:08<00:00, 1686.61it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3324.04it/s]

1
1
1
1

 88%|████████▊ | 1115/1274 [6:59:29<59:46, 22.55s/it]

1
1
Warfarin

100%|██████████| 14792/14792 [00:08<00:00, 1665.83it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3153.21it/s]

1
1
1
1

 88%|████████▊ | 1116/1274 [6:59:52<59:35, 22.63s/it]

1
1
Albendazole

100%|██████████| 14792/14792 [00:08<00:00, 1773.27it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3331.48it/s]
 88%|████████▊ | 1117/1274 [7:00:13<58:12, 22.25s/it]

1
1
1
Diclofenac

100%|██████████| 14792/14792 [00:08<00:00, 1790.16it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3379.72it/s]
 88%|████████▊ | 1118/1274 [7:00:34<56:54, 21.89s/it]

Fluticasone propionate

100%|██████████| 14792/14792 [00:10<00:00, 1386.08it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3289.15it/s]
 88%|████████▊ | 1119/1274 [7:00:58<58:12, 22.53s/it]

Diclofenac

100%|██████████| 14792/14792 [00:08<00:00, 1755.74it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3555.11it/s]

1
1
1
1

 88%|████████▊ | 1120/1274 [7:01:19<56:22, 21.97s/it]

1
1
Diclofenac

100%|██████████| 14792/14792 [00:08<00:00, 1744.67it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3262.62it/s]

1
1
1
1

 88%|████████▊ | 1121/1274 [7:01:41<56:00, 21.96s/it]

1
1
Diclofenac

100%|██████████| 14792/14792 [00:08<00:00, 1697.84it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3266.62it/s]

1
1

 88%|████████▊ | 1122/1274 [7:02:03<55:40, 21.98s/it]

Diclofenac

100%|██████████| 14792/14792 [00:08<00:00, 1713.41it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3625.42it/s]

1
1
1
1

 88%|████████▊ | 1123/1274 [7:02:23<54:25, 21.62s/it]

1
1
Diclofenac

100%|██████████| 14792/14792 [00:08<00:00, 1744.56it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3337.59it/s]
 88%|████████▊ | 1124/1274 [7:02:45<53:54, 21.56s/it]

1
Diclofenac

100%|██████████| 14792/14792 [00:08<00:00, 1764.84it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3256.77it/s]
 88%|████████▊ | 1125/1274 [7:03:06<53:36, 21.59s/it]

1
Nizatidine

100%|██████████| 14792/14792 [00:08<00:00, 1748.33it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3384.92it/s]
 88%|████████▊ | 1126/1274 [7:03:28<52:56, 21.47s/it]

1
1
1
1
1
1
1
1
1
1
1
1
Doxazosin

100%|██████████| 14792/14792 [00:10<00:00, 1453.49it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3140.80it/s]

1
1

 88%|████████▊ | 1127/1274 [7:03:52<54:48, 22.37s/it]

Enalapril

100%|██████████| 14792/14792 [00:09<00:00, 1591.28it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3372.04it/s]

1
1
1
1

 89%|████████▊ | 1128/1274 [7:04:15<54:40, 22.47s/it]

Levocarnitine

100%|██████████| 14792/14792 [00:07<00:00, 1859.61it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3361.42it/s]

1
1

 89%|████████▊ | 1129/1274 [7:04:36<53:01, 21.94s/it]

1
1
Levocarnitine

100%|██████████| 14792/14792 [00:07<00:00, 1902.90it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3413.26it/s]
 89%|████████▊ | 1130/1274 [7:04:56<51:43, 21.55s/it]

Voriconazole

100%|██████████| 14792/14792 [00:08<00:00, 1758.27it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3342.82it/s]

1
1
1

 89%|████████▉ | 1131/1274 [7:05:18<51:14, 21.50s/it]

Voriconazole

100%|██████████| 14792/14792 [00:08<00:00, 1679.31it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3368.67it/s]
 89%|████████▉ | 1132/1274 [7:05:39<51:00, 21.56s/it]

1
Lactulose

100%|██████████| 14792/14792 [00:08<00:00, 1812.18it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3265.55it/s]
 89%|████████▉ | 1133/1274 [7:06:00<50:21, 21.43s/it]

Lactulose

100%|██████████| 14792/14792 [00:08<00:00, 1739.40it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3374.49it/s]
 89%|████████▉ | 1134/1274 [7:06:22<49:48, 21.34s/it]

Doxazosin

100%|██████████| 14792/14792 [00:09<00:00, 1509.78it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3363.79it/s]

1
1

 89%|████████▉ | 1135/1274 [7:06:45<50:37, 21.86s/it]

Labetalol

100%|██████████| 14792/14792 [00:08<00:00, 1752.44it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3186.99it/s]

1
1

 89%|████████▉ | 1136/1274 [7:07:07<50:35, 22.00s/it]

Fenfluramine

100%|██████████| 14792/14792 [00:08<00:00, 1836.26it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3369.21it/s]
 89%|████████▉ | 1137/1274 [7:07:28<49:22, 21.62s/it]

Cisapride

100%|██████████| 14792/14792 [00:09<00:00, 1642.04it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3242.98it/s]
 89%|████████▉ | 1138/1274 [7:07:50<49:50, 21.99s/it]

1
Rifabutin

100%|██████████| 14792/14792 [00:13<00:00, 1083.65it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2890.92it/s]

1
1
1
1

 89%|████████▉ | 1139/1274 [7:08:20<54:45, 24.34s/it]

Ethionamide

100%|██████████| 14792/14792 [00:07<00:00, 1936.13it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3604.99it/s]
 89%|████████▉ | 1140/1274 [7:08:40<51:08, 22.90s/it]

1
1
Chloroquine

100%|██████████| 14792/14792 [00:08<00:00, 1699.76it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3432.81it/s]
 90%|████████▉ | 1141/1274 [7:09:01<49:47, 22.46s/it]

Sulindac

100%|██████████| 14792/14792 [00:08<00:00, 1677.21it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3421.98it/s]

1

 90%|████████▉ | 1142/1274 [7:09:23<48:49, 22.19s/it]

1
Sulindac

100%|██████████| 14792/14792 [00:08<00:00, 1663.43it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3374.78it/s]

1

 90%|████████▉ | 1143/1274 [7:09:45<48:23, 22.16s/it]

Cisapride

100%|██████████| 14792/14792 [00:08<00:00, 1656.21it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3162.06it/s]
 90%|████████▉ | 1144/1274 [7:10:08<48:23, 22.33s/it]

Cisapride

100%|██████████| 14792/14792 [00:09<00:00, 1610.33it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3224.18it/s]

1
1
1
1

 90%|████████▉ | 1145/1274 [7:10:31<48:29, 22.55s/it]

1
1
Cisapride

100%|██████████| 14792/14792 [00:08<00:00, 1680.32it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3287.45it/s]
 90%|████████▉ | 1146/1274 [7:10:53<47:50, 22.43s/it]

Labetalol

100%|██████████| 14792/14792 [00:08<00:00, 1752.71it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3320.10it/s]

1
1
1
1

 90%|█████████ | 1147/1274 [7:11:15<47:06, 22.26s/it]

Medroxyprogesterone acetate

100%|██████████| 14792/14792 [00:10<00:00, 1459.45it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3144.84it/s]

1
1
1
1
1
1
1
1
1
1
1
1

 90%|█████████ | 1148/1274 [7:11:39<47:55, 22.82s/it]

Medroxyprogesterone acetate

100%|██████████| 14792/14792 [00:10<00:00, 1467.64it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3374.43it/s]

1
1
1
1
1
1
1
1
1
1
1
1

 90%|█████████ | 1149/1274 [7:12:02<47:54, 23.00s/it]

1
Medroxyprogesterone acetate

100%|██████████| 14792/14792 [00:10<00:00, 1446.17it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3301.98it/s]

1

 90%|█████████ | 1150/1274 [7:12:26<47:56, 23.20s/it]

1
Ivermectin

100%|██████████| 14792/14792 [00:05<00:00, 2654.92it/s]
100%|██████████| 34899/34899 [00:08<00:00, 4294.24it/s]
 90%|█████████ | 1151/1274 [7:12:42<42:53, 20.93s/it]

Ivermectin

100%|██████████| 14792/14792 [00:05<00:00, 2715.91it/s]
100%|██████████| 34899/34899 [00:08<00:00, 4199.25it/s]
 90%|█████████ | 1152/1274 [7:12:57<39:24, 19.38s/it]

Labetalol

100%|██████████| 14792/14792 [00:08<00:00, 1735.99it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3522.22it/s]

1
1
1
1
1

 91%|█████████ | 1153/1274 [7:13:18<40:08, 19.90s/it]

1
1
Labetalol

100%|██████████| 14792/14792 [00:08<00:00, 1731.94it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3479.67it/s]

1
1
1
1

 91%|█████████ | 1154/1274 [7:13:40<40:53, 20.44s/it]

1
1
Lactulose

100%|██████████| 14792/14792 [00:08<00:00, 1674.57it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3304.36it/s]
 91%|█████████ | 1155/1274 [7:14:02<41:15, 20.80s/it]

Fenoprofen

100%|██████████| 14792/14792 [00:08<00:00, 1806.73it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3470.41it/s]
 91%|█████████ | 1156/1274 [7:14:23<40:58, 20.83s/it]

Warfarin

100%|██████████| 14792/14792 [00:09<00:00, 1588.83it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3515.19it/s]

1
1
1
1
1
1
1
1
1
1
1

 91%|█████████ | 1157/1274 [7:14:45<41:27, 21.26s/it]

1
1
1
1
1
Rofecoxib

100%|██████████| 14792/14792 [00:08<00:00, 1709.94it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3339.92it/s]
 91%|█████████ | 1158/1274 [7:15:07<41:19, 21.38s/it]

1
1
Nortriptyline

100%|██████████| 14792/14792 [00:08<00:00, 1652.27it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3567.77it/s]

1
1
1
1
1
1
1
1
1

 91%|█████████ | 1159/1274 [7:15:28<40:48, 21.29s/it]

Toremifene

100%|██████████| 14792/14792 [00:09<00:00, 1633.44it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3355.15it/s]

1
1
1
1

 91%|█████████ | 1160/1274 [7:15:50<41:06, 21.63s/it]

1
1
1
1
Ciprofloxacin

100%|██████████| 14792/14792 [00:09<00:00, 1623.31it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3143.12it/s]
 91%|█████████ | 1161/1274 [7:16:13<41:16, 21.92s/it]

1
Ciprofloxacin

100%|██████████| 14792/14792 [00:08<00:00, 1648.23it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3498.37it/s]
 91%|█████████ | 1162/1274 [7:16:34<40:32, 21.72s/it]

1
Ciprofloxacin

100%|██████████| 14792/14792 [00:09<00:00, 1570.80it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3379.80it/s]
 91%|█████████▏| 1163/1274 [7:16:56<40:21, 21.82s/it]

Rofecoxib

100%|██████████| 14792/14792 [00:08<00:00, 1743.46it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3451.15it/s]
 91%|█████████▏| 1164/1274 [7:17:17<39:41, 21.65s/it]

1
Rofecoxib

100%|██████████| 14792/14792 [00:08<00:00, 1702.53it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3168.42it/s]
 91%|█████████▏| 1165/1274 [7:17:40<39:40, 21.84s/it]

1
1
Rofecoxib

100%|██████████| 14792/14792 [00:08<00:00, 1676.25it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3340.68it/s]
 92%|█████████▏| 1166/1274 [7:18:01<39:21, 21.87s/it]

1
Amoxapine

100%|██████████| 14792/14792 [00:09<00:00, 1565.44it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3142.38it/s]

1
1
1
1

 92%|█████████▏| 1167/1274 [7:18:25<39:39, 22.24s/it]

1
1
Rofecoxib

100%|██████████| 14792/14792 [00:08<00:00, 1694.48it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3603.78it/s]
 92%|█████████▏| 1168/1274 [7:18:46<38:35, 21.84s/it]

1
Cyclophosphamide

100%|██████████| 14792/14792 [00:08<00:00, 1772.04it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3416.60it/s]
 92%|█████████▏| 1169/1274 [7:19:06<37:42, 21.55s/it]

1
Cyclophosphamide

100%|██████████| 14792/14792 [00:08<00:00, 1784.85it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3358.07it/s]
 92%|█████████▏| 1170/1274 [7:19:27<36:59, 21.34s/it]

1
Cyclophosphamide

100%|██████████| 14792/14792 [00:08<00:00, 1766.72it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3478.14it/s]
 92%|█████████▏| 1171/1274 [7:19:48<36:14, 21.12s/it]

1
1
Erlotinib

100%|██████████| 14792/14792 [00:08<00:00, 1659.56it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3284.04it/s]

1
1
1
1

 92%|█████████▏| 1172/1274 [7:20:10<36:22, 21.40s/it]

Trandolapril

100%|██████████| 14792/14792 [00:09<00:00, 1613.14it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3071.49it/s]
 92%|█████████▏| 1173/1274 [7:20:33<36:59, 21.98s/it]

Trandolapril

100%|██████████| 14792/14792 [00:09<00:00, 1622.13it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3400.95it/s]

1
1
1
1

 92%|█████████▏| 1174/1274 [7:20:56<36:57, 22.17s/it]

Benazepril

100%|██████████| 14792/14792 [00:09<00:00, 1597.97it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3206.32it/s]

1
1
1
1

 92%|█████████▏| 1175/1274 [7:21:19<37:10, 22.53s/it]

Amoxapine

100%|██████████| 14792/14792 [00:09<00:00, 1509.79it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3277.46it/s]

1
1
1
1

 92%|█████████▏| 1176/1274 [7:21:42<37:06, 22.72s/it]

1
1
Fenoprofen

100%|██████████| 14792/14792 [00:08<00:00, 1778.06it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3404.98it/s]

1
1

 92%|█████████▏| 1177/1274 [7:22:04<36:02, 22.29s/it]

Methotrexate

100%|██████████| 14792/14792 [00:09<00:00, 1544.77it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3218.28it/s]

1
1
1
1
1
1

 92%|█████████▏| 1178/1274 [7:22:27<36:23, 22.74s/it]

Propranolol

100%|██████████| 14792/14792 [00:08<00:00, 1748.69it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3389.37it/s]
 93%|█████████▎| 1179/1274 [7:22:49<35:27, 22.40s/it]

Propranolol

100%|██████████| 14792/14792 [00:08<00:00, 1764.58it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3481.91it/s]

1
1
1

 93%|█████████▎| 1180/1274 [7:23:10<34:34, 22.06s/it]

Propranolol

100%|██████████| 14792/14792 [00:08<00:00, 1652.29it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3496.61it/s]

1
1
1
1

 93%|█████████▎| 1181/1274 [7:23:32<33:52, 21.85s/it]

1
1
Propranolol

100%|██████████| 14792/14792 [00:08<00:00, 1721.62it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3402.61it/s]
 93%|█████████▎| 1182/1274 [7:23:53<33:21, 21.76s/it]

Carbamazepine

100%|██████████| 14792/14792 [00:09<00:00, 1618.12it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3647.24it/s]

1
1
1
1

 93%|█████████▎| 1183/1274 [7:24:14<32:38, 21.52s/it]

1
1
Carbamazepine

100%|██████████| 14792/14792 [00:09<00:00, 1621.23it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3363.81it/s]
 93%|█████████▎| 1184/1274 [7:24:36<32:26, 21.63s/it]

1
1
Carbamazepine

100%|██████████| 14792/14792 [00:09<00:00, 1618.14it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3475.94it/s]
 93%|█████████▎| 1185/1274 [7:24:57<31:55, 21.52s/it]

1
1
Bosentan

100%|██████████| 14792/14792 [00:09<00:00, 1615.12it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3068.29it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

 93%|█████████▎| 1186/1274 [7:25:21<32:30, 22.17s/it]

Pyridostigmine

100%|██████████| 14792/14792 [00:08<00:00, 1783.05it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3511.98it/s]
 93%|█████████▎| 1187/1274 [7:25:42<31:27, 21.69s/it]

1
1
1
Bosentan

100%|██████████| 14792/14792 [00:09<00:00, 1598.01it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3189.40it/s]

1
1
1

 93%|█████████▎| 1188/1274 [7:26:05<31:44, 22.14s/it]

Hydroxyzine

100%|██████████| 14792/14792 [00:09<00:00, 1615.98it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3483.99it/s]

1

 93%|█████████▎| 1189/1274 [7:26:27<31:12, 22.03s/it]

1
1
Lamotrigine

100%|██████████| 14792/14792 [00:08<00:00, 1785.86it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3533.11it/s]
 93%|█████████▎| 1190/1274 [7:26:47<30:13, 21.59s/it]

Piroxicam

100%|██████████| 14792/14792 [00:08<00:00, 1663.97it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3160.69it/s]

1
1
1
1

 93%|█████████▎| 1191/1274 [7:27:10<30:16, 21.88s/it]

1
1
1
Zafirlukast

100%|██████████| 14792/14792 [00:09<00:00, 1523.56it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3022.62it/s]
 94%|█████████▎| 1192/1274 [7:27:34<31:05, 22.75s/it]

Zafirlukast

100%|██████████| 14792/14792 [00:09<00:00, 1545.49it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3204.42it/s]

1
1
1
1
1
1
1
1
1

 94%|█████████▎| 1193/1274 [7:27:59<31:18, 23.19s/it]

1
1
1
Zafirlukast

100%|██████████| 14792/14792 [00:09<00:00, 1542.16it/s]
100%|██████████| 34899/34899 [00:12<00:00, 2859.83it/s]
 94%|█████████▎| 1194/1274 [7:28:24<31:44, 23.81s/it]

1
Rifabutin

100%|██████████| 14792/14792 [00:14<00:00, 1051.96it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3011.57it/s]

1
1
1
1

 94%|█████████▍| 1195/1274 [7:28:54<33:37, 25.53s/it]

Rifabutin

100%|██████████| 14792/14792 [00:13<00:00, 1094.50it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3059.29it/s]

1
1
1

 94%|█████████▍| 1196/1274 [7:29:22<34:27, 26.51s/it]

Triamcinolone

100%|██████████| 14792/14792 [00:10<00:00, 1438.97it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3150.02it/s]

1
1
1
1
1
1
1
1
1

 94%|█████████▍| 1197/1274 [7:29:47<33:11, 25.86s/it]

1
1
1
Aprepitant

100%|██████████| 14792/14792 [00:09<00:00, 1587.68it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3300.26it/s]
 94%|█████████▍| 1198/1274 [7:30:09<31:24, 24.80s/it]

Tamoxifen

100%|██████████| 14792/14792 [00:08<00:00, 1655.54it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3159.76it/s]

1
1
1
1

 94%|█████████▍| 1199/1274 [7:30:32<30:18, 24.24s/it]

1
1
1
1
Galantamine

100%|██████████| 14792/14792 [00:10<00:00, 1417.91it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3254.96it/s]

1
1
1

 94%|█████████▍| 1200/1274 [7:30:56<29:45, 24.13s/it]

1
Galantamine

100%|██████████| 14792/14792 [00:10<00:00, 1427.61it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3335.13it/s]

1
1

 94%|█████████▍| 1201/1274 [7:31:19<29:04, 23.90s/it]

1
1
Galantamine

100%|██████████| 14792/14792 [00:10<00:00, 1441.90it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3370.02it/s]

1
1
1
1

 94%|█████████▍| 1202/1274 [7:31:42<28:25, 23.69s/it]

Galantamine

100%|██████████| 14792/14792 [00:10<00:00, 1401.80it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3343.86it/s]
 94%|█████████▍| 1203/1274 [7:32:06<28:00, 23.67s/it]

Galantamine

100%|██████████| 14792/14792 [00:09<00:00, 1481.20it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3601.26it/s]
 95%|█████████▍| 1204/1274 [7:32:28<27:03, 23.19s/it]

1
Galantamine

100%|██████████| 14792/14792 [00:10<00:00, 1409.71it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3324.03it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

 95%|█████████▍| 1205/1274 [7:32:52<26:51, 23.35s/it]

Aprepitant

100%|██████████| 14792/14792 [00:09<00:00, 1594.94it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3154.51it/s]

1

 95%|█████████▍| 1206/1274 [7:33:15<26:22, 23.27s/it]

Tamoxifen

100%|██████████| 14792/14792 [00:08<00:00, 1696.03it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3182.86it/s]

1

 95%|█████████▍| 1207/1274 [7:33:38<25:48, 23.11s/it]

1
Aprepitant

100%|██████████| 14792/14792 [00:09<00:00, 1642.93it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3306.04it/s]
 95%|█████████▍| 1208/1274 [7:33:59<25:01, 22.74s/it]

Aprepitant

100%|██████████| 14792/14792 [00:09<00:00, 1598.86it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3240.06it/s]
 95%|█████████▍| 1209/1274 [7:34:22<24:32, 22.65s/it]

Aprepitant

100%|██████████| 14792/14792 [00:09<00:00, 1571.17it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3387.98it/s]
 95%|█████████▍| 1210/1274 [7:34:44<23:58, 22.48s/it]

Chlorpropamide

100%|██████████| 14792/14792 [00:08<00:00, 1789.00it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3406.51it/s]
 95%|█████████▌| 1211/1274 [7:35:05<23:04, 21.98s/it]

Chlorpropamide

100%|██████████| 14792/14792 [00:08<00:00, 1737.88it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3460.42it/s]

1
1
1
1
1
1
1

 95%|█████████▌| 1212/1274 [7:35:26<22:23, 21.68s/it]

Chlorpropamide

100%|██████████| 14792/14792 [00:08<00:00, 1767.32it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3267.36it/s]

1
1
1
1
1
1

 95%|█████████▌| 1213/1274 [7:35:47<21:56, 21.58s/it]

1
Chlorpropamide

100%|██████████| 14792/14792 [00:08<00:00, 1740.01it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3371.41it/s]

1
1
1
1
1
1
1

 95%|█████████▌| 1214/1274 [7:36:08<21:28, 21.48s/it]

Tamoxifen

100%|██████████| 14792/14792 [00:08<00:00, 1689.61it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3425.78it/s]

1
1
1
1
1
1
1
1
1

 95%|█████████▌| 1215/1274 [7:36:30<21:15, 21.62s/it]

1
1
1
Tamoxifen

100%|██████████| 14792/14792 [00:08<00:00, 1727.92it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3341.73it/s]

1
1
1
1

 95%|█████████▌| 1216/1274 [7:36:52<20:55, 21.65s/it]

1
1
Nicardipine

100%|██████████| 14792/14792 [00:09<00:00, 1628.83it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3419.97it/s]
 96%|█████████▌| 1217/1274 [7:37:14<20:41, 21.78s/it]

Warfarin

100%|██████████| 14792/14792 [00:09<00:00, 1605.21it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3348.05it/s]

1
1
1
1

 96%|█████████▌| 1218/1274 [7:37:37<20:34, 22.04s/it]

1
1
Warfarin

100%|██████████| 14792/14792 [00:08<00:00, 1671.99it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3409.48it/s]
 96%|█████████▌| 1219/1274 [7:37:59<20:12, 22.05s/it]

1
1
Warfarin

100%|██████████| 14792/14792 [00:09<00:00, 1638.99it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3430.62it/s]
 96%|█████████▌| 1220/1274 [7:38:21<19:53, 22.09s/it]

1
1
Warfarin

100%|██████████| 14792/14792 [00:08<00:00, 1670.33it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3307.06it/s]

1
1
1
1

 96%|█████████▌| 1221/1274 [7:38:43<19:35, 22.18s/it]

1
1
Warfarin

100%|██████████| 14792/14792 [00:08<00:00, 1681.91it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3187.39it/s]

1
1
1
1

 96%|█████████▌| 1222/1274 [7:39:06<19:20, 22.32s/it]

1
1
Warfarin

100%|██████████| 14792/14792 [00:08<00:00, 1670.00it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3471.02it/s]

1
1
1
1
1
1
1
1
1
1
1

 96%|█████████▌| 1223/1274 [7:39:28<18:48, 22.14s/it]

1
1
1
1
1
Warfarin

100%|██████████| 14792/14792 [00:09<00:00, 1589.06it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3261.67it/s]

1
1
1
1
1
1
1
1
1
1
1

 96%|█████████▌| 1224/1274 [7:39:51<18:39, 22.39s/it]

1
1
1
1
1
Warfarin

100%|██████████| 14792/14792 [00:09<00:00, 1600.66it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3147.29it/s]

1
1
1
1

 96%|█████████▌| 1225/1274 [7:40:14<18:27, 22.59s/it]

1
1
Warfarin

100%|██████████| 14792/14792 [00:08<00:00, 1688.17it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3343.57it/s]

1
1
1
1

 96%|█████████▌| 1226/1274 [7:40:36<17:57, 22.45s/it]

1
1
Losartan

100%|██████████| 14792/14792 [00:09<00:00, 1552.17it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3214.93it/s]

1
1

 96%|█████████▋| 1227/1274 [7:40:59<17:45, 22.67s/it]

1
1
Warfarin

100%|██████████| 14792/14792 [00:09<00:00, 1600.50it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3529.69it/s]

1
1
1
1

 96%|█████████▋| 1228/1274 [7:41:21<17:12, 22.45s/it]

1
1
Warfarin

100%|██████████| 14792/14792 [00:08<00:00, 1674.75it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3157.20it/s]
 96%|█████████▋| 1229/1274 [7:41:44<16:54, 22.54s/it]

1
Thioridazine

100%|██████████| 14792/14792 [00:09<00:00, 1558.97it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3233.26it/s]
 97%|█████████▋| 1230/1274 [7:42:07<16:41, 22.75s/it]

1
Thioridazine

100%|██████████| 14792/14792 [00:09<00:00, 1533.69it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3380.13it/s]

1
1
1
1

 97%|█████████▋| 1231/1274 [7:42:30<16:18, 22.75s/it]

Thioridazine

100%|██████████| 14792/14792 [00:09<00:00, 1545.51it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3166.68it/s]

1
1

 97%|█████████▋| 1232/1274 [7:42:53<16:02, 22.93s/it]

Losartan

100%|██████████| 14792/14792 [00:09<00:00, 1611.78it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3346.05it/s]
 97%|█████████▋| 1233/1274 [7:43:15<15:31, 22.73s/it]

1
1
1
Losartan

100%|██████████| 14792/14792 [00:08<00:00, 1676.50it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3422.78it/s]
 97%|█████████▋| 1234/1274 [7:43:37<14:56, 22.41s/it]

Chlorpropamide

100%|██████████| 14792/14792 [00:08<00:00, 1760.75it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3506.49it/s]

1
1
1
1
1
1
1

 97%|█████████▋| 1235/1274 [7:43:58<14:15, 21.94s/it]

Sumatriptan

100%|██████████| 14792/14792 [00:08<00:00, 1701.84it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3463.19it/s]
 97%|█████████▋| 1236/1274 [7:44:19<13:45, 21.71s/it]

Sumatriptan

100%|██████████| 14792/14792 [00:08<00:00, 1738.32it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3441.70it/s]
 97%|█████████▋| 1237/1274 [7:44:40<13:16, 21.53s/it]

Clorazepic acid

100%|██████████| 14792/14792 [00:08<00:00, 1656.92it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3399.43it/s]
 97%|█████████▋| 1238/1274 [7:45:02<12:58, 21.64s/it]

Astemizole

100%|██████████| 14792/14792 [00:09<00:00, 1556.17it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3093.60it/s]

1
1
1
1

 97%|█████████▋| 1239/1274 [7:45:26<12:59, 22.26s/it]

1
1
Prednisone

100%|██████████| 14792/14792 [00:10<00:00, 1435.20it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3350.40it/s]

1
1
1
1
1
1
1
1
1

 97%|█████████▋| 1240/1274 [7:45:49<12:51, 22.68s/it]

1
1
1
Prednisone

100%|██████████| 14792/14792 [00:10<00:00, 1420.61it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3269.69it/s]

1
1
1
1
1
1
1
1
1

 97%|█████████▋| 1241/1274 [7:46:14<12:42, 23.11s/it]

1
1
1
Prednisone

100%|██████████| 14792/14792 [00:10<00:00, 1443.87it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3431.83it/s]

1
1
1
1
1
1
1

 97%|█████████▋| 1242/1274 [7:46:37<12:19, 23.10s/it]

Prednisone

100%|██████████| 14792/14792 [00:10<00:00, 1438.89it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3417.61it/s]

1
1
1

 98%|█████████▊| 1243/1274 [7:47:00<11:59, 23.21s/it]

Prednisone

100%|██████████| 14792/14792 [00:10<00:00, 1451.12it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3383.82it/s]

1
1
1

 98%|█████████▊| 1244/1274 [7:47:23<11:37, 23.26s/it]

Prednisone

100%|██████████| 14792/14792 [00:10<00:00, 1464.57it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3474.24it/s]

1
1
1

 98%|█████████▊| 1245/1274 [7:47:46<11:10, 23.11s/it]

Niacin

100%|██████████| 14792/14792 [00:08<00:00, 1821.47it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3355.44it/s]
 98%|█████████▊| 1246/1274 [7:48:07<10:29, 22.47s/it]

Epinephrine

100%|██████████| 14792/14792 [00:08<00:00, 1830.65it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3313.30it/s]

1
1
1

 98%|█████████▊| 1247/1274 [7:48:29<09:57, 22.13s/it]

1
Niacin

100%|██████████| 14792/14792 [00:07<00:00, 1890.31it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3451.47it/s]
 98%|█████████▊| 1248/1274 [7:48:49<09:20, 21.56s/it]

Niacin

100%|██████████| 14792/14792 [00:07<00:00, 1852.65it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3348.54it/s]
 98%|█████████▊| 1249/1274 [7:49:09<08:52, 21.30s/it]

1
Niacin

100%|██████████| 14792/14792 [00:08<00:00, 1848.75it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3445.05it/s]
 98%|█████████▊| 1250/1274 [7:49:30<08:25, 21.05s/it]

1
Niacin

100%|██████████| 14792/14792 [00:08<00:00, 1812.06it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3392.62it/s]
 98%|█████████▊| 1251/1274 [7:49:51<08:01, 20.95s/it]

Niacin

100%|██████████| 14792/14792 [00:07<00:00, 1890.98it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3678.67it/s]
 98%|█████████▊| 1252/1274 [7:50:10<07:31, 20.50s/it]

Fluphenazine

100%|██████████| 14792/14792 [00:09<00:00, 1503.39it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3187.98it/s]
 98%|█████████▊| 1253/1274 [7:50:34<07:30, 21.44s/it]

1
Nicardipine

100%|██████████| 14792/14792 [00:09<00:00, 1587.12it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3075.74it/s]
 98%|█████████▊| 1254/1274 [7:50:57<07:22, 22.13s/it]

1
Astemizole

100%|██████████| 14792/14792 [00:09<00:00, 1578.52it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3147.80it/s]
 99%|█████████▊| 1255/1274 [7:51:21<07:06, 22.47s/it]

Astemizole

100%|██████████| 14792/14792 [00:09<00:00, 1541.92it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3108.85it/s]
 99%|█████████▊| 1256/1274 [7:51:44<06:51, 22.85s/it]

Astemizole

100%|██████████| 14792/14792 [00:09<00:00, 1526.07it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3331.27it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

 99%|█████████▊| 1257/1274 [7:52:08<06:29, 22.90s/it]

Simvastatin

100%|██████████| 14792/14792 [00:09<00:00, 1575.65it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3161.81it/s]

1

 99%|█████████▊| 1258/1274 [7:52:31<06:09, 23.09s/it]

1
Epinephrine

100%|██████████| 14792/14792 [00:08<00:00, 1793.61it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3409.82it/s]

1
1
1

 99%|█████████▉| 1259/1274 [7:52:52<05:37, 22.51s/it]

1
Verapamil

100%|██████████| 14792/14792 [00:08<00:00, 1656.25it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3294.37it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

 99%|█████████▉| 1260/1274 [7:53:15<05:16, 22.58s/it]

Verapamil

100%|██████████| 14792/14792 [00:09<00:00, 1603.31it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3275.42it/s]

1
1
1
1

 99%|█████████▉| 1261/1274 [7:53:38<04:54, 22.69s/it]

Verapamil

100%|██████████| 14792/14792 [00:08<00:00, 1684.67it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3012.61it/s]
 99%|█████████▉| 1262/1274 [7:54:01<04:35, 22.94s/it]

Verapamil

100%|██████████| 14792/14792 [00:08<00:00, 1671.31it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3113.54it/s]

1
1
1
1
1
1
1
1
1
1
1
1
1

 99%|█████████▉| 1263/1274 [7:54:25<04:12, 23.00s/it]

Trazodone

100%|██████████| 14792/14792 [00:09<00:00, 1642.60it/s]
100%|██████████| 34899/34899 [00:11<00:00, 2934.86it/s]

1
1
1
1

 99%|█████████▉| 1264/1274 [7:54:48<03:51, 23.16s/it]

1
1
Trazodone

100%|██████████| 14792/14792 [00:08<00:00, 1682.06it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3215.82it/s]

1

 99%|█████████▉| 1265/1274 [7:55:10<03:26, 22.92s/it]

1
Trazodone

100%|██████████| 14792/14792 [00:09<00:00, 1635.70it/s]
100%|██████████| 34899/34899 [00:11<00:00, 3150.10it/s]
 99%|█████████▉| 1266/1274 [7:55:33<03:02, 22.84s/it]

Leucovorin

100%|██████████| 14792/14792 [00:09<00:00, 1607.80it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3281.93it/s]
 99%|█████████▉| 1267/1274 [7:55:56<02:40, 22.94s/it]

Mitotane

100%|██████████| 14792/14792 [00:08<00:00, 1702.48it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3414.91it/s]
100%|█████████▉| 1268/1274 [7:56:18<02:14, 22.47s/it]

Mitotane

100%|██████████| 14792/14792 [00:08<00:00, 1844.46it/s]
100%|██████████| 34899/34899 [00:09<00:00, 3553.35it/s]
100%|█████████▉| 1269/1274 [7:56:38<01:49, 21.86s/it]

1
Mebendazole

100%|██████████| 14792/14792 [00:08<00:00, 1672.77it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3383.50it/s]

1

100%|█████████▉| 1270/1274 [7:57:00<01:27, 21.88s/it]

Simvastatin

100%|██████████| 14792/14792 [00:09<00:00, 1595.50it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3391.12it/s]

1
1
1
1

100%|█████████▉| 1271/1274 [7:57:22<01:06, 22.06s/it]

Simvastatin

100%|██████████| 14792/14792 [00:08<00:00, 1663.01it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3470.37it/s]

1
1

100%|█████████▉| 1272/1274 [7:57:44<00:43, 21.97s/it]

Simvastatin

100%|██████████| 14792/14792 [00:09<00:00, 1607.79it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3378.38it/s]
100%|█████████▉| 1273/1274 [7:58:07<00:22, 22.17s/it]

1
Dexmethylphenidate

100%|██████████| 14792/14792 [00:08<00:00, 1764.77it/s]
100%|██████████| 34899/34899 [00:10<00:00, 3363.64it/s]

1
1
1
1

100%|██████████| 1274/1274 [7:58:28<00:00, 22.53s/it]

1
1

In [11]:
result_num_df = pd.DataFrame(result_num)
result_num_df[result_num_df['success_predict']==1]
# failed_index2 = result_num_df[result_num_df['success_predict'] == 0].index
# print(failed_index2)

,drug_name,reaction_num,ec4_num,ec4_list,ec3_num,ec3_list,success_predict,success_ecnumber
0,Cyclosporine,1342,560,"['2.3.1.285', '3.2.1.3', '3.2.1.20', '6.3.1.10...",63,"['1.14.14', '3.1.1', '1.13.12', '1.1.99', '2.5...",1,"['1.14.15', '1.14.-']"
1,Gliclazide,186,174,"['1.14.13.71', '1.14.13.44', '3.2.1.137', '1.1...",41,"['1.14.14', '3.1.1', '1.14.-', '5.1.3', '1.3.1...",1,['1.14.14']
2,Pioglitazone,287,235,"['2.1.1.M10', '6.3.1.10', '1.14.13.71', '1.14....",54,"['1.8.3', '1.14.14', '1.13.12', '3.1.1', '1.14...",1,['1.14.14']
4,Proguanil,111,124,"['1.14.13.71', '1.14.13.44', '1.14.11.-', '1.1...",28,"['1.14.14', '1.14.-', '1.11.1', '1.14.20', '1....",1,[]
6,Tolbutamide,205,193,"['1.14.13.71', '1.14.13.44', '3.2.1.137', '1.1...",44,"['1.14.14', '1.13.12', '3.1.1', '1.14.-', '5.1...",1,['1.14.14']
...,...,...,...,...,...,...,...,...
1269,Mebendazole,311,214,"['2.1.1.M10', '1.14.13.71', '1.14.13.44', '3.2...",45,"['1.14.14', '3.1.1', '1.13.12', '1.14.-', '5.1...",1,['3.1.1']
1270,Simvastatin,539,545,"['2.3.1.285', '3.2.1.3', '3.2.1.20', '1.1.1.28...",59,"['1.14.14', '3.1.1', '1.13.12', '1.1.99', '2.5...",1,"['2.3.1', '3.1.1', '3.4.21']"
1271,Simvastatin,539,545,"['2.3.1.285', '3.2.1.3', '3.2.1.20', '1.1.1.28...",59,"['1.14.14', '3.1.1', '1.13.12', '1.1.99', '2.5...",1,['1.3.1']
1272,Simvastatin,539,545,"['2.3.1.285', '3.2.1.3', '3.2.1.20', '1.1.1.28...",59,"['1.14.14', '3.1.1', '1.13.12', '1.1.99', '2.5...",1,[]
1273,Dexmethylphenidate,285,277,"['1.14.13.71', '1.14.13.44', '3.2.1.137', '1.1...",53,"['1.14.14', '3.1.1', '1.14.-', '5.1.3', '1.3.1...",1,"['1.14.-', '1.14.11', '1.14.13']"

In [19]:
result_num_df['success_predict'].value_counts()

1    944
0    330
Name: success_predict, dtype: int64