In [16]:
import pandas as pd
import numpy as np
import json
from rdkit import Chem
from rdkit.Chem import Draw
from rdkit.Chem import rdChemReactions
from rdkit.Chem.Draw import rdMolDraw2D
from rdkit.Chem.Draw import IPythonConsole
from IPython.display import SVG, display
from rdkit.Chem.Fingerprints import FingerprintMols
from rdkit import DataStructs
from rdkit.Chem import MACCSkeys
from rdkit.Chem import AllChem
import pandas as pd
import rdchiral
import itertools
import pickle
import sys
from tqdm import tqdm 
from rdchiral.main import rdchiralRun, rdchiralRunText, rdchiralReaction, rdchiralReactants
import cobra
from itertools import chain, combinations
import sys
import multiprocessing
from functools import partial
import matplotlib.pyplot as plt
import multiprocessing
from tqdm import tqdm
sys.path.append('../')

from common import *

### input and output

In [ ]:
# step1
#input
mnxreac_smile_atom_mapping_rules_file_path = '../../Data/retrosynthesis/MNXreaction_smiles_atommap_rules_filter_0.2.csv'
mnxreac_smile_atom_mapping_rules_file_path = '/home/wuke/project/microbiome–drug/Results/MNXreaction_smiles_atommap_rules_filter_0.2.csv'
target_drug_path = '../../Data/Drug/drug_MDM+_Javdan_2020.xlsx'

###output

In [18]:
def process_rule(rule_smiles, mets_total_smiles):
    score = []
    smiles = []
    if 'C' in rule_smiles or 'c' in rule_smiles:
        for j in mets_total_smiles:
            current_score = calculate_similarity(rule_smiles, j)
            if current_score > 0.3:               ########################################################################
                score.append(current_score)
                smiles.append(j)
    else:
        smiles.append(rule_smiles)
        score.append(1)

    if len(score) == 0:
        return rule_smiles, [], []
    elif len(score) > 50:
        top40_data = sorted(zip(score, smiles), reverse=True)[:50]
    else:
        top40_data = sorted(zip(score, smiles), reverse=True)
    
    top40_scores, top40_smiles = zip(*top40_data)
    
    return rule_smiles, list(top40_smiles), list(top40_scores)

####################################################################################

def count_carbons(smiles):
    """计算一个 SMILES 字符串中碳 (C) 的个数"""
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return 0
    return sum(1 for atom in mol.GetAtoms() if atom.GetSymbol() == 'C')

# def process_rule(rule_smiles, mets_total_smiles):
#     score = []
#     smiles = []
    
#     # 计算 rule_smiles 的碳原子数
#     rule_c_count = count_carbons(rule_smiles)

#     if 'C' in rule_smiles or 'c' in rule_smiles:
#         for j in mets_total_smiles:
#             # 计算当前代谢物的碳原子数
#             j_c_count = count_carbons(j)
            
#             # 根据 mets_total_smiles 的碳原子数目，确定允许的碳数目差
#             if j_c_count < 10:
#                 allowed_diff = 1
#             elif j_c_count < 15:
#                 allowed_diff = 2
#             else:
#                 allowed_diff = 3
            
#             # 仅在碳数目差符合要求时计算相似度
#             if abs(rule_c_count - j_c_count) <= allowed_diff:
#                 current_score = calculate_similarity(rule_smiles, j)
#                 if current_score > 0.3:
#                     score.append(current_score)
#                     smiles.append(j)
    
#     else:
#         smiles.append(rule_smiles)
#         score.append(1)

#     if len(score) == 0:
#         return rule_smiles, [], []
#     elif len(score) > 20:
#         top20_data = sorted(zip(score, smiles), reverse=True)[:20]
#     else:
#         top20_data = sorted(zip(score, smiles), reverse=True)
    
#     top20_scores, top20_smiles = zip(*top20_data)
    
#     return rule_smiles, list(top20_smiles), list(top20_scores)

# def process_rule(rule_smiles, mets_total_smiles):
#     score = []
#     smiles = []
    
#     # 计算 rule_smiles 的碳原子数
#     rule_c_count = count_carbons(rule_smiles)

#     if 'C' in rule_smiles or 'c' in rule_smiles:
#         for j in mets_total_smiles:
#             # 计算当前代谢物的碳原子数
#             j_c_count = count_carbons(j)
            
#             # 计算相似度
#             current_score = calculate_similarity(rule_smiles, j)
            
#             # 计算罚分
#             if rule_c_count!=0:
#                 if rule_c_count > j_c_count:
#                     penalty = (rule_c_count - j_c_count) / (rule_c_count) /10.216
#                 elif rule_c_count < j_c_count:
#                     penalty = (j_c_count - rule_c_count) / (rule_c_count) /8.828
#                 else:
#                     penalty = 0
#             else:
#                 penalty = 0
            
#             # 应用罚分
#             adjusted_score = max(0, current_score - penalty)

#             # 仅保留相似度大于0.3的结果
#             if adjusted_score > -5:
#                 score.append(adjusted_score)
#                 smiles.append(j)
    
#     else:
#         smiles.append(rule_smiles)
#         score.append(1)

#     if len(score) == 0:
#         return rule_smiles, [], []
#     # elif len(score) > 100:
#     #     top20_data = sorted(zip(score, smiles), reverse=True)[:100]
#     else:
#         top20_data = sorted(zip(score, smiles), reverse=True)
    
#     top20_scores, top20_smiles = zip(*top20_data)
    
#     return rule_smiles, list(top20_smiles), list(top20_scores)

# def process_rule(rule_smiles, mets_total_smiles):
#     score = []
#     smiles = []
    
#     # 计算 rule_smiles 的碳原子数
#     rule_c_count = count_carbons(rule_smiles)

#     if 'C' in rule_smiles or 'c' in rule_smiles:
#         for j in mets_total_smiles:
#             # 计算当前代谢物的碳原子数
#             j_c_count = count_carbons(j)
            
#             # 计算相似度
#             current_score = calculate_similarity(rule_smiles, j)
# # 最小满足条件的 N: 21.8108108108, M: 2.4864864865
#             # 计算罚分
#             if rule_c_count!=0:
#                 if rule_c_count > j_c_count:
#                     penalty = (rule_c_count - j_c_count) / (rule_c_count) /2.4864864865
#                 elif rule_c_count < j_c_count:
#                     penalty = (j_c_count - rule_c_count) / (rule_c_count) /21.8108108108
#                 else:
#                     penalty = 0
#             else:
#                 penalty = 0
            
#             # 应用罚分
#             adjusted_score = max(0, current_score - penalty)

#             # 仅保留相似度大于0.3的结果
#             if adjusted_score > 0.1:
#                 score.append(adjusted_score)
#                 smiles.append(j)
    
#     else:
#         smiles.append(rule_smiles)
#         score.append(1)

#     if len(score) == 0:
#         return rule_smiles, [], []
#     # elif len(score) > 20:
#     #     top20_data = sorted(zip(score, smiles), reverse=True)[:20]
#     else:
#         top20_data = sorted(zip(score, smiles), reverse=True)
    
#     top20_scores, top20_smiles = zip(*top20_data)
    
#     return rule_smiles, list(top20_smiles), list(top20_scores)

In [19]:
# for index,row in retrosys_smiles_calculate_similarity_pd.iterrows():
#     if row['rules_smiles'] not in row['smiles_in_mets_total_smiles']:
#         retrosys_smiles_calculate_similarity_pd.loc[index,'smiles_in_mets_total_smiles'] = row['smiles_in_mets_total_smiles'].append(row['rules_smiles'])

In [20]:
def process_retrorule(index_row, mets_total_smiles,retrosys_smiles_calculate_similarity_pd,heterologous_met_smiles):
    rxndb_list_tmp = []
    # newdbSmiles_tmp = []
    failedrxn_tmp = []
    index, row = index_row
    rxn_id, ECnumber, reactants, products = row['MNX_ID'], row['classifs'], row['substrate_smiles'], row['product_smiles']
    deprecated_equ_smiles, reactantSMARTs, productSMARTs, rule = row['deprecated_equ_smiles'], row['ReactantsSMARTs'], row['ProductSMARTs'], row['RetroRules']
    deprecated_equ_smiles = deprecated_equ_smiles.split('>>')
    if rxn_id not in ['MNXR101882', 'MNXR101884', 'MNXR101879', 'MNXR101885', 'MNXR101886', 'MNXR101887',
                        'MNXR103528', 'MNXR103575']:  # ATP NADH conversion stuff
        productSMARTs = productSMARTs.split('.')
        products = products.split('.')
        new_products_smiles = []
        scores = []
        
        if len(productSMARTs) == len(products):
            for x in range(len(productSMARTs)):  # prepare mets with substructure and sort the reactants combination
                new_products_smile_one,score_one = get_calculate_similarity(products[x],retrosys_smiles_calculate_similarity_pd)
                new_products_smiles.append(new_products_smile_one)
                scores.append(score_one)

            product_prepared = []
            scores_prepared = []
            for lst, score_lst in zip(new_products_smiles, scores):
                if heterologous_met_smiles in lst:
                    if len(new_products_smiles) == 1:  # if only one sub list
                        product_prepared.append([heterologous_met_smiles])
                        scores_prepared.append(score_lst)
                    else:
                        other_lists = [sub_lst for sub_lst in new_products_smiles if sub_lst != lst]
                        tmp_product = list(itertools.product([heterologous_met_smiles], *other_lists))
                        product_prepared += tmp_product

                        tmp_scores = list(itertools.product([score_lst[new_products_smiles.index(lst)]], *scores))
                        scores_prepared += tmp_scores
            # print('product_prepared',product_prepared,len(product_prepared))
            for m in range(0, len(product_prepared)):  # apply the rule and output the rxn
                smile = product_prepared[m]
                score = scores_prepared[m]
                
                if len(smile) > 1:
                    product_smile = '.'.join(smile)
                else:
                    product_smile = smile[0]

                retrorule_tmp = rule.split('>>')
                retrorule_tmp = '(' + retrorule_tmp[0] + ')>>' + '(' + retrorule_tmp[1] + ')'            
                product_smile_tmp = product_smile
                # print('retrorule_tmp',retrorule_tmp)
                # print('product_smile',product_smile)
                try:
                    # print('product_smile_tmp',product_smile_tmp)
                    product_mol = Chem.MolFromSmiles(product_smile_tmp)
                    reaction = AllChem.ReactionFromSmarts(retrorule_tmp)
                    reactant_smiles = reaction.RunReactants((product_mol,))
                    smiles = [Chem.MolToSmiles(x[0]) for x in reactant_smiles]
                    reactant_smiles = list(set(smiles))

                    for reactant_smile in reactant_smiles:
                        if len(deprecated_equ_smiles) > 0:
                            if deprecated_equ_smiles[0] == '':
                                reactant_smile_final = reactant_smile
                            else:
                                reactant_smile_final = reactant_smile + '.' + deprecated_equ_smiles[0]
                            if deprecated_equ_smiles[1] == '':
                                product_smile_final = product_smile_tmp
                            else:
                                product_smile_final = product_smile_tmp + '.' + deprecated_equ_smiles[1]
                        rxn_smiles = reactant_smile + '>>' + product_smile_tmp
                        rxn_smiles_final = reactant_smile_final + '>>' + product_smile_final
                        
                        tmp = {
                            'EC number': ECnumber,
                            'rule': rule,
                            'templateID': rxn_id,
                            'templateSubstrate': products,
                            'rxn_smiles_basic': rxn_smiles,
                            'rxn_smiles_final': rxn_smiles_final,
                            'reactant_smile': reactant_smile,
                            'productsmile': product_smile_tmp,
                            'similarity': score
                        }
                        if check_rule(tmp['rxn_smiles_basic'])=='blance':
                            rxndb_list_tmp.append(tmp)  
                            # mets_tmp = reactant_smile.split('.')      
                            # for reactant in mets_tmp:             
                            #     if reactant not in mets_total_smiles and reactant not in newdbSmiles_tmp:         
                            #         newdbSmiles_tmp.append(reactant)        
                except:
                    failedrxn_tmp.append(rxn_id)
                
    return(rxndb_list_tmp,failedrxn_tmp)

In [21]:
def process_ec_list(ec_list,topn):
    processed_set = set()
    
    for ec in ec_list:
        for sub_ec in ec.split(';'):
            parts = sub_ec.strip().split('.')
            if len(parts) >= 3:  # Only process EC numbers with at least 3 parts
                processed_set.add('.'.join(parts[:topn]))
    
    return list(processed_set)

# Example usage
input_ec_numbers = ['4.1.3.-', '3.1.3.1', '1.1.3.100;2.1.4.2']
output_ec_numbers = process_ec_list(input_ec_numbers,3)
print(output_ec_numbers)

['1.1.3', '3.1.3', '4.1.3', '2.1.4']

In [22]:
def check_productsmile(smiles):#only keep smiles with carbon
    smiles_lst = smiles.split('.')
    smiles_lst = [x for x in smiles_lst if smiles_has_carbon(x)]
    return len(smiles_lst)

In [23]:
rules_product_smiles_lst = []
retrorules = pd.read_csv(mnxreac_smile_atom_mapping_rules_file_path)
# retrorules = retrorules[retrorules['MNX_ID'].str.contains('MNXR97814')]
for index,row in retrorules.iterrows():
    tmp  = row['product_smiles'].split('.')
    for i in tmp:
        if i not in rules_product_smiles_lst:
            rules_product_smiles_lst.append(i)
print('rules_product_smiles_lst',len(rules_product_smiles_lst))

rules_product_smiles_lst 11047

In [24]:
target_drug = pd.read_excel(target_drug_path)
# target_drug.rename(columns={'smiles':'drug_smiles'},inplace=True)
target_drug['drug_smiles'] = target_drug['drug_smiles'].apply(lambda x:x.replace('.Cl','').replace('.[Na+]',''))
target_drug = target_drug[target_drug['drug_smiles'].apply(lambda x:normalize_smiles(x)!=None)]

# target_drug = target_drug[target_drug['drug_name']=='digitoxin']
# target_drug = target_drug.loc[0:2,:]
# target_drug = target_drug.iloc[error_index[300:],:].reset_index(drop=True)
target_drug

,drug_name,drug_smiles,metabolite,metabolite_smiles
0,Nicardipine·HCl,CC1=C(C(C(=C(N1)C)C(=O)OCCN(C)CC2=CC=CC=C2)C3=...,Aminonicardipine,O=C(C(C(C1=CC(N)=CC=C1)C(C(OCCN(C)CC2=CC=CC=C2...
1,Risperidone,CC1=C(C(=O)N2CCCCC2=N1)CCN3CCC(CC3)C4=NOC5=C4C...,Risperidone M1,O=C1NC2=CC=C(N)C=C2C(C3=CC=CC=C3Cl)=NC1
2,Tolcapone,CC1=CC=C(C=C1)C(=O)C2=CC(=C(C(=C2)O)O)[N+](=O)...,RO-48-2485,CC1=CC=C(C=C1)C(=O)C2=CC(=C(C(=C2)O)O)NC(=O)C
3,Azathioprine,CN1C=NC(=C1SC2=NC=NC3=C2NC=N3)[N+](=O)[O-],"parent drug consumed, no observed metabolite",NaN
4,Entacapone,CCN(CC)C(=O)/C(=C/C1=CC(=C(C(=C1)O)O)[N+](=O)[...,observed,NaN
5,Exemestane,C[C@]12CC[C@H]3[C@H]([C@@H]1CCC2=O)CC(=C)C4=CC...,observed,NaN
6,Nimodipine,CC1=C(C(C(=C(N1)C)C(=O)OC(C)C)C2=CC(=CC=C2)[N+...,observed,NaN
7,Capsaicin,CC(C)/C=C/CCCCC(=O)NCC1=CC(=C(C=C1)O)OC,observed,NaN
8,Dexamethasone,C[C@@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@@]4([C@...,observed,NaN
9,Ethacrynic Acid,CCC(=C)C(=O)C1=C(C(=C(C=C1)OCC(=O)O)Cl)Cl,observed,NaN
10,Rifampin (Rifampicin),C[C@H]1/C=C/C=C(\C(=O)NC2=C(C(=C3C(=C2O)C(=C(C...,observed,NaN
11,Sulindac,CC\1=C(C2=C(/C1=C\C3=CC=C(C=C3)S(=O)C)C=CC(=C2...,Sulindac M1,CC1=C(CC(O)=O)C2=CC(F)=CC=C2/C1=C\C3=CC=C(SC)C=C3
12,Vorinostat,C1=CC=C(C=C1)NC(=O)CCCCCCC(=O)NO,observed,NaN
13,Dolasetron,C1[C@@H]2CC(C[C@H]3N2CC(=O)C1C3)OC(=O)C4=CNC5=...,"parent drug consumed, no observed metabolite",NaN
14,Mycophenolate mofetil,CC1=C2COC(=O)C2=C(C(=C1OC)C/C=C(\C)/CCC(=O)OCC...,Mycophenolic acid,CC1=C(CO2)C(C2=O)=C(O)C(C/C=C(C)/CCC(O)=O)=C1OC
15,Zidovudine (3'-Azido-3'-Deoxythymidine),CC1=CN(C(=O)NC1=O)[C@H]2C[C@@H]([C@H](O2)CO)N=...,"parent drug consumed, no observed metabolite",NaN
16,Allopurinol,C1=NNC2=C1C(=O)NC=N2,"parent drug consumed, no observed metabolite",NaN
17,Betamethasone,C[C@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@@]4([C@]...,observed,NaN
18,Bisacodyl,CC(=O)OC1=CC=C(C=C1)C(C2=CC=C(C=C2)OC(=O)C)C3=...,"parent drug consumed, no observed metabolite",NaN
19,Estradiol,C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@@H]2O)CCC4=C3...,observed,NaN
20,Famciclovir,CC(=O)OCC(CCN1C=NC2=CN=C(N=C21)N)COC(=O)C,"parent drug consumed, no observed metabolite",NaN
21,Flutamide,CC(C)C(=O)NC1=CC(=C(C=C1)[N+](=O)[O-])C(F)(F)F,observed,NaN
22,Hydrocortisone,C[C@]12CCC(=O)C=C1CC[C@@H]3[C@@H]2[C@H](C[C@]4...,20β-dihydrocortisone,C[C@]12CCC(=O)C=C1CC[C@@H]1[C@@H]2[C@@H](O)C[C...
23,Hydrocortisone Acetate,CC(=O)OCC(=O)[C@]1(CC[C@@H]2[C@@]1(C[C@@H]([C@...,20β-dihydrocortisone,C[C@]12CCC(=O)C=C1CC[C@@H]1[C@@H]2[C@@H](O)C[C...
24,Methylprednisolone,C[C@H]1C[C@H]2[C@@H]3CC[C@@]([C@]3(C[C@@H]([C@...,observed,NaN
25,Metronidazole,CC1=NC=C(N1CCO)[N+](=O)[O-],"parent drug consumed, no observed metabolite",NaN
26,Nabumetone,CC(=O)CCC1=CC2=C(C=C1)C=C(C=C2)OC,observed,NaN
27,Pantoprazole,COC1=C(C(=NC=C1)CS(=O)C2=NC3=C(N2)C=C(C=C3)OC(...,observed,NaN
28,Prednisolone,C[C@]12C[C@@H]([C@H]3[C@H]([C@@H]1CC[C@@]2(C(=...,observed,NaN
29,Progesterone,CC(=O)[C@H]1CC[C@@H]2[C@@]1(CC[C@H]3[C@H]2CCC4...,observed,NaN
30,Prednisone,C[C@]12CC(=O)[C@H]3[C@H]([C@@H]1CC[C@@]2(C(=O)...,observed,NaN
31,Spironolactone,CC(=O)S[C@@H]1CC2=CC(=O)CC[C@@]2([C@@H]3[C@@H]...,7α-thiospironolactone,O=C1CC[C@@]2(C)C(C[C@@H](S)[C@]3([H])[C@]2([H]...
32,Sulfasalazine,C1=CC=NC(=C1)NS(=O)(=O)C2=CC=C(C=C2)N=NC3=CC(=...,Sulfapyridine,C1=CC=NC(=C1)NS(=O)(=O)C2=CC=C(C=C2)N
33,Tinidazole,CCS(=O)(=O)CCN1C(=NC=C1[N+](=O)[O-])C,"parent drug consumed, no observed metabolite",NaN
34,Fluoxetine·HCl,CNCCC(C1=CC=CC=C1)OC2=CC=C(C=C2)C(F)(F)F,observed,NaN
35,Misoprostol,CCCCC(C)(C/C=C/[C@H]1[C@@H](CC(=O)[C@@H]1CCCCC...,Misoprostol acid,CCCCC(C)(C/C=C/[C@H]1[C@@H](CC(=O)[C@@H]1CCCCC...
36,Megestrol Acetate,CC1=C[C@@H]2[C@H](CC[C@]3([C@H]2CC[C@@]3(C(=O)...,observed,NaN
37,Capecitabine,CCCCCOC(=O)NC1=NC(=O)N(C=C1F)[C@H]2[C@@H]([C@@...,Degylcocapecitabine,FC1=CNC(N=C1NC(OCCCCC)=O)=O
38,Chenodiol (Chenodeoxycholic Acid),C[C@H](CCC(=O)O)[C@H]1CC[C@@H]2[C@@]1(CC[C@H]3...,observed,NaN
39,Clofazimine,CC(C)N=C1C=C2C(=NC3=CC=CC=C3N2C4=CC=C(C=C4)Cl)...,observed,NaN
40,Clonazepam,C1C(=O)NC2=C(C=C(C=C2)[N+](=O)[O-])C(=N1)C3=CC...,Clonazepam M1,NC1=CC=C(NC(CN=C2C3=CC=CC=C3Cl)=O)C2=C1
41,Cortisone Acetate,CC(=O)OCC(=O)[C@]1(CC[C@@H]2[C@@]1(CC(=O)[C@H]...,observed,NaN
42,Dantrolene·Na,C1C(=NC(=O)N1N=CC2=CC=C(O2)C3=CC=C(C=C3)[N+](=...,observed,NaN
43,Duloxetine,CNCC[C@@H](C1=CC=CS1)OC2=CC=CC3=CC=CC=C32,observed,NaN
44,Fludrocortisone Acetate,CC(=O)OCC(=O)[C@]1(CC[C@@H]2[C@@]1(C[C@@H]([C@...,observed,NaN
45,Iloperidone,CC(=O)C1=CC(=C(C=C1)OCCCN2CCC(CC2)C3=NOC4=C3C=...,observed,NaN
46,Lorazepam,C1=CC=C(C(=C1)C2=NC(C(=O)NC3=C2C=C(C=C3)Cl)O)Cl,observed,NaN
47,Nilutamide,CC1(C(=O)N(C(=O)N1)C2=CC(=C(C=C2)[N+](=O)[O-])...,observed,NaN
48,Nitisinone,C1CC(=O)C(C(=O)C1)C(=O)C2=C(C=C(C=C2)C(F)(F)F)...,observed,NaN
49,Nitrofurantoin,C1C(=O)NC(=O)N1/N=C/C2=CC=C(O2)[N+](=O)[O-],"parent drug consumed, no observed metabolite",NaN
50,Oxazepam,C1=CC=C(C=C1)C2=NC(C(=O)NC3=C2C=C(C=C3)Cl)O,observed,NaN
51,Paliperidone,CC1=C(C(=O)N2CCCC(C2=N1)O)CCN3CCC(CC3)C4=NOC5=...,observed,NaN
52,Prasugrel,CC(=O)OC1=CC2=C(S1)CCN(C2)C(C3=CC=CC=C3F)C(=O)...,observed,NaN
53,Probenecid,CCCN(CCC)S(=O)(=O)C1=CC=C(C=C1)C(=O)O,observed,NaN
54,Rifabutin,C[C@H]1/C=C/C=C(\C(=O)NC2=C(C3=C(C4=C(C(=C3O)C...,observed,NaN
55,Sulfamethoxazole,CC1=CC(=NO1)NS(=O)(=O)C2=CC=C(C=C2)N,"parent drug consumed, no observed metabolite",NaN
56,Ursodiol,C[C@H](CCC(=O)O)[C@H]1CC[C@@H]2[C@@]1(CC[C@H]3...,observed,NaN
57,Sulindac,CC\1=C(C2=C(/C1=C\C3=CC=C(C=C3)S(=O)C)C=CC(=C2...,Sulindac M2,CC1=C(CC(O)=O)C2=CC(F)=CC=C2/C1=C\C3=CC=C(S(C)...

In [25]:
# for index,row in target_drug.iterrows():
#     print('====================',row['drug_name'],'====================')
#     draw_smiles(row['drug_smiles'])
#     draw_smiles(row['product_smiles'])
# break

In [26]:
# 读取gut clean ec预测结果
with open('../../Results/AGORA2_strain_eclist_top3.pkl', 'rb') as f:
    loaded_top3 = pickle.load(f)

with open('../../Results/AGORA2_strain_eclist_top4.pkl', 'rb') as f:
    loaded_top4 = pickle.load(f)

print("读取完成！")
print(f"Top3 列表长度：{len(loaded_top3)}")
print(f"Top4 列表长度：{len(loaded_top4)}")

读取完成！
Top3 列表长度：252
Top4 列表长度：4948

## byproduct prediction

In [27]:
result_num = {'drug_name':[],
              'reaction_num':[],
              'ec4_num':[],
              'ec4_list':[],
              'ec3_num':[],
              'ec3_list':[],
            #   'success_predict':[],
            #   'success_ecnumber':[],
              }
# filter_info = {'drug_carbon':[],
#                'success_carbon':[],
#                'error_carbon':[],
#                'success_sim_score':[],
#                'error_sim_score':[],
#                }

for index,row in tqdm(target_drug.iterrows(),total=len(target_drug)):
    print(row['drug_name'])
    heterologous_met_smiles = row['drug_smiles']
    # heterologous_met_smiles = 'FC1=CNC(=O)NC1=O'
    # heterologous_met_smiles = 'N[C@@H](CC1=CC(O)=C(O)C=C1)C(O)=O'
    # heterologous_met_smiles = '[NH3+][C@@H](Cc1ccc(O)c(O)c1)C(=O)[O-]' ######## L-dopa
    heterologous_met_smiles = normalize_smiles(heterologous_met_smiles)
    # model_met = target_drug['smiles'].to_list()
    # model_met = [heterologous_met_smiles,heterologous_met_smiles,heterologous_met_smiles,'O=C([O-])CCC(=O)C(=O)[O-]']
    model_met = [heterologous_met_smiles,heterologous_met_smiles,heterologous_met_smiles,'O=C([O-])CCC(=O)C(=O)[O-]',
                 'C[S+](CC[C@@H](C(=O)[O-])N)C[C@@H]1[C@H]([C@H]([C@@H](O1)N2C=NC3=C(N=CN=C32)N)O)O',
                 'C1=NC(=C2C(=N1)N(C=N2)[C@H]3[C@@H]([C@@H]([C@H](O3)CSCC[C@@H](C(=O)O)N)O)O)N',
                 'O=C(O)[C@H]1O[C@@H](O)[C@H](O)[C@@H](O)[C@H]1O',# β-D-葡萄糖醛酸
                 'CC(=O)SCCNC(=O)CCNC(=O)[C@@H](C(C)(C)COP(=O)(O)OP(=O)(O)OC[C@@H]1[C@H]([C@H]([C@@H](O1)N2C=NC3=C(N=CN=C32)N)O)OP(=O)(O)O)O', # Acetyl-CoA
                 ]
    new_met = []

    # add heterologous_met_smiles to model_met list
    new_model_and_heterologous_met = model_met + new_met
    new_model_and_heterologous_met.append(heterologous_met_smiles)
    new_model_and_heterologous_met = [smile for smile in new_model_and_heterologous_met if '.' not in smile]
    new_model_and_heterologous_met = [smile for smile in new_model_and_heterologous_met if 'C' in smile or 'c' in smile] ###只筛第一轮
    print(len(new_model_and_heterologous_met))
    #calculate similarity
    num_processes = 100
    pool = multiprocessing.Pool(num_processes)
    retrosys_smiles_calculate_similarity = {'rules_smiles': [],
                                            'smiles_in_mets_total_smiles': [],
                                            'scores': []}


    process_rule_partial = partial(process_rule, mets_total_smiles=new_model_and_heterologous_met)
    for result in tqdm(pool.imap(process_rule_partial, rules_product_smiles_lst, chunksize=100), total=len(rules_product_smiles_lst)):
        if result[0] not in retrosys_smiles_calculate_similarity['rules_smiles']:
            retrosys_smiles_calculate_similarity['rules_smiles'].append(result[0]) 
            retrosys_smiles_calculate_similarity['smiles_in_mets_total_smiles'].append(result[1]) 
            retrosys_smiles_calculate_similarity['scores'].append(result[2]) 
    pool.close()
    pool.join()

    retrosys_smiles_calculate_similarity_pd = pd.DataFrame(retrosys_smiles_calculate_similarity)
    
##############################################
    # for index4, row4 in retrosys_smiles_calculate_similarity_pd.iterrows():
    #     if row4['rules_smiles'] not in row4['smiles_in_mets_total_smiles']:
    #         # 修改 DataFrame 中嵌套的列表
    #         retrosys_smiles_calculate_similarity_pd.at[index4, 'smiles_in_mets_total_smiles'].append(row4['rules_smiles'])
##############################################
    rxndb_list = [] 
    # newdbSmiles = []
    failedrxn = []
    num_processes =100  #  adjust the number of processes according to your needs
    pool = multiprocessing.Pool(num_processes)
    # Execute in parallel using process pool

    # Create a partial function that passes mets_total_smiles and mets_total_mol as default parameters to the process_retrorule function
    process_retrorule_partial = partial(process_retrorule, mets_total_smiles=new_model_and_heterologous_met,retrosys_smiles_calculate_similarity_pd = retrosys_smiles_calculate_similarity_pd,heterologous_met_smiles = heterologous_met_smiles)

    # Using the process pool to execute in parallel, the chunksize parameter is placed inside the imap function.
    for result in tqdm(pool.imap(process_retrorule_partial, retrorules.iterrows(), chunksize=100), total=len(retrorules)):
        # if result == ([], [], []):
        #     pass
        # else:
        #     print(result)
        if result[0] :  #  check if the result is not empty
            rxndb_list.extend(result[0]) 
        # if result[1] is not None:
        #     newdbSmiles.extend(result[1])
        if result[1]:
            failedrxn.extend(result[1])  

    pool.close()
    pool.join()

    rxndb = {}
    for i, rxn_dict in enumerate(rxndb_list):
        # generate a unique key for each reaction, for example "rxn0"，"rxn1"，"rxn2"，...
        key = f'rxn{i+1}'
        # merge to the dictionary
        rxndb[key] = rxn_dict
    # with open(rxndb_path, 'w') as json_file:
    #     json.dump(rxndb, json_file)

    # with open(rxndb_path, 'r') as f:
    #     rxndb = json.load(f)
    print('rxndb num',len(rxndb))
    print('failedrxn num',len(failedrxn))

    ecnumber_list = []
    for _,x in rxndb.items():
        ec_list = x['EC number'].split(';')
        ec_list = process_ec_list(ec_list,3)
        ecnumber_list += ec_list

    ecnumber_list = list(set(ecnumber_list))   
    result_df = {'ID':[],
            'reactant_smile':[],
            'productsmile':[],
            'rxn_smiles_basic':[],
            'templateID':[],
            'EC number':[],}

    for k,v in rxndb.items():
        result_df['ID'].append(k)
        result_df['reactant_smile'].append(v['reactant_smile'])
        result_df['productsmile'].append(v['productsmile'])
        result_df['rxn_smiles_basic'].append(v['rxn_smiles_basic'])
        result_df['templateID'].append(v['templateID'])
        result_df['EC number'].append(v['EC number'])

    result_df = pd.DataFrame({'ID': result_df['ID'],
                        'reactant_smile': result_df['reactant_smile'],
                        'productsmile': result_df['productsmile'],
                        'rxn_smiles_basic': result_df['rxn_smiles_basic'],
                        'templateID': result_df['templateID'],
                        'EC number': result_df['EC number'],
                        })

    result_df.drop_duplicates(subset=['reactant_smile', 'productsmile'], inplace=True)
    result_df.reset_index(drop=True, inplace=True)

    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.OO']
    result_df = result_df[result_df['productsmile']!='OO.'+ heterologous_met_smiles]
    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.O=C=O']
    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.O=S([O-])[O-]']
    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.[SH-]']
    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.O=P([O-])([O-])OP(=O)([O-])O']
    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.II']
    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.[NH4+]']
    result_df = result_df[result_df['productsmile']!=heterologous_met_smiles+'.[Br-]']

    result_df['productsmile_num'] = result_df['productsmile'].apply(lambda x: check_productsmile(x))
    result_df = result_df[result_df['productsmile_num']==1]


    error_ec = ['1.2.1', '1.14.13', '1.14.14', '1.1.1', '3.1.3' ,'1.21.1','1.22.1','1.1.1','3.1.6'] #1.10.3#3.1.6
    error_ec = []
    # 过滤 DataFrame，使得 "EC number" 列中的每个 EC 号都不属于 error_ec
    result_df['EC number'] = result_df['EC number'].apply(lambda x:x.split(';'))
    result_df = result_df[~result_df['EC number'].apply(lambda ec_list: all('.'.join(x.split('.')[0:3]) in error_ec for x in ec_list))]
    result_df['EC number'] = result_df['EC number'].apply(lambda x:';'.join(x))
    
    # 过滤 DataFrame，使得 "EC number" 列中的有 EC 号都属于 gut_ec
    # gut_ec_list_top3 = loaded_top3
    # result_df['EC number'] = result_df['EC number'].apply(lambda x:x.split(';'))
    # result_df = result_df[result_df['EC number'].apply(lambda ec_list: any('.'.join(x.split('.')[0:3]) in gut_ec_list_top3 for x in ec_list))]
    # result_df['EC number'] = result_df['EC number'].apply(lambda x:';'.join(x))

    try:
        res = result_df['reactant_smile'].to_list()
        ec_lst = []
        for k,v in rxndb.items():
            if v['reactant_smile'] in res:
                ec_lst.append(v['EC number'])
    except:
        ec_lst = []
        pass
    # print(row['name'],len(result_df))
    # print(row['name'],ec_lst)
    print('result_df',len(result_df))
    print(ec_lst)
    ec_lst_4 = process_ec_list(ec_lst,4)
    ec_lst_3 = process_ec_list(ec_lst,3)
    print(len(ec_lst_3))
    print(len(ec_lst_4))
    
    result_num['drug_name'].append(row['drug_name'])
    result_num['reaction_num'].append(len(result_df))
    result_num['ec4_num'].append(len(ec_lst_4))
    result_num['ec4_list'].append(str(ec_lst_4))
    result_num['ec3_num'].append(len(ec_lst_3))
    result_num['ec3_list'].append(str(ec_lst_3))
    
    # success_predict = 0
    # success_ecnumber = []
    # success_ID = []
    # if row['product_smiles'] != 'unknown' and row['drug_name'] != 'Lactulose':
    #     target_smiles = row['product_smiles'].split('.')[0]
    #     for index2,row2 in result_df.iterrows():
    #         smiles_list = row2['reactant_smile'].split('.')
    #         if any(compare_smiles_inchikey(smiles,target_smiles) for smiles in smiles_list):
    #             success_predict =1
    #             success_ID.append(row2['ID'])
    #             tmp_ec_lst = row2['EC number'].split(';')
    #             success_ecnumber+=process_ec_list(tmp_ec_lst,3)
    
    # result_num['success_predict'].append(success_predict)
    # result_num['success_ecnumber'].append(str(list(set(success_ecnumber))))
    
    
    # drug_carbon = calculate_carbon_count(heterologous_met_smiles)
    # success_sim_score = []
    # success_carbon = []
    # error_carbon = []
    # error_sim_score = []
    # # for tmpid,tmp_result in rxndb.items():
    # #     if tmpid in result_df['ID']:
    # for index3,row3 in result_df.iterrows():
    #     if row3['ID'] in success_ID:
    #         success_sim_score.append(min(rxndb[row3['ID']]['similarity']))
    #         success_carbon.append(max(calculate_carbon_count(tmp_smiles) for tmp_smiles in rxndb[row3['ID']]['templateSubstrate']))
    #     else:
    #         error_sim_score.append(min(rxndb[row3['ID']]['similarity']))
    #         error_carbon.append(max(calculate_carbon_count(tmp_smiles) for tmp_smiles in rxndb[row3['ID']]['templateSubstrate']))

    # filter_info['drug_carbon'].append(drug_carbon)
    # filter_info['success_carbon'].append(success_carbon)
    # filter_info['error_carbon'].append(error_carbon)
    # filter_info['success_sim_score'].append(success_sim_score)
    # filter_info['error_sim_score'].append(error_sim_score)
    
    # # 保存结果
    # # 保存 drug_degration_ec 到 JSON 文件
    # drug_degration_ec_path = os.path.join(output_dir, 'drug_degration_ec.json')
    # with open(drug_degration_ec_path, 'w') as json_file:
    #     json.dump(drug_degration_ec, json_file, indent=4)

    # # 保存 result_df 到 CSV 文件
    # result_df_path = os.path.join(output_dir, 'result_df.csv')
    # # 保存结果时，使用追加模式（mode='a'）
    # result_df.to_csv(result_df_path, index=False, mode='a', header=not os.path.exists(result_df_path))

  0%|          | 0/58 [00:00<?, ?it/s]

Nicardipine·HCl
9

100%|██████████| 11047/11047 [00:08<00:00, 1380.58it/s]
100%|██████████| 27873/27873 [00:18<00:00, 1494.11it/s]
  2%|▏         | 1/58 [00:31<29:27, 31.00s/it]

rxndb num 849
failedrxn num 0
result_df 58
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.1.5', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '3.1.1.70', '3.1.1.70', '1.7.1.9', '1.7.1.9', '1.7.1.-;1.7.1.16', '3.1.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.12.23', '1.14.12.23', '1.-.-.-;1.7.1', '1.7.1.-', '1.-.-.-', '1.12.99.6;1.2.7.1;1.2.7.4;1.2.99.2', '1.-.-.-', '1.7.1.-', '1.7.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.14.12.-;1.14.12.24', '1.14.12.-;1.14.12.24', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '3.1.1.95', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.3.2', '6.3.2', '3.1.1;3.1.1.1;3.1.1.3', '3.1.1;3.1.1.1;3.1.1.3', '3.1.1', '3.1.1', '3.1.1', '3.1.1', '3.1.1.26', '3.1.1.26', '3.1.1.4', '3.1.1.4', '3.1.1.13', '3.1.1.13', '1.14.13', '1.14.13', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.24', '1.14.12.24', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.7.1.16', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.7.1', '1.7.1.16', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '3.1.1.1;3.1.1.13;3.1.1.3', '3.1.1.1;3.1.1.13;3.1.1.3', '3.1.1.1;3.1.1.3', '3.1.1.1;3.1.1.3', '3.1.1.1', '3.1.1.1', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.4.21;3.4.21.104;3.4.21.42', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '3.4.16.5;3.4.21;3.4.21.62', '3.4.16.5;3.4.21;3.4.21.62', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.25', '1.14.13.25', '1.14.13.25', '1.14.13.25', '1.14.13.25', '1.14.13.25', '1.14.13.25', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.18', '1.14.-.-', '1.14.-.-', '3.2.1.35', '3.2.1.35', '3.2.1.35', '2.3.1.-', '2.3.1.-', '3.1.1', '3.1.1', '3.1.1.5', '3.1.1.5', '3.1.1.5', '3.1.1.10', '3.1.1.10', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '2.3.1.-', '2.3.1.-', '1.14.14.22;1.14.99.46', '3.1.1.116', '3.1.1.116', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.2.1.14', '3.4.19.7', '3.4.19.7', '3.4.19.7', '3.2.1.-', '3.2.1.-', '3.2.1.-', '3.1.-.-', '3.1.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.15.5', '1.14.15.5', '6.2.1.3', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '3.1.1.5', '3.1.1.5', '1.7.1.-', '1.7.1.-', '3.2.1.143', '3.2.1.143', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.122', '1.14.13.122', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.7.1.M3']
27
75
Risperidone
9

100%|██████████| 11047/11047 [00:08<00:00, 1230.01it/s]
100%|██████████| 27873/27873 [00:18<00:00, 1493.72it/s]
  3%|▎         | 2/58 [01:03<29:39, 31.77s/it]

rxndb num 256
failedrxn num 0
result_df 24
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13;1.14.14', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.176', '1.14.13', '1.14.13', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '2.6.1.114', '1.14.14', '1.14.14', '1.14.14']
7
30
Tolcapone
9

100%|██████████| 11047/11047 [00:07<00:00, 1523.81it/s]
100%|██████████| 27873/27873 [00:18<00:00, 1483.04it/s]
  5%|▌         | 3/58 [01:33<28:38, 31.25s/it]

rxndb num 1688
failedrxn num 0
result_df 89
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.7', '1.14.13.7', '1.14.13.31', '1.14.13.31', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.6', '1.14.13.6', '1.14.13.6', '1.14.13.6', '1.14.13.6', '1.14.13.6', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.20', '1.14.13.20', '1.7.1.9', '1.7.1.9', '1.14.13.219;1.14.13.7', '1.14.13.219;1.14.13.7', '1.7.1.-;1.7.1.16', '1.14.13.-;1.14.13.20;1.14.13.7', '1.14.13.-;1.14.13.20;1.14.13.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.180', '1.14.13.180', '1.14.13.180', '1.14.13.-;1.6.5.2', '1.14.13.-;1.6.5.2', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.-.-.-;1.7.1', '1.7.1.-', '1.-.-.-', '1.12.99.6;1.2.7.1;1.2.7.4;1.2.99.2', '1.-.-.-', '1.7.1.-', '1.7.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.3.1.29', '1.3.1.29', '1.3.-.-', '1.3.-.-', '1.3.-.-', '1.3.-.-', '1.6.5.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.14.12.-;1.14.12.24', '1.14.12.-;1.14.12.24', '1.14.12.-;1.14.12.24', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.13.244;1.14.13.M20', '1.14.13.244;1.14.13.M20', '1.13.12.20', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.189', '1.14.13.189', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.24', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.7.1.16', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.7.1', '1.7.1.16', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.20', '1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.6.1', '3.1.6.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.13', '1.14.13', '1.14.18.1', '1.14.18.1', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.25', '1.14.13.25', '1.14.13.25', '1.14.13.25', '3.1.3.48', '3.1.3.48', '3.1.3.2;3.1.3.48;3.1.3.76', '3.1.3.2;3.1.3.48;3.1.3.76', '3.1.3.36;3.1.3.48', '3.1.3.36;3.1.3.48', '3.1.3.48', '3.1.3.48', '3.1.3.48', '3.1.3.48', '3.1.3.2', '3.1.3.2', '1.1.3.38', '1.14.13.31', '1.14.13.31', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.97.1.2', '1.97.1.2', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '4.1.1.-', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.82', '3.2.1.15;3.2.1.82', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.2.1.76', '3.2.1.76', '3.2.1.31', '3.2.1.31', '3.2.1.35', '3.2.1.35', '1.14.13', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.1', '1.14.14.1', '3.1.3;3.1.3.2;3.1.3.48', '3.1.3;3.1.3.2;3.1.3.48', '1.14.13.12', '1.14.13.12', '1.14.13.11;1.14.14.91', '1.14.13.11;1.14.14.91', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.7', '1.14.13.7', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.14.22;1.14.99.46', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.14.1', '1.14.14.1', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '1.14.13.-', '1.14.12.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.15', '3.2.1.15', '4.2.2.2', '4.2.2.2', '1.14.13.-', '1.14.13.-', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.7.1.-', '1.7.1.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '4.2.1.67', '4.2.1.67', '1.14.13.236', '1.14.13.236', '4.2.1.40', '4.2.1.40', '4.2.1.90', '4.2.1.90', '1.14.13.-', '1.14.13.-', '1.14.14.20', '1.14.14.20', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.27', '1.14.14.27', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '2.6.1.114', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.7.1.M3', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127']
35
116
Azathioprine
9

100%|██████████| 11047/11047 [00:07<00:00, 1433.98it/s]
100%|██████████| 27873/27873 [00:16<00:00, 1652.36it/s]
  7%|▋         | 4/58 [02:03<27:23, 30.43s/it]

rxndb num 141
failedrxn num 0
result_df 15
['1.7.1.9', '1.7.1.9', '1.7.1.-;1.7.1.16', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.-.-.-;1.7.1', '1.7.1.-', '1.-.-.-', '1.12.99.6;1.2.7.1;1.2.7.4;1.2.99.2', '1.-.-.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.14.13.-', '1.14.13', '1.17.1.4', '1.17.1.4', '1.17.1.4', '1.17.1.4', '1.7.1.16', '1.7.1', '1.7.1.16', '3.8.1.7', '1.17.5.-;1.17.5.2', '1.14.14.22;1.14.99.46', '1.14.14.1', '1.7.1.-', '1.7.1.-', '1.1.1.205', '1.7.1.M3']
12
21
Entacapone
9

100%|██████████| 11047/11047 [00:06<00:00, 1599.83it/s]
100%|██████████| 27873/27873 [00:18<00:00, 1538.13it/s]
  9%|▊         | 5/58 [02:32<26:37, 30.14s/it]

rxndb num 949
failedrxn num 0
result_df 42
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.6', '1.14.13.6', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.4', '1.14.13.4', '1.7.1.9', '1.7.1.9', '1.14.13.-', '1.14.13.-', '1.7.1.-;1.7.1.16', '1.14.13.-', '1.14.13.-', '1.14.12.23', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.-.-.-;1.7.1', '1.7.1.-', '1.-.-.-', '1.12.99.6;1.2.7.1;1.2.7.4;1.2.99.2', '1.-.-.-', '1.7.1.-', '1.7.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.14.12.-;1.14.12.24', '1.14.12.-;1.14.12.24', '1.14.12.-;1.14.12.24', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13', '1.14.13', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.24', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.12.23', '1.7.1.16', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.7.1', '1.7.1.16', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.18.1', '1.14.18.1', '1.14.13.25', '1.14.13.25', '3.1.3.48', '3.1.3.48', '3.1.3.48', '3.1.3.48', '1.14.18.1', '1.14.18.1', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.36', '1.14.13.36', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '1.14.-.-', '3.2.1.35', '3.2.1.35', '1.14.14.91', '1.14.14.91', '3.1.3;3.1.3.2;3.1.3.48', '3.1.3;3.1.3.2;3.1.3.48', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '1.14.14.22;1.14.99.46', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '1.14.12.-', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.15.5', '1.14.13.-', '1.14.13.-', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.7.1.-', '1.7.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.8', '1.14.14.8', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13.-', '1.14.13.-', '1.7.1.M3', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127']
23
73
Exemestane
9

100%|██████████| 11047/11047 [00:09<00:00, 1108.97it/s]
100%|██████████| 27873/27873 [00:18<00:00, 1532.04it/s]
 10%|█         | 6/58 [03:05<26:58, 31.12s/it]

rxndb num 2091
failedrxn num 0
result_df 99

100%|██████████| 11047/11047 [00:08<00:00, 1338.81it/s]
100%|██████████| 27873/27873 [00:16<00:00, 1721.33it/s]
 12%|█▏        | 7/58 [03:35<25:55, 30.51s/it]

rxndb num 673
failedrxn num 0
result_df 53
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.1.5', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '3.1.1.70', '3.1.1.70', '3.1.1.51', '3.1.1.51', '1.7.1.9', '1.7.1.9', '1.7.1.-;1.7.1.16', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.12.23', '1.14.12.23', '1.-.-.-;1.7.1', '1.7.1.-', '1.-.-.-', '1.12.99.6;1.2.7.1;1.2.7.4;1.2.99.2', '1.-.-.-', '1.7.1.-', '1.7.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.14.12.-;1.14.12.24', '1.14.12.-;1.14.12.24', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.14.13.-;1.14.13.171', '1.1.1.363;1.1.1.388', '1.1.1.363;1.1.1.388', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '6.3.2', '6.3.2', '3.1.1;3.1.1.1;3.1.1.3', '3.1.1;3.1.1.1;3.1.1.3', '3.1.1', '3.1.1', '3.1.1', '3.1.1.26', '3.1.1.26', '3.1.1.4', '3.1.1.4', '3.1.1.13', '3.1.1.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.24', '1.14.12.24', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '1.1.1.-', '1.1.1.-', '1.14.12.23', '1.14.12.23', '1.7.1.16', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.7.1', '1.7.1.16', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.1.1;3.1.1.13;3.1.1.3', '3.1.1.1;3.1.1.13;3.1.1.3', '3.1.1.1;3.1.1.3', '3.1.1.1;3.1.1.3', '3.1.1.1', '3.1.1.1', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.13.25', '1.14.13.25', '1.14.13.25', '1.14.13.25', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.18', '1.14.-.-', '1.14.-.-', '3.2.1.35', '3.2.1.35', '3.2.1.35', '2.3.1.-', '2.3.1.-', '3.1.1', '3.1.1', '3.1.1.5', '3.1.1.5', '3.1.1.5', '3.1.1.5', '1.14.13;1.14.14.1', '1.14.13;1.14.14.1', '3.1.1.10', '3.1.1.10', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '2.3.1.-', '2.3.1.-', '1.1.1.363;1.1.1.388;1.1.1.47;1.1.1.49', '1.1.1.363;1.1.1.388;1.1.1.47;1.1.1.49', '1.14.14.22;1.14.99.46', '3.1.1.116', '3.1.1.116', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.2.1.14', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.4.19.7', '3.4.19.7', '3.4.19.7', '3.2.1.-', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.-.-', '3.1.-.-', '3.1.-.-', '3.1.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.15.5', '1.14.15.5', '1.14.15.5', '6.2.1.3', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '3.1.1.5', '3.1.1.5', '1.7.1.-', '1.7.1.-', '1.14.13.194', '1.14.13.194', '1.14.13.194', '3.1.1.101', '3.1.1.101', '3.1.1.101', '3.2.1.143', '3.2.1.143', '3.2.1.143', '1.1.1.363;1.1.1.49', '1.1.1.363;1.1.1.49', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.122', '1.14.13.122', '1.1.1.363;1.1.1.47;1.1.1.49', '1.1.1.363;1.1.1.47;1.1.1.49', '1.1.1.49', '1.1.1.49', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.7.1.M3']
27
84
Capsaicin
9

100%|██████████| 11047/11047 [00:06<00:00, 1580.24it/s]
100%|██████████| 27873/27873 [00:18<00:00, 1508.31it/s]
 14%|█▍        | 8/58 [04:04<25:15, 30.30s/it]

rxndb num 3032
failedrxn num 0
result_df 76
['3.5.1.94', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1;1.14.14.25;1.14.14.55;1.14.14.57', '1.14.13.100', '1.14.15.6', '6.3.2.1', '3.5.1.92', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.6.1;3.1.6.2', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.7', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.5.1.22', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '6.3.2.23', '1.14.13.6', '6.3.1.2;6.3.1.6', '3.5.1.65', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '6.3.2.20', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.17.1.1', '1.17.1.1', '1.14.14.-;1.14.14.1', '1.14.13.7', '1.14.13.7', '1.3.1.5', '1.3.1.5', '1.14.13.44', '3.5.1.24;3.5.1.74', '3.5.1.24', '1.3.1.48', '1.3.1.48', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.219;1.14.13.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.6.5.2', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.100;1.14.14.29', '6.3.2.36', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.13.244;1.14.13.M20', '1.14.13.-;1.14.13.161', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '3.5.1.-', '6.3.2.44', '1.14.13;1.14.13.-', '6.3.4.24', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.-;1.14.13.220', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13.228', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.3.1.114', '1.3.1.34', '6.3.2.18', '1.14.13.-;1.14.13.236', '6.3.2;6.3.2.-', '1.3.3.6', '1.14.13', '6.3.2', '6.3.2', '6.3.2', '3.4.11.25', '1.14.13;1.14.13.-', '1.3.1.93', '1.3.1.93', '6.3.2.59', '6.3.2.59', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.14.13', '1.3.1.93', '1.3.1.93', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.4.13', '6.3.2', '1.3.1.93', '1.3.1.93', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1.114', '1.3.1', '1.3.1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2', '3.4', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.20', '1.14.13;1.14.13.20', '3.5.1.115', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.3.3.6', '3.5.1.23', '3.5.1.23', '3.5.1.23', '1.14.14.1', '1.3.1.48', '1.3.1.48', '1.3.1.48', '3.5.1.23', '3.5.1.23', '3.5.1.23', '1.14.15.15', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '3.5.1.23', '1.14.14.91', '1.14.14.91', '3.5.1.23', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.11.1.7;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '3.2.1.78', '3.1.3.2', '1.14.14.1', '6.3.2.18', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.13.36', '1.14.13.36', '1.14.13.36', '3.4.11.5', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.55', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '6.3.2.17', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.145;3.2.1.23', '3.2.1.110', '1.14.13.-;1.14.13.129', '3.2.1.35', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.234', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '3.2.1.137;3.2.1.78', '1.3.1;1.3.1.-', '1.3.1;1.3.1.-', '1.3.1;1.3.1.-', '1.3.1;1.3.1.-', '2.4.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-;1.14.13.129', '6.3.1.11', '3.5.1.-;3.5.1.78', '6.3.1.8;6.3.1.9', '1.14.13.15;1.14.15.15', '1.14.13.15;1.14.15.15', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.5.1.4;3.5.1.99', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3;3.1.3.2;3.1.3.48', '1.14.14.23', '1.14.13.17', '1.14.13.46', '1.14.13.46', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.5.1.24;3.5.1.74', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.-;1.14.13.243', '1.14.13.7', '6.3.1.9', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.19.68;1.14.21.5', '1.14.21.1', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.3.1.104;1.3.1.38;1.3.1.8', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.77', '1.14.13.76', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.3.1.104;1.3.1.38;1.3.1.44;1.3.1.8', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.13.-', '1.14.13.-', '1.14.13', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '3.5.1.-', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.17', '6.3.1.13', '1.14.13.-;1.14.13.146', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1;1.3.1.44', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.3.1.-;1.3.1.72;1.3.1.M20', '1.3.1.-;1.3.1.71', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.19.41;1.3.1.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.3.99.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.88', '1.14.13.127', '1.3.99.3', '1.1.1;1.3.99.3', '1.3.1.9', '6.3.1.10', '6.3.1.10', '3.5.1.90', '3.5.1.90', '1.3.1.-', '6.3.2.56;6.3.2.ad', '1.3.1.42', '3.5.1.60;3.5.1.99', '3.5.1.60', '3.5.1.60;3.5.1.99', '3.5.1.99', '3.5.1.99', '1.14.13.-', '3.5.1.60', '1.14.14.1', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.4', '3.2.1.14', '3.2.1.37', '3.2.1.37', '3.2.1.55', '3.2.1.55', '3.2.1.3;3.2.1.58;3.2.1.59', '3.2.1.4', '3.2.1.4', '1.14.13.129', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.129', '1.14.-.-;1.14.13.-', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.141', '1.14.13.99', '3.2.1.116', '3.2.1.137', '3.2.1.154', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.4.15.6', '3.4.19.9', '3.4.19.5', '3.4.19.7', '3.2.1.1', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.21.8', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.188', '1.10.3.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '3.2.1.2', '1.14.99.45', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.13.-', '1.14.13.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.99.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.70', '1.14.13.70', '1.14.13.72', '1.14.15.5', '1.14.13.129', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '3.2.1.137', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.88', '1.14.13.159', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.186', '1.14.13.194', '6.3.2;6.3.2.-', '3.1.1.101', '1.3.1.114', '6.3.2', '3.2.1.143', '6.3.2', '6.3.2', '4.2.1.140;4.2.1.39', '4.2.1.6', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '1.3.3.6', '6.3.2', '6.3.2', '1.14.14.1', '1.14.13.100;1.14.13.17;1.14.13.60', '6.3.2.37', '1.3.1.93', '1.14.13.15', '1.14.13.99', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.3.3.6', '1.3.1.104;1.3.1.38;1.3.1.8', '6.3.1.10', '1.3.99.-', '1.3.99.-', '1.3.99.-', '1.3.99.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.190', '1.14.14.20', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13;1.14.14.1', '1.17.99.5', '1.17.99.5', '1.3.3.6;1.3.8.1;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.3.3.6', '1.3.3.6', '1.14.14.8', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.27', '1.3.1.10;1.3.1.38;1.3.1.8', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '6.3.2.58', '6.3.2.58', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.5.1.115', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.3.1.74', '1.1.1;1.1.1.206', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '3.5.1.46', '1.3.1.71', '1.14.13.159']
45
246
Dexamethasone
9

100%|██████████| 11047/11047 [00:09<00:00, 1130.12it/s]
100%|██████████| 27873/27873 [00:17<00:00, 1554.83it/s]
 16%|█▌        | 9/58 [04:37<25:17, 30.98s/it]

rxndb num 4405
failedrxn num 0
result_df 123

100%|██████████| 11047/11047 [00:07<00:00, 1522.04it/s]
100%|██████████| 27873/27873 [00:16<00:00, 1673.46it/s]
 17%|█▋        | 10/58 [05:06<24:17, 30.36s/it]

rxndb num 919
failedrxn num 0
result_df 55
['3.1.3.69', '3.1.3.74', '1.14.13.9', '1.14.13.9', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1;1.14.14.25;1.14.14.55;1.14.14.57', '1.14.13.100', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.27', '3.1.3.74', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.6.2', '3.1.6.2', '3.1.6.2', '1.14.18.1', '1.14.18.1', '3.8.1.6', '3.8.1.6', '3.1.3.2;3.1.3.29;3.1.3.38', '1.1.1.118;1.1.1.47', '1.1.1.119;1.1.1.47', '3.1.3.22;3.1.3.23', '1.14.14.1', '1.14.14.1', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.6', '1.14.13.6', '3.7.1.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.219', '1.14.13.4', '1.14.13.4', '3.1.6.9', '3.1.6.10', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.1.1.219', '1.14.13.19', '1.14.13.19', '1.1.1.173;1.1.1.378', '1.14.13.44', '1.14.13.44', '1.14.13.20', '1.14.13.20', '1.14.-.-', '1.14.-.-', '3.1.3.14', '1.1.1.234', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.20;1.14.13.7', '1.14.13.-;1.14.13.20;1.14.13.7', '1.14.13.-', '1.14.13.-', '3.1.3.69', '1.14.13.-', '1.14.13.-', '1.1.1.234', '1.1.1.362', '1.14.13.180', '1.14.13.181', '1.14.13.-;1.6.5.2', '1.14.13.-;1.6.5.2', '1.14.13.50', '1.14.13.50', '1.14.-.-', '1.14.-.-', '3.1.3.76', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.1.1.219', '1.1.1.219', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.2.1.5', '1.14.13.-', '1.14.13.-', '3.1.3.-;3.1.3.88', '1.14.13.100;1.14.14.29', '3.1.3.79', '1.14.14.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '3.1.3.80', '3.1.3.85', '3.1.3.83', '1.1.1.349', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.1.1.203', '1.1.1.203', '1.14.13;1.14.13.-', '1.1.1.363;1.1.1.388', '1.1.1.390', '3.1.3.101', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '3.1.3.103', '1.14.13.228', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.1.1.116', '1.1.1.359;1.1.1.376;1.1.1.46', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '3.1.3', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '1.14.13.-;1.14.13.7', '3.1.3.25', '3.1.3.25', '3.1.3.-', '1.1.1.203', '3.1.3;3.1.3.-', '1.14.13', '3.1.6;3.1.6.-', '1.14.13.44', '1.14.13.44', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1', '1.14.13', '1.14.13', '3.1.3', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.50', '1.1.1.362', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.1.1.-;1.1.1.377;1.1.1.378', '3.1.3.4', '3.1.3.4', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.1;1.2.1.-', '1.14.19', '1.14.19', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.2.1', '3.1.3', '1.1.1.348', '1.1.1.348', '1.1.1.-', '1.1.1', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.20', '1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '3.1.3;3.1.3.-;3.1.3.104;3.1.3.2;3.1.3.29', '3.1.3', '3.1.3;3.1.3.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.6.14', '3.1.3.29', '3.1.3.29', '1.2.1.22;1.2.1.3', '1.1.1.179;1.3.1.20', '1.1.1.179;1.3.1.20', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.91', '1.14.14.91', '1.14.18.1', '1.14.18.1', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3', '3.1.3', '1.14.14.55', '1.14.14.55', '1.1.1.121', '1.1.1.47', '3.1.3', '3.8.1.6', '3.8.1.6', '3.8.1.6', '3.8.1.6', '3.1.6.3', '1.1.1.122', '3.1.3.68', '1.14.18.1', '1.14.18.1', '1.14.12.9', '1.14.12.9', '1.14.15.4', '1.14.15.4', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.36', '1.14.13.36', '1.1.1.-', '1.14.13.-', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.55', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.82', '3.2.1.15;3.2.1.82', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '3.2.1.65', '3.1.1.75', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.145;3.2.1.23', '3.2.1.76', '3.2.1.76', '3.2.1.31', '3.2.1.31', '3.2.1.35', '3.2.1.35', '1.14.13.234', '1.1.1.246;1.1.1.348', '1.1.1.219', '1.14.14.91', '1.14.14.91', '3.2.1.137;3.2.1.78', '3.1.3.29', '2.4.1.-', '3.1.3.23;3.1.3.29;3.1.3.9', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '3.1.3.27', '1.14.14.1', '1.14.14.1', '3.1.3.24', '3.1.3.12', '1.14.14.23', '1.14.13.17', '3.1.3.29', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.3.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '1.1.1.113', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.7', '1.14.13.7', '1.1.1.186', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.14.13.50', '1.14.13.50', '3.1.3.63', '3.1.3.63', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '3.1.3.70', '1.14.13.74', '1.14.13.74', '1.14.13.77', '1.14.13.76', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.1.1.186', '1.14.13.94', '1.14.13.94', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.240', '1.14.13.240', '1.14.13.103', '1.14.13.103', '1.1.1.107;1.1.1.122', '1.14.13.17', '1.14.13.147', '1.14.13.147', '1.1.1.219', '3.1.3', '1.14.14.149', '1.14.14.149', '1.14.14.149', '3.1.3.25', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.89', '1.14.13.89', '1.3.1.-;1.3.1.72;1.3.1.M20', '1.3.1.-;1.3.1.72;1.3.1.M20', '1.3.1.-;1.3.1.71', '1.3.1.-;1.3.1.71', '1.14.13.88', '1.14.13.88', '3.1.3.45', '1.14.13.88', '1.14.13.88', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '3.1.3', '3.1.3.68', '1.14.13.127', '1.14.13.127', '1.1.1.363;1.1.1.388;1.1.1.47;1.1.1.49', '3.1.3.M8', '3.1.3.106;3.1.3.76', '1.1.1.376', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '1.14.13.-', '1.14.19.55', '1.14.19.55', '1.1.1.420', '1.14.13.9', '1.14.13.9', '3.1.3.58;3.1.3.9', '3.1.6.3', '1.1.1.120', '3.2.1.14', '3.2.1.14', '1.1.1.121;1.1.1.175', '1.1.1.121', '1.1.1.179', '1.1.1.179', '3.2.1.37', '3.2.1.37', '1.1.1.46', '1.1.1.46', '3.2.1.55', '3.2.1.55', '3.2.1.3;3.2.1.58;3.2.1.59', '3.1.3.29', '3.2.1.4', '3.2.1.4', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.1.1.121', '1.14.-.-;1.14.13.-', '1.14.13.126', '1.14.13.126', '1.14.13.99', '3.1.1.75', '3.2.1.116', '3.2.1.137', '3.2.1.137', '3.2.1.154', '3.2.1.154', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.2.1.1', '1.14.14.-', '1.14.14.-', '1.14.13.89', '1.14.13.89', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.2', '1.14.99.45', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.13.174', '1.-.-.-', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.-', '1.14.13.-', '1.14.15.5', '3.2.1.15', '3.2.1.15', '4.2.2.2', '4.2.2.2', '1.14.13.-', '1.14.13.-', '3.2.1.137', '1.1.1.117', '1.1.1.117', '1.1.1.117', '1.1.1.117', '1.14.13.103', '1.14.13.103', '1.14.13.94', '1.14.13.94', '3.1.3.27', '1.1.1.46', '1.1.1.46', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.186', '1.14.13.194', '3.1.1.101', '3.1.1.101', '3.1.3', '3.1.3', '1.14.13.236', '1.14.13.236', '4.2.1.140;4.2.1.39', '4.2.1.140;4.2.1.39', '4.2.1.6', '4.2.1.6', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.106', '1.14.19.55', '1.14.19.55', '3.1.3', '3.1.3.-;3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '1.14.14.1', '1.14.13.100;1.14.13.17;1.14.13.60', '3.2.1.23', '3.1.3.25', '1.14.13.99', '1.14.13.98', '1.14.13.98', '3.1.3.2;3.1.3.31;3.1.3.6', '1.1.1.363;1.1.1.49', '3.1.3.82', '3.1.3.29;3.1.3.50', '3.1.3.50', '1.14.13.-', '1.14.13.-', '1.3.1', '1.3.1.-', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.1.1.118', '1.1.1.120;1.1.1.179;1.1.1.359;1.1.1.360;1.1.1.47;1.1.1.48;1.3.1.20', '1.1.1.120', '3.1.3.58;3.1.3.9', '1.1.1.119', '1.14.13.97', '1.14.13.97', '1.1.1.121;1.1.1.359;1.1.1.47;1.1.1.48', '1.1.1.121', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.1.1.363;1.1.1.47;1.1.1.49', '1.1.1.49', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '1.14.13.-', '1.14.13.-', '1.2.1', '1.11.2.6', '1.11.2.6', '1.1.1.424', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '4.2.3;4.2.3.1', '3.1.3.-;3.1.3.104']
33
249
Rifampin (Rifampicin)
9

100%|██████████| 11047/11047 [00:10<00:00, 1095.18it/s]
100%|██████████| 27873/27873 [00:20<00:00, 1389.49it/s]

rxndb num 3280
failedrxn num 0

 19%|█▉        | 11/58 [05:41<24:59, 31.91s/it]

result_df 146

100%|██████████| 11047/11047 [00:06<00:00, 1604.44it/s]
100%|██████████| 27873/27873 [00:15<00:00, 1761.78it/s]
 21%|██        | 12/58 [06:10<23:42, 30.92s/it]

rxndb num 340
failedrxn num 0
result_df 22
['1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1;1.14.14.25;1.14.14.55;1.14.14.57', '1.14.13.100', '3.1.6.2', '3.1.6.2', '3.1.6.2', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.100;1.14.14.29', '1.1.1.390', '3.1.6;3.1.6.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M8', '1.1.1.-', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.14.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.8;1.14.13.84', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3', '1.14.14.55', '1.14.14.55', '1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.13.234', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.14.23', '1.14.13.17', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.79', '1.14.13.79', '1.14.13.94', '1.14.13.94', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.17', '1.14.13.147', '1.14.13.147', '3.1.3', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.246', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.99', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.70', '1.14.13.70', '1.14.13.72', '1.14.15.5', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.94', '1.14.13.94', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.194', '1.14.14.1', '1.14.13.100;1.14.13.17;1.14.13.60', '1.14.13.32', '1.14.13.99', '1.14.13.98', '1.14.13.98', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.122', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.97', '1.14.13.97', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.2.1']
8
53
Vorinostat
9

100%|██████████| 11047/11047 [00:07<00:00, 1455.84it/s]
100%|██████████| 27873/27873 [00:16<00:00, 1653.80it/s]
 22%|██▏       | 13/58 [06:39<22:49, 30.42s/it]

rxndb num 346
failedrxn num 0
result_df 59
['1.14.13.9', '1.14.13.9', '1.14.13.9', '3.1.1.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.13.59', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.17.1.1', '1.17.1.1', '1.17.1.1', '1.17.1.1', '3.4.22.40;3.5.1.72', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.8.99.3;1.8.99.5', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.13.187', '1.14.13.187', '1.11.2.5', '1.11.2.5', '1.11.2.5', '6.3.1.18', '1.14.13.195;1.14.13.196', '1.14.13.196', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.5.1.123', '1.3.3.6', '1.3.3.6', '1.3.1.93', '1.3.1.93', '1.3.1.93', '1.3.1.93', '1.3.1.93', '1.3.1.93', '1.3.1.93', '1.3.1.93', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.12', '1.3.1.93', '1.3.1.93', '1.3.1.93', '1.3.1.93', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.5.1', '1.3.1', '1.3.1', '1.3.1', '1.3.1', '1.14.13.M65', '1.3.3.6', '1.3.3.6', '1.3.1.48', '1.3.1.48', '1.3.1.48', '1.3.1.48', '1.3.1.48', '1.3.1.48', '3.4.11.3;3.4.11.6;3.4.22.40', '2.3.2.2;3.4.11.10;3.4.19.3', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.4.21.4;3.4.22;3.4.22.1', '3.3.2.6;3.4.11.10;3.4.11.15', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.91', '1.14.14.91', '1.14.14.91', '6.3.1.2', '6.3.4.2', '1.14.13.25', '1.14.13.25', '1.14.13.25', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '6.3.2.17', '6.3.2.17', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '1.3.1.104;1.3.1.38;1.3.1.8', '1.3.1.104;1.3.1.38;1.3.1.8', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.3.1.104;1.3.1.38;1.3.1.44;1.3.1.8', '1.3.1.104;1.3.1.38;1.3.1.44;1.3.1.8', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.140', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.1.1;1.3.1.44', '1.1.1;1.3.1.44', '1.3.99.-', '1.3.99.-', '1.3.99.3', '1.3.99.3', '1.1.1;1.3.99.3', '1.1.1;1.3.99.3', '1.3.1.9', '1.3.1.9', '1.3.1.-', '1.3.1.-', '1.14.13.M66', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.4.15.6', '3.4.15.6', '3.4.19.9', '3.4.19.9', '3.4.19.5', '3.4.19.5', '3.4.19.7', '3.4.19.7', '3.2.1.-', '3.2.1.-', '1.-.-.-', '1.14.13.140', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.1.101', '3.1.1.101', '1.14.13.8', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '1.14.13.M64', '1.3.3.6', '1.3.3.6', '1.3.1.93', '1.3.1.93', '1.3.3.6', '1.3.3.6', '1.3.1.104;1.3.1.38;1.3.1.8', '1.3.1.104;1.3.1.38;1.3.1.8', '1.3.99.-', '1.3.99.-', '1.3.99.-', '1.3.99.-', '1.3.99.-', '1.14.14.30', '1.14.14.30', '1.14.14.30', '1.3.3.6;1.3.8.1;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.8.1;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6', '1.3.3.6', '1.3.3.6', '1.3.3.6', '1.3.1.10;1.3.1.38;1.3.1.8', '1.3.1.10;1.3.1.38;1.3.1.8', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.14.13', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1;1.1.1.206', '1.1.1;1.1.1.206']
35
91
Dolasetron
9

100%|██████████| 11047/11047 [00:08<00:00, 1286.80it/s]
100%|██████████| 27873/27873 [00:16<00:00, 1697.68it/s]
 24%|██▍       | 14/58 [07:09<22:17, 30.39s/it]

rxndb num 765
failedrxn num 0
result_df 66
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.17.1.5', '1.1.1.148', '1.1.1.148', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.99.2', '1.14.99.2', '1.1.1;1.1.1.-', '1.1.1;1.1.1.-', '1.1.1.230', '1.1.1.230', '1.1.1.226', '1.1.1.226', '1.1.1.62', '1.1.1.62', '1.1.1.62', '1.1.1.62', '1.1.1.146', '1.1.1.146', '1.1.1.53', '1.1.1.53', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.53', '1.14.12.16', '1.14.13.61', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.-;1.1.1.329', '1.1.1.-;1.1.1.329', '1.1.1.239;1.1.1.62', '1.1.1.239;1.1.1.62', '1.1.1.213', '1.1.1.213', '1.1.1.62', '1.1.1.62', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.13.130', '1.1.1.-;1.1.1.329', '1.1.1.-;1.1.1.329', '1.1.1.335', '1.1.1.335', '1.1.1.340;1.14.13.-', '1.1.1.340;1.14.13.-', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.1.1.374', '1.1.1.374', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.1.1.393', '1.1.1.393', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.1.1.-', '1.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.224', '1.14.13.224', '1.1.1.395', '1.1.1.395', '1.1.1.-;1.1.1.395', '1.1.1.-;1.1.1.395', '1.14.14.108', '1.1.1.201', '1.1.1.201', '1.1.1.-;1.1.1.50;1.1.1.52', '1.1.1.-;1.1.1.50;1.1.1.52', '1.1.1.391', '1.1.1.391', '1.1.1.-;1.1.1.393', '1.1.1.-;1.1.1.393', '1.1.1.145', '1.1.1.145', '1.1.1.415;1.1.1.ee', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.235', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13;1.14.13.-', '1.1.1', '1.1.1.201', '1.1.1.201', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1', '1.1.1', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.13.11', '1.1.1.392', '1.1.1.392', '1.1.1.393', '1.1.1.393', '1.1.1.52', '1.1.1.52', '1.1.1.391', '1.1.1.391', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.52', '1.1.1.52', '1.1.1.391', '1.1.1.391', '1.1.1.392;1.1.1.50;1.1.1.52', '1.1.1.392;1.1.1.50;1.1.1.52', '1.1.1.392', '1.1.1.392', '1.1.1.393', '1.1.1.393', '1.1.1.393', '1.1.1.393', '1.14.12.16', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.2;1.1.1.213;1.1.1.239;1.1.1.62;1.3.1.20', '1.1.1;1.1.1.2;1.1.1.213;1.1.1.239;1.1.1.62;1.3.1.20', '1.1.1.159', '1.1.1.159', '1.1.1.1', '1.1.1.1', '1.1.1.239;1.1.1.51', '1.1.1.239;1.1.1.51', '1.1.1.239', '1.1.1.239', '1.1.1.184;1.1.1.2;1.1.1.62', '1.1.1.184;1.1.1.2;1.1.1.62', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.50', '1.1.1.209', '1.1.1.209', '1.3;1.3.1.120', '1.1.1.210;1.1.1.357', '1.1.1.210;1.1.1.357', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.2.1.78', '3.2.1.78', '3.2.1.78', '1.13.11.52', '1.1.1.146;1.1.1.159;1.1.1.50', '1.1.1.146;1.1.1.159;1.1.1.50', '1.1.99.13', '1.1.99.13', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.146', '1.1.1.146', '1.14.13.-', '3.4.11.5', '3.4.11.5', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.82', '3.2.1.15;3.2.1.82', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.2;1.1.1.209;1.1.1.21;1.1.1.213;1.1.1.50;1.3.1.20', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.2;1.1.1.209;1.1.1.21;1.1.1.213;1.1.1.50;1.3.1.20', '1.13.11.52', '1.13.11.11;1.13.11.52', '1.1.1;1.1.1.148;1.1.1.209', '1.1.1;1.1.1.148;1.1.1.209', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.1.1.159;1.1.1.50', '1.1.1.159;1.1.1.50', '1.1.1.176', '1.1.1.176', '1.1.1.206', '1.1.1.206', '1.1.1.236', '1.1.1.236', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.1.1.238', '1.1.1.238', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.1.1.146', '1.1.1.146', '1.1.1.213;1.1.1.52', '1.1.1.213;1.1.1.52', '1.1.1.152;1.1.1.184;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1.152;1.1.1.184;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1.184;1.1.1.209;1.1.1.213;1.1.1.50', '1.1.1.184;1.1.1.209;1.1.1.213;1.1.1.50', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.1.1.50', '1.1.1.50', '1.1.1.209;1.1.1.50', '1.1.1.209;1.1.1.50', '1.1.1.213;1.1.1.50;1.1.1.51', '1.1.1.213;1.1.1.50;1.1.1.51', '1.1.1.149;1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.149;1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.1.1.213;1.1.1.277;1.1.1.50', '1.1.1.213;1.1.1.277;1.1.1.50', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.278', '1.1.1.278', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.13.11.11;1.13.11.52', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.1.1.210;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1.210;1.1.1.357;1.1.1.50;1.1.1.51', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.1;1.1.1.391', '1.1.1.1;1.1.1.391', '1.1.1.-;1.1.1.146;1.1.1.209;1.1.1.213;1.1.1.392;1.1.1.50', '1.1.1.-;1.1.1.146;1.1.1.209;1.1.1.213;1.1.1.392;1.1.1.50', '1.1.1.159', '1.1.1.159', '1.14.13.88', '1.14.13.88', '1.1.1.153', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.1.1.-;1.1.1.M53', '1.1.1.-;1.1.1.M53', '1.14.13.88', '1.14.13.88', '1.1.1.415', '1.1.1.201', '1.1.1.201', '1.1.1.425', '1.1.1.425', '1.1.1', '1.1.1', '1.1.1.64', '1.1.1.64', '1.3.1.120', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '1.14.13.54', '3.2.1.87', '3.4.15.6', '3.4.15.6', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.13.11.52', '3.2.1.15', '3.2.1.15', '4.2.2.2', '4.2.2.2', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.1.1.-', '1.1.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.88', '1.14.13.88', '1.14.13.176', '1.14.13.176', '3.2.1.143', '1.1.1.M51', '1.1.1.M51', '3.1.1.1;3.1.1.84', '1.14.13.182', '1.14.13.182', '1.1.1;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.51;1.1.1.62', '1.1;1.1.1;1.1.1.209;1.1.1.213', '1.1;1.1.1;1.1.1.209;1.1.1.213', '1.1.1.1', '1.1.1.1', '1.1.99.13', '1.1.99.13', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '1.1.1.395', '1.1.1.395', '1.1.1.146', '1.1.1.146', '1.1.1.64', '1.1.1.64', '1.1.1.146', '1.1.1.146', '1.1.1.146', '1.1.1.146', '1.1.1.239', '1.1.1.239', '1.1.1.239', '1.1.1.239', '1.1.1.62', '1.1.1.62', '1.1.1.238', '1.1.1.238', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1.206', '1.1.1.206', '1.13.11.52', '1.13.11.52']
29
126
Mycophenolate mofetil
9

100%|██████████| 11047/11047 [00:09<00:00, 1207.89it/s]
100%|██████████| 27873/27873 [00:16<00:00, 1694.39it/s]
 26%|██▌       | 15/58 [07:41<21:59, 30.69s/it]

rxndb num 2476
failedrxn num 0
result_df 88
['1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.1.5', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1;1.14.14.25;1.14.14.55;1.14.14.57', '1.14.13.100', '1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.1.23', '3.1.6.1;3.1.6.2', '5.5.1.24', '3.1.1.22;3.1.1.75', '1.14.18.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.118;1.1.1.47', '1.1.1.119;1.1.1.47', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.63', '1.14.13.63', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.4', '1.17.1.1', '1.17.1.1', '1.14.14.-;1.14.14.1', '3.1.1.70', '1.3.1.5', '1.3.1.5', '3.1.1.51', '3.1.1.60', '1.3.1.48', '1.3.1.48', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.17.1.3', '1.17.1.3', '1.17.1.3', '1.14.13.22', '1.14.13.180', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.99.-', '1.14.13.-', '2.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.3.1.-', '1.3.1.-', '1.14.13.-', '1.14.13.100;1.14.14.29', '1.14.13.38', '1.14.14.-', '1.14.13.-;1.14.13.161', '1.14.13;1.14.13.-', '1.11.2.5', '1.1.1.363;1.1.1.388', '1.1.1.390', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.217', '3.3.2.14', '2.1.1.-', '3.1.1.102', '1.14.13.-;1.14.13.M56', '1.3.1.114', '1.1.1.116', '1.3.1.34', '1.1.1.359;1.1.1.376;1.1.1.46', '1.3.3.6', '1.14.13', '6.3.2', '6.3.2', '3.1.1;3.1.1.1;3.1.1.3', '1.3.1', '1.3.1', '1.14.13;1.14.13.-', '1.3.1.93', '1.3.1.93', '1.14.14.133', '1.14.13;1.14.13.-', '3.1.1', '1.1.1', '1.1.1.415;1.1.1.ee', '1.14.13', '1.3.1', '1.3.1', '1.14.13', '3.1.1', '1.3.1.93', '1.3.1.93', '3.1.1.26', '1.14.14', '1.14.14', '3.1.1.4', '3.1.1.23', '3.1.1.23', '3.1.1.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.1', '1.3.1.93', '1.3.1.93', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.3.1.114', '1.3.1', '1.3.1', '3.1.1', '1.1.1.-', '1.1.1', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M81', '1.14.13;1.14.13.-', '3.1.1.1;3.1.1.13;3.1.1.3', '3.1.1.1;3.1.1.3', '1.3.3.6', '3.1.1.3', '3.1.1.3', '1.14.14.1', '3.1.1.1', '1.3.1.48', '1.3.1.48', '1.3.1.48', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '1.14.15.15', '3.1.1.1;3.1.1.2', '3.1.1.1;3.1.1.2', '1.1.1.179;1.3.1.20', '1.1.1.179;1.3.1.20', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '3.1.1.13', '3.1.1.13', '3.1.1.13', '3.1.1.13', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '3.1.6.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '3.4.21;3.4.21.62', '3.4.16.5;3.4.21;3.4.21.62', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.18.1', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '3.1.3.48', '3.1.3.2;3.1.3.48;3.1.3.76', '3.1.3.36;3.1.3.48', '1.1.1.121', '3.1.3.2', '1.1.1.47', '1.14.13.-', '1.14.13.-', '1.1.1.122', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.2.1.74', '1.14.13.-', '1.14.13.-', '3.4.11.5', '3.4.11.5', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.55', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.82', '3.2.1.15;3.2.1.82', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.145;3.2.1.23', '1.14.13.-;1.14.13.129', '3.2.1.35', '3.2.1.35', '1.14.13.112', '1.14.13.-;1.14.13.112', '2.3.1.-', '1.14.13.38', '1.14.13.234', '3.1.1', '1.14.14.91', '3.2.1.137;3.2.1.78', '5.3.3.1', '5.3.3.1', '1.3.1;1.3.1.-', '2.4.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-;1.14.13.129', '3.1.1.5', '3.1.1.5', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13;1.14.14.1', '1.14.13.30', '1.14.14.1', '5.5.1.24', '1.14.14.23', '1.14.13.17', '1.14.13.21;1.14.13.88', '1.14.13.16', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '3.1.1.10', '1.1.1.113', '1.14', '1.14.13.36', '1.14.13.56', '1.14.13.57', '1.3.1.104;1.3.1.38;1.3.1.8', '1.3.1.69', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.77', '1.14.13.76', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14.13.89', '1.3.1.104;1.3.1.38;1.3.1.44;1.3.1.8', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.19.41;1.3.1.-', '1.14.13.-', '1.14.13.-', '1.14.13', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.240', '1.14.13.11', '1.14.13.103', '1.14.13.17', '1.14.-.-;1.14.13.-', '1.14.13.-;1.14.13.146', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1;1.3.1.44', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '1.14.14.149', '2.3.1.-', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.89', '1.14.13.89', '1.14.19.41;1.3.1.-', '1.14.13.88', '1.14.13.88', '1.3.99.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.3.99.3', '1.1.1;1.3.99.3', '1.3.1.9', '1.1.1.363;1.1.1.388;1.1.1.47;1.1.1.49', '1.1.1.415', '1.3.1.-', '1.1.1', '1.14.13.M76', '1.14.13.M76', '1.3.1.42', '3.1.1.116', '1.1.1.376', '1.1.1.420', '1.14.13.9', '1.1.1.120', '3.2.1.14', '3.2.1.14', '1.1.1.121;1.1.1.175', '1.1.1.121', '1.1.1.179', '1.1.1.179', '3.2.1.37', '3.2.1.37', '1.1.1.46', '1.1.1.46', '3.2.1.55', '3.2.1.55', '3.2.1.3;3.2.1.58;3.2.1.59', '3.2.1.4', '3.2.1.4', '1.14.13.129', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.129', '1.1.1.121', '1.14.13.110', '1.14.-.-;1.14.13.-', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.99', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.2.1.87', '3.4.19.7', '3.4.19.7', '3.2.1.1', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '3.2.1.2', '3.1.-.-', '3.1.-.-', '1.14.99.45', '1.14.13.-', '1.14.13.21', '1.3.1.-', '1.3.1.-', '1.3.3.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.-.-', '1.-.-.-', '1.14.13.-', '1.-.-.-', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.13.-', '1.14.13.72', '1.14.15.5', '1.14.13.129', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '3.2.1.15', '3.2.1.15', '4.2.2.2', '4.2.2.2', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '6.2.1.3', '6.2.1.3', '6.2.1.3', '6.2.1.3', '3.2.1.137', '1.1.1.117', '1.1.1.117', '1.1.1.117', '1.1.1.117', '1.14.13.103', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '3.1.1.5', '1.6.5.2', '1.6.5.2', '1.6.5.2', '1.6.5.2', '1.14.13.-', '1.14.13.-', '1.1.1.46', '1.1.1.46', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.194', '3.1.1.101', '3.1.1.101', '1.14.13', '1.3.1.114', '3.2.1.143', '3.2.1.143', '3.2.1.143', '3.2.1.143', '1.3.3.6', '1.14.13.100;1.14.13.17;1.14.13.60', '1.3.1.93', '1.14.13.99', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.3.3.6', '1.3.1.104;1.3.1.38;1.3.1.8', '3.1.1.1;3.1.1.84', '1.1.1.363;1.1.1.49', '1.3.99.-', '1.14.13.-', '1.14.13.116', '3.1.1.88', '1.14.13.122', '1.14.13.190', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13;1.14.14.1', '1.1.1.118', '1.1.1.120;1.1.1.179;1.1.1.359;1.1.1.360;1.1.1.47;1.1.1.48;1.3.1.20', '1.1.1.120', '1.17.99.5', '1.3.3.6;1.3.8.1;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.1.1.119', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.3.3.6', '1.3.3.6', '1.3.99.-', '1.1.1.121;1.1.1.359;1.1.1.47;1.1.1.48', '1.1.1.121', '1.14.14.12', '1.14.14.12', '1.3.1.10;1.3.1.38;1.3.1.8', '1.14.14.-', '1.14.14;1.14.14.-', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.1.1.363;1.1.1.47;1.1.1.49', '1.1.1.49', '2.6.1.114', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.11.2.6', '1.1.1.424', '3.1.1.3', '3.1.1.102', '1.14.13.3;1.14.14.9', '1.14.13.127']
44
235
Zidovudine (3'-Azido-3'-Deoxythymidine)
9

100%|██████████| 11047/11047 [00:08<00:00, 1362.26it/s]
100%|██████████| 27873/27873 [00:16<00:00, 1724.93it/s]
 28%|██▊       | 16/58 [08:11<21:18, 30.45s/it]

rxndb num 640
failedrxn num 0
result_df 32
['3.1.3.69', '1.1.1.23', '3.1.3.15', '3.1.3.74', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.74', '3.1.3.27', '3.1.3.74', '1.1.1.1', '3.1.3.73', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.1.3.23', '3.1.3.39', '3.1.3.40', '3.1.6.9', '3.1.6.10', '1.1.3.39', '3.1.3.69', '1.14.13.-', '2.4.2.4', '2.4.2.3;2.4.2.4', '1.1.1.1', '1.1.1.1', '1.1.3.-;1.1.3.43', '3.1.3.-;3.1.3.88', '1.1.3.-;1.1.3.44', '3.1.3.79', '3.1.3.85', '3.1.3.83', '1.1.3;1.1.3.-', '3.1.3.92', '2.4.2.57', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '3.1.3.101', '3.1.3.-', '1.1.3.-', '3.1.3;3.1.3.-', '1.14.13.224', '1.14.13.224', '3.1.3.103', '3.1.3', '1.1.1.1', '3.1.3.-', '5.4.99.30;5.4.99.9', '3.1.3;3.1.3.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.13', '1.1.1', '3.1.3', '1.1.1', '1.14.13', '1.14.13', '1.1.3.48', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '4.2.1.M11', '1.1.1', '1.1.1.1', '3.1.6.14', '3.1.3.29', '3.1.3.33;3.1.3.5', '1.1.3.9', '3.2.1.78', '3.2.1.78', '2.4.2.2;2.4.2.3;2.4.2.4', '3.1.3', '3.1.3', '3.1.6.3', '3.1.3.68', '3.8.1.7', '1.14.15.4', '1.14.15.4', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.55', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.82', '3.2.1.15;3.2.1.82', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.145;3.2.1.23', '3.2.1.35', '3.2.1.35', '1.14.14.1', '3.1.3.91', '3.6.1;3.6.1.-', '3.2.1.137;3.2.1.78', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '3.1.3.23;3.1.3.29;3.1.3.9', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.27', '1.14.13.30', '3.1.3', '3.1.3.24', '2.4.2.2;2.4.2.3;2.4.2.4', '3.1.3.12', '1.1.1.-', '1.1.1.136', '1.1.1.132', '1.1.3.9', '3.1.3.29', '3.1.3.-', '1.1.1.23', '1.14.13.74', '1.14.13.74', '1.1.1.186', '3.1.3.70', '1.1.1.273', '1.1.1.273', '1.1.1.273', '1.14.13.74', '1.14.13.74', '1.1.1.186', '1.14.13.97', '1.14.13.97', '2.4.2.3;2.4.2.4', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.1.1.317', '1.1.1.317', '1.14.13.-', '1.14.13.-', '3.1.3.73', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '3.1.3.45', '1.1.1.-;1.1.1.336', '1.1.1.22', '3.1.3.68', '2.4.2.1;2.4.2.2;2.4.2.23;2.4.2.3;2.4.2.4', '3.1.3.M8', '1.1.1.273', '3.1.3.105', '3.2.2.3;3.2.2.8', '3.1.3.58;3.1.3.9', '3.1.6.3', '3.2.2.3', '1.1.3.9', '1.1.3.9', '3.2.1.14', '3.2.1.14', '3.2.1.37', '3.2.1.37', '3.2.1.55', '3.2.1.55', '3.2.1.3;3.2.1.58;3.2.1.59', '3.1.3.29', '3.2.2.-;3.2.2.8', '3.2.1.4', '3.2.1.4', '3.2.1.116', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.4.15.6', '3.4.15.6', '3.2.1.1', '1.7.3.-', '1.7.3.-', '1.7.3.-', '3.2.1.-', '3.2.1.-', '3.2.1.2', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '1.14.15.5', '1.14.15.5', '6.2.1.3', '3.2.1.137', '3.1.3.27', '3.1.3', '3.1.3.73', '3.2.1.143', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.73', '3.1.3', '1.1.1.2;1.1.1.20;1.1.1.21', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '2.4.2.2', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '3.2.2.3;3.2.2.8', '3.1.3.82', '3.1.3.58;3.1.3.9', '2.6.1.114', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '3.1.3.76', '1.1.1.1', '4.2.3;4.2.3.1', '3.1.3.-;3.1.3.104']
27
163
Allopurinol
9

100%|██████████| 11047/11047 [00:07<00:00, 1400.98it/s]
100%|██████████| 27873/27873 [00:16<00:00, 1660.12it/s]
 29%|██▉       | 17/58 [08:40<20:36, 30.17s/it]

rxndb num 69
failedrxn num 0
result_df 5
['1.14.13.-', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.14.13.224', '1.14.13.224', '1.14.13.235', '1.14.13', '1.14.13;1.14.13.-', '1.14.13', '1.17.1.4', '3.8.1.7']
3
6
Betamethasone
9

100%|██████████| 11047/11047 [00:10<00:00, 1025.33it/s]
100%|██████████| 27873/27873 [00:17<00:00, 1633.46it/s]
 31%|███       | 18/58 [09:12<20:31, 30.78s/it]

rxndb num 4405
failedrxn num 0
result_df 123

100%|██████████| 11047/11047 [00:09<00:00, 1188.05it/s]
100%|██████████| 27873/27873 [00:17<00:00, 1593.19it/s]
 33%|███▎      | 19/58 [09:43<20:01, 30.79s/it]

rxndb num 852
failedrxn num 0
result_df 67
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.1.1.118;1.1.1.47', '1.1.1.119;1.1.1.47', '1.17.1.5', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.63', '1.14.13.6', '1.14.13.6', '1.14.13.6', '1.14.13.6', '1.14.13.6', '3.1.1.55', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.19', '1.14.13.19', '1.1.1.173;1.1.1.378', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '3.1.1.1;3.1.1.56', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.61', '1.14.13.61', '1.14.13.219;1.14.13.7', '1.14.13.219;1.14.13.7', '1.14.13.219;1.14.13.7', '1.14.13.219;1.14.13.7', '1.14.13.219;1.14.13.7', '1.14.12.-', '1.14.12.-', '1.14.12.-', '1.14.12.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.181', '1.14.13.-;1.6.5.2', '1.14.13.-;1.6.5.2', '1.14.13.-;1.6.5.2', '1.14.13.-;1.6.5.2', '1.14.13.-;1.6.5.2', '1.14.13.-', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.14.13.130', '1.14.13.244;1.14.13.M20', '1.14.13.244;1.14.13.M20', '1.14.13.244;1.14.13.M20', '1.14.13.244;1.14.13.M20', '1.14.13.244;1.14.13.M20', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.14.13.189', '1.1.1.203', '1.1.1.203', '1.1.1.363;1.1.1.388', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.220', '1.14.13.-;1.14.13.220', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.13.224', '1.14.13.224', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.14.13.-;1.14.13.236', '1.1.1.203', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.235', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.1.1.-;1.1.1.377;1.1.1.378', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '1.14.13.M33', '1.14.13.M33', '1.14.13.M33', '1.14.13.M33', '1.14.13.M33', '1.1.1.-', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '3.1.1;3.1.1.1;3.1.1.14;3.1.1.2;3.1.1.7;3.1.1.74;3.1.1.88;3.1.2.12;3.1.2.2', '3.1.1;3.1.1.1;3.1.1.2', '3.1.1.1;3.1.1.13', '1.1.1.179;1.3.1.20', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.1.13;3.1.1.2;3.1.1.3', '1.14.13.84', '1.14.13.84', '1.14.13.84', '3.1.1.1', '1.14.13.84', '3.1.1.1', '3.1.1.1', '3.1.1.1', '1.14.14;1.14.14.1;1.14.14.25', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.11.1.7;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.1;3.1.1.1;3.1.1.2;3.1.1.74;3.1.1.88;3.1.2.12', '3.1.1;3.1.1.1', '1.1.1.121', '1.1.1.1;1.2.1.3;1.2.1.88;3.1.1;3.1.1.1;3.1.1.101;3.1.1.2;3.1.1.3;3.1.1.6;3.1.1.7;3.1.1.74;3.1.1.88;3.1.2.12', '1.1.1.47', '1.1.1.122', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.-', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.67', '3.2.1.15;3.2.1.82', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.76', '3.2.1.31', '1.14.13.10', '1.14.13.10', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '2.4.1.-', '1.14.13.30', '3.1.1.2', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.-;1.14.13.243', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14.13.7', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14;1.14.13.36', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.84', '3.1.1;3.1.1.2', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.1.1.107;1.1.1.122', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.2.1.5', '1.2.1.39;1.2.1.5', '1.1.1.363;1.1.1.388;1.1.1.47;1.1.1.49', '1.3.3.8', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.14.19.55', '1.2.3.1', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.1.1.120', '3.2.1.14', '1.1.1.121;1.1.1.175', '1.1.1.121', '1.1.1.179', '1.1.1.179', '1.1.1.121', '3.2.1.87', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.2.1.15', '4.2.2.2', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.176', '1.14.13.194', '3.1.1.101', '1.1.1.363;1.1.1.49', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.14.20', '1.14.14.20', '1.14.14.20', '1.14.14.20', '1.14.14.20', '1.1.1.118', '1.1.1.120;1.1.1.179;1.1.1.359;1.1.1.360;1.1.1.47;1.1.1.48;1.3.1.20', '1.1.1.120', '1.1.1.119', '1.1.1.121;1.1.1.359;1.1.1.47;1.1.1.48', '1.1.1.121', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.27', '1.14.14.27', '1.14.14.27', '1.14.14.27', '1.14.14.27', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.1.1.363;1.1.1.47;1.1.1.49', '1.1.1.49', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.3;1.14.14.9', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127']
29
134
Estradiol
9

100%|██████████| 11047/11047 [00:08<00:00, 1263.68it/s]
100%|██████████| 27873/27873 [00:10<00:00, 2550.00it/s]
 34%|███▍      | 20/58 [10:07<18:07, 28.63s/it]

rxndb num 2605
failedrxn num 0
result_df 83

100%|██████████| 11047/11047 [00:08<00:00, 1283.98it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2122.85it/s]
 36%|███▌      | 21/58 [10:32<16:55, 27.45s/it]

rxndb num 189
failedrxn num 0
result_df 29
['3.1.1.5', '3.5.4.11', '3.1.1.70', '3.1.1.54', '3.8.1.8', '1.14.13.181', '3.5.4.-', '1.14.13.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.1.1.53', '3.5.4.-;3.5.4.26', '3.5.4.-;3.5.4.26', '3.5.4.32', '1.14.13.-', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.14.13.224', '1.14.13.224', '6.3.2', '6.3.2', '3.1.1;3.1.1.1;3.1.1.3', '1.7.1;1.7.1.-', '3.1.1', '3.1.1', '1.14.13.235', '3.1.1.26', '3.1.1.4', '1.14.13', '1.14.13', '3.5.4.3', '3.5.4.3', '1.14.13', '1.14.13.M9', '3.1.1', '3.1.1', '3.1.1', '3.1.1;3.1.1.-', '3.1.1', '1.3.1', '1.14.13', '3.1.1', '1.1.1.-', '1.17.1.4', '3.1.1.1;3.1.1.3', '3.1.1.1', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '3.1.1.28', '1.1.1.2', '1.14.14.1', '1.14.14.1', '3.4.21;3.4.21.62', '3.4.16.5;3.4.21;3.4.21.62', '1.14.14.55', '3.8.1.7', '3.8.1.8', '3.8.1.8', '3.4.11.5', '2.3.1.-', '3.5.4.-;3.5.99.-', '3.5.4.42;3.5.99.4', '3.5.4.45;3.5.99.-', '3.5.4.-', '3.1.1', '1.14.14.1', '3.5.4.3', '3.1.1.5', '3.1.1.5', '1.1.1.204;1.17.1.4', '1.14.13.74', '1.14.13.74', '3.1.1.10', '1.14.13.74', '1.14.13.74', '3.1.1.80', '1.14.13.97', '1.14.13.97', '3.1.1.80', '3.1.1.80', '1.14.13.-', '1.14.13.-', '3.1.1.94', '2.3.1.-', '3.1.1.105', '3.1.1.105', '3.5.1.M13', '1.14.13.5', '3.1.1.80', '3.1.1.116', '1.2.3.1', '3.5.4.11', '3.1.1.53', '3.1.1.53', '3.1.1.53', '3.1.1.53', '3.4.15.6', '3.2.1.-', '3.1.-.-', '3.1.-.-', '3.1.1.53', '6.2.1.3', '3.1.1.5', '3.1.1.101', '3.2.1.143', '1.6.6.8;1.7.1.7', '6.3.4.1;6.3.5.2', '3.5.4.15', '3.1.1', '3.1.1', '3.1.1', '3.1.1.53', '3.1.1.53', '3.6.1.18;3.6.1.9', '3.1.1.7;3.1.1.8']
25
69
Flutamide
9

100%|██████████| 11047/11047 [00:08<00:00, 1337.89it/s]
100%|██████████| 27873/27873 [00:11<00:00, 2492.67it/s]
 38%|███▊      | 22/58 [10:54<15:37, 26.03s/it]

rxndb num 136
failedrxn num 0
result_df 30
['1.14.13.9', '1.14.13.9', '1.14.13.9', '3.1.1.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.29', '1.14.13.29', '1.14.13.29', '3.4.22.40;3.5.1.72', '1.7.1.9', '1.7.1.9', '1.7.1.-;1.7.1.16', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.12.23', '1.-.-.-;1.7.1', '1.7.1.-', '1.-.-.-', '1.12.99.6;1.2.7.1;1.2.7.4;1.2.99.2', '1.8.99.3;1.8.99.5', '1.-.-.-', '1.7.1.-', '1.7.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.14.12.-;1.14.12.24', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '6.3.1.18', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-', '3.5.1.123', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.24', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '3.5.1', '1.14.12.23', '1.7.1.16', '1.14.12.23', '1.14.12.23', '1.7.1', '1.7.1.16', '3.4.11.3;3.4.11.6;3.4.22.40', '2.3.2.2;3.4.11.10;3.4.19.3', '3.3.2.6;3.4.11.10;3.4.11.15', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.13', '1.14.13', '1.14.13', '1.14.13.25', '1.14.13.25', '1.14.13.25', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.-.-', '3.2.1.35', '3.2.1.35', '5.4.99.13', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.3.8.-', '1.14.14.22;1.14.99.46', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.7.1.-', '1.7.1.-', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.7.1.M3']
23
50
Hydrocortisone
9

100%|██████████| 11047/11047 [00:09<00:00, 1130.57it/s]
100%|██████████| 27873/27873 [00:15<00:00, 1845.46it/s]
 40%|███▉      | 23/58 [11:23<15:38, 26.83s/it]

rxndb num 5123
failedrxn num 0
result_df 160

100%|██████████| 11047/11047 [00:09<00:00, 1118.19it/s]
100%|██████████| 27873/27873 [00:14<00:00, 1949.79it/s]

rxndb num 4669
failedrxn num 0

 41%|████▏     | 24/58 [11:52<15:33, 27.44s/it]

result_df 167

100%|██████████| 11047/11047 [00:08<00:00, 1367.44it/s]
100%|██████████| 27873/27873 [00:15<00:00, 1819.69it/s]
 43%|████▎     | 25/58 [12:20<15:08, 27.54s/it]

rxndb num 4635
failedrxn num 0
result_df 128

100%|██████████| 11047/11047 [00:05<00:00, 2015.12it/s]
100%|██████████| 27873/27873 [00:14<00:00, 1937.72it/s]
 45%|████▍     | 26/58 [12:43<14:02, 26.34s/it]

rxndb num 254
failedrxn num 0
result_df 22
['1.1.1.23', '3.1.3.15', '1.1.1.3', '1.1.1.3', '3.1.3.74', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '3.1.3.-', '3.1.3.74', '3.1.3.74', '1.1.1.1', '3.1.3.73', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '1.1.3.23', '1.1.3.17', '3.1.3.39', '1.1.1.191;1.1.1.2;1.1.1.21', '1.7.1.9', '1.7.1.9', '4.99.1.-', '1.7.1.-;1.7.1.16', '1.-.-.-;1.7.1', '1.7.1.-', '1.-.-.-', '1.12.99.6;1.2.7.1;1.2.7.4;1.2.99.2', '1.-.-.-', '1.7.1.-', '1.7.1.-', '1.14.14.-;1.14.14.1', '1.1.1.1', '1.14.14.-;1.14.14.1', '1.1.1;1.1.1.-;1.1.1.1', '3.1.3.-;3.1.3.88', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.14.13.-', '3.1.3;3.1.3.-', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.1.1', '1.14.13', '1.14.13', '1.1.1', '1.7.1.16', '1.7.1', '1.7.1.16', '3.1.3.33;3.1.3.5', '3.1.3', '3.1.3', '3.4.11.5', '3.1.3.91', '3.6.1;3.6.1.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3', '1.1.1.23', '1.1.1.273', '1.1.1.273', '1.1.1.273', '1.1.1.317', '1.1.1.317', '3.1.3.73', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.1.99.1', '1.14.14.22;1.14.99.46', '3.1.3.M8', '1.14.13.5', '1.1.1.273', '3.4.15.6', '1.7.3.-', '1.7.3.-', '1.7.3.-', '1.14.13.-', '1.1.1.1', '1.7.1.-', '1.7.1.-', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3;3.1.3.-;3.1.3.4', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '2.6.1.114', '3.1.3.-', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '1.7.1.M3', '1.1.1.1;1.1.1.190', '3.1.3.-;3.1.3.104', '3.1.3.2;3.1.3.75', '1.1.1;1.1.1.1', '3.1.3.1;3.1.3.75']
19
66
Nabumetone
9

100%|██████████| 11047/11047 [00:06<00:00, 1676.85it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2082.67it/s]
 47%|████▋     | 27/58 [13:07<13:10, 25.50s/it]

rxndb num 2545
failedrxn num 0
result_df 77

100%|██████████| 11047/11047 [00:06<00:00, 1586.82it/s]
100%|██████████| 27873/27873 [00:14<00:00, 1873.65it/s]
 48%|████▊     | 28/58 [13:32<12:44, 25.49s/it]

rxndb num 2515
failedrxn num 0
result_df 39
['1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.99.50;1.14.99.51', '1.14.99.51', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.3.2.14', '3.3.2.14', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '2.1.1.-', '1.14.13.224', '1.14.13.224', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.235', '1.14.13', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.35', '2.4.1.-', '2.4.1.-', '2.4.1.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.3.3.8', '3.2.1.14', '3.2.1.87', '3.2.1.87', '3.2.1.87', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '6.2.1.3', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.176', '1.14.13.176', '1.14.13.176', '3.2.1.143', '3.2.1.143', '3.2.1.143', '1.14.13.32', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.13.182', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9']
18
55
Prednisolone
9

100%|██████████| 11047/11047 [00:08<00:00, 1362.48it/s]
100%|██████████| 27873/27873 [00:15<00:00, 1823.83it/s]
 50%|█████     | 29/58 [14:00<12:36, 26.09s/it]

rxndb num 4775
failedrxn num 0
result_df 137

100%|██████████| 11047/11047 [00:08<00:00, 1351.71it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2151.15it/s]
 52%|█████▏    | 30/58 [14:25<12:04, 25.86s/it]

rxndb num 2599
failedrxn num 0
result_df 133

100%|██████████| 11047/11047 [00:08<00:00, 1349.46it/s]
100%|██████████| 27873/27873 [00:15<00:00, 1817.32it/s]
 53%|█████▎    | 31/58 [14:53<11:52, 26.38s/it]

rxndb num 4615
failedrxn num 0
result_df 147

100%|██████████| 11047/11047 [00:09<00:00, 1169.35it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2189.46it/s]
 55%|█████▌    | 32/58 [15:19<11:28, 26.49s/it]

rxndb num 3360
failedrxn num 0
result_df 157

100%|██████████| 11047/11047 [00:08<00:00, 1331.91it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2125.34it/s]
 57%|█████▋    | 33/58 [15:44<10:51, 26.07s/it]

rxndb num 1059
failedrxn num 0
result_df 76
['3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '3.1.3.74', '3.1.3.74', '3.1.3.73', '1.14.18.1', '3.1.3.39', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '3.1.3.40', '3.1.6.9', '3.1.6.10', '1.14.13.19', '1.14.13.19', '1.14.13.180', '1.14.13.180', '1.2.1.-', '1.14.13.1', '1.2.1.-', '1.14.13.1', '1.14.13.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.172', '1.14.13.-;1.14.13.172', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.1.3.-;3.1.3.88', '3.1.3.83', '3.1.3.92', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.224', '1.14.13.217', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.224', '3.1.3', '3.1.3.-', '3.1.6;3.1.6.-', '1.1.1.415;1.1.1.ee', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.6.14', '3.1.3.29', '3.1.3.33;3.1.3.5', '1.14.18.1', '3.1.1.1;3.1.1.2', '3.1.1.1;3.1.1.2', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.13', '1.2.1.3', '3.1.3.48', '3.1.3.36;3.1.3.48', '3.1.3.48', '1.14.14.55', '3.1.3.48', '3.1.3.2', '3.1.3', '3.1.3', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.13.-', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.82', '3.2.1.15;3.2.1.82', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '1.14.13.10', '1.14.13.10', '3.1.3.91', '3.6.1;3.6.1.-', '1.14.13', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.29', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.3.-', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '3.1.3.73', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.1.1.415', '3.1.3.M8', '3.1.3.105', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.1.3.29', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '3.2.1.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '3.2.1.15', '3.2.1.15', '4.2.2.2', '4.2.2.2', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '3.1.3.82', '1.14.14.8', '1.7.1.17;1.7.1.6', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '1.11.2.6', '3.1.3.-;3.1.3.104']
20
101
Tinidazole
9

100%|██████████| 11047/11047 [00:08<00:00, 1279.50it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2250.89it/s]
 59%|█████▊    | 34/58 [16:09<10:14, 25.59s/it]

rxndb num 46
failedrxn num 0
result_df 12
['1.14.14.1', '1.7.1.9', '1.7.1.9', '1.7.1.-;1.7.1.16', '1.-.-.-;1.7.1', '1.7.1.-', '1.-.-.-', '1.12.99.6;1.2.7.1;1.2.7.4;1.2.99.2', '1.-.-.-', '1.7.1.-', '1.7.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.14.13.-', '1.14.13', '1.7.1.16', '1.7.1', '1.7.1.16', '3.2.1.35', '3.2.1.35', '1.14.14.22;1.14.99.46', '1.14.13.-', '1.7.1.-', '1.7.1.-', '2.6.1.114', '1.7.1.M3']
10
18
Fluoxetine·HCl
9

100%|██████████| 11047/11047 [00:07<00:00, 1537.57it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2177.94it/s]
 60%|██████    | 35/58 [16:33<09:35, 25.01s/it]

rxndb num 595
failedrxn num 0
result_df 36
['1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.4.3.4', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.4.3.4', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.240', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.55', '1.14.14.55', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.13.112', '1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.74', '1.14.13.74', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.240', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.14.149', '1.14.14.149', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.236', '1.14.13.236', '1.14.13.236', '1.14.13.236', '1.14.13.236', '1.14.13.8', '1.14.13.98', '1.14.13.98', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127', '1.14.13.127']
15
49
Misoprostol
9

100%|██████████| 11047/11047 [00:08<00:00, 1360.20it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2004.84it/s]

rxndb num 4522
failedrxn num 0
result_df 186

 62%|██████▏   | 36/58 [16:59<09:18, 25.38s/it]

Megestrol Acetate
9

100%|██████████| 11047/11047 [00:08<00:00, 1295.24it/s]
100%|██████████| 27873/27873 [00:13<00:00, 1996.03it/s]
 64%|██████▍   | 37/58 [17:27<09:09, 26.15s/it]

rxndb num 2734
failedrxn num 0
result_df 144

100%|██████████| 11047/11047 [00:06<00:00, 1775.35it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2027.23it/s]
 66%|██████▌   | 38/58 [17:50<08:26, 25.31s/it]

rxndb num 1590
failedrxn num 0
result_df 64
['3.1.3.69', '3.1.3.69', '3.1.3.15', '3.1.3.15', '3.1.3.74', '3.1.3.74', '3.1.1.5', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.-', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.74', '3.1.3.74', '3.1.3.27', '3.1.3.27', '5.3.1.24', '3.1.3.74', '3.1.3.74', '3.1.3', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.3.-;3.1.3.4;3.1.3.76', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '3.1.3.39', '3.1.3.39', '1.1.1.148', '1.1.1.148', '1.1.3.16', '1.1.3.16', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.101', '1.1.1.101', '3.1.3.40', '3.1.3.40', '3.1.6.9', '3.1.6.9', '3.1.6.10', '3.1.6.10', '1.1.1;1.1.1.-', '1.1.1;1.1.1.-', '1.-.-.-;1.1.1.342', '1.-.-.-;1.1.1.342', '1.1.1.62', '1.1.1.62', '1.1.1.62', '1.1.1.62', '1.1.1.53', '1.1.1.53', '1.1.1.50', '1.1.1.50', '1.1.1.53', '1.1.1.53', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.166', '1.1.1.166', '1.1.1.263', '1.1.1.263', '3.1.3.69', '3.1.3.69', '1.1.1;1.1.1.-', '1.1.1;1.1.1.-', '1.1.1.364', '1.1.1.364', '1.14.13.181', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.76', '3.1.3.76', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.-', '1.1.1.-', '1.1.1;1.1.1.-;1.1.1.50', '1.1.1;1.1.1.-;1.1.1.50', '1.1.1.292', '1.1.1.292', '3.1.1.1', '2.4.2.4', '2.4.2.3;2.4.2.4', '1.1.1.-', '1.1.1.-', '1.1.1.-', '1.1.1.-', '1.1.1.-;1.1.1.341;4.2.1.-', '1.1.1.-;1.1.1.341;4.2.1.-', '1.1.1.-;1.1.1.329', '1.1.1.-;1.1.1.329', '3.1.3.-;3.1.3.88', '3.1.3.-;3.1.3.88', '1.1.1.-', '1.1.1.-', '1.1.1.213', '1.1.1.213', '3.1.3.79', '3.1.3.79', '1.1.3.-;1.1.3.45', '1.1.3.-;1.1.3.45', '3.3.2.-;3.3.2.10', '3.1.3.85', '3.1.3.85', '3.1.3.83', '3.1.3.83', '1.1.1.-;1.1.1.329', '1.1.1.-;1.1.1.329', '1.1.1.335', '1.1.1.335', '1.1.1.339;1.1.1.344', '1.1.1.339;1.1.1.344', '1.1.1.355', '1.1.1.355', '1.1.1.356', '1.1.1.356', '1.1.1.356', '1.1.1.356', '1.14.19.n5', '1.1.1.361', '1.1.1.361', '5.4.99.59', '3.1.3.92', '3.1.3.92', '1.1.1.364', '1.1.1.364', '1.1.1.367', '1.1.1.367', '1.1.1.374', '1.1.1.374', '2.4.2.57', '1.1.1.385', '1.1.1.385', '1.14.13.-;1.14.13.224', '1.14.13.-;1.14.13.224', '1.1.1.393', '1.1.1.393', '3.1.3.101', '3.1.3.101', '3.1.3.-', '3.1.3.-', '1.1.1.-', '1.1.1.-', '1.1.1.-', '1.1.1.-', '1.1.1.-', '1.1.1.-', '3.1.3;3.1.3.-', '3.1.3;3.1.3.-', '1.1.1.-', '1.1.1.-', '1.14.13.224', '1.14.13.224', '3.1.3.103', '3.1.3.103', '1.1.1.395', '1.1.1.395', '1.1.1.-;1.1.1.395', '1.1.1.-;1.1.1.395', '1.1.1', '1.1.1', '3.1.3', '3.1.3', '3.1.3.-', '3.1.3.-', '1.1.1.201', '1.1.1.201', '1.1.1.-;1.1.1.50;1.1.1.52', '1.1.1.-;1.1.1.50;1.1.1.52', '1.1.1.391', '1.1.1.391', '3.1.3;3.1.3.-', '3.1.3;3.1.3.-', '1.14.13', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '3.1.6;3.1.6.-', '1.1.1.102', '1.1.1.102', '1.1.1.145', '1.1.1.145', '1.14.14.133', '1.14.14.133', '3.1.1', '1.1.1', '1.1.1', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '5.4.99.59', '1.1.1', '1.1.1', '1.1.1.101', '1.1.1.101', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1', '1.1.1', '1.1.1', '1.1.1', '3.1.3.4', '3.1.3.4', '1.1.1.201', '1.1.1.201', '1.1.1', '1.1.1', '1.1.1', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1', '1.1.1', '1.1.1.M2', '1.1.1.M2', '1.1.1', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '1.1.1.M11', '1.1.1.M11', '1.1.1.M11', '1.1.1.M11', '1.1.1.392', '1.1.1.392', '1.1.1.393', '1.1.1.393', '1.1.1.52', '1.1.1.52', '1.1.1.391', '1.1.1.391', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.52', '1.1.1.52', '1.1.1.391', '1.1.1.391', '1.1.1.392;1.1.1.50;1.1.1.52', '1.1.1.392;1.1.1.50;1.1.1.52', '1.1.1.392', '1.1.1.392', '1.1.1.393', '1.1.1.393', '1.1.1.393', '1.1.1.393', '1.1.1', '1.1.1', '1.3.1', '1.1.1.159', '1.1.1.159', '1.1.1.218', '1.1.1.218', '3.1.6.14', '3.1.6.14', '1.1.1.218', '1.1.1.218', '3.1.3.29', '3.1.3.29', '1.1.1.149', '1.1.1.149', '3.1.3.33;3.1.3.5', '3.1.3.33;3.1.3.5', '1.1.1.133', '1.1.1.133', '1.1.1.239', '1.1.1.239', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.50', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.1.1.292', '1.1.1.292', '1.14.14.25', '1.14.14.25', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '1.14.14.55', '1.14.14.55', '3.2.1.78', '3.2.1.78', '3.2.1.78', '2.4.2.2;2.4.2.3;2.4.2.4', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '1.1.1.146;1.1.1.159;1.1.1.50', '1.1.1.146;1.1.1.159;1.1.1.50', '3.1.6.3', '3.1.6.3', '1.1.99.13', '1.1.99.13', '3.1.3.68', '3.1.3.68', '1.1.1.-', '1.1.1.-', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '3.8.1.7', '1.1.1.133', '1.1.1.133', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '3.8.1.8', '3.2.1.154;3.2.1.26;3.2.1.80', '3.2.1.154;3.2.1.26;3.2.1.80', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.113;3.2.1.114;3.2.1.137;3.2.1.163;3.2.1.77', '3.2.1.55', '3.2.1.55', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;3.2.1.165;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.82', '3.2.1.15;3.2.1.82', '3.2.1.4;3.2.1.91', '3.2.1.4;3.2.1.91', '3.2.1.21;3.2.1.3', '3.2.1.21;3.2.1.3', '1.1.1.-', '1.1.1.-', '3.2.1.65', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.145;3.2.1.23', '3.2.1.145;3.2.1.23', '3.2.1.35', '3.2.1.35', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '3.1.3.91', '3.1.3.91', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.2.1.137;3.2.1.78', '3.2.1.137;3.2.1.78', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '3.1.3.29', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.-;1.1.1.146', '1.1.1.-;1.1.1.146', '1.1.1;1.1.1.-;1.1.1.146;1.1.1.51', '1.1.1;1.1.1.-;1.1.1.146;1.1.1.51', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '3.1.1.5', '3.1.3.23;3.1.3.29;3.1.3.9', '3.1.3.23;3.1.3.29;3.1.3.9', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.27', '3.1.3.27', '1.14.13.30', '1.14.13.30', '3.1.3', '3.1.3', '3.1.3.24', '3.1.3.24', '1.1.1.133', '1.1.1.133', '2.4.2.2;2.4.2.3;2.4.2.4', '3.1.3.12', '3.1.3.12', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '1.1.1.271', '1.1.1.271', '3.1.3.29', '3.1.3.29', '1.1.1;1.1.1.148;1.1.1.209', '1.1.1;1.1.1.148;1.1.1.209', '3.1.3.-', '3.1.3.-', '1.1.1.134;1.1.1.344', '1.1.1.134;1.1.1.344', '1.1.1.159;1.1.1.50', '1.1.1.159;1.1.1.50', '1.1.1.176', '1.1.1.176', '1.1.1.206', '1.1.1.206', '1.1.1.236', '1.1.1.236', '1.1.1.241', '1.1.1.241', '1.1.1.135;1.1.1.187', '1.1.1.135;1.1.1.187', '1.1.1.187;1.1.1.281', '1.1.1.187;1.1.1.281', '1.1.1.135;1.1.1.187', '1.1.1.135;1.1.1.187', '1.1.1.187;1.1.1.281', '1.1.1.187;1.1.1.281', '1.1.1.238', '1.1.1.238', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.1.1.146', '1.1.1.146', '1.1.1.213;1.1.1.52', '1.1.1.213;1.1.1.52', '1.1.1.50', '1.1.1.50', '1.1.1.209;1.1.1.50', '1.1.1.209;1.1.1.50', '1.1.1.266', '1.1.1.266', '3.1.3.70', '3.1.3.70', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.140', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.4.2.3;2.4.2.4', '3.1.3.68', '3.1.3.68', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '3.1.3;3.1.3.-;3.1.3.11;3.1.3.23', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.1;1.1.1.391', '1.1.1.1;1.1.1.391', '1.1.1.-;1.1.1.146;1.1.1.209;1.1.1.213;1.1.1.392;1.1.1.50', '1.1.1.-;1.1.1.146;1.1.1.209;1.1.1.213;1.1.1.392;1.1.1.50', '3.1.3.73', '3.1.3.73', '1.1.1;1.1.1.-', '1.1.1;1.1.1.-', '3.1.3', '3.1.3', '3.1.3', '3.1.3', '1.1.1.159', '1.1.1.159', '1.1.1.-', '1.1.1.-', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.145;3.2.1.23;3.2.1.M17;3.2.1.M18', '3.2.1.22;3.2.1.23', '3.2.1.22;3.2.1.23', '1.1.1.153', '3.1.3.45', '3.1.3.45', '1.1.1.-;1.1.1.M53', '1.1.1.-;1.1.1.M53', '3.1.3.68', '3.1.3.68', '2.4.2.1;2.4.2.2;2.4.2.23;2.4.2.3;2.4.2.4', '1.1.1.201', '1.1.1.201', '1.1.1.425', '1.1.1.425', '3.1.3.M8', '3.1.3.M8', '1.1.1', '1.1.1', '1.1.1.266', '1.1.1.266', '3.1.3.106;3.1.3.76', '3.1.3.106;3.1.3.76', '1.1.1.367', '1.1.1.367', '3.1.3.106;3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.106', '3.1.3.106', '3.1.3.76', '3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.106;3.1.3.76', '3.1.3.105', '3.1.3.105', '1.1.1', '1.1.1', '3.2.2.3;3.2.2.8', '1.1.3.10', '1.1.3.10', '1.1.3.10', '1.1.3.10', '3.1.3.58;3.1.3.9', '3.1.3.58;3.1.3.9', '3.1.6.3', '3.1.6.3', '3.2.2.3', '3.2.1.14', '3.2.1.14', '3.2.1.37', '3.2.1.37', '3.2.1.37', '3.2.1.37', '3.2.1.55', '3.2.1.55', '3.2.1.55', '3.2.1.55', '3.2.1.3;3.2.1.58;3.2.1.59', '3.2.1.3;3.2.1.58;3.2.1.59', '3.1.3.29', '3.1.3.29', '3.2.2.-;3.2.2.8', '3.2.1.4', '3.2.1.4', '3.2.1.4', '3.2.1.4', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.-.-;1.14.13.-', '1.14.-.-;1.14.13.-', '3.3.2.-', '1.14.13.126', '1.14.13.126', '3.2.1.116', '3.2.1.116', '3.2.1.60', '3.2.1.60', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.-;3.2.1.2;3.2.1.68', '3.2.1.87', '3.2.1.87', '3.4.15.6', '3.4.15.6', '3.2.1.1', '3.2.1.1', '1.1.1.-', '1.1.1.-', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '3.2.1.-', '3.2.1.-', '1.1.1.-', '1.1.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '3.2.1.2', '3.2.1.2', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.99.-', '1.14.13.174', '1.-.-.-', '3.2.1.153;3.2.1.26;3.2.1.80', '3.2.1.153;3.2.1.26;3.2.1.80', '3.2.2.-', '1.14.15.5', '1.14.15.5', '3.2.2.3', '3.2.1.15', '3.2.1.15', '4.2.2.2', '4.2.2.2', '6.2.1.3', '6.2.1.3', '3.2.1.137', '3.2.1.137', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.1.1.-', '1.1.1.-', '3.1.3.27', '3.1.3.27', '1.14.13.140', '1.14.13.184', '1.14.13.184', '3.1.3', '3.1.3', '3.1.3.73', '3.1.3.73', '3.2.1.143', '3.2.1.143', '3.1.3.73', '3.1.3.73', '3.1.3', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.1.1.M51', '1.1.1.M51', '3.1.3.73', '3.1.3.73', '1.1.1.M51', '1.1.1.M51', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '1.11.1.13;1.16.3.-;2.4.1.25;2.4.1.63;2.4.1.8;3.1.3.90;3.2.1.20;4.2.1.131', '3.1.3.106', '3.1.3.106', '3.1.3.73', '3.1.3.73', '3.1.3', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.5.1', '2.4.2.2', '3.1.3;3.1.3.-;3.1.3.4', '3.1.3;3.1.3.-;3.1.3.4', '3.2.1.23', '3.2.1.23', '3.5.4.16', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7;3.1.3.97', '3.1.3.7', '3.1.3.7', '1.1.1.184;1.1.1.189', '1.1.1.184;1.1.1.189', '3.2.2.3;3.2.2.8', '3.1.3.82', '3.1.3.82', '3.3.2.10', '1.3.99.-', '1.3.99.-', '1.1.1;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.51;1.1.1.62', '1.1.1.271', '1.1.1.271', '1.1.1.271', '1.1.1.271', '1.1.99.13', '1.1.99.13', '3.1.3.58;3.1.3.9', '3.1.3.58;3.1.3.9', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '1.17.99.5', '3.1.3.-', '3.1.3.-', '3.1.3', '3.1.3', '3.1.3.-;3.1.3.102;3.1.3.2', '3.1.3.-;3.1.3.102;3.1.3.2', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.1.1.367', '1.1.1.367', '1.1.1.-', '1.1.1.-', '1.1.1.395', '1.1.1.395', '1.1.1', '1.1.1', '1.1.1.64', '1.1.1.64', '1.1.1.146', '1.1.1.146', '1.1.1.239', '1.1.1.239', '1.1.1.62', '1.1.1.62', '1.1.1.238', '1.1.1.238', '1.1.1.206', '1.1.1.206', '3.1.3.76', '3.1.3.76', '3.1.3.76', '3.1.3.76', '1.1.1.102', '1.1.1.102', '4.2.3;4.2.3.1', '4.2.3;4.2.3.1', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '3.1.3.-;3.1.3.104', '3.1.3.-;3.1.3.104']
37
235
Chenodiol (Chenodeoxycholic Acid)
9

100%|██████████| 11047/11047 [00:07<00:00, 1404.80it/s]
100%|██████████| 27873/27873 [00:15<00:00, 1768.90it/s]
 67%|██████▋   | 39/58 [18:18<08:13, 25.95s/it]

rxndb num 4102
failedrxn num 0
result_df 134

100%|██████████| 11047/11047 [00:08<00:00, 1366.39it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2284.89it/s]
 69%|██████▉   | 40/58 [18:42<07:40, 25.58s/it]

rxndb num 346
failedrxn num 0
result_df 40
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.8.1.7', '3.8.1.7', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.97.1.-', '1.97.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.12.16', '1.14.12.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.3.98.-', '1.3.98.-', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.176', '1.14.13.176', '1.14.13.176', '1.14.13.176', '1.14.19.58', '1.14.19.58', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14']
8
24
Clonazepam
9

100%|██████████| 11047/11047 [00:06<00:00, 1612.90it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2137.33it/s]
 71%|███████   | 41/58 [19:06<07:07, 25.15s/it]

rxndb num 369
failedrxn num 0
result_df 51
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.1.1.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '3.8.1.7', '3.4.22.40;3.5.1.72', '1.7.1.9', '1.7.1.9', '1.7.1.-;1.7.1.16', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.12.23', '1.14.12.23', '1.-.-.-;1.7.1', '1.7.1.-', '1.-.-.-', '1.12.99.6;1.2.7.1;1.2.7.4;1.2.99.2', '1.-.-.-', '1.7.1.-', '1.7.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.14.12.-;1.14.12.24', '1.14.12.-;1.14.12.24', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '6.3.1.18', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.5.1.123', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.24', '1.14.12.24', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '3.5.1', '1.14.12.23', '1.14.12.23', '1.7.1.16', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.7.1', '1.7.1.16', '3.4.11.3;3.4.11.6;3.4.22.40', '2.3.2.2;3.4.11.10;3.4.19.3', '3.4.21.4;3.4.22;3.4.22.1', '3.3.2.6;3.4.11.10;3.4.11.15', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.25', '1.14.13.25', '1.14.13.25', '1.14.13.25', '1.14.13.25', '1.14.13.25', '1.14.13.25', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.2.1.18', '3.2.1.18', '1.14.-.-', '1.14.-.-', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.140', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.14.22;1.14.99.46', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.4.15.6', '3.4.15.6', '1.3.98.-', '3.2.1.-', '3.2.1.-', '1.7.1.-', '1.7.1.-', '1.14.13.140', '1.14.19.58', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.7.1.M3', '1.1.1;1.1.1.206']
26
59
Cortisone Acetate
9

100%|██████████| 11047/11047 [00:08<00:00, 1297.67it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2000.67it/s]

rxndb num 4578
failedrxn num 0

 72%|███████▏  | 42/58 [19:34<06:51, 25.74s/it]

result_df 180

100%|██████████| 11047/11047 [00:06<00:00, 1799.31it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2055.35it/s]
 74%|███████▍  | 43/58 [19:57<06:17, 25.19s/it]

rxndb num 224
failedrxn num 0
result_df 28
['1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.7.1.9', '1.7.1.9', '1.7.1.-;1.7.1.16', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.12.23', '1.-.-.-;1.7.1', '1.7.1.-', '1.-.-.-', '1.12.99.6;1.2.7.1;1.2.7.4;1.2.99.2', '1.-.-.-', '1.7.1.-', '1.7.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.14.12.-;1.14.12.24', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.24', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.7.1.16', '1.14.12.23', '1.14.12.23', '1.7.1', '1.7.1.16', '1.14.13;1.14.14', '1.14.13;1.14.14', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.25', '1.14.13.25', '1.14.13.25', '1.14.13.25', '3.8.1.7', '3.8.1.7', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '1.14.-.-', '3.2.1.35', '3.2.1.35', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.14.22;1.14.99.46', '1.14.14.22;1.14.99.46', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.4.15.6', '3.4.15.6', '3.2.1.-', '3.2.1.-', '1.7.1.-', '1.7.1.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.7.1.M3']
17
44
Duloxetine
9

100%|██████████| 11047/11047 [00:06<00:00, 1687.65it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2155.00it/s]
 76%|███████▌  | 44/58 [20:21<05:46, 24.73s/it]

rxndb num 1013
failedrxn num 0
result_df 67
['1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.-;1.14.18.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.4.3.4', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.4.3.4', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '2.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.16.2;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.55', '1.14.14.55', '1.14.15.4', '1.14.15.4', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '2.4.1.-', '1.14.-.-', '1.14.-.-', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.-', '1.14.13.-', '1.14.14.149', '1.14.14.149', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '1.-.-.-', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.8', '1.14.13.98', '1.14.13.98', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.97', '1.14.13.97', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6']
17
58
Fludrocortisone Acetate
9

100%|██████████| 11047/11047 [00:08<00:00, 1337.47it/s]
100%|██████████| 27873/27873 [00:13<00:00, 2038.74it/s]

rxndb num 4480
failedrxn num 0

 78%|███████▊  | 45/58 [20:48<05:29, 25.33s/it]

result_df 163

100%|██████████| 11047/11047 [00:06<00:00, 1653.69it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2243.38it/s]
 79%|███████▉  | 46/58 [21:13<05:03, 25.28s/it]

rxndb num 1999
failedrxn num 0
result_df 52
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.7.1.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1.219', '1.1.1.219', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.14.13.19', '1.1.1.234', '1.1.1.234', '1.1.1.234', '1.1.1.362', '1.14.13.180', '1.14.13.180', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '1.1.1.219', '1.1.1.219', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.349', '1.14.19.n5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.3.2.14', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '2.1.1.-', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.362', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.99', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.348', '1.1.1.348', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.-;1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.14.13.M56', '1.3.1', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.14', '1.14.14.1', '1.14.14.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14.1', '3.2.1.78', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.13.21', '1.1.1.-', '1.14.13.-', '1.14.13.-', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.35', '1.1.1.246;1.1.1.348', '1.1.1.219', '2.4.1.-', '2.4.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.147', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.219', '1.14.13.88', '1.14.13.88', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.1.1.50', '3.2.1.14', '3.2.1.87', '3.2.1.87', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.14.15.5', '6.2.1.3', '6.2.1.3', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.88', '1.14.13.88', '1.14.13.176', '3.2.1.143', '3.2.1.143', '1.3.1', '1.3.1.-', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '3.6.1.18;3.6.1.9', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-']
23
75
Lorazepam
9

100%|██████████| 11047/11047 [00:06<00:00, 1638.99it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2183.09it/s]
 81%|████████  | 47/58 [21:38<04:38, 25.31s/it]

rxndb num 836
failedrxn num 0
result_df 74
['3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '3.1.3.74', '3.1.3.73', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3.39', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.1.3.40', '3.1.6.9', '3.1.6.10', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '3.8.1.7', '3.8.1.7', '3.4.22.40;3.5.1.72', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.97.1.-', '1.97.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.1.3.-;3.1.3.88', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '6.3.1.18', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.5.1.123', '3.1.3', '3.1.3.-', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.19', '1.14.19', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.5.1', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '3.1.6.14', '3.1.3.29', '3.1.3.33;3.1.3.5', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.4.21.4;3.4.22;3.4.22.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.82', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.1.3.91', '3.6.1;3.6.1.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.29', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.3.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.140', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '3.1.3.73', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.M8', '3.1.3.107', '3.1.3.105', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.1.3.29', '1.14.14.-', '1.14.14.-', '1.3.98.-', '1.3.98.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.140', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.14.19.58', '1.14.19.58', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '3.1.3.-;3.1.3.104']
25
91
Nilutamide
9

100%|██████████| 11047/11047 [00:07<00:00, 1502.95it/s]
100%|██████████| 27873/27873 [00:12<00:00, 2180.05it/s]
 83%|████████▎ | 48/58 [22:03<04:11, 25.18s/it]

rxndb num 181
failedrxn num 0
result_df 28
['1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.7.1.9', '1.7.1.9', '1.7.1.-;1.7.1.16', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.12.23', '1.-.-.-;1.7.1', '1.7.1.-', '1.-.-.-', '1.12.99.6;1.2.7.1;1.2.7.4;1.2.99.2', '1.-.-.-', '1.7.1.-', '1.7.1.-', '1.14.14.-;1.14.14.1', '1.1.1.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.14.12.-;1.14.12.24', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13', '1.14.13', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.24', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.7.1.16', '1.14.12.23', '1.14.12.23', '1.7.1', '1.7.1.16', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.13', '1.14.13', '1.14.13', '1.14.13.25', '1.14.13.25', '1.14.13.25', '3.8.1.7', '3.8.1.7', '3.8.1.7', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.18', '1.14.-.-', '3.2.1.35', '3.2.1.35', '3.2.1.35', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.14.22;1.14.99.46', '3.2.1.14', '3.2.1.14', '3.2.1.14', '3.2.1.-', '3.2.1.-', '3.2.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.M3']
17
40
Nitisinone
9

100%|██████████| 11047/11047 [00:07<00:00, 1434.27it/s]
100%|██████████| 27873/27873 [00:15<00:00, 1756.01it/s]
 84%|████████▍ | 49/58 [22:31<03:54, 26.02s/it]

rxndb num 327
failedrxn num 0
result_df 37
['1.1.1.157;1.1.1.35', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.7.1.4', '1.14.13.29', '1.14.13.29', '1.14.13.29', '1.1.1.101', '1.1.1.101', '1.14.13.4', '1.14.13.4', '1.14.13.4', '1.17.1.1', '1.17.1.1', '1.1.1.230', '1.1.1.230', '1.7.1.9', '1.7.1.9', '1.1.1.226', '1.1.1.226', '1.1.1.-;1.1.1.35', '1.1.1.166', '1.1.1.166', '1.7.1.-;1.7.1.16', '1.1.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.12.23', '1.-.-.-;1.7.1', '1.7.1.-', '1.-.-.-', '1.12.99.6;1.2.7.1;1.2.7.4;1.2.99.2', '1.-.-.-', '1.7.1.-', '1.7.1.-', '1.1.1.-;1.1.1.329', '1.1.1.-;1.1.1.329', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.14.12.-;1.14.12.24', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.1.1.-;1.1.1.329', '1.1.1.-;1.1.1.329', '1.1.1.335', '1.1.1.335', '1.1.1.349', '1.1.1.361', '1.1.1.361', '1.1.1.374', '1.1.1.374', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-', '1.1.1.393', '1.1.1.393', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.1.1.395', '1.1.1.395', '1.1.1.-;1.1.1.395', '1.1.1.-;1.1.1.395', '1.3.3.6', '1.1.1.35', '1.1.1.201', '1.1.1.201', '1.1.1.-;1.1.1.50;1.1.1.52', '1.1.1.-;1.1.1.50;1.1.1.52', '1.1.1.391', '1.1.1.391', '1.1.1.36', '1.1.1.-;1.1.1.393', '1.1.1.-;1.1.1.393', '1.1.1.35', '1.1.1;1.1.1.35', '1.1.1.145', '1.1.1.145', '1.1.1.35', '1.3.1.93', '1.3.1.93', '1.1.1.M19;1.1.1.n12', '1.1.1.330', '1.3.1.93', '1.1.1.330', '1.3.1.93', '1.1.1.M19', '1.1.1.M19', '1.1.1.101', '1.1.1.101', '1.1.1.201', '1.1.1.201', '1.1.1.330', '1.3.1.93', '1.1.1.330', '1.1.1.330', '1.3.1.93', '1.1.1.211', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.24', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.14.12.23', '1.1.1.330', '1.1.1.392', '1.1.1.392', '1.1.1.393', '1.1.1.393', '1.1.1.52', '1.1.1.52', '1.1.1.391', '1.1.1.391', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.52', '1.1.1.52', '1.1.1.391', '1.1.1.391', '1.1.1.392;1.1.1.50;1.1.1.52', '1.1.1.392;1.1.1.50;1.1.1.52', '1.1.1.392', '1.1.1.392', '1.1.1.393', '1.1.1.393', '1.1.1.393', '1.1.1.393', '1.1.1.35', '1.1.1.35', '1.1.1.35', '1.3.1', '1.3.1', '1.14.12.23', '1.7.1.16', '1.14.12.23', '1.14.12.23', '1.7.1', '1.7.1.16', '1.3.3.6', '1.1.1.159', '1.1.1.159', '1.1.1.239', '1.1.1.239', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.13.25', '1.14.13.25', '1.14.13.25', '1.1.1.146;1.1.1.159;1.1.1.50', '1.1.1.146;1.1.1.159;1.1.1.50', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.2.1.18', '3.2.1.18', '3.2.1.18', '1.14.-.-', '3.2.1.35', '3.2.1.35', '3.2.1.35', '1.1.1.211;1.1.1.35', '1.1.1.166;1.1.1.24;1.1.1.282', '1.1.1.166;1.1.1.24;1.1.1.282', '1.1.1.159;1.1.1.50', '1.1.1.159;1.1.1.50', '1.1.1.176', '1.1.1.176', '1.1.1.238', '1.1.1.238', '1.1.1.213;1.1.1.52', '1.1.1.213;1.1.1.52', '1.14', '1.14', '1.14', '1.14.13.36', '1.14.13.36', '1.14.13.36', '1.3.1.104;1.3.1.38;1.3.1.8', '1.1.1.35', '1.1.1.282', '1.1.1.282', '1.3.1.104;1.3.1.38;1.3.1.44;1.3.1.8', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.1.1.1;1.1.1.391', '1.1.1.1;1.1.1.391', '1.1.1.-;1.1.1.146;1.1.1.209;1.1.1.213;1.1.1.392;1.1.1.50', '1.1.1.-;1.1.1.146;1.1.1.209;1.1.1.213;1.1.1.392;1.1.1.50', '1.1.1;1.3.1.44', '1.1.1.159', '1.1.1.159', '1.1.1.-;1.1.1.M53', '1.1.1.-;1.1.1.M53', '1.3.99.-', '1.1.1.259;1.1.1.35', '1.3.99.3', '1.1.1;1.3.99.3', '1.3.1.9', '1.14.14.22;1.14.99.46', '1.1.1', '1.1.1.-', '1.1.1.100', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.1.1.36', '1.1.1.-', '1.1.1.-', '1.1.1.-', '1.7.1.-', '1.7.1.-', '1.1.1.-', '1.1.1.100', '1.3.3.6', '1.1.1.211;1.1.1.35', '1.1.1.211;1.1.1.35', '1.1.1.211;1.1.1.35', '1.1.1.211;1.1.1.35', '1.1.1.36', '1.1.1.36', '1.3.1.93', '1.1.1.35', '1.1.1.35', '1.3.3.6', '1.3.1.104;1.3.1.38;1.3.1.8', '1.1.1.211;1.1.1.35', '1.1.1.211;1.1.1.35', '1.1.1.211;1.1.1.35', '1.3.3.6;1.3.8.1;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6', '1.3.3.6', '1.14.14.8', '1.14.14.8', '1.14.14.8', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.3.1.10;1.3.1.38;1.3.1.8', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.3.3.6;1.3.99.-;1.3.99.13;1.3.99.3', '1.14.14', '1.14.14', '1.14.14', '1.1.1.211;1.1.1.35', '1.1.1.35', '1.1.1.395', '1.1.1.395', '1.1.1.35', '1.1.1.35', '1.1.1.35', '1.1.1.64', '1.1.1.64', '1.1.1.146', '1.1.1.146', '1.1.1.62', '1.1.1.62', '1.7.1.M3']
19
92
Nitrofurantoin
9

100%|██████████| 11047/11047 [00:08<00:00, 1337.85it/s]
100%|██████████| 27873/27873 [00:17<00:00, 1631.08it/s]
 86%|████████▌ | 50/58 [23:02<03:39, 27.38s/it]

rxndb num 198
failedrxn num 0
result_df 21
['3.5.1.94', '1.14.13.9', '1.14.13.9', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.29;1.14.13.n7', '1.14.13.29;1.14.13.n7', '6.3.2.1', '3.5.1.92', '3.5.2.4', '1.14.13.58', '1.14.13.58', '3.5.1.22', '6.3.2.23', '1.14.13.29', '1.14.13.29', '6.3.2.20', '3.5.2.14', '3.5.1.24;3.5.1.74', '1.7.1.9', '1.7.1.9', '3.5.1.24', '1.7.1.-;1.7.1.16', '1.14.13.-', '1.14.13.-', '1.-.-.-;1.7.1', '1.7.1.-', '1.-.-.-', '1.12.99.6;1.2.7.1;1.2.7.4;1.2.99.2', '1.-.-.-', '1.7.1.-', '1.7.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.1.1.1', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '6.3.2.36', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.5.1.-', '6.3.2.44', '6.3.4.24', '1.14.13.209', '1.14.13.209', '1.14.13.-', '1.14.-.-', '1.14.-.-', '6.3.2.18', '6.3.2;6.3.2.-', '6.3.2', '6.3.2', '3.5.2;3.5.2.2', '6.3.2', '3.4.13', '6.3.2', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2.M1', '6.3.2', '1.7.1.16', '1.7.1', '1.7.1.16', '3.5.1.115', '1.14.14.91', '1.14.14.91', '1.14.13', '1.14.13', '1.14.13.25', '1.14.13.25', '6.3.2.18', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.18', '3.2.1.18', '3.2.1.35', '3.2.1.35', '3.2.1.35', '3.5.1.-;3.5.1.78', '6.3.1.8;6.3.1.9', '3.5.1.24;3.5.1.74', '6.3.1.9', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '3.5.1.-', '1.14.13.11', '1.14.13.11', '6.3.1.13', '3.5.2;3.5.2.-', '6.3.1.10', '6.3.1.10', '3.5.1.90', '3.5.1.90', '6.3.2.56;6.3.2.ad', '1.14.14.22;1.14.99.46', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.2.1.14', '3.2.1.14', '3.4.15.6', '3.4.15.6', '3.4.15.6', '3.2.1.-', '3.2.1.-', '3.2.1.-', '1.7.1.-', '1.7.1.-', '6.3.2;6.3.2.-', '6.3.2', '6.3.2', '6.3.2', '6.3.2', '6.3.2', '6.3.2.37', '6.3.1.10', '6.3.2.58', '6.3.2.58', '3.5.1.115', '1.7.1.M3', '3.5.2.5']
22
73
Oxazepam
9

100%|██████████| 11047/11047 [00:08<00:00, 1375.61it/s]
100%|██████████| 27873/27873 [00:17<00:00, 1632.67it/s]
 88%|████████▊ | 51/58 [23:33<03:18, 28.39s/it]

rxndb num 748
failedrxn num 0
result_df 66
['3.1.3.15', '3.1.3.74', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '3.1.3.74', '3.1.3.73', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.1.3.39', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.1.3.40', '3.1.6.9', '3.1.6.10', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '3.8.1.7', '3.4.22.40;3.5.1.72', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.97.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '3.1.3.-;3.1.3.88', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '6.3.1.18', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.5.1.123', '3.1.3', '3.1.3.-', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13.44', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.19', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.5.1', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '1.14.13;1.14.13.20', '3.1.6.14', '3.1.3.29', '3.1.3.33;3.1.3.5', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '3.4.21.4;3.4.22;3.4.22.1', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.13.-', '1.14.13.-', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.15;3.2.1.82', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.1.3.91', '3.6.1;3.6.1.-', '3.1.3.2;3.1.3.31;3.1.3.34', '3.1.3.29', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.29', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.3.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.140', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '3.1.3.73', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.M8', '3.1.3.107', '3.1.3.105', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '1.14.13.9', '3.2.1.14', '3.1.3.29', '1.14.14.-', '1.3.98.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.140', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.14.19.58', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '3.1.3.-;3.1.3.104']
25
91
Paliperidone
9

100%|██████████| 11047/11047 [00:10<00:00, 1093.83it/s]
100%|██████████| 27873/27873 [00:18<00:00, 1539.15it/s]
 90%|████████▉ | 52/58 [24:06<02:58, 29.81s/it]

rxndb num 968
failedrxn num 0
result_df 43
['3.1.3.15', '3.1.3.74', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '1.14.13.-;1.14.14.-;1.14.14.1', '3.1.3;3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.3.31;3.1.3.5', '3.1.3.-;3.1.3.2;3.1.3.5;3.1.3.89', '3.1.3;3.1.3.31;3.1.3.35;3.1.3.5;3.1.3.89', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '3.1.5.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.-', '3.1.3.74', '3.1.3.74', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3.73', '3.1.6.2', '3.1.6.2', '3.1.6.2', '3.1.3.-;3.1.3.1;3.1.3.100;3.1.3.2', '3.1.3.39', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.6.9', '3.1.6.10', '1.1.1.234', '1.1.1.234', '1.17.1.3', '1.17.1.3', '1.1.1.234', '1.17.1.3', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.-;3.1.3.88', '1.1.1.349', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '3.1.3.-', '3.1.3;3.1.3.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3', '3.1.3.-', '3.1.6;3.1.6.-', '1.14.13', '1.14.13', '1.14.13', '1.3.1', '3.1.3', '3.1.3', '3.1.3', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.48', '3.1.3.34', '3.1.3.34', '3.1.3.2;3.1.3.34', '3.1.3.2;3.1.3.34', '1.1.1.362', '1.14.99', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1.348', '1.1.1.348', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '3.1.6.14', '3.1.3.29', '1.14.13;1.14.14', '3.1.3.33;3.1.3.5', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13', '1.14.13', '1.14.13', '3.1.3', '3.1.3', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '1.14.14.55', '3.1.3', '3.1.3', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.13.-', '3.8.1.7', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.15.6', '1.14.13.21', '2.7.1.59;3.2.1.14;4.1.3.3;4.2.1.66;5.1.3.8', '3.2.1.65', '3.2.1.49;3.2.1.52', '3.2.1.18', '3.2.1.35', '3.1.3.91', '3.6.1;3.6.1.-', '1.1.1.246;1.1.1.348', '3.1.3.2;3.1.3.31;3.1.3.34', '1.3.1;1.3.1.-', '3.1.3.29', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '3.1.3.2;3.1.3.31;3.1.3.5;3.1.3.89', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.14.1', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3.29', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '3.1.3.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '3.1.3.73', '1.1.1.219', '3.1.3', '3.6.1;3.6.1.-', '3.6.1;3.6.1.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.19.41;1.3.1.-', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.88', '3.1.3.M8', '3.1.3.105', '1.1.1.50', '3.2.1.14', '3.1.3.29', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '1.14.13.126', '3.4.15.6', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.13.99.3', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.99.-', '1.14.99.-', '1.14.-.-', '1.14.-.-', '1.-.-.-', '1.-.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.94', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.96', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.88', '1.14.13.176', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13.184', '1.14.13', '1.14.13', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3', '3.1.3.2;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.-;3.1.3.5', '3.1.3.5', '3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.2;3.1.3.5;3.1.3.91', '3.1.3;3.1.3.1;3.1.3.2;3.1.3.5', '3.1.5.1', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '1.14.13.98', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.6', '3.1.3;3.1.3.2;3.1.3.25;3.1.3.31;3.1.3.6', '3.1.3.2;3.1.3.31;3.1.3.6', '3.1.3.7;3.1.3.97', '3.1.3.7', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.3.1', '1.3.1.-', '1.13.99.3', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.13.97', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '2.6.1.114', '3.1.3.-', '3.1.3', '1.14.14', '1.14.14', '1.14.14', '3.1.3.-;3.1.3.102;3.1.3.2', '3.1.3.76', '3.1.3.-;3.1.3.104']
25
112
Prasugrel
9

100%|██████████| 11047/11047 [00:08<00:00, 1369.63it/s]
100%|██████████| 27873/27873 [00:17<00:00, 1576.25it/s]
 91%|█████████▏| 53/58 [24:37<02:31, 30.28s/it]

rxndb num 814
failedrxn num 0
result_df 60
['1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.10.3.1;1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.148', '1.1.1.148', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.13.58', '3.1.1.55', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.13.19', '1.14.13.19', '1.1.1;1.1.1.-', '1.1.1;1.1.1.-', '1.1.1.230', '1.1.1.230', '3.1.1.1;3.1.1.56', '1.1.1.62', '1.1.1.62', '1.1.1.62', '1.1.1.62', '1.1.1.146', '1.1.1.146', '1.1.1.53', '1.1.1.53', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.50', '1.1.1.53', '1.14.13.181', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '2.1.1.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1.239;1.1.1.62', '1.1.1.239;1.1.1.62', '1.1.1.213', '1.1.1.213', '1.1.1.62', '1.1.1.62', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.21.1.1;1.22.1.1', '1.1.1.335', '1.1.1.335', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.11.2.5', '1.1.1.374', '1.1.1.374', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.14.13.-;1.14.13.217', '1.1.1.393', '1.1.1.393', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.14.13.217', '1.1.1.-', '1.1.1.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '2.1.1.-', '1.1.1.395', '1.1.1.395', '1.1.1.-;1.1.1.395', '1.1.1.-;1.1.1.395', '1.1.1.201', '1.1.1.201', '1.1.1.-;1.1.1.50;1.1.1.52', '1.1.1.-;1.1.1.50;1.1.1.52', '1.1.1.391', '1.1.1.391', '1.1.1.-;1.1.1.393', '1.1.1.-;1.1.1.393', '1.1.1.145', '1.1.1.145', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.1.1', '1.1.1.201', '1.1.1.201', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.1.1', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M9', '1.1.1.392', '1.1.1.392', '1.1.1.393', '1.1.1.393', '1.1.1.52', '1.1.1.52', '1.1.1.391', '1.1.1.391', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.395', '1.1.1.52', '1.1.1.52', '1.1.1.391', '1.1.1.391', '1.1.1.392;1.1.1.50;1.1.1.52', '1.1.1.392;1.1.1.50;1.1.1.52', '1.1.1.392', '1.1.1.392', '1.1.1.393', '1.1.1.393', '1.1.1.393', '1.1.1.393', '1.1.1.-', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.2;1.1.1.213;1.1.1.239;1.1.1.62;1.3.1.20', '1.1.1;1.1.1.2;1.1.1.213;1.1.1.239;1.1.1.62;1.3.1.20', '1.1.1.159', '1.1.1.159', '1.1.1.1', '1.1.1.1', '1.1.1.149', '3.1.1.1;3.1.1.13', '1.1.1.239;1.1.1.51', '1.1.1.239;1.1.1.51', '1.1.1.239', '1.1.1.239', '1.1.1.184;1.1.1.2;1.1.1.62', '1.1.1.184;1.1.1.2;1.1.1.62', '1.1.1.213;1.1.1.50', '1.1.1.213;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.50', '3.1.1.13;3.1.1.2;3.1.1.3', '3.1.1.1', '1.1.1.209', '1.1.1.209', '3.1.1.1', '3.1.1.1', '3.1.1.1', '1.1.1.210;1.1.1.357', '1.1.1.210;1.1.1.357', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '3.1.1;3.1.1.1', '1.1.1.146;1.1.1.159;1.1.1.50', '1.1.1.146;1.1.1.159;1.1.1.50', '3.8.1.7', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.14.18.1', '1.1.1.146', '1.1.1.146', '3.4.11.5', '3.4.11.5', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '2.4.1.-', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1.210;1.1.1.239;1.1.1.357;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.209;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.2;1.1.1.209;1.1.1.21;1.1.1.213;1.1.1.50;1.3.1.20', '1.1.1;1.1.1.105;1.1.1.184;1.1.1.2;1.1.1.209;1.1.1.21;1.1.1.213;1.1.1.50;1.3.1.20', '1.14.13.30', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.14.14.1', '1.1.1;1.1.1.148;1.1.1.209', '1.1.1;1.1.1.148;1.1.1.209', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.1.1.159;1.1.1.50', '1.1.1.159;1.1.1.50', '1.1.1.176', '1.1.1.176', '1.1.1.206', '1.1.1.206', '1.1.1.236', '1.1.1.236', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.14.13.21;1.14.13.88', '1.1.1.238', '1.1.1.238', '1.14.13.74', '1.14.13.74', '1.1.1.146', '1.1.1.146', '1.1.1.213;1.1.1.52', '1.1.1.213;1.1.1.52', '1.1.1.152;1.1.1.184;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1.152;1.1.1.184;1.1.1.210;1.1.1.213;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1.184;1.1.1.209;1.1.1.213;1.1.1.50', '1.1.1.184;1.1.1.209;1.1.1.213;1.1.1.50', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.56', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.14.13.57', '1.1.1.50', '1.1.1.50', '1.1.1.209;1.1.1.50', '1.1.1.209;1.1.1.50', '1.1.1.213;1.1.1.50;1.1.1.51', '1.1.1.213;1.1.1.50;1.1.1.51', '1.1.1.149;1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.149;1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.74', '1.14.13.74', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.1.1.213;1.1.1.277;1.1.1.50', '1.1.1.213;1.1.1.277;1.1.1.50', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.53;1.14.13.89;1.14.14.90', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.209;1.1.1.213;1.1.1.357;1.1.1.50', '1.1.1.278', '1.1.1.278', '1.14.13.94', '1.14.13.94', '1.14.13.97', '1.14.13.97', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.-.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.11', '1.14.13.147', '1.14.13.147', '1.1.1.210;1.1.1.357;1.1.1.50;1.1.1.51', '1.1.1.210;1.1.1.357;1.1.1.50;1.1.1.51', '1.14.13.-', '1.14.13.-', '1.1.1.1;1.1.1.391', '1.1.1.1;1.1.1.391', '1.1.1.-;1.1.1.146;1.1.1.209;1.1.1.213;1.1.1.392;1.1.1.50', '1.1.1.-;1.1.1.146;1.1.1.209;1.1.1.213;1.1.1.392;1.1.1.50', '1.1.1.159', '1.1.1.159', '1.1.1.153', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.14.13.88', '1.1.1.-;1.1.1.M53', '1.1.1.-;1.1.1.M53', '1.14.13.88', '1.14.13.88', '1.1.1.201', '1.1.1.201', '1.1.1', '1.1.1', '1.1.1.64', '1.1.1.64', '3.2.1.87', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '1.14.13.89', '3.2.1.-', '3.2.1.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.21', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.15.5', '6.2.1.3', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.91', '1.14.13.94', '1.14.13.94', '1.1.1.-', '1.1.1.-', '1.14.13.88', '1.14.13.88', '1.14.13.194', '1.14.13', '3.2.1.143', '1.1.1.M51', '1.1.1.M51', '1.1.1.M51', '1.1.1.M51', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.1.1;1.1.1.51;1.1.1.62', '1.1.1;1.1.1.51;1.1.1.62', '1.1;1.1.1;1.1.1.209;1.1.1.213', '1.1;1.1.1;1.1.1.209;1.1.1.213', '1.1.1.1', '1.1.1.1', '1.1.99.13', '1.1.99.13', '1.17.99.5', '1.17.99.5', '1.14.13.97', '1.14.13.97', '1.17.99.5', '1.17.99.5', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '1.14.14', '3.6.1.18;3.6.1.9', '1.1.1.395', '1.1.1.395', '1.1.1.146', '1.1.1.146', '1.1.1.64', '1.1.1.64', '1.1.1.146', '1.1.1.146', '1.1.1.146', '1.1.1.146', '1.1.1.239', '1.1.1.239', '1.1.1.239', '1.1.1.239', '1.1.1.62', '1.1.1.62', '1.1.1.238', '1.1.1.238', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.11.2.6', '1.1.1.206', '1.1.1.206', '3.1.1.74']
21
106
Probenecid
9

100%|██████████| 11047/11047 [00:06<00:00, 1682.69it/s]
100%|██████████| 27873/27873 [00:16<00:00, 1682.06it/s]
 93%|█████████▎| 54/58 [25:06<01:59, 29.91s/it]

rxndb num 212
failedrxn num 0
result_df 19
['3.1.3.-', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.4', '3.1.3.27', '1.14.13.58', '1.14.13.58', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.14.-;1.14.14.1', '1.14.13.209', '1.14.13.209', '3.1.6;3.1.6.-', '1.1.1.415;1.1.1.ee', '3.1.3.4', '1.14.13', '1.14.13', '1.14.13', '1.14.14.91', '1.14.14.91', '1.2.1.3', '3.8.1.7', '3.8.1.7', '1.14.18.1', '1.14.18.1', '3.2.1.35', '3.2.1.35', '3.1.3.27', '1.14.13.71;1.14.14.102', '1.14.13.71;1.14.14.102', '1.14.13.73;1.14.14.103', '1.14.13.73;1.14.14.103', '1.14.13.97', '1.14.13.97', '1.14.13.11', '1.14.13.11', '3.1.3.73', '1.1.1.415', '3.4.19.7', '3.4.19.7', '3.1.3.27', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3.73', '3.1.3', '3.1.3.7', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '3.1.3.76']
10
30
Rifabutin
9

100%|██████████| 11047/11047 [00:14<00:00, 761.97it/s]
100%|██████████| 27873/27873 [00:18<00:00, 1537.35it/s]

rxndb num 3194
failedrxn num 0

 95%|█████████▍| 55/58 [25:44<01:36, 32.30s/it]

result_df 151

100%|██████████| 11047/11047 [00:09<00:00, 1197.76it/s]
100%|██████████| 27873/27873 [00:16<00:00, 1708.30it/s]
 97%|█████████▋| 56/58 [26:14<01:03, 31.52s/it]

rxndb num 93
failedrxn num 0
result_df 16
['1.14.14.1', '1.14.13.58', '1.14.13.58', '1.14.13.58', '1.14.12.14', '1.14.12.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.8.99.3;1.8.99.5', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.7.1.-', '1.14.13.209', '1.14.13.209', '1.14.13.209', '1.14.13', '1.14.13', '1.14.13', '3.8.1.7', '3.8.1.7', '3.2.1.35', '1.14.13.11', '1.14.13.11', '1.14.13.11', '2.6.1.114', '1.7.1.M3']
8
15
Ursodiol
9

100%|██████████| 11047/11047 [00:10<00:00, 1082.93it/s]
100%|██████████| 27873/27873 [00:20<00:00, 1390.11it/s]

rxndb num 4102
failedrxn num 0

 98%|█████████▊| 57/58 [26:49<00:32, 32.62s/it]

result_df 134

100%|██████████| 11047/11047 [00:06<00:00, 1642.34it/s]
100%|██████████| 27873/27873 [00:16<00:00, 1713.30it/s]
100%|██████████| 58/58 [27:17<00:00, 28.23s/it]

rxndb num 340
failedrxn num 0
result_df 22
['1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.14.1', '1.14.14.1;1.14.14.25;1.14.14.55;1.14.14.57', '1.14.13.100', '3.1.6.2', '3.1.6.2', '3.1.6.2', '1.14.14.-;1.14.14.1', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.100;1.14.14.29', '1.1.1.390', '3.1.6;3.1.6.-', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13', '1.14.13.M8', '1.1.1.-', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.13.-;1.14.13.M81', '1.14.14.1', '1.14.13.126;1.14.15.16', '1.14.13.126;1.14.15.16', '1.14.13.8;1.14.13.84', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14;1.14.14.1;1.14.14.25', '1.14.14.25', '1.14.14.25', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.1', '1.14.14.1', '3.1.3', '3.1.3', '1.14.14.55', '1.14.14.55', '1.14.14.1', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.4', '1.14.15.6', '1.14.15.6', '1.14.13.234', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.91', '1.14.14.25', '1.14.14.25', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.13.-;1.14.13.95;1.14.18.8', '1.14.14.23', '1.14.13.17', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.74', '1.14.13.79', '1.14.13.79', '1.14.13.94', '1.14.13.94', '1.14.13.97', '1.14.13.97', '1.14.13.-', '1.14.13.-', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.52;1.14.14.88', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.17', '1.14.13.147', '1.14.13.147', '3.1.3', '1.14.13;1.14.13.-', '1.14.13;1.14.13.-', '1.14.13.246', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.-;1.14.13.112', '1.14.13.126', '1.14.13.126', '1.14.13.99', '1.14.13.112', '1.14.13.112', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.70', '1.14.13.70', '1.14.13.72', '1.14.15.5', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.79', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.103', '1.14.13.94', '1.14.13.94', '1.14.13.72', '1.14.13.72', '1.14.13.72', '1.14.13.183', '1.14.13.183', '1.14.13.184', '1.14.13.184', '1.14.13.194', '1.14.14.1', '1.14.13.100;1.14.13.17;1.14.13.60', '1.14.13.32', '1.14.13.99', '1.14.13.98', '1.14.13.98', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.-', '1.14.13.122', '1.14.13.-;1.14.15.6', '1.14.13.-;1.14.15.6', '1.14.13.97', '1.14.13.97', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.12', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.14.14;1.14.14.-', '1.2.1']
8
53

In [28]:
rxndb

{'rxn1': {'EC number': '1.14.15.4',
  'rule': '[C:1]-[CH2;D2;+0:2]-[C:3].[O;H0;D1;+0:5]=[O;H0;D1;+0:4]>>[C:1]-[C@H;D3;+0:2](-[C:3])-[OH;D1;+0:4].[OH2;D0;+0:5]',
  'templateID': 'MNXR102250_reverse',
  'templateSubstrate': ['C[C@]12CC[C@H]3[C@@H](CCC4=CC(=O)CC[C@@]43C)[C@@H]1CC[C@@H]2C(=O)CO',
   'O=O'],
  'rxn_smiles_basic': 'CC1=C([C@H](O)C(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=O',
  'rxn_smiles_final': 'CC1=C([C@H](O)C(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O.NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)c1>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=O.[H+].NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1',
  'reactant_smile': 'CC1=C([C@H](O)C(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O',
  'productsmile': 'CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=O',
  'similarity': (0.3655913978494624, 0.3655913978494624, 1)},
 'rxn2': {'EC number': '1.14.15.4',
  'rule': '[C:1]-[CH2;D2;+0:2]-[C:3].[O;H0;D1;+0:5]=[O;H0;D1;+0:4]>>[C:1]-[C@H;D3;+0:2](-[C:3])-[OH;D1;+0:4].[OH2;D0;+0:5]',
  'templateID': 'MNXR102250_reverse',
  'templateSubstrate': ['C[C@]12CC[C@H]3[C@@H](CCC4=CC(=O)CC[C@@]43C)[C@@H]1CC[C@@H]2C(=O)CO',
   'O=O'],
  'rxn_smiles_basic': 'CC1=C([C@@H](O)C(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=O',
  'rxn_smiles_final': 'CC1=C([C@@H](O)C(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O.NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)c1>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=O.[H+].NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1',
  'reactant_smile': 'CC1=C([C@@H](O)C(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O',
  'productsmile': 'CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=O',
  'similarity': (0.3655913978494624, 0.3655913978494624, 1)},
 'rxn3': {'EC number': '1.14.15.4',
  'rule': '[C:1]-[CH2;D2;+0:2]-[C:3].[O;H0;D1;+0:4]=[O;H0;D1;+0:5]>>[C:1]-[C@@H;D3;+0:2](-[C:3])-[OH;D1;+0:4].[OH2;D0;+0:5]',
  'templateID': 'MNXR102251_reverse',
  'templateSubstrate': ['C[C@]12CC[C@H]3[C@@H](CCC4=CC(=O)CC[C@@]43C)[C@@H]1CC[C@]2(O)C(=O)CO',
   'O=O'],
  'rxn_smiles_basic': 'CC1=C([C@H](O)C(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=O',
  'rxn_smiles_final': 'CC1=C([C@H](O)C(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O.NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)c1>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=O.[H+].NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1',
  'reactant_smile': 'CC1=C([C@H](O)C(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O',
  'productsmile': 'CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=O',
  'similarity': (0.43010752688172044, 0.43010752688172044, 1)},
 'rxn4': {'EC number': '1.14.15.4',
  'rule': '[C:1]-[CH2;D2;+0:2]-[C:3].[O;H0;D1;+0:4]=[O;H0;D1;+0:5]>>[C:1]-[C@@H;D3;+0:2](-[C:3])-[OH;D1;+0:4].[OH2;D0;+0:5]',
  'templateID': 'MNXR102251_reverse',
  'templateSubstrate': ['C[C@]12CC[C@H]3[C@@H](CCC4=CC(=O)CC[C@@]43C)[C@@H]1CC[C@]2(O)C(=O)CO',
   'O=O'],
  'rxn_smiles_basic': 'CC1=C([C@@H](O)C(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=O',
  'rxn_smiles_final': 'CC1=C([C@@H](O)C(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O.NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)c1>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=O.[H+].NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1',
  'reactant_smile': 'CC1=C([C@@H](O)C(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O',
  'productsmile': 'CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=O',
  'similarity': (0.43010752688172044, 0.43010752688172044, 1)},
 'rxn5': {'EC number': '1.14.14.1',
  'rule': '[#8:1]-[C:2]-[CH2;D2;+0:3]-[C:4].[O;H0;D1;+0:5]=[O;H0;D1;+0:6]>>[#8:1]-[C:2]-[C@@H;D3;+0:3](-[C:4])-[OH;D1;+0:5].[OH2;D0;+0:6]',
  'templateID': 'MNXR102275',
  'templateSubstrate': ['CC(=O)O[C@H]1C(=O)[C@]2(C)[C@@H](O)C[C@H]3OC[C@@]3(OC(C)=O)[C@H]2[C@H](OC(=O)c2ccccc2)[C@]2(O)C[C@H](OC(=O)[C@H](O)[C@@H](NC(=O)c3ccccc3)c3ccccc3)C(C)=C1C2(C)C',
   'O=O'],
  'rxn_smiles_basic': 'CC1=C([C@@H](O)C(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=O',
  'rxn_smiles_final': 'CC1=C([C@@H](O)C(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O.NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)c1>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=O.[H+].NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1',
  'reactant_smile': 'CC1=C([C@@H](O)C(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O',
  'productsmile': 'CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=O',
  'similarity': (0.4895833333333333, 0.4895833333333333, 1)},
 'rxn6': {'EC number': '1.14.14.1;1.14.14.25;1.14.14.55;1.14.14.57',
  'rule': '[C:1]=[C:2]-[CH2;D2;+0:3]-[C:4].[O;H0;D1;+0:5]=[O;H0;D1;+0:6]>>[C:1]=[C:2]-[C@@H;D3;+0:3](-[C:4])-[OH;D1;+0:5].[OH2;D0;+0:6]',
  'templateID': 'MNXR102287_reverse',
  'templateSubstrate': ['C[C@]12CC[C@H]3[C@@H](CCC4=CC(=O)CC[C@@]43C)[C@@H]1CC[C@@H]2O',
   'O=O'],
  'rxn_smiles_basic': 'CC1=C([C@H](O)C(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=O',
  'rxn_smiles_final': 'CC1=C([C@H](O)C(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O.NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)c1>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=O.[H+].NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1',
  'reactant_smile': 'CC1=C([C@H](O)C(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O',
  'productsmile': 'CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=O',
  'similarity': (0.3448275862068966, 0.3448275862068966, 1)},
 'rxn7': {'EC number': '1.14.13.100',
  'rule': '[C:1]-[CH2;D2;+0:2]-[C:4]=[C:5].[O;H0;D1;+0:3]=[O;H0;D1;+0:6]>>[C:1]-[C@H;D3;+0:2](-[OH;D1;+0:3])-[C:4]=[C:5].[OH2;D0;+0:6]',
  'templateID': 'MNXR102295_reverse',
  'templateSubstrate': ['O=O',
   'C[C@H](CCCC(C)(C)O)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@@]21C'],
  'rxn_smiles_basic': 'CC1=C([C@@H](O)C(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=O',
  'rxn_smiles_final': 'CC1=C([C@@H](O)C(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O.NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)c1>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=O.[H+].NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1',
  'reactant_smile': 'CC1=C([C@@H](O)C(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O',
  'productsmile': 'CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=O',
  'similarity': (0.32786885245901637, 1, 0.34408602150537637)},
 'rxn8': {'EC number': '3.1.6.2',
  'rule': '[C:1]-[OH;D1;+0:2].[O-;H0;D1:7]-[S;H0;D4;+0:3](-[O;-;D1;H0:4])(=[O;D1;H0:5])=[O;D1;H0:6]>>[C:1]-[O;H0;D2;+0:2]-[S;H0;D4;+0:3](-[O;-;D1;H0:4])(=[O;D1;H0:5])=[O;D1;H0:6].[OH2;D0;+0:7]',
  'templateID': 'MNXR104605_reverse',
  'templateSubstrate': ['O=S(=O)([O-])[O-]',
   'C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](O)CC[C@@]43C)[C@@H]1CCC2=O'],
  'rxn_smiles_basic': 'CC1=C(CC(=O)OS(=O)(=O)[O-])c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=S(=O)([O-])[O-]',
  'rxn_smiles_final': 'CC1=C(CC(=O)OS(=O)(=O)[O-])c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=S(=O)([O-])[O-].[H+]',
  'reactant_smile': 'CC1=C(CC(=O)OS(=O)(=O)[O-])c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O',
  'productsmile': 'CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=S(=O)([O-])[O-]',
  'similarity': (0.3508771929824561, 1, 0.3508771929824561)},
 'rxn9': {'EC number': '3.1.6.2',
  'rule': '[C:1]-[OH;D1;+0:2].[O-;H0;D1:7]-[S;H0;D4;+0:3](-[O;-;D1;H0:4])(=[O;D1;H0:5])=[O;D1;H0:6]>>[C:1]-[O;H0;D2;+0:2]-[S;H0;D4;+0:3](-[O;-;D1;H0:4])(=[O;D1;H0:5])=[O;D1;H0:6].[OH2;D0;+0:7]',
  'templateID': 'MNXR104607_reverse',
  'templateSubstrate': ['O=S(=O)([O-])[O-]',
   'CC(C)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@@]21C'],
  'rxn_smiles_basic': 'CC1=C(CC(=O)OS(=O)(=O)[O-])c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=S(=O)([O-])[O-]',
  'rxn_smiles_final': 'CC1=C(CC(=O)OS(=O)(=O)[O-])c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=S(=O)([O-])[O-].[H+]',
  'reactant_smile': 'CC1=C(CC(=O)OS(=O)(=O)[O-])c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O',
  'productsmile': 'CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=S(=O)([O-])[O-]',
  'similarity': (0.3220338983050847, 1, 0.3220338983050847)},
 'rxn10': {'EC number': '3.1.6.2',
  'rule': '[C:1]-[OH;D1;+0:2].[O-;H0;D1:7]-[S;H0;D4;+0:3](-[O;-;D1;H0:4])(=[O;D1;H0:5])=[O;D1;H0:6]>>[C:1]-[O;H0;D2;+0:2]-[S;H0;D4;+0:3](-[O;-;D1;H0:4])(=[O;D1;H0:5])=[O;D1;H0:6].[OH2;D0;+0:7]',
  'templateID': 'MNXR104608_reverse',
  'templateSubstrate': ['O=S(=O)([O-])[O-]',
   'CC(=O)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C'],
  'rxn_smiles_basic': 'CC1=C(CC(=O)OS(=O)(=O)[O-])c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=S(=O)([O-])[O-]',
  'rxn_smiles_final': 'CC1=C(CC(=O)OS(=O)(=O)[O-])c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=S(=O)([O-])[O-].[H+]',
  'reactant_smile': 'CC1=C(CC(=O)OS(=O)(=O)[O-])c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O',
  'productsmile': 'CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=S(=O)([O-])[O-]',
  'similarity': (0.3448275862068966, 1, 0.3448275862068966)},
 'rxn11': {'EC number': '1.14.14.-;1.14.14.1',
  'rule': '[C:1]-[CH2;D2;+0:2]-[C:4]=[O;D1;H0:5].[O;H0;D1;+0:3]=[O;H0;D1;+0:6]>>[C:1]-[C@@H;D3;+0:2](-[OH;D1;+0:3])-[C:4]=[O;D1;H0:5].[OH2;D0;+0:6]',
  'templateID': 'MNXR108152_reverse',
  'templateSubstrate': ['C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](O)CC[C@@]43C)[C@@H]1CCC2=O',
   'O=O'],
  'rxn_smiles_basic': 'CC1=C([C@@H](O)C(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=O',
  'rxn_smiles_final': 'CC1=C([C@@H](O)C(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O.NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)c1>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=O.[H+].NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1',
  'reactant_smile': 'CC1=C([C@@H](O)C(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O',
  'productsmile': 'CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=O',
  'similarity': (0.3508771929824561, 0.3508771929824561, 1)},
 'rxn12': {'EC number': '3.1.1.51',
  'rule': '[C:1]-[C;H0;D3;+0:2](-[O-;H0;D1:6])=[O;D1;H0:3].[C:5]-[OH;D1;+0:4]>>[C:1]-[C;H0;D3;+0:2](=[O;D1;H0:3])-[O;H0;D2;+0:4]-[C:5].[OH2;D0;+0:6]',
  'templateID': 'MNXR108670_reverse',
  'templateSubstrate': ['CCCC(=O)[O-]',
   'CCCC(=O)O[C@@]12[C@H](O)[C@@H](C)[C@@]3(O)[C@@H](C=C(CO)C[C@]4(O)C(=O)C(C)=C[C@@H]34)[C@@H]1C2(C)C'],
  'rxn_smiles_basic': 'CC1=C(CC(=O)OC(=O)CCC(=O)C(=O)[O-])c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=C([O-])CCC(=O)C(=O)[O-]',
  'rxn_smiles_final': 'CC1=C(CC(=O)OC(=O)CCC(=O)C(=O)[O-])c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=C([O-])CCC(=O)C(=O)[O-].[H+]',
  'reactant_smile': 'CC1=C(CC(=O)OC(=O)CCC(=O)C(=O)[O-])c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O',
  'productsmile': 'CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=C([O-])CCC(=O)C(=O)[O-]',
  'similarity': (0.35294117647058826,
   0.5555555555555556,
   0.42105263157894735)},
 'rxn13': {'EC number': '3.1.1.51',
  'rule': '[C:1]-[C;H0;D3;+0:2](-[O-;H0;D1:6])=[O;D1;H0:3].[C:5]-[OH;D1;+0:4]>>[C:1]-[C;H0;D3;+0:2](=[O;D1;H0:3])-[O;H0;D2;+0:4]-[C:5].[OH2;D0;+0:6]',
  'templateID': 'MNXR108670_reverse',
  'templateSubstrate': ['CCCC(=O)[O-]',
   'CCCC(=O)O[C@@]12[C@H](O)[C@@H](C)[C@@]3(O)[C@@H](C=C(CO)C[C@]4(O)C(=O)C(C)=C[C@@H]34)[C@@H]1C2(C)C'],
  'rxn_smiles_basic': 'CC1=C(CC(=O)OC(=O)C(=O)CCC(=O)[O-])c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=C([O-])CCC(=O)C(=O)[O-]',
  'rxn_smiles_final': 'CC1=C(CC(=O)OC(=O)C(=O)CCC(=O)[O-])c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=C([O-])CCC(=O)C(=O)[O-].[H+]',
  'reactant_smile': 'CC1=C(CC(=O)OC(=O)C(=O)CCC(=O)[O-])c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O',
  'productsmile': 'CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.O=C([O-])CCC(=O)C(=O)[O-]',
  'similarity': (0.35294117647058826,
   0.5555555555555556,
   0.42105263157894735)},
 'rxn14': {'EC number': '2.1.1.329',
  'rule': '[C:5]-[S@@+;H0;D3:6](-[C:7])-[CH3;D1;+0:1].[c:3]:[cH;D2;+0:2]:[c:4]>>[CH3;D1;+0:1]-[c;H0;D3;+0:2](:[c:3]):[c:4].[C:5]-[S;H0;D2;+0:6]-[C:7]',
  'templateID': 'MNXR109275_reverse',
  'templateSubstrate': ['C[S@@+](CC[C@H]([NH3+])C(=O)[O-])C[C@H]1O[C@@H](n2cnc3c(N)ncnc32)[C@H](O)[C@@H]1O',
   'C/C(=C\\Cc1cc(O)c2ccccc2c1O)CCC[C@H](C)CCC[C@H](C)CCCC(C)C'],
  'rxn_smiles_basic': 'CC1=C(CC(=O)O)c2cc(F)cc(C)c2C1=Cc1ccc(S(C)=O)cc1.Nc1ncnc2c1ncn2[C@@H]1O[C@H](CSCC[C@H](N)C(=O)[O-])[C@@H](O)[C@H]1O>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.C[S+](CC[C@@H](C(=O)[O-])N)C[C@@H]1[C@H]([C@H]([C@@H](O1)N2C=NC3=C(N=CN=C32)N)O)O',
  'rxn_smiles_final': 'CC1=C(CC(=O)O)c2cc(F)cc(C)c2C1=Cc1ccc(S(C)=O)cc1.Nc1ncnc2c1ncn2[C@@H]1O[C@H](CSCC[C@H](N)C(=O)[O-])[C@@H](O)[C@H]1O.[H+]>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.C[S+](CC[C@@H](C(=O)[O-])N)C[C@@H]1[C@H]([C@H]([C@@H](O1)N2C=NC3=C(N=CN=C32)N)O)O',
  'reactant_smile': 'CC1=C(CC(=O)O)c2cc(F)cc(C)c2C1=Cc1ccc(S(C)=O)cc1.Nc1ncnc2c1ncn2[C@@H]1O[C@H](CSCC[C@H](N)C(=O)[O-])[C@@H](O)[C@H]1O',
  'productsmile': 'CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.C[S+](CC[C@@H](C(=O)[O-])N)C[C@@H]1[C@H]([C@H]([C@@H](O1)N2C=NC3=C(N=CN=C32)N)O)O',
  'similarity': (0.3389830508474576, 1.0, 0.3389830508474576)},
 'rxn15': {'EC number': '2.1.1.329',
  'rule': '[C:5]-[S@@+;H0;D3:6](-[C:7])-[CH3;D1;+0:1].[c:3]:[cH;D2;+0:2]:[c:4]>>[CH3;D1;+0:1]-[c;H0;D3;+0:2](:[c:3]):[c:4].[C:5]-[S;H0;D2;+0:6]-[C:7]',
  'templateID': 'MNXR109275_reverse',
  'templateSubstrate': ['C[S@@+](CC[C@H]([NH3+])C(=O)[O-])C[C@H]1O[C@@H](n2cnc3c(N)ncnc32)[C@H](O)[C@@H]1O',
   'C/C(=C\\Cc1cc(O)c2ccccc2c1O)CCC[C@H](C)CCC[C@H](C)CCCC(C)C'],
  'rxn_smiles_basic': 'CC1=C(CC(=O)O)c2cc(F)c(C)cc2C1=Cc1ccc(S(C)=O)cc1.Nc1ncnc2c1ncn2[C@@H]1O[C@H](CSCC[C@H](N)C(=O)[O-])[C@@H](O)[C@H]1O>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.C[S+](CC[C@@H](C(=O)[O-])N)C[C@@H]1[C@H]([C@H]([C@@H](O1)N2C=NC3=C(N=CN=C32)N)O)O',
  'rxn_smiles_final': 'CC1=C(CC(=O)O)c2cc(F)c(C)cc2C1=Cc1ccc(S(C)=O)cc1.Nc1ncnc2c1ncn2[C@@H]1O[C@H](CSCC[C@H](N)C(=O)[O-])[C@@H](O)[C@H]1O.[H+]>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.C[S+](CC[C@@H](C(=O)[O-])N)C[C@@H]1[C@H]([C@H]([C@@H](O1)N2C=NC3=C(N=CN=C32)N)O)O',
  'reactant_smile': 'CC1=C(CC(=O)O)c2cc(F)c(C)cc2C1=Cc1ccc(S(C)=O)cc1.Nc1ncnc2c1ncn2[C@@H]1O[C@H](CSCC[C@H](N)C(=O)[O-])[C@@H](O)[C@H]1O',
  'productsmile': 'CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.C[S+](CC[C@@H](C(=O)[O-])N)C[C@@H]1[C@H]([C@H]([C@@H](O1)N2C=NC3=C(N=CN=C32)N)O)O',
  'similarity': (0.3389830508474576, 1.0, 0.3389830508474576)},
 'rxn16': {'EC number': '2.1.1.329',
  'rule': '[C:5]-[S@@+;H0;D3:6](-[C:7])-[CH3;D1;+0:1].[c:3]:[cH;D2;+0:2]:[c:4]>>[CH3;D1;+0:1]-[c;H0;D3;+0:2](:[c:3]):[c:4].[C:5]-[S;H0;D2;+0:6]-[C:7]',
  'templateID': 'MNXR109275_reverse',
  'templateSubstrate': ['C[S@@+](CC[C@H]([NH3+])C(=O)[O-])C[C@H]1O[C@@H](n2cnc3c(N)ncnc32)[C@H](O)[C@@H]1O',
   'C/C(=C\\Cc1cc(O)c2ccccc2c1O)CCC[C@H](C)CCC[C@H](C)CCCC(C)C'],
  'rxn_smiles_basic': 'CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1C.Nc1ncnc2c1ncn2[C@@H]1O[C@H](CSCC[C@H](N)C(=O)[O-])[C@@H](O)[C@H]1O>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.C[S+](CC[C@@H](C(=O)[O-])N)C[C@@H]1[C@H]([C@H]([C@@H](O1)N2C=NC3=C(N=CN=C32)N)O)O',
  'rxn_smiles_final': 'CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1C.Nc1ncnc2c1ncn2[C@@H]1O[C@H](CSCC[C@H](N)C(=O)[O-])[C@@H](O)[C@H]1O.[H+]>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.C[S+](CC[C@@H](C(=O)[O-])N)C[C@@H]1[C@H]([C@H]([C@@H](O1)N2C=NC3=C(N=CN=C32)N)O)O',
  'reactant_smile': 'CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1C.Nc1ncnc2c1ncn2[C@@H]1O[C@H](CSCC[C@H](N)C(=O)[O-])[C@@H](O)[C@H]1O',
  'productsmile': 'CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.C[S+](CC[C@@H](C(=O)[O-])N)C[C@@H]1[C@H]([C@H]([C@@H](O1)N2C=NC3=C(N=CN=C32)N)O)O',
  'similarity': (0.3389830508474576, 1.0, 0.3389830508474576)},
 'rxn17': {'EC number': '2.1.1.329',
  'rule': '[C:5]-[S@@+;H0;D3:6](-[C:7])-[CH3;D1;+0:1].[c:3]:[cH;D2;+0:2]:[c:4]>>[CH3;D1;+0:1]-[c;H0;D3;+0:2](:[c:3]):[c:4].[C:5]-[S;H0;D2;+0:6]-[C:7]',
  'templateID': 'MNXR109275_reverse',
  'templateSubstrate': ['C[S@@+](CC[C@H]([NH3+])C(=O)[O-])C[C@H]1O[C@@H](n2cnc3c(N)ncnc32)[C@H](O)[C@@H]1O',
   'C/C(=C\\Cc1cc(O)c2ccccc2c1O)CCC[C@H](C)CCC[C@H](C)CCCC(C)C'],
  'rxn_smiles_basic': 'CC1=C(CC(=O)O)c2c(ccc(F)c2C)C1=Cc1ccc(S(C)=O)cc1.Nc1ncnc2c1ncn2[C@@H]1O[C@H](CSCC[C@H](N)C(=O)[O-])[C@@H](O)[C@H]1O>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.C[S+](CC[C@@H](C(=O)[O-])N)C[C@@H]1[C@H]([C@H]([C@@H](O1)N2C=NC3=C(N=CN=C32)N)O)O',
  'rxn_smiles_final': 'CC1=C(CC(=O)O)c2c(ccc(F)c2C)C1=Cc1ccc(S(C)=O)cc1.Nc1ncnc2c1ncn2[C@@H]1O[C@H](CSCC[C@H](N)C(=O)[O-])[C@@H](O)[C@H]1O.[H+]>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.C[S+](CC[C@@H](C(=O)[O-])N)C[C@@H]1[C@H]([C@H]([C@@H](O1)N2C=NC3=C(N=CN=C32)N)O)O',
  'reactant_smile': 'CC1=C(CC(=O)O)c2c(ccc(F)c2C)C1=Cc1ccc(S(C)=O)cc1.Nc1ncnc2c1ncn2[C@@H]1O[C@H](CSCC[C@H](N)C(=O)[O-])[C@@H](O)[C@H]1O',
  'productsmile': 'CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.C[S+](CC[C@@H](C(=O)[O-])N)C[C@@H]1[C@H]([C@H]([C@@H](O1)N2C=NC3=C(N=CN=C32)N)O)O',
  'similarity': (0.3389830508474576, 1.0, 0.3389830508474576)},
 'rxn18': {'EC number': '2.1.1.329',
  'rule': '[C:5]-[S@@+;H0;D3:6](-[C:7])-[CH3;D1;+0:1].[c:3]:[cH;D2;+0:2]:[c:4]>>[CH3;D1;+0:1]-[c;H0;D3;+0:2](:[c:3]):[c:4].[C:5]-[S;H0;D2;+0:6]-[C:7]',
  'templateID': 'MNXR109275_reverse',
  'templateSubstrate': ['C[S@@+](CC[C@H]([NH3+])C(=O)[O-])C[C@H]1O[C@@H](n2cnc3c(N)ncnc32)[C@H](O)[C@@H]1O',
   'C/C(=C\\Cc1cc(O)c2ccccc2c1O)CCC[C@H](C)CCC[C@H](C)CCCC(C)C'],
  'rxn_smiles_basic': 'CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)c(C)c1.Nc1ncnc2c1ncn2[C@@H]1O[C@H](CSCC[C@H](N)C(=O)[O-])[C@@H](O)[C@H]1O>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.C[S+](CC[C@@H](C(=O)[O-])N)C[C@@H]1[C@H]([C@H]([C@@H](O1)N2C=NC3=C(N=CN=C32)N)O)O',
  'rxn_smiles_final': 'CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)c(C)c1.Nc1ncnc2c1ncn2[C@@H]1O[C@H](CSCC[C@H](N)C(=O)[O-])[C@@H](O)[C@H]1O.[H+]>>CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.C[S+](CC[C@@H](C(=O)[O-])N)C[C@@H]1[C@H]([C@H]([C@@H](O1)N2C=NC3=C(N=CN=C32)N)O)O',
  'reactant_smile': 'CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)c(C)c1.Nc1ncnc2c1ncn2[C@@H]1O[C@H](CSCC[C@H](N)C(=O)[O-])[C@@H](O)[C@H]1O',
  'productsmile': 'CC1=C(CC(=O)O)c2cc(F)ccc2C1=Cc1ccc(S(C)=O)cc1.C[S+](CC[C@@H](C(=O)[O-])N)C[C@@H]1[C@H]([C@H]([C@@H](O1)N2C=NC3=C(N=CN=C32)N)O)O',
  'similarity': (0.3389830508474576, 1.0, 0.3389830508474576)},
 'rxn19': {'EC number': '2.1.1.285',

In [29]:
result_num_df = pd.DataFrame(result_num)
result_num_df['ec3_list'] = result_num_df['ec3_list'].apply(lambda x:ast.literal_eval(x))
result_num_df['ec3_list'] = result_num_df['ec3_list'].apply(lambda x:[ec for ec in x if '-' not in ec])
result_num_df['ec3_num'] = result_num_df['ec3_list'].apply(lambda x:len(x))

result_num_df['ec4_list'] = result_num_df['ec4_list'].apply(lambda x:ast.literal_eval(x))
result_num_df['ec4_list'] = result_num_df['ec4_list'].apply(lambda x:[ec for ec in x if '-' not in ec])
result_num_df['ec4_num'] = result_num_df['ec4_list'].apply(lambda x:len(x))

result_num_df

,drug_name,reaction_num,ec4_num,ec4_list,ec3_num,ec3_list
0,Nicardipine·HCl,58,66,"[1.2.7.1, 1.14.14.102, 1.7.1.9, 3.8.1.7, 3.1.1...",24,"[1.2.7, 1.12.99, 1.2.99, 2.3.1, 1.14.18, 1.7.1..."
1,Risperidone,24,26,"[1.14.14.102, 3.8.1.7, 1.14.13.91, 1.14.13.97,...",6,"[3.2.1, 2.6.1, 1.14.18, 1.14.13, 3.8.1, 1.14.14]"
2,Tolcapone,89,106,"[1.7.1.9, 3.8.1.7, 1.14.13.n7, 1.14.13.219, 1....",32,"[1.2.7, 1.12.99, 1.2.99, 1.10.3, 2.6.1, 1.14.1..."
3,Azathioprine,15,16,"[1.2.7.1, 1.7.1.9, 3.8.1.7, 1.14.99.46, 1.12.9...",11,"[1.2.7, 1.12.99, 1.2.99, 1.17.5, 1.14.99, 1.14..."
4,Entacapone,42,66,"[1.2.7.1, 1.14.14.102, 1.7.1.9, 3.8.1.7, 3.1.3...",21,"[1.2.7, 1.12.99, 1.2.99, 1.14.18, 1.11.2, 1.7...."
5,Exemestane,99,173,"[1.3.1.3, 1.1.1.323, 1.3.1.115, 1.14.18.8, 1.1...",18,"[1.2.1, 1.14.18, 1.3.1, 1.14.21, 1.3.3, 1.14.1..."
6,Nimodipine,53,73,"[1.7.1.9, 3.8.1.7, 1.14.13.n7, 1.14.15.5, 1.7....",24,"[1.2.7, 1.12.99, 1.2.99, 2.3.1, 1.14.18, 1.7.1..."
7,Capsaicin,76,232,"[3.2.1.60, 1.14.13.159, 3.8.1.7, 1.14.18.8, 6....",43,"[1.10.3, 2.4.1, 1.14.18, 3.4.13, 1.11.2, 3.4.1..."
8,Dexamethasone,123,430,"[1.1.1.138, 1.1.1.414, 3.1.3.50, 1.14.15.5, 1....",34,"[2.4.1, 1.2.1, 1.14.18, 1.3.1, 3.1.1, 1.11.1, ..."
9,Ethacrynic Acid,55,235,"[3.2.1.60, 1.1.1.360, 1.14.18.8, 1.2.1, 3.1.3....",31,"[2.4.1, 1.2.1, 1.14.18, 1.11.2, 1.3.1, 1.6.5, ..."
10,Rifampin (Rifampicin),146,285,"[3.2.1.60, 3.8.1.7, 1.14.18.8, 1.14.13.n7, 3.2...",46,"[1.10.3, 2.4.1, 2.3.1, 2.6.1, 1.14.18, 3.4.15,..."
11,Sulindac,22,49,"[1.14.13.84, 1.14.13.183, 1.14.18.8, 1.2.1, 1....",8,"[1.2.1, 1.14.14, 1.14.15, 3.1.6, 1.1.1, 1.14.1..."
12,Vorinostat,59,84,"[1.14.14.30, 3.8.1.7, 1.14.13.n7, 1.14.13.M66,...",33,"[1.10.3, 1.14.18, 3.4.15, 1.11.2, 1.3.1, 3.1.1..."
13,Dolasetron,66,121,"[3.8.1.7, 1.1.1.230, 1.1.1.395, 1.1.1.64, 1.17...",28,"[1.10.3, 1.14.18, 3.4.15, 1.11.2, 1.3.1, 6.2.1..."
14,Mycophenolate mofetil,88,221,"[3.2.1.60, 3.8.1.7, 1.1.1.360, 1.14.18.8, 1.14...",41,"[2.4.1, 1.2.1, 2.3.1, 2.6.1, 1.14.18, 1.11.2, ..."
15,Zidovudine (3'-Azido-3'-Deoxythymidine),32,152,"[3.2.1.60, 3.8.1.7, 3.1.3.97, 1.14.15.5, 3.2.1...",26,"[2.4.1, 5.4.99, 2.6.1, 3.4.15, 6.2.1, 1.11.1, ..."
16,Allopurinol,5,5,"[1.14.13.235, 3.8.1.7, 1.14.13.224, 1.17.1.4, ...",3,"[1.17.1, 3.8.1, 1.14.13]"
17,Betamethasone,123,430,"[1.1.1.138, 1.1.1.414, 3.1.3.50, 1.14.15.5, 1....",34,"[2.4.1, 1.2.1, 1.14.18, 1.3.1, 3.1.1, 1.11.1, ..."
18,Bisacodyl,67,125,"[1.14.13.10, 1.1.1.360, 1.14.13.n7, 1.14.13.21...",27,"[1.10.3, 2.4.1, 1.2.1, 1.14.18, 1.11.2, 1.2.3,..."
19,Estradiol,83,240,"[3.2.1.60, 3.8.1.7, 1.1.1.323, 1.14.18.8, 1.14...",28,"[1.10.3, 2.8.2, 2.4.1, 1.14.18, 1.11.2, 1.3.1,..."
20,Famciclovir,29,59,"[3.8.1.7, 1.1.1.2, 3.5.4.15, 3.5.4.42, 1.14.13...",24,"[6.3.5, 2.3.1, 3.4.15, 1.2.3, 1.3.1, 1.7.1, 6...."
21,Flutamide,30,43,"[1.2.7.1, 3.5.1.123, 1.7.1.9, 3.4.11.3, 3.4.11...",21,"[1.2.7, 1.12.99, 1.2.99, 5.4.99, 1.7.1, 3.1.1,..."
22,Hydrocortisone,160,447,"[1.1.1.138, 1.1.1.414, 3.1.3.50, 1.14.15.5, 1....",38,"[2.4.1, 1.2.1, 1.14.18, 1.3.1, 3.1.1, 1.11.1, ..."
23,Hydrocortisone Acetate,167,441,"[1.1.1.138, 1.1.1.414, 3.1.3.50, 1.14.15.5, 1....",41,"[2.4.1, 2.3.1, 1.14.18, 1.3.1, 6.2.1, 3.1.1, 1..."
24,Methylprednisolone,128,439,"[1.1.1.138, 1.1.1.414, 3.1.3.50, 1.14.15.5, 1....",36,"[2.4.1, 1.2.1, 1.14.18, 1.3.1, 3.1.1, 1.11.1, ..."
25,Metronidazole,22,57,"[1.2.7.1, 3.1.3.2, 1.7.1.9, 3.1.3.33, 1.1.1.31...",18,"[1.2.7, 1.12.99, 1.2.99, 2.6.1, 3.4.15, 4.99.1..."
26,Nabumetone,77,154,"[1.1.1.323, 1.1.1.352, 1.14.18.8, 1.14.13.219,...",24,"[1.10.3, 2.4.1, 1.2.1, 1.14.18, 1.11.2, 1.3.1,..."
27,Pantoprazole,39,49,"[1.14.14.102, 3.8.1.7, 5.1.3.8, 1.14.13.91, 1....",17,"[2.4.1, 4.2.1, 3.2.1, 2.1.1, 6.2.1, 1.14.14, 2..."
28,Prednisolone,137,453,"[1.1.1.138, 1.1.1.414, 3.1.3.50, 1.14.15.5, 1....",37,"[2.4.1, 1.2.1, 1.14.18, 1.3.1, 3.1.1, 1.11.1, ..."
29,Progesterone,133,171,"[1.3.1.3, 1.1.1.323, 1.3.1.115, 1.1.1.352, 1.1...",19,"[1.2.1, 1.14.18, 1.3.1, 5.3.3, 1.14.13, 1.1.3,..."
30,Prednisone,147,457,"[1.1.1.138, 1.1.1.414, 3.1.3.50, 1.14.15.5, 1....",38,"[2.4.1, 1.2.1, 1.14.18, 1.3.1, 3.1.1, 1.11.1, ..."
31,Spironolactone,157,267,"[1.3.1.3, 1.1.1.323, 6.2.1.41, 1.3.1.115, 1.14...",29,"[1.2.1, 2.3.1, 1.14.18, 1.3.1, 6.2.1, 3.1.1, 2..."
32,Sulfasalazine,76,93,"[3.8.1.7, 1.14.13.10, 1.14.13.n7, 3.1.3.97, 1....",19,"[1.2.1, 1.14.18, 1.11.2, 1.7.1, 3.1.1, 4.1.3, ..."
33,Tinidazole,12,14,"[1.2.7.1, 1.7.1.9, 1.7.1.M3, 1.14.99.46, 1.2.7...",9,"[1.2.7, 1.12.99, 1.2.99, 3.2.1, 2.6.1, 1.14.13..."
34,Fluoxetine·HCl,36,44,"[1.14.14.102, 3.8.1.7, 1.14.13.183, 1.14.18.8,...",13,"[1.10.3, 1.14.3, 1.4.3, 1.22.1, 1.14.14, 1.17...."
35,Misoprostol,186,388,"[1.1.1.138, 1.1.1.414, 3.1.3.50, 1.14.15.5, 1....",43,"[2.4.1, 2.3.1, 5.3.99, 1.14.18, 1.3.1, 6.2.1, ..."
36,Megestrol Acetate,144,227,"[1.3.1.3, 1.1.1.323, 1.3.1.115, 1.1.1.352, 1.1...",27,"[2.3.1, 1.14.18, 1.3.1, 6.2.1, 3.1.1, 1.3.3, 1..."
37,Capecitabine,64,220,"[3.2.1.60, 3.8.1.7, 3.1.3.97, 1.14.15.5, 1.1.1...",35,"[2.4.1, 5.4.99, 3.4.15, 1.3.1, 6.2.1, 3.1.1, 1..."
38,Chenodiol (Chenodeoxycholic Acid),134,299,"[1.1.1.414, 1.14.15.5, 1.1.1.69, 4.2.1.140, 3....",32,"[2.4.1, 1.2.1, 1.14.18, 1.3.1, 3.1.1, 1.11.1, ..."
39,Clofazimine,40,20,"[1.14.14.102, 3.8.1.7, 1.14.13.91, 1.14.13.58,...",8,"[1.3.98, 1.14.19, 1.14.14, 1.14.13, 1.14.18, 1..."
40,Clonazepam,51,51,"[1.2.7.1, 3.5.1.123, 1.7.1.9, 3.8.1.7, 3.4.11....",24,"[1.2.7, 1.12.99, 1.2.99, 1.14.18, 3.4.15, 1.7...."
41,Cortisone Acetate,180,432,"[1.1.1.138, 1.1.1.414, 3.1.3.50, 1.14.15.5, 1....",41,"[2.4.1, 2.3.1, 1.14.18, 1.3.1, 6.2.1, 3.1.1, 1..."
42,Dantrolene·Na,28,37,"[1.2.7.1, 1.7.1.9, 3.8.1.7, 3.2.1.18, 1.14.99....",15,"[1.2.7, 1.12.99, 1.2.99, 4.2.1, 3.2.1, 1.14.14..."
43,Duloxetine,67,51,"[1.14.14.102, 3.8.1.7, 1.14.13.183, 1.14.13.91...",15,"[1.10.3, 1.14.3, 1.4.3, 2.4.1, 6.2.1, 1.22.1, ..."
44,Fludrocortisone Acetate,163,420,"[1.1.1.138, 1.1.1.414, 3.1.3.50, 1.14.15.5, 1....",39,"[2.4.1, 2.3.1, 1.14.18, 1.3.1, 6.2.1, 3.1.1, 1..."
45,Iloperidone,52,65,"[1.1.1.50, 1.14.14.102, 3.8.1.7, 5.1.3.8, 3.2....",21,"[2.4.1, 1.14.18, 1.3.1, 6.2.1, 3.3.2, 2.1.1, 4..."
46,Lorazepam,74,83,"[3.8.1.7, 3.1.3.97, 1.14.13.44, 1.14.13.140, 4...",24,"[1.10.3, 1.14.18, 1.11.2, 1.97.1, 1.3.98, 1.22..."
47,Nilutamide,28,33,"[1.2.7.1, 1.7.1.9, 3.8.1.7, 3.2.1.18, 1.14.99....",15,"[1.2.7, 1.12.99, 1.2.99, 4.2.1, 3.2.1, 1.14.14..."
48,Nitisinone,37,85,"[1.7.1.9, 3.8.1.7, 1.14.13.n7, 1.14.14.8, 1.1....",17,"[1.2.7, 1.12.99, 1.2.99, 1.3.1, 1.7.1, 1.3.3, ..."
49,Nitrofurantoin,21,64,"[1.2.7.1, 1.7.1.9, 6.3.2.44, 3.5.1.74, 3.2.1.1...",20,"[1.2.7, 1.12.99, 1.2.99, 3.4.13, 3.4.15, 1.7.1..."
50,Oxazepam,66,83,"[3.8.1.7, 3.1.3.97, 1.14.13.44, 1.14.13.140, 4...",24,"[1.10.3, 1.14.18, 1.11.2, 1.97.1, 1.3.98, 1.22..."
51,Paliperidone,43,102,"[3.8.1.7, 1.14.18.8, 3.1.3.97, 1.1.1.348, 1.1....",23,"[2.6.1, 1.13.99, 1.14.18, 3.4.15, 1.11.2, 1.3...."
52,Prasugrel,60,99,"[3.8.1.7, 1.1.1.230, 1.14.15.5, 1.1.1.395, 1.1...",20,"[1.10.3, 2.4.1, 1.14.18, 1.11.2, 1.3.1, 6.2.1,..."
53,Probenecid,19,26,"[1.14.14.102, 3.8.1.7, 3.4.19.7, 1.1.1.ee, 1.1...",10,"[3.2.1, 1.2.1, 1.14.13, 3.1.6, 1.1.1, 1.14.18,..."
54,Rifabutin,151,308,"[1.14.13.159, 1.14.15.5, 3.2.1.91, 3.1.3.4, 1....",46,"[2.4.1, 2.3.1, 2.6.1, 1.14.18, 3.4.15, 1.11.2,..."
55,Sulfamethoxazole,16,12,"[1.8.99.3, 3.8.1.7, 1.7.1.M3, 1.14.12.14, 3.2....",8,"[3.2.1, 1.14.14, 2.6.1, 1.14.13, 1.8.99, 3.8.1..."
56,Ursodiol,134,299,"[1.1.1.414, 1.14.15.5, 1.1.1.69, 4.2.1.140, 3....",32,"[2.4.1, 1.2.1, 1.14.18, 1.3.1, 3.1.1, 1.11.1, ..."
57,Sulindac,22,49,"[1.14.13.84, 1.14.13.183, 1.14.18.8, 1.2.1, 1....",8,"[1.2.1, 1.14.14, 1.14.15, 3.1.6, 1.1.1, 1.14.1..."

In [30]:
result_num_df.to_csv('../../Results/ref2_drug_deg_result_filter.csv',index=None)